Version 2 of Stallionboi by Fuxi begins here.
[ Originally Authored by Sarokcat n Verarh]
[ Version 2 - Expansion of defeat scenes by Fuxi. Coding done by Prometheus]

"Adds a Stallionboi to Flexible Survival's Wandering Monsters table, with impreg chance"

Section 1 - Creature Responses

to say Stallionboi wins:
	project the Figure of Stallionboi_hard_icon;
	if vorelevel > 2 and glowing mushroom is owned:
		if a random number between 1 and 3 is:
			-- 1:
				say "[StalloinBoiCockVore]";
			-- 2:
				say "[StallionBoiNewOral]";
			-- 3:
				say "[StallionGroupSex]";
	else:
		if a random number between 1 and 2 is:
		-- 1:
			say "[StallionBoiNewOral]";
		-- 2:
			say "[StallionGroupSex]";

to say StalloinBoiCockVore:
	say "     Falling to the ground, you let out a mixed groan of arousal and pain, succumbing at last to the stallionboi's unusual fighting style. Your supplies fall alongside you, spilling along the floor around you and attracting the horse's attention. One of those objects rolling right toward the femme horse is a glowing green mushroom. 'Hmm, what's this? Looks tasty,' The femboy curiously says as he picks up the growing fungi and examines it, pressing his muzzle against it and sniffing it inquisitively. Remembering where you first happen upon the mushroom and any of your own experience using it, you glance hopefully up at the equine, anticipation bubbling up as you see him open his mouth slightly and close his eyes like he's about to take a nibble. Still, before he does, he looks down at you again, catching your open disappointment that he's stopped. 'Why the long face? Is there something special about this mushroom I should know about?' the girly horse questions you grinning, 'I'm not just some cum guzzling bimbo. Y'know, anybody could tell there was something strange about this mushroom. I mean, c'mon, it literally glows!' he exclaims, and you just scowl back at him. 'Well, it looks like you won't tell me, so I'll just have to find out another way,' the stallionboi states and moves toward you, mushroom clutched in hand.";
	say "     At first, you don't understand what his intentions are, head still hazy with lust, but when the little stud leans down to grab you, one hand on your chin, thumb poking open your mouth, you realize what his intentions are and futilely struggle to get away from the stallionboi as he brings the glowing shroom closer to your mouth, and after a bit of time succeeds in shoving the anomalous food in your maw. 'Don't make this any more difficult than it has to be now. You wouldn't want to upset me now, would you?' the stallionboi questions you sweetly, holding your mouth shut and forcing you to chew up the glowing fungi, much to your dismay. When you've finished your forced meal, the femboy stands back again, watching you closely as he waits to see what effect the glowing vegetable has on you, which comes in almost immediately. Right away, you can feel yourself growing smaller and weaker, any clothes you're wearing growing looser around your body until soon you've sunken below even 1 foot in height, so small and helpless that even a house cat would pose a significant danger to you much less a now comparatively ginormous stallionboi who is currently gawking at you in complete shock at your drastic transformation.";
	WaitLineBreak;
	say "     'Oh my god! You look so! SO CUTE!' The femme horse squeals with excitement as he barrels toward you, making the ground tremor beneath your tiny feet as he grabs you easily, scooping you up into one hand and spinning you around, making you yelp and strain hopelessly to get the boi to let you go kicking and screaming in terror and outrage at what he's down to you. 'Oh, sorry about that. You're just so adorable, like a weak little doll!' the stallionboi shouts, clearly enjoying your new small form immensely. Gradually, though, as his excitement cools down and he refocuses on your helpless body, his eyes are no longer filled with glee but predatory lust. 'There's been something I've wanted to try for a while now, and I think I've found the most precious volunteer to assist me out,' The stallionboi says, grinning and pulling down his thong slightly revealing a large and thick equine cock 'Now I'm not just a cum guzzling whore, but I'm still a whore nonetheless one of a whole herd! And do you know what whores talk about? Sex! And lots of it,' the girly lad explains to you as he brings you closer to his throbbing tool. 'A friend told me about an encounter he had with an extraordinarily hung horseman, and ever since then, I've been curious about all kinds of things you're going to help me experience.'";
	say "     The stallionboi finishes his sentence and brings you right up to the head of his dick, making you flail about as you attempt to push yourself away, only making the femboy groan slightly in pleasure as your feet patter against his sensitive cockhead as you lash out, you feel them sink into something soft and wet making the stallionboi's soft groans morph into a gasp. You're feet have sunk right in his urethra! 'Oh, yessss, this feels even better than I imagined!' the short stud hisses in pleasure, bringing you up again before forcing you back down fucking his cock with your legs. You can feel his pre soaking your lower body, sticking to you as his cock contracts around you, sucking you deeper and splattering more pre on you, proof of the stallion boi's arousal along with his moans and grunts, and he uses you to a little more than a living sounding rod. As this continues, you start to sink deeper until your midsection is subsumed into the boi's prick as well, and it forces you to grip onto the edges of the horse's shaft to desperately keep yourself from sinking any further. 'Everything you do is so sweet. Even your struggle is just precious! I can feel your feet kicking against my walls, scraping against me. God, it feels amazing! I need more!' the stallionboi whines out in euphoria.";
	WaitLineBreak;
	say "     Quickly, he pulls you back up again, removing your grip before shoving you back down, forcing your arms inside him, and removing the last safety net you had, preventing your complete consumption. Indeed, that's exactly what follows next. The flexing walls of the femme stud's cock slowly pull you in. Before long, only your head lays out in the open, letting you look pleadingly up at your attacker, who offers no mercy, pushing you down completely into him with one finger. The inside of the horseboi's cock is humid, musky, and tight. His dick contracts around you sporadically when his pleasure rises, wringing you tightly and shooting pre-up to douse your little body and inundate you in the salty smell of equine arousal that wafts from all around you, strangely arousing you even in your dire circumstances. Slick and soaking wet with pre, you start sliding further down the stallionboi's shaft, gasping for breath as you reach a particular tight point in your journey. For a moment, you dare to hope it's all over and that you can go no further into the femboy, but all of a sudden, the contractions grow even stronger, and the tides of precum even larger as you feel something from the outside press down on you all this coinciding with louder moans from the outside stallionboi. That bastard must be masturbating! He's jerking off with you trapped inside him!";
	say "     The extra suction and lubrication shatter any hopes that your journey has ended and sends you straight into a pool of cum, making you realize you've ended up in the stallionboi's balls. Your new circumstances are just as unfortunate as your last. Jostled around in the equine's sack, spunk pours all over you and forces you to gulp down whatever lands in your mouth so you may gasp for breath in the unrelenting tide. Looks like the hooved whore is also playing with his nuts if your shaky conditions are anything to go by, and it's making your time bathing in his seed anything but peaceful as you're thrown around inside of him. More concerningly, the amount of jizz is only increasing. And yet, you're no longer panicked. Perhaps it's the nanites, trauma, or nothing but arousal, but either way, you've stopped struggling. In the beginning, you tried your hardest to escape, but seeing that time and time again, your efforts were in vain; This time, you don't fight the waves or try to avoid swallowing cum. You embrace it wantonly, moaning as you writhe in the stallionboi's ballsack, gurgling cum and more horny than perhaps you'd ever been in your life. You even climax, adding your cum to the studs supply and intermixing your fluids with his own.";
	WaitLineBreak;
	say "     As sperm fills the stallionboi's sack to the brim and you're left with little space, you're not afraid, too lost in cum-drunk delight to care. Some part of you maybe even craves to become just more seed for the femme horse, but right as you're about to sink, the equine's moans reach a crescendo. You're launched out of him alongside a deluge of spunk, splattering on a nearby wall and sliding down shamefully but uninjured. 'Whoops, sorry there, little fella, I might've gotten a little carried away.' Your attacker kneels to speak with you, giving you a light poke to see if you're alright, to which you respond with a needy groan, 'Heh, looks like you enjoyed yourself anyway. Well, thanks for helping me volunteer. Hope to see you soon!' the stallionboi cheerfully bids you farewell, giving you a parting kiss and lick, leaving you to wallow in a puddle of seed until you eventually regain your proper size and enough energy to recollect your items, then move onwards one glowing mushroom shorter than before.";
	ItemLoss glowing mushroom by 1;

to say StallionBoiNewOral:
	say "     Falling to the ground, you let out a mixed cry of arousal and pain, succumbing at last to the stallionboi's unusual fighting style. Walking up to you, the whore's hooves clack against the ground, and when you open your eyes again, he's standing above you, his mottled horsecock hanging over your head, making you groan in annoyance. 'You already know how these battles work, sugar. Don't make things any harder than they need to be,' the equine says smugly and shucks off his thong, throwing the musky garment onto your face. Before you can shake off the garment, you briefly sample the scent of his arousal, which you're sure to be getting much more closely acquainted with soon. 'Alright, get to work now. Don't be a sore loser; start with your hands. I'm in the mood for something more slow-paced today,' the stallionboi directs you sweetly, and you reluctantly rise to your knees, sore, horny, and irritated that a flouncy femboy like this has defeated you. Gripping his considerable shaft with both hands, you slowly masturbate the victorious horse.";
	say "     You keep a somewhat dispassionate pace for a while, steadily stroking your attacker's cock in your hands while glaring up at the grinning and moaning stallionboi with open hostility. 'You'd be so much prettier if you smiled more. You know, if you were a proper whore you'd never pick up any clients looking like such a stick in the mud!' The slutty equine teasingly chides you, but you refuse to dignify him with a response, merely scowling and forcing your gaze downwards to focus on the task at hand. Trying to end your humiliation as fast as possible, you pick up the pace and put more technique into working the femme horse's prick, and after a while, find your emotions begin to change with your focus from anger and shame at your loss to a fascination with throbbing horsecock in your grasp. The little equine may be a femboy, but that doesn't make him any less a stud. You can feel the stallionboi's pulse beating through his dick, each twitch in your grasp, sending another dribble of pre down the slut's blunt cockhead and his shaft to further lubricate his manhood and soak your hands. When you start to play with the opening of the boi's and edges of his spongy glans, he loudly moans and shoots a large string of pre right across your face!";
	WaitLineBreak;
	say "     Unconsciously, you lick your lips and receive your first real taste of the Stallionboi's liquid lust, sending a shiver down your spine. He tastes amazing. Sugary and slightly savory, like salted caramel, you can feel yourself drooling with desire as you unconsciously push your face closer to the stud's leaky tool. 'Did I say we could move onto that yet?' your attacker says cheekily and pulls his manhood away from you, to your extreme embarrassment as you realize your libido and cocklust had overwhelmed you to the point you hadn't even realized you were leaning closer hoping to cop another taste of the stallionboi's salty-sweet precum. 'Y'know, even though you lost, I might be persuaded to let you have your way if you beg me,' the femme equine says sweetly. You are ashamed to say you managed to hold back for hardly even a minute before you break quietly, whimpering to the whore that you want to taste him. 'What that? I didn't hear you. I guess you must not want anything,' the whore teasingly says while fondling himself above you and letting a little drop of his desire trickle down on your face warning you of what you stand to lose, so you force yourself to get a little louder, squirming in desperation. 'Louder!' the skinny slut shouts, and you lose all restraint yelling loudly to please be allowed the privilege to service the slut stud to gurgle his seed and choke on that massive spire of horse meat.";
	say "     'That's all you had to say,' the stallionboi smugly proclaims, grinning mischievously down at you as he promptly shoves his prick into your mouth. While begging, you felt almost as if you might die of humiliation at your whorish actions and the sheer need you felt. Still, the moment that thick cock pushes into you, everything is pushed out to make room, crushed under the taste and smell of musky horse dick. You force yourself to hold your breath and take even more of that magnificent pole into you until it's taken all the space in your mouth, bulging your cheeks. He rams into your throat, bulging out your neck, but you don't even care. You don't attempt to pull back but instead try your best to choke down even more turgid equine meat, swallowing around it and using your throat muscles to milk it further. All the while, the stallionboi is moaning loudly moaning and complimenting your BJ skills, calling you a naturally born slut. Then he starts to withdraw from you, slowly pulling inch after inch of saliva-soaked cock from you until nothing but the tip rests on your tongue,  all while you fruitlessly chase after his dick trying to sheath it back inside of you, held back only by the femboy's surprisingly firm grip until all of a sudden nearly 15 inches of dick is slammed back into you, making your throat spasm all around the invading horse meat, much to the stallionboi's obvious enjoyment.";
	WaitLineBreak;
	say "     This stables slut continued to slam fuck your throat recklessly, using and abusing you like you're little more than a disposable fleshlight. At the same time, you gag and drool messily around his length, eventually though all good things must come to an end, and so with a victorious whiny, the stallionboi climaxes unleading what must be gallons of cum in your throat down your stomach. You can feel his balls pushing against your skin, each hard clench sending another rope of gooey cum to bloat your belly, and at the moment, the only regret you have is that you don't get to taste any, only getting a paltry sample of the equine's detectable seed when he exits entirely from you and drags in virility-soaked tool from your wrecked mouth and unintentionally smears his cum across your tastebuds. 'Man, you sure look like you had fun! I recognize that look anywhere. I could probably tell you to lick my cock and balls clean, and you'd do it without a second thought!' the stallionboi jokes, but you don't perceive it instead already moving to start doing exactly as your enemy said you would to go clean him surpassing his expectations as you didn't even have to be commanded to try and give the full service to him. 'Woah there! Down, boy, as much as I'd love to play with you all day, I still have work and sex to have with paying clients. So goodbye for now, but rest assured I'll be back.' The sexy equine rejects your advances in a remarkable display of self-control and then quickly runs out on you, leaving you alone to recover from the brutal facefucking.";
	CreatureSexAftermath "Player" receives "OralCock" from "Stallionboi";

to say StallionGroupSex:
	if Player is female:
		say "     The slutty stallionboi gives a rather girlish squeal of glee as you finally give up your futile attempt at resisting the strange horseboi's assault. 'We are going to make such a pretty little stallionslut out of you!' He gushes happily, as he grabs your arms and practically drags you through the halls with a lusty smirk on his face, his sexy black horselike tail swishing eagerly in front of you as he drags you along. Catching your breath slightly, you try to open your mouth to protest your rough handling only to stumble as he stops in front of a door and throws it open wide. You get a confused glimpse of several equine heads turning in your direction as he shoves you inside, his call of 'Boys, we got a new playtoy!' fills your ears for a second, before the sound of loud partially equine squealing drowns out anything else.";
		say "     You gasp and try to struggle as a large number of the vaguely feminine stallionbois descend eagerly on your already aroused body, their hands groping and stroking you all over even as the aroused musk of a roomful of horny equines washes over you. Unable to resist their advances, you find yourself moaning wantonly as they begin to tease and play with your body, rubbing their thick erect equine cocks up against you as you find yourself hauled down onto the bed. It isn't long before they have those wonderful equine members buried in your all too eager body either, causing you to moan helplessly around the equine rod filling your mouth as your increasingly sex crazed body is filled by the strangely sexy beasts. Before long you find yourself losing track of anything but the hands stroking and playing with your overstimulated body, and the thick horsemeat rubbing up against you, or plunging into your all too eager holes.";
		WaitLineBreak;
		say "     Completely losing track of how many times you are taken by the sexy male slutbois, or in how many ways, your pussy and ass are stuffed throughout the night by who knows how many different partners. Eventually you find yourself orgasming for the final time, and are carried away into unconsciousness on a wave of sexual bliss, your body still being used by the many sexy equines the entire time. When you wake up you find yourself still in the same room, though someone took time to move you off to a more comfortable position on the side of the room. Looking around, you see the room is filled with the bodies of a number of those exhausted little slut stallions, most of them passed out still in a pile or holding each other close, the strange orgy obviously having continued long after you passed out.";
		say "     The scent of sex and equines fills the air, causing you to moan slightly as your well used body tries to respond in the way they were training it too, your pussy clenching eagerly as your lust to experience more of that wonderful pleasure begins to grow between your legs. Fortunately you still manage to retain just enough willpower to take the opportunity to slip out the door while they are all unconscious, staggering drunkenly back towards the entrance to this crazy and sensual place even while still covered with their seed and smelling of sex.";
	else:
		say "     The slutty stallionboi gives a rather girlish squeal of glee as you finally give up your futile attempt at resisting the strange horseboi's assault. 'We are going to make such a pretty little stallionslut out of you!' He gushes happily, as he grabs your arms and practically drags you through the halls with a lusty smirk on his face, his sexy black horselike tail swishing eagerly in front of you as he drags you along. Catching your breath slightly, you try to open your mouth to protest your rough handling only to stumble as he stops in front of a door and throws it open wide. You get a confused glimpse of several equine heads turning in your direction as he shoves you inside, his call of 'Boys, we got a new playtoy!' fills your ears for a second, before the sound of loud partially equine squealing drowns out anything else.";
		say "     You gasp and try to struggle as a large number of the vaguely feminine stallionbois descend eagerly on your already aroused body, their hands groping and stroking you all over even as the aroused musk of a roomful of horny equines washes over you. Unable to resist their advances, you find yourself moaning wantonly as they begin to tease and play with your body, rubbing their thick erect equine cocks up against you as you find yourself hauled down onto the bed. It isn't long before they have those wonderful equine members buried in your all too eager body either, causing you to moan helplessly around the equine rod filling your mouth as your increasingly sex crazed body is filled by the strangely sexy beasts. Before long you find yourself losing track of anything but the hands stroking and playing with your overstimulated body, and the thick horsemeat rubbing up against you, or plunging into your all too eager holes.";
		WaitLineBreak;
		say "     Completely lose track of how many times you are taken by the sexy male slutbois, or in how many ways, your mouth and ass are stuffed throughout the night by who knows how many different partners, even while your own [Cock of Player] rod is lavished with attention again and again, as they wring orgasm after orgasm out of you. Eventually you find yourself orgasming for the final time, and are carried away into unconsciousness on a wave of sexual bliss, your body still being used by the many sexy equines the entire time. When you wake up you find yourself still in the same room, though someone took time to move you off to a more comfortable position on the side of the room. Looking around, you see the room is filled with the bodies of a number of those exhausted little slut stallions, most of them passed out still in a pile or holding each other close, the strange orgy obviously having continued long after you passed out.";
		say "     The scent of sex and equines fills the air, causing you to moan slightly as your well used body tries to respond in the way they were training it too, your cock twitching as it tries to revive itself for another round, even as your lust to experience more of that wonderful pleasure begins to grow between your legs. Fortunately you still manage to retain just enough willpower to take the opportunity to slip out the door while they are all unconscious, staggering drunkenly back towards the entrance to this crazy and sensual place even while still covered with their seed and smelling of sex.";
	CreatureSexAftermath "Player" receives "PussyFuck" from "Stallionboi";
	CreatureSexAftermath "Player" receives "AssFuck" from "Stallionboi";
	CreatureSexAftermath "Player" receives "PussyFuck" from "Stallionboi";
	CreatureSexAftermath "Player" receives "AssFuck" from "Stallionboi";

To say Stallionboi loses:
	project the Figure of Stallionboi_clothed_icon;
	if Player is Male:
		say "     Falling to his knees with a loud oomph, the stallionboi glances up at you with a strange mixture of fear, lust, and admiration whirling in his eyes. Though the girly boy is afraid of getting any more of a beating from you, his infected mind can't help but feel a depraved attraction towards his betters. He'll snap out of his trance soon enough. If you want to take advantage of him, you better do it quickly.";
		say "     [bold type]Do you want to put him in his place?[roman type][line break]";
		let StallionBoi_Victory_Choices be a list of text;
		add "No, let him go." to StallionBoi_Victory_Choices;
		if Cock Length of Player < 8:
			add "Fuck his cock slit." to StallionBoi_Victory_Choices;
		add "Make use of his long equine muzzle." to StallionBoi_Victory_Choices;
		add "Fuck his ass." to StallionBoi_Victory_Choices;
		let StallionBoi_Victory_Choice be what the player chooses from StallionBoi_Victory_Choices;
		if StallionBoi_Victory_Choice is:
			-- "No, let him go.":
				LineBreak;
				say "     You decide you're not in the mood to ravage the sexy little stallionboi and turn to leave, breaking the femboy out of his reverie for a minute; you swear he almost looks disappointed at your decision but, in the end, he decides to scamper off before you can change your mind.";
			-- "Fuck his cock slit.":
				LineBreak;
				say "     Walking up to the beaten stallionboi, you see him tense up, preparing to make a break for it, but you're already hauling him up to his feet to face you. Ow, ow, ow! Let go of me, you big meanie! I was just trying to have fun, and you've beaten me black and blue, you brute! What are you some type of sadist like those Donkeywomen? the femboy whines and complains as you move him, clearly quite upset at your earlier harsh treatment, although he was the one who attacked you in the first place, grabbing that equines still dribbling flared cock, however, quickly silences those complaints. Typical boys like him are rather short-sighted in the end. Mmmm, that feels good. Rub the tip a little bit more, please? Well, it seems like you wanna make it up to me, big guy, so I guess I'll let things slide and stick around, the stallionboi says breathily, almost immediately forgiving you and deciding to play along with your desires. Still, it's not like he had much choice in the first place either way.";
				say "     For what you have in mind, you'll want the slutty little stud to be nice and horny, so you decide to spend a good while continuing to stroke his pulsing equine arousal while groping his body, loosening the grip you had on the stallionboi's shoulder to keep him in place, you bring it down to his ass instead groping and kneading at the bottom boy's soft round cheeks and occasionally slapping his butt now and again enjoying the way it jiggles each time and the loud gasps and needy moans you draw from the stallionboi each time further needed evidence of his obvious arousal is the increased flow of pre from his dick you're still massaging with your other hand. Despite his earlier outrage at your attacks, it seems the whore gets off quite a bit on being smacked. With your other hand, you shift your focus from stroking his dick to rubbing his cocktip and smearing the sticky and thick pre that leaks from the equine all over the entrance to his shaft in preparation for what is to come.";
				WaitLineBreak;
				say "     You carry on like this for quite some time before suddenly stopping, drawing a needy whine from the squirming stallionboi. C'mon, why'd you stop? I was so close! he says petulantly, looking at you with adorable begging eyes that probably have most guys tripping over themselves, eager to please the feminine stud. You remain resolute in your goals, though, and firmly order him to stand in front of you, slapping away his hands when he dares to reach for his arousal to finish himself off. Left with little choice if he wants to get his rocks off, the stallionboi obeys, uneasily shifting as he tries to resist the need to ease his aching balls. You reward him with a quick little rub up and down his manhood before moving back to his flared head to claim your true prize. C'mon, this is torture! Just stop teasing me already. I need, PleauSSeuh! the whore tries to beg you, but you cut him off before he can finish.";
				say "     Carefully you've insert one finger into the stallionboi's penis slit. His reaction is immediate, begging, cutting off almost instantaneously while his knees shake with the effort to keep standing and, more importantly, pleasurable sensation. You can feel his dick suckling around your finger, and you can feel the pre lubing up his walls. Judging by the tightness, he's also a virgin in this hole, a rarity for a whore, and a guess he confirms moments later. Oh, God, that feels amazing. Nobody's ever been inside there before. You're not supposed to be inside there! the stallionboi gasps and writhes, forcing you to grasp his shoulder again to still him so he doesn't accidentally dislodge you. You'd expected the slut to fight you more but were completely subverted in your expectation. The stallionboi seems to be enjoying himself to an extraordinary degree, you humping against your fingers desperately, and so soon you add another into his urethra, to his extreme enthusiasm, thoroughly prepping the equine for what comes next.";
				WaitLineBreak;
				say "     Still, despite his immense enjoyment, the stallionboi hasn't achieved orgasm, but from the looks of it, your fingering has him quickly approaching climax, which leaves him looking heartbroken when you stop touching him, looking at once betrayed, annoyed, and sad as you pull your fingers from his cock with a slight slurp and pop. Why'd you stooop? he whines petulantly, bemoaning the loss of your digits, to which your only response is a grin as you promise he'll enjoy what comes next much more and tell him to stand up straight and come closer, commands the hypersexual femboy quickly follow. Reaching out for the equine meat again and firmly grasping it while also pushing your arousal against his, the stallionboi seems excited at this, happy to be frotting with you but also slightly disappointed seeing this as a de-escalation of the previous act.";
				say "     His expression turns into something more questioning as instead of starting to frot with him; you aline yourself with the opening of his prick, a look of confusion that rapidly switches to realization and then ecstasy as you waste no further time in sheathing yourself into his cock. You have to bring up your arms to support the stallionboi as, this time, his legs do give out, and he nearly collapses due to the novel sensations you're letting him experience, drooling and loudly moaning all the while. And as for you, the floozy's urethra is everything you could wish for a wonderful, tight, wet, and warm hole perfect for you to fuck, just as good as his ass or mouth even if the stallionboi's not as experienced in using this hole, that just makes it even tighter. Not wanting to hurt your boy toy, you start slow and steady, grinding in deeply and thrusting in and out gently as you enjoy the equine's spasming insides squeezing and trying futilely to push your intruding cock out.";
				WaitLineBreak;
				say "     And the stallionboi's on cloud nine, gripping your shoulders tightly and resting his head against your shoulders to keep standing, making him moan and whiny right into your ears while he kisses and licks your neck to even further stroke the fires of your lust, making you speed up your cock-fucking. You groan raggedly, knowing your orgasm is coming soon by the familiar tightness in your balls. You wanted this encounter to last longer, but it looks like your body has other ideas. Jet ends up pushing you over the edge is the stallionboi's orgasm, his pleasure reaching a crescendo. He mauls your neck with sloppy kisses to muffle his screams of satisfaction as he cums, bathing your shaft in the warm sticky fluid and further lubricating your thrusts as you grind yourself deep inside his member and blow your load inside the equine whore. For a minute, you both stand there panting, coming down from the high of orgasm, and you feel a surge of affection towards the stallionboi in your current blissful state. Noting how tired he looks, you pull the feminine stud to rest alongside a wall with you, and when he's soundly asleep, head off again to continue your adventures content in your momentary lover's comfort.";
			-- "Make use of his long equine muzzle.":
				LineBreak;
				say "     Walking up to the beaten stallionboi, you see him tense up, preparing to make a break for it, but you've already got a rough hand tangled in his long hair, making him wince in discomfort as you tug him toward you by his mane. Whimpering in fear equine whore looks up at you with pleading eyes expecting the worse after attacking you. Luckily for him, though you're not interested in giving the stallionboi the beating he rightfully deserves, on the contrary, you're sure what you crave will be quite fulfilling for the both of you. Kneeling like this, the femboy is right at crotch height, and you waste no more time making your desires clear by pushing his snout right against your balls and giving one clear command to the helpless male: sniff, Huff in your musk deeply. A command he's quick to follow.";
				say "     Loosening your grip on the stalliknboi, you let him get more acquainted with your scent, pushing his nose to your scrotum and under to inhale your musky male fragrance and the sweat that clings to you. He tries to go further, giving a quick kiss to your sack and letting his tongue poke out to provide you with a quick lick, sampling the taste of your body, but you quickly put a stop to that. You plan to savor this conquest with no use letting such an experienced whore rush through things. It is much better to enjoy his talents slowly. The stallionboi, moving on from your balls, pushes his nose upward, grinding it against the underside of your shaft to tease you before he reaches the head of your cock and gives that a long sniff, too, his actions coaxing a droplet of pre to splash over his sensitive sniffer. By now, you have noticed something quite amusing: the feminine equine's eyes have gone half-lidded. His hypersexual nature has completely taken over, with the previous fear having disappeared and replaced with a hazy lust and hunger.";
				WaitLineBreak;
				say "     Deciding to tease the defeated whore a little longer, your trace your prick against the stallionboi's lips. You can see him struggle to restrain himself, remembering your previous command and knowing that you haven't given him permission to do anything but sniff as of yet. He chews his lip, and that pleading look returns to his face, although for a far different reason now. Chuckling slightly, you decide to show your boy toy a little mercy, pushing him down to your balls again; you tell the Stallionboi to show you how much he loves them, something he takes to with immense zeal. Kissing and licking your sack like they're a longtime lover, the subby equine worships your family jewels, sucking both orbs into his mouth and swirling his tongue around them, polishing them with his saliva and moaning all the while looking up at you almost adoringly for giving him the privilege to service you, getting particularly adventurous sometimes he'll take a break to stick that broad equine tongue under your nuts and deliver a very well received lick to your perineum making you squirm in place. You can't help but feel a bit of envy towards the horsemen that guard this place for having such dedicated and gifted sluts around to use whenever they wish.";
				say "     Enjoying your ball worship for a while more, letting the stallionboi show you all his tricks before you decide to move into the main course. Pulling him up by his hair again, you force the femboy to focus on your dick but notice that he seems reluctant to begin despite the apparent desperation in his eyes, then chuckle as you realize you haven't given your plaything permission ah, well, you're sure he'll get the hint next anyway you think to yourself commanding the stallionboi to open his mouth and then promptly shoving your cock to the hilt into him. It's like a switch flips in the girly lad the second he realizes he has you're okay as he responds with the same voracious lust and service he gave your balls, slobbering and moaning around your shaft as he deepthroats you shoving his snout right against your pubes and holding himself there letting you relish in the way his throat squeezes your [Cock of Player] meat, the stallionboi repeats this several times practically choking himself out with your dick as he deepthroast you then rising and panting sluttily with his tongue hanging out barely even giving himself to catch his breath before he's back to kissing and slurping at your rod.";
				WaitLineBreak;
				say "     The stallionboi's hands, too, are never idle, constantly stroking your thighs or playing with your balls, giving them an expert massage as he tries to coax you into working up a fat load for him to swallow. As the blowjob goes on and your pleasure steadily rises, the stallionboi changes his tactics and, instead of slowly letting you plunder his throat, switches to much more aggressively bobbing his head on your dick loudly, drooling and moaning around you, the equine harlot's makeup running slightly and hair messy with eh effort he puts into blowing you, and god if it isn't an effect give turn on! He's certainly good at what he does, that's for sure. All too soon, you feel your pleasure bubbling over, and so with a loud groan, you force the stallionboi to sheath you one last time as you empty your balls down his throat, then pull out to shoot the final couple strings of your seed over his face to which your slut cheerfully responds by opening his mouth to catch your seed.";
				say "     Having gotten what you wanted, you leave the stallionboi to lie on the floor, exhausted from servicing you. Quickly, you scamper off to continue your adventures, already looking forward to beating down the next stallionboi that crosses paths with you.";
				CreatureSexAftermath "Stallionboi" receives "OralCock" from "Player";
			-- "Fuck his ass.":
				LineBreak;
				say "     Walking up to the beaten stallionboi, you see him tense up, preparing to make a break for it, but you've already got a rough hand tangled in his long hair, making him wince in discomfort as you tug him toward you by his mane. Whimpering in fear equine whore looks up at you with pleading eyes expecting the worse after attacking you. Luckily for him, though you're not interested in giving your attacker the beating he rightfully deserves, on the contrary, you're sure what you crave will be quite fulfilling for the both of you. Keeping a grip on his glossy mane, you force the stallionboi to follow you and press his hands against a wall, then command him to hold his position, a command the cowed horse does nothing to resist, though you notice he's shaking slightly in fear, and make a note to yourself to treat him more gently.";
				say "     In the position you have the stallionboi, you have an excellent view of him, and it especially enhances his backside, forcing him to stick his out for your pleasure rather than go right for the main prize. However, you decide to start slowly, gently running your fingers through the stallionboi's silky hair, then run your hands along his back and give him a gentle rub, which works to calm down the skittish stud, his shake disappearing under your relaxing touch. Truthfully, it's pretty relaxing for you, too, running your hands through the equine's soft hair and coat and rubbing his back and neck muscles. Eventually, you must move on through, and so you start with the stallionboi's thighs and push yourself closer until your crotch is rubbing right against the stallionboi's ass. You're able to ever so slowly and ever so gently grind against him.";
				WaitLineBreak;
				say "     Your intentions are crystal clear now, but you note with some delight this time that the stallionboi does not shake or cower away from you now quite the opposite; in fact, it's subtle, but as you knead his soft and girly thighs, giving one a soft spank and curling up right to the sides of his cheeks you feel the stallionboi grinding lightly against your hard arousal. You keep playing with the femboy thoughts for quite some time, but eventually, you decide to move on again to massage a much more sensitive part of the equine, his dripping cock. Having gotten quite excited by all your touching, the horse's erection is hard as a rock and completely soaked through his undersized thong, which you slowly pull off, leaving his dick wholly exposed as well as his ass, your prick pushing between the stallionboi's soft buns, but still you're not ready to claim him just yet. Bringing a hand to the feminine lad's cock you start to slowly stroke him.";
				say "     You continue this for quite some time until the stallionboi's hovering right at the edge of orgasm, your hand having transitioned from stroking his dick to gently rubbing his cocktip edging the feminine lad slowly, and right when you feel him about to burst, you pull your hand away and slather your pulsing meat with the gathered pre-cum, and taking advantage of the stallionboi's lust addled state push yourself into him. His insides are all that you wanted, and his puffy equine pucker grips you snugly despite his evident experience. Even if his hole isn't exactly tight from all its use, it's very well trained, squeezing rhythmically and almost suckling on your cock. And besides that, the horse boy just has a lovely bubbly, ass perfect for groping and spanking as you plunder his hole.";
				WaitLineBreak;
				say "     Your patience has worn thin from all the foreplay, and from the sounds the stallionboi is making, he isn't interested in going slow and steady. He wants to get fucked. More than fucked he wants to be ravaged, and you're more than happy to oblige. Withdrawing until almost nothing but the head of your dick lays clutched by the whore's needy donut, you push all of yourself in again in a single harsh thrust pounding right against the stallionboi's prostate, making him wail out in euphoria at your harsh treatment. Despite his earlier fear, you know that the stallionboi is conditioned to enjoy rough sex. You know how the horsemen operate around here. They certainly aren't gentle. Now that he knows you're not going to just beat him, he's quite into it. Neither of you is going to last long the play stripped away all patience and left you both too worked up for that, so it comes as no surprise when the stallionboi climaxes quite quickly, spraying his seed all over the wall while his hole spasms around you driving you to climax as well your balls rising tight as you flood his bowels with your seed.";
				say "     You both slump to the floor, a sweaty tangle of limbs lost in the afterglow of climax exchanging light almost loving kisses and murmured words of affection. It's hard to bring yourself to move on, but you know you'll have to eventually. Rising shakily to your feet, you leave the stallionboi to rest as you continue your exploration.";
				CreatureSexAftermath "Stallionboi" receives "AssFuck" from "Player";
	else if Player is Female:
		say "     Driven back by your powerful assault, the stallionboi groans with pain as he staggers backwards and shoots you a rather dirty and sexy look, before bursting into tears as he says '[one of]Well you didn't have to be so mean!'[or]Maybe you will be more fun next time sexy,'[or]Why don't you want to fuck me?'[or]Damn sweetie, that's a little rough for me, maybe you should try one of the donkeys,'[at random] before staggering off down the corridor, shooting you a last teasing glance over his shoulder as he does so.";

Section 2 - Creature Insertion

to say Stallionboi_Desc:
	say "     Wandering through the building you encounter a horny stallionboi. You see that he is wearing black silk stockings and a skimpy tight black thong that isn't hiding his fully equine manhood. His look is finished off with long black silk gloves and black choker collar around his neck. The stallionboi has a slender almost girlish figure. His human body is starting to sprout dark chocolate colored fur, a long black horsetail flicks eagerly behind him. His face is stretched out into a slender, feminine half equine muzzle and his ears are more equine than human. His dark hair is shoulder length with bright blue frosted tips. Giving you a slutty grin, he strides towards you and says, 'You are going to look so hot when I get done with you!'";

Table of CombatPrep (continued)
name(text)	PrepFunction(text)
"Stallionboi"	"[PrepCombat_Stallionboi]"

to say PrepCombat_Stallionboi:
	project the Figure of Stallionboi_clothed_icon;
	setmongender 3;

Table of Random Critters (continued)
NewTypeInfection (truth state)	Species Name	Name	Enemy Title	Enemy Name	Enemy Type	Attack	Defeated	Victory	Desc	Face	Body	Skin	Tail	Cock	Face Change	Body Change	Skin Change	Ass Change	Cock Change	str	dex	sta	per	int	cha	sex	HP	lev	wdam	area	Cock Count	Cock Length	Ball Size	Nipple Count	Breast Size	Male Breast Size	Cunt Count	Cunt Depth	Cunt Tightness	SeductionImmune	Libido	Loot	Lootchance	TrophyFunction	MilkItem	CumItem	Scale (number)	Body Descriptor (text)	Type (text)	Magic (truth state)	Resbypass (truth state)	non-infectious (truth state)	Cross-Infection (text)	DayCycle	Altcombat (text)	BannedStatus (truth state)
--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--;

When Play begins:
	Choose a blank row from Table of Random Critters;
	now NewTypeInfection entry is false;
	now Species Name entry is "Horse"; [ Name of the overall species of the infection, used so a "male x" and "female x" have "pureblood X" children. ]
	add "Stallionboi" to infections of EquineList;
	add "Stallionboi" to infections of FurryList;
	add "Stallionboi" to infections of NatureList;
	add "Stallionboi" to infections of MaleList;
	add "Stallionboi" to infections of BluntCockList;
	add "Stallionboi" to infections of SheathedCockList;
	add "Stallionboi" to infections of BipedalList;
	add "Stallionboi" to infections of TailList;
	now Name entry is "Stallionboi";
	now enemy title entry is ""; [ Name of the encountered creature at combat start - Example: "You run into a giant collie." instead of using "Smooth Collie Shemale" infection name. ]
	now enemy Name entry is ""; [ Specific name of unique enemy. ]
	now enemy type entry is 0; [ 0 = non unique enemy; 1 = unique (unknown name); 2 = unique (known name) | Used to disqualify unique enemies from Vore/UB and showing the enemy name in encounters. ]
	now attack entry is "[one of]He gives you an equine grin for a minute, confusing you slightly, as he slowly stretches and poses teasingly in front of you, your body growing hot and aroused from the sexy show[or]The stallionboi reaches out and strokes his hands over your body teasingly[or]Pulling a large transparent blue double ended dildo from somewhere, he smacks you in the ass with it[at random].";
	now defeated entry is "[Stallionboi loses]";
	now victory entry is "[Stallionboi wins]";
	now desc entry is "[Stallionboi_Desc]"; [ Description of the creature when you encounter it.]
	now face entry is "slight equine muzzle, its slender stretched out look is strangely sexy as your stare out of it with your sensuous equine eyes. Your mostly equine ears sticking up jauntily out of your long sexy mane of dark brown hair with sea green highlights, giving a rather sexy and teasing look overall to your new face"; [ Face description, format as "Your face is [Face of Player]." ]
	now body entry is "slender and feminine, clothed in some sexy slutty clothes you found near where you finished changing, your sexy silk stalkings and gloves, do nothing to hide your slightly equine changes, though the feel of their dark purple silk against your [Skin of Player] skin makes you feel increasingly aroused and sexy with every step";
	now skin entry is "[one of]soft feminine[or]lightly furred[or]sexy chocolate furred[at random]";
	now tail entry is "You have a long, sexy equine tail swishing behind you eagerly, swaying side to side with every step as if inviting some sexy beast to hold you down and fuck you."; [ Tail description, write a whole Sentence or leave blank. ]
	now cock entry is "[one of]equine[or]stallion like[or]thick[or]blunt equine[at random]";
	now face change entry is "it begins to stretch and change, pushing forward slightly and giving you a more equine look, even as your hair grows out and changes in color and texture to form a proper mane, you find yourself neighing and squealing with pleasure as your face finishes shifting, and your ears come to rest on top of your head, and you find you love admiring your new sexy look, and your lovely dark mane with shimmering sea green highlights threaded through it"; [ Face change text, format as "Your face feels funny as [face change entry]." ]
	now body change entry is "it shifts and changes, your bones shifting slightly as your body curves into a more suggestive feminine shape, and your hips widen slightly even as a strange erotic energy seems to run through you, making you shudder with arousal as a soft breeze brushes your body. Looking around desperately, you spot a discarded bit of silk clothing nearby, and quickly pull it on, the sleek silk stockings and gloves doing nothing to hide your sexy new form, though the rich royal purple silk looks amazing on you, and the feel of the silk caressing your body teasingly makes you moan with pleasure"; [ Body change text, format as "Your body feels funny as [body change entry]." ]
	now skin change entry is "it shudders and softens, becoming sexier and more feminine, before a small coating of sexy dark brown fur begins to grow in, the fur only covering part of your body in its sexy sleekness, and leaving the rest of your chest and other areas teasingly bare";
	now ass change entry is "a sexy little equine tail begins to form behind you, the new equine appendage making you moan with pleasure as it swishes behind you, somehow every movement of your new appendage seeming amazingly erotic, especially when its soft silken strands brush up against your tight and eager ass";
	now cock change entry is "it balloons outwards, your balls swelling up as they begin to hang even lower between your legs. Your large thick new cock darkening in color as its textures changes, and the tip flattens out until you have a properly shaped equine shaft hanging low between your legs"; [ cock change text. format as "Your cock feels funny as (your text)." ]
	now str entry is 20;
	now dex entry is 14;
	now sta entry is 18;
	now per entry is 12;
	now int entry is 12;
	now cha entry is 14;
	now sex entry is "Male"; [ Defines which sex the infection will try and make you. current options are 'Male' 'Female' 'Both']
	now HP entry is 25;
	now lev entry is 3; [ Level of the Monster, you get this much HP if you win, or this much HP halved if you loose ]
	now wdam entry is 3; [ Amount of Damage monster Does when attacking. ]
	now area entry is "Stable"; [ Current options are 'Outside' and 'Mall'. Case sensitive]
	now Cock Count entry is 1; [ How many cocks will the infection try and cause if sex is 'Male' or 'Both']
	now Cock Length entry is 15; [ Length infection will make cock grow to if cocks]
	now Ball Size entry is 3; [ Size of balls 1-7: "acorn-sized", "dove egg-sized", "chicken egg-sized" "goose-egg sized", "ostrich-egg sized", "basketball-sized", "beachball-sized"]
	now Nipple Count entry is 0; [ Number of nipples infection will give you (males have nipples too) ]
	now Breast Size entry is 0; [Size of breasts infection will try to attain ]
	now Male Breast Size entry is 0; [ Breast size for if Sex="Male", usually zero. ]
	now Cunt Count entry is 0; [ if sex = "Female or both", indicates the number of female sexes infection will grant you.]
	now Cunt Depth entry is 0; [penetrable length in inches; some minor stretching allowed, or more with Twisted Capacity] [ Length of female sex infection will attempt to give you. ]
	now Cunt Tightness entry is 0; [size 1-5, generates adjectives of extremely tight/tight/receptive/open/gaping] [ Width of female sex infection will try and give you ]
	now SeductionImmune entry is false;
	now libido entry is 75; [ As part of infection, the Player will be gradually moved towards this value; also used for the creature's seduce defense as a penalty ]
	now loot entry is "lucky horseshoe"; [ Loot monster drops, usually infective with the monster's _own_ strain (for example if there is a Cross-Infection from sex)]
	now lootchance entry is 20; [ Chance of loot dropping 0-100 ]
	now MilkItem entry is "stallionboi milk"; [ Item to be given to the player if they have this infection and milk themselves. ]
	now CumItem entry is ""; [ Item to be given to the player if they have this infection and jerk off. ]
	now TrophyFunction entry is "-"; [ Function to generate a list of optional loot items, of which the player can choose one after victory. ]
	now scale entry is 3; [ Number 1-5, approx size/height of infected PC body: 1=tiny, 3=avg, 5=huge ]
	now body descriptor entry is "[one of]girly[or]feminine[at random]";
	now type entry is "[one of]equine[or]horse-like[at random]";
	now magic entry is false;
	now resbypass entry is false;
	now non-infectious entry is false;
	now Cross-Infection entry is ""; [ Infection that this infection will give the player when they lose; can be left empty if they infect with the monster's own strain. ]
	now DayCycle entry is 0; [ 0 = Up at all times; 1 = Diurnal (day encounters only); 2 = Nocturnal (night encounters only);]
	now altcombat entry is "default";
	now BannedStatus entry is false;

[
Table of New Infection Parts (continued)
Species Name	Name	Body Weight	Body Definition	Androginity	Head Change	Head Description	Head Adjective	Head Skin Adjective	Head Color	Head Adornments	Hair Length	Hair Shape	Hair Color	Hair Style	Beard Style	Body Hair Length	Eye Color	Eye Adjective	Mouth Length	Mouth Circumference	Tongue Adjective	Tongue Color	Tongue Length	Torso Change	Torso Description	Torso Adjective	Torso Skin Adjective	Torso Adornments	Torso Color	Torso Pattern	Breast Adjective	Breast Size	Male Breast Size	Nipple Count	Nipple Color	Nipple Shape	Back Change	Back Adornments	Back Skin Adjective	Back Color	Arms Change	Arms Description	Arms Skin Adjective	Arms Color	Locomotion	Legs Change	Legs Description	Legs Skin Adjective	Legs Color	Ass Change	Ass Description	Ass Skin Adjective	Ass Color	Ass Width	Tail Change	Tail Description	tail skin adjective	Tail Color	Asshole Depth	Asshole Tightness	Asshole Color	Cock Change	Cock Description	Cock Adjective	Cock Color	Cock Count	Cock Girth	Cock Length	Ball Description	Ball Count	Ball Size	Cunt Change	Cunt Description	Cunt Adjective	Cunt Color	Cunt Count	Cunt Depth	Cunt Tightness	Clit Size
--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--;

When Play begins:
	Choose a blank row from Table of New Infection Parts;
	now Species Name entry is ""; [ Name of the overall species of the infection, used so a "male x" and "female x" have "pureblood X" children. ]
	now Name entry is ""; [matching infection name to Table of Random Critters]
	now Body Weight entry is 5; [scale of 1-9 for body weight, grouped into low weight (1-3), mid weight (4-6) and high weight (7-9)]
	now Body Definition entry is 5; [scale of 1-9 for body definition, grouped into low muscle (1-3), mid muscle (4-6), high muscle (7-9)]
	[Body Adjective is generated out of the body weight and body definition and can be used in scenes - one word descriptive adjective depending on weight and definition groups: low weight group: skinny/slender/lithe; mid weight group: average/fit/muscled; high weight group: pudgy/husky/jacked]
	now Androginity entry is 5; [1-9 scale of hypermasculine to hyperfeminine]
	[Gender Adjective is generated out of androginity 1-9: hypermasculine/masculine/effeminate/somewhat effeminate/androgynous/feminine butch/tomboyish/feminine/hyperfeminine]
	now Head Change entry is ""; [partial sentence that fits in: "Your head and face [one of]tingle[or]go flush[or]vibrate with odd pleasure[or]go cold[or]feel oily[at random] as [head change entry]."]
	now Head Description entry is ""; [partial sentence that fits in "Your face and head resemble that of [Head Description of Player]. You have [Eye Adjective of Player], [Eye Color of Player] eyes and an overall [Gender Adjective of Player] appearance."]
	now Head Adjective entry is ""; [one word descriptive adjective (avian/canine/...)]
	now Head Skin Adjective entry is ""; [one word descriptive adjective]
	now Head Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	now Head Adornments entry is "";[partial sentence that fits in "Before moving on from your head, you give your [Head Adornments of Player] a proud glance followed by a light caress."]
	now Hair Length entry is 2; [hair length in inches]
	now Hair Shape entry is ""; [one word shape descriptor (curly/straight/...)]
	now Hair Color entry is ""; [one word color descriptor]
	now Hair Style entry is ""; [one word style descriptor (ponytail/mohawk/buzzcut/...) to fit "On top of your head you have [Hair Length of Player] inch long, [Hair Shape of Player] [Hair Color of Player] hair in the [Hair Style of Player] style."]
	now Beard Style entry is ""; [short beard style (goatee/3-day stubble beard/porn stache/mutton chops beard/...) to go into "You have a [Hair Color of Player] [Beard Style of Player]."]
	now Body Hair Length entry is 0; [numerical value, 0-4 (no body hair/light/moderate/heavy/furry) - only set to > 0 if the infection does not have fur/scales/etc. !]
	now Eye Color entry is ""; [one word color descriptor]
	now Eye Adjective entry is ""; [one word descriptive adjective (slitted/round/...)]
	now Mouth Length entry is 3; [inches deep for face fucking; maximum possible will be double this number (when deep throating)]
	[Mouth Length Adjective is generated by a function and can be used in scenes too - "petite, shallow, average, deep, bottomless"]
	now Mouth Circumference entry is 3; [mouth circumference 1-5, see Mouth Circumference Adjective]
	[Mouth Circumference Adjective is generated by a function and can be used in scenes too - "tiny, small, normal, wide, gaping"]
	now Tongue Adjective entry is ""; [one word descriptive adjective (wide/slobbery/...)]
	now Tongue Color entry is ""; [one word color descriptor]
	now Tongue Length entry is 3; [length in inches]
	now Torso Change entry is ""; [partial sentence that fits in: "Your torso [one of]tingles[or]goes flush[or]vibrates with odd pleasure[or]goes cold[or]feels oily[at random] as [Torso Change entry]."]
	now Torso Description entry is ""; [partial sentence, fitting in "Looking down at yourself, you appear [Gender Adjective of Player] with a [Body Adjective of Player] build. Your torso is [Torso Description of Player][if Body Hair Length of Player > 1], covered in [Torso Color of Player] skin and [Body Hair Description of Player][else if Body Hair Length of Player is 1], covered in smooth, [Torso Color of Player] skin[end if]."]
	now Torso Adjective entry is ""; [one word descriptive adjective (avian/canine/...)]
	now Torso Adornments entry is ""; [(pouch/udders/...); partial sentence to fit: "You take a moment to feel your [Torso Adornments of Player]."]
	now Torso Skin Adjective entry is ""; [one word adjective (feathered/furred/scaly/...); EMPTY "" for creatures with just skin]
	now Torso Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	now Torso Pattern entry is ""; [single word color adjective for the dominant pattern of the skin/fur/feathers/scales]
	now Breast Adjective entry is ""; [adjective(s) example: round, pointy, perky, saggy, bouncy. This would serve as either a general appearance of a infections breasts or possibly something that may be effected by a item or NPC.]
	now Breast Size entry is 0; [cup size as number, counting Flat Pecs = 0, A = 1, B = 2, ...]
	now Male Breast Size entry is 0; [cup size as number, counting Flat Pecs = 0, A = 1, B = 2, ...]
	now Nipple Count entry is 2; [count of nipples]
	now Nipple Color entry is ""; [one word color descriptor]
	now Nipple Shape entry is ""; [shape example: any shape will do as long as it has a baseline with a current infection or item]
	now Back Change entry is ""; [partial sentence that fits in: "Your back [one of]tingles[or]goes flush[or]vibrates with odd pleasure[or]goes cold[or]feels oily[at random] as [Back Change entry]."]
	now Back Adornments entry is ""; [partial sentence to fit: "Your back tickles with the feeling of movement caused by [back adornments of Player]."]
	now Back Skin Adjective entry is ""; [one word adjective (feathered/furred/scaly/...); EMPTY "" for creatures with just skin]
	now Back Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	[Limbs Adjective is generated by a function and can be used in scenes too - "rail-thin, slender, sinewy, average, firm, muscular, flabby, meaty, rippling"]
	now Arms Change entry is ""; [partial sentence that fits in: "Your arms [one of]tingle[or]go flush[or]vibrate with odd pleasure[or]go cold[or]feel oily[at random] as [Arms Change entry]."]
	now Arms Description entry is ""; [partial sentence to fit: "Your [Limbs Adjective of Player] arms are [Arms Description of Player]."]
	now Arms Skin Adjective entry is ""; [one word adjective (feathered/furred/scaly/...); EMPTY "" for creatures with just skin]
	now Arms Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	now Locomotion entry is ""; [one word adjective: (bipedal/quadrupedal/octapedal/serpentine/sliding)]
	now Legs Change entry is ""; [partial sentence that fits in: "Your legs [one of]tingle[or]go flush[or]vibrate with odd pleasure[or]go cold[or]feel oily[at random] as [Legs Change entry]."]
	now Legs Description entry is ""; [partial sentence to fit: "As your inspection goes even lower, you come to the two [Body Adjective of Player] legs supporting you. They are [Legs Description of Player]."]
	now Legs Skin Adjective entry is ""; [one word adjective (feathered/furred/scaly/...); EMPTY "" for creatures with just skin]
	now Legs Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	now Ass Change entry is ""; [partial sentence that fits in: "Your ass [one of]tingles[or]goes flush[or]vibrates with odd pleasure[or]goes cold[or]feels oily[at random] as [Ass Change entry]."]
	now Ass Description entry is ""; [partial sentence to fit: "Using your hands you feel your behind enjoying the sensation of your [Ass Width Adjective of Player], [Ass Shape Adjective of Player] [Ass Description of Player]." (For players with skin, instead of the period: ", covered in [Ass Color of Player] skin and [Body Hair Description of Player]"]
	now Ass Skin Adjective entry is ""; [one word adjective (feathered/furred/scaly/...); EMPTY "" for creatures with just skin]
	now Ass Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	now Ass Width entry is 3; [ass width from 1-5]
	[Ass Width Adjective generated by function out of ass width: dainty/small/round/huge/enormous]
	[Ass Adjective generated by function out of body definition and ass width]
	now Tail Change entry is ""; [partial sentence that fits in: "Your rear [one of]tingles[or]goes flush[or]vibrates with odd pleasure[or]goes cold[or]feels oily[at random] as [if HasTail of Player is true]your existing tail is changed into a [Tail Description entry][else][Tail Change entry][end if]."]
	now Tail Description entry is ""; [partial sentence to fit: "Just below your lower back sprouts a [Tail Description of Player], which you move back and forth with glee."]
	now Tail Skin Adjective entry is ""; [one word adjective (feathered/furred/scaly/...); EMPTY "" for creatures with just skin]
	now Tail Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	now Asshole Depth entry is 7; [inches deep for anal fucking]
	[Asshole Depth Adjective is generated by a function and can be used in scenes too - "petite (< 3), shallow (< 5), average (< 9), deep (< 15), bottomless (15+)"]
	now Asshole Tightness entry is 3; [asshole tightness 1-5, "extremely tight, tight, receptive, open, gaping"]
	[Asshole Tightness Adjective is generated by a function and can be used in scenes too - "extremely tight, tight, receptive, open, gaping"]
	now Asshole Color entry is ""; [one word color descriptor]
	now Cock Count entry is 0;
	now Cock Girth entry is 0; [thickness 1-5, generates the Cock Girth Adjective]
	[Cock Girth Adjective is generated by a function and can be used in scenes too: thin/slender/average/thick/monstrous]
	now Cock Length entry is 0; [length in inches]
	now Cock Adjective entry is ""; [one word adjective: avian/canine/...]
	now Cock Change entry is ""; [partial sentence that fits in: "Your cock [one of]tingles[or]goes flush[or]vibrates with odd pleasure[or]goes cold[or]feels oily[at random] as [Cock Change entry]."]
	now Cock Description entry is ""; [partial sentence to fit: "You have a [Cock Girth Adjective of Player], [Cock Length of Player]-inch-long [Cock Adjective of Player] [one of]cock[or]penis[or]shaft[or]maleness[at random] that [cock Description of Player]."]
	now Cock Color entry is ""; [one word color descriptor]
	now Ball Count entry is 0; [allowed numbers: 1 (uniball), 2 or 4]
	now Ball Size entry is 0; [size of balls 1-7: "acorn-sized", "dove egg-sized", "chicken egg-sized" "goose-egg sized", "ostrich-egg sized", "basketball-sized", "beachball-sized"]
	[Ball Size Adjective is generated by a function and can be used in scenes too]
	now Ball Description entry is ""; [partial sentence to fit: "Underneath it hangs a pair of [Ball Size Adjective of Player] [Ball Description of Player]."]
	now Cunt Count entry is 0;
	now Cunt Depth entry is 0; [penetrable length in inches; some minor stretching allowed, or more with Twisted Capacity]
	now Cunt Tightness entry is 0; [size 1-5, generates adjectives of extremely tight/tight/receptive/open/gaping]
	[Cunt Tightness Adjective is generated by a function and can be used in scenes too: extremely tight/tight/well-used/open/gaping]
	now Cunt Adjective entry is ""; [one word adjective: avian/canine/...]
	now Cunt Change entry is ""; [partial sentence that fits in: "Your pussy [one of]tingles[or]goes flush[or]vibrates with odd pleasure[or]goes cold[or]feels oily[at random] as [Cunt change entry]."]
	now Cunt Description entry is ""; [partial sentence to fit: "You have a [Cunt Tightness Adjective of Player] [one of]cunt[or]pussy[or]vagina[or]cleft[at random] that [Cunt Description of Player]."]
	now Cunt Color entry is ""; [one word color descriptor]
	now Clit Size entry is 0; [size 1-5, see Clit Size Adjective]
	[Clit Size Adjective is generated by a function and can be used in scenes: very small/small/average/large/very large]
]


Section 3 - Endings

Table of GameEndings (continued)
Name (text)	Type (text)	Subtype (text)	Ending (rule)	Priority (number)	Triggered (truth state)
"Stallionboi Infection"	"Infection"	""	Stallionboi Infection rule	1000	false

This is the Stallionboi Infection rule:
	if Player has a body of "Stallionboi":
		trigger ending "Stallionboi Infection"; [Here it states, that the ending has been played.]
		if humanity of Player < 10:
			if Player is male:
				say "     Unable to deny your body the sexual pleasure and stimulation it craves, you quickly run back to the wonderful stables, and all the sexy stallionbois you just know are waiting for you there. The guards smirk with amusement as you rush by, their eyes drawn to your sexy little part equine body, causing you to shudder happily at the thought of the more powerful horsemen using you like a good little pet again and again. Once inside, you quickly charge off down the halls, finding yourself nearly squealing with joy as your lust fogged mind follows the scent of equine sex through the halls. It isn't long before another of those sexy stallionbois finds you, and he grins happily and squeals with pleasure as you practically throw yourself onto him, leading you through the corridors quickly to where the rest of the stallionbois are waiting for you eagerly with arms wide open, and cocks already erect. It isn't long before they fuck any last remaining doubts about being a sexy slutty stallionboi out of you, teaching you all about how to be a proper little stallionslut and how to service any client or mare (or stallion!) that wants to use your slutty little body. And you find yourself smiling happily as you learn to be a proper little submissive femboi, finding yourself strangely happy with your new feminine like part horse form, as the more horselike mares and stallions go about the business of the place, you find yourself eagerly looking forward to your new life of sex and pleasure serving their every whim...";
			else:
				say "     Unable to deny your body the sexual pleasure and stimulation it craves, you quickly run back to the wonderful stables, and all the sexy stallionbois you just know are waiting for you there. The guards smirk with amusement as you rush by, their eyes drawn to your sexy little part equine body, causing you to shudder happily at the thought of the more powerful horsemen using you like a good little pet again and again. Once inside, you quickly charge off down the halls, finding yourself nearly squealing with joy as your lust fogged mind follows the scent of equine sex through the halls. It isn't long before another of those sexy stallionbois finds you, and he grins happily and squeals with pleasure as you practically throw yourself onto him, leading you through the corridors quickly to where the rest of the stallionbois are waiting for their slutty little stallionpussy with arms wide open, and cocks already erect. It isn't long before they fuck any last remaining doubts about being a sexy slutty stallionslave out of you, teaching you all about how to be a proper little stallionslut and how to service any client or mare (or stallion!) that wants to use your slutty little body, teaching you how to use your pussy and mouth properly to please any master who wants you. And you find yourself smiling happily as you learn to be a proper little submissive femme, finding yourself strangely happy with your new feminine like part horse form, and as the more horselike mares and stallions go about the business of the place, you find yourself eagerly looking forward to your new life of sex and pleasure serving their every whim...";
		else:
			if Player is male:
				say "     When the rescue finally comes, you find yourself unable to resist as the powerful military men come and take you away to safety, something about their strong well toned bodies and purposeful actions making you feel rather mild and meek as they lead you away. Eventually after being poked and prodded by several of their scientists, when they can't figure out what to do with you otherwise, they end up letting you go, having deemed you to not be a threat to society, and focus their attentions back on the fight raging throughout the city. Free, you find yourself drifting for a while, unable to find much purpose or direction in your life as you wander around aimlessly. You soon realize that you are far more girlish and submissive than ever before, and are unable to put yourself forward, or deny most dominant people whatever it is they want. This results in you taking a number of jobs, and eventually slinking away from them quietly when the people there begin to realize this and start to take advantage of you. Finally you find yourself making some friends with a few sympathetic women one night, and they help you to get a job at a sexy clothing store for women. You find yourself beginning to enjoy your work again, and growing somewhat more comfortable with the place, although the female owner does think it is fun sometimes to dress your feminine form up in some of the clothing around the place. You actually find yourself amused by this as well sometimes, the feel of silk and leather on your sensitive skin making you feel quite nice and slutty, and the looks on some of the men's faces when they realize you are packing a large equine cock is hilarious sometimes. Of course eventually you do manage to find a few men and women willing to experiment with your sexy new body, including of course most of your co workers, who soon come to love being just as sexy and slutty as you do. Eventually your owner decides to start branching out the direction of the store, and you just love the thought of how much fun you are going to have with all the new lovely sex toys and bondage gear she is stocking up in back for the customers... or to use on the customers... you just can't wait to try it out yourself!";
			else:
				say "     When the rescue finally comes, you find yourself unable to resist as the powerful military men come and take you away to safety, something about their strong well toned bodies and purposeful actions making you feel rather mild and meek as they lead you away. While they quickly dismiss you as relatively harmless compared to the more dangerous beasts within the city, you find yourself somewhat less than willing to leave right away, spending your time at the base helping the soldiers fetch things and take care of any small tasks they might need your help with. The more time you spend in the presence of the sexy and dominant men, the less you find yourself wanting to leave, somehow craving the sense of safety and security being surrounded by the soldiers gives you. When one of them inevitably takes you off into a dark corner to put your sexy little mare pussy to use, you find yourself squealing happily as your body responds eagerly to his touch. Once you realize how amazing it feels to serve your rescuers with your body, you waste no time in doing so at every opportunity, spreading your legs for them eagerly as often as possible. Before long, you find yourself hardly even thinking of them as soldiers anymore, and start thinking of the sexy uniform clad men as your masters instead. As things get worse and worse in the city, the military turns a blind eye (perhaps helped by how often some of your higher ranked masters enjoy using you) to your presence, you enjoy your new position more and more. And when eventually some of your sexy masters start showing even more handsome equine features, you don't hesitate to send them in the direction of the stables, where you assure them they can find all sorts of horsey fun when they go into the city. And while few of them come back from venturing into that part of the city, and those that do only stay back long enough to take a few friends with them as they head back out, and as the military encampment slowly shrinks in size, and the numbers of sexy horsemen in the city swells larger, you have a feeling you will be seeing many of your now horsey masters again soon enough, in the meantime, there are still plenty of sexy masters willing to use your slutty equine body as often as possible... with more arriving every day...";

Stallionboi ends here.
