Version 1 of Inner Mall Events by Wahn begins here.
[ Version 1 - New Event Area ]

JayMarkRelationship is a number that varies.
MiltonRelationship is a number that varies.

Dressing Room Rampage is a situation.
The sarea of Dressing Room Rampage is "Smith Haven".

when play begins:
	add Dressing Room Rampage to badspots of furry;

Instead of resolving a Dressing Room Rampage:
	say "     Wandering the hallways of the Smith Haven Mall, you pass through crowds of all sorts of people: lots of mall rats and countless other species, demi-human hybrids, as well as very rare pure humans. You stroll in and out of various stores, some occupied by the refugees of the outbreak, others laying abandoned. But just as you pass through a fancy clothing boutique that is empty of people, you hear something - the slapping sound of flesh on flesh, followed by a lewd moan. Curiosity guides your steps deeper into the store, walking along the aisles full of skimpy garments that are less than useless in the current crisis, until you spot a series of dressing rooms against the back wall. You notice that the third little room has its curtain drawn closed, and it is moving a little, as if being bumped around by its occupants. Judging by their tone of voice, the moans emanating from within must belong to two men who are clearly distracted indulging in carnal pleasures.";
	say "     [bold type]Do you want to pull back the curtain and have a closer look?[roman type][line break]";
	LineBreak;
	say "     ([link]Y[as]y[end link]) - Sure! They won't mind some company, will they?";
	say "     ([link]N[as]n[end link]) - Hell no! Give the guys some privacy.";
	if player consents:
		LineBreak;
		say "     Stepping forward, you take hold of the red drapes hiding the inside of the dressing room cabin and slowly pull it aside, revealing the two men within. They are an interesting couple - a magnificently large polar bear, with broad shoulders and hard muscles on his bulky frame, holding a much smaller partner by the hips as he pounds into him from behind with a thick, black-skinned shaft, balls slapping the bottom's ass in a regular rhythm. For a second, you almost peg the guy being fucked as a short, uninfected male, given his bare pink skin and rock-hard humanoid cock - but no, he's too slender and elfin for that. The glimpse of some green and red garment lying crumpled on the floor makes things click in your mind, and your guess at him being a Christmas elf is confirmed when another hard thrust makes his shoulder-length hair swing forward, revealing pointy ears beneath.";
		say "     Suddenly having a [bodyname of player in lower case] standing in front of them doesn't give pause to either of the two men. The elf has his gaze firmly trained upon the two large mirrors covering whole sections of the wall in the little room, watching his top's shaft saw in and out of his ass. Meanwhile, the polar bear just continues to pound into his little partner, although he actually registers your presence, letting out a gruff grunt to acknowledge you. 'Join in or fuck off. Better choose quickly! And draw that fucking curtain before more spectators come in,' the bear barks out in a harsh tone, spearing you with an intense gaze that demands an immediate reply.";
		say "     [bold type]How do you react to his demand?[roman type][line break]";
		LineBreak;
		say "     ([link]Y[as]y[end link]) - Step into the dressing room and strip, presenting your crotch to the elf.";
		say "     ([link]N[as]n[end link]) - Draw the curtain closed again, leaving the two of them alone.";
		if player consents:
			LineBreak;
			say "     'Damn boy, squeeze that ass. Yeah!' the polar bear grunts out loud, his large hands tightly wrapped around the elf's hips as he grinds his crotch against his ass. The small, human-like bottom whimpers in submissive pleasure from the deep penetration, his belly bulging out a little with the ursine's generous shaft. Accepting the polar bear's enticing invitation, you quickly strip down and ";
			if cocks of player > 0:
				say "present your hardening cock to the slender twink of an elf. The happily moaning bottom reacts immediately, opening wide to accept your offered shaft without a beat of hesitation. His diminutive mouth forms a warm, wet vise that suckles slickly on your pulsing prick, sending shivers of arousal through your form. For such a small guy, he sure knows how to deep-throat! You run your fingers through the long and soft strands of his hair, then grab hold of them to guide the elf's blushing face up and down your [cock of player] erection, savoring his every gurgling moan around your pre-dripping cockmeat. Face-fucking the elfin male, you exchange a broad grin with the polar bear top on the other end, whose steady thrusts sink your dick deeper into his bottom's squeezing throat.";
				say "     'Quite something, isn't he?' the white-furred man says proudly, half-grunting the words as he pounds the elf's ass with one savage thrust after another. 'Best ass one could wish for. Such a fucking [italic type]tight[roman type] boy-pussy!' Given the enthusiasm with which the big man is pounding his submissive partner, you're surprised that the little guy can take it all. Maybe Christmas elves are naturally stretchy, or maybe the bottom is just exceptionally skilled at what he does? The sensation of his slurping mouth and tensing throat around your cock certainly suggests it, the little elf taking your rapid face-fucking effortlessly. He even employs little tricks to tease your arousal to greater heights, from the massaging rippling of his throat to the nimble, curling sweeps of that tiny tongue lavishing your [cock size desc of player], throbbing cock.";
				WaitLineBreak;
				say "     Spit-roasting the pale-skinned elf between the two of you is a lot of fun, and soon, you hear the grunts of the bucking polar bear grow more and more intense, heralding his impending orgasm. YYou pick up the slack and start really going to town on his bottom boy's face, slamming your hips against his puckered lips with increasing zeal, your own arousal soaring as his throat reflexively seizes around your shaft. It's a close call, but in the end, the broad-shouldered ursine is the first to come, thrusting in all the way and stuffing the slender elf with heavy spurts of potent seed, a hot and sticky deluge of heat that draws a fluttering moan around your member. You're only moments behind the bear, ramming your pointy-eared partner down on your shaft as you feel your balls churn and tighten. Groaning in ecstasy, the first spurt of seed paints his tongue white, and the rest is shot directly down the elf's greedy gullet, pulse after pulse of scintillating warmth coursing through his trembling form.";
				say "     Blissfully riding out your orgasm, you stay leaned over the small form of the elfin bottom, your cock throbbing with tapering spurts of cum, until you suddenly feel a tapping on your thighs, getting more urgent by the second. It takes a heartbeat or two for you to register what it actually is - your cocksucker is running out of air! you quickly slide yourself out of his tight, sweet throat, freeing the little guy to gasp for air and pant in big gulps to soothe his burning lungs. 'Thanks,' he says breathlessly as he looks up at you, amber eyes meeting your own with a cheerful smile before the guy licks his lips to catch a stray streak of cum. Meanwhile, the polar bear top behind him reaches around his still thoroughly impaled bottom boy to take hold of his hard and dripping cock, jerking him off with rapid pumps of that large, furry hand.";
			else:
				say "present your [bodyname of player in lower case][if cunts of player > 0] pussy [else] crotch [end if]to the slender twink of an elf. The happily moaning bottom reacts immediately, sticking out his tongue to lick over your [if cunts of player > 0]nether lips. The tip of his fleshy appendage circles your clit a few times[else]sensitive skin. The tip of his fleshy appendage seeks out a surprisingly sensitive spot[end if], making sure to stimulate it nice and long to drive you wild. He may just be a small dude, but this little guy sure knows how to please [if cunts of player > 0]a woman[else]someone[end if]! You run your fingers through the long and soft strands of his hair, then grab it and use it as a nice handhold, grinding the elf's head up and down against your crotch. Rubbing up against the elfin male, you exchange a broad grin with the polar bear top on the other end.";
				say "     'Quite something, isn't he?' the white-furred man says proudly, half-grunting the words as he pounds the elf's ass with thrust after hard thrust. 'Best ass one can wish for. Such a fucking [italic type]tight[roman type] boy-pussy!' Given the enthusiasm with which the big man is pounding his submissive partner, you're surprised that the little guy can take it all. Maybe Christmas elves are just naturally stretchy, or the bottom is just exceptionally skilled at what he does. The sensation of his slurping tongue and the little teasing nibbles [if cunts of player > 0]on your clit[else]he gives you[end if] certainly suggest it, as he eagerly replies to your grinding and even employs some little tricks with his tongue to tease your arousal to ever higher levels.";
				WaitLineBreak;
				say "     Spit-roasting the pale-skinned elf between the two of you is a lot of fun, and soon, you can hear the grunts of the fucking polar bear get more and more intense, heralding his impending orgasm. You take up the challenge and really push his bottom boy's face up against your [if cunts of player > 0]pussy, sending your own arousal soaring from the new depth his questing tongue can reach[else]crotch, sending your own arousal soring from the increase in licking that brings with it[end if]. It is a close thing, but in the end, the broad-shouldered ursine is the first to come, thrusting in all the way and breeding the twinky elf with heavy spurts of his potent seed. You're only moments behind though, hands clamped on your pointy-eared partner as you start to [if cunts of player > 0]squirt femcum into his face. He happily catches it with his tongue, then puts his lips over your clit to suckle on it and prolong your orgasm[else]tremble against his soft-skinned face[end if].";
				say "     Blissfully riding out the height of pleasure, you stay leaned over the small form of the elfin bottom, your [if cunts of player > 0]sex feeling hot and wet[else]body feeling hot and sweaty[end if], until you suddenly feel a tapping on your thighs. It takes a heartbeat or two for you to register what it actually is - you've still got the elf's head wedged against your crotch, holding him rather tightly. Somewhat shamefaced, you quickly let go of his long silky hair, freeing the little guy to raise his upper body. 'Thanks,' he says with an eager smile and looks up at you, amber eyes meeting your own as the guy smiles and licks his lips. Meanwhile, the polar bear top behind him reaches around his still thoroughly impaled bottom boy and takes hold of his hard cock, jerking him off with rapid pumps of his large hand.";
			WaitLineBreak;
			say "     Wound up as the elf already is from your threesome, it doesn't take very long before he moans out loud and starts to cum, splattering the ground between his legs with spurt of his creamy white load. The polar bear keeps holding his cock until his orgasm has run its course, then brings his furry hand to the elf's face and has him lick up a streak of cum matting the fur on the side of the index finger. 'That's my boy,' the big ursine says proudly, tousling the elf's long hair. Then he turns his gaze to you and says, 'What do you think of this little slut?' The beaming smile and thumbs up he gets in response is all the bear needs to know. With a chuckle, he adds, 'Would you believe that this sweet twink was my top when we stumbled into the mall together? I'm Mark and he's Jay by the way. Been together for five years now, just... the other way around, before things happened.'";
			say "     'Hey [mister],' the exhausted elf tells you in a happy tone, lifting himself from being bent over and leaning back against the polar bear's broad chest, now giving you the full view of his slender, naked body for the first time. He is a sexy twink indeed, with his belly currently bulging out a fair bit, both from Mark's cock as well as the load of cum the bear pumped into him. Strong, white-furred arms wrap around the lithe elf and Mark adds, 'Crazy how things happen, eh? Came here to find refuge together with my man. I was a happy sub ever since I lost my virginity, but after some alone-time with Santa Claws... I started feeling differently. Stronger. More dominant. You know how it goes.' Jay leans into his embrace happily, rubbing his cheek against the polar bear's white fur, then adding a playful comment of, 'I love how my big bear daddy makes me feel. He's shown me a whole new side of myself.'";
			WaitLineBreak;
			say "     After you introduce yourself[if player is not defaultnamed] as [name of player][end if], the three of you chat a little while longer until Mark grows soft enough that his dick slips out of his lover all on its own. What doesn't come out though is cum, as all of it is apparently so deeply planted into the elven bottom that there is no danger of leakage from his tight behind. The two of them start picking up clothes to get dressed again, which actually is a bit of a difficult task with all three of you in the small dressing room. After bumping into each other a few times, you are actually allowed to go first at getting dressed, so you can step out and give them a bit more space. As you are about to pull the curtain shut behind yourself, Mark gives you an eager grin, while Jay cheerfully calls out, 'Have a nice day. Hope to see you again sometime [mister].'";
			now JayMarkRelationship is 3; [fucked around with the two of them, player knows the names]
		else:
			LineBreak;
			say "     Face burning in embarrassment, you murmur an apology and step back, drawing the curtain closed again. The sounds of sex from the other side continue without even a hint of an interruption. Shrugging, you turn around, quietly leaving the store again. The rest of your current trip through the building doesn't reveal any particularly interesting situations, so you eventually end up where you started.";
			now JayMarkRelationship is 1; [saw the two of them]
	else:
		LineBreak;
		say "     The men in the dressing booth seem to be making the best of the whole refugee situation in the mall right now. You wish them well in your mind and turn around, quietly leaving the store again. Moving on, you follow one side of the mall wing, checking out some of the former businesses to pass the time. As you make your way forward, you eventually double back on the other side of the wide mall hallway, and fate leads you past the very store where you heard the commotion from the dressing room just as what must have been the participants walk out of it. Visually, the gay couple couldn't be more different: a towering polar bear in a checkered flannel shirt and jeans, accompanied by what is clearly a Christmas elf, complete with the stereotypical red and green outfit and sharply pointed ears that stick out through the long brown hair cascading over his shoulders.";
		say "     Yet the fact that one of them is only half as tall as the other doesn't stop them from being together, as evident by their very open affection for one another. Patting the thick and sturdy ursine leg beside him, the elf calls out, 'How about a goodbye kiss, big guy?' With a grin, the large anthro bear picks his boyfriend up for a deep and hungry kiss. Arms wrapped partially around the much bigger man's broad chest, the elf tells him, 'Be careful out there. You may be my big, strong bear now, but I worry sometimes.' With a consoling grunt, his ursine partner replies, 'Of course, hon. Nothing will keep me from coming back to you.' Following another kiss between them, the big polar bear sets his lover down, then walks off towards the mall entrance. Looking after him, you manage to lose track of his diminutive partner. Being only about four feet tall, he is quite easy to lose in the crowds of people populating the mall.";
		now JayMarkRelationship is 1; [saw the two of them]
	now Elven Issues is not resolved;
	now Dressing Room Rampage is resolved;

Elven Issues is a situation. Elven Issues is resolved.
The sarea of Elven Issues is "Smith Haven".

Instead of resolving a Elven Issues:
	say "     As you go for a stroll through the mall, you suddenly hear a bit of a commotion ahead of you. Shouts of 'Hey, stop! That's mine! Thief!' come from somewhere ahead, followed by the sight of a kangaroo-morph sprinting your way. She is rushing through the thick crowd of people in the middle of the east wing of the mall at a breakneck pace, followed by a small-ish figure in a green and red outfit, running as fast as he can and furiously calling after her. It is a Christmas elf, and one you know: [if JayMarkRelationship is 3]Jay, the boyfriend of Mark the polar bear, whom you met in the dressing room of a fancy boutique[else]He was getting pounded by a quite large polar bear in the dressing room of a fancy boutique when you stumbled over him[end if]. Looks like the kangaroo will pass right by you in a few seconds.";
	say "     [bold type]How do you react to this?[roman type][line break]";
	LineBreak;
	say "     ([link]Y[as]y[end link]) - Stick out your foot and trip her.";
	say "     ([link]N[as]n[end link]) - Do not get involved.";
	if player consents:
		LineBreak;
		say "     Holding out your foot at just the right moment, you pull the legs out under the thieving marsupial, sending her to fall flat on her face. The four foot tall elf chasing after her calls out in vindication, rushing to stand over the kangaroo with his arms crossed in front of his chest. 'Just because I'm small doesn't mean you can just take whatever you want. Give it back.' Looking up defiantly, she doesn't reply for a long moment. [if JayMarkRelationship is 3]Jay[else]The elf[end if] suddenly grabs a handful of hair, pulling her head up sharply. He meets the woman's eyes with a steely gaze and says in a low tone, 'I am not some weak little victim, stupid bitch. Now give it back, or I'll tell the wolverines all about a certain petty thief disturbing the peace. You'll be out on the street before you know it.' With a growl under her breath, the kangaroo reaches into her pouch, pulling out a thin leather strap tied into a loop. A heavy gold ring dangles from it, clearly belonging to a man. Pulling the band over his head and stuffing the ring under his clothing to let the ring dangle over his breastbone, Jay takes a deep breath and lets it out slowly.";
		say "      After that, he hisses to the kangaroo, 'Get out of here, and I better not see you causing trouble again.' After pushing herself up to stand, the woman runs off without looking back. As soon as she is gone, the diminutive man turns to you and says, [if JayMarkRelationship is 1]'Thank you, [mister]. I'm Jay, by the way. It's a pleasure to meet you.' [else]'Thank you, [mister].' [end if]You introduce yourself [if player is not defaultnamed]as [name of player][else]in turn[end if] and nod for him to continue. 'I don't have much left from my life before. This was one of the commitment rings I got for myself and Mark. It doesn't even fit me anymore like this, and he's the provider now, but one should always remember where you come from.' With the way he says this, you sense that he has accepted his new self, but he clearly still gets frustrated when bigger people pick on him. Reaching out, the elf shakes your hand and smiles, then adds, 'I'll make sure to return the favor sometime. For now, I need to head to the entrance court to meet up with Mark. Since I can't exactly help him scavenge out there, the least I can do is give him a warm welcome when he returns.' With that said, he ducks into the crowd and is gone a moment later.";
		now Mark's Dinner Invite is not resolved;
	else:
		LineBreak;
		say "     Just after the kangaroo rushes past you, a whole crowd of mall rats rushes out of a video game store, swamping the hallway completely. This stops [if JayMarkRelationship is 3]Jay's[else]the elf's[end if] pursuit cold, preventing him from following the thief any further. By the time the crowd disperses enough for the elf to continue on, the kangaroo is gone without a trace. The slender male pulls himself to his full four foot height and puts his hands on his hips, staring at the people ahead and giving a deep sigh. 'Well, fuck!' he grumbles, then whirls around and stalks off, back the way he came. In his huff, he doesn't even notice you as he dashes past.";
	now Elven Issues is resolved;

Mark's Dinner Invite is a situation. Mark's Dinner Invite is resolved.
The sarea of Mark's Dinner Invite is "Smith Haven".

Instead of resolving a Mark's Dinner Invite:
	say "     As you walk into the east wing of the mall, you draw the attention of a powerful polar bear, towering a full head over the surrounding crowd of people. Moving towards you with long strides, he has little trouble navigating the hallway despite how crowded it is, a swarm of mall rats congregating around the video game store nearby. Then again, no one really wants to stand in the way of such a muscular and broad-shouldered ursine, so they all quickly step out of his path on their own volition. The big white bear moves to stand before you, gives you a brief inspection, and then creases a broad grin as he offers you his large hand-paw to shake.";
	say "     '[if JayMarkRelationship is 1]Hey there, I'm Mark [end if]I hear you've been helping out my man. Thank you. Things have been hard for him since the transformation. So, how about joining us for dinner sometime? Got some good hauls out in the city recently, and we'd be happy to share a little something with a nice person like yourself,' the bear offers with a smile that shows off his large, sharp fangs. 'When you have the time, just meet me at the north entrance of the mall in the evening. I always come in on that side after a day's scavenging and hang out a bit with the wolverines. And be sure you're hungry, it'll be a nice little feast.' The bear squeezes your shoulder in a friendly way, then walks off again, leaving you to dwell on his offer.";
	now Mark's Dinner Invite is resolved;
	now JayMarkRelationship is 2; [player knows their names (for sure)]
	now thirst of Mark is 1; [dinner invite extended]
	now XP of Mark is 1; [starting his daily rhythm]
	now XP of Jay is 1; [starting his daily rhythm]

[ End of Jay + Mark content, other events below ]


Size Envy is a situation.
The sarea of Size Envy is "Smith Haven".

when play begins:
	add Size Envy to badspots of furry;

Instead of resolving a Size Envy:
	say "     Wandering the hallways of the Smith Haven Mall, you pass through crowds of all sorts of people: lots of mall rats and countless other species, demi-human hybrids, as well as very rare pure humans. Curiosity makes you stroll in and out of the various stores - some are occupied by the refugees, others lay abandoned. Going into one of the places that is inhabited, your attention is drawn by a group of young men huddled in the far corner, with one of them suddenly calling out, 'No way! You're just pulling our leg.' Casually turning your steps to move closer, you inspect the little group of guys closer: there is a German shepherd human hybrid sporting paw-feet and a tail, a slender mall rat with spiky, purple hair, a shirtless anthro donkey wearing jeans and a clockwork fox standing there in the nude, unconcerned about showing his metallic body and all of its details.";
	say "     'Nope, I'm not!' the mall rat says with a proud smirk on his face, then grabs the front of his baggy pants and gives his crotch a squeeze. 'You simply can't be bigger then Axel,' the clockwork fox interjects, raising his arm with a few soft clicks and pointing at the donkey-boy, who nods and adds, 'Not to toot my own horn, but us equines are just naturally bigger, you know. And you're... well, short. In height, I mean.' Crossing his arms in front of his chest, the partially canine young man (whose voice you recognize as being the one who called out) demands, 'So cut the tall tales, Nicholas! Just admit that you were making it up.' Nicholas the mall rat just keeps grinning, then wiggles his eyebrows and says, 'Wanna bet that I'm bigger than all of you, Rob? A bottle of water each, winner takes all? You in too Axel, Milton?' Nods of agreement go through the little group, though when Nicholas pulls out a tape measure from his pocket, the guys pause as they realize that he planned this.";
	WaitLineBreak;
	say "[SizeEnvyMenu]";

to say SizeEnvyMenu:
	LineBreak;
	say "     [bold type]Well, this certainly could get interesting. How do you want to deal with the development between the guys?[roman type][line break]";
	now sextablerun is 0;
	blank out the whole of table of fucking options;
	[]
	choose a blank row in table of fucking options;
	now title entry is "Casually observe their competition";
	now sortorder entry is 1;
	now description entry is "Simply watch the action";
	[]
	choose a blank row in table of fucking options;
	now title entry is "Step up and offer a blowjob for the winner, in trade for the water";
	now sortorder entry is 2;
	now description entry is "Trade a little mouth action for several bottles of clean water";
	[]
	if cocks of player > 0 and carried of water bottle > 0: [only males and herms can compete, and you need a bottle]
		choose a blank row in table of fucking options;
		now title entry is "Step up and ask to join the competition";
		now sortorder entry is 3;
		now description entry is "Compete with the guys in dick size";
	[]
	sort the table of fucking options in sortorder order;
	repeat with y running from 1 to number of filled rows in table of fucking options:
		choose row y from the table of fucking options;
		say "[link][y] - [title entry][as][y][end link][line break]";
	say "[link]100 - Nevermind[as]100[end link][line break]";
	while sextablerun is 0:
		say "Pick the corresponding number> [run paragraph on]";
		get a number;
		if calcnumber > 0 and calcnumber <= the number of filled rows in table of fucking options:
			now current menu selection is calcnumber;
			choose row calcnumber in table of fucking options;
			say "[title entry]: [description entry]?";
			if player consents:
				let nam be title entry;
				now sextablerun is 1;
				if (nam is "Casually observe their competition"):
					say "[SizeEnvy_Observe]";
				if (nam is "Step up and offer a blowjob for the winner, in trade for the water"):
					say "[SizeEnvy_BJ]";
				if (nam is "Step up and ask to join the competition"):
					say "[SizeEnvy_Compete]";
				now Size Envy is resolved;
				now Standard Maintenance is not resolved;
				wait for any key;
		else if calcnumber is 100:
			say "Break off the conversation?";
			if the player consents:
				now sextablerun is 1;
				say "     You step back from the group of young men and simply walk out of their temporary home.";
				now Standard Maintenance is not resolved;
				now Size Envy is resolved;
				wait for any key;
			else:
				say "Pick between 1 and [the number of filled rows in the table of fucking options] or 100 to exit.";
		else:
			say "Invalid Option. Pick between 1 and [the number of filled rows in the table of fucking options] or 100 to exit.";
	clear the screen and hyperlink list;

to say SizeEnvy_Observe:
	say "     Quietly strolling closer, you lean against a nearby wall from where you have a good view of the four young men.";
	say "[SizeEnvy_Strip]";
	WaitLineBreak;
	say "     'Okay, I win. Pay up, guys. Much as I'd love to offer you a chance at having a rub and seeing it in action, but we've got some company and don't want to escalate things here, do we?' Nicholas nods in your direction, causing the other guys to become aware of your presence and shove their dicks back into their pants with startled expressions. Except Milton, that is - he just opens a little pressure valve on his clockwork body and with a little hiss, the shaft of his brass cock shrinks to its original size. Their mall rat friend stays fully naked from the hips down while the guys go grab the water bottles they lost and hand them over, only then going to collect his pants and putting them back on. With a grin to you, he puts them in a backpack, then tells his friends, 'Come on guys, lets hang in the atrium.' Just a moment later, they're gone, leaving you behind in the store.";
	now MiltonRelationship is 1; [player knows his name at least]

to say SizeEnvy_Strip:
	say "     Milton is the easiest to measure as he doesn't wear any clothing at all. The clockwork fox wraps his fingers around the knotted cock hanging between his legs, pumping the flexible metal construct up and down and making quiet ticking and humming noises as he does so. The coppery flesh bends easily in his grasp and expands a little to reach a fully extended state, leaking clear lubricant from the tip that the mechanical young man rubs into his shaft. Nicholas smiles at his friend as he lays the tape measure on top of his dick, then announces, 'Nine inches. Nice one, man.' The clockwork fox grins back and gives his buddy a gentle fist-bump, then steps aside, still slowly stroking himself.";
	say "    'You next, Rob,' the mall rat tells the human hybrid, crooking his finger to make him step forward. Rob is a bit hesitant at first, looking to the other guys, then drops his trousers and reveals that his German Shepherd infection reaches all the way from the foot-paws to just below the navel, including a furry canine sheath that already has the tip of his shaft poking out. With a little bit of rubbing and stroking, he gets himself fully hard too, then presents the red rocket of his canine shaft to Nicholas. 'Eight inches,' the mall rat gives as his verdict a moment later, to which Rob replies, 'Yeah, but it's got a really nice knot too - that counts in bed, if you get my drift.' Nicholas raises his eyebrows and moves his hand to give his friend's knot a little squeeze, chuckling as the young man lets out a moan. 'I'll call it a nine, so you're even with Mil.'";
	WaitLineBreak;
	say "     Axel steps up confidently, rubbing a dick-shaped bulge in his jeans that stretches down one pants-leg. 'Time to finish this,' he says with a laugh, then pops the buttons of his jeans and shoves them down, making a massive equine shaft spring up as it is freed from confinement. The anthro donkey's dick is certainly an impressive piece of equipment, with weighty balls, a long, black shaft and flared head. He wraps his hand around it and strokes up and down until a gleaming drop of pre forms at the tip. Only then does he allow his buddy to lay the tape measure along the top of his shaft, to announce a moment later, 'Thirteen inches! Hung like a horse, even though he's a donkey.' Axel gives him a beaming grin, putting his hands behind his head and standing in a proud pose.";
	say "     'That doesn't mean you've won, you know,' Nicholas adds with a chuckle as he starts to undo his own baggy pants, drawing disbelieving glances from the other guys. 'See it and weep!' the mall rat calls in a teasing tone, then shoves his pants down his legs and kicks them off. The piece of man-meat hanging between his legs is almost monstrous, at least on a not quite five foot tall anthro rodent. It literally reaches his knee! Hanging his tape measure over one shoulder, the grinning mall rat strokes himself with both hands, getting the pinkish-white cock fully hard and erect. When he rolls out the measuring band over its top, everyone in the little group leans in to have a look - he's all of fifteen inches long. 'Damn, that's one big kahuna,' Milton says in a shocked tone, a sentiment that the other two guys fully share.";

to say SizeEnvy_BJ:
	say "     Quietly strolling closer, you lean against a nearby wall from where you have a good view of the four young men, then clear your throat. Rob, Axel and Milton are a bit startled as they see you, while Nicholas clearly was already aware of your presence. 'Yeah? What do you want?' he asks, a slight smile on his muzzle as he clearly expects a good answer. When you offer the four young men oral pleasure in exchange for the water that they were originally betting, they are only too happy to say yes[if cocks of player > 0], if only after some objections that you're a guy from Axel and Milton. Rolling his eyes, Nicholas brushes any hesitation aside with the argument, 'Hey guys. A blowjob is a blowjob. Doesn't matter who gives it, come on!'[end if] At that point you move right up to them, eager to watch the competition from a ringside seat.";
	say "[SizeEnvy_Strip]";
	WaitLineBreak;
	say "     'Okay, I win. Let's get some fun going with our new friend here [PosAdj of player]!' The guys step out of their lowered pants and crowd around you with eager expressions. Sinking to your knees, you find yourself presented with four hard cocks. On a whim, you reach for Axel first, holding up his equine shaft and licking over its head to taste the young donkey's sweet pre-cum. 'Fuuuck yeah,' he lets out in a pleased grunt, putting one hand gently on the top of your head to guide you closer. Suckling on his big rod, one hand wrapped around the base of his manhood, you reach out with the other one and take hold of Milton's flexible brass shaft. The clockwork fox holds his breath for a second, making the ticking of his body stop, then gives a groan, and a little spurt of clear lube shoots out of the tip of his cock.";
	say "     Curious about the fox's taste, you switch over to his cock and slowly take the head into your mouth - it is warm and slightly slippery with what you would guess to be almond oil. Not a bad taste for a guy to have. Suckling on his shaft, you make sure not to neglect Axel's length either, pumping its length with a firm grip at the same time. After a little while of going down on the mechanical fox, you pull back from him with an intentionally loud pop, then look around for the next contestant. Rob's red doggy bone comes into sight, but there already is someone's hand wrapped around it - and it isn't the hybrid boy's own! Glancing up, you see Nicholas smile broadly, then say in a low voice, 'Take care of them. We're good here.' The demi-human by his side is standing there with his eyes closed, biting his lip in pleasure and is simply holding on to Nicholas with one hand on his shoulder, but the mall rat clearly doesn't mind that their sexual interaction currently is only one way.";
	WaitLineBreak;
	say "     Getting back to your own erect studs, you hold their dicks up next to each other, licking back and forth between them again and again, your tongue slurping over the undersides of their hard lengths. As you do so, the two of them slowly inch closer to one another to allow you easier access - until eventually, their cocks bump heads. Hearing indrawn breaths from above, you glance up to see them staring at one another with wide eyes, hesitating for several long seconds before Axel throws his arm around his friend's shoulders and grunts out, 'Let's just enjoy this.' Milton lets out a little huff, then lays his own arm on Axel's shoulder in turn. Smiling a little to yourself about them pushing past at least that hangup, you guide their dicks together side by side, pressing them together so that you can lick them with one lick of your tongue.";
	say "     After more switching back and forth between their dickheads, suckling here and there, you eventually attempt to put both guys into your mouth at the same time. It takes quite a bit of effort to open your mouth wide enough and wedge the dickheads of the two friends in at the same time, but you do manage it - and the happy moans this earns you are well worth the trouble. Lips tightly stretched around their two dickheads, this gives you some freedom with your hands, which you use to reach for the balls of your two partners. Warm, furry, and quite a handful on one side, and firm, warm in a sun-heated metal kind of way on the other, you caress them with eager attention, really pushing their buttons. Between the sucking, rubbing against a friend's dick, and getting fondled, the two of them have no chance of holding back for very long, and soon, you can hear them pant out that they are getting close.";
	WaitLineBreak;
	say "     Intensifying your sucking even more to finish the guys off, you are rewarded by a thick and creamy spurt of equine cum, followed up by what seems like thick almond milk from the clockwork fox. By pure chance, their orgasms line up just right to have one blasting cum in the pause between spurts of the other one, meaning that you're exposed to a constant barrage of nut-milk from these two. With nothing else to do but chugging it down as quickly as they fill your mouth, you swallow everything the guys have to give you, leaving you full indeed by the time they run out of steam. When you finally pull back from their dicks and turn around to check on the other two guys, you are just in time to hear Rob groan out loud, then blast you straight across the forehead with his load. Spurt after spurt covers your face and you quickly have to clench your eyes so he doesn't hit them too.";
	say "     You don't see anything for a little while, not daring to open your eyes, then someone uses a towel or something to dab at your face, wiping off the canine cum around your eyes. Slowly opening your lids, you see that it was Nicholas, who gives you a somewhat shame-faced smile. 'Sorry about that. I was aiming him at your shoulder, then suddenly you turn your head, and... well, things were too late to stop after that first blast hit your forehead. And your face covered with Rob's load looked pretty hot too, to be honest. But now, think you could finish me off? Haven't cum yet myself.' Laughing about the horny mall rat's focus on his dick, you open your lips and catch the end of his massive prick between your lips, then start bobbing up and down on it. He clearly is quite aroused from handling his friend's canine cock earlier, as it doesn't take long at all to get Nicholas to reach his own orgasm, blasting thick spurts of cream down your throat to join the cum of his friends.";
	WaitLineBreak;
	say "     'After catching his breath, Nicholas says, 'Time to pay up.' Rob, Axel and Milton have made themselves presentable again already in the meantime, so they just go grab a bottle of water each from their packs, bringing it back to hand to you. Their mall rat friend stays fully naked from the hips down, unconcerned with his giant dick swinging between his legs as he goes to grab his pants, then pulls out one more water bottle from one of the large side pockets. This leaves you with a nice and even number of pure water bottles. While you pack them away and clean yourself up, the mall rat thanks you, then tells his friends, 'Come on guys, lets hang in the atrium.' Just a moment later, they're gone, leaving you behind in the store.";
	PlayerDrink 20;
	PlayerEat 20;
	LineBreak;
	say "[bold type]You gain 4 water bottles![roman type][line break]";
	increase carried of water bottle by 4;
	now MiltonRelationship is 1; [player knows his name at least]

to say SizeEnvy_Compete:
	say "     Quietly strolling closer, you lean against a nearby wall from where you have a good view of the four young men, then clear your throat. Rob, Axel and Milton are a bit startled as they see you, while Nicholas clearly was already aware of your presence. 'Yeah? What do you want?' he asks, a slight smile on his muzzle as he clearly expects a good answer. When you pull out a bottle of water from your pack and tell the young men that you wanna join in, they look surprised, but agree to let you compete after a little bit of murmuring between them. With a grin on your face, you move right up to them, eager to participate.";
	say "[SizeEnvy_Strip]";
	WaitLineBreak;
	if cock length of player > 15: [player wins]
		say "     With a confident grin on your face, you pull out your own [cock of player] manhood, jerking its length before the gathered friends. 'Fucking hell,' Rob groans as he sees what you bring to the competition, and even Nicholas gives you a respectful nod after he measures your erection. '[cock length of player] inches, I'm impressed. Guess we have a winner, guys. Time to pay up.' Rob and Axel quickly shove their dicks back into their pants with startled expressions and walk off to get your payment. Meanwhile, Milton just opens a little pressure valve on his clockwork body, allowing the shaft of his brass cock to shrink to its original size with a soft hiss, then also goes to get a water bottle from his pack. Their mall rat friend stays fully naked from the hips down, stroking himself gently before leaning a bit closer to you and whispering, 'This never was about the water. I don't begrudge you the win. And thanks for showing your piece. It's a good one.'";
		say "     As the others start to come back, Nicholas winks at you, then grabs his own pants and pulls a bottle from one of the many pockets on it, handing it to you. One by one, the young men do the same, leaving you with a nice and even number of pure water bottles. While you pack them away, the mall rat tells his friends, 'Come on guys, lets hang in the atrium.' Just a moment later, they're gone, leaving you behind in the store.";
		LineBreak;
		say "[bold type]You gain 4 water bottles![roman type][line break]";
		increase carried of water bottle by 4;
	else if cock length of player is 15: [evenly matched]
		say "     With a confident grin on your face, you pull out your own [cock of player] manhood, jerking its length before the gathered friends. 'Fucking hell,' Rob groans as he sees what you bring to the competition, and even Nicholas gives you a respectful nod after he measures your erection. '[cock length of player] inches, I'm impressed. Guess we're evenly matched, so let's split. You keep your stake and get one more, I'll take the rest. Okay guys, time to pay up.' Rob and Axel quickly shove their dicks back into their pants with startled expressions, then walk off to get your payment. Meanwhile, Milton just opens a little pressure valve on his clockwork body, allowing the shaft of his brass cock to shrink to its original size with a soft hiss, then also goes to get a water bottle from his pack.";
		say "     Their mall rat friend stays fully naked from the hips down, stroking himself gently before leaning a bit closer to you and whispering, 'This never was about the water. I don't begrudge you half the pot. And thanks for showing your piece. It's a good one.' As the others start to come back, Nicholas winks at you, then grabs his own pants and pulls a bottle from one of the many pockets on it, handing it to you. One by one, the remaining young men give him their bottles, leaving him with a nice armful of pure water bottles. After stuffing them into his backpack, the mall rat tells his friends, 'Come on guys, let's hang in the atrium.' Just a moment later, they're gone, leaving you behind in the store.";
		LineBreak;
		say "[bold type]You gain 1 water bottle![roman type][line break]";
		increase carried of water bottle by 1;
	else if cock length of player > 8: [third place]
		say "     Putting on a confident expression, you pull out your own [cock of player] manhood, jerking its length before the gathered friends. 'Fucking hell,' Rob groans as he sees what you bring to the competition, and even Nicholas gives you a respectful nod after he measures your erection. '[cock length of player] inches, not bad at all, but I still win. Okay guys, time to pay up.' Rob and Axel quickly shove their dicks back into their pants with startled expressions, then walk off to get your payment. Meanwhile, Milton just opens a little pressure valve on his clockwork body, allowing the shaft of his brass cock to shrink to its original size with a soft hiss, then also goes to get a water bottle from his pack.";
		say "     Their mall rat friend stays fully naked from the hips down, stroking himself gently before leaning a bit closer to you and whispering, 'This never was about the water, to be honest. Thanks for showing your piece. It's a good one.' As the others start to come back, Nicholas winks at you, then accepts the stakes of each of his friends, and finally your own bet, leaving him with a nice armful of pure water bottles. After stuffing them into his backpack, the mall rat tells his friends, 'Come on guys, let's hang in the atrium.' Just a moment later, they're gone, leaving you behind in the store.";
		LineBreak;
		say "[bold type]You lose 1 water bottle![roman type][line break]";
		decrease carried of water bottle by 1;
	else:
		say "     Somewhat nervous about exposing yourself in what turned out to be a group of very big boys indeed, you pull out your own [cock of player] manhood, jerking its length before the gathered friends. 'Finally someone smal-' Rob starts to say, then clamps his hand in front of his mouth, getting red-faced. Nicholas simply gives you an encouraging smile and comes closer to measure your erection. '[cock length of player] inches, not bad at all, but that still leaves me the undisputed winner. Okay guys, time to pay up.' Rob and Axel quickly shove their dicks back into their pants with startled expressions, then walk off to get your payment. Meanwhile, Milton just opens a little pressure valve on his clockwork body, allowing the shaft of his brass cock to shrink to its original size with a soft hiss, then also goes to get a water bottle from his pack.";
		say "     Their mall rat friend stays fully naked from the hips down, stroking himself gently before leaning a bit closer to you and whispering, 'This never was about the water, to be honest. Thanks for showing your piece too. No need to be self-conscious just because we're bigger. It all depends on how you use em, right?' As the others start to come back, Nicholas winks at you, then accepts the stakes of each of his friends, and finally your own bet, leaving him with a nice armful of pure water bottles. After stuffing them into his backpack, the mall rat tells his friends, 'Come on guys, let's hang in the atrium.' Just a moment later, they're gone, leaving you behind in the store.";
		LineBreak;
		say "[bold type]You lose 1 water bottle![roman type][line break]";
		decrease carried of water bottle by 1;
	now MiltonRelationship is 1; [player knows his name at least]

Standard Maintenance is a situation. Standard Maintenance is resolved.
The sarea of Standard Maintenance is "Smith Haven".

Instead of resolving a Standard Maintenance:
	say "     Wandering the hallways of the Smith Haven Mall, you pass through crowds of all sorts of people: lots of mall rats and countless other species, demi-human hybrids, as well as very rare pure humans. Curiosity makes you stroll in and out of the various stores - some are occupied by the refugees, others lay abandoned. Eventually you wander into a place you have been in before, when you saw those four young men comparing their dick sizes. By pure chance, one of the guys actually is there too[if MiltonRelationship > 0] - Milton[end if], the clockwork fox. He is sitting cross-legged on a large white mat, bent over forward as he disassembles his foot-paw, spreading countless little cogs and pieces of machinery out around him. A spray-can in his hand hisses a little as he uses the compressed air inside to clean his mechanical parts.";
	say "     [bold type]What do you want to do now?[roman type][line break]";
	LineBreak;
	say "     ([link]Y[as]y[end link]) - Walk up and try to start a conversation.";
	say "     ([link]N[as]n[end link]) - Leave him to his work.";
	if player consents:
		LineBreak;
		say "     Moving closer, you say hello to the clockwork fox and he glances up at you, his mechanical parts clicking a little as he moves. 'Oh hey, um - [if MiltonRelationship > 0]we never really got introduced, did we?' [else]you're new here, aren't you?' [end if]he asks, to which you shake your head. 'Well, I'm Milton. I'd get up, but as you can see, I'm a bit out of commission right now.' Waving him down to stay sitting, you tell him your name in turn, then take a cross-legged pose across the field of gears. 'So[if player is not defaultnamed], [name of player][end if] - what brings you [if MiltonRelationship > 0]back [end if]here? Wanted to learn a bit of fox mechanics? I can tell you one thing: This is not as uncomfortable as it may look.' He raises his disassembled leg a little, tapping this part or that. 'Here are the structural members, joints and whatnot, while the moving parts are currently spread out here. This new body is a mechanical marvel - and the gears re-grow if I lose any. But sadly, the amazing abilities somehow do not include any way to get grit and dust out of the works...'";
		say "     He explains more details of his body to you as he slowly reassembles himself, pushing the pieces back into place to see them instantly snap into motion with smooth precision. Apparently he learned in the first few days after his infection that he can actually just take pieces of himself apart and put them back together, as long as the separate parts stay within about 3 feet of his body. The concept is strange, but fascinating, and somehow it feels good to just spend a while talking to the bright young man, even if he is made of metal. When he eventually is all the way assembled again, Milton stands up and gives you a smile and a handshake, then packs up his gear. With the words, 'It was nice talking to you. Hope to see you sometime again,' the young man soon sets out into the hallways of the mall, most likely to find his friends.";
		SanBoost 5;
		now MiltonRelationship is 2; [two-sided introductions, and a nice chat]
	else:
		LineBreak;
		say "     You quietly watch him for a few seconds longer, then shrug and continue on your way. Eventually, you reach the point of the mall where you started your little exploration tour.";
	now Standard Maintenance is resolved;

Inner Mall Events ends here.
