Version 1 of Razorback Boar by Wahn begins here.
[Version 1 - New Creature]

"Adds an Razorback Boar to Flexible Survival's Wandering Monsters table, With Impreg chance"

[ RazorbackBoarEvents                                               ]
[  0: never met                                                     ]
[  1: player saw him take on Andrew and his wolf buddies            ]

RazorbackBoarEvents is a number that varies.

when play begins:
	add { "Razorback Boar" } to infections of guy;

Section 1 - Razorback Fury Event

Razorback Fury is a situation. The level of Razorback Fury is 7.
The sarea of Razorback Fury is "Forest".
when play begins:
	add Razorback Fury to badspots of guy;
	add Razorback Fury to badspots of furry;

Instead of resolving a Razorback Fury:
	say "     You hear crashes, shouts and howls from somewhere nearby in the dense forest - sounds like there's quite a scuffle going on. Curiosity drives you to investigate and you walk towards the fight in a slow pace, doing your best to be stealthy. Soon, a small clearing comes into sight - and in it, three anthro wolves and an anthro boar. A very angry anthro boar, with the coarse fur on his bulky yet powerful body bristling. Looking at the thick mane that starts at his head and runs halfway down his back in a raised ridge, it is immediately obvious that this isn't a docile pig - no, you're seeing a feral razorback! He doesn't seem to believe in wearing clothing (not that he has to, with a coat of fur) and is holding one of the wolves raised by his throat, half a foot off the ground. The other two canines lie on the forest floor, one of them knocked out completely, the other whimpering and holding a broken arm.";
	say "     The boar shakes his captive and growls at him, then says in a snarky tone, 'So how did you think this was gonna go, punk? You and your little buddies become wolves and think you're the top dogs now?' The only reply is a choked gurgle from the wolf - which might have something to do with the razorback pig holding him a bight tight by the throat. 'Bah! Wannabes - I could see it on you a mile away! You become animals and then go trampling into MY forest while still wearing designer jeans?! Humanity is gone, dip-shit!' With that, the boar slams the roughed-up wolf against the trunk of a nearby tree, then lets go of him, sending the canine to collapse at his feet. After a few coughs and groans, the wolf looks up fearfully at the guy standing over him and says, 'Look, we were just gonna...'";
	say "     [WaitLineBreak]";
	say "     The boar scoffs, 'I could hear you idiots!' His captive winces as the standing feral pig pitches his voice high and says, 'We're predators - so let's hunt. I heard there are pigs in this area. How about some fresh pork, eh? Yeah, totally man - I could eat one whole!' Looking left and right for a way to escape, the bruised canine scrambles backwards - only to bump against the tree behind him. 'I - em... sorry! Please, I - I...' he whines as the boar steps closer. 'You're in luck, boy. Because Garth *he thumps his chest* is a really nice guy. So I won't grind you into paste. Tell me - what's your name, punk?' The intimidated wolf is pretty quick to gasp out 'Andrew, S-Sir', looking wide-eyed at the boar standing over him. 'Okay Andy, you're learning. As a reward you'll even get something to fill your stomach! ' And with that, the razorback boar lowers a hand to his crotch, taking hold of the thick shaft dangling between his legs. 'Now open that muzzle wide, you're getting some pig in your moth after all. And don't even think about biting me, little fucker!'";
	say "     Shocked at the unexpected turn to their hunting trip, the wolf whines and opens his mouth - most likely to plea with his captor some more, but the boar doesn't give him any chance to do so. One hand on the back of the would-be predator's head and guiding his erection with the other one, the muscled wild pig starts to face-fuck his captive, transforming anything he might have wanted to say into gurgles around the piece of man-meat sliding in and out. Garth uses the wolf for a hard, no nonsense dicking, just hammering into him till the poor guy's nose is ground into the bush of his pubes and the weighty balls below slap his chin. Again and again does he thrust his hips forward while holding his captive tight, filling the little clearing with the sounds of sex. Before much longer, his arousal reaches a high point and the razorback slams his cock deep and holds it there, grunting with each shot of cum he pumps down Andrew's throat.";
	say "     [WaitLineBreak]";
	say "     Garth's orgasm lasts quite a long moment and you guess that his captive his getting a stomach-full of the boar's seed - the wild pig is quite a virile guy, it seems. This even goes on to get Andrew into a bit of trouble... breathing that is, as the thick piece of meat in his throat blocks replenishing his air supply. Unable to pull away as his head is tightly gripped by the climaxing boar, the wolf can only push against Garth's hips weakly, then more and more insistent until finally his captor relents and lets go, allowing Andrew to collapse on the ground and gasp for breath. 'Got a nice tight throat on you boy,' comes the gruff laugh from Garth as his cock continues to spurt the slowly ebbing blasts of cum - which the anthro boar aims right at the wheezing wolf, matting his fur in streaks of sticky semen.";
	say "     'Jeez, get over it already. You're a wolf, not a pussy,' the razorback boar scoffs as Andrew stays hunched over and panting for another full minute. Right until Garth turns him over with the cloven hoof at the end of his muscled, stocky leg. The wild pig laughs as he sees that Andrew's skin-tight designer jeans are tented out at the front, so much so that the wolf must be feeling quite a pinch. 'So that's how it is, eh? Little wolfie got off on being the prey. Hah, how pathetic. Now take your buddies and get out of my forest. And don't you dare think you can rub one out on the way and soil the ground around here with that weak-ass cum of yours!' Shame-faced, Andrew picks himself up and walks over - in a hunched-over gait that takes at least a little pressure off his crotch - to his friend with the by-now healed arm. Together, they pick up their unconscious compatriot and stumble away out of the clearing. You're quick to follow suit - in another direction though - so that the boar doesn't detect you as well.";
	now Razorback Fury is resolved;
	now RazorbackBoarEvents is 1;
	repeat with y running from 1 to number of filled rows in table of random critters:
		choose row y in table of random critters;
		if name entry is "Razorback Boar":
			now monster is y;
			now area entry is "Forest";
			break;
	
Section 2 - Monster Responses

to say RazorbackBoar wins:
	if hp of player is greater than 0: [player surrendered]
		say "     'That's right - submit like you should. I don't enjoy punching someone's nose in, you know. The sooner everyone realizes that I'm tougher than them the better,' Garth the razorback boar tells you in a gruff voice, ";
	otherwise: [player got clobbered]
		say "     'Could have told you that's how it was gonna end,' Garth the razorback boar scoffs as you collapse on the ground. He steps up right next to you, the ground shaking a little under his cloven hooves as the stout and muscled boar stomps around demonstratively. 'I don't enjoy punching someone's nose in, you know. The sooner everyone realize that I'm tougher than them the better.' he adds in a gruff voice, ";
	say "then pulls you over to stand straight before him. 'Let's have a look what we got then,' come his next words, then he quickly pulls off your gear and clothes, casually throwing them to the side to land in a small pile. A plus point is that he put them on a patch of grass in the clearing, and seemingly took the effort to not break anything - demonstrating that he's a tough guy, but not as much of an asshole as some in the city. Finally, you're bare-ass naked in front of him, ready to be inspected.";
	if cunts of player > 0: [female and herm]
		say "     Sliding a hand between your legs, he brings it up to brush over your pussy, stroking along the folds of your sex and searching out the sensitive little clit at the top. As you moan at the stimulation, he grins broadly and says, 'Yeah, that's just what I need baby. Being out and about in my territory - my forest - always gets my blood pumping. And as for where it's being pumped to...' Knowing very well how things work in this crazy city, you don't have to look down to know that he's holding his dick in hand - but you do anyways, taking in the thick and long shaft the powerful boar sports. That'll definitively leave you walking funny for a while, as you have little doubt that he knows exactly what he's doing with his manhood.";
		say "     [WaitLineBreak]";
		say "     'I love that things are back to the basics these days. The way nature intended them to be. You live, you eat, you... breed,' Garth tells you, wiggling his bushy eyebrows expressively as he says the last word. 'Come here sweet-cheeks,' he adds a moment later, drawing you close to give you a rousing kiss. As the mighty razorback makes out with you, his hands wander over your body, stroking and squeezing. Something about being in the arms of such a big and burly being makes you rather horny - and eager to comply, kissing him back with lusty intensity. An idle thought in your head tells you that part of it must be caused by his scent - a heady mixture of spicy notes and pheromones - but then... you don't care all that much right now. It just feels nice to be desired by the broad-shouldered wild pig, and you tongue-wrestle with him as he picks you up.";
		say "     Carrying you in his strong arms, Garth makes a few steps until reaching the nearest tree, against the smooth bark of which you soon find your back being pressed. The anthro razorback gives a lusty grunt and kisses you again deeply, then you feel the hot tip of his shaft nudging apart your nether lips. With a bellowing roar, he thrusts up into you, sinking his erection deep. 'Oh YEAH!' *thrust* 'You got one.' *thrust* 'Sweet pussy!' *thrust* Garth grunts out between each new penetration into your innermost depths, driving you wild with the sheer girth and length of his erection. The wild pig is an energetic lover with quite a bit of stamina, pounding into you tirelessly while still making out like a storm.";
		say "     [WaitLineBreak]";
		say "     You don't really know how long your mating lasted, just that you reached multiple orgasms during his sexual onslaught and that you pulled some tufts of hair off his back-fur at the height of this climax or that. Garth just takes it all in stride, plenty tough enough to just endure the thrashing of his sexual partners. He works his thick rod in and out of your hole with undiminished energy the whole time, making it good for both of you until eventually the point of no return is reached. With a deep grunt, he sinks himself in one last time, then holds still as the first throb of his seed splashes into your womb, followed by another and another.";
		say "     The virile boar cums - a lot - and is still pumping more sperm into you by the time other males would already be ready to doze off after sex. It is so much that you do feel a bit stuffed when he eventually does stop coming, then slowly carries you over to the patch of grass on which your gear lies. Lowering you to the ground, Garth plants another deep kiss on your lips, then finally slides his softening shaft out of your pussy, smiling at the gush of cum that comes with it. 'You're definitively a hot lay, babe. Come back again to my territory when you need that itch scratched again. And I'd love to meet all my new little piglets, if it takes.' With that said, the boar-man pats your stomach lightly and gets up, then walks off into the forest.";
		say "     [impregchance]";
	otherwise:
		if cocks of player > 0: [male]
			say "     Leaning back a little, Garth has a look at your crotch and huffs as he sees your manhood. 'Hmpf - another dude trying to move in on my territory. There already are few enough females to breed out here so that's just what I need.' Sarcasm almost drips off his last comment. Then he continues, 'Well dude... you're a bit out of luck. Its just me you're gonna get today, no big-breasted babes. You see - being out and about in my territory always gets my blood pumping. And as for where it's being pumped to...' Knowing very well how things work in this crazy city, you don't have to look down to know that he's holding his dick in hand - but you do anyways, taking in the thick and long shaft the powerful boar sports. 'Since you got me all excited, I'll just have to make use of you another way.'";
		otherwise: [neuter]
			say "     Leaning back a little, Garth has a look at your crotch and huffs as he sees your manhood. 'What the hell? Where's your bits? Some freaky dude moving in on my territory, that's just what I need.' Sarcasm almost drips off his last comment. Then he continues, 'Well... you're a bit out of luck. Its just me you're gonna get today, no big-breasted babes. You see - being out and about in my territory always gets my blood pumping. And as for where it's being pumped to...' Knowing very well how things work in this crazy city, you don't have to look down to know that he's holding his dick in hand - but you do anyways, taking in the thick and long shaft the powerful boar sports. 'Since you got me all excited, I'll just have to make use of you another way.'";
		say "     [WaitLineBreak]";
		say "     Pushing down on your shoulders in a slow yet unyielding manner, the razorback boar forces you to your knees and holds out the erection between his legs for you. He is really quite hung and has weighty balls too. But that's far from all of it - as he pulls your head closer with a strong hand, the full intensity of Garth's scent hits you... a heady mixture of spicy notes and pheromones that makes your arousal sour and the thought of just giving in to the burly male become more and more attractive. You're pulled out of your thoughts by him smacking his shaft against your forehead gently, paired with the impatient grunt of, 'Go on, get sucking!' With the state of mind you're in right now, there is no hesitation before you got your lips opening to slide over his cockhead, then further down along his weighty shaft.";
		say "     With a satisfied grunt, the boar puts a hand on your head to guide you as you go down on him, stroking your head as he does so. 'Yeah, and play with my balls too,' comes the next command pretty soon, prompting you to raise your hands and brush them along his furry thighs to cup his balls. Slurping on Garth's massive shaft and fondling his sperm-factories, you surprise yourself a bit with the eagerness to service this powerful being. Though as an idle thought tells you - there is a definite animal magnetism to him that just can't be denied. And so you give Garth a blowjob that soon leads over to him all-out face-fucking you as arousal starts to mount, ultimately culminating in him giving a lusty roar and ramming his shaft down your throat and letting loose a deluge of cum to fill your stomach. It just seems like there is no end to the pulsing of his rod, with throb after throb of virile seed shooting through it.";
		say "     [WaitLineBreak]";		
		say "     The virile boar cums - a lot - and is still pumping more sperm into you by the time other males would already be ready to doze off after sex. It is so much that you do feel sated as if you just had a heavy meal, and your air supply is getting a bit low too. Finally, there is little choice but to either pull off his shaft or pass out, so you plant both hands on his hips and give a push away from him, breaking the boar's hold on you. As you fall back on your ass, coughing and gasping, Garth's erection keeps spurting several more long spurts of seed into the ground before his orgasm slowly starts to wind down. 'Phew, I really needed that,' the anthro pig finally groans, then looks down at you and adds, 'Oh, sorry for getting a bit carried away. But hey - small price for you trespassing, eh?' With that said, the boar-man gives you a satisfied nod and walks off into the forest.";

To say RazorbackBoar loses:
	say "     Crashing to the ground with a grunt and an audible thump, the bruised boar-man pushes himself up halfway on his elbow and looks up at you. He has to pant a few times before being able to say, 'Okay, you're quite a tough one yourself. I admit that.' As he proceeds to stand up again, Garth then adds, 'Not that I'm beat or anything, but at some point one has to evaluate the situation. Wouldn't do for both of us to totally wear each other out, then have some little pissant like those good-for-nothing wolves come sniffing around and take advantage. So...' The razorback boar looks you up and down appraisingly and huffs out, 'I'll overlook your trespassing. It's still my forest, you know. Or did you want... something else?";
	say "     The twitch of Garth's thick shaft as it dangles between his legs clearly illustrates that he meant some sexy fun with his last comment. What do you do?";
	say "     ([link]Y[as]y[end link]) - Have sex with him.";
	say "     ([link]N[as]n[end link]) - Just go on your ways.";
	if player consents:
		say "     [line break]";
		say "[RazorbackBoarSexMenu]";
	otherwise:
		say "     [line break]";
		say "     Waving the boar-man's offer off, you walk away from him, soon losing sight of the anthro razorback between the dense trees.";

to say RazorbackBoarSexMenu:
	now sextablerun is 0;
	blank out the whole of table of fucking options;
	[]
	if (cocks of player > 0):
		choose a blank row in table of fucking options;
		now title entry is "Take him from behind";
		now sortorder entry is 1;
		now description entry is "Push Garth against a tree and really pound into him";
	[]
		choose a blank row in table of fucking options;
		now title entry is "Ride Garth's thick shaft (anal)";
		now sortorder entry is 4;
		now description entry is "Power-bottom the boar-man";
	[]
	if cunts of player > 0:
		choose a blank row in table of fucking options;
		now title entry is "Ride Garth's thick shaft (vaginal)";
		now sortorder entry is 4;
		now description entry is "Take the boar-man in your pussy";
	[]
	sort the table of fucking options in sortorder order;
	repeat with y running from 1 to number of filled rows in table of fucking options:
		choose row y from the table of fucking options;
		say "[link][y] - [title entry][as][y][end link][line break]";
	say "[link]100 - Nevermind[as]100[end link][line break]";
	while sextablerun is 0:
		say "Pick the corresponding number> [run paragraph on]";
		get a number;
		if calcnumber > 0 and calcnumber <= the number of filled rows in table of fucking options:
			now current menu selection is calcnumber;
			choose row calcnumber in table of fucking options;
			say "[title entry]: [description entry]?";
			if player consents:
				let nam be title entry;
				clear the screen and hyperlink list;
				now sextablerun is 1;
				if nam is "Take him from behind":
					say "[RazorbackBoarSex1]";
				if nam is "Ride Garth's thick shaft (anal)":
					say "[RazorbackBoarSex2]";
				if nam is "Ride Garth's thick shaft (vaginal)":
					say "[RazorbackBoarSex3]";			
				wait for any key;
		otherwise if calcnumber is 100:
			say "Break off?";
			if the player consents:
				now sextablerun is 1;
				say "     You step back from the gruff boar-man, shaking your head slightly as he gives a questioning look.";
				wait for any key;
			otherwise:
				say "Pick between 1 and [the number of filled rows in the table of fucking options] or 100 to exit.";
		otherwise:
			say "Invalid Option. Pick between 1 and [the number of filled rows in the table of fucking options] or 100 to exit.";
	clear the screen and hyperlink list;
	
to say RazorbackBoarSex1: [Pounding against a tree]
	say "     Throwing off your clothes in mere moments, you chuckle that you indeed want something from him and you step up to the boar-man. You dig a hand into the bristly fur over his neck to pull the gruff guy close for a demanding kiss. Then you wrench his bulky form around and give him a forceful shove, making Garth stumble against the nearest tree. As his large hands thud against its bark to catch himself, you're behind the wild pig eye-blink later with your erection leading the way, pressing against his firm buttocks. The pink ring of his pucker still has the looks of what might be virgin territory, a strong and firmly muscle as you push against it testingly. Looks like he really is straight - or at least not a bottom usually. Rubbing your erection up and down between his cheeks draws a gruff grunt from Garth, joined a moment later by the comment, 'So you're an ass-bandit, eh? No wonder you were extra motivated to fight! I know you dudes can't resist my animal magnetism, hah!' Proving him right, you thrust into the strong male's tight hole at just that moment, making him roar at the sudden anal invasion.";
	say "     Garth's pucker only yielded to the pressure of a full-on thrust with your hips, so your first penetration actually goes balls-deep from your momentum, complete with a meaty slap of your balls against his furred ass. He feels so very warm and snug to be in, the tightly gripping chute of a dominant male pushed into putting out makes your blood boil with arousal. And so you pull back till just your cockhead is inside his tightly-stretched opening, then hammer in again and again, making hard use of your partner's back door. Garth grunts and groans as he is getting fucked - some of them with a wincing undertone at the somewhat painful stretching at first. Being the tough guy he is, the razorback just takes everything you can give and after a short while you think you can hear lust outweighing everything else in his bellows.";
	say "     [WaitLineBreak]";
	say "     Grunts and slapping noises of your hips against Garth's ass echo throughout the forest, coming in a rapid pace as you fuck him deeply without restraint. That tight hole of his just feels soo good, as do the muscles of his stocky body as you hold on to him and press against his back. Lust has you in its grip so tightly that you think of little else but sliding in and out of your partner... so much so that you find yourself surprised by him gripping your right wrist with his hand, pulling your arm around himself and further down until it comes to rest on his crotch. 'You were getting a bit carried away there, buddy. Have some decency and give a guy a reacharound if you're pounding his ass, eh?' Garth grunts, then squeezes his ass extra tight around your cock for a second. The thick rod of his erect shaft rests hotly against your skin and you take the hint to grip it, jerking the aroused wild pig in rhythm with your own thrusts. You can feel his manhood twitch and pulse each time you give him an especially deep thrust - no matter what his orientation, pounding Garth's prostate has a definite effect.";
	say "     In a wild and exhilarating ride, you drive the big man closer and closer to the edge, his grunts and moans coming quicker and becoming even deeper, more filled with urgency. Not having any shame at coming to enjoy this kind of sex, the anthro razorback even starts to shout, 'Yeah, you bastard! Faster! Hit that spot hard! Again! Ngh - Nnngh! More! NnnnngggghhhHH!' With that last drawn-out roar, Garth starts to cum, his shaft rhythmically pulsing in your hand as stream after stream of cum blasts through it and splashes the tree-trunk he's leaning against. With each spurt of the boar's seed, all the muscles in Garth's body twitch and tense - including those inside his ass, around your shaft. This results in you joining your stocky partner in orgasm just moments later, gripping him tightly around the hips as your balls start to unload everything they got. Your seed gets pumped into the anthro animal guy in weighty bursts, filling him up with creamy cum.";
	say "     [WaitLineBreak]";
	say "     After blasting the last few spurts of your orgasm into Garth, you pull out of him with a slurp. A string of cum connects your cockhead to his puckered hole for a second before it snaps, then more of your seed starts to leak out of his slightly gaping hole. The sight makes your heart beat faster for a second - a visible proof that you bred this powerful male. As the first white droplets fall on the ground, Garth looks over his shoulder and grunts, 'Made quite a mess back there. I'll have those damned chipmunks following me around all day again. Persistent little butt-munchers, I tell you. They just can't get enough of the stuff.'";
	say "     Despite his gruff tone, the boar-man seems to be looking forward to having his ass eaten. Maybe he doesn't have to wait, with you here?";
	say "     ([link]Y[as]y[end link]) - Eat your load from his ass.";
	say "     ([link]N[as]n[end link]) - Just go on your ways.";
	if player consents:
		say "     [line break]";
		say "     Crouching down behind the wild pig, you rub the base of his tail and make him pant in pleasure at that tough, then set both hands on his firm buttocks. Feels great to just touch them, hard muscle under a layer of fur. Spreading Garth's buttocks, you then push your face in between them, sticking out your tongue to lick his gaping hole. Slurping up the first trickle, the taste of sperm fills your mouth and you hum with pleasure as you swallow. 'Yeah, eat that ass!' Garth replies with obvious pleasure, grinding his hips back against you and making more creamy cum leak out. You spend some more time tonguing his hole, even going on to use your fingers too, swallowing every drop of your earlier deposit into the boar.";
		say "     Still licking and teasing his by now quite relaxed hole (despite there being no cum left), you play a bit longer with Garth. Using your hands to stroke him and fondle his balls, the guy even gets half-hard once again - but he eventually pulls away from you. 'You're great at this, thanks. But... I gotta go. Can't fuck away the whole day, you know. Come by again sometime.' And with that, the naked razorback boar stalks off into the forest.";
	otherwise:
		say "     [line break]";
		say "     Patting the boar-man on the shoulder, you go to grab your gear and clothes, then go on your way after dressing again.";
	
to say RazorbackBoarSex2: [riding him (anal)]
	say "     Chuckling that you indeed want something from him, you step up to the boar-man and dig a hand into the bristly fur over his neck, pulling the gruff guy close for a demanding kiss. Then you put your hands on his shoulders, pressing down and pant out that he should lay down. Chuckling at your urgent tone, the burly boar-man follows suit, stretching out on the ground as you quickly get rid of your gear and clothes, then step up to stand over him in all your naked glory. As you spit in your hand and proceed to lube your own asshole with it, the razorback boar comments, '[if cunts of player > 0]Going for anal, eh babe? Fine by me. I'm more of a pussy guy admittedly, but any tight hole is a sweet thing.'[otherwise]Going for anal, eh dude? Fine by me. Now don't misunderstand me - I'm not really an ass bandit, but... I definitively won't say no to a nice and tight hole.'[end if] As he says this, Garth's thick prick fills out more and more, hardening to a towering shaft of erect man-meat. The razorback boar proudly strokes his cock, waving it towards you and winks with broad grin on his face.";
	say "     Eager to make use of the oh so willing boar-man, you feast your eyes on his stocky yet quite muscular body once more, then eventually crouch down over his crotch. Garth strokes the insides of your thighs with his strong hands while you reach down between the two of you, grasping his thick shaft and giving it several long strokes. Just feeling the girth of his member gives you tingles of anticipation, so you quickly smear the copious pre-cum oozing from his cockhead over the towering pole and then move your ass into position right above it. Relaxing your opening, you press down against the horny boar-man until he pops into you, making both of you moan loudly at the sensations of the penetration. '[if cunts of player > 0]Yeah, ride that dick baby! Nnnggh - you feel nice and warm,'[otherwise]Yeah, ride that dick dude! Nnnggh - show me what your boipussy can take,'[end if] Garth grunts in a husky voice as you sink deeper on his erection. His hands move to your hips, stroking their sides while Garth [if cunts of player > 0]looks up at you, his eyes hungrily taking in your whole body.[otherwise]leans his head back, closing his eyes to focus on your hole's tight grip on his dick.[end if]";
	say "     [WaitLineBreak]";
	say "     After slowly working your way down on the razorback boar's thick piece of man-meat, you eventually feel the bristly pubes of your former opponent press against your buttcheeks. Yeah, you've taken all of him - balls-deep in your asshole, the strong and stocky male gives you a quite nice feeling of fullness. Resting like this and taking in the ridges and bumps of his cock, the sensation of his hot shaft pressing against more than a few 'magic' spots inside you, you're already very satisfied with your decision of using the very willing boar for your enjoyment - but there's a lot more fun to come. Looking down upon the razorback pig, you lean forward and plant your hands on his broad, pretty firmly muscled chest and brace yourself, then start sliding your ass up again. Garth's eyes [if cunts of player < 1]open and [end if]focus on your own with a wild intensity of barely contained lust and the big man shows a wide grin, exposing his sharp tusks as he grunts deeply.";
	say "     His grip on your hips tightens as you go on and on until just the tip of his erection is inside you, though he just moves his hands with you, not actually pulling or pushing in any way. Looks like he has enough self-control to keep his urges to rut you like a wild beast in check - for now. You can't help but grin at having won out over the hunk of a guy and decide to push his buttons a bit, pinching Garth's nipples and squeezing his abs, then start rocking up and down on his thick prick. Moans and gasps fill the little clearing in the forest as you ride the razorback, taking his meat all the way in quick succession. Before long, the sensations of being inside your tight ass erode Garth's resistance more and more and he begins taking a more active role in the coupling, humping his hips up to meet yours, with his balls smacking against your ass with satisfying thuds.";
	say "     [WaitLineBreak]";
	say "     Bouncing up and down on the wild pig's cock you have one hell of a nice time, as his manhood nudges all the right places and stretches your chute tight around it. With your libido in roaring heat, your hands fly to your own crotch and proceed to [if cunts of player > 0]caress your clit, rubbing it in circling movements [otherwise if cocks of player > 0]grab your swinging erection, jerking it in a rapid pace [otherwise]caress your featureless crotch, rubbing its sensitive skin with circling movements [end if]while you throw your head back and give a lewd moan, announcing to everyone in earshot that you're getting close to an orgasm. Then suddenly, the world spins around you for a second as you find yourself pulled against Garth's chest by strong hands and the razorback boar performs a full-on flip that would make any wrestler proud, grunting in satisfaction as he covers your form with his bulky body, pressing your back against the ground. Any thought of maybe resisting or protesting is swept away by the amazing new sensations the move gives you, as his cock stayed inside you the whole time and now presses into your depths in an all new angle.";
	say "     Seems like your partner finally gave in to his rut, freeing up his libido-fuelled urge to breed you hard. And oh boy, does he perform - the stocky body of this boar really has quite a few muscles - all of which perform to their utmost as his hips start to pound against your ass. Garth is grunting and chuffing hard as he fucks you, and his snout is buried in the curve of your neck, taking deep breaths of your scent and licking your skin, clearly turned on by all the sweat and pheromones. 'Oh yeah! Gonna fffuuuuckkk you good!' he grunts, almost drunk on lust, breathlessly barking out the words. 'Gonna show everyone that this forest IS MINE!' he adds next, getting louder with each word as he builds up to a howling orgasm, his thick shaft sending forth a deluge of cum to flood your asshole. You can feel the throb of his manhood against your stretched pucker and a pleasant warmth fills you more and more with every new spurt. Garth's full balls churn out quite a bit of seed to really stuff you good, trying [if player is not mpreg_ok]futilely[otherwise]hard[end if] to knock you up with his piglets.[mimpregchance]";
	say "     [WaitLineBreak]";
	say "     The heavy form of the razorback boar keeps you pinned under him as Garth's orgasm runs its course, with the panting male holding and caressing your body as his cock fills you with cum. He even plants a kiss or two on your shoulder and neck as he starts to catch his breath, then says in a still somewhat breathless voice, 'Thanks, you're a great lay. And - ah well, I can't say I'm sorry for turning things around on ya. Its just how I swing, you know? But don't think that means I leave my partners hanging";
	if cocks of player > 0 and cunts of player is 0:
		say " even if its a dude!' And with that, the boar takes your still rock-hard cock in his hand, chuckling at the string of pre-cum connecting it to your abs. 'I can see you liked it. Let's get you off buddy!' Garth adds and starts to jerk you off, feeling out what really turns you on. With his dick still buried balls-deep in your ass and the general state of high arousal you're in, it doesn't take long at all until his efforts bear fruit - turning your cock into a cum-fountain that spurts long strings of seed all over your abs, chest and even chin.";
	otherwise if cocks of player > 0:
		say " even she's part dude!' And with that, the boar takes your still rock-hard cock in his hand, chuckling at the string of pre-cum connecting it to your abs. 'I can see you liked it. Let's get you off babe!' Garth adds and starts to jerk you off, feeling out what really turns you on. With his dick still buried balls-deep in your ass and the general state of high arousal you're in, it doesn't take long at all until his efforts bear fruit - turning your cock into a cum-fountain that spurts long strings of seed all over your abs, chest and even chin. Meanwhile, femcum squirts and trickles from your wet pussy, soaking Garth's pubes and running down over the base of his cock and his balls.";
	otherwise if cunts of player > 0:
		say " especially not a babe like you!' And with that, the boar puts a hand on your pubic mound, searching out your clit with his thumb to rub it with circling movements. 'Man, you're really wet. Someone liked taking it up the ass quite a bit, haha. Let's get you off babe!' Garth adds and starts to work your magic button with a new intensity, feeling out what really turns you on. With his dick still buried balls-deep in your ass and the general state of high arousal you're in, it doesn't take long at all until his efforts bear fruit - femcum squirts and trickles from your wet pussy, soaking Garth's pubes and running down over the base of his cock and his balls.";
	otherwise: 
		say " even if its... well, whatever you are!' And with that, the boar puts a hand on your pubic mound, searchingly caressing your featureless crotch. As you pant and twitch a little at his touch, he chuckles and says, 'Oho, turned on much? Seems like someone really liked taking it up the ass. Let's get you off buddy!' With that said, he starts to stroke your pubic region, feeling out the most sensitive spots. With his dick still buried balls-deep in your ass and the general state of high arousal you're in, it doesn't take long at all until his efforts bear fruit - making you shiver and writhe as your whole body gets a tingling feeling of pleasure running through it.";
	say "     As you slump back, still out of breath from your orgasm, Garth gently pulls his erection out of you, accompanied by a little slurping sound and the feeling of his cum trickling down from your well-bred and still a little gaping hole. 'I still would have preferred pussy, but I can't say this hasn't been fun, eh? Still, I'm tempted to offer you a second round of fun in a little while, but... I gotta go. Can't fuck away the whole day, you know. Come by again sometime.' And with that, the naked razorback boar stands up and stalks off into the forest.";
	
to say RazorbackBoarSex3: [riding him (vaginal)]
	say "     Chuckling that you indeed want something from him, you step up to the boar-man and dig a hand into the bristly fur over his neck, pulling the gruff guy close for a demanding kiss. Then you put your hands on his shoulders, pressing down and pant out that he should lay down. Chuckling at your urgent tone, the burly boar-man follows suit, stretching out on the ground as you quickly get rid of your gear and clothes, then step up to stand over him in all your naked glory. As you lower your hand to brush its fingers over your nether lips, then spread them invitingly for him to see, the razorback boar comments, 'Oh yeah babe. Show me that pussy! [if cocks of player > 0]Had me worried for a second with that cock of yours, but you just [otherwise]You [end if]wanna get a good dicking, don't you?' As he says this, Garth's thick prick fills out more and more, hardening to a towering shaft of erect man-meat. The razorback boar proudly strokes his cock, waving it towards you and winks with broad grin on his face.";
	say "     Eager to make use of the oh so willing boar-man, you feast your eyes on his stocky yet quite muscular body once more, then eventually crouch down over his crotch. Garth strokes the insides of your thighs with his strong hands while you reach down between the two of you, grasping his thick shaft and giving it several long strokes. Just feeling the girth of his member gives you tingles of anticipation, so you quickly smear the copious pre-cum oozing from his cockhead over the towering pole and then move your pussy into position right above it. Relaxing your inner muscles, you sink down over the horny boar-man and slide his cockhead into you, making both of you moan loudly as his erection nudges apart the drippingly moist nether lips. 'Yeah, ride that dick baby! Nnnggh - you feel nice and warm,' Garth grunts in a husky voice as you sink deeper on his erection. His hands move to your hips, stroking their sides while Garth looks up at you, his eyes hungrily taking in your whole body.";
	say "     [WaitLineBreak]";
	say "     After slowly working your way down on the razorback boar's thick piece of man-meat, you eventually feel the bristly pubes of your former opponent press against the insides of your thighs. Yeah, you've taken all of him - balls-deep in your pussy, the strong and stocky male gives you a quite nice feeling of fullness. Resting like this and taking in the ridges and bumps of his cock, the sensation of his hot shaft pressing against more than a few 'magic' spots inside you, you're already very satisfied with your decision of using the very willing boar for your enjoyment - but there's a lot more fun to come. Looking down upon the razorback pig, you lean forward and plant your hands on his broad, pretty firmly muscled chest and brace yourself, then start sliding your hips up again. Garth's eyes focus on your own with a wild intensity of barely contained lust and the big man shows a wide grin, exposing his sharp tusks as he grunts deeply.";
	say "     His grip on your hips tightens as you go on and on until just the tip of his erection is inside you, though he just moves his hands with you, not actually pulling or pushing in any way. Looks like he has enough self-control to keep his urges to rut you like a wild beast in check - for now. You can't help but grin at having won out over the hunk of a guy and decide to push his buttons a bit, pinching Garth's nipples and squeezing his abs, then start rocking up and down on his thick prick. Moans and gasps fill the little clearing in the forest as you ride the razorback, taking his meat all the way in quick succession. Before long, the sensations of being inside your gripping pussy erode Garth's resistance more and more and he begins taking a more active role in the coupling, humping his hips up to meet yours, with his balls smacking against your ass with satisfying thuds.";
	say "     [WaitLineBreak]";
	say "     Bouncing up and down on the wild pig's cock you have one hell of a nice time, as his manhood nudges all the right places and stretches your chute tight around it. With your libido in roaring heat, your hands fly to your own crotch and proceed to [if cunts of player > 0]caress your clit, rubbing it in circling movements [otherwise if cocks of player > 0]grab your swinging erection, jerking it in a rapid pace [end if]while you throw your head back and give a lewd moan, announcing to everyone in earshot that you're getting close to an orgasm. Then suddenly, the world spins around you for a second as you find yourself pulled against Garth's chest by strong hands and the razorback boar performs a full-on flip that would make any wrestler proud, grunting in satisfaction as he covers your form with his bulky body, pressing your back against the ground. Any thought of maybe resisting or protesting is swept away by the amazing new sensations the move gives you, as his cock stayed inside you the whole time and now presses into your depths in an all new angle.";
	say "     Seems like your partner finally gave in to his rut, freeing up his libido-fuelled urge to breed you hard. And oh boy, does he perform - the stocky body of this boar really has quite a few muscles - all of which perform to their utmost as his hips start to pound against yours. Garth is grunting and chuffing hard as he fucks you, and his snout is buried in the curve of your neck, taking deep breaths of your scent and licking your skin, clearly turned on by all the sweat and pheromones. 'Oh yeah! Gonna fffuuuuckkk you good!' he grunts, almost drunk on lust, breathlessly barking out the words. 'Gonna show everyone that this forest IS MINE!' he adds next, getting louder with each word as he builds up to a howling orgasm, his thick shaft sending forth a deluge of cum to flood your vagina. You can feel the throb of his manhood against your stretched nether lips and a pleasant warmth fills you more and more with every new spurt. Garth's full balls churn out quite a bit of seed to really stuff you good, trying hard to knock you up with his piglets.[fimpregchance]";
	say "     [WaitLineBreak]";
	say "     The heavy form of the razorback boar keeps you pinned under him as Garth's orgasm runs its course, with the panting male holding and caressing your body as his cock fills you with cum. He even plants a kiss or two on your lips as he starts to catch his breath, then says in a still somewhat breathless voice, 'Thanks, you're a great lay. And - ah well, I can't say I'm sorry for turning things around on ya. Its just how I swing, you know? But don't think that means I leave my partners hanging";
	if cocks of player > 0:
		say " even she's part dude!' And with that, the boar takes your still rock-hard cock in his hand, chuckling at the string of pre-cum connecting it to your abs. 'I can see you liked it. Let's get you off babe!' Garth adds and starts to jerk you off, feeling out what really turns you on. With his dick still buried balls-deep in your ass and the general state of high arousal you're in, it doesn't take long at all until his efforts bear fruit - turning your cock into a cum-fountain that spurts long strings of seed all over your abs, chest and even chin. Meanwhile, femcum squirts and trickles from your wet pussy, soaking Garth's pubes and running down over the base of his cock and his balls.";
	otherwise if cunts of player > 0:
		say " especially not a babe like you!' And with that, the boar puts a hand on your pubic mound, searching out your clit with his thumb to rub it with circling movements. 'Man, you're really wet. Getting bred by a stud like my was right up your alley, eh? Let's get you off babe!' Garth adds and starts to work your magic button with a new intensity, feeling out what really turns you on. With his dick still buried balls-deep inside you and the general state of high arousal you're in, it doesn't take long at all until his efforts bear fruit - femcum squirts and trickles from your wet pussy, soaking Garth's pubes and running down over the base of his cock and his balls.";
	say "     As you slump back, still out of breath from your orgasm, Garth gently pulls his erection out of you, accompanied by a little slurping sound and the feeling of his cum trickling down from your well-bred and still a little gaping hole. 'You're one hot lay! I'm tempted to offer you a second round of fun in a little while, but... I gotta go. Can't fuck away the whole day, you know. Come by again sometime.' And with that, the naked razorback boar stands up and stalks off into the forest.";	
			
to say RazorbackBoarDesc:
	setmongender 3;
	say "     Walking through the forest, you run into Garth, the razorback boar. Unheard and unnoticed till he suddenly steps out from behind a thick tree nearby, he proves that he's completely at home in this patch of 'wilderness'. The anthro furry male looks you up and down and gives a grunt, then says, 'So, what makes you think you can just stomp through my forest? Civilization's gone - it's back to survival of the fittest! So I'm your boss here and now - or do you seriously think you can take me, eh?' He leaves you little time to make up your mind, instead charging at you right away.";

Table of random critters (continued)
name	attack	defeated	victory	desc	face	body	skin	tail	cock	face change	body change	skin change	ass change	cock change	str	dex	sta	per	int	cha	sex	hp	lev	wdam	area	cocks	cock length	cock width	breasts	breast size	male breast size	cunts	cunt length	cunt width	libido	loot	lootchance	scale (number)	body descriptor (text)	type (text)	magic (truth state)	resbypass (truth state)	non-infectious (truth state)	nocturnal (truth state)	altcombat (text)
--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	-- 	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--;

[ Adds a blank row to the table, this is immediately filled ;) ]
When Play begins:
	Choose a blank row from Table of random critters;
	now name entry is "Razorback Boar";         [The creature's name as displayed and used in naming descriptions]
	now attack entry is "[one of]With a deep grunt, the boar-man charges at you. You're thrown onto the ground as he bowls you over.[or]Making a fist, the razorback boar punches you in the gut, leaving you coughing for breath.[or]Snapping his head forward, the boar-man bites at you and leaves shallow gashes with his tusks.[or]Kicking a leg out from under you with one of his cloven hooves, the wild pig sends you sprawling on the ground.[at random]"; [Text used when the monster makes an Attack]
	now defeated entry is "[RazorbackBoar loses]";   [ Text or say command used when Monster is defeated.]
	now victory entry is  "[RazorbackBoar wins]";    [ Text used when monster wins, can be directly entered like combat text or description. or if more complex it can be linked to a 'To Say' block as the demonstration text shows.]
	now desc entry is "[RazorbackBoarDesc]";            [ Description of the creature when you encounter it. ]
	now face entry is "that of a wild boar, with an elongated snout showing sharp tusks. With the bristly fur covering all of it and two eyes capable of giving a very penetrating stare, you're an image of untamed spirit.";
	now body entry is "stocky in build, but quite obvious muscles make up much of that large bulk - from the broad shoulders down to the cloven hooves on which you stand. Anyone looking at you can easily see why wild boars shouldn't be messed with.";
	now skin entry is "[one of]bristly-furred[or]brown-furred[or]dark-furred[at random]";
	now tail entry is "You have a firm bubble butt, complete with a short tail ending in a brush of hairs.";  [ Tail desc., written as a full sentence or left blank for none. ]
	now cock entry is "human-like";
	now face change entry is "your facial muscles seem to ripple under the skin, rearranging themselves into an elongated visage complete with a boar's snout and sharp tusks. Bristly fur sprouts all over your face, giving you a hardy appearance"; [ face change text. format as "Your face feels funny as (your text)" ]
	now body change entry is "it is reshaped into a quite stocky form, though quite a bit of that bulk is made out of muscles. Heavy-footed - or rather hoofed, as your feet transform too - you may be, but there is little doubt that you're a force to be reckoned with looking like this. You're no weakling domestic pig. No, you're a razorback boar now";
	now skin change entry is "fur sprouts and grows all over your body, clothing you in a dark brown bristly coat";
	now ass change entry is "it tightens up into a firm, bubble butt and a tail sprouts out of your spine just above";
	now cock change entry is "it becomes uncut and human-like in shape. A pair of full and pretty hairy balls completes the picture";
	now str entry is 22;
	now dex entry is 12;
	now sta entry is 20;
	now per entry is 18;
	now int entry is 12;
	now cha entry is 10;
	now sex entry is "Male";						[ Infection will move the player towards this gender.  Current: 'Male' 'Female' 'Both' ]
	now hp entry is 90;									[ The monster's starting hit points. ]
	now lev entry is 10;                [ Monster level.  (Level x 2) XP for victory.  (Level / 2) XP for losing. ]
	now wdam entry is 12;               [ Monster's average damage when attacking. ]
	now area entry is "Nowhere";        [ "Outside" "Mall" "Park" "Beach" etc... Check an existing creature in the area. ]
	now cocks entry is 1;               [ Number of cocks the infection will try to cause if sex entry is 'Male' or 'Both'. ]
	now cock length entry is 13;        [ Length infection will make cock grow to if cocks. ]
	now cock width entry is 6;          [ Cock width, more commonly used for ball size. ]
	now breasts entry is 2;             [ Number of breasts the infection will give a player. ]
	now breast size entry is 0;         [ Size of breasts the infection will try to attain. ]
	now male breast size entry is 0;    [ Breast size for if Sex="Male", usually zero. ]
	now cunts entry is 0;               [ The number of cunts the infection will try to cause if sex entry is 'Female' or 'Both'. ]
	now cunt length entry is 0;         [ Depth of female sex the infection will attempt to give a player. ]
	now cunt width entry is 0;          [ Width of female sex the infection will try to give a player. ]
	now libido entry is 80;             [ Target libido the infection will rise towards. ]
	now loot entry is "";               [ Dropped item, blank for none.  Case sensitive. ]
	now lootchance entry is 0;          [ Percentage chance of dropping loot, from 0-100. ]
	[ These represent the new additions to the table of random critters ]
	now scale entry is 3;               [ Number 1-5, approx size/height of infected PC body: 1=tiny, 3=avg, 5=huge ]
	now body descriptor entry is "[one of]stocky[or]bulky[or]powerful[at random]";
	now type entry is "[one of]swine[at random]";
	now magic entry is true;            [ Is this a magic creature? true/false (normally false) ]
	now resbypass entry is false;       [ Bypasses Researcher bonus? true/false (almost invariably false) ]
	now non-infectious entry is false;  [ Is this a non-infectious, non-shiftable creature? True/False (usually false) ]
	blank out the nocturnal entry;      [ True=Nocturnal (night encounters only), False=Diurnal (day encounters only), blank for both. ]
	now altcombat entry is "default";   [ Row used to designate any special combat features, "default" for standard combat. ]

[
when play ends:
	if bodyname of player is "Razorback Boar":
		if humanity of player is less than 10:
			say "     ....";
		otherwise:
			say "     ...";
]
Razorback Boar ends here.
