Version 1 of Satyr Frat by Wahn begins here.
[ Version 1 - Initial Event ]

[ SatyrFratPartyStage                                                  ]
[  0: Free Drink event not done yet                                    ]
[  1: player helped in the free drink event (punched Richard)          ]
[  2: player helped in the free drink event (fought incubi - won)      ]
[  3: player helped in the free drink event (fought incubi - fled)     ]
[  4: player helped in the free drink event (fought incubi - lost)     ]
[  5: player helped in the free drink event (BJ for Richard)           ]
[  6: player helped in the free drink event (got fucked by Richard)    ]
[ 99: player declined helping the satyrs                               ]

[ SatyrFratRichardRelationship                                         ]
[  0: not met                                                          ]
[  1: friendly encounter (know his name)                               ]
[  2: sexual encounter (know his name)                                 ]
[ 98: neutral encounter (do not know his name)                         ]
[ 99: unfriendly encounter (do not know his name)                      ]

SatyrFratPartyStage is a number that varies.
SatyrFratRichardRelationship is a number that varies.

to say Satyr Frat Party:
	say "     You walk over the campus with the two satyrs, chatting a bit as you go along. Their names are Kerr and Talov, with Kerr having a bit more masculine features and thicker brown hair and Talov being pretty slender, with red hair and an almost shaved-looking chest. The two of them are pretty mellow and friendly, going on and on how much fun the party will be. Seems to you as if they stopped more than just once to drink cups of wine on the way too. After a while, Kerr asks you to take his place pushing the barrel for a moment, then skips ahead, scouting out where you're going. When he comes back a moment later, he says, 'We've got a small problem... they've got someone standing guard.' Seeing your questioning expression at this, he continues, 'Well, it's like this - we're the surprise guests... in that no one knows we're coming. The frat-boys have been partying for a while, so they are tipsy and distracted enough not to care too much if we join them... but that guy back there looks like he drew the short straw. Totally sober and alert.'";
	say "     [line break]";
	say "     Already having downed a few cups themselves, your two satyr compatriots seem a bit indecisive in how to deal with this little problem. You doubt they'll manage their plan on infiltrating the frat party on their own. Do you want to help them out?";
	if player consents:
		say "     [line break]";
		say "     Telling Kerr and Talov that you'll deal with things, you walk ahead of them and soon see a young man standing guard in front of a frat house in which a roaring party is going on. He's tall and pretty handsome too, dressed in a black Phi Alpha Nu t-shirt and jeans. From the looks of his muscled body, he's obviously an athlete - which throws the option of just attacking him out of the window. A prolonged brawl right in front of the house would surely be noticed even by the wildest partying crowd, and a jeering crowd of onlookers is exactly what your satyr friends don't need.";
		say "     [line break]";		
		say "     You could try knocking him out with a sucker-punch [link](1)[as]1[end link] - if it's all over in a second, no one might notice. Or you could try to get him out of position with some quick lying [link](2)[as]2[end link]. And of course, being a satyr yourself, there's always the option of just charming the pants off the young man [link](3)[as]3[end link] - he definitively won't be thinking of guarding anything while you take care of him...";
		now calcnumber is 0;
		while calcnumber < 1 or calcnumber > 3:
			say "Choice? (1-2)>[run paragraph on]";
			get a number;
			if calcnumber is 1 or calcnumber is 2 or calcnumber is 3:
				break;
			otherwise:
				say "Invalid choice.  Type [link]1[end link] to punch him out, [link]2[end link] to talk your way through this, or [link]3[end link] to have sex with him.";
		if calcnumber is 1:								[knockout]
			say "     [line break]";			
			let bonus be (( the Strength of the player minus 10 ) divided by 2);
			let diceroll be a random number from 1 to 20;
			say "You roll 1d20([diceroll])+[bonus]: [diceroll + bonus] (Strength-Check vs 18)";
			increase diceroll by bonus;
			say "     [line break]";						
			if diceroll is greater than 17:
				say "     Walking up to the young human man in a relaxed, nonthreatening manner, you greet him and... land a hard punch right in his face. Unprepared for this sudden violence, the frat-member just crumples to the ground. That went surprisingly smooth. You have a quick look over to the house, but none of the partying people seems to have noticed your very short altercation. Grabbing the knocked-out student under the arms, you start dragging him out of sight, around the corner of the frat-house's garage. As you do so, Kerr and Talov pass you with their barrel, rolling it towards the entrance of the building. You can tell from Kerr's expression that he's a bit surprised at your violent solution to this situation.";
				say "     After you finish dragging your unconscious victim around the corner and put him on the ground behind a tall bush, you unobtrusively check for the other satyrs. Looks like they made it into the building alright. With a smile at the thought of the two of them joining the party and handing out wine left and right, you walk away from the frat-house - for now. Maybe you should return here sometime later and see how this [bold type]party[roman type] develops...";
			otherwise:
				say "     Walking up to the young human man in a relaxed, nonthreatening manner, you greet him and... land a punch right in his face. Unprepared for this sudden violence, the frat-member stumbles backwards, but quickly catches himself. Uh-oh... that just made him angry. Using the moment in which the muscled guy shakes off the slight daze you gave him as a head-start, you dash away down the street, quickly followed by the yelling and cursing young man. This might not have been such a bright idea after all - he almost catches you several times, proving the speed and stamina a trained athlete can muster. Only when you jump over a hedge just after turning a corner do you get rid of him, as he dashes past your hiding spot.";
				say "     Phew, that was close. Though at least you can be sure that you gave Kerr and Talov enough time to make their way into the frat house. Maybe you should return here sometime later and see how this [bold type]party[roman type] develops...";
			now SatyrFratPartyStage is 1;
			now SatyrFratRichardRelationship is 99;
			now Let's Party is not resolved;
		if calcnumber is 2:								[lying]
			say "     [line break]";			
			say "     Running up to the young human man on quick hooves, you do a bit of play-acting as if you're out of breath, then pant that you saw a group of incubi climbing over the fence behind the house. The athletic young man's eyes widen in alarm and he says 'What?! Where? And who are -' Quickly interrupting him before he can really think about anything, you tell him to come quickly and run past the garage of the frat-house, turning the corner towards the backyard. And it works - the frat party guardian follows you a moment later, leaving his post to check out your imaginary incubi.";
			say "     Though as it turns out, they're not as imaginary as you thought - there actually are two incubi climbing over the fence! What a coincidence. Dropping down into the garden, they take up poses that show off their inhumanly perfect bodies and await you and the frat-member behind you calmly. 'Didn't I say there'd be a delicious banquet of studs in here? I'll take the left one,' one of them says to the other, then they attack...";
			challenge "Incubus";
			if fightoutcome >= 20 and fightoutcome <= 29:									[lost]
				say "     After the incubus finishes with you, he's suddenly punched out by the frat guy, who finished off his own attacker in the meantime. The young man helps you back to your feet, meanwhile closely watching the incubi pick themselves up and flee. When the two of you walk back to the front of the house afterwards, he says 'Thanks for the warning and... er, help. I'm Richard by the way.' He's too intent in getting back to his post to do more than have a short chat on the way, but you get the impression that he's a pretty friendly and nice guy. As you come to the front of the house, your satyr compatriots are nowhere in sight - seems like they made it into the building alright. Getting another bit of thanks from Richard, you say your goodbyes and walk away. Maybe you should return here sometime later and see how this [bold type]party[roman type] develops...";
				now SatyrFratPartyStage is 4;
			otherwise if fightoutcome >= 30:			[fled]
				say "    Sometimes it's best to flee - this isn't really your fight after all. As you dash off, you see that the frat guy has finished off his own incubus. He lunges at yours as the demon tries to run after you, bringing both of down to sprawl on the ground, wrestling with each other. And that's the last you see of the fight, as you turn a corner and move further away. A bit of a dick move to leave the young man to fight alone, though at least you can be sure that you gave Kerr and Talov enough time to make their way into the frat house. Maybe you should return here sometime later and see how this [bold type]party[roman type] develops...";
				now SatyrFratPartyStage is 3;
			otherwise if fightoutcome >= 10 and fightoutcome <= 19:  			[won]
				say "     After finishing off the incubus, you look around and see frat guy standing over his own opponent. The young man claps your shoulder in camaraderie and keeps a close watch on the bruised incubi as they pick themselves up and flee. When the two of you walk back to the front of the house afterwards, he says 'Thanks for the warning and help. I'm Richard by the way.' He's too intent in getting back to his post to do more than have a short chat on the way, but you get the impression that he's a pretty friendly and nice guy. As you come to the front of the house, your satyr compatriots are nowhere in sight - seems like they made it into the building alright. Getting another bit of thanks from Richard, you say your goodbyes and walk away. Maybe you should return here sometime later and see how this [bold type]party[roman type] develops...";
				now SatyrFratPartyStage is 2;
			now SatyrFratRichardRelationship is 1;
			now Let's Party is not resolved;
		if calcnumber is 3:								[sex]
			say "     [line break]";			
			say "[SatyrFratSex]";
			now SatyrFratRichardRelationship is 2;
			now Let's Party is not resolved;
	otherwise:
		say "     [line break]";
		say "     Maybe it's for the best that the two of them won't manage to pass their infective wine to dozens of frat members here on the campus. With a well-meant suggestion of just taking their wine barrel and enjoying the contents themselves, you leave the satyrs and turn your attention back to more important matters.";
	
to say SatyrFratSex:	
	say "     Walking up to the young human man in a relaxed, nonthreatening manner, you greet him and start a conversation. As it turns out, his name is Richard and he just started out here in Tenvale College on a sports scholarship this semester. He's a running back in the football team and joined the Phi Alpha Nu fraternity as a legacy member, just like his father before him. Nevertheless, he's still low on the totem pole - which explains why he's out here on guard duty and not enjoying himself with all the others inside. He's got a bit of a wistful look in his eye as he tells you about it, finishing 'I'd love to party with the guys... err, and all the hot chicks we've got over. Yeah, love the babes on campus. Definitively.'";
	say "     That last bit was said a bit too hurriedly, a blurt of words only making clearer what he wanted to hide. And catching his eyes stray down your body for a second confirms it a moment later - so Richard has some interest there for both sides of the fence. Perfect, for what you're planning. Keeping him talking about what he likes in women and his past conquests, you get the football-player in a receptive mood, then smoothly compliment him on what great shape he's in. Things progress to him showing off his muscles, then you feeling and... gently stroking them, just a little bit at first, then ever bolder. Soon you're standing very close besides the young man, one hand on the growing bulge in his pants. In the most charming tone you can manage, you tell him...";
	say "     [line break]";
	say "     [link](1)[as]1[end link] That you want to give him a blowjob.[line break]     [link](2)[as]2[end link] That you want him to fuck you.";
	now calcnumber is 0;
	while calcnumber < 1 or calcnumber > 2:
		say "Choice? (1-2)>[run paragraph on]";
		get a number;
		if calcnumber is 1 or calcnumber is 2:
			break;
		otherwise:
			say "Invalid choice.  Type [link]1[end link] to blow him or [link]2[end link] to get fucked.";
	if calcnumber is 1:								[BJ]
		say "     As wound up as you've got the athletic student, he eagerly and immediately agrees and lets himself be led around the corner of the frat-house's garage, to a nice secluded spot between several high bushes. Looking back before joining him there, you see your two satyr compatriots, grinning broadly at how you're dealing with the frat party guardian. While they start rolling their barrel on towards the goal, you pull Richard close and give him a deep kiss. His eyes widen at actually being intimate with [if cunts of player is 0]another male[otherwise]a herm[end if] for the first time and he freezes for a second, then quickly gets over his shock and happily replies in kind. As you make out with the young man, your hands quickly undo his button and zipper, opening the way to the quite impressive tent showing at the front of his boxer shorts.";
		say "     He moans between your kisses as you slide your hands under the band of his shorts, fondling his balls and jerking him off with the other hand. Then you kneel down, pulling down his pants and shorts as you go along, freeing his well-sized manhood to dangle just before your nose. Very nicely hung, your young running back. Eager to get going, you take hold of his shaft and slowly lick up the underside of Richard's shaft, making him pant loudly in lust. Soon arriving at the tip of his manhood, you play your tongue over it, teasing his slit for a moment, then slide your lips over his cock and sink them down along its length.";
		say "     [WaitLineBreak]";
		say "     While bobbing up and down on Richard's shaft, you use your hands to play with his balls, stroking and fondling to give your partner even more pleasure. At one point, you even snake a hand through between his legs, seeking out the round and firm globes of his butt to give them a good squeeze, then moving on what lies between them. Richard's pants come even quicker as you rub a finger around his pucker, which culminates in a pleasantly surprised gasp as you push it in a moment later, probing his virgin hole. Nice and tight, and you can make this strong male give a very cute little squeal when you rub his prostate. Definitively something to remember for later - though for now, you decide it'd be better to just concentrate on the blowjob.";
		say "     With you so eagerly going down on him, as well as touching and stroking his body, it's no big wonder that Richard soon gets closer and closer to orgasming. His pants and moans rise in volume and frequency until he finally gives a breathless grunt of 'I'm coming!' and blasts of his cum start filling your mouth. You feel the pleasant taste of his seed on your tongue for a moment, then swallow it down as more and more pulses out of his cock. 'That was *pant* amazing!' Richard gets out after getting himself under control again, before accepting a kiss that lets him taste his own cum a moment later.";
		say "     [WaitLineBreak]";
		say "     After a bit more pretty nice making out with the student, you leave to pull his pants back up, unobtrusively checking for the other satyrs in the meantime. Looks like they made it into the building alright. With a smile, you playfully grope Richard's butt one last time, then bid him farewell and watch as he walks back to his post. Maybe you should return here sometime later and see what you've just helped do...";
		now SatyrFratPartyStage is 5;
	otherwise if calcnumber is 2:			[Fuck]
		setmonster "human";
		choose row monster from the table of random critters;
		say "     As wound up as you've got the athletic student, he eagerly and immediately agrees and lets himself be led around the corner of the frat-house's garage, to a nice secluded spot between several high bushes. Looking back before joining him there, you see your two satyr compatriots, grinning broadly at how you're dealing with the frat party guardian. While they start rolling their barrel on towards the goal, you pull Richard close and give him a deep kiss. His eyes widen at actually being intimate with [if cunts of player is 0]another male[otherwise]a herm[end if] for the first time and he freezes for a second, then quickly gets over his shock and happily replies in kind. As you make out with the young man, your hands quickly undo his button and zipper, opening the way to the quite impressive tent showing at the front of his boxer shorts.";
		say "     He moans between your kisses as you slide your hands under the band of his shorts, fondling his balls and jerking him off with the other hand. Then you kneel down, pulling down his pants and shorts as you go along, freeing his well-sized manhood to dangle just before your nose. Very nicely hung, your young running back. Eager to get going, you take hold of his shaft and slowly lick up the underside of Richard's shaft, making him pant loudly in lust. Soon arriving at the tip of his manhood, you play your tongue over it, teasing his slit for a moment, then slide your lips over his cock and sink them down along its length.";
		say "     [WaitLineBreak]";
		say "     While bobbing up and down on Richard's shaft, you use your hands to play with his balls, stroking and fondling to give your partner even more pleasure. At one point, you even snake a hand through between his legs, seeking out the round and firm globes of his butt to give them a good squeeze, then moving on what lies between them. Richard's pants come even quicker as you rub a finger around his pucker, which culminates in a pleasantly surprised gasp as you push it in a moment later, probing his virgin hole. Nice and tight, and you can make this strong male give a very cute little squeal when you rub his prostate. Definitively something to remember for later - though for now, you want to get fucked yourself.";
		say "     Pulling your lips off his nice and wet shaft with a pop, you pant that it's time for him to fuck you, quickly dropping your gear and clothes to the ground before bending over for Richard. Wiggling your furred butt invitingly is all it takes for the young man to step up to you and put the tip of his shaft against your hole. With a lustful grunt, he thrusts right in, plunging his manhood deep into you. 'Man, that feels as good as any pussy I ever fucked - maybe better!' he pants as he wraps his arms around your chest from behind. Being fucked by this very eager young man, you delight in flexing your inner muscles and listening to the moaned and gasped reactions you get as you do. With it this being his first time, with a [if cunts of player > 0]herm[otherwise]man[end if] that is, it's no big wonder that Richard soon gets closer and closer to orgasming. His pants and moans rise in volume and frequency until he finally gives a breathless grunt of 'I'm coming!' and pounds his cock into your hole one last time as it starts blasting spurt after spurt of cum.[mimpregchance]";
		say "     [WaitLineBreak]";
		say "     You can feel his manhood twitch and pulse with more and more of his seed being deposited into you, leaving you with a pretty nice and full sensation. Holding on to you and leaning his head against your back, Richard gets out 'That was *pant* amazing!' You pull off his still hard cock with a wet slurp, then turn around and give him a deep kiss. After a bit more pretty nice making out with the student, you leave to pull his pants back up, unobtrusively checking for the other satyrs in the meantime. Looks like they made it into the building alright. With a smile, you playfully grope Richard's butt one last time, then bid him farewell and watch as he walks back to his post. Maybe you should return here sometime later and see what you've just helped do...";
		now SatyrFratPartyStage is 6;

Let's Party is a situation.
The sarea of Let's Party is "Campus".
when play begins:
	add Let's Party to badspots of guy;       [frat boys]
	add Let's Party to badspots of girl;      [sorority girls]

Instead of resolving a Let's Party:
	say "     Making your way back to the Phi Alpha Nu frat house, you find that the party is still going on - and it's wilder than ever. There is no trace of [if SatyrFratRichardRelationship > 97]the guy who was guarding the entrance before[otherwise]Richard[end if], maybe he joined the crowd inside at some point. In a bit of a partying mood yourself as you think back to the support you gave to some fellow satyrs, you walk up to the large house, up the stairs and into the open entrance door. Inside, the frat party is in full swing, with handsome guys and gals moving to the beat of loud music, drinks in their hands as they have fun dancing and talking. You do notice a definite prevalence of goatees among the men... might be that that type of beard is 'in' right now - or the result of smuggling in two satyrs with a whole barrel full of changing wine.";
	say "     While your eyes are still wandering over the crowd of attractive young adults, someone calling your name draws your attention suddenly. It's Kerr, standing behind an improvised bar on the other side of the room. After gleefully filling two more plastic cups with drinks and handing them to already somewhat buzzed students, he waves you closer. Talov, the other satyr you met before, isn't in sight as you walk up to the bar - at least not until you're right at it and lean in to talk to Kerr - which is when you notice the two curved horns poking up in front of Kerr's crotch. Rhythmically moving horns, as their owner's head bobs up and down on his friend's hard shaft. Gripping Talov by the horns and giving their sensitive base a teasing rub, the standing satyr says, 'Hey T, our friend is back.' Creating a deliberate loud pop that can be heard even above the loud music, Talov pulls off the cock in his mouth and stands up, licking his lips demonstratively before giving you a beaming smile.";
	say "     [WaitLineBreak]";
	say "     'Hey, nice to see you.' and 'Glad you could make it here again!' the two satyrs say loudly almost at the same time, immediately chuckling at the jumble of words that creates. A moment later, Talov gives Kerr a light slap on the brown-furred butt and tells him, 'You get back to the drinks. I'll talk with [if player is female]her[otherwise]him[end if].' As his friend gets back to filling plastic cups with booze, the red-headed satyr gives his butt a leering stare for a moment, then he turns to you and leans over the bar so he can talk without shouting. 'Thanks for helping to get us in here. It's a fun party. But it could still be better... there's a few holdouts and we really could use someone to wind up the crowd a bit more. Wanna join us and make sure that this will be absolutely legendary?'";
	say "     [line break]";
	if player consents:
		say "     [line break]";
		say "[SatyrFratSexMenu]";
	otherwise:
		say "     [line break]";
		say "     Replying that you can't, not right now, and that you only wanted to see how they were doing, you excuse yourself and leave the somewhat disappointed Talov standing at the bar. Making your way back to the entrance, you leave the crowd of young adults and the beat of their music behind and get back to the center of the campus.";

to say SatyrFratSexMenu:
	say "Replying that you're of course in on that, you turn around and let your gaze wander over the room. There's definitively a lot of possibilities here. Now where to start...";
	now sextablerun is 0;
	blank out the whole of table of fucking options;
	[]
	choose a blank row in table of fucking options;
	now title entry is "Arrange a drinking competition";  
	now sortorder entry is 1;  
	now description entry is "Try to drink a few hunky guys under the table";
	[]     
	choose a blank row in table of fucking options;
	now title entry is "'Accidentally' spill a drink over someone and help him 'clean up' in the shower";
	now sortorder entry is 2;
	now description entry is "Have some fun with a frat guy once you got his clothes off";
	[  
	if SatyrFratRichardRelationship < 90:
		choose a blank row in table of fucking options;
		now title entry is "Get it on with Richard - publicly";
		now sortorder entry is 3;
		now description entry is "Pull the guy down on a sofa right here in the room and have your way with him";
	]     
	sort the table of fucking options in sortorder order;
	repeat with y running from 1 to number of filled rows in table of fucking options:
		choose row y from the table of fucking options;
		say "[link][y] - [title entry][as][y][end link][line break]";
	say "[link]100 - Nevermind[as]100[end link][line break]";
	while sextablerun is 0:
		say "Pick the corresponding number> [run paragraph on]";
		get a number;
		if calcnumber > 0 and calcnumber <= the number of filled rows in table of fucking options:
			now current menu selection is calcnumber;
			choose row calcnumber in table of fucking options;
			say "[title entry]: [description entry]?";
			if player consents:
				let nam be title entry;
				clear the screen and hyperlink list;
				now sextablerun is 1;
				if nam is "Arrange a drinking competition":  
					say "[SatyrFratSex1]";
				if nam is "'Accidentally' spill a drink over someone and help him 'clean up' in the shower":  
					say "[SatyrFratSex2]";
				if nam is "Get it on with Richard - publicly":  
					say "[SatyrFratSex3]";
				wait for any key;
				now lastfuck of Aelias is turns;
		otherwise if calcnumber is 100:
			say "Break off?";
			if the player consents:
				now sextablerun is 1;
				say "     You change your mind, and tell Talov that you only wanted to see how they were doing, then excuse yourself and leave the somewhat disappointed satyr standing at the bar. Making your way back to the entrance, you leave the crowd of young adults and the beat of their music behind and get back to the center of the campus.step back from the SatyrFratNPC, shaking your head slightly as he gives a questioning look.";
				wait for any key;
			otherwise:
				say "Pick between 1 and [the number of filled rows in the table of fucking options] or 100 to exit.";
		otherwise:
			say "Invalid Option.  Pick between 1 and [the number of filled rows in the table of fucking options].";
		clear the screen and hyperlink list;

to say SatyrFratSex1: [drinking]
	say "     Snatching a freshly filled drink from the bar in front of Kerr, you shout out 'Phi Alpha Nu Forever!' and down the cup, drawing a loud cheer from everyone in the room. Now that you've got their attention, you go through a little spiel of praising their accomplishments (getting things mostly right by bringing up what you see on trophies and flags on the wall) - but also insinuating that they may or may not be able to hold their liquor. Before long, you've got three studly hunks of football players stepping forward to defend the frat's honor... and you guide em straight to the bar where a widely grinning Kerr is lining up shot glasses and cutting limes. As he fills one after another of them with golden-yellow Tequila, all four of the contestants take your places at the counter and get ready to drink.";
	say "     Surrounded by an excited and active crowd, you look at each other, three human guys and you - then the chant of 'Drink! Drink! Drink!' raises among the students. That's your cue - putting some salt on your hand and licking it off, you throw back the first shot with a single move, then hammer the glass down and bite into a slice of lime. Fire-water trickles down your throat as the sour taste hits our mouth, making you twitch and grunt out loud as warmth spreads through your insides. Yeah, that's just like it! Rolling your head from side to side, you reach out to take the next glass. Shot after shot is filled and hammered back and soon, the first of your four is out of the race, swaying for a moment before onlookers have to catch him to keep him from collapsing on the floor. With that guy half-dragged and half-stumbling to a couch, it's down to three now.";
	let bonus be (( the Stamina of the player minus 10 ) divided by 2);
	let diceroll be a random number from 1 to 20;
	say "You roll 1d20([diceroll])+[bonus]: [diceroll + bonus] (Stamina-Check vs 18)";
	increase diceroll by bonus;
	say "     [line break]";						
	if diceroll is greater than 17:	
		say "     Even as the drinking continues unabated, you manage to hold your ground admirably... much better than your two neighbours whose faces redden more and more, their competitive jeers about winning getting pretty slurred in the end. Then finally, the guy to your left thunks down on the counter with his head, spilling his shot and starting to snore loudly as he hangs over the bar. Turning from him to your other drinking buddy, you're surprised by finding yourself right face to face with him, bumping into his nose with yours as he has stumbled right up to you. Suddenly his lips press against yours as he gives you a drunken smooch - which has the crowd laugh and give whistles. Since this is what you set out to do anyways, you just go with it, replying to his kiss and wrestling his tongue with yours while your hand snakes down to rub the football player's crotch.";
		say "     The making out and groping does give the crowd around you some ideas - you can see some people pairing up from the corner of your eye while you continue to kiss your college athlete. One arm around the young man, you start guiding him out of the circle of onlookers - who congratulate you and give you pats on the back. But before you can start wondering what you'll do with him once you got him in a bedroom alone, he mumbles, 'Unnngh... I thschink I... got to sitttt. Down.' Seems like this hunk is a bit too out of it to have fun with after all, so you gently lower him to a sofa to rest until his head stops spinning.";
	otherwise:
		say "     Ungh, after that last shot, everything kinda seems to sway around you and you have trouble making out the glass on the counter in front of you. Why would Kerr fill three of them at the same time? Reaching out, you try to grab one of them - but strangely you can't... just grasping right through it - and then, you knock over the real glass and spill all the tasty Tequila. You contemplate licking it up for a second, then the thought 'Wait - what did I want to do again?' shoots through your head. Getting people wound up and partying - that's what it was! Deciding to start right away with the drinking competitor next to you, you stumble forward and throw your arms around his neck, then give the human athlete a resounding smooch on the lips.";
		say "     The guy is surprised at the sudden tongue-wrestling action he finds himself in, but he decides to go with the flow and just makes out with you a bit. You don't register too much of what's going on around - just his lips on yours - but something tells you that your plan was a success. Might be the cheering and congratulations your kissing partner is getting. After some more moments, he guides you away from the bar - to do what, you don't know. And you never will, as a seductive voice calls out to him, 'You're such a champ, Tyler! Wanna celebrate your victory up in your room?' Whoever it is, they seem to have really hit the right tone with him, as you find yourself lowered on to a sofa and then your stud is gone, off to enjoy himself with someone else.";
	say "     [line break]";
	say "     With the drinking competition done now, you hang out a while longer on one of the sofas in the frat house, then finally get up. Can't party all day, sadly, so you make your way to the entrance and walk back to the campus center.";
	
to say SatyrFratSex2:
	setmonster "Satyr";
	choose row monster from the table of random critters;	
	say "     Leaning in close over the counter, you ask him where the next shower in here is - as it turns out, just down one short hallway behind the door at the end. Equipped with that important knowledge for your plan, you let Kerr fill two plastic cups. One with the most sticky and sweet drink he has in his repertoire, the other with pure, undiluted satyr wine. Holding both cups in your hands, you then set out to find a mark. Moving through the big living room, then the adjoining kitchen, it doesn't take long till you spot a handsome stud of a college jock - leaning against a wall with a pretty indifferent expression towards all the people enjoying themselves on his face. Perfect.";
	say "     You let your feet carry you towards the guy, then 'accidentally' stumble when you get next to him. Splashing the young man with the contents of both cups, you're even fairly accurate - hitting his chest with the satyr wine and his face and neck with the soda. 'What the hell? Eww - I'm all sticky - and you got this crap in my eye,' your hapless victim shouts, wiping at his face with both hands and keeping his eyes clenched. Apologizing profusely, you take him by the arm and say that you'll of course help him clean up, then guide the student down the hall and into the thankfully empty bathroom. Locking the door behind you so you're not disturbed, you tell the college athlete to stand still for a moment and get a shower running, nice and warm, then get into the cabin right with him.";
	say "     [WaitLineBreak]";
	say "     While the frat member holds his head under the spray and rubs the stickiness of his face, you grab hold of his shirt. With the excuse of 'getting that stained thing off him', you pull the wet fabric up and over his head, revealing the young man's muscular chest. What it also reveals is that the satyr wine is already showing some effect - even with external application. From what you can see, this guy kept himself shaved of body hair, though that is changing fast now. Before your very eyes, hair sprout from his skin, forming a light layer of chest hair and looking almost identical to Kerr's manly curls. Blinking his by now mostly washed out eyes, the athlete looks down at his chest in befuddlement, then at you and the shirt in your hands.";
	say "     'What the -' ...is as far as you let the young man get before going in for the kill - silencing him with a long and deep kiss while pressing your body against his. There is a short moment of hesitation and surprise in which his eyes widen in shock, then he's past the point of no return and starts to eagerly reply to your tongue wriggling in his mouth. As you give him kiss after kiss, there is a small tingle against your skin - caused by a rapidly growing goatee on your college jock's chin. Bringing a hand up to stroke over the soft hair, you tell him it suits him well (which it actually does) and continue to make out with him while your hands get busy on his pants.";
	say "     [WaitLineBreak]";
	say "     Undoing the button of your transforming stud's jeans, you slide a hand inside them, feeling around for his family jewels. Oho - he's already a bit more than half-hard for you and a nice little handful of balls to go with it - no, can strike that 'little' from your mind as you feel them shift under your fingers, becoming fuller, bigger and more than a little furry. Wanting to see if his cock changed too, you proceed to lower the zipper of his pants and slide them down, revealing a nice and hard - but still completely human cock. Hm, seems like you'll have to get your college boy's juices flowing to speed things along.";
	if cocks of player > 0:
		say "     Do you want to let him fuck you (Y), or would you rather pound the guy in the ass yourself (N)?";
		if player consents:
			say "     After stroking your new friend's cock for a second, you take a step away from him and quickly strip, just throwing your gear and clothes aside in your eagerness to get it on with the handsome guy. And he's more than just a little willing to do so, as he is watching your naked body with a hungry gaze and his manhood stands fully erect by now. 'I don't know what's happening, but it feels great!' the jock pants loudly and steps forward, wrapping his arms around you. Your lips meet as eager hands wander over your body, then the horny college stud pulls you under the warm flow of the still-running shower. Being kissed and stroked by a handsome guy, your arousal skyrockets and soon, you moan for him to take you - right here, right now, against the shower wall.";
			say "     [WaitLineBreak]";
			say "     'Oh yeah, baby,' the guy gives a breathless pant, then his strong arms start to slide down the sides of your body, following every curve. He hooks his hands under your thighs and lifts you up, holding you with your back pressed against the tiled wall. The transforming student's lips brush against yours in the very moment that his pre-cum dripping erection nudges against your asshole - and a second later, he's balls-deep inside your butt and giving you an amazing kiss at the same time. The wet and wild coupling that follows is a constant assault on your senses, with your handsome stud pounding your butt in a lustful frenzy and you barely getting in a second to take a breath during an epic make-out session with the guy.";
			say "     While the exact order of things is slightly hazy in your recollection, you clearly remember the moment as small and nubby horns push out of the athlete's forehead - with him barely even noticing. At one point after that, the sound of hooves on the tiled floor of the shower becomes noticeable for the first time, soon followed by the interesting feeling of having a cock change shape inside your body. Suddenly having that goat-like shaft rubbing your inner walls drives you to new heights quickly ...and before much longer, you come hard - together with a by now completely transformed frat member.[mimpregchance]";
			say "     [WaitLineBreak]";
			say "     Breathing heavily as his cock pulses with blast after blast of fertile seed shooting into your insides, just like your own [cock of player] shaft splashes your cum all over your chest, the newly minted satyr holds on to you for a while yet, then eventually gives you a last kiss and lowers you back on your own feet slowly. 'Wow! That was am-az-ing! I'd have gone on more of these parties if I had known that sexy babes just drag you into a room and fuck your brains out!' he tells you with a goofy grin on his face. A moment after that, his brows suddenly draw together in puzzlement and he looks down, really noticing his now furred legs for the first time. 'Wait - what's this? Hooves? Kewl! I've got to show this to Dave and Bobby, they won't believe their eyes!'";
			say "     With that said, the student gives you a quick kiss on the cheek and with little more than a 'Thanks dude', he's out of the door to join the partying crowd again. As he never thought to stop for his clothes or even a towel, you bet that he'll be quite a surprise for his friends - as a wet and naked satyr with cum still dripping from his goat-like cock. Well, Kerr and Talov wanted you to mix things up - Mission Accomplished you'd say!";
			say "     [WaitLineBreak]";
			say "     Unlike your over-excited stud, you do dry yourself off and put your clothes back on before you make your way out of the bathroom. Back in the main room of the frat house, you don't see the new satyr you helped create - but the thumbs-up and grin that Talov shows tells you that he made a nice big splash. Content with a job well done, you walk back towards the entrance and leave - for now. A voice inside you tells you to just stay, but you can't - you've got to work at it if you want to survive in this ever-changing crazy world.";	
		otherwise:
			say "     After stroking your new friend's cock for a second, you take a step away from him and quickly strip, just throwing your gear and clothes aside in your eagerness to get it on with the handsome guy. And he's more than just a little willing to do so, as he is watching your naked body with a hungry gaze and his manhood stands fully erect by now. 'I don't know what's happening, but it feels great!' the jock pants loudly and steps forward, wrapping his arms around you. Your lips meet as eager hands wander over your body, then the horny college stud pulls you under the warm flow of the still-running shower. Being kissed and stroked by a handsome guy, your arousal skyrockets and soon, you moan that you want to fuck him - right here, right now, against the shower wall.";
			say "     [WaitLineBreak]";
			say "     'I'm not gay - or... I wasn't... wait -,' the guy says with confusion in his voice as he really thinks about what you've been doing for the first time since you got him all alone. Not willing you let this handsome stud slip out of your grasp, you quickly push him against the wall and kiss him again, then let your hands wander down over he muscled curves of his body. Hooking your hands under his thighs, you lift the frat guy up, holding him with his back pressed against the tiled wall. The transforming student's lips brush against yours in a followup kiss just as your pre-cum dripping erection nudges against his asshole. An eye-blink later, you're thrusting deep into his butt and giving him an amazing kiss at the same time. The wet and wild coupling that follows is a constant assault on your senses, with his clenching hole around your shaft, those soft lips against yours and comfortably warm water spraying down over you.";
			say "     While the exact order of things is slightly hazy in your recollection, you clearly remember the moment as small and nubby horns push out of the athlete's forehead - with him barely even noticing - well, how could he... with his eyes rolled back as he gasps at an especially deep thrust you did. Not long after that, his legs become much more furry under your hands and you can see human feet change to hooves from the corner of your eye. Interestingly, the young man's cock is the last thing to go, the last little bit of humanity he kept to the end - until it suddenly shifts as well, re-forming into a goat's penis. The sensation of completing his transformation is what drives him over the edge, and with a breathless moan, the frat member starts shooting cum all over his own chest. You're not long after him yourself, as the student's twitching and flexing asshole gives the last little push you needed.";
			say "     [WaitLineBreak]";
			say "     Breathing heavily as your cock pulses with blast after blast of fertile seed shooting into his insides, you hold the newly minted satyr for a while longer, then eventually give him a last kiss and lower him to stand back on his own two... hooves. 'Wow! That was am-az-ing! I - I guess I'm bi after all. Maybe I should have gone on more of these parties - who knew a handsome guy would just drag you into a room and fuck your brains out!' he tells you with a goofy grin on his face. A moment after that, his brows suddenly draw together in puzzlement and he looks down, really noticing his now furred legs for the first time. 'Wait - what's this? Hooves? Kewl! I've got to show this to Dave and Bobby, they won't believe their eyes!'";
			say "     With that said, the student gives you a quick kiss on the cheek and with little more than a 'Thanks dude', he's out of the door to join the partying crowd again. As he never thought to stop for his clothes or even a towel, you bet that he'll be quite a surprise for his friends - as a wet and naked satyr with cum still dripping out of his furry butt. Well, Kerr and Talov wanted you to mix things up - 'Mission Accomplished' one could say!";
			say "     [WaitLineBreak]";
			say "     Unlike your over-excited stud, you do dry yourself off and put your clothes back on before you make your way out of the bathroom. Back in the main room of the frat house, you don't see the new satyr you helped create - but the thumbs-up and grin that Talov shows tells you that he made a nice big splash. Content with a job well done, you walk back towards the entrance and leave - for now. A voice inside you tells you to just stay, but you can't - you've got to work at it if you want to survive in this ever-changing crazy world.";
	otherwise:
		if cunts of player > 0:
			say "     After stroking your new friend's cock for a second, you take a step away from him and quickly strip, just throwing your gear and clothes aside in your eagerness to get it on with the handsome guy. And he's more than just a little willing to do so, as he is watching your naked body with a hungry gaze and his manhood stands fully erect by now. 'I don't know what's happening, but it feels great!' the jock pants loudly and steps forward, wrapping his arms around you. Your lips meet as eager hands wander over your body and the horny college stud pulls you under the warm flow of the still-running shower. Being kissed and stroked by a handsome stud, your arousal skyrockets and soon, you moan for him to take you - right here, right now, against the shower wall.";
			say "     [WaitLineBreak]";
			say "     'Oh yeah, baby,' the guy gives a breathless pant, then his strong arms start to slide down the sides of your body, following every curve. He hooks his hands under your thighs and lifts you up, holding you with your back pressed against the tiled wall. The transforming student's lips brush against yours in the very moment that his erection nudges apart your nethers - and a second later, he's balls-deep inside your pussy and giving you an amazing kiss at the same time. The wet and wild coupling that follows is a constant assault on your senses, with your handsome stud pounding deep into your pussy in a lustful frenzy and you barely getting in a second to take a breath during an epic make-out session with the guy.";
			say "     While the exact order of things is slightly hazy in your recollection afterwards, you clearly remember that sometime after your first orgasm, small and nubby horns pushed out of the athlete's forehead - and that he barely even noticed, being so totally focused on fucking you. At some point after that, the sound of hooves on the tiled floor of the shower became noticeable for the first time, soon followed by the interesting feeling of having a cock change shape inside your body. The changed sensations of suddenly having that goat-like shaft fucking your pussy drove you to new heights quickly and before much longer, you came again - together with a by then completely transformed frat member.[fimpregchance]";
			say "     [WaitLineBreak]";
			say "     Breathing heavily as his cock pulses with blast after blast of fertile seed shooting into your womb, the newly minted satyr holds on to you for a while yet, then eventually gives you a last kiss and lowers you back on your own feet slowly. 'Wow! That was am-az-ing! I'd have gone on more of these parties if I had known that sexy babes just drag you into a room and fuck your brains out!' he tells you with a goofy grin on his face. A moment after that, his brows suddenly draw together in puzzlement and he looks down, really noticing his now furred legs for the first time. 'Wait - what's this? Hooves? Kewl! I've got to show this to Dave and Bobby, they won't believe their eyes!'";
			say "     With that said, the student gives you a quick kiss on the cheek and with little more than a 'Thanks babe', he's out of the door to join the partying crowd again. As he never thought to stop for his clothes or even a towel, you bet that he'll be quite a surprise for his friends - as a wet and naked satyr with cum still dripping from his half-hard goat-like cock. Well, Kerr and Talov wanted you to mix things up - 'Mission Accomplished' one could say!";
			say "     [WaitLineBreak]";
			say "     Unlike your over-excited stud, you do dry yourself off and put your clothes back on before you make your way out of the bathroom. Back in the main room of the frat house, you don't see the new satyr you helped create - but the thumbs-up and grin that Talov shows tells you that he made a nice big splash. Content with a job well done, you walk back towards the entrance and leave - for now. A voice inside you tells you to just stay, but you can't - you've got to work at it if you want to survive in this ever-changing crazy world.";
		otherwise:
			say "     After stroking your new friend's cock for a second, you take a step away from him and quickly strip, just throwing your gear and clothes aside in your eagerness to get it on with the handsome guy. And he's more than just a little willing to do so, as he is watching your naked body with a hungry gaze and his manhood stands fully erect by now. 'I don't know what's happening, but it feels great!' the jock pants loudly and steps forward, wrapping his arms around you. Your lips meet as eager hands wander over your body, then the horny college stud pulls you under the warm flow of the still-running shower. Being kissed and stroked by a handsome guy, your arousal skyrockets and soon, you moan for him to take you - right here, right now, against the shower wall.";
			say "     [WaitLineBreak]";
			say "     'Oh yeah, baby,' the guy gives a breathless pant, then his strong arms start to slide down the sides of your body, following every curve. He hooks his hands under your thighs and lifts you up, holding you with your back pressed against the tiled wall. The transforming student's lips brush against yours in the very moment that his pre-cum dripping erection nudges against your asshole - and a second later, he's balls-deep inside your butt and giving you an amazing kiss at the same time. The wet and wild coupling that follows is a constant assault on your senses, with your handsome stud pounding your butt in a lustful frenzy and you barely getting in a second to take a breath during an epic make-out session with the guy.";
			say "     While the exact order of things is slightly hazy in your recollection, you clearly remember the moment as small and nubby horns push out of the athlete's forehead - with him barely even noticing. At one point after that, the sound of hooves on the tiled floor of the shower becomes noticeable for the first time, soon followed by the interesting feeling of having a cock change shape inside your body. Suddenly having that goat-like shaft rubbing your inner walls drives you to new heights quickly ...and before much longer, you come hard - together with a by now completely transformed frat member.[mimpregchance]";
			say "     [WaitLineBreak]";
			say "     Breathing heavily as his cock pulses with blast after blast of fertile seed shooting into your insides, the newly minted satyr holds on to you for a while yet, then eventually gives you a last kiss and lowers you back on your own feet slowly. 'Wow! That was am-az-ing! I'd have gone on more of these parties if I had known that sexy babes just drag you into a room and fuck your brains out!' he tells you with a goofy grin on his face. A moment after that, his brows suddenly draw together in puzzlement and he looks down, really noticing his now furred legs for the first time. 'Wait - what's this? Hooves? Kewl! I've got to show this to Dave and Bobby, they won't believe their eyes!'";
			say "     With that said, the student gives you a quick kiss on the cheek and with little more than a 'Thanks dude', he's out of the door to join the partying crowd again. As he never thought to stop for his clothes or even a towel, you bet that he'll be quite a surprise for his friends - as a wet and naked satyr with cum still dripping from his goat-like cock. Well, Kerr and Talov wanted you to mix things up - 'Mission Accomplished' one could say!";
			say "     [WaitLineBreak]";
			say "     Unlike your over-excited stud, you do dry yourself off and put your clothes back on before you make your way out of the bathroom. Back in the main room of the frat house, you don't see the new satyr you helped create - but the thumbs-up and grin that Talov shows tells you that he made a nice big splash. Content with a job well done, you walk back towards the entrance and leave - for now. A voice inside you tells you to just stay, but you can't - you've got to work at it if you want to survive in this ever-changing crazy world.";	
		
to say SatyrFratSex3:
	say "     SatyrFratNPC says, 'bla bla.'";

Satyr Frat ends here.