Version 2 of Seraphim by Wahn begins here.
[Version 2 - Actual Monster now with full infection and fight texts]

[ hp of Gabriel                                              ]
[  0: not around yet                                         ]
[  1: Elijah has been corrupted                              ]
[  2: player saw Gabriel appear and ask for Elijah           ]
[  3: player had a run-in with Gabriel before                ]
[  4: Gabriel got fucked - now has genitals                  ]
[  5: Gabriel got fucked - repeat                            ]


Section 1 - Victory/Defeat Sex

to say SeraphDefeated:
	say "     Crumpling to his knees in exhaustion, Gabriel pants, 'You are far stronger than you are supposed to be. I yield, as I would have to harm you significantly if I met this with equal force.' He pulls the flaming sword from his hip and sets it down on the ground with calm movements, then looks at you with a concerned expression, 'You really should let me help you. Don't you see that resistance only hurts yourself?'";
	say "     [line break]";
	say "     Well, now that you've won this fight, what do you want to do?";
	say "     (Y) - Take advantage of the angel.[line break]";
	say "     (N) - Just leave.[line break]";
	if player consents:
		say "     [line break]";
		if hp of Gabriel < 4: [didn't have sex before]
			say "     Excited by the opportunity of having this magnificent creature at your mercy, you lean over him and start pulling off his armor piece by piece, then soon move on to undo the fastenings of his robe. 'What are you doing?', Gabriel asks as you pull open his clothes and bare his muscled chest, then as you are undoing a golden belt-buckle, he adds, 'I am a protector - I wasn't created for what you seem to expect from me.' And it's true... pulling down the soft white fabric of his pants, you reveal a totally sexless smooth crotch. Gabriel says, 'Now you see. There is nothing I can do for you. You should -' Before he can add another word, you put a finger on his lips and shush him, all the while giving the angel a salacious grin that makes a hint of doubt in his confident expression appear.";
			if cocks of player > 0:
				say "     Even without genitals on his own body, there are lots of possibilities for fun with this pretty hunk - a whole lot more than the innocent virgin could even imagine. Your cock goes hard inside your pants from the idea of feeling those soft lips of his stretched around your shaft - but no, there is a greater prize to be had right now... between the two shapely buns of Gabriel's ass. How often does the opportunity of popping an angel's cherry present itself, after all. You continue unwrapping your beaten opponent some more until he's almost completely naked, just his white pants still pooled at his knees and covering the lower legs, then get a grip on the back of his head and pull him in for a surprise kiss that makes his eyes go round.";
				say "     [WaitLineBreak]";
				say "     After making out with Gabriel for some very enjoyable moments, exploring his mouth with your tongue and finding yourself delighted by the confused and clueless reactions of a person who has never been kissed, you take a second to catch a breath, leaving the angel to pant loudly and look at you in wonder. As it's best to forge while the iron is hot - and the hottie still reeling from all the new sensation, you immediately proceed to grab him by the arm and pull Gabriel forwards. As he finds himself on all fours before you a moment later, a flash of realization at what will happen next spreads over Gabriel's face, causing his cheeks to turn red in embarrassment. Giving him a grin, you then stand up and walk around the angel to stand behind him.";
				say "     Quickly undoing your own pants and freeing your by now rock-hard erection, you kneel down behind the virgin hunk, then grab both of his well-rounded butt-cheeks with your hands and pull them apart, squeezing tightly as you do so. The nice and pink pucker between his shapely buns looks very inviting and you stretch your thumb to rub lightly over it, provoking a breathless little pant from your captive, which leads over into silent moaning as you proceed to stroke over the bumps and wrinkles of his pucker in teasing slowness. Gathering a bit of spit and smearing that on his back door to help lube the way, you then push your index finger against Gabriel's hole, slowly increasing pressure and wiggling it a bit until his muscle yields and you can slip right in.";
				say "     [WaitLineBreak]";
				say "     Your winged hunk can't help but gasp and moan as you explore his pretty tight, virgin hole with your probing digit, stroking sensitive spots. It's quite a bit of fun to see what noises you can let him make if you for example... wiggle your fingertip like so - which makes Gabriel give a half-panted squeak of arousal - or bend your finger to rub another specific spot... which draws a full-throated moan out of him and makes his toes curl up. In fact, you find yourself distracted quite a bit with this fun game, stroking him and adding another finger, then a third, until you eventually remember there is another exciting thing you can do with the angel.";
				say "     As you pull your fingers from Gabriel's hole, the muscled guy pants loudly and his pucker winks at you as he tries to prepare himself for whatever new way you'll touch him next - though he falls into shocked silence as not a finger but rather the tip of your cock nudges his opening and sinks inside. There is an instinctive tightening of his muscles around your unexpected invasion - but you're already halfway inside him, making him only squeeze down on your shaft in a most stimulating manner that feels pretty great. Giving Gabriel a moment to get used to the hot and hard pole now inside his body, you revel in the tightness of his passage around your cock, then eventually tell him to relax and start to press even deeper.";
				say "     [WaitLineBreak]";
				say "     Before long, you bottom out inside the handsome angel and lean forward to lick him between his wings and nibble his ear, then - in a whisper - ask him if your [cock of player] cock feels good inside him. There is a short moment of silence in which you first think he won't answer, then you can hear a low, 'Yes... its wrong, but... I like it.' And he really does - after getting over the first shock of finding himself being fucked, Gabriel turns out to be a very receptive - and vocal - partner, gasping and moaning loudly while his inner muscles grip your thrusting shaft. You give the angel a good and long pounding, really laying into him with deep thrusts that make him gasp in lust, and eventually drive the winged hunk to his first orgasm, trembling and twitching all over.";
				say "     The sensations of Gabriel's anal muscles flexing around your cock, in addition to the satisfaction of picking his cherry, push you over the edge too in short notice and you thrust in deep one last time until your crotch meets his cheeks with a satisfying slap. Balls-deep in the no-longer virgin angel, you unload everything that you have from your balls, blasting your thick, creamy cum into him. Spurt after spurt fills Gabriel up as he moans and pants like a good bottom-boy should.";
				say "     [WaitLineBreak]";
				say "     When your orgasm finally winds down, you pull out of the angel and wipe the last bit of cum sticking to your prick off on his buttcheeks, then pull up your pants and grab all the gear that you put down before having sex. With a spring in your step - from having fucked such a hottie, and a virgin no less - you walk down the street, leaving the cum-dripping angel to pick himself up on his own.";
			otherwise:
				say "     Even without genitals on his own body, there are lots of possibilities for fun with this pretty hunk - a whole lot more than the innocent virgin could even imagine. [if cunts of player > 0]Your pussy gets wet from the thought of having him licking you down there [otherwise]You get pretty excited from the thought of him licking your sensitive skin on the crotch [end if]- but no, to break him in to sex for good, you'll concentrate on something else right now... with it between the two shapely buns of Gabriel's ass. Also, how often does the opportunity of popping an angel's cherry present itself? You continue unwrapping your beaten opponent some more until he's almost completely naked, just his white pants still pooled at his knees and covering the lower legs, then get a grip on the back of his head and pull him in for a surprise kiss that makes his eyes go round.";
				say "     [WaitLineBreak]";
				say "     After making out with Gabriel for some very enjoyable moments, exploring his mouth with your tongue and finding yourself delighted by the confused and clueless reactions of a person who has never been kissed, you take a second to catch a breath, leaving the angel to pant loudly and look at you in wonder. As it's best to forge while the iron is hot - and the hottie still reeling from all the new sensation, you immediately proceed to grab him by the arm and pull Gabriel forwards. As he finds himself on all fours before you a moment later, a flash of realization at what will happen next spreads over Gabriel's face, causing his cheeks to turn red in embarrassment. Giving him a grin, you then stand up and walk around the angel to stand behind him.";
				say "     You kneel down behind the virgin hunk, then grab both of his well-rounded butt-cheeks with your hands and pull them apart. Squeezing their firm flesh appreciatively as you do so, the nice and pink pucker between his shapely buns is revealed, looking very inviting. You stretch your thumb to rub lightly over it, provoking a breathless little pant from your captive, which quickly leads over into silent moaning as you proceed to stroke over the bumps and wrinkles of his pucker in teasing slowness. Gathering a bit of spit and smearing that on his back door to help lube the way, you then push your index finger against Gabriel's hole, slowly increasing pressure and wiggling it a bit until his muscle yields and your fingertip can slip right in.";
				say "     [WaitLineBreak]";
				say "     Your winged hunk can't help but gasp and moan as you explore his pretty tight, virgin hole with your probing digit, stroking sensitive spots. It's quite a bit of fun to see what noises you can let him make if you for example... wiggle your fingertip like so - which makes Gabriel give a half-panted squeak of arousal - or bend your finger to rub another specific spot... which draws a full-throated moan out of him and makes his toes curl up. Before long, as you continue fondling the handsome angel, you lean forward to lick him between his wings and nibble his ear, then - in a whisper - ask him if he likes what you're doing. There is a short moment of silence in which you first think he won't answer, then you can hear a low, 'Yes... its wrong, but... I like it.'";
				say "     And he really does - after getting over the first shock of having his ass played with, Gabriel turns out to be a very receptive - and vocal - partner, gasping and moaning loudly while his inner muscles grip your questing fingers. You stimulate the angel more and more, really finding all his pressure points and tickling them and eventually drive the winged hunk to his first orgasm, trembling and twitching all over. When you eventually pull out your fingers, he even moves with you a little bit, trying to keep them inside - just like a good bottom-boy should.";
				say "     [WaitLineBreak]";
				say "     Standing up, you go and grab all the gear that you put down before deciding to have fun with Gabriel, then walk away, leaving the worn out and still panting angel to pick himself up on his own.";
			now hp of Gabriel is 4;
		otherwise if hp of Gabriel is 4: [had sex before]
			say "     Excited by the opportunity of having this magnificent creature at your mercy, you lean over him and start pulling off his armor piece by piece, then soon move on to undo the fastenings of his robe. 'Again?', Gabriel asks as you pull open his clothes and bare his muscled chest, then as you are undoing a golden belt-buckle, he adds, 'I've been feeling... different, since last time. My body... changed.' And it's true - pulling down the soft white fabric of his pants, you reveal that where previously there was only sexless smoothness, now a respectably sized manhood dangles between his legs. Gabriel looks down at his cock a bit sheepishly, then says, 'The tiny machines that infuse everything around here added this to me. It is... irregular. I wasn't created for -' Before he can add another word, you put a finger on his lips and shush him, all the while giving the angel a salacious grin.";
			if cocks of player > 0: [males and herms]
				say "     Continuing to strip Gabriel all the way until he's bare-ass naked, you lay out his clothes on top of each other, then gently press against the angel's chest, pushing him to lie back on the soft layer of fabric. He looks pretty amazing, stretched out on the ground before you in his well-built beauty and with white wings stretched to the sides - so much so that you can't help but want to feel his lips on yours. Leaning over the naked male, you put your hands on his upper arms to brace yourself and pin him down, then give him a deep and hungry kiss. And... quite interestingly, Gabriel replies in kind, the feelings you've just awoken leading him to actively participate in a very nice making-out session.";
				say "     You'd love to continue snogging with the handsome male for quite a while - but at one point, a sudden feeling of being poked in the stomach distracts you from him. Looking down, you see that it's Gabriel's cock, by now fully hard and ready for action. Reaching out to take hold of his manhood, you stroke the angel, making him arch his back and moan loudly from all the novel sensations he is going through. The youthful male's breathing soon comes faster and faster and a clear drop of pre forms at the slit of his cockhead, glistening in the light - which is exactly when you suddenly stop and pull your hand away.";
				say "     [WaitLineBreak]";
				say "     The angel looks up at you with a surprised expression, panting quickly in built-up arousal as his eyes jump between your hand and the erect pole standing proudly over his crotch. Gabriel's deep need to get off is painfully obvious on that unlined face of his, but as second after second ticks by and you don't react, he clears his throat and says in a pleading voice, 'Please... can - can you continue with...' Giving a wide smile at the angel, you do take hold of his cock again - but only with two fingers and your thumb, slowly, very slowly stroking up and down. As you continue this merciless teasing for a minute, then two, Gabriel gets pretty tense and even reaches out to grab his own cock - which you stop by clearing your throat and pushing his hand aside.";
				say "     Eventually, when he's all twitchy and can't suppress needy little whimpers at each touch anymore, you do ask if he wants you to show him another technique that is sure to him off - to which he almost screams, 'Yes, please! Anything!' You can't help but grin at having reduced the proud angel to this, lying before you in all his naked beauty and begging for you to take him - which is exactly what you plan to do. Quickly standing up and stripping off your clothes, you're kneeling between his legs a moment later and slide both hands up the inside of Gabriel's thighs. Taking hold of his legs, you raise and spread them to bare his tight little pucker, the view of which makes your hard cock pulse in anticipation.";
				say "     [WaitLineBreak]";
				say "     Without any further delay, you line up your erection with your captive angel's winking hole, then thrust in deep into his warm and tight chute. There is a breathless groan from Gabriel at the sudden invasion, leading over to lust-filled moaning as you proceed until you bottom out inside him. Giving him a short moment to get used to it - you then pull most of the way back out and start fucking the angel's hole with with hard and deep thrusts. Gabriel just feels amazing to be in, with a yielding yet very tight hole and anal muscles that seem to know instinctively when to flex around your shaft. As wound up as you got him and with your own satisfaction of how nicely this is working out, it doesn't take all that long until the two of you approach your respective orgasms.";
				say "     Coming more or less at the same time, you sink your manhood deep and blast the first spurt of your creamy cum into Gabriel, while he grips the fabric of his clothes on the ground tightly with both hands and sprays a quite respectable load into the air to splat down all over his chest and neck. It's pretty cute how he moans and pants as you fill him up - just like a good bottom-boy should. You can't help but think how awesome it would be to just... keep him, having an eager little slut to breed whenever you want to. Though you guess you'd have to break him in a bit more before that.";
				say "     [WaitLineBreak]";
				say "     When your orgasm finally winds down, you pull out of the angel and wipe the last bit of cum sticking to your prick off on his buttcheeks, then go and grab your clothes and gear, putting it all back on. With a spring in your step - from having fucked such a hottie - you walk down the street, leaving the cum-dripping angel to pick himself up on his own.";
			otherwise: [females and neuter]
				say "     Continuing to strip Gabriel all the way until he's bare-ass naked, you lay out his clothes on top of each other, then gently press against the angel's chest, pushing him to lie back on the soft layer of fabric. He looks pretty amazing, stretched out on the ground before you in his well-built beauty and with white wings stretched to the sides - so much so that you can't help but want to feel his lips on yours. Leaning over the naked male, you put your hands on his upper arms to brace yourself and pin him down, then give him a deep and hungry kiss. And... quite interestingly, Gabriel replies in kind, the feelings you've just awoken leading him to actively participate in a very nice making-out session.";
				say "     You'd love to continue snogging with the handsome male for quite a while - but at one point, a sudden feeling of being poked in the stomach distracts you from him. Looking down, you see that it's Gabriel's cock, by now fully hard and ready for action. Reaching out to take hold of his manhood, you stroke the angel, making him arch his back and moan loudly from all the novel sensations he is going through. The youthful male's breathing soon comes faster and faster and a clear drop of pre forms at the slit of his cockhead, glistening in the light - which is exactly when you suddenly stop and pull your hand away.";
				say "     [WaitLineBreak]";
				say "     The angel looks up at you with a surprised expression, panting quickly in built-up arousal as his eyes jump between your hand and the erect pole standing proudly over his crotch. Gabriel's deep need to get off is painfully obvious on that unlined face of his, but as second after second ticks by and you don't react, he clears his throat and says in a pleading voice, 'Please... can - can you continue with...' Giving a wide smile at the angel, you do take hold of his cock again - but only with two fingers and your thumb, slowly, very slowly stroking up and down. As you continue this merciless teasing for a minute, then two, Gabriel gets pretty tense and even reaches out to grab his own cock - which you stop by clearing your throat and pushing his hand aside.";
				say "     Eventually, when he's all twitchy and can't suppress needy little whimpers at each touch anymore, you do ask if he wants you to show him another technique that is sure to him off - to which he almost screams, 'Yes, please! Anything!' You can't help but grin at having reduced the proud angel to this, lying before you in all his naked beauty and begging for you to take him - which is exactly what you plan to do. Quickly standing up and stripping off your clothes, you're kneeling over him a moment later, with knees left and right of Gabriel's hips. Then, without any further delay, you reach down to take hold of his erection and lower your hips a bit. [if cunts of player > 0]There is the magic moment when the tip of his cock first nudges your nether lips, making both of you moan in lust, then his manhood slides into your drippingly wet and swollen pussy, filling you quite nicely and rubbing many sensitive spots deep inside.[otherwise]There is the magic moment when the tip of his cock first nudges your crack, making both of you moan in lust, then with a little help, his manhood presses directly against your pucker. Having prepared yourself and relaxed properly, it doesn't take long until your muscle yields to the pressure and Gabriel's cock slides right into your tight hole, filling you quite nicely and rubbing many sensitive spots deep inside.[end if]";
				say "     [WaitLineBreak]";
				say "     Leaning over your captive angel and pinning his arms down with your hands to show that you're still the one in control, you gyrate your hips and ride him hard, raising yourself up and then slamming down again to take all of his prick at once. Gabriel accepts you holding him down without any problems, panting loudly as he's being fucked, though at some point, he can't help himself and starts to buck his hips up and down. Seems like he's not completely submissive (yet?) - but then, he doesn't have to be, as his own movements add a nice little bit of fun to your coupling. Your sexy angel feels amazing inside you, with his cock having both the length and girth to really get to the good spots...";
				say "     As wound up as you got him and with your own satisfaction of how nicely this is working out, it doesn't take all that long until the two of you approach your respective orgasms. Coming more or less at the same time, you lower yourself on his pole all the way, trembling as your femcum squirts out and soaks his pubes, while Gabriel grips the fabric of his clothes on the ground tightly with both hands and sprays a quite respectable load into your body, squirting directly into your womb as his cockhead is tightly pressed against your cervix. As the warmth of his seed fills you more and more, you can't help but think how awesome it would be to just... keep him, having an eager little slut to breed you whenever you want him to. Though you guess you'd have to break him in a bit more before that.";
				say "     [WaitLineBreak]";
				say "     When your orgasm finally winds down, you pull away from the angel, his cock leaving your body with a wet slurp and a small gush of cum. Then you go and grab your clothes and gear, putting it all back on. With a spring in your step - from having fucked such a hottie - you walk down the street, leaving the cum-dripping angel to pick himself up on his own.";
			now hp of Gabriel is 5;
		otherwise if hp of Gabriel is 5: [saw Gabriel's genitals before]
			say "     Excited by the opportunity of having this magnificent creature at your mercy, you lean over him and start pulling off his armor piece by piece, then soon move on to undo the fastenings of his robe. 'Again?', Gabriel asks as you pull open his clothes and bare his muscled chest, then as you are undoing a golden belt-buckle, he adds, 'I must admit... I have been thinking about what you've been doing with me. It is... strangely exciting.' A moment later, your actions reveal the physical manifestation of Gabriel's submissive desires - an already half-hard cock, dangling between his legs. The angel looks down at his cock a bit sheepishly, then says, 'It does feel nice, but at the same time it is... irregular. I wasn't created for -' Before he can add another word, you put a finger on his lips and shush him, all the while giving the shy guy a salacious grin.";
			if cocks of player > 0: [males and herms]
				say "     Continuing to strip Gabriel all the way until he's bare-ass naked, you lay out his clothes on top of each other, then gently press against the angel's chest, pushing him to lie back on the soft layer of fabric. He looks pretty amazing, stretched out on the ground before you in his well-built beauty and with white wings stretched to the sides - so much so that you can't help but want to feel his lips on yours. Leaning over the naked male, you put your hands on his upper arms to brace yourself and pin him down, then give him a deep and hungry kiss. And Gabriel replies in kind, the feelings your previous interactions have awoken leading him to actively participate in a very nice making-out session.";
				say "     You'd love to continue snogging with the handsome male for quite a while - but at one point, a sudden feeling of being poked in the stomach distracts you from him. Looking down, you see that it's Gabriel's cock, by now fully hard and ready for action. Reaching out to take hold of his manhood, you stroke the angel, making him arch his back and moan loudly from all the still rather new sensations he is going through. The youthful male's breathing soon comes faster and faster and a clear drop of pre forms at the slit of his cockhead, glistening in the light - which is exactly when you suddenly stop and pull your hand away.";
				say "     [WaitLineBreak]";
				say "     The angel looks up at you with a surprised expression, panting quickly in built-up arousal as his eyes jump between your hand and the erect pole standing proudly over his crotch. Gabriel's deep need to get off is painfully obvious on that unlined face of his, but as second after second ticks by and you don't react, he clears his throat and says in a pleading voice, 'Please... can - can you continue with...' Giving a wide smile at the angel, you do take hold of his cock again - but only with two fingers and your thumb, slowly, very slowly stroking up and down. As you continue this merciless teasing for a minute, then two, Gabriel gets pretty tense and even reaches out to grab his own cock - which you stop by clearing your throat and pushing his hand aside.";
				say "     Eventually, when he's all twitchy and can't suppress needy little whimpers at each touch anymore, you tell Gabriel that you can keep this up all day - and also that he knows how to get his sweet release. Your massively aroused captive gives a few panting breaths, then silently pleads, 'Fuck me.' Acting like you didn't hear him, you just continue with your merciless teasing a moment longer, until Gabriel says, 'Fuck me. Please.' a bit louder, in answer to which you casually whistle and say that he should speak up. Eventually, after another minute or so of slow, slow jerking on his shaft, he gives an aroused wail of, 'Take me! Please! I need to feel you in me!' You can't help but grin at having reduced the proud angel to this, lying before you in all his naked beauty and begging for a fuck - which is exactly what you plan to do now. Quickly standing up and stripping off your clothes, you're kneeling between his legs a moment later and slide both hands up the inside of Gabriel's thighs. Taking hold of his legs, you raise and spread them to bare his tight little pucker, the view of which makes your hard cock pulse in anticipation.";
				say "     [WaitLineBreak]";
				say "     Without any further delay, you line up your erection with your captive angel's winking hole, then thrust in deep into his warm and tight chute. There is a breathless groan from Gabriel at the sudden invasion, leading over to lust-filled moaning as you proceed until you bottom out inside him. Giving him a short moment to get used to it - you then pull most of the way back out and start fucking the angel's hole with with hard and deep thrusts. Gabriel just feels amazing to be in, with a yielding yet very tight hole and anal muscles that seem to know instinctively when to flex around your shaft. As wound up as you got him and with your own satisfaction of how nicely this is working out, it doesn't take all that long until the two of you approach your respective orgasms.";
				say "     Coming more or less at the same time, you sink your manhood deep and blast the first spurt of your creamy cum into Gabriel, while he grips the fabric of his clothes on the ground tightly with both hands and sprays a quite respectable load into the air to splat down all over his chest and neck. It's pretty cute how he moans and pants as you fill him up - just like a good bottom-boy should. You can't help but think how awesome it would be to just... keep him, having an eager little slut to breed whenever you want to. After imagining some very nice scenes starring this cutie and yourself, you bring your eyes into focus again... and notice the narrow little storefront of a nearby sex shop for the first time. Especially the sign 'Custom Leather-Work' does draw your attention.";
				say "     [line break]";
				say "     Do you want to use the opportunity to duck in there and see if you can find something that fits Gabriel?"; 
				if player consents:
					say "     [line break]";
					say "     After waiting some moments until your orgasm finally winds down, you pull out of the angel and wipe the last bit of cum sticking to your prick off on his buttcheeks, then go and grab your clothes and gear, putting it all back on. With a spring in your step, you walk down the street to the store, leaving the cum-dripping angel to pick himself up on his own while you browse some wares. The store has been partially ransacked before, as is evident by the many empty spots in the shelves and a pile of what must have been all the lube bottles they had stockpiled, bone-dry and empty. Almost looks like something drank them all out - who or what would do such a thing? But no matter... the creature or creatures are long gone, leaving you with quite a chaos to look through.";
					say "     Thankfully, prodding around here and there fore a minute or three does indeed reveal a mannequin-like plastic bust, still with a very well made collar tight around its neck. It's just perfect for your little feathered bitch - complete with a few decorative spike studs and a ring for a leash at the front end. Holding your prize in hand, you emerge from the store to find Gabriel just adjusting his robe and then closing its belt. The angel's eyes widen as he realizes you didn't leave but are coming back, then his eyebrows draw together in wonder at the collar you hold up demonstratively. He doesn't resist as you put the piece of soft leather-work on him, only raising a hand to feel its tightness when you close the little buckle to fasten the collar around his neck. Again pre-empting a question from Gabriel, you tell him that it looks very nice and you'd like to see him wear the collar all the time now. After giving the calm threat of not letting him get off - at all - when you next have him in your grasp, you leave the angel standing in the empty street and get back to other matters.";
					now hp of Gabriel is 6;
				otherwise:
					say "     [line break]";
					say "     No, now isn't the time for that. Maybe another time. When your orgasm finally winds down, you pull out of the angel and wipe the last bit of cum sticking to your prick off on his buttcheeks, then go and grab your clothes and gear, putting it all back on. With a spring in your step - from having fucked such a hottie - you walk down the street, leaving the cum-dripping angel to pick himself up on his own.";
			otherwise: [females and neuter]
				say "     Continuing to strip Gabriel all the way until he's bare-ass naked, you lay out his clothes on top of each other, then gently press against the angel's chest, pushing him to lie back on the soft layer of fabric. He looks pretty amazing, stretched out on the ground before you in his well-built beauty and with white wings stretched to the sides - so much so that you can't help but want to feel his lips on yours. Leaning over the naked male, you put your hands on his upper arms to brace yourself and pin him down, then give him a deep and hungry kiss. And Gabriel replies in kind, the feelings your previous interactions have awoken leading him to actively participate in a very nice making-out session.";
				say "     You'd love to continue snogging with the handsome male for quite a while - but at one point, a sudden feeling of being poked in the stomach distracts you from him. Looking down, you see that it's Gabriel's cock, by now fully hard and ready for action. Reaching out to take hold of his manhood, you stroke the angel, making him arch his back and moan loudly from all the novel sensations he is going through. The youthful male's breathing soon comes faster and faster and a clear drop of pre forms at the slit of his cockhead, glistening in the light - which is exactly when you suddenly stop and pull your hand away.";
				say "     [WaitLineBreak]";
				say "     The angel looks up at you with a surprised expression, panting quickly in built-up arousal as his eyes jump between your hand and the erect pole standing proudly over his crotch. Gabriel's deep need to get off is painfully obvious on that unlined face of his, but as second after second ticks by and you don't react, he clears his throat and says in a pleading voice, 'Please... can - can you continue with...' Giving a wide smile at the angel, you do take hold of his cock again - but only with two fingers and your thumb, slowly, very slowly stroking up and down. As you continue this merciless teasing for a minute, then two, Gabriel gets pretty tense and even reaches out to grab his own cock - which you stop by clearing your throat and pushing his hand aside.";
				say "     Eventually, when he's all twitchy and can't suppress needy little whimpers at each touch anymore, you tell Gabriel that you can keep this up all day - and also that he knows how to get his sweet release. Your massively aroused captive gives a few panting breaths, then silently pleads, 'Fuck me.' Acting like you didn't hear him, you just continue with your merciless teasing a moment longer, until Gabriel says, 'Fuck me. Please.' a bit louder, in answer to which you casually whistle and say that he should speak up. Eventually, after another minute or so of slow, slow jerking on his shaft, he gives an aroused wail of, 'Take me! Please! I need to feel you around my cock!' You can't help but grin at having reduced the proud angel to this, lying before you in all his naked beauty and begging for you to take him - which is exactly what you plan to do. Quickly standing up and stripping off your clothes, you're kneeling over him a moment later, with knees left and right of Gabriel's hips. Then, without any further delay, you reach down to take hold of his erection and lower your hips a bit. [if cunts of player > 0]There is the magic moment when the tip of his cock first nudges your nether lips, making both of you moan in lust, then his manhood slides into your drippingly wet and swollen pussy, filling you quite nicely and rubbing many sensitive spots deep inside.[otherwise]There is the magic moment when the tip of his cock first nudges your crack, making both of you moan in lust, then with a little help, his manhood presses directly against your pucker. Having prepared yourself and relaxed properly, it doesn't take long until your muscle yields to the pressure and Gabriel's cock slides right into your tight hole, filling you quite nicely and rubbing many sensitive spots deep inside.[end if]";
				say "     [WaitLineBreak]";
				say "     Leaning over your captive angel and pinning his arms down with your hands to show that you're still the one in control, you gyrate your hips and ride him hard, raising yourself up and then slamming down again to take all of his prick at once. Gabriel accepts you holding him down without any problems, panting loudly as he's being fucked, though at some point, he can't help himself and starts to buck his hips up and down. Seems like he's not completely submissive (yet?) - but then, he doesn't have to be, as his own movements add a nice little bit of fun to your coupling. Your sexy angel feels amazing inside you, with his cock having both the length and girth to really get to the good spots...";
				say "     As wound up as you got him and with your own satisfaction of how nicely this is working out, it doesn't take all that long until the two of you approach your respective orgasms. Coming more or less at the same time, you lower yourself on his pole all the way, trembling as your femcum squirts out and soaks his pubes, while Gabriel grips the fabric of his clothes on the ground tightly with both hands and sprays a quite respectable load into your body, squirting directly into your womb as his cockhead is tightly pressed against your cervix. As the warmth of his seed fills you more and more, you can't help but think how awesome it would be to just... keep him, having an eager little slut to breed you whenever you want him to. After imagining some very nice scenes starring this cutie and yourself, you bring your eyes into focus again... and notice the narrow little storefront of a nearby sex shop for the first time. Especially the sign 'Custom Leather-Work' does draw your attention.";
				say "     [line break]";
				say "     Do you want to use the opportunity to duck in there and see if you can find something that fits Gabriel?"; 
				if player consents:
					say "     [line break]";
					say "     After waiting some moments until your orgasm finally winds down, you pull away from the angel, his cock leaving your body with a wet slurp and a small gush of cum. With a spring in your step, you walk down the street to the store, leaving the sweaty and somewhat sticky angel to pick himself up on his own while you browse some wares. The store has been partially ransacked before, as is evident by the many empty spots in the shelves and a pile of what must have been all the lube bottles they had stockpiled, bone-dry and empty. Almost looks like something drank them all out - who or what would do such a thing? But no matter... the creature or creatures are long gone, leaving you with quite a chaos to look through.";
					say "     Thankfully, prodding around here and there fore a minute or three does indeed reveal a mannequin-like plastic bust, still with a very well made collar tight around its neck. It's just perfect for your little feathered bitch - complete with a few decorative spike studs and a ring for a leash at the front end. Holding your prize in hand, you emerge from the store to find Gabriel just adjusting his robe and then closing its belt. The angel's eyes widen as he realizes you didn't leave but are coming back, then his eyebrows draw together in wonder at the collar you hold up demonstratively. He doesn't resist as you put the piece of soft leather-work on him, only raising a hand to feel its tightness when you close the little buckle to fasten the collar around his neck. Again pre-empting a question from Gabriel, you tell him that it looks very nice and you'd like to see him wear the collar all the time now. After giving the calm threat of not letting him get off - at all - when you next have him in your grasp, you leave the angel standing in the empty street and get back to other matters.";
					now hp of Gabriel is 6;
				otherwise:
					say "     [WaitLineBreak]";
					say "     When your orgasm finally winds down, you pull away from the angel, his cock leaving your body with a wet slurp and a small gush of cum. Then you go and grab your clothes and gear, putting it all back on. With a spring in your step - from having fucked such a hottie - you walk down the street, leaving the cum-dripping angel to pick himself up on his own.";
		otherwise if hp of Gabriel is 6:
			say "     Excited by the opportunity of continuing Gabriel's training, you lean over him and start pulling off his armor piece by piece, then soon move on to undo the fastenings of his robe. 'Again? Ooohh...' the angel sighs in a needy voice as you pull open his clothes and bare his muscled chest, then as you are undoing a golden belt-buckle, he adds, 'I couldn't stop thinking about what you've been doing with me. The collar was a constant reminder, and... I got quite excited as I imagined you, and me...' A moment later, your actions reveal the physical manifestation of Gabriel's submissive desires - an already half-hard cock, dangling between his legs. The angel looks down at his cock a bit sheepishly, then says, 'I - I am ready for your pleasure... Do you want to -' Before he can add another word, you put a finger on his lips and shush him, all the while giving the shy guy a salacious grin.";
			say "     [WaitLineBreak]";
			if cocks of player > 0: [males and herms]
				say "     Continuing to strip Gabriel all the way until he's bare-ass naked, you wrap all the gear in a bundle with his clothes, then swing that over your shoulder and walk down the street. The winged hunk gapes after you, opening and closing his mouth in shock a few times, then finally gets over his paralysis and hurries after you. It's a sight to behold - those flawless muscles of his body moving in concert without a stitch of clothing to hide them. You can't help but grin as you watch Gabriel come closer quickly, finally taking position by your side and starting to shyly ask, 'Didn't you want to -' A commanding shush stops the words still in his mouth, making the angel fall quiet as you lead him through the streets of the red light district.";
				say "     Before long, your little party has drawn the attention of more than a few inhabitants of the area, with wolf whistles and comments like 'Oooh, look at that ass' and 'Wanna show me what you can do with that pole, fly-boy?' Cute, how pink Gabriel can turn in the face, clearly embarrassed but held back from even trying to cover himself with his hands by your command. Eventually, you choose one of the available porn stores and enter it, starting to browse what hasn't been looted yet - though you soon notice that Gabriel didn't come with you. The naked angel is still standing right at the entrance of the store, looking with big eyes at an emptied out stand of porn DVDs. The discs may be gone, but the quite explicit cardboard mock-up still stands - and has more than a little bit of effect on Gabriel's manhood, making it stand straight too.";
				say "     [WaitLineBreak]";
				say "     A sharp whistle from you stops Gabriel's hand from creeping any closer to his crotch, and also serves to frighten the angel out of his aroused haze. Both hands whipping to his side as he instinctively stands to attention, he shame-facedly looks down as you remind him that he may not touch himself. A moment later, the angel meekly follows you again as you pass all the empty shelves and step over strewn about lube bottles. They're all empty too, leaving you to wonder if maybe something drank the contents. It's not as unlikely as one might think, not these days. Soon, a door at the back draws your attention, saying 'Workshop' and 'Custom Items' on it. Trying the doorknob, you find that it is locked, but thankfully a short search behind the store's counter reveals a key.";
				say "     Unlocking and entering the porn store's workshop, you find yourself in a mid-sized room filled with leather-working tools, a low fuck-bench with restraints and... jackpot! There's a sturdy frame bolted to the back wall, holding up a well-crafted sex sling. Just the right thing for your little angel. You draw Gabriel close and give him a deep kiss, putting your tongue into the male's mouth as he trembles in arousal. Then you walk him towards the sling and give him a little push to fall right into it. The needy expression on his face and a sighed, 'Please, take me now. I need it,' almost makes you pound him right then - but no, you're not quite done. Snatching a set of matching leather cuffs from the workbench, you fasten them around Gabriel's wrists and ankles, then strap him in to the harness fully - now totally subject to your every whim.";
				say "     [WaitLineBreak]";
				say "     Collared, cuffed and dangling naked in a sex sling - Gabriel is truly a sight to behold now. Time to finish re-shaping this formerly sexless divine warrior to the new purpose you have in mind for him. In moments, your clothes and gear are off your body and piled on the workbench, and you're stepping up to Gabriel, following the lead of your erect cock. There is a needy whimper from him as your cockhead brushes over his hole and he even raises his butt a bit to push against you and get it inside - but you still hold back, teasing him with your manhood while at the same time lazily stroking his. 'Unnngh - please fuck me. Please!' he soon begs, painfully aroused and unable to do anything about it, strapped in as he is.";
				say "     You leave your sexy pet to suffer for a few moments longer, then lean over him and thrust in deep, reveling in the angel's lust-filled gasp as you penetrate him. Giving Gabriel a rough kiss, you proceed to fuck him with rapid thrusts without pause, really taking it out on the guy - and the beauty of it is, he just begs for more. Having accepted his properly submissive place, Gabriel stays rock hard the whole time, with the proudly standing erection leaking drops of precum to drip on his rippling abs. He just feels amazing to be in too, with a yielding yet very tight hole and anal muscles that seem to know instinctively when to flex around your shaft. As wound up as you got him and with your own satisfaction of how nicely this is working out, it doesn't take all that long until the two of you approach your respective orgasms.";
				say "     [WaitLineBreak]";
				say "     ...which is when you pause again, although it is hard to control your own roaring libido. Breathing hard, you ask if he doesn't enjoy this a whole lot more than the pointless quest he was on - and he literally screams, 'YES!' After making him squirm and twitch in need with a slow grind of your hips against his butt, you tell him he could have such fun all the time - if he only accepted you as his master. That you'll take care of his needs if he becomes your slut. Again, the reply of the near delirious angel is, 'YES! Take me, my master! I'm yours!' Just what you wanted to hear, so you start fucking him again, eager to plant your claim on this sexy pet in the form of a creamy filling.";
				say "     Pounding into Gabriel hard, it's not long before you come more or less at the same time, sinking your manhood as deep as it will go and blasting the first spurt of your seed into him while Gabriel moans incoherently, the muscles in his arms tensing as he pulls on his restraints. His cock jerks and pulses as it sprays a quite respectable load into the air to splat down all over his chest and neck. It's pretty cute how he moans and pants as you fill him up - just like a good bottom-boy should. And he's all yours now - to keep and have as an eager little slut you can breed whenever you want to.";
				say "     [WaitLineBreak]";
				say "     Slowly winding down from your orgasm, you make out a moment longer with Gabriel, then eventually pull your softening manhood out of his cream-filled asshole. After enjoying the sight of your cum slowly oozing out of his winking pucker for a moment, you move over to the workbench to clean up and get dressed, leaving your angelic sex pet to wind down from the hottest fuck in his life, still strapped in and oh so deliciously helpless. After ducking out into the store to find a fitting item, you do come back and undo the straps holding Gabriel to the sex sling - but tell him to keep the leather cuffs on. 'Yes master,' he replies immediately, then goes to grab his bundle of gear and clothes - only to be stopped short when you command that he should stay naked, so that everyone can see the signs of his submission - cum between his butt-cheeks and the white splatter over his front.";
				say "     And with that said, you clip the leash you just got from the store to his collar, then lead the angel out of the room, still just carrying the bundle and totally naked. The way back to the library is a lot of fun - as you strut down the road with your new pet in tow, lots of people and creatures give you interested looks and wolf whistles. Thankfully, no one decides they want a piece of Gabriel themselves - maybe your current confident aura is enough to keep em just watching, not pouncing your naked pet. When you soon arrive back at the library, you tell the angel that that is his new home and he shouldn't leave the building without you. 'I won't, master' he obediently agrees, and follows you inside.";
				say "     [WaitLineBreak]";
				say "     Letting the angel off his leash, you find that he still follows you quite closely - a new pet, eager to learn from his master. Getting shown the library upper floor and ground level, he thanks you for your permission to roam the building and read when he wants to, then he follows down the flight of stairs into the library bunker. While you have him set down his gear on one of the beds right next to yours, wanting to get him settled in and ready for easy access, a mocking voice suddenly stops Gabriel in his tracks, 'Now what do we have here? A needy slut, covered in dried cum. The look suits you, Gabe.'";
				say "     It's Elijah, leaning against a wall behind you in a lazy pose, arms crossed over his chest as he gives the naked Gabriel a shameless leer. Whirling around to face his lost friend, Gabriel's eyes go wide as he takes in Elijah's black wings and aura of domineering masculinity and arrogance. He wails. 'Elijah! What happened to you?!' The other angel just chuckles darkly, then says, 'I found out what fun you can have if you're not just another sexless sock-puppet, always serving a 'higher purpose'. What should have been allowed to us from the start. The feeling of a tight hole or pussy stretched around your cock is just priceless, don't you think? Oh wait - seems like you're more on the receiving team.'";
				say "     Elijah's pointed stare at the cum on Gabriel's chest and the part of your load that trickled down the inside of his legs makes the angel flush bright red, looking down over himself in shame. Then he stammers, 'I - I... yes. I like it. I need it. My master said he'd fuck me all the time from now on.' The other angel just gives you an approving nod, 'Nice work training the little slut. Seems you've got Gabe turned into a subby pet, don't you. I'll have to tap that ass myself too sometime...' Before you can reply anything, Elijah then saunters out of the room, going up, most likely to hunt down something to fuck outside.";
			otherwise if cunts of player > 0: [females and neuter]
				say "     Continuing to strip Gabriel all the way until he's bare-ass naked, you wrap all the gear in a bundle with his clothes, then swing that over your shoulder and walk down the street. The winged hunk gapes after you, opening and closing his mouth in shock a few times, then finally gets over his paralysis and hurries after you. It's a sight to behold - those flawless muscles of his body moving in concert without a stitch of clothing to hide them. You can't help but grin as you watch Gabriel come closer quickly, finally taking position by your side and starting to shyly ask, 'Didn't you want to -' A commanding shush stops the words still in his mouth, making the angel fall quiet as you lead him through the streets of the red light district.";
				say "     Before long, your little party has drawn the attention of more than a few inhabitants of the area, with wolf whistles and comments like 'Oooh, look at that ass' and 'Wanna show me what you can do with that pole, fly-boy?' Cute, how pink Gabriel can turn in the face, clearly embarrassed but held back from even trying to cover himself with his hands by your command. Eventually, you choose one of the available porn stores and enter it, starting to browse what hasn't been looted yet - though you soon notice that Gabriel didn't come with you. The naked angel is still standing right at the entrance of the store, looking with big eyes at an emptied out stand of porn DVDs. The discs may be gone, but the quite explicit cardboard mock-up still stands - and has more than a little bit of effect on Gabriel's manhood, making it stand straight too.";
				say "     [WaitLineBreak]";
				say "     A sharp whistle from you stops Gabriel's hand from creeping any closer to his crotch, and also serves to frighten the angel out of his aroused haze. Both hands whipping to his side as he instinctively stands to attention, he shame-facedly looks down as you remind him that he may not touch himself. A moment later, the angel meekly follows you again as you pass all the empty shelves and step over strewn about lube bottles. They're all empty too, leaving you to wonder if maybe something drank the contents. It's not as unlikely as one might think, not these days. Soon, a door at the back draws your attention, saying 'Workshop' and 'Custom Items' on it. Trying the doorknob, you find that it is locked, but thankfully a short search behind the store's counter reveals a key.";
				say "     Unlocking and entering the porn store's workshop, you find yourself in a mid-sized room filled with leather-working tools, a well-crafted sex sling and... jackpot! There's a sturdy fuckbench with restraints standing in front of the back wall. Just the right thing for your little angel. You draw Gabriel close and give him a deep kiss, putting your tongue into the male's mouth as he trembles in arousal. Then you walk him towards the bench and give him a little push to fall right onto it. The needy expression on his face and a sighed, 'Please, take me now. I need it,' almost makes you mount him right then - but no, you're not quite done. Snatching a set of matching leather cuffs from the workbench, you fasten them around Gabriel's wrists and ankles, then strap him in to the bench - making him now totally subject to your every whim.";
				say "     [WaitLineBreak]";
				say "     Collared, cuffed and bound to a fuckbench - Gabriel is truly a sight to behold now. Time to finish re-shaping this formerly sexless divine warrior to the new purpose you have in mind for him. In moments, your clothes and gear are off your body and piled on the workbench, and you're stepping up to Gabriel, eyes firmly riveted to his erect shaft. There is a needy whimper from him as you step over him and brush the are between your legs over his cockhead. He even raises his butt a bit to push against you and maybe sink his shaft into you - but you still hold back, just teasing his erection with a few light touches. 'Unnngh - please fuck me. Please!' he soon begs, painfully aroused and unable to do anything about it, strapped in as he is.";
				say "     You leave your sexy pet to suffer for a few moments longer, then lower yourself a little bit more, letting his cock press in against the opening off your [if cunts of player > 0]pussy[otherwise]asshole[end if] - then sink inside. The angel gives a lust-filled gasp as you allow him to penetrate, and you even have to give him a little swat to stop his reflexive thrust up. Leaning over Gabriel, you give him a rough kiss, then proceed to ride his pole with rapid intensity, really giving using him hard - and the beauty of it is, he just begs for more. Having accepted his properly submissive place, Gabriel moans and whimpers as you make use of his proudly standing erection, making your hole pretty slick with his precum. As wound up as you got him and with your own satisfaction of how nicely this is working out, it doesn't take all that long until the two of you approach your respective orgasms.";
				say "     [WaitLineBreak]";
				say "     ...which is when you pause again, although it is hard to control your own roaring libido. Breathing hard, you ask if he doesn't enjoy this a whole lot more than the pointless quest he was on - and he literally screams, 'YES!' After making him squirm and twitch in need through slowly sliding up and down his shaft a few times, you tell him he could have such fun all the time - if he only accepted you as his [if cunts of player > 0]mistress[otherwise]master[end if]. That you'll take care of his needs if he becomes your slut. Again, the reply of the near delirious angel is, 'YES! Take me, my [if cunts of player > 0]mistress[otherwise]master[end if]! I'm yours!' Just what you wanted to hear, so you start fucking him again, eager to milk the first of many loads to come from this sexy dude.";
				say "     Bouncing up and down on Gabriel's hard cock, it's not long before you come more or less at the same time, your inner muscles trembling around his shaft while Gabriel moans incoherently, the muscles in his arms tensing as he pulls on his restraints. An eye-blink later, his cock jerks and pulses inside you as it sprays a quite respectable load [if cunts of player > 0]right into your womb[otherwise]deep into your ass[end if]. It's pretty cute how he moans and pants as he fills you up - just like a good slave-boy should. And he's all yours now - to keep and have as an eager little slut you can ride whenever you want to.";
				if cunts of player > 0:
					say "[fimpregchance]";
				otherwise:
					say "[mimpregchance]";
				say "     [WaitLineBreak]";
				say "     Slowly winding down from your orgasm, you make out a moment longer with Gabriel, then eventually pull off his softening manhood, leaking creamy cum and femcum onto his crotch. After enjoying the sight of your sweaty and cum-stained angel fuckpet for a moment, you move over to the workbench to clean up and get dressed, leaving the submissive angel to wind down from the hottest fuck in his life, still strapped in and oh so deliciously helpless. After ducking out into the store to find a fitting item, you do come back and undo the straps holding Gabriel to the bench - but tell him to keep the leather cuffs on. 'Yes [if cunts of player > 0]mistress[otherwise]master[end if],' he replies immediately, then goes to grab his bundle of gear and clothes - only to be stopped short when you command that he should stay naked, so that everyone can see his submission - a perfect naked body and your mixed fluids drying on his crotch.";
				say "     And with that said, you clip the leash you just got from the store to his collar, then lead the angel out of the room, still just carrying the bundle and totally naked. The way back to the library is a lot of fun - as you strut down the road with your new pet in tow, lots of people and creatures give you interested looks and wolf whistles. Thankfully, no one decides they want a piece of Gabriel themselves - maybe your current confident aura is enough to keep em just watching, not pouncing your naked pet. When you soon arrive back at the library, you tell the angel that that is his new home and he shouldn't leave the building without you. 'I won't, [if cunts of player > 0]mistress[otherwise]master[end if]' he obediently agrees, and follows you inside.";
				say "     [WaitLineBreak]";
				say "     Letting the angel off his leash, you find that he still follows you quite closely - a new pet, eager to learn from his master. Getting shown the library upper floor and ground level, he thanks you for your permission to roam the building and read when he wants to, then he follows down the flight of stairs into the library bunker. While you have him set down his gear on one of the beds right next to yours, wanting to get him settled in and ready for easy access, a mocking voice suddenly stops Gabriel in his tracks, 'Now what do we have here? A needy slut, covered in dried cum. The look suits you, Gabe.'";
				say "     It's Elijah, leaning against a wall behind you in a lazy pose, arms crossed over his chest as he gives the naked Gabriel a shameless leer. Whirling around to face his lost friend, Gabriel's eyes go wide as he takes in Elijah's black wings and aura of domineering masculinity and arrogance. He wails. 'Elijah! What happened to you?!' The other angel just chuckles darkly, then says, 'I found out what fun you can have if you're not just another sexless sock-puppet, always serving a 'higher purpose'. What should have been allowed to us from the start. The feeling of a tight hole or pussy stretched around your cock is just priceless, don't you think?'";
				say "     Elijah's pointed stare at the cum and femcum staining Gabriel's crotch makes the angel flush bright red, looking down over himself in shame. Then he stammers, 'I - I... yes. I like it. I need it. My [if cunts of player > 0]mistress said she'd[otherwise]master said he'd[end if] fuck me all the time from now on.' The other angel just gives you an approving nod, 'Nice work training the little slut. Seems you've got Gabe turned into a subby pet, don't you. I'll have to tap that ass myself too sometime...' Before you can reply anything, Elijah then saunters out of the room, going up, most likely to hunt down something to fuck outside.";
			move Gabriel to bunker;
			move player to bunker;
			repeat with y running from 1 to number of filled rows in table of random critters:
				choose row y in table of random critters;
				if name entry is "Seraphim":
					now monster is y;
					now area entry is "nowhere";
					break;
	otherwise:
		say "     [line break]";
		say "     You decide to just go, leaving Gabriel to pick himself up on his own.";
	
to say SeraphVictorious:
	if hp of player > 0:    [player submits]
		say "     As you submit, Gabriel presses his glowing hand against your forehead, causing you to scream in pain from the sensations of a fiery fingers rifling through your mind. They drag questionable things you have done in the past to its forefront and shine a light on them, banishing whatever justification you thought you had before. Then he lets go and helps you sit down to hold your head and process what just happened. 'There - this is enough for now or I would break your mind. Ponder these acts and better yourself. Return when you are ready for more. I will patrol these streets for demons until you are back.'";
	otherwise: [player loses]
		say "     As you collapse in defeat, Gabriel presses his glowing hand against your forehead, causing you to scream in pain from the sensations of a fiery fingers rifling through your mind. They drag questionable things you have done in the past to its forefront and shine a light on them, banishing whatever justification you thought you had before. Then he lets go and leaves you to crumple on the floor. 'There - this is enough for now or I would break your mind. Ponder these acts and better yourself. Return when you are ready for more - and be sure that I will hunt you down if you do not.'";
	
to say SeraphDesc:
	if hp of Gabriel is 2:
		say "     Turning around a street corner, you suddenly find yourself face to face with the angel you saw search for Elijah earlier - and hacking apart or interrogating demons while doing that. The divine warrior's handsome face turns to you and his eyes widen as he recognizes you from the incubus['] description, then he says, 'Hello Mortal, you may call me Gabriel. I heard you have had a hand in the disappearance of my brother in arms Elijah. Explain yourself!'";
		say "     [line break]";
		say "     [link](1)[as]1[end link] - Just tell him what you did.[line break]";
		say "     [link](2)[as]2[end link] - Make up a convincing lie.[line break]";
		say "     [link](3)[as]3[end link] - Run away.[line break]";
		now calcnumber is 0;
		while calcnumber < 1 or calcnumber > 3:
			say "Choice? (1-3)>[run paragraph on]";
			get a number;
			if calcnumber is 1 or calcnumber is 2 or calcnumber is 3:
				break;
			otherwise:
				say "Invalid choice. Type [link]1[end link] to admit everything, [link]2[end link] to lie or [link]3[end link] to run away.";
		if calcnumber is 1: [admitting]
			say "     Steeling your nerves for the likely reaction from this divine warrior, you come clean and admit how you corrupted Elijah, turning him into a vain and lust-filled shadow of his former self. Gabriel's eyes harden with every word you speak and his right hand strays to the grip of his flaming sword, closing halfway around it, then he shakes his head and says, 'No, even as vile and despicable as you are, you are still of those I was made to protect. I long to be done with you and hasten to save my brother from the pit you've pushed him in, but duty comes first, always. You WILL be cleansed you from your sins even if I have to BURN it out of you - and then you WILL assist me in saving Elijah.'";
			say "     A pale-white glow appears around Gabriel's hands and the angel's expression hardens. 'This will not be without pain - and you deserve nothing less. Do not struggle against me, it is only to your best,' he says, then steps forward and reaches out for you.";
		otherwise if calcnumber is 2: [lying]
			say "     Cold sweat runs down your back as you try to come up with some convincing story that doesn't enrage someone armed with a flaming sword... but as you open your mouth to speak, the angel raises his hand. 'Don't bother lying - guilt hangs around you like a rotten stench. I can see that dark influences have affected you and nothing you say can be believed.' His right hand strays to the grip of his flaming sword, closing halfway around it, then he shakes his head and says, 'No, corrupted as you are, you are still of those I was made to protect. Since a proper interrogation is out of the question, I will have to do this the hard way - cleansing you from your sins bit by bit until you are ready to assist me in saving Elijah.'";
			say "     A pale-white glow appears around Gabriel's hands and the angel's expression hardens. 'This will not be without pain, but it is for your best. Do not struggle against me,' he says, then steps forward and reaches out for you.";
		otherwise if calcnumber is 3: [running]
			say "     You turn and run - only to find Gabriel standing before you some moments later, folding his wings after a short dash through the air. He's got you on mobility, that's for sure. 'Halt! Your actions prove your guilt - and now I can see that dark influences have affected you and nothing you say can be believed.' His right hand strays to the grip of his flaming sword, closing halfway around it, then he shakes his head and says, 'No, corrupted as you are, you are still of those I was made to protect. Since a proper interrogation is out of the question, I will have to do this the hard way - cleansing you from your sins bit by bit until you are ready to assist me in saving Elijah.'";
			say "     A pale-white glow appears around Gabriel's hands and the angel's expression hardens. 'This will not be without pain, but it is for your best. Do not struggle against me,' he says, then steps forward and reaches out for you.";
	otherwise if hp of Gabriel is 3:
		say "     You run into an angel on the seedy streets of the red light district - and it's one you know... Gabriel. He turns his head to look you up and down, then says, 'I still sense some darkness in your soul. Please do not resist - this is only to help you.' With that, he steps forward, white light glowing around his raised hand.";	
	otherwise if hp of Gabriel is 4:
		say "     You run into an angel on the seedy streets of the red light district - and it's one you know... intimately. Gabriel looks at you and hesitates a second, biting his lip, then says, 'I still sense some darkness in your soul. Please do not resist - this is only to help you.' With that, he steps forward, white light glowing around his raised hand.";	
	otherwise if hp of Gabriel is 5:
		say "     You run into an angel on the seedy streets of the red light district - and it's one you know... intimately. After all, he's only a real man because of your actions. Gabriel looks at you and hesitates a second, biting his lip, then says, 'I still sense some darkness in your soul. Please do not resist - this is only to help you.' With that, he steps forward, white light glowing around his raised hand.";	
	otherwise if hp of Gabriel is 6:
		say "     You run into an angel on the seedy streets of the red light district - and it's one you know... intimately. Gabriel still wears the tight leather collar you put onto him, and you can see his face flush as he gulps at your presence. A small bulge appears at the front of his pants, but for now, he manages to control himself, biting his lip before saying, 'I - I must do my duty. Cleanse you from your wickedness. Please do not resist - this is only to help you.' With that, he steps forward, white light glowing around his raised hand.";	
		
Section 2 - Monster Insertion 

Table of random critters (continued)
name	attack	defeated	victory	desc	face	body	skin	tail	cock	face change	body change	skin change	ass change	cock change	str	dex	sta	per	int	cha	sex	hp	lev	wdam	area	cocks	cock length	cock width	breasts	breast size	male breast size	cunts	cunt length	cunt width	libido	loot	lootchance	scale (number)	body descriptor (text)	type (text)	magic (truth state)	resbypass (truth state)	non-infectious (truth state)	nocturnal (truth state)	altcombat (text)
--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	-- 	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--;

When Play begins:
	Choose a blank row from Table of random critters;
	now name entry is "Seraphim";
	now attack entry is "[one of]The Seraphim calls out, 'Surrender! This just prolongs your pain. It will be over quickly if you do not struggle.' Then he smites you with a faintly glowing hand.[or]Your angelic opponent calls out, 'Stop fighting, foolish mortal - I only want to help you!' Then he gives you a hard punch in the face, a mixture of regret and annoyance on his face.[or]Hooking a foot behind your leg, the Seraphim pulls it out from under you. As you crash down on the ground, he calls out, 'Surrender, I do not wish to hurt you more than necessary.'[at random]";
	now defeated entry is "[SeraphDefeated]";
	now victory entry is "[SeraphVictorious]";
	now desc entry is "[SeraphDesc]";
	now face entry is "quite beautiful, with chiseled features bare of even the slightest imperfection. A full head of shoulder-length and slightly curled brown hair frames the picture of a handsome male";
	now body entry is "that of a well-built and muscular human being, toned and strong. It is garbed in a robe of pure white, flowing fabric. Two large wings sprout from your back, bearing white feathers";
	now skin entry is "[one of]pale, flawless[or]pristine[or]perfect[at random]";
	now tail entry is "You have a round, firm bubble butt, just waiting to be grabbed.";  [ Tail desc., written as a full sentence or left blank for none. ]
	now cock entry is "[one of]amazing[or]perfect[or]human-like[at random]";
	now face change entry is "your facial muscles seem to ripple under the skin, rearranging themselves into perfectly sculpted male features. Shoulder-length locks of brown hair form to frame your handsome visage"; [ face change text. format as "Your face feels funny as (your text)" ]
	now body change entry is "it is reshaped into a very well-built form, leaving you with a toned and strong human-like body. A moment later, a pair of large white wings unfold behind your back, leaving you to wonder if you might fly once you've figured out how they actually work. Then finally, there is a short ringing in the air behind you, as if from hundreds of tiny bells, leaving you to find a neatly folded white robe on the ground as you turn around. Slipping into the silk-soft item of clothing, you just feel right";
	now skin change entry is "it seems to soften and smooth out, creating the impression of timeless youth. Any blemishes and unwanted hair are wiped away with a wonderfully pleasant sensation that leaves you with perfect skin";
	now ass change entry is "it tightens up into a firm, round bubble butt";
	now cock change entry is "it becomes human-like, uncut and well-proportioned";
	now str entry is 20;                  [ These are now the creature's stats... ]
	now dex entry is 18;                  [ ...and are only altered onto the player via Shifting or the Mighty Mutation feat ]
	now sta entry is 16;                  [ These values may be used as part of alternate combat.]
	now per entry is 14;
	now int entry is 16;
	now cha entry is 18;
	now sex entry is "Male";              [ Infection will move the player towards this gender.  Current: 'Male' 'Female' 'Both' ]
	now hp entry is 85;                   [ The monster's starting hit points. ]
	now lev entry is 13;                  [ Monster level.  (Level x 2) XP for victory.  (Level / 2) XP for losing. ]
	now wdam entry is 12;                 [ Monster's average damage when attacking. ]
	now area entry is "Nowhere";          [ "Outside" "Mall" "Park" "Beach" etc... Check an existing creature in the area. ]
	now cocks entry is 1;                 [ How many cocks will the infection try and cause if sex is 'Male' or 'Both']
	now cock length entry is 9;           [ Length infection will make cock grow to if cocks]
	now cock width entry is 6;            [ Size of balls apparently ;) sneaky Nuku]
	now breasts entry is 2;               [ Number of Breasts infection will give you. ]
	now breast size entry is 0;           [ Size of breasts infection will try to attain ]
	now male breast size entry is 0;      [ Breast size for if Sex="Male", usually zero. ]
	now cunts entry is 0;                 [ if sex = "Female or both", indicates the number of female sexes infection will grant you.]
	now cunt length entry is 6;           [ Length of female sex  infection will attempt to give you. ]
	now cunt width entry is 4;            [ Width of female sex  infection will try and give you ] 
	now libido entry is 25;               [ Amount player Libido will go up if defeated ]
	now loot entry is "";                 [ Loot monster drops, ]
	now lootchance entry is 0;            [ Chance of loot dropping 0-100 ]
	now scale entry is 3;                 [ Number 1-5, approx size/height of infected PC body:  1=tiny, 3=avg, 5=huge ]
	now body descriptor entry is "angelic";
	now type entry is "angel";
	now magic entry is false;             [ Is this a magic creature? true/false (normally false) ]
	now resbypass entry is false;         [ Bypasses Researcher bonus? true/false (almost invariably false) ]
	now non-infectious entry is false;    [ Is this a non-infectious, non-shiftable creature? True/False (usually false) ]
	blank out the nocturnal entry;        [ True=Nocturnal (night encounters only), False=Diurnal (day encounters only), blank for both. ]
	now altcombat entry is "default";     [ Row used to designate any special combat features, "default" for standard combat. ]

Section 3 - NPC

Gabriel is a man.
The hp of Gabriel is normally 0.
The description of Gabriel is "[Gabrieldesc]".
The conversation of Gabriel is { "Mew!" }.

to say Gabrieldesc:
	say "     Gabriel is tall and well-built, looking an early 20 years old. He has an unlined, very pretty face with azure eyes, crowned by a full head of curly brown hair that falls down to his shoulders. Being your submissive pet now, he always wears the collar, wrist-cuffs and leather anklet straps you picked out for him, combined with a very tight set of jeans. As he isn't allowed to go outside, he simply goes barefoot all the time too, just like he leaves his chest bare for you to enjoy some very handsomely sculpted abs. Two large white wings are folded together behind the angel's back, which tend to spread out a bit and move animatedly when he's talking to you.";

instead of sniffing Gabriel:
	say "Gabriel is surrounded by the faint smell of sandalwood.";

instead of fucking Gabriel:
	say "<Sorry, this project hasn't advanced to full on sex with the npc yet>";
	
Seraphim ends here.