Version 1 of Zephias by Wahn begins here.

Section 1 - Zephias the spidertaur

[ Lust of Zephias                                                        ]
[  0: player hasn't met him with the captive Julio yet                   ]
[  1: player met the spidertaur with his captive soldier before          ]
[  2: player learned that Julio is gay and doesn't fuck women            ]

Zephias is a man.
The description of Zephias is "[Zephiasdesc]";
The conversation of Zephias is { "Meep!" }.

instead of sniffing Zephias:
	say "    A";

to say Zephiasdesc:
	say "    A";

instead of conversing Zephias:
	say "    A";


Section 2 - Events

Captured Soldier is a situation. Captured Soldier is resolved.
The sarea of Captured Soldier is "Warehouse";

when play begins:
	add Captured Soldier to badspots of guy;     

Instead of resolving a Captured Soldier:
	if lust of Zephias is 0:  [first time]
		say "     As you make your way through the chaos of abandoned, sometimes smashed vehicles on the street, you spot several large shapes in the distance, flying about a hundred feet above the street and getting bigger - it's a trio of wyverns, out hunting together. Best to avoid attracting their attention, so you hurriedly rush over to one of the side alleys, throwing yourself out of sight just moments before the huge shadows of the massive creatures sweep over the street. They screech to each other, seemingly disappointed by the absence of prey around here, then the sounds of large flapping wings abates as they move on. Phew, seems like ...";
		say "     [WaitLineBreak]";
		say "     'My, my - whom do we have here? Elijah's little fucktoy.' says a voice from deeper in the alley. Turning that way, you see that it's a spidertaur - and one you know at that. With his handsome features, muscular upper body and a spider body with green body-paint, it's almost impossible not to recognize Zephias, the guy who fashioned a silken sex-nest for Elijah and got to fuck you as payment for that. A shiver of lust runs through your body as you think back to him dominating you, thrusting into your tied-up body - then you shake off the memory and focus on what Zephias is carrying. It's a humanoid shape, wrapped in many strands of silk, and you can see a military uniform through the gaps between the binding.";
		say "     Giving you a wide grin as he sees you staring, Zephias says 'Ah, but where are my manners. Fucktoy, meet soldier boy.' He gives his captive's ass a grope, causing the man to struggle futilely for a second and mumble something into the silken gag in his mouth. 'Just caught him in one of my webs. Gonna take this little stud home and have some fun with him. Isn't he cute?' With that, he lowers the soldier from his shoulder, turning him around to face you. He's a good-looking young guy, pretty fit and well-built from what you can see, with a mane of somewhat longer than regulation black hair. He looks at you with an imploring gaze and murmurs something into his gag.";
		say "     [line break]";
		say "Do you want to do something about this situation? Zephias is a fairly reasonable guy from all accounts, he'd most likely let the soldier go if you offered yourself to take his place. Do you do so? ";
		if player consents: [random selection if Zephias or the soldier fucks the player]
			say "     [line break]";
			say "     [ZephiasJulioRandomSelection]";
		otherwise:	[let Zephias carry the guy off]
			say "     [line break]";
			say "     You stay silent as the bound man gets hefted back on Zephias shoulder and the spidertaur says 'No worries about my little soldier boy - I won't let anything happen to him. At worst he'll have trouble sitting down for a day or two after I let him go later.' Zephias says and gives his captive's ass another quick squeeze, then scuttles off down the alleyway."; 
		now lust of Zephias is 1;
	otherwise:  [repeat scene]
		say "     As you make your way through the chaos of abandoned, sometimes smashed vehicles on the streets, you duck into an alley at one point to get around the wreck of a truck blocking the road ahead. Walking in the shadowy alley, you're halfway through when suddenly someone else enters from the other end, a large shape carrying a white bundle. It's Zephias, a cocooned body over his shoulder. Peeking out from under the silk strands binding the man, a military uniform can be seen, as well as his somewhat longer than regulation black hair. Could that be... the same soldier he had with him when you met last time in this area?";
		say "     Giving you a wide grin, Zephias says 'What a coincidence, here we three meet again.' He gives his captive's ass a grope, causing the man to struggle futilely for a second and mumble something into the silken gag in his mouth. 'Julio here just can't stay out of my traps it seems. Or maybe he actually wants to be dragged off to my lair to be fucked...' Lowering the soldier from his shoulder, Zephias turns him to face you and says 'Do say hello to Fucktoy, my little soldier boy' - after which Private Vasquez murmurs something into his gag and gives you a nod. Then the large spidertaur puts his hands on his bound captive again, taking hold of several though silk strands to carry him away to his lair.";
		say "     [line break]";
		say "Do you want to do something about this situation? Zephias is a fairly reasonable guy from all accounts, he'd most likely let the soldier go if you offered yourself to take his place. Do you do so? ";
		if player consents:
			say "     [line break]";
			if lust of Zephias is 2 and cunts of player > 0 and cocks of player is 0:  [that Julio is gay is known, so the female sex option with him doesn't come up]
				say "     Coming to a decision, you speak up and ask for Zephias to let his captive go free. The spidertaur gives you a lust-filled leer, then says 'Agreed.' Then he ruffles his captive's hair with one hand, telling the young man 'Hear that, soldier boy? She's so concerned about you that she offers himself in your place. How sweet.' He lowers the soldier to the ground, positioning him to sit against the building wall on one side of the alley, still wrapped tight in his silk bindings. 'There, you even get a ringside seat for the show.' Zephias says and chuckles. Ignoring the man mumble something into his gag, the spidertaur then turns to you and says 'Okay fucktoy, strip!'";
				say "     A lustful shiver runs down your spine as you hear the hybrid creature's order, striking a cord with your submissive nature. You drop your gear on the ground and start giving the two of them a little show, stretching and turning as you slide off your clothes piece by piece. You can almost feel their eyes on your exceedingly naked form, making you feel all warm inside and very sexy. By the time you're completely naked, Zephias human-like shaft is fully hard, jutting out from between protective chitinous plates.";				
				say "     [WaitLineBreak]";
				say "     [ZephiasAlleyFuck]";								
			otherwise:  [random selection if Zephias or the soldier fucks the player]
				say "     [ZephiasJulioRandomSelection]";
		otherwise:	[let Zephias carry the guy off]
			say "     [line break]";			
			say "     You stay silent as the bound man gets hefted back on Zephias shoulder and the spidertaur says 'No worries about my little soldier boy - I won't let anything happen to him. At worst he'll have trouble sitting down for a day or two after I let him go later.' Zephias says and gives his captive's ass another quick squeeze, then scuttles off down the alleyway."; 				
		

to say ZephiasJulioRandomSelection:
	if a random chance of 1 in 2 succeeds:	[Zephias fucks the player]		
		say "     Coming to a decision, you speak up and ask for Zephias to let his captive go free. The spidertaur gives you a lust-filled leer, then says 'Agreed.' Then he ruffles his captive's hair with one hand, telling the young man 'Hear that, soldier boy? [if cunts of player > 0 and cocks of player is 0]She's so concerned about you that she offers himself in your place. How sweet.' [otherwise]He's so concerned about you that he offers himself in your place. How sweet.' [end if]He lowers the soldier to the ground, positioning him to sit against the building wall on one side of the alley, still wrapped tight in his silk bindings. 'There, you even get a ringside seat for the show.' Zephias says and chuckles. Ignoring the man mumble something into his gag, the spidertaur then turns to you and says 'Okay fucktoy, strip!'";
		say "     A lustful shiver runs down your spine as you hear the hybrid creature's order, striking a cord with your submissive nature. You drop your gear on the ground and start giving the two of them a little show, stretching and turning as you slide off your clothes piece by piece. You can almost feel their eyes on your exceedingly naked form, making you feel all warm inside and very sexy. By the time you're completely naked, Zephias human-like shaft is fully hard, jutting out from between protective chitinous plates.";				
		say "     [WaitLineBreak]";
		say "     [ZephiasAlleyFuck]";
	otherwise:		[the player is told to fuck themselves on the captive soldier's cock]
		say "     Coming to a decision, you speak up and ask for Zephias to let his captive go free. The spidertaur gives you a lust-filled leer, then says 'Agreed.' Then he ruffles his captive's hair with one hand, telling the young man 'Hear that, soldier boy? [if cunts of player > 0 and cocks of player is 0]She's so concerned about you that she offers himself in your place. How sweet.' [otherwise]He's so concerned about you that he offers himself in your place. How sweet.' [end if]He lowers the soldier to the ground, positioning him on his back, then cuts away those strands wrapped around his hips and pulls down the young man's zipper. 'Your ass is safe, soldier boy - but I still want to see you in action today.' Zephias says and chuckles, pulling down the soldier's pants a bit to reveal his whole crotch and half-hard cock. Ignoring the man mumble something into his gag, the spidertaur then turns to you and says 'Okay fucktoy, strip! And after that you'll mount him.'";
		if cocks of player is 0 and cunts of player > 0:  [female player - though that doesn't get Julio hard]
			say "     A lustful shiver runs down your spine as you hear the hybrid creature's order, striking a cord with your submissive nature. You drop your gear on the ground and start giving the two of them a little show, stretching and turning as you slide off your clothes piece by piece. You can almost feel their eyes on your exceedingly naked form, making you feel all warm inside and very sexy. By the time you're completely naked, Zephias human-like shaft is fully hard, jutting your way from between protective chitinous plates. The soldier on the other hand... isn't hard at all. 'Oh, is our little Fucktoy not to your liking? Guess you'd have preferred the time in my lair more, then. Oh well...' he pulls the soldier a bit to the side, positioning him to sit against the building wall on one side of the alley '...then I get to fuck her and you can watch.'.";					
			say "     [WaitLineBreak]";					
			say "     [ZephiasAlleyFuck]";
		otherwise:	[male, herm, neuter players]
			say "     A lustful shiver runs down your spine as you hear the hybrid creature's order, striking a cord with your submissive nature. You drop your gear on the ground and start giving the two of them a little show, stretching and turning as you slide off your clothes piece by piece. You can almost feel their eyes on your exceedingly naked form, making you feel all warm inside and very sexy. By the time you're completely naked, the soldier's cock stands erect as a flagpole, showing his clear arousal at watching your performance. Zephias puts a hand on it and strokes up and down a few times, then waves you closer.";
			say "     [WaitLineBreak]";					
			say "     [RidingJulio]";				
								
to say ZephiasAlleyFuck:
	setmonster "Spidertaur";
	choose row monster from the table of random critters;	
	if cunts of player > 0:
		say "     Arranging your dropped clothes to give at least a bit of comfort over the bare stone ground, you lie down on them and obediently spread your legs for Zephias. The spidertaur is on you in seconds, running one of his human hands over your crotch, stroking along your sensitive nether lips, then pushing two fingers into your pussy. He says 'Very nice, little slut. I'm gonna fuck your hot little hole so hard...', replacing his probing digits a moment later with something much thicker and longer.";
		say "     You feel his hard rod against your pussy lips, nudging them apart as he pushes forward and enters your body. He slides deeper slowly but surely, grinning down at you as the feeling of his shaft rubbing your insides makes you moan. Soon he's all the way in, his cock poking the entrance to your womb and you can feel the chitinous plates of his lower body against your crotch. Stroking your legs with his human hands, he then starts to thrust in and out, fucking you with deep strokes. Pulling out till only the tip of his cock remains inside you, then slamming it all the way in again, he has you gasping in lust and squirming under him in no time. 'You like that, don't you? Getting fucked hard and fast in front of an audience. Go on, give [if lust of Zephias < 2]soldier boy [otherwise]Julio [end if]a wave. You haven't forgotten him already, have you?'";
		say "     [WaitLineBreak]";
		say "     Panting and moaning as the spidertaur thrusts into you again and again, you weakly turn your head to the bound soldier sitting against the wall and watching you and wave a hand to him. There really is something to what he says, a little bit of extra naughtiness at getting fucked with others watching - just like Elijah was when the spidertaur got to fuck you as payment for his services.";
		say "     Zephias takes great pleasure in dominating you, his cock twitching every time you give him an involuntary moan after one of his sudden thrusts. After quite a bit more hot and hard fucking, he groans 'Time for the finale of our little show, pet. I'm gonna.... cuummmMMM!', pushing all of his shaft into you one last time and gives a satisfied grunt with each shot of cum directly into your womb as he orgasms. The dominant spider-hybrid coming inside you, using your body for his pleasure, pushes you over the edge right with him [if cocks of player > 0]and your own cock starts pulsing as long strings of cum splatter all over your chest.[otherwise]and femcum starts gushing out around his shaft from your well-bred pussy.[end if][fimpregchance]";
	otherwise if cocks of player > 0:
		say "     Arranging your dropped clothes to give at least a bit of comfort over the bare stone ground, you lie down on them and obediently spread your legs for Zephias. The spidertaur is on you in seconds, running one of his human hands over your crotch, jerking your cock a few times, then moving down to brush over your pucker and making you moan in anticipation. Leaning forward, he holds to fingers out for you to take into your mouth and suck on, then when they are good and wet, he pushes them against into your ass. Stretching your pucker with his fingers in preparation, he says 'Very nice, little slut. I'm gonna fuck your hot little hole so hard...', replacing his probing digits a moment later with something much thicker and longer.";	
		say "     You feel his hard rod against your asshole, pushing forward until your pucker yields to the pressure and allows him in. He slides deeper slowly but surely, grinning down at you as the feeling of his shaft rubbing your insides makes you moan. Soon he's all the way in, his cock poking pleasure spots you didn't know you had, and you can feel the chitinous plates of his lower body against your butt. Stroking your legs with his human hands, he then starts to thrust in and out, fucking you with deep strokes. Pulling out till only the tip of his cock remains inside you, then slamming it all the way in again, he has you gasping in lust and squirming under him in no time. 'You like that, don't you? Getting fucked hard and fast in front of an audience. Go on, give [if lust of Zephias < 1]soldier boy [otherwise]Julio [end if]a wave. You haven't forgotten him already, have you?'";
		say "     [WaitLineBreak]";
		say "     Panting and moaning as the spidertaur thrusts into you again and again, you weakly turn your head to the bound soldier sitting against the wall and watching you and wave a hand to him. There really is something to what he says, a little bit of extra naughtiness at getting fucked with others watching - just like Elijah was when the spidertaur got to fuck you as payment for his services.";		
		say "     Zephias takes great pleasure in dominating you, his cock twitching every time you give him an involuntary moan after one of his sudden thrusts. After quite a bit more hot and hard fucking, he groans 'Time for the finale of our little show, pet. I'm gonna.... cuummmMMM!', pushing all of his shaft into you one last time and gives a satisfied grunt with each shot of cum deep into your asshole as he orgasms. The dominant spider-hybrid coming inside you, using your body for his pleasure, pushes you over the edge right with him and your own cock starts pulsing as long strings of cum splatter all over your chest.[mimpregchance]";
	otherwise:
		say "     Arranging your dropped clothes to give at least a bit of comfort over the bare stone ground, you lie down on them and obediently spread your legs for Zephias. The spidertaur is on you in seconds, running one of his human hands over your featureless crotch, then moving down to brush over your pucker and making you moan in anticipation. Leaning forward, he holds to fingers out for you to take into your mouth and suck on, then when they are good and wet, he pushes them against into your ass. Stretching your pucker with his fingers in preparation, he says 'Very nice, little slut. I'm gonna fuck your hot little hole so hard...', replacing his probing digits a moment later with something much thicker and longer.";	
		say "     You feel his hard rod against your asshole, pushing forward until your pucker yields to the pressure and allows him in. He slides deeper slowly but surely, grinning down at you as the feeling of his shaft rubbing your insides makes you moan. Soon he's all the way in, his cock poking pleasure spots you didn't know you had, and you can feel the chitinous plates of his lower body against your butt. Stroking your legs with his human hands, he then starts to thrust in and out, fucking you with deep strokes. Pulling out till only the tip of his cock remains inside you, then slamming it all the way in again, he has you gasping in lust and squirming under him in no time. 'You like that, don't you? Getting fucked hard and fast in front of an audience. Go on, give [if lust of Zephias < 1]soldier boy [otherwise]Julio [end if]a wave. You haven't forgotten him already, have you?'";
		say "     [WaitLineBreak]";
		say "     Panting and moaning as the spidertaur thrusts into you again and again, you weakly turn your head to the bound soldier sitting against the wall and watching you and wave a hand to him. There really is something to what he says, a little bit of extra naughtiness at getting fucked with others watching - just like Elijah was when the spidertaur got to fuck you as payment for his services.";		
		say "     Zephias takes great pleasure in dominating you, his cock twitching every time you give him an involuntary moan after one of his sudden thrusts. After quite a bit more hot and hard fucking, he groans 'Time for the finale of our little show, pet. I'm gonna.... cuummmMMM!', pushing all of his shaft into you one last time and gives a satisfied grunt with each shot of cum deep into your asshole as he orgasms. The dominant spider-hybrid coming inside you, using your body for his pleasure, pushes you over the edge right with him and you climax, a tingly feeling of satisfaction spreading through you from your crotch.[mimpregchance]";		
	say "     [WaitLineBreak]";		
	say "     After he finishes cumming, Zephias pulls his shaft out of you with a wet slurp and gives your freshly fucked form an appraising look before remarking 'I really have to congratulate Elijah again for owning such a nice submissive pet. You can go dress now, Fucktoy.' While you stand up and start collecting your gear, the spidertaur cuts his human captive's bindings and allows him to stand up. As the gag comes off, the young man calls to you 'Thanks for the... help? [if lust of Zephias < 1]I'm Private Julio Vasquez by the way.' [otherwise]' [end if]Then his gaze is drawn downward to the trickle of cum running down the inside of your leg and he turns an interesting tone of embarrassed red as his thoughts catch up with what just happened here. He pants 'Thanks' again, then beats a hasty retreat and runs off.";		

to say RidingJulio:
	setmonster "human";
	choose row monster from the table of random critters;		
	if cunts of player > 0:  [herms]
		say "     Walking over to the tied-up soldier, you kneel down and get to work on him, sliding your lips over the head of his manhood and starting to bob up and down on the shaft. Zephias captive moans into his gag as you blow him, his hips soon thrusting upwards as he tries to get more of his cock in your mouth. After a few more minutes, you pull off his manhood with a wet pop, giving its tip one last lick before you move upwards, swinging your legs over your bound partner to straddle his hips. Reaching down with one hand to grasp his wet and slippery shaft, you hold it up and rub it against your moist pussy lips in eager anticipation of feeling him inside you.";
		say "     But then, as you start lowering yourself on it, with the tip just nudging apart your nether lips, the man under you gives you a pretty intense gaze and shakes his head. Seems like he's this hot and bothered not for your pussy, but rather another hole... something you take in stride as you slide a little bit further up his body and bring the young man's hard cock up against your asscrack. Then, with a smile down at the now happily nodding soldier, you push his cockhead against your pucker and gasp as it yields and his manhood penetrates your ass. You go lower and lower, slowly sinking him further into you until finally your buns touch his hips and he's all the way in. Taking a deep breath, you wait for a moment to get used to the hard rod, then start sliding up and down on it. He feels amazing inside you, his hard shaft rubbing your inner walls, making you pant and moan as it hits your prostate.";
	otherwise:   [male and neuter]
		say "     Walking over to the tied-up soldier, you kneel down and get to work on him, sliding your lips over the head of his manhood and starting to bob up and down on the shaft. Zephias captive moans into his gag as you blow him, his hips soon thrusting upwards as he tries to get more of his cock in your mouth. After a few more minutes, you pull off his manhood with a wet pop, giving its tip one last lick before you move upwards, swinging your legs over your bound partner to straddle his hips. [if cocks of player > 0]Reaching down with one hand to grasp his wet and slippery shaft, you hold it up and bring your own manhood against it, rubbing against his as you jerk both off together for a moment.[end if]";
		say "     Then, the anticipation of feeling him inside you burning in you, you bring the young man's hard cock up against your asscrack. With a smile down at the soldier, you push his cockhead against your pucker and gasp as it yields and his manhood penetrates your ass. You go lower and lower, slowly sinking him further into you until finally your buns touch his hips and he's all the way in. Taking a deep breath, you wait for a moment to get used to the hard rod, then start sliding up and down on it. He feels amazing inside you, his hard shaft rubbing your inner walls, making you pant and moan as it hits your prostate.";		
	say "     [WaitLineBreak]";		
	say "     Riding the bound soldier's cock with abandon, your gasps, moans and pants fill the alleyway and echo out into the city. Your captive partner gets off on it quite a bit too, judging from the throb of his rock-hard shaft deep inside your body. With the wild ride you're giving his erect pole, it's not much longer before that drives him over the edge. His whole body stiffens and twitches, lust-filled grunts escaping through his silken gag as he comes, long strings of his human seed squirting deep into your asshole. Feeling the pulse of his cock against your inner walls as he fills you up, your hands just fly to [if cocks of player > 0]grab your own cock, joining your partner in orgasm after just a few seconds of rapid jerking. With a satisfied grunt, you come, squirting your cum over the young soldier's chest to soak into his bindings and shirt.[otherwise]stroke your featureless crotch, caressing the sensitive area and driving you the rest of the way to an orgasm. With a satisfied grunt, you feel a tingly feeling of satisfaction spread through you from your crotch.[end if][mimpregchance]";
	say "     Breathing hard, you rest on top of the bound soldier for a moment with his manhood still inside you, revelling in the feeling of fullness, your eyes closed. Then suddenly, the sound of slow clapping shakes you out of your thoughts. Opening your eyes, you see Zephias standing nearby as he leers at you with lust in his gaze, his spidertaur cock hard and dripping precum from the end. 'A very nice show, Fucktoy - but you're not quite done yet.' he says, with a nod at his own erection. Then he scuttles closer on his many legs, standing over the bound human on the ground an instant later, his cock just inches from your face. Giving an aroused moan at getting used for his pleasure, you lean forward as he puts his hands on your head and starts to face-fuck you with rapid thrusts. Having watched you riding the soldier's shaft and masturbated to it, he's already quite close to his own climax, so it doesn't take all that long until spidertaur cum gushes into your mouth, leaving a spicy taste on your tongue as you eagerly swallow blast after blast of it.";
	say "     [WaitLineBreak]";
	say "     After he finishes cumming, Zephias pulls your head off his shaft with a plop and pushes it back so he can lean down and make out with you. The spidertaur's tongue invades your mouth as his lips press against yours, tasting his own cum. As he pulls back, he holds your head by the chin for a moment, giving you an appraising look before remarking 'I really have to congratulate Elijah again for owning such a nice submissive pet. You can go dress now, Fucktoy.' While you pull off the soldier's cock and go grab your stuff, Zephias cuts his bindings and allows him to stand up. As the gag comes off, the young man calls to you 'Thanks for the... help? [if lust of Zephias < 1]I'm Private Julio Vasquez by the way.' [otherwise]' [end if]Then his gaze is drawn downward to the trickle of cum running down the inside of your leg and he turns an interesting tone of embarrassed red as his thoughts catch up with what just happened here. He pants 'Thanks' again, then beats a hasty retreat and runs off.";
	
Zephias ends here.