Version 1 of Skarnoth-Brutus scenes by Luneth begins here.

[ Stamina of Skarnoth (evil Brutus)                                       ]
[   0: No sexual content offered                                          ]
[   1: Allow royal incubus Skarnoth and evil male Brutus to have sex      ]
[   2: Allow royal incubus Skarnoth and evil herm Brutus to have sex      ]
[   3: Allow royal incubus Skarnoth and evil female Brutus to have sex    ]
[   4: Allow master Skarnoth and evil male Brutus to have sex             ]
[   5: Allow master Skarnoth and evil herm Brutus to have sex             ]
[   6: Allow master Skarnoth and evil female Brutus to have sex           ]
[   7: Allow submissive Skarnoth and evil male Brutus to have sex         ]
[   8: Allow submissive Skarnoth and evil herm Brutus to have sex         ]
[   9: Allow submissive Skarnoth and evil female Brutus to have sex       ]
[  10: Allow mind-broken Skarnoth and evil male Brutus to have sex        ]
[  11: Allow mind-broken Skarnoth and evil herm Brutus to have sex        ]
[  12: Allow mind-broken Skarnoth and evil female Brutus to have sex      ]
[  99: Ban all Skarnoth forms and evil Brutus from having sex             ]

[ Charisma of Skarnoth (good Brutus)                                      ]
[   0: No sexual content offered                                          ]
[   1: Allow royal incubus Skarnoth and pure male Brutus to have sex      ]
[   2: Allow royal incubus Skarnoth and pure herm Brutus to have sex      ]
[   3: Allow royal incubus Skarnoth and pure female Brutus to have sex    ]
[   4: Allow master Skarnoth and pure male Brutus to have sex             ]
[   5: Allow master Skarnoth and pure herm Brutus to have sex             ]
[   6: Allow master Skarnoth and pure female Brutus to have sex           ]
[   7: Allow submissive Skarnoth and pure male Brutus to have sex         ]
[   8: Allow submissive Skarnoth and pure herm Brutus to have sex         ]
[   9: Allow submissive Skarnoth and pure female Brutus to have sex       ]
[  10: Allow mind-broken Skarnoth and pure male Brutus to have sex        ]
[  11: Allow mind-broken Skarnoth and pure herm Brutus to have sex        ]
[  12: Allow mind-broken Skarnoth and pure female Brutus to have sex      ]
[  99: Ban all Skarnoth forms and pure Brutus from having sex             ]

Book 1 - Original Events

Section 1 - Royal Incubus Skarnoth and Evil Brutus Events

Part 1 - Male Brutus
[WIP]

Part 2 - Herm Brutus
[WIP]

Part 3 - Female Brutus
[WIP]

Section 2 - Master Skarnoth and Evil Brutus Events

Part 1 - Male Brutus
[WIP]

Part 2 - Herm Brutus
[WIP]

Part 3 - Female Brutus
[WIP]

Section 3 - Submissive Skarnoth and Evil Brutus Events

Part 1 - Male Brutus

after going to Half-Renovated Room while (Skarnoth is booked and SkarnothMasterSlave > 1 and Stamina of Skarnoth is 0 and demon brute is listed in companionList of Player and DBCaptureQuestVar is 5 and DemonBruteStatus is 0 and "Unchained" is listed in Traits of Skarnoth):
	say "     Note: Once Skarnoth's Master/Slave chain is completed this event will only be encountered if you have sub slave Skarnoth instead of default slave Skarnoth.";
	say "     Walking into the half-renovated room with Brutus at your side, you see the demon prince sitting upon his [']throne['], more than likely attempting to recharge so that he can leave and do whatever it is that he does when you're not around. Out of the corner of your eye, you see the demon brute stop and take in the sight of [if SkarnothThongStatus is 1]a naked Skarnoth[else]Skarnoth[end if]. You try to remember if this is the first time that your pet has seen the royal demon you've claimed, but judging by the look on his face, you assume that it is. Brutus's eyes are wide, and his fanged jaw is hanging open slightly. Without any prompt from either you or Skarnoth, Brutus immediately starts to walk over to the demon prince quickly.";
	say "     Getting down on one knee, the demon brute regards his prince with respect. 'Master! I didn't know this [BodyName of Player in lower case] is yours?! Or do you want to reclaim your worthless servant?' The demonic prince seems shocked at first, but quickly attempts to reel it in. 'So one of my hellguard is serving the [master] as well? Well, that's good. It will make me feel better knowing that [SubjectPro of Player] has a strong warrior by their side.' Brutus is visibly taken aback by the fact that his prince just referred to you as [master]. 'My prince! What do you mean by ['][master][']? Aren't you gonna take me back from the mortal? Or make [ObjectPro of Player] serve you!'";
	WaitLineBreak;
	say "     Skarnoth's eye widen in shock. 'The [master] serving me!? That's crazy. I'm [PosAdj of Player] subby slave, and I wouldn't have it any other way!' Brutus stands up with a look of disdain on his face. 'You worthless whore! Unworthy of my obedience!' Turning his back on his at one point prince, Brutus regards you with even more rage in his eyes than usual, 'You made the old master into your slut?! The hellguard is broken too then. No going back for me now.' For the first time, you see the closest thing to hopelessness enter the demon brute's eyes, all while the demon's erection keeps growing in size.";
	LineBreak;
	say "     [bold type]Do you want to attempt making Brutus feel better?[roman type][line break]";
	say "     ([link]Y[as]y[end link]) - Yes, let the demonic slave play with your royal slut, at least for a bit.";
	say "     ([link]N[as]n[end link]) - No, you don't really like your [']toys['] playing with each other.";
	if Player consents: [This will allow future scenes between the two, also part of the sexual allies route for the master of hell quest]
		LineBreak;
		say "     You confidently walk up to Brutus and begin to stroke his abs with one hand, slowly snaking your way higher, feeling the hard muscles of his pecs. Allowing one of your nails to scrape against his dark-purple nipples causes a sharp intake of breath from the broken demon and what had appeared as despair in his eyes now starts to fill with both lust and rage. Looking down, you can see his uncut dick begin to harden. The firmer it becomes, the less human it appears. Thick bumps begin to form around his shaft from underneath the sensitive flesh while at the same time his foreskin pulls back over the head of his prick, revealing firm ridges hardening just beneath the crown.";
		say "     Reaching up to the side of his face with your other hand, you softly stroke his horned jaw, before hooking a finger behind one of the protrusions, pulling him closer to you. Brutus's expression looks aroused and at the same time leery. Pressing your mouth against the demon's, you can't help but smirk when his lips pull back, baring his fangs. You slip your tongue out and gently caress one of his sharp canines, and a weird sort of purr then starts to come from the demon's chest as his eyes flutter shut.";
		WaitLineBreak;
		say "     You can't help but want to continue stroking the demon's fangs to elicit that sound, your smile beginning to grow bigger the longer Brutus's purr lasts. You eventually pull back, and the demon's eyes slowly open to see you grinning at him. Oddly enough, his face changes color, becoming a much darker indigo, and you can only assume it's because of his lustful desires. However, without warning, he quickly turns his head away from you as an annoyed look forms on his face, and he attempts to stand up straighter. It finally clicks: could it be that he isn't just merely aroused? Could he actually be... embarrassed that you caught him purring?";
		say "     Having come to terms with this new development, you move around Brutus's body until you are once again face to face. The demon opens his mouth, more than likely to attempt to threaten you, however before he can say a word, you surge forward and press your lips to his own. At first, his mouth remains immobile, but eventually, he begins to return the kiss. The demon's powerful arms surround your waist in a crushing grip, his claws digging into your midsection and piercing you. You know that you could use the power of the amulet to control the brute and force him to stop, however you have other plans in mind. Brutus eventually pulls back from the kiss and with a curious look in his eyes, looks down at the thick marks left on your body.";
		WaitLineBreak;
		say "     The demon brute's face morphs into one ready for a threat. 'Why?' That one word speaks volumes to the mindset of the hellspawn, and you can't help but return the question with a simple, 'Why not?' Brutus's chest quickly begins to puff up in an attempt to appear more intimidating. 'Gonna trick me? Break me? Forget it! I'll never bow to a pathetic mortal!' With rising confidence, you remind the demon that you have broken his old master, and you have also broken him to your will. Raising one finger in the air, you silence the outburst of rage you know that is about to pour from the brute's lips and finally say something to make him pause.";
		say "     You explain to him that you don't want another broken toy, but a soldier, an ally, now that is something you have much more interest in. Brutus turns his gaze to the rest of the room, as if preparing himself for some sort of trick or trap. 'Think I'm a fool?! It's just another way to break me into some obedient pet!' Not allowing yourself to react angrily to the outburst from the demon, you calmly explain to him that with Skarnoth under your rule, you are now the new ruler of the hellguard, and effectively now his lord. Before Brutus can make more accusations, you continue speaking and inform him that you have no desire to break him further, or to change him.";
		WaitLineBreak;
		say "     You simply desire to have a powerful, handsome, and brutal general, one that will be loyal and force any and all to bend to your will no matter what. A dark guttural chuckle fills the room, and the demon looks at you with a manic expression in his eyes. 'I'm strong, dumb and convenient. That's what the old master always said! Don't call me 'handsome' just to fuck with my head! Just use me as a tool to break slaves with, like he did!' With that, he pushes his long, thick, forked tongue to slip past his fangs and wiggles it around in an obscene way. Leaning forward, you allow your own tongue to lick upwards against the demon's, apparently shocking him if the loud growl is anything to go by. 'I am tired of your games, mortal!'";
		say "     Reaching up, you begin to fondle with his meaty chest, paying special attention to circling and teasing the flesh around the base of each of the horns adorning his pecs. With your face so close to his own, you lean in and whisper that every ruler needs a dark knight, a being of darkness that will destroy and consume anything in their path. Pulling back, you ask him in your most seductive voice if he won't be the hand that delivers terror and depravity in your name. 'What do I get out of that?!' You simply smile and tell him that he will get everything he wants. The only thing that will be off limits are your other allies, well unless you give permission, but the rest of the city can be his dark paradise, as long as he serves you.";
		WaitLineBreak;
		say "     'Can you make the pain stop?' You assure him that if he stands by your side, you will do everything you can to keep him both happy and sated. Brutus thinks on this for a few moments. Eventually though, an arrogant smile forms on his lips. 'Let's say I want to destroy something with my cock right now. Am I free to leave and snatch up the prey I want?' You can't help but laugh out loud at his request, before pointing behind him, and in a seductive voice, you ask him why go out hunting when the prey has come to him. Turning around, Brutus is met with the sight of his broken master of the past, laying upon his throne like a perfect little subby pet.";
		say "     'You'll share your whore?' Rubbing your body up against the brute's, you tell him to consider the submissive fuck-meat as a gift for his initiation as your general of the new hellguard, the only requirement to obtain this title being to kneel and accept you as his new [master]. A long pause takes place. 'If you are deceiving me, I will destroy you. Somehow.' The words are said so casually that you don't doubt he means what he is saying. With a firm nod of your head, the demon lowers himself down on one knee, and you stroke one of your hands up one of the giant horns on his head and whisper to him that you vow to keep his depraved hunger sated.";
		WaitLineBreak;
		say "     Brutus rises back to his feet, his still hard dick bouncing around with his movement. You let your handle circle around the dark-purple shaft, stroking it firmly and asking the brute if he is ready to claim his reward for becoming your soldier. With a sadistic smile on his face, the demon gives you a nod of approval, and the two of you make your way over towards Skarnoth's throne. The submissive former prince of hell doesn't even acknowledge Brutus and simply looks to you either for praise or orders. You explain to your slut that since Brutus has chosen to follow you faithfully that you have decided to offer him as a reward for the brute.";
		say "     The look on Skarnoth's face is mortified, '[Master], you can't be serious! I have never fucked a brute, I mean come on they're animals, just corruption fodder!' You silence the past royal with a raise of your hand, explaining to him that it has already been decided and that he should be careful of what he says in front of his future [']lover[']. Glancing over at Brutus, you can see that his hard cock is already starting to drip precum on the floor heavily, and you take a step back. Your new soldier takes this as your approval to begin his fun and quickly grabs hold of Skarnoth's massive horns and yanks [if SkarnothThongStatus is 1]his naked form [else]him [end if]to the floor. 'Hey, watch who the fuck you throw on the floor you dum-oooaahh!'";
		WaitLineBreak;
		say "     Your royal slave has his tirade ended quickly by Brutus quickly shoving his entire 18-inches of prick inside of the subby demon's throat, causing his eyes to tear up as he gags and chokes on the immense amount of meat that he is being forced to take in. Brutus looks down at the pitiful sight his past master makes with a vicious grin. 'Shouldn't talk with your mouth full, whore!' As if to exert his own sadistic pleasure, the demon brute then begins to chuckle as he grabs Skarnoth's horns like handlebars and begins to power fuck the royal demon's throat as intensely as if he were screwing the royal slave's ass at full speed. The submissive demon's whole body flops around like a ragdoll as he does all that he can just to stay upright.";
		say "     '[Master], I'm gonna destroy this slut's throat-cunt!' Looking down, you can see that Skarnoth's face is starting to gain a slight blue hue to it from the lack of oxygen being inflicted upon him, and you decide that it would probably be best if you intervene. Walking up to Brutus's side, you pull his face towards your own, and he quickly captures your mouth in a searing kiss, the whole time never letting up on the skull-fucking that is being delivered to Skarnoth's throat. Feeling his long, serpentine tongue swirling around your mouth is almost enough to make you forget why you actually came over. Yanking your head back, you allow your fingertips to travel down the chest of the muscular brute, feeling the immense heat burning from within.";
		WaitLineBreak;
		say "     Breathless, you ask Brutus why he doesn't make use of the subby demon's other hole. 'Good idea, [master]. Its suck-hole is getting loose anyway.' The brute forces Skarnoth's face against his pelvic bone one last time, looking down with a devilish smirk and watching the bitch choke on the cock that is fully encased in the former prince's esophagus. 'You think that this was fun, hell-slut? The best part comes next!' With that, Brutus pushes the subby demon off of his prick, causing him to fall backwards and gasp for breath. Without giving your slave a chance to fully recover, the brute reaches down and grabs one of Skarnoth's legs, pulling it up and moving the former prince into the position he desires.";
		say "     Being forced to balance on one foot while the other is stretched over Brutus's shoulder, Skarnoth looks more like he is attempting to do the splits across the whole length of the brute's body. You can see him look down at the infernal prince's [if SkarnothThongStatus is 1]fully-exposed hole[else]thong-covered ass, before he quickly adjusts his new toy and yanks the obstructing garment down[end if]. 'This is gonna hurt, princeling! I'm gonna enjoy breaking you!' With that last comment, Brutus slams his ribbed shaft inside of Skarnoth, going balls deep, and then begins to pound into him as hard as he possibly can.";
		WaitLineBreak;
		say "     You walk in a slow circle around the two screwing demons, taking in the sight that the pair make. While Brutus appears to be having the time of his life ramming into the demon below him, Skarnoth appears to be either in a state of shock, ecstasy, or agony, you can't be sure which. The infernal prince's brimstone-colored eyes have rolled up into his head, and his long forked tongue is hanging out of his mouth. Finally, he's actually able to focus on you and attempts to plead with you to stop Brutus, '[Master], you have to stop him! His cock is way too thick! At this speed, he's going to destroy me! I can feel my ass breaking!'";
		say "     That information is slightly alarming to say the least, and you look to the demon brute for a reply, who simply rolls his crimson-colored eyes. 'I won't break your toy, [master]. We are demons and heal faster than even those little machines make you do. That's why demons are always virgin tight, no matter how much you use them! Ain't that right, you little cum-whore?!' With that, he ups his pounding speed even further, making Skarnoth release a mixture of squeals and unearthly moans. Realizing that Brutus is right, well going by the demons that you have encountered anyway, you walk back up to his side as he continues to punch fuck his cock into Skarnoth's hole, which does look awfully stretched at this point.";
		WaitLineBreak;
		say "     Watching as the prince's backside jiggles with each thrust, you can't help the playful side that wants to be let out from within you, and you reach over, spanking the subby demon's ass every time the brute pulls his dick back. This causes Brutus to chuckle, and eventually, it becomes a game between the two of you, each trying to make the other mess up the tempo. You notice what feels like a snake trailing up your leg and look down to see that the brute's dark-purple tail has started to coil around your calf. Glancing at his face, you see that he now refuses to make eye contact and what appears to be a burst of rage passes over his features as the color of his flesh darkens.";
		say "     You notice that Brutus is mumbling something in between grunts, and you strain your ears to make out, 'Take it! You know want to! Give into your instinct!' At first, you aren't sure if he is talking to either you or Skarnoth, but then you see the brute's throat being purposely exposed ever so slightly, and without thinking, you give in. Rushing forward, you clamp your mouth over the firm skin you find there and lightly bite down, feeling a surge of heat erupt within your body. 'I'm not some fucking pussy! I can take everything you got!' Those words spur you on, and you deepen the pressure on his neck, and for a moment, you feel as if magma has surged under your skin, and Brutus lets out an ear-shattering roar.";
		WaitLineBreak;
		say "     'I'm gonna blast your insides with my fucking load, you little hell-slut!' Pulling your mouth away from the demon's throat, you look down as he begins to shoot inside of Skarnoth, and the torrent of cum just seems to be never ending. Eventually, Brutus rips his cock free from the vice-like grip that Skarnoth's hole had on him and allows the infernal prince to crumble to the floor. Turning to face you, the demon brute once again pulls you into a heated kiss, but when he pulls back, you are shocked to see the look on Brutus's face. While he doesn't look peaceful, he certainly does look content. Could it have had something to do with the claiming bite you left on him? Not noticing the ideas floating inside of your head, the demon brute turns to his former master.";
		say "     'You're lucky that you aren't a woman, little whore-prince! Otherwise I would have knocked your pussy up past the point of no return, haha!' His laugh while still giving off evil vibes, actually sounds... happy. '[Master], I'm going to try out my new freedom. Call my name though, and I will be there to punish any you desire!' With that Brutus leaves, no doubt to go about checking out the library and the surrounding area without a [']handler[']. Reaching down, you pick up Skarnoth and carry him over to his throne and set him down gently, you take a moment to pet and love up your passed out demon slut, praising him for his efforts.";
		WaitLineBreak;
		say "     You know that you will have to figure out more about how demons work to be able to properly handle these two, but thankfully that's tomorrow's problems. You can't help but also think about Brutus's parting words to Skarnoth, the whole knocking up thing. The idea of using Brutus as a breeding stud does excite you, and what better way to build an army than through conception..[if carried of orc pill case > 0]. Then again, you do have something that you could use to make it possible for Skarnoth and even Brutus himself to get knocked up as well... Time to work on some plans[end if].";
		add "Master's Bite" to the Traits of demon brute;
		now Stamina of Skarnoth is 7; [allowed them]
	else: [This will ban future scenes between the two, also part of the dark harem master route for the master of hell quest]
		LineBreak;
		say "     You confidently walk up to Skarnoth's throne and grab the demonic prince by his jaw, surprising him with a dominating kiss of ownership. Reaching down, you grab his [if SkarnothThongStatus is 1]fully-exposed[else]cloth-covered[end if], half-hard cock and give it a firm squeeze. A moan escapes from the infernal royal's throat, and with a cocky smirk on your lips you decide to let go and walk back over towards your demon brute. Brutus barely acknowledges your presence, too busy glaring daggers at what was once his lord. Once you are close enough, you wrap your fingers around the brute's bumpy and ridged shaft.";
		say "     Slowly, you begin to jerk Brutus off, eliciting a growl from the beast. Stepping further into the demon's personal space, you force him to look you in the eye and bring his face closer to your own. Pressing your mouth against the demon's, you can't help but smirk when his lips pull back, baring his fangs. You slip your tongue out and softly caress one of his sharp canines, and a weird sort of purr then starts to come from the demon's chest. Having had your fun for the moment, you whisper to Brutus, making sure that he understands how both him and his old master belong to you, now and forever. Removing your hand from his dick, you begin to make your way back to the task at hand, with Brutus's essence returning to the amulet.";
		now Stamina of Skarnoth is 99; [blocking further content]

Part 2 - Herm Brutus
[WIP]

Part 3 - Female Brutus
[WIP]

Section 4 - Mind-Broken Skarnoth and Evil Brutus Events

Part 1 - Male Brutus

[after going to Half-Renovated Room while (Skarnoth is booked and SkarnothMasterSlave < 1 and demon brute is tamed and demon brute is active companion and DBCaptureQuestVar is 5 and DemonBruteStatus is 0 and "Unchained" is listed in Traits of Skarnoth):
	say "     Note: Once Skarnoth's Master/Slave chain is completed this event will only be encountered if you have mindbroken slave Skarnoth instead of default slave Skarnoth.";
	say "     ";]

Part 2 - Herm Brutus
[WIP]

Part 3 - Female Brutus
[WIP]

Book 2 - Second Events

Section 1 - Royal Incubus Skarnoth and Evil Brutus Events

Part 1 - Male Brutus
[WIP]

Part 2 - Herm Brutus
[WIP]

Part 3 - Female Brutus
[WIP]

Section 2 - Master Skarnoth and Evil Brutus Events

Part 1 - Male Brutus
[WIP]

Part 2 - Herm Brutus
[WIP]

Part 3 - Female Brutus
[WIP]

Section 3 - Submissive Skarnoth and Evil Brutus Events

Part 1 - Male Brutus

after going to Maintenance Storeroom while (Skarnoth is booked and SkarnothMasterSlave > 1 and Stamina of Skarnoth is 7 and demon brute is listed in companionList of Player and DBCaptureQuestVar is 5 and DemonBruteStatus is 0 and "Soldier" is listed in Traits of demon brute and "Master's Bite" is not listed in Traits of demon brute and HP of Lilith > 0): [12 hours later might need wahn to help with the coding portion for that]
	say "     Walking back into the storeroom that you've been using as a makeshift bedroom, you are slightly surprised to see your demonic slave prince stretched across the small bed, the glow of the limited lighting in the room casting shadows across the demon's form. You're about to ask Skarnoth what exactly he's doing in your personal room, but stop yourself when you realize that the horned stud is asleep. This is a rare opportunity, usually whenever your gaze falls upon the royal hellspawn, he is either smirking or looking at you with nothing but slutty desire. Right now, you are able to see a different side, softer perhaps, or maybe he just appears that way since he isn't playing a [']role['] at the moment. Softly, you close the door behind you and take a single step further into the room, but you stop in your tracks when you hear a heavy thud from the other side of the now closed door.";
	say "     '[Master], I will keep guard over your room.' At first, you are surprised to hear Brutus's voice echoing inside your skull, but you quickly recover, knowing that after claiming the demon brute as your dark knight that things would likely change. Concentrating as much as you can, you ask Brutus if he can hear you. 'Yes, [master]. After I offered myself and you claimed me as yours, it opened a new way for me to receive your orders.' A dark thought enters your mind, and you ask the demon on the other side of the door if he can always read your mind. 'No, I can only hear you when you [']want['] to let me in, but you shouldn't have that same problem. Reading our minds are how our masters track down renegades.' Taking in this new information, you nod your head in acceptance, even though you know that Brutus can't see you do so.";
	WaitLineBreak;
	say "     Looking back over towards the bed, you double-check to make sure that your [']guest['] is still asleep and didn't wake up due to the loud arrival of the heavy demon brute. Your eyes take in the tan flesh of the dark prince's chest, which rises and falls with each deep breath the demon takes. Once you are sure that the fallen prince is still slumbering within dreamland, you allow yourself to fully enjoy the sight that Skarnoth makes resting there. Your slave's broad frame is laying on his side with one of his thick biceps under his head while the other is casually draped over the demon's wide hips. Slowly, you make your way over towards the cot, the feeling of a hunter stalking its prey at the forefront of your mind. 'Haha!' The raspy laugh in your head stops you dead in your tracks till you quickly remember that whatever noise Brutus makes can only be heard within your head.";
	say "     'It might take some time getting used to blocking your thoughts, [master], but... I am enjoying the imagery that you're sending out.' The pleased rumble at the end of the brute's comment excites you. The feeling of doing something naughty, something that you're not supposed to be doing and all the while being encouraged by others to break the rules, it's an adrenaline rush. You continue forward, finally reaching the bed and can't help the feeling of power that courses through your veins as you loom over the unsuspecting Skarnoth. Reaching out, you slowly caress the demon's face and can't believe how innocent he appears while asleep. His long eyelashes flutter slightly in his sleep as your hand creeps even higher up through the silky strands of the incubus's crimson mane. While you've touched the royal's massive horns before, you haven't actually taken the time to examine them closely.";
	WaitLineBreak;
	say "     The ebony-colored keratin feels slick under your fingertips, the thick base leading up to the much narrower sharp points of each large piece of bone. A smile creeps across your mouth at the thought of this powerful and handsome being that has completely given himself over to you, well, with a little bit of training, but still. A soft moan escapes the demon's lips as he moves slightly in his sleep, the sound exciting you further and causing your gaze to lower to Skarnoth's crotch. His [if SkarnothThongStatus is 1]exposed cock is standing fully erect and leaking profusely[else]cloth-covered cock is straining at the material, and judging by the wet spot, is leaking profusely[end if]. An erotic hunger fills your thoughts while an almost electric feeling travels down your spine.";
	say "     A slightly dark and perverse idea enters your mind, and you attempt to open your mind to Brutus and ask him the [']full['] extent of his abilities. '[Master], you have seen my abilities first hand. Why not just give me orders, and I will complete them.' You can make out some slight annoyance in the brute's voice and inform him that it isn't about orders. He's the new leader of your hellguard, meaning that he should feel pride with all of your decisions. A rumbling purr extends through the connection that the two of you share, followed by a feeling of warmth. You can't help but wonder if this is Brutus's... happiness, or if perhaps you are simply imagining it. Deciding to share your plan with your dark knight, a boisterous laugh soon erupts inside your head. 'I like the way your twisted mind works, [master]!'";
	WaitLineBreak;
	say "     Looking back at the entrance of the room, a glowing dark-purple mist begins to flow from underneath and through the small keyhole of the door. A smile of anticipation forms on your lips as you watch the winding smoke creep ever closer. Once it reaches the large cot, it slowly swirls around the legs of the bed and starts to rise. Watching the entity glide over the sleeping prince, you can almost make out a clawed hand caressing Skarnoth's calf and continues trailing up his thigh. The fiery-maned sub moves around slightly in his sleep as a soft moan can be heard, and by now, the mist has reached his [if SkarnothThongStatus is 1]hard, throbbing cock, fully exposed to whatever may happen[else]hard, throbbing cock, still confined within his black thong[end if].";
	say "     As the mist tightens around the former royal's body, you are able to see the indentions from Brutus's clawed hands on the supple tan flesh. You move to Skarnoth's side and gently nudge him in an effort to wake the handsome demon, his eyes finally fluttering open as you murmur that it's time for sleeping beauty to awaken. Looking down into the normally magma-like eyes, at the moment, they appear to be closer to a warm amber color, more than likely due to the demon's sleepy state. '[Master]?' The fallen prince's groggy and questioning tone tells you that he's still not fully awake yet. Leaning down, your nose softly bumps into the man below you, and with no other warning, you quickly capture his lips in a searing kiss that tastes like smoke and chocolate. While you focus on where your mouth meets, you feel a sharp claw caress along your side, almost as if Brutus is reminding you that you're not alone.";
	WaitLineBreak;
	say "     Drawn out moans can be heard from within Skarnoth's throat, causing you to open your eyes and look down his heaving torso. You attempt to hold in a snicker as you watch the purple smoke [if SkarnothThongStatus is 1]weave around your sub's cock[else]quickly pulls off your sub's black thong and weave around his cock[end if]. The glowing mist alternates from sensually gentle strokes to rough quick ones in an effort to never allow their victim to prepare for what's to come. Reaching up, you give one of Skarnoth's dark nipples a sharp twist and enjoy the squeal of both shock and pleasure that seems to vibrate through the fallen prince's entire body. Pulling your mouth away, you smile when the subby incubus rushes to follow your lips with a needy whine. Looking into his now luminescent hellfire eyes, you softly stroke his cheek, watching as his long eyelashes slowly flutter, almost begging for you to come hither.";
	say "     Whispering into the prince's ear for him to close his eyes, an oddly shy smile spreads across his face as he complies, 'Anything you want, [master]. It feels like you're touching me everywhere, please don't stop!' A dark chuckle reverberates through you as you promise that you have no intention of stopping. Your eyes land on where the incubus's throat meets his shoulder, and without warning, a sudden almost instinctual need rises up within you. Remembering your last encounter with Skarnoth and Brutus, you had the same desire to lay claim to the demon brute The only question is do you really want to give into this instinct? You attempt to think of reasons why this would be a bad idea, but the only thing that keeps popping into your mind is that he is already yours, so why not give him what he needs.";
	WaitLineBreak;
	say "     Surging forward, your teeth find purchase, and you bite into the thick meaty flesh before you, feeling his heat and tasting his sweat upon your tongue. A roar erupts from within Skarnoth's chest, sounding more like a feral beast rather than a royal incubus of hell. The demon's hands quickly shoot up and wrap around your neck, holding you in place, not that you need any incentive to continue. Your mind begins to become foggy and even with your eyes closed, you're able to see a vision of a dark castle surrounded by lava and flames.";
	say "     [bold type][italic type]FLASH![roman type]";
	say "     After the bright light, the sight of the castle quickly melts and reforms into that of a room you can only assume is within the large fortress. The room that you are in now has a lush decor, overflowing with crimson silk, ebony velvet pillows and assorted animal furs across the floors. Laying on a large bed that could easily fit ten or more people is Skarnoth being waited on and entertained by the promiscuity of his demonic guests. Looking closer at the prince of hell, you are brought back to when you first met him. The arrogance and self entitlement the being before you still has all of those traits. The room around you begins to tremble, and it only continues to get worse, causing objects to fall off the walls and leading the demons to run screaming out of the room.";
	WaitLineBreak;
	say "     [bold type][italic type]FLASH![roman type]";
	say "     Glancing around the room, it appears that the disaster has already ended at this point. Nothing is left upright within the room and parts of the walls have even collapsed onto the stone floor. Standing in the middle of the room is Skarnoth, and the look on the demon's face is one of anger mixed with indignation, even when one of the doors calmly opens to reveal a beautiful succubus that you recognize immediately as Lilith from that decimated church. Seductively, she saunters over to Skarnoth. 'Lord Skarnoth, due to the chaos on Earth, a portal has opened up, connecting both heaven and hell to the mortal plane.' A dark smile replaces the rage that was on the demon prince's face a moment ago. 'Get the troops ready then. The last thing we want is to be impolite guests and not accept their eager invitation!'";
	say "     You're quickly brought back to reality, not even sure if what you just saw was a vision or a hallucination. Stepping back, you take in the sight of the writhing demon prince moaning in ecstasy as purple smoke works its magic across his muscled form, and your gaze still zeroes in on the mark you left on your subby demon. To be honest, you are a bit shocked that Skarnoth still managed to keep his eyes closed during the claiming bite. '[Master], what was that? It was so... primal. I feel different, [master]. I mean, I already felt that I belong to you, but after that bite, it feels as if every fiber of my being is yours to do with what you want.' With affection in your voice, you agree that he's right, he does belong to you, down to his very core, and a happy smile spreads across the prince's lips.";
	WaitLineBreak;
	say "     Part of you wants to think about what you just saw when you bit the sexy incubus, but looking down at the display your servants are putting on removes all those pesky thoughts from your mind. Reaching over, you rub and knead Skarnoth's thick thigh with your left hand, causing a grunt to rise from the prince's throat as he attempts to thrust his cock further into the tight grip of the demon brute's mist. Slowly, you dip your right into the purple smoke that is the demon brute's current form and swirl your fingers around, caressing the glowing entity. 'Feeling a bit playful, are you, [master]? I thought that you wanted us to focus on your little royal slut here?' Brutus's voice in your mind sounds teasing, but you can also hear the desire in his rumblings.";
	say "     A lust-driven smirk crosses your face as you submerge your hand fully into the glowing mist and begin to mimic a jerking off motion. You're not sure if your actions are having an effect on Brutus or if he is simply giving you what you want, but slowly, some of the smoke starts to corporealize before your eyes. You quickly pull your hand back, not wanting it to potentially be trapped within the solidifying mist, and in the wake of your excitement, you are presented with a dark-purple dick floating in mid-air. Oddly enough, the base is still connected to the mist via glowing tendrils. Watching the hardening cock, you can see the foreskin begin to pull back, revealing the hard ridges just underneath the helmet and the protruding bumps forming along the shaft.";
	WaitLineBreak;
	say "     Reaching out, you wrap your fingers around the thick piece of meat in front of you. Stroking it slowly, you are rewarded by a deep baritone purr inside of your head. Pearls of precum form at the head of Brutus's prick and begin to overflow, and without paying much attention, they dribble down onto Skarnoth's abs. '[Master], you're being awfully naughty. Ya'know that I don't need lube. My body is always ready for you!' With a hint of mirth in your voice, you explain that you must have forgotten and order him to get into a more [']subservient['] position while reminding him to keep his eyes closed. '[Master], you're so naughty, wanting a powerful guy like me to bow down to you like a horny little bitch!' With a chuckle, you inform him that [if carried of orc pill case > 0]if he's a good boy, you will in fact make him into your personal breeding slut, making sure that he is filled up with so many babies that he will never know what it feels like to not be knocked up[else]he's your personal slut, and it's good for him to always be the answer to your desires[end if].";
	say "     Skarnoth's only response is to moan and quickly getting on all fours, presenting his huge ass to your gaze, and you can't help but smack it firmly, enjoying the way his muscled rear jiggles. 'Please, [master], [if carried of orc pill case > 0]I want to be bred. I will give you the most powerful offspring you could ever imagine[else]I want my body to be a riddle that only your touch can unravel[end if]!' No sooner do those words leave the incubus's mouth than the demon brute's ghostly hands reach up and spread the royal's ass, exposing his small pink opening. Feeling wicked, you shoot your hand out in an attempt to grab one of Brutus's glowing incorporeal hands, and oddly enough, you're able to grab it as if it were solid. Pulling it back, you're rewarded with a full bodied demon brute forming from within the mist.";
	WaitLineBreak;
	say "     You had no idea that you could actually grapple the demon from its smoky state. 'Things have changed, [master]. By making me your champion, you have more power over me.' The voice in your mind sounds both amused and proud all at the same time, and you rush your mouth forward to claim his smiling lips, however, before you can fully enjoy the taste of your dark knight, a pleading voice can be heard from the decent-sized cot. '[Master], stop teasing me. Just ram [if player is male]your cock[else]that toy[end if] in, I need it!' Not sure exactly what Skarnoth is talking about, you peer around the demon's large body and are shocked by what you see. Hotdogging the incubus's ass is Brutus's hard cock. Your eyes follow the tendrils of smoke leading back to the brute's now mist-covered but empty crotch.";
	say "     A laugh bubbles out of your mouth, which leads to Skarnoth questioning you, '[Master], what's so funny? Is it amusing to push me to my limits and have me begging for it?!' You can hear the hurt in the incubus's voice and inform him that you are simply happy. This seems to do the trick and causes a smile to cross the prince's mouth. Crisis averted, you are about to lean forward and kiss Brutus, only to have the demon hold his hands up in front of you. With a wink of his crimson-slitted eye, the brute's hands fade into smoke and travel over to Skarnoth once again, spreading his ass open and making it easier for his cock to rub up against the royal hole in front of it. 'See, [master], no body needed.' A smirk forms on your lips at seeing this new playful side to the normally rage-engulfed hellspawn.";
	WaitLineBreak;
	say "     While it's strange to see the demon brute with only smoke for hands, it's certainly a fun turn of events. Stepping forward, you begin to back the demon up against the side of the cot furthest away from Skarnoth and push his large form down. The impact startles the incubus, who up until now thought that it was only the two of you in the room and believed that you were behind him. His gaze snaps open and takes in the sight of the two of you chuckling. '[Master], what's going on?!' Before you can respond, Brutus chooses that exact moment to penetrate his former prince, causing Skarnoth to release a guttural moan as his eyes roll into the back of his head. With a level of casualness that impresses you, the demon brute gets into a proper position with his back up against the wall as he tucks his feet under the groaning demon prince.";
	say "     Skarnoth's body starts to lurch back and forth quickly as Brutus begins to pummel his hole. The whole thing looks slightly odd as while the incubus is being fucked in the ass, his face is right over where the brute's cock [']should['] have been. '[Master], you certainly made the right choice in turning this thing into a dutiful hell slut. Its hole is so tight that it feels like it might break, haha!' While the demon's words arouse you, one thing sticks out in your mind. Ever since he was introduced to Skarnoth, he has referred to him as an it, never as a person. Walking behind the incubus, that at this point can't even keep his head up, your hand darts out and grabs the base of Brutus's cock. '[Master], what are you doing?! Let me fuck this dumb whore!' Those words call back to when you decided to break Skarnoth of his entitlement, however, if you had wanted him to be a dumb broken slut, you would have just destroyed his mind, but... you didn't.";
	WaitLineBreak;
	say "     You demand that Brutus say the incubus's name. 'Haha, is that all? Its name is hell slut. Has a nice ring to it, don't you think?' You explain that while that may be fine during sex time, he needs to also have a level of respect for the demon prince. 'Why should I? He treated all of us like fodder. He wasn't like you. He was a horrible master.' A swell of pride fills your chest at hearing that you are the superior choice, but you also explain to Brutus that the being in front of him is no longer his prince, and since they both belong to you, this in fact makes them brothers. The brute looks slightly uncomfortable by your words. 'Brothers? We are born from the lava pits of Hell. We don't... that word has no meaning to me.' Through the connection that you share with Brutus, you can feel something empty, and you comment on the fact that may have been his past, but not his present.";
	say "     The demon just lays there not moving, well, other than the occasional throbbing from his cock in your hand. 'So I can continue if I can say its... his name once?' You nod your head in agreement. 'Fine! Can I continue turning Skarnoth's ass into a cunt?!' His choice of words cause you to laugh out loud, and while it's not exactly what you had in mind, it's progress. You release your grip on the hellspawn's cock, and without any hesitation, he once again begins to pummel Skarnoth's insides. Walking back over to Brutus, you realize that there is no more room on the cot for your form and instead decide to straddle the brute's torso. The demon refuses to look directly into your eyes. You can only assume it's due to embarrassment from your talk, so you lean forward, gently pressing your lips to his own and allowing your tongue to rub and massage one of the demon's sharp canines, causing a rumbling purr to echo throughout the room.";
	WaitLineBreak;
	say "     Pulling back, Brutus now looks intently into your eyes, as if he wants to say something, so you wait till he is ready. 'Does this mean that I can still just do whatever I want to the rest of the city?' With a smirk, you explain to the brute that you have no intention of trying to turn him into a being of virtue and that Skarnoth is different than those other toys out in the city who are just waiting to be used and broken. A huge smile spreads across the demon's fanged mouth. 'So I can still grab anything I want out there and destroy its holes, well, other than those that belong to you?!' Smiling at how much he sounds like a kid at Christmas, you lean down and before you capture his lips, you whisper that he had better make sure that those whores' holes never recover from what he does to them.";
	say "     The demon brute's response is instant, and he passionately begins to kiss you. He must also have gone back to fucking Skarnoth in earnest, well, if the head shape that's hitting your backside is any indicater. You jump a bit when you feel something slick begin to[if player is female] rub and squirm at your clit[else if player is male] wrap around your cock[else] put pressure on the mound of flesh where your genitals would be located[end if], causing you to throw your head back and moan in pleasure. Looking at Brutus with desire, you see a line of mist leaving his mouth, and he opens it, revealing that his tongue found other uses. Before you can even adjust to this new feeling, another slick member joins the first, this one probing [if player is female]your soft nether lips[else]the rim of your ass[end if], invading your inner walls. You catch on to the fact that both Skarnoth and Brutus are both trying to make you feel pleasure and with a breathy moan, you tell them what good boys they are.";
	WaitLineBreak;
	say "     As the two demons continue to stimulate you, your hips grind back and forth, using Skornoth's tongue for penetration and Brutus's for masturbation. From behind, you hear a squeal from the incubus as his face is pushed hard into your backside, and the familiar scent of salty cum begins to fill the room. Not one to be outdone, you quicken your pace, pushing yourself closer to orgasm until it finally tears through your body. With a[if player is female]high-pitched squeal of your own, your femcum begins flooding onto [else if player is male]loud bellowing roar, your load shoots out in heavy ropes onto [else]loud bellowing roar, your shapeless mound spasms and leaves you lying on [end if]Brutus's abs. Completely exhausted by the passion that overtook the room, you collapse next to the demon brute, forcing him to lay on his side rather than on his back. With a sleepy glaze over your eyes, you notice that Brutus has [']reconstituted['] himself and looks equally satisfied. Reaching over, you pull the hulking male over, making his head rest on your[if Breast Size of player > 0] soft, pillowy[else] hard, muscled[end if] chest.";
	say "     Glancing over with the intention of pulling Skarnoth onto the free side of your body, you are shocked to see the tan adonis huddled in a corner of the cot by himself. Calmly, you ask him why he doesn't come closer and lay with the two of you. 'Why would I come over there? I'm just a cumdump to be used and thrown away, aren't I?' The look of betrayal and sadness in the incubus's lava-like eyes pulls at your heartstrings, and you ask why he feels like that's the case. 'Well, I came here to spend time with you, but instead of what I was hoping for, you had that animal use me!' You can feel one of Brutus's claws tighten at your side either in rage or guilt. You attempt to reach out mentally but can't seem to get a good read, almost as if too many things are overlapping with each other. Not wanting to make Skarnoth any more frustrated than he already is, you inform him that it's a pity that he doesn't want to join because you were looking forward to some cuddle time with him.";
	WaitLineBreak;
	say "     With a huff, the incubus finally comes over and lays his head opposite the demon brute. 'Fine, well, here I am.' Wrapping your free arm around the fallen prince, you are surprised when it's Brutus that breaks the silence. 'So... it's me that made you feel that way?' Silence fills the room for a few tense moments. 'I don't see anyone else calling me nothing but an [']it[']? Do you? I mean, we are demons. It's not like we can ever do anything but try to beat down anyone that doesn't own us!' The venom in the incubus's voice is palpable, but you can't help but wonder if this means that Skarnoth didn't actually hear your earlier conversation with the demon brute. You slowly begin to rub the agitated demon's back in an effort to help comfort him, but before you speak your dark knight prevents you. 'Well... that's our past, not our present.'";
	say "     You're glad that neither of them are looking at your face at the moment. You're a bit blown away by Brutus using your own words, but even more so that he remembered. The brute must be feeling more confident in the conversation because he continues without pause, 'We both belong to the [master], and [SubjectPro of Player] chose us because we are the best at what we do. If you look at it that way, it makes us brother-in-arms.' Skarnoth is getting a bit jittery to your left, leading you to hold him tighter as he speaks, 'We're demons. We don't have brothers, and ya'know it.' The empty way that the former royal says those words forces you to speak, and you tell him that this is a new world for them both and that means that the old rules don't matter anymore. Finally, Brutus sends a solid feeling through the link that you share before he speaks out loud, oddly one of humor, 'Well, out of the two of us, it's a given that I'm the big brother anyway!'";
	WaitLineBreak;
	say "     The incubus prickles at those words. 'You dumbass. The older brother is always decided by who is older and that's me!' The brute seems to mull that over for a bit, until he finally voices his own opinion, 'Yeah, well, I'm bigger, and everyone knows that the bigger brother has to look out for the smaller one! Besides, everyone also knows that the sluttier bottom bitch one is always the little brother. I mean, why have one if you can't breed him?!' You can feel Brutus's face breaking out into a smile against your side. 'Oh yeah? Well why would I ever agree to that? That just makes it sound like I'm still just something to be used!' Skarnoth snaps. At this point, you begin to feel the warning signs of a headache from all of their bickering. Hopefully, the brute to your right can pick it up through the connection you share. 'How about this? You agree to be the lil bro, and I will sometimes bring you back some goodies from city?'";
	say "     You can feel Skarnoth start to shake next to you, but thankfully it's with laughter. 'Oh yeah, that's just what I've always wanted, someone to bring sweets, haha!' Brutus is silent for a moment, but eventually speaks up with a hint of darkness in his voice, 'Who said anything about candy? I meant toys. Ya'know the [master] gave me permission to use anyone out in the city I want, well, as long as they don't belong to them, right, [master]?' Wanting this conversation over so that you can rest, you simply nod your head in the affirmative. Unfortunately, this leads to debates on the best way to capture people, what sort of sluts are the best to turn into fuck toys, and finally what's the best method of shattering a person's will. If you weren't so tired, you may have been more scared by the things that were mentioned, but you still manage a smile before sleep finally overtakes you. The sight of your two demon boys huddled at your side while their tails are intertwined in sheer glee at the chaos they would unleash let you know that things would never be boring at least.";
	add "Master's Bite" to the Traits of demon brute;
	now energy of The-Voice is turns; [saves the turn when the event happened]

Part 2 - Herm Brutus
[WIP]

Part 3 - Female Brutus
[WIP]

Section 4 - Mind-Broken Skarnoth and Evil Brutus Events

Part 1 - Male Brutus

[WIP]

Part 2 - Herm Brutus
[WIP]

Part 3 - Female Brutus
[WIP]

Section 5 - Notes

[Lords of hell
Player - New Master of Hell
Brutus - Hellguard Warriors
Skarnoth - Imp Servants
Lilith or Atticus - Incubus/Succubus Whores
Nala - Mischief Makers
Kyle (incubus) - Slavery & Drugs
]

[need 7 hellspawn for ritual of corruption (just initial ideas)
Lucifer or Chase - Wrath
Boghrim or Grant or Leonard - Pride
Susan or Christy - Lust
Darius or Logan - Greed
Steven or Roman - Envy
Philip or Francois - Gluttony
Frank or Leon - Sloth
]



Skarnoth-Brutus scenes end here.
