Rock And A Hard Place by Voidsnaps begins here.


Table of GameEventIDs (continued)
Object	Name
Stuck	"Stuck"

Stuck is a situation.
ResolveFunction of Stuck is "[ResolveEvent Stuck]".
Sarea of Stuck is "Outside".

when play begins:
	add Stuck to BadSpots of FurryList;

to say ResolveEvent Stuck:
	project the figure of Gargoyle_stuck_icon;
	say "     A pitiful, hoarse voice draws you from the street as you wander, searching for nothing in particular. Curious, you follow it to its source, raising an eyebrow at what you find. In the middle of an alley, two stone statues entangle a very naked, weakly struggling man. He's pinned between them, and a closer look shows their twin shafts stretching the poor guy open, dripping with what looks like multiple loads of fresh cum. His bare chest drips with streaks of his enjoyment, and though he's trying his best to escape, his cock still slaps wetly against his stomach, appearing perfectly content with his predicament. If it weren't for his incoherent pleading, you'd almost believe he put himself in this position. 'No more... Please.' The lost soul whimpers as you cross his field of view. He pushes at the horned head of the statue in front of him, but the way the thing's arms encircle his, he's stuck fast, only able to stir his insides with twin cocks and beg you for help, his eyes glazed over and spit trickling from the corner of his mouth.";
	say "     [italic type] Do you want to help him?[roman type][line break]";
	say "     ([link]Y[as]y[end link]) - Try to save the poor guy.";
	say "     ([link]N[as]n[end link]) - Walk away.";
	Linebreak;
	if Player consents:
		say "     Shaking away your desire to run off before you join the wretch, you inspect the stone fingers encircling his limbs, wincing at the reddened marks left by his struggles. Strangely, he seems none the worse for the wear despite his obviously 'fucked silly' appearance, though even your tugs can't free him from that horny stone embrace. Wiping the sweat from your brow, you circle the man's predicament, wondering aloud how he placed himself so precisely on both statues. Did something put him there? 'Not. Me.'  The captive groans out, his voice going up an octave. Slack and defeated, he regards you with a gaze that seems to stare right past you, but why do you get the impression that the statues have moved slightly despite him giving up? 'Well, well.' Causing you to jump with a sudden growl, a masculine voice comes next to your ear, accompanied by the soft rumble of stone on stone. One of the horned gargoyle faces contorts into a grin as its stone flesh slowly de-petrifies, becoming more like living marble than cold rock. Re-solidifying its grip on its captive, it stretches its body, its tail whipping from side to side as it grinds its still erect cock into his ruined hole. 'Looks like we've found another toy.'";
		say "     Surprised, you attempt to back away, only to stop as an iron grip grabs your wrist, trapping you within easy reach. The second gargoyle isn't far behind its playmate, and as sharp teeth show through a crooked grin, you can only guess that he's up to no good. His voice is less gravelly and sexually charged than his partner's, but he seems just as excited by your presence, dragging you in until you can smell the unmistakable scent of stone and cum wafting from their coupling. 'Two in one day? Maybe we won't have to keep using this little bitch.' Unceremoniously dumping their original victim to the ground, the pair set their sights on you, their erections looming as they drag you into a lewd embrace. Groping hands give you no chance to escape, and a glance down at the man you attempted to help shows he's passed out, his legs spread and a veritable river of seed staining the concrete from his overfucked colon. You doubt you'll receive any help from that poor bastard. Swallowing, you attempt to take in the situation as it unfolds. It seems like there are two options. Struggle, like the poor soul by your feet, or give in and hope they release you before you're as far gone as he is. Judging by the exhausted man's still throbbing erection, the second option will probably be great fun, even if they don't release you.";
		say "     [italic type] Do you want to fight back?[roman type][line break]";
		say "     ([link]Y[as]y[end link]) - Let them have their way with you.";
		say "     ([link]N[as]n[end link]) - Fuck these guys. Attempt to break their grip and leave.";
		Linebreak;
		if Player consents:
			say "[GargoyleStuckFuck]";
		else:
			say "[GargoyleStuckRape]";
	else:
		say "     Shaking your head, you murmur an apology to the bound man, hoping he'll forgive you for leaving him. The likelihood that you'll end up alongside him- or taking his place- is too high, and you would rather not spend days trapped where he is. The crackling of stone and renewed whimpers follow you as you turn to leave the alley, and a bit of guilt crosses your mind, but you're quick to push it down, mentally marking this spot on your map so you can avoid it in the future.";
	now Stuck is resolved;

to say GargoyleStuckFuck:
	if Player is female: [anal and vaginal]
		say "     Swallowing with either excitement or trepidation, you allow the horny gargoyles to draw you into their embrace, wriggling out of your gear without protest. Quietly, you mention that they don't have to be rough with you. You'll do as they like if they show you a good time. To show your sincerity, you sandwich yourself between both toned marble bodies, arching your hips and presenting your ass to the deeper-voiced monster as you look up at the other with your best 'fuck me' expression. 'Looks like we've got a willing participant.' Quick to take advantage of your position, the gargoyle behind you smears his already slick cock between your cheeks, testing your hole and swabbing it with cooled cum. It's surprisingly warm to the touch outside of the gooey first impression. 'You sure about this?' He says, seemingly confused by your willingness to give yourself up. 'You don't want to try to get away? Maybe force me to tackle you to the ground?' He seems almost excited by the prospect of a fight.";
		say "     'Pussy's pussy, man.' The much more agreeable, softer-voiced gargoyle before you tilts your chin up as he heaves you upward, drool dripping from his lips as he mashes them against yours, the sharp points of his teeth teasing your tongue while dragging a thick, draconic appendage through your mouth, exploring it like he owns you. His dick's just as excited as his partner's, though it dips between your lower lips rather than grinding against them, penetrating to your core in one solid thrust. 'I like it when they struggle.' Muffled against your ear, the gargoyle behind you grumbles but grabs your legs, forcing them apart and following the first one's lead, ceasing his teasing grind and forcing your ass open in one hard thrust. 'Fuck it. Clench for me.' He growls after that first taste, ramming away and pressing his musculature against your back. Trapped between rock-hard physiques, all you can do is moan into that greedy maw,  gagging on gargoyle tongue and whimpering as your innermost depths stretch. It feels far too good to want it to end, and your body is at the mercy of your monstrous lovers, all four limbs clutched by taloned stone fingers, so it's impossible to struggle even if you want to. Reduced to nothing but a tandem fleshlight, you rock your hips as best as you can, feeling your pussy drool down two sets of balls and add to the mess already coating those full orbs.";
		WaitLineBreak;
		say "     'No fair. Let me have some.' Squabbling for position, the gargoyle behind you rips your face away from the one in front with a rude jerk. You assume he means he wants to take over where the first left off, so you lean your head back expectantly, only to blink in confusion as he hungrily meets the first's mouth, kissing over your trembling body even as you feel him throb deep inside your clenching ass. Feeling a bit left out, you sulk, only to distract yourself with the heavy rhythm of the front gargoyle's lower stomach beating your poor clit to a pulp. Maybe it's not so bad. Nothing stops the passionate, machine-like pistoning your body endures. Even your orgasm only adds to the mess, dragging desperate whimpers from your mouth as you bury your face in a sweaty chest, still subjected to ramming thrusts that stir your juices into froth. Your captives ignore you, instead groping at each other, losing their grip on your body and holding you up while kissing so messily that you feel their spittle drip down onto your face.";
		say "     'Fuck.' That simple word is all that escapes that feral liplock. You're not sure which of the two says it, but they both stiffen, and their cocks flex in their respective holes, bathing your innermost depths in the evidence of their enjoyment. There's so much that you wonder whether you'll pop, but your stomach swells to take it all, stopping at a pregnant bulge. Panting and weakened, you hang there, held up by nothing but two softening cocks, as your bestial lovers sandwich you between their bodies. Their kiss doesn't cease until you feel the wet squelch of cocks flopping free, and as you fall to the ground below, a cursory glance shows the gargoyles engaged in what you can only describe as a loving embrace. You can't help feeling used as you watch the gruffer-voiced man grab at his partner's ass, but before you speak up, you realize that their little 'lovefest' has handed you a chance to escape! Gathering your things, you scurry off, noting that their original victim has already disappeared while you were fucked silly.";
		CreatureSexAftermath "Player" receives "PussyFuck" from "Gargoyle";
		CreatureSexAftermath "Player" receives "AssFuck" from "Gargoyle";
	else if Player is male: [Spitroast oral and anal]
		say "     Swallowing with either excitement or trepidation, you allow the horny gargoyles to draw you into their embrace, wriggling out of your gear without protest. Confronting them with your growing erection, you state that they don't have to be rough with you. As they draw you in, you arch your back and present your ass, shivering at the slightly cool touch of those living stone cocks and doing your best to catch the deeper-voiced gargoyle's member between your cheeks, eager to see how much steam's left in their engines. 'Looks like we've caught ourselves a slut.' Quick to take advantage of your offered assets, the gargoyle behind you smears his cockhead over your hole, thrusting eagerly and prodding inward. His member's so coated in the evidence of his last orgasm that it nearly slides right in, but it remains stubbornly outside of you, teasing your increasingly needy ass. It's surprisingly warm beneath the outer coating, and you can't help but wonder how it'll feel inside you. 'You sure you don't want to struggle? I like it when they try to get away.' Digging claws into your ass, he seems to dare you to attempt something, eager for a fight.";
		say "     'Man, it doesn't matter.' His companion chimes in as marble eyes stare down at you with a hint of approval. Leaning in, he looks like he's about to kiss you, but he stops just as his mouth opens, instead smearing a long tongue over your lips and leaving you with a brief taste of wet stone and animalistic spit. 'You take the other side. I'm feeling greedy.' He growls as he adjusts his stance, hanging your unresisting body between them and presenting you with his still drooling cock. You couldn't protest if you wanted to, letting out a muffled moan as your panting mouth overflows with hot, gooey gargoyle cock. You can't help but gag, your eyes watering and your lips coated in a heavy mixture of cum and drool, but the eager [']goyle doesn't seem to mind, sheathing himself in your throat and leaving you with nothing but a pair of (literally) chiseled abs to stare at.";
		WaitLineBreak;
		say "    Just as you start to get acclimated to the sheer size and pulse of the cock in your mouth, you feel the first gargoyle's cock split your backside open, delving deep in one claiming thrust that sends a brief shockwave of pain through your unresisting body. He's less courteous than his partner, slamming in deep with thrusts that rebound off of your ass and threaten to crush your poor prostate, but you can't help but enjoy every second, clenching for more. 'Fuck, man. Quit holding out on me.' The gargoyle destroying your ass grumbles as he adjusts his position, leaning over you and taking a firmer grip on your hips. 'You know I can't cum unless you-' Suddenly, his voice cuts off, taken over by a muffled moan and wet, sloppy sounds. Shuddering, you realize that the gargoyles above you are using you as nothing but a sex toy, making out while taking turns ravaging your holes. Somehow, that fact makes submitting to them even hotter, and you grab the gargoyle in front of you's ass, encouraging that flexing cock deep into your throat and swallowing every drop of pre that perfect cock drips into you. You might be a toy, but they'll never forget using you!";
		say "     'Fuck.' That word is all that breaks the sloppy liplock, heralding a flood of cum that threatens to drown you, squirting from your nose and filling your stomach until you feel it swelling like an overstuffed water balloon, wobbling in time with every thrust into your throat and ass. Your rear receives the same treatment, subjected to savage thrusts culminating in shot after shot of gooey gargoyle and fighting with the load in your stomach for space, leaving you pregnant-looking and sloshing with seed. Overwhelmed and overstuffed, you cum hard enough that you see stars, adding to the messy concrete below. After a moment's respite, while the gargoyles grind their manhoods into your holes, you're broken out of your cock-drunk stupor by a sudden tumble to the ground. In their passion, the gargoyles have forgotten you, pinning each other against the wall and making out with increasing fervor while their cocks duel. You feel slightly left out, but common sense kicks back in as you remember the man they trapped between them. You don't have time to become a statue's cumbucket! Gathering your things, you steal one last glance at the gargoyles before shouldering your pack and stumbling away, thankful for the cum drooling down your legs. You don't think you could walk long with all that added weight!";
		CreatureSexAftermath "Player" receives "AssFuck" from "Gargoyle";
		CreatureSexAftermath "Player" receives "OralCock" from "Gargoyle";

to say GargoyleStuckRape:
	if Player is female: [Rough vaginal.]
		say "     Tearing your hand away from that iron grip, you tell the gargoyles to fuck off, taking a step backward but unwittingly bumping into the wall behind you. You realize your mistake and attempt to turn tail and run, but the distraction gives clawed fingers time to grab onto your wrist again, yanking you back and pinning you against the brick wall. 'Fuck yeah. Love it when you run.' A snarling voice accompanied by hot breath brings your gaze back to one of the gargoyles, his eyes glinting with glee as his erection angrily throbs between you. He tears at your gear with wild abandon, tossing it to the side and smearing his tongue along your neck, letting you feel the sharp points of his teeth as his goal comes into view. Triumphant, he spreads your legs with both paws, ramming himself home and splitting your unprepared nethers with that gooey gargoyle cock. 'Not willing to share this time?' The gruffer gargoyle's companion smirks as he watches your rape, stroking himself idly while his other paw roams over his companion's ass, just out of view. 'Should I help you hurry it up so I can get a piece? Or do you want this one all to yourself?'";
		say "     'Don't fuckin' tease me, man.' Your rapist groans, his cock twitching against your innermost depths, its length allowing him to bruise your cervix with every thrust. 'You know I can't concentrate on pussy when you-' Groaning deep in his throat, he renews his thrusts, arching his back and lifting his tail. The second gargoyle disappeared from view, but the wet slurping noises you hear give you some idea of what he's doing. 'Gonna fuckin['] tear you up.' The gruffer gargoyle growls as teeth dig into your shoulder, every thrust growing more ragged and desperate, slapping your clit against the base of his cock and flinging your body around, scraping your bare back against the concrete. It's like trying to ride a bucking bronco that just won't let you let go, and the rhythmic slurp of his companion's tongue has only made him go faster, his balls slapping against your ass so hard you're sure they'll leave a mark. Unwanted but inescapable, your orgasm crests then explodes, dripping down those punishing wrecking balls and bathing your rapist's cock in sloppy femcum. Thankfully for your poor, overfucked body, your clenching pussy sets him off, bathing your innermost depths in so much cum that your stomach bulges with it, all but guaranteeing you'll be carrying a litter.";
		WaitLineBreak;
		say "     'Shit, dude. You earned your turn.' The gruff gargoyle dumps you to the ground as he speaks in a tired, satisfied tone, bringing you face to face with his partner as the other disengages from his task. 'I'm gonna take a breather.' Prodding you with one foot and spreading your legs to look at his partner's handiwork, the other gargoyle chuckles under his breath. 'Looks like you ruined it. I'll have to get creative if I want any tread on those tires.' Tilting your face upward and slipping his thumb into your mouth, the gargoyle inspects it, then shrugs, spreading his legs and stepping closer to guide his cock between your lips. Before you can protest, he plugs your throat with his still slick cock, giving you the distinct taste of salty seed and musky male, mixed with the unmistakable flavor of wet stone, like a pebble on your tongue. Any hope of a break fades as he grunts and surges forward, and all you can do is swallow as he jackhammers into your mouth, bashing your head against the brick behind you with overzealous thrusts.";
		say "     'Fuck, that's hot.' The first gargoyle joins his buddy, draping his arm across the other as his half-hard cock smears your cheek, suffocating you in cockflesh and rudely coating you in still-dripping seed. 'Maybe I shoulda taken their mouth.'  They share a strange moment as they debase you with twin cocks, and before long, you hear soft sounds from above. Are they making out? You don't have long to watch the display before your eyes tear up, your desperate attempts at keeping up with the heavy thrust of cock into your throat devolving into sloppy, wet gagging. Heavy balls bruise your chin, slapping against it hard enough to sting, and the first gargoyle's hardening cock smears your face with so much pre that you can barely see through the spiderwebs of desire.";
		WaitLineBreak;
		say "     You lose track of time, slurping weakly and trying to ignore the rhythmic slap of your skull against brick, but a veritable flood of cum brings you back to your senses, forcing you to scramble to stop yourself from drowning. Sweet air comes shortly after as the gargoyles melt into each other, making out and pulling away from your cum-covered face and abused body. Thankful for the respite, you crawl from the scene, holding your swollen, heavily filled stomach, and gather your gear, wincing as a dull headache starts. At least you avoided the same fate as the man you tried to save- though the ingrate seems to have run off while you distracted his captors. You're unsure whether you should curse or wish him the best, but you doubt you'll see him again.";
		CreatureSexAftermath "Player" receives "PussyFuck" from "Gargoyle";
		CreatureSexAftermath "Player" receives "OralCock" from "Gargoyle";
	else if Player is male: [Rough Anal.]
		say "     Tearing your hand away from that iron grip, you tell the gargoyles to fuck off, taking a step backward but unwittingly bumping into the wall behind you. You realize your mistake and attempt to turn tail and run, but the distraction gives clawed fingers time to grab onto your wrist again, yanking you back and pinning you against the brick wall.  'Where do you think you're going?' Eyes flashing with glee, the gruffer-voiced gargoyle leans in close, licking over your cheek and grinning as you recoil. He makes quick work of your gear, spreading your legs with one knee and lining himself up to tease your ass as one hand pins both of yours above your head. Dragging your naked body up the rough brick with his stony grip, he pushes inside with a triumphant growl, coring you out in one thrust.";
		say "     Squeaking out in protest, you try to struggle, but all your efforts are for naught, slapping your hardening cock against the gargoyle's sculpted abs and bringing attention to the warm heat spreading through your inner walls. He's so big that it brings tears to your eyes, but thankfully the coating of cum from his last victim eases the way, leaving you with nothing but the dull ache of stretching. 'Greedy, aren't you?' The gargoyle's partner slinks up, stroking himself to the display and leaning on his buddy's shoulder. 'Thought you'd want to share again. Guess I'll have to find someone else to play with.' His voice sounds teasing, but it's hard to concentrate while being power-fucked into the wall, and your view of him shakes as your eyes cross and blur with tears. 'Don't you fuckin' dare!' The gargoyle sheathed in your guts releases his clawed grip on your rear, dragging the second gargoyle into a kiss that would be romantic under any other circumstances. A whirlwind of motion brings your body away from the brick, but your respite from the sandpapery feel is short-lived as you feel the second gargoyle maneuver himself into place, stretching your already full hole.";
		WaitLineBreak;
		say "     'Damn, they're tighter than the last one.' Dripping with approval, the newcomer bites at his lover's lip, holding your legs up as he joins him in a pistoning rhythm that leaves your innards no time to adjust to the stretch. 'Bet you'll cum first.' He teases, completely ignoring your face as he sandwiches it between two rough chests to continue his hot and heavy makeout session. Trapped between the stony lovers, you grit your teeth and hold on, jostled like a man on a bucking bull. You can see the outline of their cocks in your stomach, and the bubble of pre around them is worrying. Any more, and you might pop! 'Dammit. Won't go first-' Attempting to refute those teasing words, the first gargoyle stills himself, only to moan out as the second speeds up, pounding your prostate into dust. The first gargoyle abandons the pretense of self-control, swelling your stomach into pseudo-pregnancy with heavy pumps of seed and clanking teeth, demanding another savage kiss.";
		say "     The second isn't far behind, emptying his balls into your ruined hole with such force that you can hear it sloshing. Unfortunately, they don't give you any time to adjust to your stomach's obscene size, instead tossing you to the ground like a forgotten cumrag as your rapists grow too hot and heavy to care, kissing each other and grinding still hard manhoods fresh from violating you. Sulking off, you hold your swollen stomach, grabbing your things and limping off before the gargoyles can regroup and force you into their embrace. Sparing one last glance at where they left their first victim, you shake your head. That coward ran off while they were busy with you! You don't know whether you should wish him the best or hope he gets caught again, but it's not your problem.";
		CreatureSexAftermath "Player" receives "AssFuck" from "Gargoyle";
		CreatureSexAftermath "Player" receives "AssFuck" from "Gargoyle";




Rock And A Hard Place ends here.