Version 2 of Lindsey by Sarokcat begins here.
[Version 2.3 - Lindsey WS scene ]

"Adds an NPC to Flexible Survival with a variety of responses and goals."


[ Hp of Lindsey                            ]
[   0 = not met                            ]
[   1 = talked                             ]

[ level of Lindsey                         ]
[ 4+ = player claimed                      ]

LindseyMPregDetected is a truth state that varies. LindseyMPregDetected is usually false.
lindseyws is a truth state that varies. lindseyws is usually false.

Section 1

Lindsey is a man.
The description of Lindsey is "There is a large wolftaur examining itself in the mirror. Its large, canine lower body stretches behind it, and its tail is wagging slightly as it obviously approves of what it sees. The upper body of the beast is covered in soft grey fur, and the face is definitely more lupine than human. The sharp claws on its human hands look capable of doing a great deal of damage. As the wolftaur shifts its body around and turns its yellow canine gaze to you, you are given a good look between its legs, the large canine organ hanging half-erect there leaving no doubt as to the beast's maleness.".
The conversation of Lindsey is { "Suck it!" }.
Lindsey is in Zoo Restrooms.

the scent of Lindsey is "Lindsey has a strong, masculine scent. It is powerful and arousing, making you long to submit to this beast[if level of Lindsey > 5]. As you should, for you are his bitch to use[end if].".

instead of conversing the Lindsey:
	if HP of Lindsey is 0:[first time you encounter the NPC text]
		say "     'Well, hey there,' the large beast says with a small smile tugging at his muzzle. 'Fancy seeing someone like you here in the zoo. Must just be my good luck, I guess,' the creature says with a lupine grin as he moves his gaze up and down your body. 'Oh, I suppose I haven't introduced myself yet. The name is Lindsey, a few friends and I decided to have some fun breaking into the zoo when all the crazy stuff started going down,' the male wolf with a female name says, a look of fond remembrance seeming to cross his lupine face as he thinks about the events. 'Let's just say it was a wonderful night to remember.'";
		say "     He pads towards you slowly, the musky smell in the room seeming to intensify as he draws close to you. 'I actually come by here occasionally just for the lovely memories. I had such a lovely time here that night with the wolftaur that used to be my boyfriend... He makes such a lovely bitch now,' the beast says with a grin. He reaches out and strokes your face with one of his clawed fingers, his strong masculine musk flooding your nose and making you feel slightly weak at the knees. 'Hmmm, I think you could make a fine little bitch too, all you need to do is ask, and I can help you with that...' the beast says with a lupine grin before lowering its face to yours to give your cheek a lick. 'Just say the word, and you could be enjoying yourself as much as I am,' Lindsey says in a teasing tone of voice as he saunters back over to the mirrors, his tail wagging happily for some reason as you stand there and try to recover your wits.";
		increase HP of Lindsey by 1;
	else if HP of Lindsey is 1:[Normal short messages the NPC will say each time you talk to them]
		say "[one of]'So are you ready to be my bitch?'[or]'My former boyfriend is back at the den. I could take you to meet her sometime, if you were a proper bitch...'[or]'I am so glad we came to the zoo that night.'[or]'The whole wolf thing was a bit scary at first, but now it is downright amazing.'[or]'It would be nice to have a pack, don't you think?'[or]'I think you would make a fine addition to my pack.'[or]'I wish I knew who caused whatever this is to happen, so I could thank them!'[or]'Have you seen those Tigertaurs out there? If they weren't so feline they could be fun to fuck...'[or]'I love having a cock. I never realized how much fun they were before.'[or]'Don't you want to pet my soft fur?' Lindsey says with a teasing look in his eyes.[or]The wolftaur just stares at you with his bright yellow eyes as you try to talk to him. Unable to meet that intent gaze, you quickly find yourself lowering your eyes. The wolftaur chuckles, his dominance established.[or]'Wolves have all the fun. I should know.'[or]'Wouldn't you feel better on all four paws?'[or]'It's good to be the alpha.'[at random]";


the fuckscene of Lindsey is "[sexwithLindsey]".

to say sexwithLindsey:
	[puts Wolftaur as lead monster in case of impregnation]
	repeat with y running from 1 to number of filled rows in table of random critters:
		choose row y in table of random critters;
		if name entry is "Wolftaur":
			now monster is y;
			break;
	if lastfuck of Lindsey - turns < 6:
		say "     'Sorry there my horny little bitch,' Lindsey says with a soft chuckle, 'but I have to check on my other bitch and make sure she is properly taken care of too, so I need to save a bit of energy for that. Why don't you come back in a little bit and I can make you even more into a proper little bitch, just like you want,' the masculine wolftaur says with lupine grin, the mingled musk of male wolftaur and your recent sex filling the air.";
	else if cunts of player is 0 and cocks of player is 0:
		say "     You are ill-equipped to play with the alluring and masculine wolftaur before you.";
	else if level of Lindsey > 3:
		if bodyname of player is "Wolftaur":
			if wslevel is 3 and a random chance of 1 in 4 succeeds:
				say "     'Well well, what have we here?' Lindsey says with an amused look on her canine muzzle as he examines your wolftaur form. 'Are you back for another lesson on your proper place? That's easy,' he growls before pouncing against your side, knocking you to the floor on your side. 'Your place is beneath me,' he states, striding confidently over you and grinds his crotch into your face. Confronted by the smell of the dominant wolf's erect manhood right in your face, you give a soft moan as the musky scent arouses you. You have your lips around that throbbing cock before you even know what you're doing.";
				say "     'That's right, my little bitch. Suck that cock and you'll get your treat,' he chuckles. You moan softly around his meat, your increasingly cloudy mind wanting nothing more than to suck the alpha wolf and get your tasty reward. The feel of it pulsing and throbbing in your mouth is wonderful. The taste of that musky rod and the copious precum leaking from it coats your tongue. As you keep sucking, Lindsey goes on to tell you what an eager cocksucker you are and how your place has always meant to be under him. And in your lust-addled have, the wolf's words ring true - [if cocks of player > 0]a weak male like yourself is nowhere near as strong and virile as[else]a wolf-bitch like yourself is meant to be mounted by[end if] an alpha stud like him.";
				WaitLineBreak;
				say "     Lindsey places a paw possessively on your ass, rubbing it as you continue to suck him off. You fondle the wolftaur's plump ballsack while licking and sucking all the harder on his rod. He pushes his hips down and forward hard, popping his thick knot past your lips before cumming with a loud howl. Blast after blast of gooey wolf semen shoots into your mouth and pours down your throat. As you struggle to swallow it all, he gives your rear another pat. 'Be a good bitch and take everything I give you,' he pants as he continues to cum. Wanting to please the virile stud, you try all the harder like a good and obedient slut.";
				say "     The wolftaur keeps his spent shaft in your mouth after he's finished, leaving you to lick and suck it clean. During that, a fresh flow starts up and pours down your throat as the wolf gives a soft sigh of relief. You've already obediently swallowed down several mouthfuls of the acrid liquid before realizing that it is his piss. ";
				if lindseyws is false:
					say "You cough and sputter, pulling your mouth away only to get a faceful of urine. Lindsey growls and continues to piss across your body. 'I told you to take everything I give you, bitch,' he snaps at you, digging his claws into your flank as a painful reminder to obey him in the future. Worn and humiliated, you flop down onto the wet floor, the alpha's mark soaking into your body.";
					infect "Wolftaur";
					infect "Wolftaur";
					now lindseyws is true;
					now lastfuck of Lindsey is turns;
					increase level of Lindsey by 2;
					decrease humanity of player by 3;
				else:
					say "You resist the momentary urge to pull away, reminding yourself to obey your alpha and take your reward. You continue to drink down his sharp tasting urine, feeling it warm your belly alongside the semen pooled in there. Only when he's spent does the satisfied wolf step back. Worn and satisfied, you flop down onto the messy floor, your confused mind trying for some time to recall what it is like to be more than just a submissive wolftaur.";
					infect "Wolftaur";
					infect "Wolftaur";
					now lastfuck of Lindsey is turns;
					increase level of Lindsey by 1;
					decrease humanity of player by 6;
			else if cocks of player > 0:
				if cunts of player > 0:
					say "     'Well well, what have we here?' Lindsey says with an amused look on his canine muzzle as he examines your own wolftaur-like body. 'A bit of a gender-confused wolftaur I see,' the strong male wolftaur says with a chuckle. 'I see your body can't decide if it should be male or female there or a bit of both. Maybe I can help you out there by showing you what it's like to be a proper little bitch,' he says in a low, teasing tone, his dominant words making your body shudder and grow hot with arousal. At the same time, his powerful alpha musk surrounds you, making your body respond instinctively, your pussy dampening while your rear legs shift further apart and your tail lifts up in anticipation. You only have a moment for your lust-fogged mind to realize the implications of your body's new stance before the strong male beast is climbing atop you, his forepaws gripping your canine sides while his arms reach around your humanoid torso to clutch you close against his own upper body. His canine chin comes to rest against your shoulder as a moan of pleasure slips through your lips.";
					say "     Your mind is still reeling even as your body responds eagerly to his soft touch and the weight of him on your back, instinctively bracing itself underneath him, your pussy beginning to burn with primal need while your cock feels limp and useless as you rub your body up against the strong alpha wolftaur. Your canine ass wiggles as it rubs up against his own firm, powerful hindquarters, teasing and begging for his dominant rod to fill you up. You can feel yourself panting in need as your own hands reach down to tangle with the more dominant male's as he strokes your chest and reaches up to tease and rub your soft nipples.";
					WaitLineBreak;
					say "     Lindsey wastes no time in accepting your body's encouragement, his cock beginning to rub against your canine pussy, the intense smell of his musk making you feel like a bitch in season as you whine underneath him. Then, with one powerful thrust, the male sheathes himself in you, and your mind shuts down as the pleasure of his hot thick canine meat pressing into your body fills you, instincts fully taking over as you yip and whine in pleasure underneath him while he pistons that amazing wolf cock in and out of your wet pussy. 'Feel that wonderful sensation of my cock inside you? Splitting you open and making you feel so good?' Lindsey whispers in your ears, your mind barely able to comprehend the meaning of his words as his knot presses up against your body, pushing in more and more with each powerful thrust as it seeks to lock the two of you together in a purely animal embrace.";
					say "     'Feel that cock inside you my little bitch, and let yourself realize that my cock is the only cock a proper bitch like you needs,' he growls into your ear as his hands roam your body. 'After all, what need does a submissive little bitch like you have for a [cock of player] cock. It just hangs there uselessly while the stronger males mount your slutty little bitch pussy, doesn't it? I can't even imagine what use a bitch like you would have for such a thing,' the male says as you groan in pleasure at his thick knot sliding into your body, your pussy clenching it tight as he ties with you.";
					WaitLineBreak;
					say "     You groan submissively underneath him as you realize he is right. Submissive little bitches like you don't need cocks, and yours isn't even erect despite how horny your body is; in fact, with his wonderful wolf cock inside you, you can't even imagine yourself in any male role anymore. The final realization of your body's total eager submission to the powerful male makes you groan and shudder with orgasm underneath your dominant mate, your body accepting its role as a bitch as your vagina grips his bestial cock tight. Feeling your orgasm underneath him, Lindsey howls in triumph as he gives into his own orgasm, his cock twitching as it paints your willing womb with your alpha's healthy seed.";
					say "     You pant in pleasure at the feel of your mate's seed filling your womb, even as he relaxes and begins to stroke you with his claw-tipped hands. 'You feel that lovely wolf sperm sinking into your body?' the alpha male says with a lupine grin as he relaxes on top of you. 'That is what being a proper bitch is about, letting your mate fill you full of his seed so you can carry his pups, not having a useless little cock of your own,' Lindsey says with a satisfied air of triumph as you pant and nod eagerly in agreement, your mind still awash in pleasure. Eventually his large knot shrinks to the point where he can pull himself out of you, and your handsome mate saunters over to the bathroom counter while you stand there in the middle of the room, his seed leaking down your hind legs as you vaguely try to recall what it is like to be more than just a wolftaur bitch.[impregchance]";
					infect "Wolftaur";
					infect "Wolftaur";
					now lastfuck of Lindsey is turns;
					increase level of Lindsey by 1;
					decrease humanity of player by 5;
				else if "MPreg" is listed in feats of player:
					if LindseyMPregDetected is false:
						say "     'Another male wolftaur?' Lindsay says with an amused look on his canine face as he examines your own wolftaur body. 'Well, since you obviously want to be my bitch so badly even as a male, who am I to say no?' the strong wolftaur says as he stalks around you in a predatory manner. His hands slowly stroke across your skin as his powerful dominant musk fills the small space and makes your head swim. 'And I can tell you're proper bitch deep down, like you should be, so I can still enjoy using you like one,' the dominant beast says, rubbing a paw over your lower belly in a way that fills it with a warm, aching need.";
						say "     Your head spins with lust as you try to grasp his meaning, only to feel his weight settle onto your back. You gasp as you brace your lower legs to support the larger wolf's weight while he positions himself on you, his powerful arms wrapping around your upper body as his cock begins to rub up against your own canine rear. You moan as your head begins to cloud over with pleasure, and he settles his canine chin on your shoulder, unable to even think about resistance with his powerful male body on top of your own. He licks your ear and whispers, 'That's right, I can smell that womb of yours, even over the stink of this place. I'm going to enjoy putting my pups in you.'";
						now LindseyMPregDetected is true;
					else:
						say "     'Still a male wolftaur?' Lindsay asks with an amused look on his canine face as he examines your own wolftaur body. 'But we both know you're just as capable of being my breeding bitch even as a male, so who am I to say no?' the strong wolftaur says as he stalks around you in a predatory manner. His hands slowly stroke across your skin as his powerful dominant musk fills the small space and makes your head swim. 'And I can tell that's just what you need--to be that proper bitch you are deep down,' the dominant beast says, rubbing a paw over your lower belly in a way that fills it with a warm, aching need. Your head spins with lust as you try to grasp his meaning, only to feel his weight settle onto your back. You gasp as you brace your lower legs to support the larger wolf's weight while he positions himself on you, his powerful arms wrapping around your upper body as his cock begins to rub up against your own canine rear. You moan as your head begins to cloud over with pleasure, and he settles his canine chin on your shoulder, unable to even think about resistance with his powerful male body on top of your own. He licks your ear and whispers, 'That's right, I've got just what a wolftaur womb needs, even for a male like you. I'm going to enjoy putting my pups in you.'";
						WaitLineBreak;
					say "     You find yourself panting in need as his canine member rubs up against your hole, the tip pushing in slightly as he shifts his hips in order to get the best position before thrusting himself into you in one swift, sure movement. You shudder underneath him as you feel his cock filling your ass, a strong wave of submissive pleasure coming over you as his knot rubs against the base of your tailhole. Lindsey groans in pleasure as he whispers into your ear, 'Just let go of all that male aggression.' He traces his tongue along your ear as he begins to move his hips, driving his amazing cock into you further with each thrust. 'We both know you're meant to be a breeder, so just let it all go and embrace those submissive, bitch-like tendencies we both know you love so much,' the male pants into your ears. His words send a rush of heated need into your hidden womb, filling your lust-fogged mind with an increasing sense of their rightness. 'Just submit and let your alpha take care of breeding you from now on...' he says as he grunts, his knot pressing up against your rear as it seeks to lock the two of you together.";
					WaitLineBreak;
					say "     'Feel that big large wolf knot as it rubs up against you,' he growls into your ear as his hands roam your body. 'Soon you will have that knot inside you, locking me inside you and ensuring that none of my seed escapes you, my little breeding bitch,' the male says confidently as he licks and nibbles at your ear. You groan in pleasure as his thick knot finally slides fully into your body a few hard thrusts later. Your ass clenches that meaty bulb tight after it's popped into you, ensuring a good, solid tie. You groan submissively underneath him as you realize he is right; you are just a submissive little breeding he-bitch for your big strong alpha. In fact, with his wonderful wolf cock inside, you can't even imagine how you could have ever wanted to be anything but the slutty bitch of this strong, powerful male. The final realization of your body's total eager submission to the powerful male makes you groan and shudder with orgasm underneath your dominant mate, your body accepting its role as a bitch as your anus squeezes his bestial cock needfully. Feeling your orgasm underneath him, Lindsey howls in triumph as he gives into his own orgasm, his cock twitching as it paints your willing womb with your alpha's healthy seed.";
					WaitLineBreak;
					say "     You pant in pleasure at the feel of your mate's seed filling your womb, even as he relaxes and begins to stroke you with his claw-tipped hands. 'You feel that lovely wolf sperm sinking into your body?' the alpha male says with a lupine grin as he relaxes on top of you. 'Just give into what you know you want, become a submissive little bitch for me to use and fill full of my seed whenever I want. Doesn't your body feel so good, nice and full of my lovely little pup batter? Such strong and virile alpha cum that it'll put pups even in your male belly. Just imagine how much better you would feel with your submissive he-bitch belly round and swollen with a litter of puppies instead of just my seed,' Lindsey says with a satisfied air of triumph. You pant and nod eagerly in agreement, your hands rubbing your sides as you imagine the feel of your alpha's pups growing in your body, your mind still completely awash in pleasure. Eventually his large knot shrinks to the point where he can pull himself out of you, and your handsome mate saunters over to the bathroom counter while you stand there in the middle of the room, his seed leaking down your hind legs as you vaguely try to recall what it is like to be more than just a wolftaur bitch.[mimpregchance]";
					infect "Wolftaur";
					infect "Wolftaur";
					now lastfuck of Lindsey is turns;
					increase level of Lindsey by 1;
					decrease humanity of player by 5;
				else:
					say "     'Another male wolftaur?' Lindsey says with an amused look on his canine face as he examines your own wolftaur body. 'Well, since you obviously want to be my bitch so badly even as a male, who am I to say no?' the strong wolftaur says as he stalks around you in a predatory manner. His hands slowly stroke your [skin of player] skin as his powerful dominant musk fills the small space and makes your head swim. 'Even though you aren't a proper bitch like you should be, I can still enjoy using you like one,' the dominant beast says, your head spinning with lust as you try to grasp his meaning, only to feel his weight settle onto your back. You gasp as you brace your lower legs to support the larger wolf's weight as he positions himself on you, his powerful arms wrapping around your upper body as his cock begins to rub up against your own canine rear. You moan as your head begins to cloud over with pleasure, and he settles his canine chin on your shoulder, unable to even think about resistance with his powerful male body on top of your own.";
					say "     You find yourself panting in need as his canine member rubs up against your hole, the tip pushing in slightly as he shifts his hips to get the best position before thrusting himself into you in one swift, sure movement. You shudder underneath him as you feel his cock filling your ass, a strong wave of submissive pleasure coming over you as his knot rubs against the base of your tail hole. Lindsey groans in pleasure as he whispers into your ear, 'Just let go of all that male aggression.' He traces his tongue along your ear as he begins to move his hips, driving his amazing cock into you further with each thrust. 'You can't handle being a dominant male wolf now, and you know it, so just let it all go and embrace those submissive, bitch-like tendencies we both know you love so much,' the male pants into your ears, his words filling your lust-fogged mind with an increasing sense of their rightness. 'Just submit and let your alpha take care of you now...' he says as he grunts, his knot pressing up against your rear as it seeks to lock the two of you together.";
					WaitLineBreak;
					say "     You aren't sure what it is about the situation: the strong male on your back with his cock in your ass as he uses you like a bitch, his soft words of encouragement, or the feel of his powerful male arms wrapped around you as he presses himself up against your body, but you find yourself feeling even more submissive and weaker than ever, happy to moan under the stronger, more dominant male as his knot enters your body and seals you together. Groaning underneath the more powerful wolf, you find yourself realizing that inside you are nothing more than his slutty canine bitch, even though your outside is male. The realization makes your body shudder in pleasure underneath your alpha male as you feel your old aggressive tendencies slipping away, happy to embrace your bestial side and let your nice strong alpha take care of you.";
					say "     The feel of his seed spurting into your ass makes you howl in pleasure, your voice joining your alpha's as you both shudder in orgasm as he fills your insides up with his sperm, marking you forever as his submissive pack member. The two of you stay locked together for a time, his seed churning inside your bowels as his knot slowly begins to shrink, your alpha stroking and petting you with his hands and paws even as he tells you what a good bitch you will be for his pack. Eventually, Lindsey's knot has shrunk enough he can pull it out of you, making you shudder at the sudden feeling of emptiness as he stalks happily over to the bathroom sinks, leaving you to slowly come to terms with all that has happened.[mimpregchance]";
					infect "Wolftaur";
					infect "Wolftaur";
					now lastfuck of Lindsey is turns;
					increase level of Lindsey by 1;
					decrease humanity of player by 5;
			else:
				say "     'Well well, what have we here?' Lindsey says with an amused look on his canine muzzle as he examines your own wolftaur-like body. 'A nice proper little wolftaur bitch for me to enjoy,' the strong male wolftaur says with a chuckle, 'and obviously ready and eager for a real wolftaur to take you into his pack and show you just what life is like for needy little wolftaur bitches,' he says in a low, teasing tone, his dominant words making your body shudder and grow hot with arousal, even as his powerful alpha musk surrounds you, making your body respond instinctively, your pussy dampening while your rear legs shift further apart and your tail lifts up in anticipation. You only have a moment for your lust-fogged mind to realize the implications of your body's new stance before the strong male beast is climbing atop you, his forepaws gripping your canine sides even as his arms reach around your humanoid torso to clutch you close against his own upper body, his canine chin coming to rest against your shoulder as a moan of pleasure slips through your lips.";
				WaitLineBreak;
				say "     Your mind is still reeling even as your body responds eagerly to his soft touch and the weight of him on your back, instinctively bracing itself underneath him, your pussy beginning to burn with primal need, strong feelings of submissive bliss washing through your mind as your canine ass rubs up against his own strong, powerful hindquarters in need, teasing and begging for his dominant rod to fill you up. You can feel yourself panting in bestial need as your own hands reach down to tangle with the more dominant male's as he strokes your chest and reaches up to tease and rub your soft nipples. Lindsey wastes no time in accepting your body's encouragement and obvious submission, as his cock begins to rub against your canine pussy, the intense smell of his musk making you feel like nothing more than a bitch in season as you whine underneath him.";
				say "     Then, with one powerful thrust, the male sheathes himself in you, and your mind shuts down as the pleasure of his hot thick canine meat pressing into your body fills you, instincts fully taking over as you yip and whine in pleasure underneath him as he pistons that amazing wolf cock in and out of your wet pussy. 'Feel that wonderful sensation of my cock inside you? Splitting you open and making you feel so good?' Lindsey whispers in your ears, your mind barely able to comprehend the meaning of his words as his knot presses up against your body, pushing in more and more with each powerful thrust as it seeks to lock the two of you together in a purely animal embrace.";
				WaitLineBreak;
				say "     'Feel that big large wolf knot as it rubs up against you,?' he growls into your ear as his hands roam your body. 'Soon you will have that knot inside you, locking me inside you and ensuring that none of my seed escapes my little breeding bitch,' the male says as he licks and nibbles at your ear even as you groan in pleasure at his thick knot finally sliding fully into your body, your pussy clenching it tightly as he ties with you. You groan submissively underneath him as you realize he is right, you are just a submissive little breeding bitch for your big strong alpha, in fact with his wonderful wolf cock inside you can't even imagine how you could have ever wanted to be anything but the slutty bitch of this strong, powerful male. The final realization of your body's total eager submission to the powerful male makes you groan and shudder with orgasm underneath your dominant mate, your body accepting its role as a bitch as your vagina grips his bestial cock tight. Feeling your orgasm underneath him, Lindsey howls in triumph as he gives into his own orgasm, his cock twitching as it paints your willing womb with your alpha's healthy seed. You pant in pleasure at the feel of your mate's seed filling your womb";
				WaitLineBreak;
				say "     As he relaxes and begins to stroke you with his claw-tipped hands. 'You feel that lovely wolf sperm sinking into your body?' the alpha male says with a lupine grin as he relaxes on top of you. 'Just give into what you know you want, become a submissive little bitch for me to use and fill full of my seed whenever I want. Doesn't your body feel so good, nice and full of my lovely little pup batter? Just imagine how much better you would feel with your submissive little bitches belly round and swollen with a litter of puppies instead of just my seed,' Lindsey says with a satisfied air of triumph as you pant and nod eagerly in agreement, your hands rubbing your sides eagerly as you imagine the feel of your alpha's pups growing in your body, your mind still completely awash in pleasure. Eventually his large knot shrinks to the point where he can pull himself out of you, and your handsome mate saunters over to the bathroom counter while you stand there in the middle of the room, his seed leaking down your hind legs as you vaguely try to recall what it is like to be more than just a wolftaur bitch.[impregchance]";
				infect "Wolftaur";
				infect "Wolftaur";
				now lastfuck of Lindsey is turns;
				increase level of Lindsey by 1;
				decrease humanity of player by 5;
		else if bodyname of player is listed in infections of taurlist:
			if cunts of player > 0 and cocks of player > 0:
				say "     'Well, look at you?' Lindsey says with an amused look on his canine muzzle as he examines your [bodytype of player] body. 'A bit of a gender-confused taur. But just as needy, I can tell,' he adds with a chuckle while running a paw across your rear. 'I see your body can't decide if it should be male or female there or a bit of both. Maybe I can help you out there by showing you what it's like to be a proper little bitch,' he says in a low, teasing tone. His dominant words make your body shudder and grow hot with arousal, even as his powerful alpha musk surrounds you. Your body starts to respond instinctively, your pussy dampening while your rear legs shift further apart in anticipation. You only have a moment for your lust-fogged mind to realize the implications of your body's new stance before the strong male beast is climbing atop you. His forepaws grip your tauric sides even as his arms reach around your humanoid torso to clutch you close against his own upper body, his canine chin coming to rest against your shoulder as a moan of pleasure slips through your lips.";
				say "     Your mind is still reeling even as your body responds eagerly to his soft touch and the weight of him on your back, instinctively bracing itself underneath him. Your pussy begins to burn with primal need as you rub your body up against the strong alpha wolftaur, your hindquarters wiggling as it rubs up against his erection, teasing and begging for his dominant rod to fill you up. You can feel yourself panting in need as your own hands reach down to tangle with the more dominant male's as he strokes your chest and reaches up to tease and rub your soft nipples. Lindsey wastes no time in accepting your body's encouragement as his cock begins to rub against your dripping pussy, the intense smell of his musk making you need the powerful taur inside you all the more.";
				WaitLineBreak;
				say "     With one powerful thrust, the male sheathes himself in you, and your mind shuts down as the pleasure of his hot thick canine meat pressing into your body fills you, instincts fully taking over as you yip and whine in pleasure underneath him as he pistons that amazing wolf cock in and out of your wet pussy. 'Doesn't that big, lupine cock feel wonderful inside you? Splitting you open and making you feel so good?' Lindsey whispers in your ears, your mind barely able to comprehend the meaning of his words as his knot presses up against your body. It pushes in more and more with each powerful thrust as it seeks to lock the two of you together in a purely animal embrace.";
				say "     'Feel that cock inside you. Doesn't it just make you want to be my little bitch, and let yourself realize that my cock is the only cock a proper bitch like you needs,' he growls into your ear as his hands roam your body. 'After all, what need does a submissive little bitch like you have for a [cock of player] cock. All the cock you really need is mine stuffed hard and deep into you, isn't that right?' he rumbles in your ear, thrusting all the harder, making you moan and nod in response, loving the feel of the wolftaur's throbbing meat buried deep inside you.";
				WaitLineBreak;
				say "     You groan in pleasure at his thick knot slides into your body, your pussy clenching it tight as he ties with you. You groan submissively underneath him as you realize he is right, submissive little bitches like you don't need cocks. Yours isn't even erect despite how horny your body is. In fact, with his wonderful wolf cock inside, you can't even imagine yourself in any male role anymore. The final realization of your body's total eager submission to the powerful male makes you groan and shudder with orgasm underneath your dominant mate, your body eager to accept its new role as the wolftaur's bitch as your vagina grips his bestial cock tight. Feeling your orgasm underneath him, Lindsey howls in triumph as he gives into his own orgasm, his cock twitching as it paints your willing womb with his healthy seed.";
				say "     You pant in pleasure at the feel of your lover's seed filling your womb, even as he relaxes and begins to stroke you with his claw-tipped hands. 'You feel that lovely wolf sperm sinking into your body?' the alpha male says with a lupine grin as he relaxes on top of you. 'That is what being a proper bitch is about and what you'll have to look forward to soon,' he says, reaching back to stroke across your flank, now a little more rounded with her hot load and large cock filling you. Lindsey grins and nibbles along your neck as you pant and nod eagerly in agreement, your mind still awash in pleasure. Eventually his large knot shrinks to the point where he can pull himself out of you, and the handsome wolftaur saunters over to the bathroom counter while you stand there in the middle of the room, his seed leaking down your hind legs as you imagine what it'll be like to be a wolftaur bitch.[impregchance]";
				infect "Wolftaur";
				infect "Wolftaur";
				now lastfuck of Lindsey is turns;
				increase level of Lindsey by 1;
				decrease humanity of player by 3;
			else if cunts of player > 0:
				say "     'Well, look at you?' Lindsey says with an amused look on his canine muzzle as he examines your [bodytype of player] body. 'You may not be a wolftaur yet, but you certainly look like a horny, needy taur nonetheless. I can tell,' he adds with a chuckle while running a paw across your rear. 'Ready and eager to have a strong, male taur atop you and teach you what it's like to be a proper bitch,' he says in a low, teasing tone. His dominant words make your body shudder and grow hot with arousal, even as his powerful alpha musk surrounds you. Your body starts to respond instinctively, your pussy dampening while your rear legs shift further apart in anticipation. You only have a moment for your lust-fogged mind to realize the implications of your body's new stance before the strong male beast is climbing atop you. His forepaws grip your tauric sides even as his arms reach around your humanoid torso to clutch you close against his own upper body, his canine chin coming to rest against your shoulder as a moan of pleasure slips through your lips.";
				say "     Your mind is still reeling even as your body responds eagerly to his soft touch and the weight of him on your back, instinctively bracing itself underneath him. Your pussy begins to burn with primal need as you rub your body up against the strong alpha wolftaur, your hindquarters wiggling as it rubs up against his erection, teasing and begging for his dominant rod to fill you up. You can feel yourself panting in need as your own hands reach down to tangle with the more dominant male's as he strokes your chest and reaches up to tease and rub your soft nipples. Lindsey wastes no time in accepting your body's encouragement as his cock begins to rub against your dripping pussy, the intense smell of his musk making you need the powerful taur inside you all the more.";
				WaitLineBreak;
				say "     With one powerful thrust, the male sheathes himself in you, and your mind shuts down as the pleasure of his hot thick canine meat pressing into your body fills you, instincts fully taking over as you yip and whine in pleasure underneath him as he pistons that amazing wolf cock in and out of your wet pussy. 'Doesn't that big, lupine cock feel wonderful inside you? Splitting you open and making you feel so good?' Lindsey whispers in your ears, your mind barely able to comprehend the meaning of his words as his knot presses up against your body. It pushes in more and more with each powerful thrust as it seeks to lock the two of you together in a purely animal embrace.";
				say "     'Feel that cock inside you. Doesn't it just make you want to be my little bitch, and let yourself realize that my cock is the only cock a proper bitch like you needs?' he growls into your ear as his hands roam your body. 'Soon you will have that knot inside you, locking me inside you and ensuring you'll be knocked up like my little breeding bitch. Doesn't that sound divine, you needy slut?' he rumbles in your ear, thrusting all the harder, making you moan and nod in response, loving the feel of the wolftaur's throbbing meat buried deep inside you. You groan in pleasure at his thick knot slides into your body, your pussy clenching it tight as he ties with you.";
				WaitLineBreak;
				say "     You groan submissively underneath him as you realize he is right, you're meant to be a submissive little breeding bitch for your big, strong alpha. In fact, with his wonderful wolf cock inside you, you can't even imagine how you could have ever wanted to be anything but the slutty bitch of this strong, powerful male. Feeling your orgasm underneath him, Lindsey howls in triumph as he gives into his own orgasm, his cock twitching as it paints your willing womb with his healthy seed.";
				say "     You pant in pleasure at the feel of your lover's seed filling your womb, even as he relaxes and begins to stroke you with his claw-tipped hands. 'You feel that lovely wolf sperm sinking into your body?' the alpha male says with a lupine grin as he relaxes on top of you. 'That is what being a proper bitch is about and what you'll have to look forward to soon,' he says, reaching back to stroke across your flank, now a little more rounded with her hot load and large cock filling you. Lindsey grins and nibbles along your neck as you pant and nod eagerly in agreement, your mind still awash in pleasure. Eventually his large knot shrinks to the point where he can pull himself out of you, and the handsome wolftaur saunters over to the bathroom counter while you stand there in the middle of the room, his seed leaking down your hind legs as you imagine what it'll be like to be a wolftaur bitch.[impregchance]";
				infect "Wolftaur";
				infect "Wolftaur";
				now lastfuck of Lindsey is turns;
				increase level of Lindsey by 1;
				decrease humanity of player by 3;
			else if "MPreg" is listed in feats of player:
				if LindseyMPregDetected is false:
					say "     'Another male taur?' Lindsey says with an amused look on his canine face, as he examines your own [bodydesc of player] body. 'And I can tell you're proper bitch deep-down, like you should be, so I can still enjoy using you like one,' the dominant beast says, rubbing a paw over your lower belly in a way that fills it with a warm, aching need. Your head spins with lust as you try to grasp his meaning, only to feel his weight settle onto your back. You gasp as you brace your lower legs to support the larger wolf's weight as he positions himself on you, his powerful arms wrapping around your upper body as his cock begins to rub up against your hindquarters. You moan as your head begins to cloud over with pleasure, and he settles his canine chin on your shoulder, unable to even think about resistance with his powerful male body on top of your own. He licks your ear and whispers 'That's right, I can smell that womb of yours, even over the stink of this place. I'm going to enjoy putting my pups in you.'";
					now LindseyMPregDetected is true;
				else:
					say "     'Well, look at you?' Lindsey says with an amused look on his canine muzzle as he examines your [bodytype of player] body. 'You may not be a wolftaur yet, but we both know you're certainly capable of being my breeding bitch even as a male taur,' the strong wolftaur says as he stalks around you in a predatory manner. His hands slowly stroke across your skin as his powerful dominant musk fills the small space and makes your head swim. 'And I can tell that's just what you need--to be that proper bitch you are deep-down,' the dominant beast says, rubbing a paw over your lower belly in a way that fills it with a warm, aching need.";
					say "     Your head spins with lust as you try to grasp his meaning, only to feel his weight settle onto your back. You gasp as you brace your lower legs to support the larger wolf's weight as he positions himself on you, his powerful arms wrapping around your upper body as his cock begins to rub up against your own canine rear. You moan as your head begins to cloud over with pleasure, and he settles his canine chin on your shoulder, unable to even think about resistance with his powerful male body on top of your own. He licks your ear and whispers 'That's right, I've got just what a bitch's womb needs, even for a male like you. I'm going to enjoy making that taur belly of yours round with my pups.'";
					WaitLineBreak;
					say "     You find yourself panting in need as his canine member rubs up against your hole, the tip pushing in slightly as he shifts his hips in order to get the best position before thrusting himself into you in one swift, sure movement. You shudder underneath him as you feel his cock filling your ass, a strong wave of submissive pleasure coming over you as his knot rubs against the base of your tailhole. Lindsey groans in pleasure as he whispers into your ear, 'Just let go of all that male aggression.' He traces his tongue along your ear as he begins to move his hips, driving his amazing cock into you further with each thrust. 'You can't compare to a sexy and strong wolf like me and you know it. There's no point in resisting it, we both know you're meant to be a breeder. So just let it all go and embrace those submissive, bitch-like tendencies we both know you love so much,' the male pants into your ears. His words fills your lust-fogged mind with an increasing sense of their rightness even as they send a rush of heated need into your hidden womb. 'Just submit and let the big wolf take care of breeding you from now on...' he says as he grunts, his knot pressing up against your rear as it seeks to lock the two of you together.";
					WaitLineBreak;
					say "     'Feel that big large wolf knot as it rubs up against you,' he growls into your ear as his hands roam your body. 'Doesn't it just make you want to be my little bitch, and let yourself realize that my cock is the only cock a proper bitch like you needs?' he growls into your ear as his hands roam your body. 'Soon you will have that knot inside you, locking me inside you and ensuring you'll be knocked up like my little breeding bitch. Doesn't that sound divine, you needy slut?' he rumbles in your ear, thrusting all the harder, making you moan and nod in response, loving the feel of the wolftaur's throbbing meat buried deep inside you.";
					say "     You groan in pleasure as his thick knot finally sliding fully into your [bodydesc of player] body a few hard thrusts later. Your ass clenches that meaty bulb tight after it's popped into you, ensuring a good, solid tie. You groan submissively underneath him as you realize he is right; you're meant to be a submissive breeding he-bitch for your big, strong alpha. In fact, with his wonderful wolf cock inside you, you can't even imagine how you could have ever wanted to be anything but the slutty bitch of this strong, powerful male. The final realization of your body's total eager submission to the powerful male makes you groan and shudder with orgasm underneath your dominant mate, your body accepting its role as a bitch as your anus squeezes his bestial cock needfully. Feeling your orgasm underneath him, Lindsey howls in triumph as he gives into his own orgasm, his cock twitching as it paints your willing womb with your alpha's healthy seed.";
					WaitLineBreak;
					say "     'Feel that wolf cock inside you. Doesn't it just make you want to be my little bitch, and let yourself realize that my cock is the only cock a proper bitch like you needs,' he growls into your ear as his hands roam your body. 'Soon you will have that knot inside you, locking me inside you and ensuring you'll be knocked up like my little breeding bitch. Doesn't that sound divine, you needy slut?' he rumbles in your ear, thrusting all the harder, making you moan and nod in response, loving the feel of the wolftaur's throbbing meat buried deep inside you. You groan in pleasure at his thick knot slides into your body, your pussy clenching it tight as he ties with you.";
					say "     You groan submissively underneath him as you realize he is right, you're meant to be a submissive little breeding bitch for your big, strong alpha. In fact, with his wonderful wolf cock inside you, you can't even imagine how you could have ever wanted to be anything but the slutty bitch of this strong, powerful male. Feeling your orgasm underneath him, Lindsey howls in triumph as he gives into his own orgasm, his cock twitching as it paints your willing womb with his healthy seed.";
					WaitLineBreak;
					say "     You pant in pleasure at the feel of your lover's seed filling your womb, even as he relaxes and begins to stroke you with his claw-tipped hands. 'You feel that lovely wolf sperm sinking into your body?' the alpha male says with a lupine grin as he relaxes on top of you. 'That is what being a proper bitch is about and what you'll have to look forward to soon,' he says, reaching back to stroke across your flank, now a little more rounded with her hot load and large cock filling you. 'Even as the needy he-bitch your body wants to be,' he adds. Lindsey grins and nibbles along your neck as you pant and nod eagerly in agreement, your mind still awash in pleasure. Eventually his large knot shrinks to the point where he can pull himself out of you, and the handsome wolftaur saunters over to the bathroom counter while you stand there in the middle of the room, his seed leaking down your hind legs as you imagine what it'll be like to be a wolftaur bitch.[mimpregchance]";
					infect "Wolftaur";
					infect "Wolftaur";
					now lastfuck of Lindsey is turns;
					increase level of Lindsey by 1;
					decrease humanity of player by 3;
			else:
				say "     'Another male taur?' Lindsey says with an amused look on his canine face, as he examines your own [bodydesc of player] body. 'Well, since you obviously know you can't compare with a big, strong wolf like myself, you must want to be my bitch so badly even as a male,' the strong wolftaur says as he stalks around you in a predatory manner. His hands slowly stroke your sides as his powerful dominant musk fills the small space and makes your head swim. 'Even though you aren't a proper bitch, like you should be, I can still enjoy using you like one,' the dominant beast says, your head spinning with lust as you try to grasp his meaning, only to feel his weight settle onto your back. You gasp as you brace your lower legs to support the large wolf's weight as he positions himself on you, his powerful arms wrapping around your upper body as his cock begins to rub up against your hindquarters. You moan as your head begins to cloud over with pleasure, and he settles his canine chin on your shoulder, unable to even think about resistance with his powerful male body on top of your own.";
				say "     You find yourself panting in need as his canine member rubs up against your hole, the tip pushing in slightly as he shifts his hips in order to get the best position before thrusting himself into you in one swift, sure movement. You shudder underneath him as you feel his cock filling your ass, a strong wave of submissive pleasure coming over you as his knot rubs against the base of your tailhole. Lindsey groans in pleasure as he whispers into your ear, 'Just let go of all that male aggression.' He traces his tongue along your ear as he begins to move his hips, driving his amazing cock into you further with each thrust. 'You can't compare to a sexy and strong wolf like me and you know it. There's no point in resisting it, so just let it all go and embrace those submissive, bitch-like tendencies we both know you love so much,' the male pants into your ears, his words filling your lust-fogged mind with an increasing sense of their rightness. 'Just submit and let the big wolf take care of you now,' he says as he grunts, his knot pressing up against your rear as it seeks to lock the two of you together.";
				WaitLineBreak;
				say "     You aren't sure what it is about the situation, but the overload of sensation from being mounted by the virile male while his heavy musk suffuses your senses leaves you moaning and panting beneath him. Between having the strong, male wolf on your back, with his cock in your ass as he uses you like a bitch, listening to his soft words of encouragement and the feel of his powerful male arms wrapped around you as he presses himself up against your body, you can't help but feel like his inferior and want to be used as such. You find yourself feeling even more submissive and weaker than ever, happy to moan under the more dominant wolf as his knot enters your body and seals you together. Groaning underneath the more powerful wolf, you find yourself realizing that you want nothing more than his slutty canine bitch, even though your outside is male.";
				say "     The realization makes your body shudder in pleasure underneath your alpha male as you feel your old aggressive tendencies slipping away, happy to embrace your bestial side and let the strong, virile wolf take you as he pleases. The feel of his seed spurting into your ass makes you cry out in pleasure, your voice joining your alphas as you both shudder in orgasm as he fills your insides up with his sperm, marking you forever as his submissive plaything. The two of you stay locked together for a time, his seed churning inside your bowels as his knot slowly begins to shrink, the wolftaur stroking and petting you with his hands and paws even as he tells you what a good bitch you will be for his pack. Eventually Lindsey's knot has shrunk enough he can pull it out of you, making you shudder at the sudden feeling of emptiness as he stalks happily over to the bathroom sinks, leaving you to slowly come to terms with all that has happened.[mimpregchance]";
				infect "Wolftaur";
				infect "Wolftaur";
				now lastfuck of Lindsey is turns;
				increase level of Lindsey by 1;
				decrease humanity of player by 3;
		else if cunts of player > 0:
			say "     'Well well, look what I have here,' Lindsey says with amusement as you approach the male wolftaur. 'It looks like my newest bitch couldn't stay away from her alpha, now could she?' the male taur says in a teasing tone of voice as he begins to slowly stalk towards you, his powerful male musk filling the enclosed bathroom with its strongly arousing scent. 'I knew you had the making of a proper bitch inside you,' the male says as he slowly moves around your body, his furred flank rubbing up against your side and making you moan in pleasure. 'Such a shame the outside doesn't match the inside though...' he says mournfully as his clawed hands pet and stroke your head, the combination of his musk, his soft touches, and his strangely soothing dominant tone, cause your body to respond to him even as your mind fogs over with lust. 'Aren't you lucky that your alpha is here to help you out with that? To help show you how to be a proper bitch inside and out?' Lindsey says teasingly, his lupine muzzle pulling back in a grin as you nod in agreement with the dominant alpha before his words can even fully register.";
			say "     'Well to start with, proper bitches walk around on all four paws,' the Wolftaur says in amusement as he pushes your upper body down to the ground, and you find yourself dropping down to all fours on the dirty cum stained floor eagerly. The situation seems wrong for a minute, as you breathe in his musky scent as you crawl around on the floor, but somehow being on all fours like this in the presence of such a wonderful alpha male is making your body feel even hornier than ever, your pussy feeling warm and empty as it aches for a thick canine cock to fill it. 'Now that's better,' you can hear the alpha male say with amusement as he watches you move around on the floor. 'Now that we have you positioned and acting like a proper bitch, it's time for your reward,' he says, his words making you shudder in anticipation even as his furred side rubs up against your skin.";
			WaitLineBreak;
			say "     'For your reward, I think you need a hefty helping of fertile wolf seed, don't you?' Lindsey says, even as he lifts his paw up over your body, and crawls on top of you. 'A nice helping of your alpha's seed should help make you into a proper little wolftaur bitch for me just like we both want,' he says, as you find yourself whimpering in need underneath him, his front paws just in front of your shoulders, as his thick cock rubs up against your upturned rear. The feeling of the tip of his cock rubbing up against your swollen lips makes you pant desperately as you try to grind your hips back against his strong canine hindquarters, your mouth hanging open as his masculine musk fills your mind with lustful thoughts of being a proper bitch for your alpha. You groan in submissive need as he shifts his weight forward slightly, and pushes his thick rod into you in one swift stroke, his knot pressed up against your body seeking to lock the two of you together, even as he begins to thrust his cock in and out of you with bestial abandon.[line break]";
			say "     You can feel your body relax underneath him, as you lower your face even closer to the ground, giving in by instinct to the strong dominant male, your lips stretching wide to allow his knot to lock the two of you together. He yips in pleasure above you, the sound filling your musk fogged mind with happy pleasure at the evidence of your alpha's approval, his large bulb swelling within your body and making you feel even more like a proper submissive bitch with every minute. With his knot locked into you, he begins to make even faster short hard thrusts into your body, his pointed canine shaft rubbing within you and making you moan in pleasure as every thrust brings you closer to having his thick seed make you into that much more of a proper bitch. Your body spasms underneath him in pleasure as you feel the first heavy spurt of his wolf-like cum shooting into your needy womb, the feel of your alpha's seed settling into your body and marking you as his own triggering your own overpowering orgasm.[line break]";
			WaitLineBreak;
			say "     Lindsey pants above you as his knot ties the two of you together, ensuring his seed fills you all the way to the brim, the sensation of being trapped and tied underneath such a powerful beast filling your head with images of him making you his bitch, keeping you as his own, and making you a proper wolftaur just like him... Eventually his knot slowly shrinks, and he pulls out of you with a soft popping noise, and you slump to the ground bonelessly, lost in submissive bliss as the male grins down at you for a minute, before patting you on the head and saying 'I'm sure you will make a good bitch,' before padding back over to the bathroom counter. You aren't sure how long you lie there on the cum stained floor, with his seed swirling inside you, and a happy smile on your face at being told you will be a good bitch. Eventually, you begin to recover your wits, and gather yourself and your equipment back up and prepare to try to face the world again... though you would almost rather just stay here and be a happy bitch...[impregchance]";
			infect "Wolftaur";
			increase level of Lindsey by 1;
			now lastfuck of Lindsey is turns;
		else:
			say "     'After all our fun together you don't have a proper little bitch cunt yet?' Lindsey asks you as he shakes his head sadly. 'Well I guess we will have to work with what we have now then, won't we?' the large male wolftaur says as he guides you back over to the wall where his seed still stains the floor from your earlier fun. 'Let's see if another coating of wolftaur seed will help matters,' he says as he pushes you down flat onto the floor, your back resting in his partially dried seed from earlier, as he steps over your prone body, bringing his hindlegs and cock up to your chest. 'Now why don't you be a good little submissive and help me cover you in my seed again hmm?' the male beast says as he thrusts his hips slightly in the air for emphasis, his sexual musk overwhelming you with lustful thoughts of submission as you reach up and begin to stroke his pointed canine tool. The feel of his strong, powerful cock under your hands, the thick canine member feeling so much better under your hands than your own cock could ever be, his dominant musk fills your head even as you lie under him rubbing and stroking his cock and balls for all you are worth.";
			say "     You can feel your own cock hanging limply between your legs, a totally useless and weak organ compared to the handsome wolftaur's, even as your body surges with arousal and need, and his own masterful cock swells with power, its knot slowly growing ever bigger as the alpha canine groans and yips with pleasure above you. Soon your efforts are rewarded, as Lindsey lets out a loud howling noise, his voice filling the bathroom as he shoots his canine seed all over your chest and face. The feel of his cum on your body, and the increased scent of his fertile musk in your nose, makes you writhe on the ground in pleasure, your hands reaching up to rub that powerful dominant seed all over your skin, even as it slowly drips down your body to mingle with the puddles of seed you are already lying in. You hardly notice when the more dominant canine backs off, staring down at you for a minute with an amused look on his lupine face, before heading back over to the bathroom counters, leaving you lying there basking in his male gift until you finally begin to be able to think clearly again.";
			infect "Wolftaur";
			infect "Wolftaur";
			increase level of Lindsey by 1;
			now lastfuck of Lindsey is turns;
			stop the action;
	else:
		if cocks of player > 0:
			if cunts of player > 0:
				say "     'I knew you would come to see things my way,' the large male wolftaur says with a grin, as he stalks forward, the strong musk of aroused canine filling the air. 'And you are definitely looking nice and eager there, but you definitely have some equipment there that a proper bitch doesn't need. Still, we can fix that with some proper bitch training, I'm sure,' Lindsey says with an amused tone in his voice as he backs you up against the wall, his muzzle stretched wide in a lupine grin. 'Don't worry though, I'm sure once I have you properly trained you won't miss that useless little cock of yours at all,' the male wolf says as he reaches out and pushes your back up against the wall, before pushing you down into a kneeling position. Lindsey then grins as he grips the top of the nearby stall with his hands, and uses it to help him lift his front paws up onto the wall as well. His paws land on each side of your head as he braces herself on the wall, his long canine body stretching above you as his erect canine cock comes to rest right in front of your face.";
				say "     The strong musk of a dominant wolf redoubles and wipes out any thoughts of protest you might have, as he begins to thrust his canine hips forward, his cock bouncing in the air in front of you lewdly. 'Why don't you give a wolf a hand, my little wannabe bitch, or better yet, your mouth?' the male beast asks in a teasing tone, his voice seeming to invade your lust-filled thoughts, as his suggestion fills your mind. You find yourself happily reaching up to rub your hands along his canine shaft, one hand rubbing at the beasts amazing rod, while the other caresses the large canine's sac, the soft pouch full of the wonderful beast's dominant, bitch-breeding seed, making your mouth water.";
				WaitLineBreak;
				say "     You find yourself panting like a bitch as you stroke the canine creature, knowing your own pathetic cock could never match this beast's glorious rod, as the dominant wolf makes happy noises of pleasure above you while your hands tease his bestial rod, the knot on the cock in front of you growing ever larger under your hands as he yips in pleasure. Staring at the thick pink cock in front of your face, you find yourself leaning forward, needing to feel the taste of that lovely canine cock on your tongue. As your tongue traces across Lindsey's stiff organ, he groans above you in pleasure, the sound encouraging some animal part of your brain as you begin to lick and suck on his wonderful lupine rod, loving the submission and the taste of the wolftaur's dominant cock. Without any real warning, the powerful taur's cock shudders and begins to shoot its long jets of seed out onto your hands and face, Positioned in front of his canine cock as you are, your face is quickly covered with the soft strings of his seed, and your hands are soaked in his amazing smelling essence.";
				say "     You pant happily as the large wolftaur backs off down the wall, licking your lips and tasting his strong dominant gift with a smile on your face, your mind empty of everything but the dominant wolf's lovely musk, and the taste of his pleasure. Lindsey looks down at you with a canine grin, and reaches down one of his hands to pet you on the head. 'Good bitch,' the wolftaur says before he saunters back over to the counter, the words of praise making you happy as you sit there against the wall, glad to have been such a good bitch for the handsome male taur.";
				WaitLineBreak;
				say "     Your pussy clenching in lustful need as you imagine being an even better and more submissive bitch for the strong beast next time you come this way and beg him to show you what it is like to be a proper bitch. Thinking of that you realize that even though the recent encounter has your body amazingly aroused, your cock is still lying there limply, and you can hardly even bring yourself to think of using it instead of being used after your encounter with such a desirable male. Blinking dazedly several times, you find yourself trying to figure out if there isn't something wrong with that way of thinking. With your head still wrapped in his strong musk though, you shrug and merely lie there for a while against the wall, happily licking up his seed as you try to regain some semblance of normal thought...";
				infect "Wolftaur";
				increase level of Lindsey by 1;
				now lastfuck of Lindsey is turns;
			else:
				say "     'I knew you would come to see things my way,' the large male wolftaur says with a grin, as he stalks forward, the strong musk of aroused canine filling the air. 'But you certainly aren't properly equipped to be a good little bitch yet,' Lindsey says in an amused tone as he backs you up against the wall. 'Don't worry though, I'm sure we can fix that soon enough,' the wolf says as he reaches out and pushes you up against the wall, before pushing you down into a kneeling position. Lindsey then grins as he grips the top of the nearby stall with his hands, and uses it to help him lift his front paws up onto the wall as well. His paws land on each side of your head as he braces herself on the wall, his long canine body stretching above you as his erect canine cock comes to rest right in front of your face.";
				say "     The strong musk of a dominant wolf redoubles and wipes out any thoughts of protest you might have, as he begins to thrust his canine hips forward, his cock bouncing in the air in front of you lewdly. 'Why don't you give a wolf a hand, little wannabe bitch?' the male beast asks, his voice seeming to invade your lust-filled thoughts, as his suggestion fills your mind. Happily you find yourself reaching up to rub your hands along his canine shaft, one hand rubbing at the beasts amazing rod, while the other caresses the large canine's sac, the soft pouch full of the wonderful beast's dominant, bitch-breeding seed. You find yourself panting like a bitch as you stroke the canine creature, the dominant wolf making happy noises of pleasure above you as your hands tease his bestial rod, the knot on the cock in front of you growing ever larger under your hands as he yips in pleasure.";
				WaitLineBreak;
				say "     Without any real warning, the powerful taur's cock shudders and begins to shoot its long jets of seed out onto your hands and body. Positioned in front of his canine cock as you are, you are quickly covered in soft strings of his seed, and your hands are soaked in his amazing smelling essence. You pant happily as the large wolftaur backs off down the wall, licking your lips and tasting his strong dominant gift with a smile on your face, your mind empty of everything but the dominant wolf's lovely musk, and the taste of his pleasure. Lindsey looks down at you with a canine grin, and reaches down one of his hands to pet you on the head. 'Good bitch,' the wolftaur says before he saunters back over to the counter, the words of praise making you happy as you sit there against the wall, glad to have been such a good bitch for the handsome male, even without the proper equipment. Thinking of that you realize that even though the recent encounter has your body amazingly aroused, your cock is still lying there limply, and you can hardly even bring yourself to think of using it instead of being used after your encounter with such a desirable male.";
				infect "Wolftaur";
				increase level of Lindsey by 1;
				now lastfuck of Lindsey is turns;
		else:
			say "     'I knew you would come to see things my way,' the large male wolftaur says with a grin, as he stalks forward, the strong musk of aroused canine filling the air. 'And you are definitely looking nice and eager there, but you definitely still need some proper training in how to be a good little bitch for me,' Lindsey says with an amused tone in his voice as he backs you up against the wall. 'Don't worry though, I'm sure we can take care of that problem soon enough,' the male wolf says as he reaches out and pushes your back up against the wall, before pushing you down into a kneeling position. Lindsey then grins as he grips the top of the nearby stall with his hands, and uses it to help him lift his front paws up onto the wall as well. His paws land on each side of your head as he braces herself on the wall, his long canine body stretching above you as his erect canine cock comes to rest right in front of your face.";
			say "     The strong musk of a dominant wolf redoubles and wipes out any thoughts of protest you might have, as he begins to thrust his canine hips forward, his cock bouncing in the air in front of you lewdly. 'Why don't you give a wolf a hand, my little wannabe bitch, or better yet, your mouth?' the male beast asks in a teasing tone, his voice seeming to invade your lust-filled thoughts, as his suggestion fills your mind. You find yourself happily reaching up to rub your hands along his canine shaft, one hand rubbing at the beasts amazing rod, while the other caresses the large canine's sac, the soft pouch full of the wonderful beast's dominant, bitch-breeding seed, making your mouth water. You find yourself panting like a bitch as you stroke the canine creature, the dominant wolf making happy noises of pleasure above you as your hands tease his bestial rod, the knot on the cock in front of you growing ever larger under your hands as he yips in pleasure.";
			WaitLineBreak;
			say "     Staring at the thick pink cock in front of your face, you find yourself leaning forward, needing to feel the taste of that lovely canine cock on your tongue. As your tongue traces across Lindsey's stiff organ, he groans above you in pleasure, the sound encouraging some animal part of your brain as you begin to lick and suck on his wonderful lupine rod, loving the submission and the taste of the wolftaur's dominant cock. Without any real warning, the powerful taur's cock shudders and begins to shoot its long jets of seed out onto your hands and face, Positioned in front of his canine cock as you are, your face is quickly covered with the soft strings of his seed, and your hands are soaked in his amazing smelling essence.";
			say "     You pant happily as the large wolftaur backs off down the wall, licking your lips and tasting his strong dominant gift with a smile on your face, your mind empty of everything but the dominant wolf's lovely musk, and the taste of his pleasure. Lindsey looks down at you with a canine grin, and reaches down one of his hands to pet you on the head. 'Good bitch,' the wolftaur says before he saunters back over to the counter, the words of praise making you happy as you sit there against the wall, glad to have been such a good bitch for the handsome male taur. Your pussy clenching in lustful need as you imagine being an even better and more submissive bitch for the strong beast next time you come this way and beg him to show you what it is like to be a proper bitch. Blinking dazedly several times, you find yourself trying to think about that, and wondering if there isn't something wrong with that way of thinking. With your head wrapped in his strong musk though, you shrug and merely lie there for a while against the wall, happily licking up his seed as you try to regain some semblance of normal thought...";
			infect "Wolftaur";
			increase level of Lindsey by 1;
			now lastfuck of Lindsey is turns;

Lindsey ends here.
