Nightmare by Sarokcat begins here.
[ Edit the above line, replace monster name with your monster's name, and your name with the name you'd like credited for the mod. ]

"Adds a Nightmare to Flexible Survival's Wandering Monsters table, With Impreg chance"
[Description text for this Extension.]

Section 1 - Monster Responses

[ Use To say for overlong behaviours that would make the table difficult to read and understand. Typically needed if there are a lot of cock/species/cunt checks. ]

to say Nightmare attack:
	say "Unable to continue fighting the stronger and more experienced stablemaster, you collapse helplessly on top of a pile of cushions, and try to catch your breath after the battering your mind and body has endured during the combat, fortunately for you, the stablemaster seems distracted for a second as he hunts among the cushions nearby. You hear a soft whimpering noise over in the corner, and manage with some effort to turn your equine head to look, only to see the mare Daisy touching her body as she stares at you and the stablemaster with ever increasing arousal, her heat filled scent still permeating the room.  Your attention is drawn back to the stablemaster however, as the powerful black stallion steps up next to your prone form and bends over you, Looking back up at him, you realize in a panic that the golden collar you had made to chain the stablemaster is now in his hands! You try to lift up your hands to ward him off, but are far too slow and weakened from the combat to react in time, as he slips the collar around your neck and latches it firmly shut. You groan in despair as you try to grasp it with your hands, only to moan in pain as the golden treasure seems to burn into your body, melding with your neck as it sinks down under your fur.";
	say "The pain of the collar melding to your neck is only the start, and as the stablemaster steps back to watch with a chuckle, your entire body begins to burn and shift from within, and that powerful store of energy within you seems to slowly slip away and change to a more mild and servile form of power. Yes, you find yourself thinking, mild and servile is what a good slave should be, you moan happily at this realization, even though you know that somehow the collar is causing you to think such nice and submissive thoughts. You are distracted again though as your body reshapes itself more obviously, remaining powerful and equine, but also becoming slimmer and much much more feminine as well, your large breasts and slimming legs becoming increasingly sensitive as you writhe in pleasure on the cushions. Your skin burns with a strange heat, and you can hear an amused chuckle from nearby as you stroke your slender hands over your body. Looking up at the source of the noise, you find your eyes locked to the most powerful and wonderful example of stallionhood you have ever seen. The sight of his powerful body and his thick meaty manhood make your mouth water, as well as your new mare's pussy dampen with need as your own heat scent begins to fill the room and mingle with that of Daisy[']s. Something seems to click within you as you gaze with awe upon your master, for how could such a powerful stallion not own such a submissive little slave like you, and you can feel your mind empty of everything but thoughts of sex and being owned as you bring yourself up to your knees in front of him as the last of your new changes finish.";


To say Nightmare loss:
	say "You find yourself grinning eagerly as you send the stablemaster reeling one last time, the powerful stallion staggering backwards before he trips over several of the cushions and crashes to the floor, sending the cushions flying. Looking down at the prone stallion cautiously, you notice a slight glint from nearby, and a smile stretches across your muzzle as you realize that the stablemaster's fall knocked the enchanted collar out into the open. Quickly reaching down, you snatch up the collar and lunge towards the stablemaster even as he tries to struggle back to his feet. You can see his eyes widen as he tries to react, but this time at least he is far too slow to stop you from snapping the collar around his large equine neck. You can see panic in his eyes as he tries to reach up and pull the collar off, and you step back to watch to see what will happen warily. The stablemaster moans with what appears to be pleasure as he tries tearing at the collar, which seems to slowly be sinking into his body and merging with his hide, the strange glyphs on the item glowing softly as he paws at his neck. His attentions soon shift from his neck as he moans again and begins rubbing his hands over his increasingly sexy body, and you blink as he massages his expanding chest and shrinking cock eagerly, even as the rest of his body seems to become much more slender and suitable for a mare. Which is obviously what the stablemaster is now becoming you find yourself noticing with a grin as you watch the former stallion's body continue to shift and change, her new breasts blossoming out under her hands even as her new slit finishes forming and the scent of another mare in heat fills the room. Probably the most arousing thing however, is how eagerly the new mare turns to look at you with her red eyes full of adoration, and her muzzle hanging open as she pants eagerly. 'Please master, please use your slave,' you hear her moan softly as she continues to stroke her body eagerly while she stares up at you.";
		infect "Nightmare";


Section 2 - Monster Insertion

Table of random critters (continued)
name	attack	defeated	victory	desc	face	body	skin	tail	cock	face change	body change	skin change	ass change	cock change	str	dex	sta	per	int	cha	sex	hp	lev	wdam	area	cocks	cock length	cock width	breasts	breast size	male breast size	cunts	cunt length	cunt width	libido	loot	lootchance	scale (number)	body descriptor (text)	type (text)	magic (truth state)	resbypass (truth state)	non-infectious (truth state)	nocturnal (truth state)	altcombat (text)
--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	-- 	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--;

[ Adds a blank row to the table, this is immediately filled ;) ]
When Play begins:
	Choose a blank row from Table of random critters;
	now name entry is "Nightmare"; [Name of your new Monster]
	now attack entry is "[one of]He stares at you with his blazing red eyes, the flame within seeming to tear at your mind and unbalance your sense of self.[or]He strikes out at you with one powerful hoof-tipped hand, knocking you backwards![or]The powerful musk of the stablemaster fills your nostrils, causing you to pause for a minute as a wave of submissiveness sweeps over you.[or]He lashes out at you with one of his blood red hooves, knocking the wind out of you![or]The stablemaster grabs hold of you and tries to wrestle you down to the ground![or]Your opponent strokes his cock teasingly, the sight making you pause as a strange desire sweeps through you for a minute, before you shake off the effects.[at random]"; [Text used when the monster makes an Attack]
	now defeated entry is "[Nightmare loss]"; [ Text or say command used when Monster is defeated.]
	now victory entry is  "[Nightmare attack]"; [ Text used when monster wins, can be directly entered like combat text or description. or if more complex it can be linked to a 'To Say' block as the demonstration text shows.]
	now desc entry is "The stablemaster charges forward to attack, his powerful black equine form almost a mirror of your own new body as he tries to grapple you into submission!";[ Description of the creature when you encounter it.]
	now face entry is "rather sexy coal black equine muzzle stretching forward from your face, your broad forehead and mobile black equine ears sitting atop your new countenance are rather sexy as well. Although the most striking features of your new face have to be your eyes, which burn from within with an inner fire that is almost mesmerizing to look at, and the dark black and red mane of hair which spills down the back and sides of your head, the iridescent strands of black and red hair seeming to almost burn with your every movement as they frame your new face"; [You have a (your text) face."]
	now body entry is "the strong and powerful body of a black stallion, with blood red hooves and hoof tipped hands, as well as a large chest and fully digitigrade equine legs. Your new body is amazingly responsive and powerful feeling, with almost unnatural amounts of energy surging through you constantly";[ Body Description, format as the text "Your Body is (your text)"]
	now skin entry is "[one of]dark black[or]shimmering black furred[or]Nightmare[or]Coal black[or]midnight black furred[or]shadowy furred[at random]";[ skin Description, format as the text "You have (your text) skin"]
	now tail entry is "You have a long sexy shimmering equine tail swaying teasingly behind you, its silken black and deep red coloured strands seeming to catch and bend the light slightly around themselves until they almost appear to burn with an inner dark fire with every step you take.";[ Tail description, write a whole Sentence or leave blank. ]
	now cock entry is "[one of]equine[or]blunt-tipped[or]horse-like[at random]";[ Cock Description, format as you have a 'size' (your text) cock]
	now face change entry is "you feel a strange yet familiar burning pressure in your head, and cry out slightly as your face pushes forward and reshapes itself again, your forehead flattening out and your eyes burning with an inner flame as your dark equine muzzle finishes reshaping itself, your dark blood red mane once more shimmering like fire as it trails down the back of your fully equine face once more."; [ face change text. format as "Your face feels funny as (your text)" ]
	now body change entry is "your can feel that strange energy from the vials you drank building up withing you again, and causing your body to burn with energy as it begins to twist and reshape itself as it changes back into your now familiar and comfortable equine form. Flexing your hands and stomping your hooves on the ground, you find yourself grinning with amusement as you throw off the weak and pathetic infection that tried to mar your Nightmarish equine beauty."; [ body change text. format as "Your body feels funny as (your text)" ]
	now skin change entry is "your body once more burns with that strange inner fire, as it seems to crackle over and under your skin, the strange power within you sweeping over your form until once again you are completely covered in a shadowy midnight black coating of fur"; [ skin change text. format as "Your skin feels funny as (your text)" ]
	now ass change entry is "your spine cracks and shifts, and your rear shifts and changes slightly as your lovely red and black equine tail once more grows out of your rear, its soft sexy strands feel rather comforting as they overwhelm your more recent infection"; [ ass/tail change text. format as "Your ass feels funny as (your text)" ]
	now cock change entry is "power seems to flow into it and it becomes equine in form"; [ cock change text. format as "Your cock feels funny as (your text)" ]
	now str entry is 28;
	now dex entry is 26;
	now sta entry is 24;
	now per entry is 18;
	now int entry is 18;
	now cha entry is 20;
	now sex entry is "Male"; 	[ Defines which sex the infection will try and make you. current options are 'Male' 'Female' 'Both']
	now hp entry is 225;			[ How many HP has the monster got? ]
	now lev entry is 25;			[ Level of the Monster, you get this much hp if you win, or this much hp halved if you loose ]
	now wdam entry is 15;			[Amount of Damage monster Does when attacking.]
	now area entry is "None";	[ Current options are 'Outside' and 'Mall'  Case sensitive]
	now cocks entry is 1;			[ How many cocks will the infection try and cause if sex is 'Male' or 'Both']
	now cock length entry is 16;		[ Length infection will make cock grow to if cocks]
	now cock width entry is 5;		[ Size of balls apparently ;) sneaky Nuku]
	now breasts entry is 0;			[ Number of Breasts infection will give you. ]
	now breast size entry is 0;		[Size of breasts infection will try to attain ]
	now male breast size entry is 0;	[ Breast size for if Sex="Male", usually zero. ]
	now cunts entry is 0;			[ if sex = "Female or both", indicates the number of female sexes infection will grant you.]
	now cunt length entry is 0;		[ Length of female sex  infection will attempt to give you. ]
	now cunt width entry is 0;		[ Width of female sex  infection will try and give you ]
	now libido entry is 50;			[ Amount player Libido will go up if defeated ]
	now loot entry is "Chipped tooth";			[ Loot monster drops, ]
	now lootchance entry is 0;		[ Chance of loot dropping 0-100 ]
	[ These represent the new additions to the table ]
	now scale entry is 4;				[ Number 1-5, rough approx of infected PC body size/height.  1=small, 3=avg, 5=huge ]
	now body descriptor entry is "[one of]powerful[or]muscled[or]chiseled[at random]";
	now type entry is "[one of]equine[or]horse-like[at random]";
	now magic entry is true;			[ Is this a magic creature? true/false ]
	now resbypass entry is true;			[ Bypasses Researcher bonus? True/False (should almost invariably be false) ]
	now non-infectious entry is true;		[ Is this a non-infectious, non-shiftable creature? True/False ]
	now nocturnal entry is true;			[ True=Nocturnal (night encounters only), False=Diurnal (day encounters only), blank for both. ]
	now altcombat entry is "bearhugger";	[ Uses the 'bearhugger' entry from the Table of Critter Combat ]


when play ends:
	if bodyname of player is "Nightmare":
		if nightmareslavery is 1:
			say "You easily settle into your new life as your masters pet and slut in the stables, happy to tell him anything he wants to know and serve your amazing master in any way he wishes. Best of all though, you aren[']t alone as his pet for very long, as soon enough Fancy joins you in his office with a lovely new collar all her own! She seems a little confused at first, but soon comes around after you explain what an honor it is to be the slave of such a handsome and powerful stallion. Your stallion seems to find this to be amusing and pleasing as well, and he often has you tell him what a wonderful and sexy stallion he is, and how lucky you are to be his pet, and how your body constantly burns for his touch.  Happily enough, he is more than willing to touch you quite often, breeding both you and your fellow pet often, until both your bellies are full of his seed and his foals. Though sometimes he does share you out as a special reward for some of the other horsemen, which is always lovely and filling, but just not the same as having your powerful stallion bury himself in you. Eventually as his favored pet you help him expand his territory in the city, your strength now serving your master as you fight beside him on the few times his authority is challenged, often surprising his opponents with your capability and might. And when it finally comes time for the stables to be relocated elsewhere, you are proud to follow your master to a new city where you can start up another stables, and breed him many strong and powerful foals... You are just so glad to have managed to find such a wonderful and fulfilling life as a slave of such a handsome stallion!";
		if Nightmaremastery is 1:
			if humanity of player is less than 10:
				say "Your mind overwhelmed by lust and the images of all the fun you can have with your pets and servants, you quickly return to the stables where you can enjoy yourself properly. You quickly settle in to your office again, enjoying the fruits of your labors and the bodies of your many sexy mares and stallions, and while you begin to let things not related to sex slide just like the previous stablemaster did. You are more then cunning enough to ensure that fancy is no longer in a position to cause problems for you even as you give in more and more to your increasingly lustful urges. Though of course you do love visiting her in her new cell in the breeders quarters, her belly already nice and round with foal, her lust filled eyes and moans of pleasure as you tease her body are some of the most arousing things to you even now. And while the maintenance of the stables and the mares quarters does drop off a bit with her gone, you really don[']t care too much as long as there are always plenty of mares for you and the clients to enjoy, and the stables keeps expanding...";
			otherwise:
				say "When the military arrive in force, you quickly return to the stables and set up a proper welcoming party for them, with everyone being nice and well behaved, and plenty of sexy mares ready to 'properly thank' the male soldiers for rescuing them. Though you grin with amusement as you think about just how many of those mares were former soldiers themselves. Your peaceful display however confuses the military somewhat, as you knew it would, and allows you to strike a deal with several of the military leaders involved... a deal which was no doubt influenced by the teasing glimpses of naked horseflesh you allow them to see, as well as your newly acquired skill at mesmerizing people. Before long in return for some of your guards aid in pacifying some of the areas of the city, and their information on the hyena gang (which has mostly already slipped out of the city, not that they need to know that,). You have secured their agreement to transport your entire stables to a safer and more isolated location without any testing or issues, since obviously you are all still sane... of course, while all this is happening you end up quartered just behind the military lines for a while.[line break]";
				say "Which allows a number of the bored and horny soldiers plenty of time to visit your always eager mares, and lets you get a considerable amount of influence over the troops, as well as the people in charge of arranging for your move to your new stable. A location which soon, amusingly enough, changes from an isolated and remote location, to a rather nice spot right outside another major city, with easy access to another military base just a short drive away. Once you have secured this change, it isn[']t long before you begin slipping more and more of your people out to the new spot to begin 'getting it ready'. Fancy doing an amazing job of setting the new building up for you with all the supplies you manage to coax out of the military, and you smile with amusement as the military continues to arm and train your own guards as they go through the city. What is even more amusing is how they never seem to realize that your squads often go into the city smaller then they come out, while their own troops often vanish into the city instead. Your ranks swelling as more and more soldiers are seduced into becoming slutty little mares or powerful horseguards.[line break]";
				say "When the situation starts to get bad for the blockade, you leave only a token group of guards there to continue to help, as the rest of you relocate to your new home. Your obligation to the military fulfilled, you turn your full attention to building a new clientele in the city around your new home, and even begin setting up a few cameras to start dabbling in some of the more amusing porn and fetish industries.  Eventually the Hyena gang makes contact again under a new matriarch, and you renew your mutually beneficial partnership with the crazy beasts, your buisness expanding faster then ever as time goes on. And you look forward to leaving a powerful and influential legacy to one of your many foals one day, while you retire and enjoy the fine life with Fancy and a few other hand picked equines...";
		otherwise: [full quest, never took on stablemaster]
			if humanity of player is less than 10:
				if cocks of the player is greater than 0:
					say "Finally giving in to the powerful and bestial instincts of your new stallion body, you return to the stables and try to force your way in, though you are eventually driven back by the sheer numbers of guards. Crying out in rage and lust, you take the few guards and mares you managed to convert to your side during the combat, and roam the streets of the city looking for an appropriate location to build your new harem at. It isn[']t long before you manage to find a spot for your small harem to shelter, though building up a proper harem from the few mares you managed to acquire is rather hard as unchanged humans are harder then ever to find now. Eventually however the military moves into the city, and while you manage to convert several squads into more mares for your harem, they manage to drive your small band of equines back farther and farther... until eventually you are forced to slip out of the city with only a handful of mares again under cover of night. Seething with rage and lust, you waste no time searching out a small town nearby and go about rebuilding your harem and your forces once again in a night long orgy across the town. Once the town is converted, you and your new mares and guards vanish into the wilderness before any response can come, already looking for new people to convert into breeding mares so your harem can grow stronger and you can take revenge on the military and anyone else that tries to drive you out again...";
				otherwise:
					say "With your new Nightmarish instincts overwhelming your mind, you return to the stables to try to establish your dominance once and for all, though you barely make in the door before the guards try to spring a trap on you with nearly overwhelming force. You manage to slip away, beating down many of the guards to make your escape, and while they pursue you for a while, you are much faster and more capable and you eventually manage to slip away. Annoyed and angry, you wander the city streets for a while, smashing everything that gets in your way, as you take out your frustration and lust on anything and everything you can. Unfortunately, this leaves you tired and surprised when the military finally move in, and after quite a struggle they eventually manage to capture you and bring you in for study. Which actually finally lets you rest long enough to begin to influence your captors, who have no idea just how much more potent your transformation is and how much more powerful you are then the average infected beast.[line break]";
					say "It isn[']t long before you have most of the staff investigating you under your thrall, and well on their way to becoming proper equines, and soon after that your new stallions and mares manage to slip you out of captivity and into the area outside the military cordon. From there your new instincts lead you to the wide plains and open wilds, where you and your stallions and mares can run wild and free and enjoy yourself properly. Converting those few humans that discover you, and even adding some regular horses to your wandering herd, you find yourself loving the freedom of your new life, almost as much as the near constant attention from all the handsome stallions...";
			otherwise:
				say "When the military arrive, you are more then ready to leave the city behind, and the stables with the stablemaster to them. And go with them quietly to their camp to be evaluated for release. With your charisma and mesmeric abilities however, such evaluation obviously goes the way you want, and it isn't long before you are released as harmless and noninfectious not that you actually are either of those things. You find yourself grinning though as you quickly go about wandering in some of the shadier areas of the city and collecting the people you will need to build your own stable and harem here in the city. Let the old stablemaster have his run down hotel, you have much much bigger plans for yourself, and you are more then eager to get started on making a much larger, fancier, and above all, more comfortable place for yourself...";


[ Edit this to have the correct Name as well]
Nightmare ends here.
