Version 3 of Succubus by Sarokcat begins here.
[Version 3.1 - Promotion to level 8]

"Adds a Succubus to Flexible Survivals Wandering Monsters table, With Impreg chance"

Section 1 - Monster Responses

to say Succubus attack:
	if cocks of player is greater than 0:
		if bodyname of player is "Incubus":
			say "     'Ah! I can see that you[']ve already met some of my male brethren out there and are already on your way to joining us,' he succubus says with a grin as she stalks forward again. 'And now that you have stopped that silly pretense of wanting to resist, it[']s time for me to enjoy that lovely cock you[']ve brought for me to play with,' she teases with a grin as she reaches out and pushes you back and down. Your overly-aroused body is forced to stumble and lie back on the ground, while the succubus eagerly moves over you, her hands tracing down your chest until she can wrap one of them around your cock, stroking it several times and making you moan. 'What a nice lovely [cock of player] cock you have here for me, why it[']s just what I wanted!' She says teasingly as she straddles your helpless form, her perfect breasts bouncing teasingly above you as her wings lower down and rub up against your sides. The feel of her hand guiding your cock into her damp moist pussy is amazing, her other hand resting on your chest as she lowers herself onto you, her body engulfing your thick rod easily as she slides it all the way into he. She moans in pleasure above you as she begins to rock up and down on your body, both her hands rubbing up against your [skin of player] chest even as she presses your back into the ground, her pussy seeming to vibrate and massage your cock as she pistons it into her amazing female body.";
		otherwise:
			say "     'Ah! A lovely cock for me to play with, just what I needed,' The succubus says with a grin as she stalks forward again, 'And now that you have stopped that silly pretense of wanting to resist,' She says with a teasing grin as she reaches out and pushes you back and down. Your overly-aroused body is forced to stumble and lie back on the ground, while the succubus eagerly moves over you, her hands tracing down your chest until she can wrap one of them around your cock, stroking it several times and making you moan. 'What a nice lovely [cock of player] cock you have here for me, why it[']s just what I wanted!' She says teasingly as she straddles your helpless form, her perfect breasts bouncing teasingly above you as her wings lower down and rub up against your sides. The feel of her hand guiding your cock into her damp moist pussy is amazing, her other hand resting on your chest as she lowers herself onto you, her body engulfing your thick rod easily as she slides it all the way into he. She moans in pleasure above you as she begins to rock up and down on your body, both her hands rubbing up against your [skin of player] chest even as she presses your back into the ground, her pussy seeming to vibrate and massage your cock as she pistons it into her amazing female body.";
		say "     You groan as you feel your orgasm building, unable to resist her body[']s teasing of your manhood, your cock seeming to become even more sensitive as you spill your seed into her, your body shuddering with pleasure even as her pussy milks your cock of every drop of seed. She chuckles down at you as you lie there gasping with pleasure underneath her, her breasts shaking in front of you as evidence of her own female orgasm, 'That was a good start,' she says teasingly as she begins to rub up against your hypersensitive body all over again, 'But surely you don[']t think we are done quite yet?' The succubus purrs out, and you moan as you can feel your cock growing hard again under the ministrations of her amazingly enticing pussy. You lose track of anything but the pleasure as she begins to fuck you again, only able to catch small flashes of her body moving against yours, as you cry out several times over the next hour. Eventually when even her talents are unable to coax your cock into life for another round, she grins as she finally gets off of you, leaving you lying there on the ground panting desperately as you try to think. 'You were fun, I bet you would make a good little pet...' She purrs as she looks down at you appraisingly, and you blink up at her, barely having the energy to muster a reaction as she reaches down and pets your head affectionately. 'If you ever get bored of just wandering around out here, and want to be a nice well-fucked sexy little pet, just hunt me down again sometime... I[']m looking forward to it already,' The succubus says with a smile, before turning and stalking off down the streets of the red light district, her hips swaying seductively with each step.";
	otherwise:
		if bodyname of player is "Succubus":
			say "     'Ah looking good there, very good,' The succubus says teasingly as she rubs her naked body up against your own unprotesting form, the fight having gone out of you at some point as you stare at your fellow succubus happily. 'Almost a proper succubus already, I bet you just can[']t wait,' She says as she hugs you to her, her lips meeting your own as she kisses you enthusiastically your own mouth parting almost automatically as you find your tongue meeting hers in a deep teasing kiss. You groan into her mouth as her hands roam your body, seeming to know exactly where to touch and tease you to bring you the most pleasure, your own hands soon rubbing over the succubus[']s body just as eagerly as the amazing pleasure fills your mind. 'Isn[']t this wonderful,' The succubus breathes out as she breaks the kiss, and you can only moan in response, your reaction causing her to chuckle as she grinds her naked body up against your own soft female form. 'You aren[']t quite a full succubus yet, but you are almost there, soon very soon,' She says with amusement as her wings fold around you and rub your sides teasingly, their soft leathery feel on your hypersensitive skin makes you cry out with pleasure even as you bring your own new wings down to rub up against your fellow succubus[']s.  'That[']s it, just forget that silly humanity of yours and embrace the pleasure,' She whispers to you, her words sinking into your mind and sounding increasingly tempting and reasonable with each whispered syllable, 'These bodies of ours are just made for pleasure, made to enjoy amazing orgasms, made to tempt and tease and flirt, and most especially made to enjoy the cocks and pussies of all sorts of creatures.' She says as she brings you to a gasping orgasm with her silken touches and sensual words, you shudder against her helplessly as she continues to whisper all sorts of erotic suggestions to you, filling your head with increasingly arousing thoughts of all the sexual fun you can have as a proper succubus. Eventually she grins and helps you to sit down on the pavement for a minute, your mind still reeling as she grins down at you, before saying 'Yes, you will have such fun, such fun with us indeed. I look forward to seeing you join us, you will make a wonderful sister...' She says, her approving words making you strangely happy, as she turns and vanishes down the street, looking for some more fun...";
		otherwise:
			say "     'You look like you will make a fine little succubus soon,' The succubus says as she pins your tired body up against one of the buildings, 'After all, why else would someone like you be wandering around in this lovely place if you weren[']t looking for all the amazing sex your body can stand,' She says teasingly as she runs one of her claw like nails down your cheek teasingly, before leaning in and planting a kiss on your mouth, the taste of her lips on yours makes your body tighten with need, as pleasure washes over your mind. You moan into her mouth as her hand slowly drifts down your body teasingly, until she is rubbing her fingers up against your increasingly damp pussy, and you pant with need as she breaks the kiss and licks her lips, your mind increasingly filled with thoughts of lots of lovely depraved sexual acts. 'Good girl,' she whispers into your ear teasingly, her hands roaming your increasingly aroused body as she continues, 'It[']s so nice to give into all those wonderful sexual urges you have isn[']t it, and as a Succubus like me you will get to experience all the wonderful pleasures that female body of yours is designed for.' She purrs into your ear as the hand on your crotch rubs and strokes all the right places to make you moan eagerly, your body screaming to be filled with each teasing touch. You lose track of what the succubus is saying, as your mind fills with visions of all the lusty beasts in the city, and how good it would be to fuck them all, play with them, tease them, with a body that never grows tired, and is more sensitive then you ever imagined before...  Soon you feel yourself crying out in orgasm, and gasping look around you, only to note that the street is now empty, and the hands that have been rubbing your body so intensely have been yours for a while now.  Blushing slightly you try to gather your wits together as you continue onwards, but you still find your thoughts oddly filled with images of all the fun you could have as a lusty little succubus...";
	if libido of player > 80, now libido of player is 80;
	if "Male Preferred" is listed in feats of player and guy is not banned:
		infect "Incubus";
	otherwise:
		infect "Succubus";

To say Succubus loss:
	if lisaartemiscount1 > 0 and lisaartemiscount1 < 5, increase lisaartemiscount1 by 1;
	if companion of player is demon brute and hp of Lilith is 0 and inasituation is false:			
		if cocks of player is greater than 0:
			if bodyname of player is "Incubus":
				say "     'Good fight, dark brother,' the succubus says with a smile as she raises her hands in surrender and you order your companion to stop fighting and stand still. 'You are definitely the more powerful seducer,' she acknowledges with a smile as you grin back at her, 'and you do have a most interesting pet... how did you get him so - tame?'";
				say "     She saunters over to your captured demon brute, stroking her hand over his muscled form and grabbing his balls. He snarls, clearly aching to rape her, you, anyone - then starts to whimper as the succubus squeezes tightly. She gives a somewhat cruel chuckle as she turns to you, her eyes searching out the amulet around your neck. 'Magic, hm? That opens some possibilities... I could change your pet a bit, if you[']re interested. Just think about how much fun you could have with this big boy if he had a pussy too. Look me up in the [bold type]Burned-Out Chapel[roman type] in Flint street, if you[']re interested. For now, I[']ve got to go - mortals to corrupt, you know...'";
				say "     The defeated succubus purrs as she slips forward to give you a hug, her lips meeting your own in a surprisingly intimate kiss, your body reacting instinctively as you melt into her kiss.  Before you can bring yourself to protest, the tricky succubi has already broken the kiss and flown off into the [if daytimer is day]shadows[otherwise]night[end if], leaving you standing there with the feel of her lips pressed up against your own, as your body tingles with arousal.";
				infect "Incubus";	
			otherwise:
				say "As the succubus staggers back under your assault, your captured demon brute gives a satisfied grunt and steps forward to throw her down and rape her. With a single command, you freeze him in his steps - you wouldn[']t want the creature to think it can decide anything on its own, now that you[']re its master. Finding her balance again, your infernal opponent gives you a surprised look, which gives way to a seductive smile. 'How interesting... how did you get him so - tame?'";
				say "     She saunters over to your captured demon brute, stroking her hand over his muscled form and grabbing his balls. He snarls, clearly aching to rape her, you, anyone - then starts to whimper as the succubus squeezes tightly. She gives a somewhat cruel chuckle as she turns to you, her eyes searching out the amulet around your neck. 'Magic, hm? That opens some possibilities... I could change your pet a bit, if you[']re interested. Just think about how much fun you could have with this big boy if he had a pussy too. Look me up in the [bold type]Burned-Out Chapel[roman type] in Flint street, if you[']re interested. For now, I[']ve got to go - mortals to corrupt, you know...'";
				say "     The defeated succubus purrs as she slips forward to give you a hug, her lips meeting your own in a surprisingly intimate kiss, your body reacting instinctively as you melt into her kiss.  Before you can bring yourself to protest, the tricky succubi has already broken the kiss and flown off into the [if daytimer is day]shadows[otherwise]night[end if], leaving you standing there with the feel of her lips pressed up against your own, as your body tingles with arousal.";				
		otherwise:
			if bodyname of player is "Succubus":
				say "     'Good fight, dark sister,' the succubus says with a smile as she raises her hands in surrender and you order your companion to stop fighting and stand still. 'You are definitely the more powerful succubus,' she acknowledges with a smile as you grin back at her, 'and you do have a most interesting pet... how did you get him so - tame?'";
				say "     She saunters over to your captured demon brute, stroking her hand over his muscled form and grabbing his balls. He snarls, clearly aching to rape her, you, anyone - then starts to whimper as the succubus squeezes tightly. She gives a somewhat cruel chuckle as she turns to you, her eyes searching out the amulet around your neck. 'Magic, hm? That opens some possibilities... I could change your pet a bit, if you[']re interested. Show this big brute how it is to have a pussy. Look me up in the [bold type]Burned-Out Chapel[roman type] in Flint street, if you[']re interested. For now, I[']ve got to go - mortals to corrupt, you know...'";
				say "     The defeated succubus purrs as she slips forward to give you a hug, her lips meeting your own in a surprisingly intimate kiss, your body reacting instinctively as you melt into her kiss.  Before you can bring yourself to protest, the tricky succubi has already broken the kiss and flown off into the [if daytimer is day]shadows[otherwise]night[end if], leaving you standing there with the feel of her lips pressed up against your own, as your body tingles with arousal.";
				infect "Succubus";
			otherwise:
				say "     As the succubus staggers back under your assault, your captured demon brute gives a satisfied grunt and steps forward to throw her down and rape her. With a single command, you freeze him in his steps - you wouldn[']t want the creature to think it can decide anything on its own, now that you[']re its master. Finding her balance again, your infernal opponent gives you a surprised look, which gives way to a seductive smile. 'How interesting... how did you get him so - tame?'";
				say "     She saunters over to your captured demon brute, stroking her hand over his muscled form and grabbing his balls. He snarls, clearly aching to rape her, you, anyone - then starts to whimper as the succubus squeezes tightly. She gives a somewhat cruel chuckle as she turns to you, her eyes searching out the amulet around your neck. 'Magic, hm? That opens some possibilities... I could change your pet a bit, if you[']re interested. Show this big brute how it is to have a pussy. Look me up in the [bold type]Burned-Out Chapel[roman type] in Flint street, if you[']re interested. For now, I[']ve got to go - mortals to corrupt, you know...'";
				say "     The defeated succubus purrs as she slips forward to give you a hug, her lips meeting your own in a surprisingly intimate kiss, your body reacting instinctively as you melt into her kiss.  Before you can bring yourself to protest, the tricky succubi has already broken the kiss and flown off into the [if daytimer is day]shadows[otherwise]night[end if], leaving you standing there with the feel of her lips pressed up against your own, as your body tingles with arousal.";				
		now Burned-Out Chapel is known;			
		now hp of Lilith is 2;
	otherwise:
		if cocks of player is greater than 0:
			if bodyname of player is "Incubus":
				say "     'Good fight, dark brother,' the succubus says with a smile as she raises her hands in surrender.  'You are definitely the more powerful seducer,' she acknowledges with a smile as you grin back at her, feeling strangely at ease now that the combat is over. 'I really look forward to you joining our ranks fully and showing us just how amazing you can be.' The defeated succubus purrs as she slips forward to give you a hug, her lips meeting your own in a surprisingly intimate kiss, your body reacting instinctively as you melt into her kiss.  Before you can bring yourself to protest, the tricky succubi has already broken the kiss and flown off into the [if daytimer is day]shadows[otherwise]night[end if], leaving you standing there with the feel of her lips pressed up against your own, as your body tingles with arousal.";
				infect "Incubus";
			otherwise:
				say "     'Well that[']s just too bad,' The succubus says as she staggers back under your assault, 'I could have shown you such an amazing time,' she sighs, as she turns and leaps into the sky, sending you a teasing wink over her shoulder as she vanishes.";
		otherwise:
			if bodyname of player is "Succubus":
				say "     'Good fight, dark sister,' the succubus says with a smile as she raises her hands in surrender.  'You are definitely the more powerful succubus,' she acknowledges with a smile as you grin back at her, feeling strangely at ease now that the combat is over. 'I really look forward to you joining our ranks fully and showing us just how amazing you can be,' The defeated succubus purrs as she slips forward to give you a hug, her lips meeting your own in a surprisingly intimate kiss, your body reacting instinctively as you melt into her kiss. Before you can bring yourself to protest, the tricky succubi has already broken the kiss and flies off into the [if daytimer is day]shadows[otherwise]night[end if], leaving you standing there with the feel of her lips pressed up against your own, as your body tingles with arousal.";
				infect "Succubus";
			otherwise:
				say "'Oh, what a nice, strong woman.  Are you sure you don[']t want to be a sexy little succubus like me?' The succubus says teasingly as she dances backwards from your last attack. 'You really don[']t know what you are missing... maybe next time you will let me show you just how to embrace your true, feminine power,' she says with a grin as she launches herself into the air and vanishes.";

to say succubus fight:
	say "[one of]The succubus strikes out at you with her surprisingly sharp nails.[or]The succubus[']s strange green eyes seem to glow, and you find yourself staring into their slit pupiled depths, and wondering whether it wouldn[']t be a better idea just to submit to her desires.[or]She pauses to pose in front of you, and you find yourself unable to attack such a perfectly beautiful creature...[or]Darting forward, you are surprised when she presses her lips to your face and gives you a kiss, the feel of her soft lips rubbing up against you making you moan with increasing desire.[or]Slipping to the side as you try to strike at her, the succubus lashes out at you with one of her wings![or]The succubus sways her hips seductively as she stalks forward, distracting you enough that her fist connecting with your face comes as a complete surprise![at random]";
	increase libido of player by a random number from 3 to 8;
	if bodyname of player is "Succubus" or bodyname of player is "Incubus", increase libido of player by a random number between 1 and 2;
	if "Horny Bastard" is listed in feats of player, increase libido of player by 1;
	if "Cold Fish" is listed in feats of player, decrease libido of player by 1;
	if libido of player >= 110:
		say "You find yourself too aroused to keep fighting the sexy seductress and drop to your knees.  Having fallen under the sway of this infernal temptress, you long for her to help relieve the heat in your loins.";

Section 2 - Monster Insertion

Table of random critters (continued)
name	attack	defeated	victory	desc	face	body	skin	tail	cock	face change	body change	skin change	ass change	cock change	str	dex	sta	per	int	cha	sex	hp	lev	wdam	area	cocks	cock length	cock width	breasts	breast size	male breast size	cunts	cunt length	cunt width	libido	loot	lootchance	scale (number)	body descriptor (text)	type (text)	magic (truth state)	resbypass (truth state)	non-infectious (truth state)	nocturnal (truth state)	altcombat (text)
--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	-- 	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--;

When Play begins:
	Choose a blank row from Table of random critters;
	now name entry is "Succubus"; [Name of your new Monster]
	add {"Succubus"} to infections of girl;
	add {"Succubus"} to infections of hellspawn;
	now attack entry is "[succubus fight]"; [Text used when the monster makes an Attack]
	now defeated entry is "[Succubus loss]"; [ Text or say command used when Monster is defeated.]
	now victory entry is  "[Succubus attack]"; [ Text used when monster wins, can be directly entered like combat text or description. or if more complex it can be linked to a 'To Say' block as the demonstration text shows.] 
	now desc entry is "Travelling the mostly empty streets of the red light district, you are caught by surprise when a rather large naked woman steps out in front of you. Looking her over you would almost think she was still human, if it weren[']t for the large bat-like wings coming out of her back, and of course, the small horns on her head and the rather feral look in her green, slit pupil eyes. Seeing she has your undivided attention, the strange woman twists her lavender lips into an amused smile and says '[one of]Oh yes, now this should be fun,[or]You look like you need some help loosening up a bit...[or]Let me show you how much fun a succubus can be[or]I wonder if you will make a better pet, or a better succubus... Lets find out shall we?[at random]' before lifting up her hands with their rather sharp nails and stalking towards you in a predatory manner.";[ Description of the creature when you encounter it.]
	now face entry is "beautiful human face, your strange slit pupiled eyes and the small horns poking out of your hair, the only clue that your almost perfect features hide the lusty desires of a succubus behind your innocent";[Your have a (your text) face."] 
	now body entry is "surprisingly perfect, your muscles and curves nicely defined, your long eye catching legs perfect for showing off, and your soft hands with their long nails are just made for stroking and petting the opposite sex. The only true sign of your unusual nature, are the two large bat-like wings, folded up against your back, and while they are not quite powerful enough to lift you aloft yet, though you think that might change sometime soon";[ Body Description, format as the text "Your Body is (your text)"] 
	now skin entry is "[one of]soft, human[or]pale[or]perfect[at random]";[ skin Description, format as the text "You have (your text) skin"] 
	now tail entry is "";[ Tail description, write a whole Sentence or leave blank. ] 
	now cock entry is "[one of]amazing[or]incubus[or]perfect[or]human-like[at random]";[ Cock Description, format as you have a 'size' (your text) cock] 
	now face change entry is "your facial muscles seem to ripple under the skin, rearranging themselves into a softer more sexual appearance, soft horns pushing out of your lovely new waterfall of long silken hair"; [ face change text. format as "Your face feels funny as (your text)" ]
	now body change entry is "invisible hands seem to massage your muscles, rubbing and molding your body into a more attractive form, though you are soon distracted from this change by the strange feeling of your skin stretching and pressing out from your back. Looking over your shoulder you can[']t help but stare in wonder as two large bunches of flesh push out of your back, before shifting and stretching themselves out into two surprisingly good looking wings"; [ body change text. format as "Your body feels funny as (your text)" ]
	now skin change entry is "your skin seems to soften and glow with a sexual sheen, any blemishes and unwanted hair wiped away by the amazingly wonderful feeling changes"; [ skin change text. format as "Your skin feels funny as (your text)" ]
	now ass change entry is "it tightens up into a perfect sexy ass"; [ ass/tail change text. format as "Your ass feels funny as (your text)" ]
	now cock change entry is "it seems to grow partially erect and twitch eagerly, almost like it has a mind of its own, eagerly hunting for the next chance to be put to use"; [ cock change text. format as "Your cock feels funny as (your text)" ]
	now str entry is 16;
	now dex entry is 20;
	now sta entry is 12;
	now per entry is 16;
	now int entry is 10;
	now cha entry is 25;
	now sex entry is "Female";       [ Defines which sex the infection will try and make you. current options are 'Male' 'Female' 'Both']
	now hp entry is 50;              [ How many HP has the monster got? ]
	now lev entry is 8;              [ Level of the Monster, you get this much hp if you win, or this much hp halved if you loose ] 
	now wdam entry is 14;            [Amount of Damage monster Does when attacking.]
	now area entry is "Red";         [ Current options are 'Outside' and 'Mall'  Case sensitive]
	now cocks entry is 0;            [ How many cocks will the infection try and cause if sex is 'Male' or 'Both']
	now cock length entry is 0;      [ Length infection will make cock grow to if cocks]
	now cock width entry is 0;       [ Size of balls apparently ;) sneaky Nuku]
	now breasts entry is 2;          [ Number of Breasts infection will give you. ]
	now breast size entry is 9;      [Size of breasts infection will try to attain ]
	now male breast size entry is 0; [ Breast size for if Sex="Male", usually zero. ]
	now cunts entry is 1;            [ if sex = "Female or both", indicates the number of female sexes infection will grant you.]
	now cunt length entry is 12;     [ Length of female sex  infection will attempt to give you. ]
	now cunt width entry is 6;       [ Width of female sex  infection will try and give you ] 
	now libido entry is 80;          [ Amount player Libido will go up if defeated ]
	now loot entry is "Chipped tooth";			[ Loot monster drops, ]
	now lootchance entry is 0;       [ Chance of loot dropping 0-100 ]
	[ These represent the new additions to the table of random critters ]
	now scale entry is 3;            [ Number 1-5, approx size/height of infected PC body: 1=tiny, 3=avg, 5=huge ]
	now body descriptor entry is "[one of]alluring[or]sexy[or][if cunts of player > 0]sultry[otherwise]handsome[end if][at random]";
	now type entry is "demonic";     [ one-word creature type. Ex: feline, canine, lupine, robotic, human... Use [one of] to vary ]
	now magic entry is true;         [ Is this a magic creature? true/false (normally false) ]
	now resbypass entry is false;    [ Bypasses Researcher bonus? true/false (almost invariably false) ]
	now non-infectious entry is false;		[ Is this a non-infectious, non-shiftable creature? True/False (usually false) ]
	blank out the nocturnal entry;   [ True=Nocturnal (night encounters only), False=Diurnal (day encounters only), blank for both. ]
	now altcombat entry is "default";[ Row used to designate any special combat features, "default" for standard combat. ]

when play ends:
	if bodyname of player is "Succubus":
		if humanity of player is less than 10:
			if cunts of the player is greater than 0:
				if cocks of the player is greater than 0:
					say "Finally giving in to your new body[']s strong sexual urges, you waste no time in returning to the red light district, where you waste no time in hunting down one of the succubi that changed you. Once you find her, you waste no time in pouncing on her surprised form, and while she smiles at first at her new sister in welcome, her eyes go wide as she feels your large cock rubbing up against her eager pussy.  Grinning evilly, you waste no time in fucking the surprised succubus senseless, her female body unable to keep up with the stamina of your own male and female needs.  Once she finally acknowledges you as her superior, she leads you back to where the other succubi are waiting with their captive pets, and you waste no time in filling each and every one of them with your demonic seed, plunging your cock into their bodies again and again, even as other succubi lick and worship your needy pussy and bountiful new breasts. Soon the other succubi are all kneeling before you as well, even their lusty desires unable to keep up with your insatiable new body, and your new subjects hail you as their queen.  You can almost feel your horns growing slightly larger, as your body becomes even more perfect under their adoring caresses, and you enjoy the irony of your former tormentors worshipping you so very eagerly. Still, their worship isn[']t quite enough, and while you are sure that your seed will grow in their bellies until more succubi will be born to worship you, you still need more playthings to satisfy you now. You waste no time in commanding your new subjects to hunt through the city to find you more pets and people to convert, while you enjoy the ones already here, and when this doesn[']t bear fruit fast enough, you order them to search even farther afield.[line break]";
					say "The military camp proves to be the perfect place for your succubi to hunt, all the horny young soldiers being easily led astray and converted into either succubi themselves, or pets for your pleasure, depending on just how depraved they are to begin with. And soon the camp is in chaos as more and more soldiers give in to your temptations every day, the quarantine attempt failing as they begin to lack the ability to reinforce the barricades, the soldiers joining your ranks faster then they can be replaced. While this lets all the other creatures in the city out as well, their survival and intent to spread only amuses you and your sisters, and you look forward to keeping them as lovely little pets as well, once you and your army of succubi have finished securing your hold on the rest of the land around here.  Soon your small foothold spreads across the land, as more and more people give in to their baser urges, and a new kingdom rises up from the ruins of their pathetic little civilization. A kingdom of succubi, based on sex and pleasure, with you at its head, as the dark queen of all the succubi...";
				otherwise:
					say "Succumbing to your new desires, you quickly spread your wings and return to the red light district of the city, where your new succubus sisters greet your arrival with open arms and lusty kisses. Joining your new sisters in celebration of your new form, you return their kisses eagerly, and find your hands straying over their soft sultry bodies just as eagerly as their hands roam over your own. Soon enough, that just isn[']t enough for you and your sisters, and you all break up to go roam the city some more, looking eagerly for more survivors to convert. While you find a number of already converted beasts and creatures as you prowl the streets, most of them are hardly able to sate your needs for long, and you leave them behind you, nice and worn out from your insatiable appetites, as you continue your search. Fortunately for you, it isn[']t long until the rescue comes, and you are able to sidle up to several squads of those handsome soldiers as they come in to [']rescue['] you. Soon it is they who need rescuing, as you tease and kiss them, and whisper how much you want to [']thank['] them for coming to save you into their all to gullible ears. Before long, each batch of soldiers is well on their way to joining you as a lovely new sister, or becoming a nicely oversexed little male pet for you and your sisters to enjoy. And the best part is, there always seem to be more lovely little gullible soldiers where the last group came from...";
			otherwise:
				say "Succumbing to the strange whispering desires in your head, you find yourself wandering back to the area where you were accosted by the strangely alluring succubus earlier. Arriving there, you feel strangely lost for several minutes, until you see the beautiful succubus approaching you teasingly, a collar in one hand, and a leash in the other. 'Now there[']s a fine looking pet for me and my sisters to play with,' She says teasingly as she examines your form with an amused smile on her dark lips. 'It looks like you[']ve finally learned to accept your new role as just another male pet for us to suck and fuck now haven[']t you.' She purrs with amusement as she holds up the collar to you as you shudder with arousal and desire for her sultry body. 'All you need to do now is slip the collar on for me and we will make sure you never need to worry about anything other then fucking ever again...' She says teasingly as she holds the collar out for you, and while you know somewhere deep down inside that if you put the collar on, you will never be the same again, the need in your body is just too great, and the promise of all the amazing sex to come fills your mind as you reach out and take the collar. The succubus smiles happily as you slip the collar around your neck, the latch seeming to vanish once the soft leather band is securely fastened against your skin, and you feel like something inside you has been collared and chained as well. Fastening the leash to your collar, the succubus begins to lead you off down the street like a good pet, your cock growing harder and your body tingling more and more with arousal at every step.  Soon you can[']t help but fantasize about all the ways you can be a good little pet for your mistress, serving her and her sisters like a good fucktoy, while they go out and hunt for more innocent people to make into sexy pets just like you. Arriving at the lobby of a small building, you look up to see a number of other succubi smiling and grinning at you eagerly.  As your new mistress parades her pet around the room, you see several other pets already serving their own mistresses in the corners, and realize that all your dirty little fantasies are about to come true.";
		otherwise:
			if cunts of the player is greater than 0:
				say "When the rescue comes, you are more then happy to wait for the military to show up and escort you out of the horribly strange city. Your new form getting you several speculative looks and the phone numbers of a number of the soldiers before you can manage to talk your way out of their camp, their fawning attempts to win your favor making you smile and feel rather powerful. Once you are clear of the military and free to do what you want, you try to think for a minute about what you can do to make a living now that you have changed so drastically.  The answer comes to you easily however as you recall how well people respond to your new body, and so you [one of]decide to try your hand at being a model, putting your new awesome body to good use. Tracking down several people involved in the industry is surprisingly easy, and with your looks soon several modeling firms are fighting with each other over you, much to your amusement. When you finally get out on the runway, you spark a tremendous amount of interest and not a little controversy there as well, starting a whole new fad for the backless dresses you wear to emphasize your wings, and earning you even more offers to model for different companies. Soon you can see your own inhumanly beautiful face smiling back at you from billboards and commercials all over the place, and as you realize just how rich and powerful your new body has made you, you find yourself smiling and wondering what that succubus you met in the city would think if she could see you now... maybe you should hire someone to go into the quarantined city and find out... after all it would be fun to have another sister or two around to share your fame with...[or]look into what it takes to get on TV, sure that with your looks and charm, it won[']t be hard at all. You find your assumption to be correct, as once you track down one of the talent agencies, they practically beg you for the honor of putting you on TV. Soon you find yourself moving up from a guest on several shows, to lead, and before you know it you have a number of movie offers as well, your exotic looks and your perfect poise making you quite popular to all ages, and amusingly enough a sex symbol for both sexes. The worship of your many adoring fans makes you feel powerful and downright demonic at times, and you enjoy your new life with hedonistic abandon, never seeming to grow any older, or to change in appearance much from your current perfection, for many many decades to come...[at random]";
			otherwise:
				say "Fighting off the building urges of your new body, you are relieved when the military finally arrives to rescue those of you who still are sane enough to want to be rescued. Going with them you find your new body to be almost a blessing as you see just how many other strange and unusual forms the people in the city ended up with. Looking relatively human turns out to be a good thing as you are released from military custody after only the most cursory of examinations, free to start a new life for yourself far away from the strangely seductive woman who changed your body and gave you a pair of wings to match her own.  Making your way in the world after your life changing ordeal is hard, but you find yourself relishing the challenge, the work taking your mind off your ever present sexual urges, and your near inexhaustible energy helps you to excel at most everything you set your hands to. Soon you are living an increasingly comfortable life, as the money and promotions roll in steadily, and before too long you have an increasing number of women throwing themselves at you.";
				say "[one of]Never one to turn down an opportunity for fun, you enjoy indulging yourself with the women at every turn, acquiring quite a reputation as both a ladykiller, and as a mind blowingly amazing lover. Still despite all your conquests in the bedroom, something still seems to be missing, both in the bed and in your life, the women you sleep with never able to quite sate your lusts, or bring you to the level of pleasure you somehow know is just out of reach.  Your life goes on like this for quite a while, others growing older and weaker while you never seem to age a day, until eventually one day you have a strange visitor.  When she throws back her cloak to reveal herself as the succubus from the city, you find your mind filling with lustful joy at the sight, and your cock growing incredibly hard as you realize every woman you have fucked up until this point was all in preparation for this moment. Welcoming it into your house eagerly, she soon makes it her own, as it should be, your well trained body making you the perfect little pet for her and her sisters. Surrendering to the passionate nature of your succubus mistress, you realize that you have finally found the meaning in life you were waiting for, as a powerful sexual pet and tool made for serving your mistress, as she expands her control throughout the outside world one new pet at a time...[or]While you are always horny, and increasingly interested in the array of women, something holds you back from indulging yourself, as you look at them and realize just how pale and lifeless they seem beside the woman you met in the city. Your playing hard to get only intrigues the women further and helps boost your success, but you still find yourself holding back and waiting for something you can[']t quite define. Eventually many years later, still young and strong while others around you have grown old, you have a strange visitor arrive at your door one night, and as she throws off her disguise and you stare at the mesmerizingly beautiful succubus once again, and you realize that what you have been waiting for has finally arrived. Welcoming her into your house and your bed, you learn that the years of saving up your energy and building up your willpower have made you powerful internally as well as externally, and you are finally a match for the amazingly talented succubus. Your willpower and resilience having built up to the level where you can meet her as an equal in bed as well as out of it, surprising and pleasing her greatly. Intrigued she decides to stay with you this time, and together the two of you become a very powerful force behinds the scenes in the world of human business, helping to steer the world into one more suitable for both of you to enjoy over your long long lives...[at random]";

Succubus ends here.
