Tigertaur by Sarokcat begins here.
[ Version 1.2 - Player loss anal scene ]

"Adds a tigertaur to Flexible Survival's Wandering Monsters table, with impreg chance"

Section 1 - Creature Responses

to say Tigertaur Wins:
	project the Figure of Tigertaur_hard_icon;
	if Player is female:
		say "     Unable to resist the strong advances of the tiger-like beast, you swiftly find yourself knocked to the ground. Rubbing herself against you, her touch causes your body to tingle in pleasure, as the scent of her musky tiger-like arousal causes your pussy to dampen with arousal. Seeming to scent your reaction to her, the tigertaur rumbles in approval, as she moves herself over your body, the feline herm's cock rubbing against your nether regions as her soft breasts rub up against your body. Her front paws grip your body tight, as she lowers her hips and begins to thrust them against you, causing you to moan at the feel of her soft belly fur and even softer breasts rubbing up against your body, as her pointed cock tries to find its way inside you. Soon you both cry out in ecstasy, as her hard cock manages to gain entrance to your increasingly willing body, the tigertaur's front paws run themselves along your sides as she grips you tightly, pulling you to meet her with every one of her short quick thrusts. You find yourself trapped in a sensualistic paradise as her silken fur runs over your body, and her hot thick tiger-like cock fills your passage with its amazing presences, its soft barbs tugging at your insides with every movement and making you writhe and beg underneath the beast like a cat in heat.";
		say "     Soon you find yourself moaning underneath the tigertaur as she shoots her hot feline seed into your body, causing you to cry out in your own orgasm at the feel of her fertile cream filling your insides, causing you to shudder and grip her bestial body against you tightly. Even as you begin to relax and come down from the heights of pleasure, you can feel her cock stiffening within your body again, causing your eyes to widen as the tiger-like beast begins to move her hips against you again. You moan as you recall that tigers can mate for hours or even days without much rest, as she begins to move her magnificent cock into your sensitive body again, you find yourself eagerly submitting to the pleasure all over again. Her thick musk and bestial cock arousing you even faster than before as she continues to thrust herself into you again and again, causing you to orgasm underneath her as she fills you with her seed time after time, each rough coupling sending your mind spiraling ever higher with pleasure. Eventually you lose track of anything but the feel of the tiger-like body above you, and the joy of your body being penetrated again and again, your mind a haze of lust and hormones as the tigertaur reduces you to little more than a pleasure crazed beast underneath her. Finally though, the tiger taur seems to be satisfied as it lifts its strong body off your addled form.";
		CreatureSexAftermath "Player" receives "PussyFuck" from "Tigertaur";
		if Player is male:
			say "     The beast looks over your spent form, her eyes straying to your limp cock, where it had been spilling its seed over your body helplessly with each orgasm. And the creature seems to murr in disappointment as she rubs her back legs together, seeming to realize that you are in no shape to attend to her own body right now, the beast seems to sigh, as it goes off looking for something else to sate itself on. Leaving you lying there in a puddle of your own seed, while the beast's own seed leaks out of your well used passage.";
		else:
			say "     The beast looks over your spent and well-fucked form, her eyes straying to your belly, slightly distended from her seed, and your well-used pussy, which is still clenching desperately for her feline cock to fill it again while her seed leaks out of it. Murring and seeming satisfied, she lifts up one of her front paws and rubs it over your stomach for a minute, before backing off and heading on her way, apparently happy at her day's work. You moan as your body slowly relaxes and your mind clears slightly of the needy haze that had taken it over, you find your own hands lowering to rub your well-filled stomach as well, wondering if the tiger-like beast left you with several little tiger-like beasts planted deep inside you. You find yourself almost excited by that thought, your sensitive body reacting to your touch easily, as you find yourself almost hoping to have a permanent reminder of your lovely encounter with the tiger beast growing within you...";
	else if a random chance of anallevel in 7 succeeds or Cock Count of Player is 0:
		say "     Unable to resist the strong advances of the tiger-like beast, you swiftly find yourself knocked to the ground. Rubbing herself against you, you can feel your skin tingle in pleasure wherever she touches, as she rubs her furred form over yours. The tigertaur gropes you between your legs and, after confirming that you don't have a pussy for her to fill, she shrugs and pushes you down onto all fours. The large feline moves to mount you; her desire to fuck something now focused on your asshole as a replacement. As she moves her body over yours, her scent filling your head you with its spicy musk, arousing you with its dual-gendered aromas[if Player is submissive or HP of Player > 0]. You moan and squirm a little, mostly trying to get yourself into a more comfortable position for the coming assfuck you increasingly desire[else]. You moan and squirm a little, part of you still trying to resist, but you're too worn to really succeed in escaping the coming assfuck[end if].";
		say "     The tigertaur rumbles excitedly as prods her feline cock against your asshole. Her front paws grip you firmly as she presses her hips to yours, driving her herm cock past your puckered ring and into your bowels. You cry out at the sudden penetration while the lustful beast rumbles lustfully. She fucks you with animalistic zeal, her pointed cock drilling into you over and over again. Your [bodytype of Player] body can't help but respond to this treatment and soon you're panting and moaning beneath the large taur. Her hot thick tiger-like cock fills your passage with its amazing presences, its soft barbs tugging at your insides with every movement and making you writhe and beg underneath the beast like a cat in heat.";
		say "     Soon you find yourself moaning underneath the tigertaur as she shoots her hot feline seed into your [bodydesc of Player] body, causing you to cry out in your own orgasm at the feel of her fertile cream coating your rectal walls and filling your bowels. Even as you begin to relax and come down from the heights of pleasure, you can feel her cock stiffening within your body again, causing your eyes to widen as the tiger-like beast begins to move her hips against you again. You moan as you recall that tigers can mate for hours or even days without much rest. As she begins to move her magnificent cock into your sensitive body again, you find yourself eagerly submitting to the pleasure all over again. Her thick musk and bestial cock arousing you even faster than before as she continues to thrust herself into you again and again, causing you to orgasm underneath her as she fills you with her seed time after time, each rough coupling sending your mind spiraling ever higher with pleasure. Eventually you lose track of anything but the feel of the tiger-like body above you, and the joy of your body being penetrated again and again. Your mind is a haze of lust and hormones as the tigertaur reduces you to little more than a pleasure crazed beast underneath her. Finally though, the tigertaur seems to be satisfied as she lifts her strong body off your addled form.";
		CreatureSexAftermath "Player" receives "AssFuck" from "Tigertaur";
		if Player is male:
			say "     The beast looks over your spent form, her eyes straying to your limp cock, where it had been spilling its seed onto the ground with each orgasm. And the creature seems to murr in disappointment as she rubs her back legs together, seeming to realize that you are in no shape to attend to her own body right now. The beast seems to sigh as it goes off looking for something else to sate itself on. You are left laying there in a puddle of your own seed even as the beast's own semen leaks out of your well used passage.";
		else:
			say "     The beast looks over your spent and well-fucked form, her eyes straying to your belly, slightly distended from her seed, and your well-used ass, which is still clenching desperately for her feline cock to fill it again while her seed leaks out of it. Murring and seeming satisfied, she lifts up one of her front paws and rubs it over your stomach for a minute, before backing off and heading on her way, apparently happy at her day's work. You moan as your body slowly relaxes and your mind clears slightly of the needy haze that had taken it over, you find your own hands lowering to rub your well-filled stomach as well. [if Player is mpreg_ok]You can't help but wonder if the tiger-like beast left you with several little tiger-like beasts planted deep inside you. You find yourself almost excited by that thought, your sensitive body reacting to your touch easily, as you find yourself almost hoping to have a permanent reminder of your lovely encounter with the tiger beast growing within you[else]You can't help but muse on how good it felt to be fucked wildly and repeatedly by the tiger-like beast. You find yourself excited by those thoughts and a part of you longs to find more of the tiger-like beasts so you might let them have their way with you again and again[end if]...";
	else:
		say "     Rubbing herself against you, you can feel your skin tingle in pleasure wherever she touches, as she rubs her furred form over yours. The tigertaur seems to murr in disappointment when she finds you don't seem to have a proper opening for her to play with, this doesn't stop her for long though, as she moves her body over yours, her scent filling your head you with its spicy arousing musk. Before you can do anything about your new position, the tigertaur slowly lowers herself onto your erect shaft, her tight loins gripping your cock even as her soft feline breasts rub up against your body. You moan as her hot pussy rubs over your cock, her excited juices coating it and dripping down over your cock from where your bodies join. The tigertaur takes advantage of your open mouth, as one of her hands reaches down and guides one of her soft pert breasts into it, the taste of her body sending a thrill of pleasure through your form as she begins to massage your cock with her short movements on top of you. You groan as your cock moves inside her, and find yourself licking and nibbling at the breast in your mouth, needing more of her wonderful flavor on your tongue even as your body succumbs to her attentions.";
		say "     Soon you feel a soft trickle of milk fill your mouth as you tease and work her breasts, its strong, rich taste seemingly laced with aphrodisiacs as it sets your head spinning with need, and you thrust up to meet her feline hips. Before you know it you have climaxed within her wonderful folds, and her body shudders over you in orgasm as you feel her own cock shooting its own seed all over your body, she doesn't stop there, but continues to tease and work your body, and perhaps due to the effects of her milk, you are erect again and moving within her sooner than you ever thought possible. You lose track of time as your world narrows to the wonderful breasts in front of you, and the wonderful feeling of shooting your seed deep in her body, eventually though your body just can't take anymore, and you collapse helplessly. The tigertaur seems rather disappointed when she realizes you are completely spent, but rubs her belly with one of her forepaws happily at all the fertile sperm you managed to shoot in her so far. Rising up on all four legs, she then trots back the way she came, leaving you lying there nearly covered in her seed and with the taste of her addictive milk in your mouth.";
		CreatureSexAftermath "Tigertaur" receives "PussyFuck" from "Player";
	infect "Tigertaur";

to say Tigertaur Loses:
	project the Figure of Tigertaur_hard_icon;
	say "     The tigertaur growls in disbelief as you gain the upper hand, and she shrinks away from you for a few steps before whirling around to flee. The tussle has taken its toll on her through, and she tangles herself up in her own four legs, stumbling and falling down. You're on her in an eyeblink, with this being a perfect opportunity to savor the bounty of your might, if you dare. She's still a claw-bearing pretty big cat, so there's always danger to go along with what lust or thirst might make you do...";
	say "     [bold type]What do you want to do with the tigertaur?[roman type][line break]";
	let Tigertaur_Initial_Choices be a list of text;
	add "Pull up that tail and fuck her pussy. You earned the right!" to Tigertaur_Initial_Choices;
	add "Pull up that tail and fuck her ass. You earned the right!" to Tigertaur_Initial_Choices;
	if Player is female:
		add "Roll her on her back and mount that shaft with your pussy." to Tigertaur_Initial_Choices;
	if Player is male:
		add "Roll her on her back and mount that shaft with your ass." to Tigertaur_Initial_Choices;
	add "Those six breasts look pretty enticing for a thirsty survivor..." to Tigertaur_Initial_Choices;
	add "Just let her go." to Tigertaur_Initial_Choices;
	let Tigertaur_Initial_Choice be what the player chooses from Tigertaur_Initial_Choices;
	if Tigertaur_Initial_Choice is:
		-- "Roll her on her back and mount that shaft with your pussy.":
			LineBreak;
			say "     You seize the opportunity, asserting your dominance over the fallen tigertaur. Pinning her struggling, furred form beneath your weight, your eyes fix on her large, erect feline cock, twitching erratically beneath her belly, leaking pre-cum onto the dirt. A low rumble of anticipation vibrates through her powerful body, but your defeated opponent makes no effort to stop you. The horny kitty's eyes, wide with eager submission, fix on yours as she stares back over her shoulder. The powerful hind legs, braced against the ground, tense, ready to push back, not in defiance, but in readiness to aid your conquest. Your hand reaches down, stroking the length of her large, engorged cock, the thick, barbed shaft surprisingly warm against your palm, the sensation immediately welcomed by the tigertaur. Her struggles cease entirely, replaced by full compliance. Your defeated kitty watches this, a clear fascination in her gaze as she feels your touch on her proud, stiff member, eager for what comes next.";
			say "     You slide your hand up and down, slicking the feline cock with her own juices, the surface feeling surprisingly rough against your palm, yet she makes no objection to the preparation. With a firm grip on one of her powerful hind legs, you begin to roll her over. The tigertaur, initially offering a slight resistance, quickly yields, her powerful body twisting, four legs tangling for a moment before she is fully splayed out on her back, her massive form stretched to its full length on the grimy earth. She lies completely exposed, her powerful body vulnerable, the large feline cock jutting proudly upwards, glistening with pre-cum. Her multiple rows of breasts rise and fall with rapid breaths, a clear testament to her escalating arousal. You lean over her, preparing your pussy by spreading your own wetness, then ready your body for the immense penetration. The horny kitty watches, a new kind of avid desire in her eyes, a mixture of raw hunger and excited anticipation for your ritual.";
			WaitLineBreak;
			say "     Her breath catches in her throat as you straddle her. Aligning your slick pussy with her awaiting cock, the warmth of her belly fur becomes a tantalizing sensation against your inner thighs. Slowly, deliberately, you begin to lower yourself onto her, impaling yourself on her massive, barbed shaft. A sharp gasp tears from the tigertaur's throat, quickly followed by a guttural moan that vibrates through her entire powerful frame, rattling her very bones as your pussy slides down, fully enveloping her large feline cock. The pressure exquisite as you fully impale yourself, her barbed shaft stretching your receptive pussy to its limits. You sink down, the warmth of her belly fur a luxurious friction against your inner thighs as you settle onto her. Your defeated opponent's legs instinctively push back against your sides, pulling you deeper, securing your conquest. You take a perverse pleasure in the contrast - the magnificent beast, now utterly subdued beneath you, her proud tigress form yielding, writhing, and begging for more with every desperate movement, fully consumed by the primal urges you have unleashed.";
			say "     You begin to ride the horny kitty, your hips bucking, grinding your pussy against her furred belly, reveling in the friction and the rhythmic pounding of her hips instinctively thrusting into you. The claimed feline's growls morph into breathless whimpers as you drive yourself down onto her. Her eyes glaze with escalating pleasure, her mouth slightly ajar, panting. Multiple rows of breasts jiggle violently with each powerful impact of your hips against her furry abdomen. Your pussy grips her cock with a relentless, milking suction, squeezing every inch of her shaft, building the pressure and stimulating your clit with every movement. Her tail twitches, then starts to wag slowly, unconsciously, a clear sign of the profound pleasure she experiences, pushing the defeated opponent closer to the brink.";
			WaitLineBreak;
			say "     Relentlessly, you continue to ride the tigertaur, plunging yourself deep onto her hot, slick cock, feeling the warm rod inside yourself, relentlessly stimulating your g-spot while you feel her soft fur against your clit. Powerful core muscles contract, milking her shaft with savage intensity, stealing the air from the tigertaur's lungs with each exquisite thrust. The tigress's head lolls back, her tongue hanging from her mouth, eyes now almost completely rolled back, lost in the overwhelming sensation. A low, continuous growl escapes her, deepening with each stroke as her body tenses, powerful muscles coiling, twitching. Within her, the pressure builds to an unbearable degree, her body arching off the ground, straining against the primal force you wield. Her massive feline cock erupts, blasting a surprisingly voluminous load deep inside you, a thick, satisfying creampie filling your womb completely, a testament to her eagerness. The tigertaur arches her back, a raw, triumphant roar tearing from her throat as a final, powerful release washes through her in a full-body spasm, her claws digging deeply into the dirt, tearing at the earth, utterly spent.";
			say "     Your own orgasm builds, a roaring inferno, and with a final, thunderous series of powerful grinds, you climax, emptying yourself with a scream of pleasure all over her warm, belly fur, soaking her in your femcum. A low growl rumbles in her chest as your pussy slides off her shaft with a wet schlorp, leaving her a trembling mass of sticky fur and exhausted muscle on the ground. She lies there, breathing heavily, her multiple rows of breasts still heaving. Her eyes, hazy with spent pleasure, slowly regain some of their earlier defiance, locking onto yours with a look that is both deeply satisfied and faintly annoyed at her own weakness, at the ease with which you dominated her primal urges. With an annoyed chuff, the lustful feline gets back on her feet, then dashes off, dropping from sight in the overgrown space of the zoo in moments.";
			CreatureSexAftermath "Player" receives "PussyFuck" from "Tigertaur";
		-- "Roll her on her back and mount that shaft with your ass.":
			LineBreak;
			say "     You seize the opportunity, asserting your dominance. Pinning the tigertaur's struggling, furred form beneath your weight, your eyes fix on her large, erect feline cock, twitching erratically beneath her belly, leaking pre-cum onto the dirt. A surprised growl rumbles in her chest, a low, guttural protest vibrating through her powerful body, but your defeated opponent makes no real effort to stop you. The horny kitty's eyes, wide with a mix of defiance and dawning submission, fix on yours as she stares back over her shoulder. The powerful hind legs, braced against the ground, tense, ready to spring, but a low growl from you keeps her subdued, reminding her of your temporary mastery. Your hand reaches down, stroking the length of her large, engorged cock, the thick, barbed shaft surprisingly warm against your palm, the sensation seeming to pacify her, her struggles ceasing entirely. Your defeated kitty watches this, a clear fascination in her gaze as she feels your touch on her proud, stiff member.";
			say "     You slide your hand up and down, slicking the feline cock with her own juices, the surface feeling surprisingly rough against your palm, yet she makes no objection to the preparation she's never truly needed before. With a firm grip on one of her powerful hind legs, you begin to roll her over. The tigertaur, initially resistant, quickly yields, her powerful body twisting, four legs tangling for a moment before she is fully splayed out on her back, her massive form stretched to its full length on the grimy earth. She lies completely exposed, her powerful body vulnerable, her large feline cock jutting proudly upwards, glistening with pre-cum. Her multiple rows of breasts rise and fall with rapid breaths, a clear testament to her escalating arousal. You lean over her, spitting into your hand to gather extra lubricant, then spread the fluid over her erect shaft and your anus, preparing them for your pleasure. The horny kitty watches, a new kind of bewildered awe in her eyes, a mixture of raw desire and faint confusion at your ritual.";
			WaitLineBreak;
			say "     Her breath catches in her throat as you straddle her. Aligning your slick ass with her awaiting cock, the warmth of her belly fur becomes a tantalizing sensation against your skin. Slowly, deliberately, you begin to lower yourself onto her, impaling yourself on her massive, barbed shaft. A sharp gasp tears from the tigertaur's throat, quickly followed by a guttural moan that vibrates through her entire powerful frame, rattling her very bones as your body slides down, fully enveloping her large feline cock. The pressure exquisite as you fully impale yourself, her barbed shaft stretching your receptive ass to its limits. You sink down, the warmth of her belly fur a luxurious friction against your inner thighs as you settle onto her. Your defeated opponent's legs instinctively push back against your sides, pulling you deeper, securing your conquest. You take a perverse pleasure in the contrast - the magnificent beast, now utterly subdued beneath you, her proud tigress form yielding, writhing, and begging for more with every desperate movement, fully consumed by the primal urges you have unleashed.";
			say "     You begin to ride the horny kitty, your hips bucking, grinding your own cock against her furred belly, reveling in the friction and the rhythmic pounding. The claimed feline's growls morph into breathless whimpers as you drive yourself down onto her. Her eyes glaze with escalating pleasure, her mouth slightly ajar, panting. Multiple rows of breasts jiggle violently with each powerful impact of your hips against her furry abdomen. Your ass grips her cock with a relentless, milking suction, squeezing every inch of her shaft, building the pressure in her testicles. Her tail twitches, then starts to wag slowly, unconsciously, a clear sign of the profound pleasure warring with her inherent defiance, pushing the defeated opponent closer to the brink.";
			WaitLineBreak;
			say "     Relentlessly, you continue to ride the tigertaur, plunging yourself deep onto her hot, slick cock, feeling the warm rod inside yourself, stimulating your prostate so very good. Powerful core muscles contract, milking her shaft with savage intensity, stealing the air from the tigertaur's lungs with each throb of your vice-like passage. The tigress's head lolls back, her tongue hanging from her mouth, eyes now almost completely rolled back, lost in the overwhelming sensation. A low, continuous growl escapes her, deepening with each stroke as her body tenses, powerful muscles coiling, twitching. Within her, the pressure builds to an unbearable degree, her body arching off the ground, straining against the primal force you wield. Your own orgasm builds, a roaring inferno, and with a final, thunderous series of powerful grinds, you climax, emptying yourself all over her warm, belly fur.";
			say "     Her massive feline cock erupts, blasting a surprisingly voluminous load deep inside you, a thick, satisfying creampie filling you completely. The tigertaur arches her back, a raw, triumphant roar tearing from her throat as a final, powerful release washes through her in a full-body spasm, her claws digging deeply into the dirt, tearing at the earth, utterly spent. A low growl rumbles in her chest as your ass slides off her shaft with a wet schlorp, leaving her a trembling mass of sticky fur and exhausted muscle on the ground. She lies there, breathing heavily, her multiple rows of breasts still heaving. Her eyes, hazy with spent pleasure, slowly regain some of their earlier defiance, locking onto yours with a look that is both deeply satisfied and faintly annoyed at her own weakness, at the ease with which you dominated her primal urges. With an annoyed chuff, the lustful feline gets back on her feet, then dashes off, dropping from sight in the overgrown space of the zoo in moments.";
			CreatureSexAftermath "Player" receives "AssFuck" from "Tigertaur";
		-- "Pull up that tail and fuck her pussy. You earned the right!":
			LineBreak;
			say "     You seize the opportunity, asserting your dominance. Pinning her struggling, furred form beneath your weight, you grab her striped tail, pulling it up and out of the way, exposing her vulnerable rear. A surprised growl rumbles in her chest, a low, guttural protest vibrating through her powerful body, but she makes no real effort to stop you, her eyes, wide with a mix of defiance and dawning submission, fixed on yours as she stares back over her shoulder. Her large feline cock, already erect, twitches erratically beneath her belly, leaking a few drops of pre-cum onto the dirt, a testament to her inherent lust, but your focus is elsewhere. You maneuver, positioning yourself at her rear, aligning your throbbing cock with the swollen, pink slit of her pussy, nestled low on her tigress body, underneath her anus. The musky scent of her, a heady mix of raw animal and potent female heat, fills your nostrils, pulling you deeper into the primal scene.";
			say "     With a determined push, you drive into her, burying yourself deep within her tight, hot pussy. A sharp gasp tears from her throat, quickly followed by a guttural moan that vibrates through her entire powerful frame, rattling her very bones. Her large feline cock, now fully free, twitches wildly against her belly, releasing a steady stream of slick pre-cum. The powerful hind legs, braced against the ground, tense and then instinctively push back, grinding her pussy against your invading [cock of Player] shaft, securing your conquest. The magnificent beast, a creature of immense power and untamed grace, now utterly subdued beneath you, her proud tigress form yielding, writhing, and begging for more with every desperate movement, fully consumed by the primal urges you have unleashed.";
			WaitLineBreak;
			say "     Pounding into the tigertaur with unyielding force, a primal rhythm takes furious hold, making her entire body convulse against the ground. The feline's growls morph into breathless whimpers. Her torso twisting, the claimed feline cranes her head, looking over her shoulder at you, eyes glazed with escalating pleasure, her mouth slightly ajar, panting. Multiple rows of breasts jiggle violently with each powerful impact of your hips against her rump. The tigress's pussy, impossibly tight and slick, grips your cock with a relentless, milking suction, squeezing every inch of your shaft, building the pressure, stretching her sensitive depths. Her tail twitches, then starts to wag slowly, unconsciously, a clear sign of the profound pleasure warring with her inherent defiance, pushing the defeated opponent closer to the brink.";
			say "     Relentlessly, you continue to drive into the tigertaur, plunging deep into her hot, slick depths, feeling the unwavering grip of her pussy around your cock. Powerful core muscles contract, milking your shaft with savage intensity, stealing the air from your lungs with each exquisite thrust. The tigress's head lolls back, her tongue hanging from her mouth, eyes now almost completely rolled back, lost in the overwhelming sensation. A low, continuous growl escapes her, deepening with each stroke as her body tenses, powerful muscles coiling, twitching. Within her, the pressure builds to an unbearable degree, her body arching off the ground, straining against the primal force you wield. Her pussy tightens around you, milking, squeezing, preparing for the inevitable eruption.";
			WaitLineBreak;
			say "     With a final, thunderous series of powerful thrusts, you blast your hot load deep inside her, filling her completely with a thick, satisfying creampie, pushing her past her breaking point. The tigertaur arches her back, a raw, triumphant roar tearing from her throat as a final, powerful release, washes through her in a full-body spasm, her claws digging deeply into the dirt, tearing at the earth, utterly spent. A low growl rumbles in her chest as your cock slides free with a wet schlorp from her thoroughly fucked pussy, leaving her a trembling mass of fur and muscle on the ground. She lies there, breathing heavily, her multiple rows of breasts still heaving, her large feline cock still twitching out its own last spurts of cum, adding to a puddle on the ground, a clear testament to the overwhelming pleasure and exhaustion that now claim her. Her eyes, hazy with spent pleasure, slowly regain some of their earlier defiance, locking onto yours with a look that is both deeply satisfied and faintly annoyed at her own weakness, at the ease with which you dominated her primal urges.";
			say "     You watch her, savoring the moment, the scent of her arousal and your cum thick in the air. The tigertaur slowly pushes herself up, her powerful limbs shaking slightly, the struggle against her own unleashed desires evident in every movement. She casts a final, piercing glance your way, a mix of grudging respect and lingering irritation in her gaze. There's a subtle tremor in her striped tail, a last twitch of the pleasure you so easily commanded from her, before she offers a quick, defiant flick of her ear, acknowledging your temporary victory. With an annoyed chuff, the lustful feline gets back on her feet, her powerful quadrupedal form regaining its usual grace. Without another look, she dashes off, disappearing from sight in the overgrown spaces of the zoo in moments, leaving you alone amidst the lingering scent of her defeat and pleasure, a clear victory claimed.";
			CreatureSexAftermath "Tigertaur" receives "PussyFuck" from "Player";
		-- "Pull up that tail and fuck her ass. You earned the right!":
			LineBreak;
			say "     You seize the opportunity, asserting your dominance. Pinning the tigertaur's struggling, furred form beneath your weight, you grab her striped tail, pulling it up and out of the way, exposing her vulnerable rear. A surprised growl rumbles in her chest, a low, guttural protest vibrating through her powerful body, but your defeated opponent makes no real effort to stop you. Her eyes, wide with a mix of defiance and dawning submission, fix on yours as she stares back over her shoulder. Her large feline cock, already erect, twitches erratically beneath her belly, leaking a few drops of pre-cum onto the dirt, a testament to her inherent lust, but your focus is elsewhere. Maneuvering, you position yourself at her rear, the tight, dark pucker of her anus now prominently displayed, a tightly wrinkled star clearly unfamiliar for your intended use. The musky scent of her, a heady mix of raw animal and potent female heat, fills your nostrils, pulling you deeper into the primal scene.";
			say "     Leaning in, you spit into your hand, the warm, slick saliva coating your palm, then carefully lubricate your throbbing cock. Your defeated opponent watches this preparation with wide, curious eyes, a low whine escaping her. The tigertaur's intense gaze suggests a deep fascination with your actions, her head twisting to better observe the process. You then line up your slick shaft with her tight pucker, pressing the head against the sphincter. A sharp gasp tears from her throat, quickly followed by a guttural moan that vibrates through her powerful frame, rattling her very bones as she feels the unexpected pressure. You grab her tail firmly, like a leash or rudder, giving it a subtle tug, a silent reminder that she is not in control here, that her fate is entirely in your hands. Her resistance, a faint tremor in her powerful legs, ebbs off, replaced by a tense anticipation.";
			WaitLineBreak;
			say "     With a determined push, you drive into her, burying yourself deep within her tight, unyielding ass. A sharp yelp tears from the tigertaur's throat, quickly followed by a primal moan that vibrates through her powerful frame as the penetration stretches her, far beyond her usual limits. Plunging deep inside, your [Cock of Player] shaft finds the sensitive prostate, rubbing against it and driving her wild. The powerful hind legs, braced against the ground, tense and then instinctively push back, grinding her anus against your invading shaft, securing your conquest. The magnificent beast, now utterly subdued beneath you, feels your deep thrusts, her proud tigress form yielding, writhing, and begging for more with every desperate movement, fully consumed by the primal urges you have unleashed. Her large feline cock twitches wildly against her belly, leaking more pre-cum.";
			say "     Pounding into the horny kitty with unyielding force, a primal rhythm takes furious hold, making her entire body convulse against the ground. The claimed feline's growls morph into breathless whimpers, her head twisting, looking over her shoulder at you, eyes glazed with escalating pleasure, her mouth slightly ajar, panting. Multiple rows of breasts jiggle violently with each powerful impact of your hips against her rump. The tigress's ass, unbelievably tight and slick, grips your cock with a relentless, milking suction, squeezing every inch of your shaft, building the pressure against her prostate, stretching her sensitive depths. Her tail, still firmly in your grasp, twitches, then starts to wag slowly, unconsciously, a clear sign of the profound pleasure warring with her inherent defiance, pushing the defeated opponent closer to the brink.";
			WaitLineBreak;
			say "     Relentlessly, you continue to drive into the tigertaur, plunging deep into her hot, slick depths, feeling the unwavering grip of her ass around your cock, relentlessly stimulating her prostate. Powerful core muscles contract, milking your shaft with savage intensity, stealing the air from your lungs with each exquisite thrust. The tigress's head lolls back, her tongue hanging from her mouth, eyes now almost completely rolled back, lost in the overwhelming sensation. A low, continuous growl escapes her, deepening with each stroke as her body tenses, powerful muscles coiling, twitching. Within her, the pressure builds to an unbearable degree, her body arching off the ground, straining against the primal force you wield. Her anal muscles tighten around you, milking, squeezing, preparing for the inevitable eruption, as her massive feline cock continues to twitch and leak.";
			say "     With a final, thunderous series of powerful thrusts, you blast your hot load deep inside the tigertaur, filling her completely with a thick, satisfying creampie, pushing her past her breaking point. The tigertaur arches her back, a raw, triumphant roar tearing from her throat as a final, powerful release washes through her in a full-body spasm, her claws digging deeply into the dirt, tearing at the earth, utterly spent. A low growl rumbles in her chest as your cock slides free with a wet schlorp from her thoroughly fucked ass, leaving her a trembling mass of fur and muscle on the ground. She lies there, breathing heavily, her multiple rows of breasts still heaving, her large feline cock still twitching out its own last spurts of cum, adding to a puddle on the ground, a clear testament to the overwhelming pleasure and exhaustion that now claim her. Her eyes, hazy with spent pleasure, slowly regain some of their earlier defiance, locking onto yours with a look that is both deeply satisfied and faintly annoyed at her own weakness, at the ease with which you dominated her primal urges. With an annoyed chuff, the lustful feline gets back on her feet, then dashes off, dropping from sight in the overgrown space of the zoo in moments.";
			CreatureSexAftermath "Tigertaur" receives "AssFuck" from "Player";
		-- "Those six breasts look pretty enticing for a thirsty survivor...":
			LineBreak;
			say "     Feeling bold, you quickly grab the stripped feline by the tail, halting her from running off. Muscle tensing in aggravation, you watch nervously as the other swivels her head around to glare at you warningly. Not wanting to get into another fight with the predatory feline, you reach a hand up to paw at the tigertaur's full breast to show her your intention. Slowly the feline's glare shifts into a mask of [one of]confusion[or]bemusement[or]understanding[or]concern[at random] before it slips its tail from your grasp and turns it's tauric form towards you giving you complete access to her upper torso. [one of]Gently you[or]Cautiously you[or]Eagerly you[at random] continue to palm the same breast you had been playing with before, tugging at the nipple hidden beneath the tawny fur to help the feline's milk within flow outward, before you reach out to nuzzle your [FaceSpeciesName of Player in lower case] nose into the tiger herm's [one of]firm[or]muscular[or]deceptively soft[at random] abdomen.";
			WaitLineBreak;
			say "     A calm, yet demanding paw reaches out to grab the back of your head, forcing your face to ride up into the tigertaur's buxom chest. Without hesitation you latch your lips around her firm teat to begin nursing from the feline, your [FaceSpeciesName of Player in lower case] tongue stroking along the length of the firm mound of flesh to help the milk flow deep into your throat. A rumbling growl rents the air as the tigertaur pulls your head closer into her chest as the sensations of having her milk filled breast empty out into your mouth makes her tail lash wildly behind her. Stroking the feline's tit while at the same time nuzzling into her chest, you make a soft hum into the back of your throat which cause the muscles of the tigertaur's breast to dribble more and more creamy tiger milk down into your belly.";
			WaitLineBreak;
			say "     It doesn't take long for you to get your fill, the fatty fluids filling you up in a [one of]relaxing[or]disarming[or]mind numbing[at random] sort of way, and you have to force yourself to step away from the other before you can get [italic type]too[roman type] comfortable. Pulling away from the tigertaur, you watch as the herm gives you a pleased chuff-like growl before she turns to bound off deeper into the zoo.";
			PlayerDrink 12;
			PlayerEat 3;
			SanLoss 5;
			if "Iron Stomach" is not listed in feats of Player, infect "tigertaur";
			CreatureSexAftermath "Tigertaur" receives "Nursing" from "Player";
		-- "Just let her go":
			LineBreak;
			say "     With an annoyed chuff, the lustful feline gets back on her feet, then dashes off, dropping from sight in the overgrown space of the zoo in moments.";

Table of CombatPrep (continued)
name(text)	PrepFunction(text)
"Tigertaur"	"[PrepCombat_Tigertaur]"

to say PrepCombat_Tigertaur:
	setmongender 5;
	if CreatureArtworkOverride is false: [in case this creature is called up in an event and other artwork needs to be used]
		project the Figure of Tigertaur_soft_icon;

Section 2 - Creature Insertion

to say TigertaurDesc:
	say "     You find yourself face to face with a rather impressive figure, a sleek humanoid torso topped with a tiger's face, sits atop the lower body of a strong four-legged tiger. You find your eyes drawn to the several rows of breasts trailing down her body, only to have your eyes catch on her large feline cock where it hangs underneath her tiger-like paws, erect and obviously eager for action as the tigertaur moves forward with lust in her eyes.";

Table of CombatPrep (continued)
name(text)	PrepFunction(text)
"Tigertaur"	"[PrepCombat_Tigertaur]"

to say PrepCombat_Tigertaur:
	say "";

Table of Random Critters (continued)
NewTypeInfection (truth state)	Species Name	Name	Enemy Title	Enemy Name	Enemy Type	Attack	Defeated	Victory	Desc	Face	Body	Skin	Tail	Cock	Face Change	Body Change	Skin Change	Ass Change	Cock Change	str	dex	sta	per	int	cha	sex	HP	lev	wdam	area	Cock Count	Cock Length	Ball Size	Nipple Count	Breast Size	Male Breast Size	Cunt Count	Cunt Depth	Cunt Tightness	SeductionImmune	Libido	Loot	Lootchance	TrophyFunction	MilkItem	CumItem	Scale (number)	Body Descriptor (text)	Type (text)	Magic (truth state)	Resbypass (truth state)	non-infectious (truth state)	Cross-Infection (text)	DayCycle	Altcombat (text)	BannedStatus (truth state)
--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--;

When Play begins:
	Choose a blank row from Table of Random Critters;
	now NewTypeInfection entry is false;
	now Species Name entry is "Tigertaur"; [ Name of the overall species of the infection, used so a "male x" and "female x" have "pureblood X" children. ]
	add "Tigertaur" to infections of FelineList;
	add "Tigertaur" to infections of FurryList;
	add "Tigertaur" to infections of MaleList;
	add "Tigertaur" to infections of BarbedCockList;
	add "Tigertaur" to infections of SheathedCockList;
	add "Tigertaur" to infections of TaurList;
	add "Tigertaur" to infections of TailList;
	now Name entry is "Tigertaur";
	now enemy title entry is "Tigertaur"; [ Name of the encountered creature at combat start - Example: "You run into a giant collie." instead of using "Smooth Collie Shemale" infection name. ]
	now enemy Name entry is ""; [ Specific name of unique enemy. ]
	now enemy type entry is 0; [ 0 = non unique enemy; 1 = unique (unknown name); 2 = unique (known name) | Used to disqualify unique enemies from Vore/UB and showing the enemy name in encounters. ]
	now attack entry is "[one of]She leaps forward, slamming her large body into you roughly[or]Lashing out with one of her large tiger forepaws, she her claws rake over your body.[or]The tiger-like taur moans and rubs her hands along her body, a strong scent of need and arousal filling the air.[or]Much to your surprise, she rubs her body against yours in excitement instead of attacking![or]Dancing forward on her four feline legs, she lashes out with one of her clawed hands.[or]Springing forward, she slams her head forward, her tiger teeth glinting dangerously as they approach your face, only to find her muzzle lock with your mouth as she kisses you passionately![or]She charges forward, her hands and paws roaming excitedly over your body as she tries to find a way to pin you down.[at random]";
	now defeated entry is "[Tigertaur Loses]";
	now victory entry is "[Tigertaur Wins]";
	now desc entry is "[TigertaurDesc]";
	now face entry is "sleek tiger-like head, your muzzle and feline countenance almost completely unrecognizable from that of a regular tiger's"; [ Face description, format as "Your face is [Face of Player]." ]
	now body entry is "lean and strong, with a relatively humanlike torso resting atop your strong furred tiger lower body, your four tiger paws easily gripping the ground as you prowl along"; [ Body Description, format as "Your Body is [Body of Player]." ]
	now skin entry is "[one of]tiger striped[or]tiger furred[or]soft furred[or]orange and black striped[at random]"; [ Skin Description, format as "Looking at yourself, your body is covered in [Skin of Player] skin." ]
	now tail entry is "You have a long, tiger-like tail extending from just above your rear, lashing back and forth in excitement and need with every step you take."; [ Tail description, write a whole Sentence or leave blank. ]
	now cock entry is "[one of]feline[or]Tiger[or]barbed[or]tigertaur[at random]"; [ Cock Description, format as you have a 'size' (your text) cock]
	now face change entry is "a pleasurable stretching sensation comes over your face, as your teeth begin to sharpen and length, and your jaw extends outward the muscles rearranging themselves into the powerful configuration of a tiger. Your nose twitches as it merges with your muzzle, new scents of sex and prey exploding into your head, as your eyes shift and become those of a great hunting cat. Finally your ears finishing shifting to their new place on top of your head having pulled and shaped themselves into proper tiger ears, as your face finishes up its changes into a proper tiger face"; [ Face change text, format as "Your face feels funny as [face change entry]." ]
	now body change entry is "your muscles tighten underneath your skin, twisting and cording and arranging themselves in a more feline manner, claws bursting through your fingertips as your hands change slightly. You stumble and collapse to the ground as your legs bend and shift underneath you, your midsection lengthening as your legs shift to become full tiger legs, and two new limbs begin to push themselves out of your torso. You groan in pleasure as your body continues to rearrange itself, before finally lifting yourself back up on your four new tiger paws, finding it seems easy and almost natural to walk around on all four tiger legs, while holding your slightly changed torso erect"; [ Body change text, format as "Your body feels funny as [body change entry]." ]
	now skin change entry is "it shudders and seems to shift on its own, thick orange and black tiger fur pushing out in soft pleasurable waves of change all over your body"; [ Skin change text, format as "Your skin feels funny as [skin change entry]." ]
	now ass change entry is "your ass grows powerfully muscled, and a long sleek tiger tail erupts outwards from your tailbone, soon it is lashing around behind you in long natural motions, almost feeling as if it had always been a part of you"; [ Ass/tail change text, format as "Your ass feels funny as [ass change entry]." ]
	now cock change entry is "it shifts and tapers to a soft point, short barbs slowly sprouting along its length, the skin of your belly stretching out to pull it up close to your body, and wrapping it in a properly bestial tiger sheath"; [ cock change text. format as "Your cock feels funny as (your text)." ]
	now str entry is 22;
	now dex entry is 20;
	now sta entry is 14;
	now per entry is 18;
	now int entry is 12;
	now cha entry is 14;
	now sex entry is "Both"; [ Defines which sex the infection will try and make you. current options are 'Male' 'Female' 'Both']
	now HP entry is 80;
	now lev entry is 9; [ Level of the Monster, you get this much HP if you win, or this much HP halved if you loose ]
	now wdam entry is 12; [ Amount of Damage monster Does when attacking. ]
	now area entry is "Zoo"; [ Current options are 'Outside' and 'Mall'. Case sensitive]
	now Cock Count entry is 1; [ How many cocks will the infection try and cause if sex is 'Male' or 'Both']
	now Cock Length entry is 11; [ Length infection will make cock grow to if cocks]
	now Ball Size entry is 2; [ Size of balls ]
	now Nipple Count entry is 6; [ Number of nipples infection will give you (males have nipples too) ]
	now Breast Size entry is 3; [cup size as number, counting Flat Pecs = 0, A = 1, B = 2, ...]
	now Male Breast Size entry is 0; [ Breast size for if Sex="Male", usually zero. ]
	now Cunt Count entry is 1; [ if sex = "Female or both", indicates the number of female sexes infection will grant you.]
	now Cunt Depth entry is 12;
	now Cunt Tightness entry is 4;
	now SeductionImmune entry is false;
	now libido entry is 70; [ As part of infection, the Player will be gradually moved towards this value; also used for the creature's seduce defense as a penalty ]
	now loot entry is "lucky horseshoe"; [ Loot monster drops, usually infective with the monster's _own_ strain (for example if there is a Cross-Infection from sex)]
	now lootchance entry is 0; [ Chance of loot dropping 0-100 ]
	now MilkItem entry is "tigertaur milk"; [ Item to be given to the player if they have this infection and milk themselves. ]
	now CumItem entry is "tigertaur cum"; [ Item to be given to the player if they have this infection and jerk off. ]
	now TrophyFunction entry is "-"; [ Function to generate a list of optional loot items, of which the player can choose one after victory. ]
	now scale entry is 4; [ Number 1-5, approx size/height of infected PC body: 1=tiny, 3=avg, 5=huge ]
	now body descriptor entry is "[one of]animalistic[or]exotic[or]tauric[at random]";
	now type entry is "[one of]feline[or]tigrine[or]tigertaur[at random]";
	now magic entry is false;
	now resbypass entry is false; [ Bypasses Researcher bonus? true/false (almost invariably false) ]
	now non-infectious entry is false;
	now Cross-Infection entry is ""; [ Infection that this infection will give the player when they lose; can be left empty if they infect with the monster's own strain. ]
	now DayCycle entry is 0; [ 0 = Up at all times; 1 = Diurnal (day encounters only); 2 = Nocturnal (night encounters only);]
	now altcombat entry is "ftaurpounce"; [ Row used to designate any special combat features, "default" for standard combat. ]
	now BannedStatus entry is false;

[
Table of New Infection Parts (continued)
Species Name	Name	Body Weight	Body Definition	Androginity	Head Change	Head Description	Head Adjective	Head Skin Adjective	Head Color	Head Adornments	Hair Length	Hair Shape	Hair Color	Hair Style	Beard Style	Body Hair Length	Eye Color	Eye Adjective	Mouth Length	Mouth Circumference	Tongue Adjective	Tongue Color	Tongue Length	Torso Change	Torso Description	Torso Adjective	Torso Skin Adjective	Torso Adornments	Torso Color	Torso Pattern	Breast Adjective	Breast Size	Male Breast Size	Nipple Count	Nipple Color	Nipple Shape	Back Change	Back Adornments	Back Skin Adjective	Back Color	Arms Change	Arms Description	Arms Skin Adjective	Arms Color	Locomotion	Legs Change	Legs Description	Legs Skin Adjective	Legs Color	Ass Change	Ass Description	Ass Skin Adjective	Ass Color	Ass Width	Tail Change	Tail Description	tail skin adjective	Tail Color	Asshole Depth	Asshole Tightness	Asshole Color	Cock Change	Cock Description	Cock Adjective	Cock Color	Cock Count	Cock Girth	Cock Length	Ball Description	Ball Count	Ball Size	Cunt Change	Cunt Description	Cunt Adjective	Cunt Color	Cunt Count	Cunt Depth	Cunt Tightness	Clit Size
--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--;

When Play begins:
	Choose a blank row from Table of New Infection Parts;
	now Species Name entry is ""; [ Name of the overall species of the infection, used so a "male x" and "female x" have "pureblood X" children. ]
	now Name entry is ""; [matching infection name to Table of Random Critters]
	now Body Weight entry is 5; [scale of 1-9 for body weight, grouped into low weight (1-3), mid weight (4-6) and high weight (7-9)]
	now Body Definition entry is 5; [scale of 1-9 for body definition, grouped into low muscle (1-3), mid muscle (4-6), high muscle (7-9)]
	[Body Adjective is generated out of the body weight and body definition and can be used in scenes - one word descriptive adjective depending on weight and definition groups: low weight group: skinny/slender/lithe; mid weight group: average/fit/muscled; high weight group: pudgy/husky/jacked]
	now Androginity entry is 5; [1-9 scale of hypermasculine to hyperfeminine]
	[Gender Adjective is generated out of androginity 1-9: hypermasculine/masculine/effeminate/somewhat effeminate/androgynous/feminine butch/tomboyish/feminine/hyperfeminine]
	now Head Change entry is ""; [partial sentence that fits in: "Your head and face [one of]tingle[or]go flush[or]vibrate with odd pleasure[or]go cold[or]feel oily[at random] as [head change entry]."]
	now Head Description entry is ""; [partial sentence that fits in "Your face and head resemble that of [Head Description of Player]. You have [Eye Adjective of Player], [Eye Color of Player] eyes and an overall [Gender Adjective of Player] appearance."]
	now Head Adjective entry is ""; [one word descriptive adjective (avian/canine/...)]
	now Head Skin Adjective entry is ""; [one word descriptive adjective]
	now Head Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	now Head Adornments entry is "";[partial sentence that fits in "Before moving on from your head, you give your [Head Adornments of Player] a proud glance followed by a light caress."]
	now Hair Length entry is 2; [hair length in inches]
	now Hair Shape entry is ""; [one word shape descriptor (curly/straight/...)]
	now Hair Color entry is ""; [one word color descriptor]
	now Hair Style entry is ""; [one word style descriptor (ponytail/mohawk/buzzcut/...) to fit "On top of your head you have [Hair Length of Player] inch long, [Hair Shape of Player] [Hair Color of Player] hair in the [Hair Style of Player] style."]
	now Beard Style entry is ""; [short beard style (goatee/3-day stubble beard/porn stache/mutton chops beard/...) to go into "You have a [Hair Color of Player] [Beard Style of Player]."]
	now Body Hair Length entry is 0; [numerical value, 0-4 (no body hair/light/moderate/heavy/furry) - only set to > 0 if the infection does not have fur/scales/etc. !]
	now Eye Color entry is ""; [one word color descriptor]
	now Eye Adjective entry is ""; [one word descriptive adjective (slitted/round/...)]
	now Mouth Length entry is 3; [inches deep for face fucking; maximum possible will be double this number (when deep throating)]
	[Mouth Length Adjective is generated by a function and can be used in scenes too - "petite, shallow, average, deep, bottomless"]
	now Mouth Circumference entry is 3; [mouth circumference 1-5, see Mouth Circumference Adjective]
	[Mouth Circumference Adjective is generated by a function and can be used in scenes too - "tiny, small, normal, wide, gaping"]
	now Tongue Adjective entry is ""; [one word descriptive adjective (wide/slobbery/...)]
	now Tongue Color entry is ""; [one word color descriptor]
	now Tongue Length entry is 3; [length in inches]
	now Torso Change entry is ""; [partial sentence that fits in: "Your torso [one of]tingles[or]goes flush[or]vibrates with odd pleasure[or]goes cold[or]feels oily[at random] as [Torso Change entry]."]
	now Torso Description entry is ""; [partial sentence, fitting in "Looking down at yourself, you appear [Gender Adjective of Player] with a [Body Adjective of Player] build. Your torso is [Torso Description of Player][if Body Hair Length of Player > 1], covered in [Torso Color of Player] skin and [Body Hair Description of Player][else if Body Hair Length of Player is 1], covered in smooth, [Torso Color of Player] skin[end if]."]
	now Torso Adjective entry is ""; [one word descriptive adjective (avian/canine/...)]
	now Torso Adornments entry is ""; [(pouch/udders/...); partial sentence to fit: "You take a moment to feel your [Torso Adornments of Player]."]
	now Torso Skin Adjective entry is ""; [one word adjective (feathered/furred/scaly/...); EMPTY "" for creatures with just skin]
	now Torso Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	now Torso Pattern entry is ""; [single word color adjective for the dominant pattern of the skin/fur/feathers/scales]
	now Breast Adjective entry is ""; [adjective(s) example: round, pointy, perky, saggy, bouncy. This would serve as either a general appearance of a infections breasts or possibly something that may be effected by a item or NPC.]
	now Breast Size entry is 0; [cup size as number, counting Flat Pecs = 0, A = 1, B = 2, ...]
	now Male Breast Size entry is 0; [cup size as number, counting Flat Pecs = 0, A = 1, B = 2, ...]
	now Nipple Count entry is 2; [count of nipples]
	now Nipple Color entry is ""; [one word color descriptor]
	now Nipple Shape entry is ""; [shape example: any shape will do as long as it has a baseline with a current infection or item]
	now Back Change entry is ""; [partial sentence that fits in: "Your back [one of]tingles[or]goes flush[or]vibrates with odd pleasure[or]goes cold[or]feels oily[at random] as [Back Change entry]."]
	now Back Adornments entry is ""; [partial sentence to fit: "Your back tickles with the feeling of movement caused by [back adornments of Player]."]
	now Back Skin Adjective entry is ""; [one word adjective (feathered/furred/scaly/...); EMPTY "" for creatures with just skin]
	now Back Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	[Limbs Adjective is generated by a function and can be used in scenes too - "rail-thin, slender, sinewy, average, firm, muscular, flabby, meaty, rippling"]
	now Arms Change entry is ""; [partial sentence that fits in: "Your arms [one of]tingle[or]go flush[or]vibrate with odd pleasure[or]go cold[or]feel oily[at random] as [Arms Change entry]."]
	now Arms Description entry is ""; [partial sentence to fit: "Your [Limbs Adjective of Player] arms are [Arms Description of Player]."]
	now Arms Skin Adjective entry is ""; [one word adjective (feathered/furred/scaly/...); EMPTY "" for creatures with just skin]
	now Arms Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	now Locomotion entry is ""; [one word adjective: (bipedal/quadrupedal/octapedal/serpentine/sliding)]
	now Legs Change entry is ""; [partial sentence that fits in: "Your legs [one of]tingle[or]go flush[or]vibrate with odd pleasure[or]go cold[or]feel oily[at random] as [Legs Change entry]."]
	now Legs Description entry is ""; [partial sentence to fit: "As your inspection goes even lower, you come to the two [Body Adjective of Player] legs supporting you. They are [Legs Description of Player]."]
	now Legs Skin Adjective entry is ""; [one word adjective (feathered/furred/scaly/...); EMPTY "" for creatures with just skin]
	now Legs Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	now Ass Change entry is ""; [partial sentence that fits in: "Your ass [one of]tingles[or]goes flush[or]vibrates with odd pleasure[or]goes cold[or]feels oily[at random] as [Ass Change entry]."]
	now Ass Description entry is ""; [partial sentence to fit: "Using your hands you feel your behind enjoying the sensation of your [Ass Width Adjective of Player], [Ass Shape Adjective of Player] [Ass Description of Player]." (For players with skin, instead of the period: ", covered in [Ass Color of Player] skin and [Body Hair Description of Player]"]
	now Ass Skin Adjective entry is ""; [one word adjective (feathered/furred/scaly/...); EMPTY "" for creatures with just skin]
	now Ass Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	now Ass Width entry is 3; [ass width from 1-5]
	[Ass Width Adjective generated by function out of ass width: dainty/small/round/huge/enormous]
	[Ass Adjective generated by function out of body definition and ass width]
	now Tail Change entry is ""; [partial sentence that fits in: "Your rear [one of]tingles[or]goes flush[or]vibrates with odd pleasure[or]goes cold[or]feels oily[at random] as [if HasTail of Player is true]your existing tail is changed into a [Tail Description entry][else][Tail Change entry][end if]."]
	now Tail Description entry is ""; [partial sentence to fit: "Just below your lower back sprouts a [Tail Description of Player], which you move back and forth with glee."]
	now Tail Skin Adjective entry is ""; [one word adjective (feathered/furred/scaly/...); EMPTY "" for creatures with just skin]
	now Tail Color entry is ""; [single word color adjective for the dominant color of the skin/fur/feathers/scales]
	now Asshole Depth entry is 7; [inches deep for anal fucking]
	[Asshole Depth Adjective is generated by a function and can be used in scenes too - "petite (< 3), shallow (< 5), average (< 9), deep (< 15), bottomless (15+)"]
	now Asshole Tightness entry is 3; [asshole tightness 1-5, "extremely tight, tight, receptive, open, gaping"]
	[Asshole Tightness Adjective is generated by a function and can be used in scenes too - "extremely tight, tight, receptive, open, gaping"]
	now Asshole Color entry is ""; [one word color descriptor]
	now Cock Count entry is 0;
	now Cock Girth entry is 0; [thickness 1-5, generates the Cock Girth Adjective]
	[Cock Girth Adjective is generated by a function and can be used in scenes too: thin/slender/average/thick/monstrous]
	now Cock Length entry is 0; [length in inches]
	now Cock Adjective entry is ""; [one word adjective: avian/canine/...]
	now Cock Change entry is ""; [partial sentence that fits in: "Your cock [one of]tingles[or]goes flush[or]vibrates with odd pleasure[or]goes cold[or]feels oily[at random] as [Cock Change entry]."]
	now Cock Description entry is ""; [partial sentence to fit: "You have a [Cock Girth Adjective of Player], [Cock Length of Player]-inch-long [Cock Adjective of Player] [one of]cock[or]penis[or]shaft[or]maleness[at random] that [cock Description of Player]."]
	now Cock Color entry is ""; [one word color descriptor]
	now Ball Count entry is 0; [allowed numbers: 1 (uniball), 2 or 4]
	now Ball Size entry is 0; [size of balls 1-7: "acorn-sized", "dove egg-sized", "chicken egg-sized" "goose-egg sized", "ostrich-egg sized", "basketball-sized", "beachball-sized"]
	[Ball Size Adjective is generated by a function and can be used in scenes too]
	now Ball Description entry is ""; [partial sentence to fit: "Underneath it hangs a pair of [Ball Size Adjective of Player] [Ball Description of Player]."]
	now Cunt Count entry is 0;
	now Cunt Depth entry is 0; [penetrable length in inches; some minor stretching allowed, or more with Twisted Capacity]
	now Cunt Tightness entry is 0; [size 1-5, generates adjectives of extremely tight/tight/receptive/open/gaping]
	[Cunt Tightness Adjective is generated by a function and can be used in scenes too: extremely tight/tight/well-used/open/gaping]
	now Cunt Adjective entry is ""; [one word adjective: avian/canine/...]
	now Cunt Change entry is ""; [partial sentence that fits in: "Your pussy [one of]tingles[or]goes flush[or]vibrates with odd pleasure[or]goes cold[or]feels oily[at random] as [Cunt change entry]."]
	now Cunt Description entry is ""; [partial sentence to fit: "You have a [Cunt Tightness Adjective of Player] [one of]cunt[or]pussy[or]vagina[or]cleft[at random] that [Cunt Description of Player]."]
	now Cunt Color entry is ""; [one word color descriptor]
	now Clit Size entry is 0; [size 1-5, see Clit Size Adjective]
	[Clit Size Adjective is generated by a function and can be used in scenes: very small/small/average/large/very large]
]


Section 3 - Endings

Table of GameEndings (continued)
Name (text)	Type (text)	Subtype (text)	Ending (rule)	Priority (number)	Triggered (truth state)
"Tigertaur Infection"	"Infection"	""	Tigertaur Infection rule	1000	false

This is the Tigertaur Infection rule:
	if Player has a body of "Tigertaur":
		trigger ending "Tigertaur Infection"; [Here it states, that the ending has been played.]
		if humanity of Player < 10:
			if Player is female:
				if Player is male:
					say "     Unable to hold out against the strong desires within, you return to the zoo where you found the wonderful tigertaur that changed you in the first place. Soon you find several of the lovely looking tigertaurs, who eagerly welcome you into their happy number, mounting you and filling you with their seed, and allowing you to mount them as well. Your mind soon falls into a predatory mindset as the days pass by, filled with hunting and fucking. You eagerly hunt down the few unchanged left, and you are as happy as the rest of your kind when you find a small den full of tiger men and women who haven't been fully changed yet. You find you love spreading this most wonderful gift you have been given to new people, watching them change and embrace their new tiger-like instincts, and enjoying as they thank you vigorously for their new gifts. Eventually the military comes and attempts to retake the area, but by that point there are enough of you that you manage to overwhelm the scattered forces that make it this far into the city, their lines spread then and under assault from many other infected. The newly converted tigertaurs remind you that there is a whole world out there in need of your gifts of tiger-like power and primal pleasure, and soon you and several others slip out of the besieged city, eager to show humanity why tigers are considered the superior predator.";
				else:
					say "     Unable to hold out against the strong desires within, you return to the zoo where you found the wonderful tigertaur that changed you in the first place. Soon you find several of the lovely looking tigertaurs, who eagerly welcome you into their happy number, they seem especially pleased when they realize you are a pure female, needing their attentions. Your strong instincts cause you to tease and torment the other tigertaurs who court you though, causing them to fight amongst themselves for the right to breed you, eventually the victor emerges, and you lay your long new body down before him, eagerly accepting his dominance. Finding you lack much of the strong desire the others have to spread the infection, you spend more and more time in the zoo, with the other tigertaurs, or hunting for food and supplies. Soon you begin to show the results of your many matings with the strong victorious tigertaur, and before you know it you are raising several quickly growing cubs as well, taking care of yours as well as others cubs while they hunt for still more converts to this wonderful new way of life. While the military eventually come and are driven back, you find yourself hardly noticing, your life continuing mostly uninterrupted in the city, and each time your heat cycle comes, you find yourself happily teasing the males, your instincts allowing only the strongest and most dominant to fill your belly with their cubs, as you work hard to increase the tigertaur population in your own way.";
			else:
				say "     Finally giving in to your body's needs, your mind snaps as you prowl the city, hunting for more people or creatures to convert to your wonderful new form. You are mostly unsuccessful, until the military arrives and like the true predator you are, you manage to stalk and transform an isolated squad as they move through the city. Soon your newly transformed mates have all bowed to your dominance, and are happily carrying your seed in their new tiger wombs, and they then help you sneak through the military blockade of the city. Free of the confines of the city, you find that pickings are much better out here, and as soon as you and your newly converted mates manage to find a proper den for yourselves, you start seeing about spreading your wonderful gift and your fertile seed to the outlying towns and areas. The military eventually tries to respond to the growing explosion of tigertaurs, but by the time they realize what is happening, many of the small towns near them have succumbed, and the force outside the main infected city is now under siege itself. As more and more of the military succumb to the joy of being mostly feline, you find yourself spending more and more time ensuring your seed is spread far and wide in their new fertile wombs... and you wouldn't have it any other way...";
		else:
			say "     Rescued by the military, they are surprised by your new extremely sensitive tiger-like form, as well as your heightened senses and strength. Once they have determined that you still retain your (mostly) human mind, you find they seem eager to offer you a job. While you decline at first and try to work yourself back into the civilian world, you find your tiger-like form seems to upset most people, and your predatory instincts make it hard to settle for long. Soon you end up contacting the military again, and taking them up on the offer, and are happy you did. You take to hunting and stalking like a natural, and they offer you a perfect outlet for some of the more violent tiger-like instincts you have. You find yourself somewhat surprised when the first trooper shows up in your den after dark looking to get closer to you, though you accept eagerly. Soon you rarely spend the night alone, as word of the incredible pleasure you can give spreads, and while many of your nightly mates begin to slowly change as well, becoming even more handsome as they gain a more tigertaur like form. The military seems to be very accepting, even encouraging of this newest change, and soon you are leading a squad of military trained tigertaurs, an elite force that can travel faster, scent out your prey, and react with feline speed and power to most any situation. While several of the changed with you sometimes talk about spreading their new gifts far and wide, you remind them to be careful and cautious about such talk. After all, if there is anything life in the military has taught you, it's that one always needs to plan carefully before taking action so as not to let your targets know what you are planning...";

Tigertaur ends here.
