Zoo People by SarokCat begins here.




"Adds a large group of scattered npcs to Flexible Survival with a variety of responses and goals..."

Section 1- Brian

Briantalk is a number that varies.
LastBrianfucked is a number that varies. LastBrianfucked is usually 250.
Brianfucked is a number that varies. Brianfucked is usually 0.

Brian is a man.
The description of Brian is "You see an exceptionally large and well built Rhino man, obviously heavily infected, over by a series of cracks in the border wall. Easily eight feet tall or more, his body is covered in thick rough looking grey skin, he balances rather uneasily on his large hooflike feet, a large thick cock hangs rather limply between his legs, swaying slightly as he moves. His face is a cross between a humans and a rhinos, though it seems to lean more towards that of a beasts, especially with the large thick bony horn that protrudes from the top of his rhinolike muzzle.  He doesn[apostrophe]t seem to be the brightest of the infected, whatever he might have been before, this is emphasized by him lowering his his head so his horn is facing the wall... and charging forward at the thick concrete wall. There is a resounding impact as he staggers backwards slightly, holding his head, although you do think there are a few new cracks in the wall where he hit...";
Brian is in Border Wall.

The conversation of Brian is { "[Briantalking]" };

To say Briantalking:
	if Briantalk is 0:
		say "'Huh?' The large Rhinolike man stops staring at the wall for a minute, his eyes darting around until they finally focus on you. 'Oh hey, sorry I didn[apostrophe]t notice you there.' he says, shrugging his large shoulders before glancing back at the cracked area of the wall. 'The name is Brian, and well, as you can see I kind of ran into a Rhino just a little way out of the zoo... I well I really don[apostrophe]t want to talk about what happened with the rhino,' Brian says, his grey skin seeming to flush slightly in embarrassment for a second as he thinks about the encounter. 'You can see the end result plainly enough though,' He says as he gestures at his large rhino like form, his horn bobbing slightly as he shakes his head sadly. 'Kinda a big change, I mean I wasn[apostrophe]t a small guy to begin with, but now. Well damn right?' Brian says with amusement.  'Kinda a bit harder to think clearly though, if ya know what I mean.... but hey, at least it made me lots stronger, I should be able to get us out of here in no time now!'  The excited rhino man says, 'I mean ya know the military is watchin all the regular ways out of the city, but way I figures it, they won[apostrophe]t be watchin this part with the wall, so once I bust my way through, it[apostrophe]s clear sailering from there!' Brian says, getting even more excited by the idea, as he turns back to the wall, lowers his head, and charges it again. The impact sending him reeling back from the wall shaking his head, as he adds a couple more cracks to the already damaged area.";
		increase Briantalk by 1;
		stop the action;
	if Briantalk is 1:
		say "[one of]'One more should do it!' He says as he charges the wall[or]'I[apostrophe]ll have us out of here in no time!'[or]Brian is too busy holding his head from his last run at the wall to talk to you right now[or]'Watch this one!' He says as he charges.[or]'Woah' Brian mutters as he reels back from the wall, 'I can hear magenta..' he mutters, and you decide it might be best trying to talk to him later...[or]'Chaaaaarge!'[or]'Hey, haven[apostrophe]t I seen you somewhere before?' Brian asks blearily, his large eyes unfocused as he tries to think.[or]'For the Horde!' Brian shouts, as he leads a particularly vigorous charge at the wall. Sadly the wall seems unimpressed at this passioned cry, as it remains standing, although Brian doesn't as he lands hard on his ass.[or]'If ya are just gonna stand there and watch, ya could like do some cheering or something' Brian says as he eyes the wall again.[or]' Eat this wallface!'[or]'Dude, you don[apostrophe]t think all this headbanging is gonna hurt my brain any do yas?'[or]'Die concrete!'[or]'Woah, I can still hear my brain ringing from that last hit...'[at random]";



Instead of fucking the Brian:
	if cunts of the player is greater than 0:
		say "'[one of]Once we get out of here, I[apostrophe]ll be happy to fuck you up on that...[or]'Yeah sure,' he says absently, 'Just as soon as I finish up here.[or]Maybe when my head stops spinning...[or]That sounds nice dear[or]Fucking you up against the wall?' He says in a puzzled tone, 'That doesn[apostrophe]t sound like it would do much damage to the wall...[or]huh?[or]Fucking? Yeah I think I like fucking..[or]Are you kidding? Have you SEEN how fucking large my cock is now? I mean I could use it as a battering ram!  Hey wait, that[apostrophe]s an idea...[or]I dunno, maybe later?[at random]' Brian says as he looks at you for a minute, before refocusing his attention on the wall.";
	otherwise:
		say "'Sorry dude, but I only like the ladies, I think anyways, it can be hard to remember sometimes' Brian says in an absentminded manner as he stares at the wall."; 





Section 2- Diego


Diegotalk is a number that varies.
Coyotetricks is a number that varies.
LastDiegotricked is a number that varies. LastDiegotricked is usually 250.
Diegotricked is a number that varies. Diegotricked is usually 0.
LastDiegofucked is a number that varies. LastDiegofucked is usually 250.
Diegofucked is a number that varies. Diegofucked is usually 0.

Diego is a man.
The description of Diego is "A tan furred coyote like man is leaning up against the wall dividing the park from the rest of the city, he eyes you curiously as you approach the park, one of his ears flicking in amusement as a small smile plays across his muzzle.";
Diego is in Park Entrance.

The conversation of Diego is { "[Diegotalking]" };

To say Diegotalking:
	if Diegotalk is 0:
		say "'Hey there,' The coyote like man says with a grin, 'The name is Diego friend, and I have to say this is an unexpected surprise, haven[apostrophe]t seen too many people in these parts that haven[apostrophe]t completely given in to the pleasure.' Diego says as he readjusts his position against the wall to get a better look at you. 'Can[apostrophe]t say how long that will last of course, you look like you like to enjoy yourself as much as anyone else around here... and well, I[apostrophe]d be lying if I said this wasn[apostrophe]t the most fun i[apostrophe]ve had in my life.' He says with a grin playing across his muzzle. 'Never been so glad to have a coyote nip me in my backyard, course everything seems much more amusing to me now also, must be that whole trickster thing eh?' The coyote man says as he leans back against the wall happily, 'Guess we will see how long you last here, course if ya need any advice about the creatures in the park feel free to talk to me as much as you want, of course I can[apostrophe]t garuntee it will be GOOD advice, that whole trickster thing and all ya ken?' He says as he gives you a sly wink.  'Course ya could always just wait here until the military finally gets itself together and comes to visit, course if I felt like it I could always pull out a few coyote tricks on them, that would be sure to slow them down a bit if ya know what I mean.... I[apostrophe]d only do something like that as a favor to a fellow trickster.' Diego snickers at the thought of the poor tricked military fools.";
		increase Diegotalk by 1;
		stop the action;
	if Diegotalk is 1:
		say "'[one of]Hmm, advice eh? Hows this, always remember to brush your teeth after giving a blowjob, good hygiene is still important![or]Have you tried looking in some of the small lairs in the park? You might find something worthwhile, just be careful to wait until no ones home before you take a peek.[or]Don[apostrophe]t mess with badgers, seriously even I wouldn[apostrophe]t kid you about those dangerous buggers[or]I hear there was a Doe hanging around here at some point, if ya want her to go with ya just make sure to grab her right away.[or]Have you seen those handsome felinoids out there? Maybe you should try petting one a few times, I[apostrophe]m sure you will find it educational[or]I hear if you play with the small felines enough, a big strong alpha lion will show up.[or] If you see some wyverns fighting in the park, you should probably just watch and not interfere, not your business right?[or] Theres some weird skunks out there, but I hear the bigger beasts are lots of fun to play with.[or]Happy with your current look? than this is definitely not the place to be.[or]Don[apostrophe]t worry about any of the plants you see moving around the park, just go give them a pet they are pretty much harmless[or]have you seen any little yellow rodents in the park? Seems to me like something you might be interested in.[or]Don[apostrophe]t hit the chinchillas! Hurting something that cute has to be against some kinda law, you wouldn[apostrophe]t want to get in trouble now would you?[or]Feel like a real trickster today? Why not try tricking me and see what happens?[or]I bet you can[apostrophe]t trick old Diego here, just give it a try![at random]'";


Diegotricking is an action applying to nothing

Understand "Trick Diego" as Diegotricking.
Understand "Trick military" as Diegotricking.
Understand "Trick coyote" as Diegotricking.
Understand "delay military" as Diegotricking.

Check Diegotricking:
	If Diego is not visible, say "Who?" instead;

carry out Diegotricking:
	if lastDiegotricked - turns is less than 8:
		say "'Sorry bud, only so much time for tricking people in the day,' Diego says as he shakes his head sadly, 'Trick people too much and it just gets stale, so come back and try again later.'";
		stop the
 action;
	now lastDiegotricked is turns;
	say "Oh so you think a new little trickster like you can pull one over on me? Lets see what you got!";
	let bonus be (( the Intelligence of the player minus 10 ) divided by 2);
	let diceroll be a random number from 1 to 20;
	say "You roll 1d20([diceroll])+[bonus]: [diceroll + bonus], ";
	increase diceroll by bonus;
	if diceroll is greater than 12:
		say "'Dang that was a good one! Not quite up to my usual standards of course, but pretty damn good!' Diego says with a happy grin on his face, 'I think I might be willing to try that one out on some of their scouts, might earn ya a bit of time ya see.";
		extend game by 6;
		increase Coyotetricks by 1;
		stop the action;
	if diceroll is greater than 18:
		say "'Woah amazing!' Diego exclaims happily, 'Are you sure you aren[apostrophe]t part coyote? I mean Damn that was an impressive trick!' The coyote says as he shakes his head in admiration. 'That kinda trick will get some extra effort on my part, should take those silly military types ages to get it all sorted out!'";
		increase Coyotetricks by 2;
		extend game by 18; 
	otherwise:
		say "'You call that a trick?' Diego says derisively, snickering at your pathetic attempt, 'Now this is a trick!' He says as he swiftly whips out a trick that makes you stagger back in shock and makes you feel slightly less human.";
		decrease humanity of player by 10;


Instead of fucking the Diego:
	if lastDiegofucked - turns is less than 6:
		say "'Sorry there, the Little coyote can only come out to play every so often,' Diego says with a smirk on his muzzle.";
		stop the action;
	otherwise:
		if coyotetricks is greater then 6:
			if cocks of player is greater than 0:
				if cunts of player is greater than 0:
					say "'Hmm you look pretty good there,' Diego says with some interest,  'Sadly though, as a coyote I can already tell you have a trick hidden away next to your lovely treat.' The coyote says as he gestures to your cock.  'Nice try there. But better luck next time eh?'";
				otherwise:
					say "'Heh you want to play with a hot coyote stud like me?' Diego says with amusement, 'Hard to blame you for that I know, but I think I[apostrophe]ll pass. You may be a good trickster, but figuring out the 2 guys arrangement isn[apostrophe]t a trick I happen to be interested in.'";
			otherwise:
				say "'Well after all that tricking and flirting, how could I say no?' Diego says with an amused grin, his pawlike hand reaching out and pulling you closer to him. 'What say we have a go right here then?' The coyote trickster says with a grin, as he moves around you until he is pressing your body up against the wall he was leaning on. 'Hmm I like what I see,' Diego says with a grin as his hands roam down your body, you open your mouth to say something, only for the tricky coyote to take advantage of this fact. His furred muzzle presses up against your face as he takes advantage of your open mouth to let his tongue dart inside your mouth, tangling with your own pleasantly as his hands settle on your ass, rubbing it softly. 'Now now,' Diego pants out as he breaks the deep kiss, 'No more tricks for today, now its time for you to get your treat.' the male coyote says as his stiff cock rubs up against your crotch.[line break]";
				say "You can[apostrophe]t manage to respond to the male coyotes comments as he wastes no time in lifting your ass up slightly, giving himself a better angle as his cocktip probes at your hot passage. You find yourself moaning as your back is pressed up against the cool wall, your legs automatically wrapping around the hot coyote stud as he sinks his thick rod into your needy body.  'God you feel so good' Diego moans as he begins to thrust into you in short powerful thrusts, each one pressing you into the wall as you find your hands gripping his shoulders tightly, encouraging the strong coyote to fuck you even harder. Soon you feel the base of his cock swelling up inside you, making you moan as he continues to fuck you up against the park wall, the rough feeling of the wall and the soft feel of his fur rubbing against your [skin of player] skin erotically. Diego[apostrophe]s breath comes out in harsh panting as his thrusts speed up, his knot locking the two of you together fully as with a grunt he finally shoots his thick seed into your body. The feel of his cock exploding within you triggers your own powerful orgasm, and you find yourself throwing your head back and panting as your body shakes with pleasure. 'Oh yeah, now that was a sweet treat,' Diego mutters as the two of you stay there your bodies still locked together against the wall by his knot.  You find yourself enjoying the time in silence as his knot slowly deflates, before with a soft pop he is able to pull out of you and set you back down on your own feet.   'Come back again anytime,' The coyote stud says as he leans up against the wall again, seeming to need its support to keep himself stable after all the exertion[impregchance]";
		otherwise:
			if cocks of player is greater than 0:
				say "'Sorry bud, I don[apostrophe]t care to play with guys, maybe you should come back a bit later.'";
			otherwise:
				 say "'Hmm Maybe, I[apostrophe]ll really have to think about your offer for a while,' the coyote says, as he looks you up and down, 'Since you aren[apostrophe]t much of a trickster now are you...'.";






Section 3- Timothy


Timothytalk is a number that varies.
Timothymated is a number that varies.
LastTimothymilked is a number that varies. LastTimothymilked is usually 250.
Timothymilked is a number that varies. Timothymilked is usually 0.
LastTimothyfucked is a number that varies. LastTimothyfucked is usually 250.
Timothyfucked is a number that varies. Timothyfucked is usually 0.

Timothy is a man.
The description of Timothy is "Lying on a rather large pile of stolen cushions, is a rather striking blue furred gryphon, her attractive blue feathered wings half spread out behind her as she reclines back. The creatures talon like hands are absently rubbing its large white furred belly, obviously quite pregnant and unable to move quickly, its large breasts are slowly dribbling milk as it shifts its body slightly, giving you a good look at both its thick black cock resting up against the gryphons distended belly, and the rather large and obviously well used passage resting between the gryphons leonine thighs.  Its lionlike tail twitches where it is lying between her slightly spread legs, as the Hemaphrodite gryphon cocks her avian head to look at you, her tongue hanging out the side of her beak slightly as she pants and rubs herself a bit more. You notice a small collar with a tag hanging around her neck, the tag just reads 'Pet'";


The conversation of Timothy is { "[Timothytalking]" };

To say Timothytalking:
	if Timothytalk is 0:
		say "'Oh wow!' The gryphon says as you approach to talk to her, 'I didn[apostrophe]t expect to see someone like you here,' She says as she looks you over, moaning slightly in pleasure as she shifts her large egg filled weight to look at you better. 'Welcome to the flying city, I think they are calling it Qytat or something, to be honest I wasn[apostrophe]t paying too much attention to things like that when my mistress led me here.' Seeing your confusion she  begins to explain. 'My mistress is the one who changed me into this lovely new body,' She says as she gestures at her long leonine form, and her avian wings, and finally rubs her pregnant belly. 'And my mistress is the one who keeps me nice and full of her gryphonic offspring as well. I was once a human called Timothy, living down there in the city, before I met her while I was out camping one night. That was the best night of my life.' She says, as her flexible beak pulls back in a happy smile. 'She changed me and filled me right up with her wonderful cock, and than led me here where I could be a good little breeding pet for her, bearing her eggs again and again, and letting her drink my tasty milk and fuck me whenever she wants.' The gryphon says, obviously growing somewhat excited at the memory, and small trickles of milk begin to dampen the soft fur on her large breasts.  'She still calls me by my old name sometimes, But I love it best when she calls me her pet, or even mate or breeder, it just seems so right.' The gryphon says with a shudder as she licks her lips.  'And sometimes she even lets other gryphons come in and breed me too, to make sure that I am always nice and full of little baby gryphons. It[apostrophe]s the best life ever, you should really try it! I bet my mistress would love to make you into a happy slutty breeding gryphon too!' Timothy says as she rubs herself erotically,  'And you could stay here and talk with me and we could bear eggs for the handsome gryphon studs all day long... mmm' she moans as she orgasms just from the thought, lying back on the cushions and panting slightly as you try to decide just what to say to that.";
		increase Timothytalk by 1;
		stop the action;
	if Timothytalk is 1:
		say "'[one of]Gryphon cock is amazing, you should try it.[or]Mmm I can[apostrophe]t wait for my next breeding.[or]Are you sure you wouldn[apostrophe]t be happier as a breeding gryphon?[or]I[apostrophe]m so glad to leave all that being human stuff behind me.[or]It feels good being stuffed nice and full of eggs, you should try it[or]Not long now' she says as she pats her belly, 'And than I can get filled up again![or]Isn[apostrophe]t it nice up here?[or]My mistress doesn[apostrophe]t use my cock much, but being filled with hers is just amazing so I dont mind.[or]Would you like a little bit of milk?[or]If you keep hanging around here to talk to me, one of the other gryphons might find you in here and make you a happy little breeding toy too.... Wouldn[apostrophe]t that be wonderful?[or]Have you ever given any thought to having a tail? I love mine![or]Oh my, my breasts are going to need milking soon.[or]This infection or whatever it is is the best thing that ever happened to me.[or]I can[apostrophe]t decide which I like more,' The gryphon says speculatively, 'My wonderful new talons.' She says as she flexes her talonlike hands, than gestures down at her digigrade lion feet and paws. 'Or my handsome new paws.' She coos in happy contemplation before looking at you. 'What do you think?[or]Whew, I[apostrophe]m still me, I had a nightmare the other day where I was a human again.' She says with a shudder 'Wouldn[apostrophe]t that be horrible?[or]God I love being pregnant with lots of little gryphons![or]Who knew being an egg filled breeder could be so satisfying?[or]I bet you would look amazing pregnant with gryphons[or]I just can[apostrophe]t wait for my mistress to return and fill me with more of her lovely seed!'[or]Oh please won[apostrophe]t you take some time out and try some of my milk?[at random]'";



Timothymilking is an action applying to nothing.

Understand "Milk Timothy" as Timothymilking.
Understand "Milk Tim" as Timothymilking.
Understand "Milk gryphon" as Timothymilking.

Check Timothymilking:
	If Timothy is not visible, say "Who?" instead;

carry out Timothymilking:
	if lastTimothymilked - turns is less than 6:
		say "'Mmm sorry, that sounds like a wonderful way to pass the time' Timothy says as she rubs her large breasts slightly, before sighing, 'But I have to make sure to keep some for my mistress when she comes back, or in case the little ones come. Maybe a little bit later when I have a bit more stocked up' She says looking at you hopefully, 'You[apostrophe]ll come back than won[apostrophe]t you?'";
		stop the action;
	otherwise:
		say "'Oh that sounds wonderful!' Timothy murrs as she rubs her obviously full breasts, several small drops of milk already leaking from her nipples as you move forward to take her breasts in your hands.  Looking around somewhat you find an oddly shaped bowl near the cushions, a small curved depression built into its lip, as you bring it up to her breasts you find the depression matches the curve of her breast, the bowl obviously made for situations like this. The pregnant gryphoness moans as she holds the bowl in place while you softly massage her breasts, soft gryphon milk beginning to flow under your hands as you tease her nipples.  The air fills with the strangely arousing scent of the strange hybrids milk, as the bowl slowly beings to fill, making you lick your lips slightly as you think about what the potent milk must taste like.   You soon lose yourself in the feel of her soft furred breasts underneath your hands, running your hands over and through her fur rythmically as you coax her milk into the swiftly filling bowl.  Soon the bowl is completely full, and you are forced to set it aside, though Timothys breasts are still leaking milk onto her fur as she pants, her head thrown back in obvious pleasure at being milked.  Unable to help yourself, you find yourself lowering your head down to her damp breasts, and stretching your tongue out to take a taste of the milk straight from the source.   You and Timothy both moan as your tongue licks over her nipple, the taste of her lovely body on your tongue is just amazing, and you quickly find yourself licking and sucking slightly on her nipples, soft trickles of milk filling your mouth with its wonderful taste, before you finally sit back panting almost as much as the gryphoness is from the lovely experience. Looking down at the full bowl, you decide not to let any of that wonderful milk go to waste, and gather some of it up to take with you.";
		infect "Hermaphrodite Gryphon";
		add "gryphon milk" to invent of player;
		now lastTimothymilked is turns;



Instead of fucking the timothy:
	if lastTimothyfucked - turns is less than 6:
		say "'Sorry, I know you want to play with me again,' Timothy says as she lies back on her cushions with a satisfied look on her beak. 'But I still need some time to recover before we have some fun again, maybe you could go find another gryphon to have fun with for a bit and come back later?'";
		stop the action;
	if cocks of player is greater than 0:
		if cunts of player is greater than 0:
			if bodyname of player is "Hermaphrodite Gryphon":
				say "'Mmm a lovely little gryphon just like me!' Timothy says happily as she runs her eyes over your gryphon body, lingering for a moment at your cock before taking in your damp pussy. 'You must want to see what its like to be a happy slut gryphon like me!' She says with a grin on her beak as she gestures for you to come closer, the thick scent of gryphon musk filling your head with lust as she pulls you up close to her large egg filled belly, rubbing your bodies together pleasantly. 'Feel that lovely full belly? Nice and round with gryphon eggs? Isn[apostrophe]t it wonderful? I bet you want to feel nice and round and full of life too don[apostrophe]t you?' The gryphon moans, not waiting for an answer before positioning her thick barbed and knotted cock at your entrance. 'I may not be one of those handsome gryphon studs, but I can still give you a little taste of that lovely feeling' She says as she pulls you down onto her thick cock, making you gasp as her soft barbs rub against your sensitive walls.[line break]";
				say "'Doesn't that gryphon cock feel good?' The gryphon gasps, as she thrusts into your slick tight passage. Her knot bumping up against you as she pulls you down onto her shaft.  'Nice and right as it fills you up?' She whispers, the feel of her soft barbs moving within you at every thrust causing you to gasp and groan in pleasure as she runs her talons over your body, her furred lion hindpaws rubbing against your own leonine legs as she moves within you. 'And feel that wonderful knot?' She pants out as her knot spreads you open more with each soft pleasurable thrust, seeking entrance into your eager body. 'Once it enters you it will lock your body to mine just like a good breeding slut should be, sealing your passage tight while my cock fills your body up with its wonderful gryphon seed.  Every pump of my cock ensuring your belly will grow nice and round with the gryphon eggs growing inside you.' Timothy moans, as with one final push her knot enters your body, causing you to gasp helplessly as your pussy clenches it tight, holding it within you tightly like she said.  Timothy immediately begins to speed up her thrusting, making you melt helplessly in her hands, your stiff cock rubbing up against her round belly with every thrust, her soft fur massaging it almost as well as your soft folds are massaging her own cock inside you.[line break]";
				say "Finally she clutches you tight as her body stiffens underneath you, her cock shuddering and twitching inside you as she shoots her gryphonic seed deep into your willing body. The feel of her fertile seed coating your insides, every drop of it trapped in your womb by her knot while her barbs massage your passage is too much for you, and you find yourself crying out as your own powerful orgasm washes over you, your passage shuddering around her cock as your own cock stiffens and shoots its seed, your thick cum coating her soft belly fur even as her own seed fills your body. You pant as she holds you tight, her knot tieing you together as she whispers into your ears about the many more pleasures of being a breeding gryphon, nice and broody and well sexed.  Eventually her knot softens enough that you can pull yourself off of her, your wings splaying out behind you as you rest back on your lionlike paws.  'That was so nice,' Timothy murmers as you slowly begin to gather your wits about you, 'And just think, that was only a short sample, of what being a gryphon breeder is like, though with any luck you can enjoy the feeling of my seed growing within you, and feel the joy of bearing gryphon eggs just like me.' She groans in pleasure while she rubs her own large egg filled belly, as she lies back on the cushions her eyes closing in exhaustion. You find your hand straying to your own belly as her words sink in, finding yourself half hoping that her seed has indeed caught and you will soon be joining her in her large gravid state...[impregchance][impregchance]";
				infect "Hermaphrodite Gryphon";
				increase Timothymated by 1;
				now lastTimothyfucked is turns;
			otherwise:
				say "'Sorry, but I really don[apostrophe]t think my mistress would like it if I let a non gryphon like you have its way with me. It just wouldn[apostrophe]t be right for a happy little breeding gryphon like me to get pregnant with anything but gryphon seed you understand.' Timothy says with a sad look at your body. 'But if you really want to have a little fun we could try to play around a little ourselves?' She says as she pats her thick black cock where It rests up against her pregnant belly.";
				if player consents:
					say "'Ah I knew you wanted to play around a bit with a big slutty gryphon, and maybe eventually you can become one yourself!' Timothy says happily as she gestures for you to crawl up onto the cushions with her.  Her excited scent and the scent of gryphonic rut filling your nose as you find yourself moving closer automatically, you feel your cock stiffening as your pussy clenches with need. 'Mmm I can see that idea turns you on doesn[apostrophe]t it?' she says as she pulls you up until you are lying next to her on the soft cushions, 'Wouldn[apostrophe]t it be great to have nice big breasts like mine?' She says as she moves her large milk filled breasts closer to you, her taloned hand reaching behind your head as she slowly guides your mouth down to one of her nipples, while her other hand guides your hand to her other breast, making her gasp in pleasure. 'Lovely big milk filled breasts, for little gryphlets and playful mates to suck on and tease...' She moans, as you find yourself doing just that, her wonderful flavor making you nibble and lick at her breast playfully, while her hand holds your head in place, and your other hand slowly roams over her other breast, running through the soft fur and teasing her nipple.  Soon your effort is rewarded by the pleasant flavor of her gryphon milk starting to trickle into your mouth, its flavor seeming to explode across your tongue as a new rush of arousal surges through your body.[line break]";
					say "'Mmm oh that feels so good,' She moans as you lick and suck on her wonderful milk giving breasts, her taloned hand stroking the back of your head, before roaming down your body further.  'Of course theres also the joy of having a nice thick gryphon cock,' Timothy says in a teasing tone, as her soft talons trace over your [cock of player] cock, making you gasp against her soft breast as she wraps her hand around your excited cock and pumps it a few times. 'A nice knotted gryphon cock to play with whenever you want is just amazing, but the most fun part of being a big slutty gryphon isn[apostrophe]t the cock,' She says as her taloned hand roams even lower, making you gasp as her clawed talon traces along the outside of your damp pussy.  'No the best part is the wonderful lion pussy of a gryphon slut,' the gryphoness moans, as her talon slowly pushes into your own pussy, causing you to moan in pleasure as your mouth fills with even more of her wonderful milk, your lust fogged head filling with the wonderful images her words are painting for you.  'Just imagine having a lovely gryphon body, like mine, with a hot needy pussy for all the lovely gryphon studs to fill full of their delicious thick cocks. Wouldn[apostrophe]t it be nice to be fucked again and again, their wonderful seed filling your body with delicious eggs.' She moans, as her talon thrusts into you teasingly, bringing you to the cusp of orgasm. 'And the best part is feeling your belly grow large with their nice thick eggs, and the orgasmic pleasure of laying them and growing round all over again.' Timothy moans, her body shuddering as she orgasms at the thought, your mouth filling with her delicious milk as her hand tightens within you, causing you to explode in orgasm as well. Your seed mingling with hers as it coats the cushions underneath you, and your slick juices coating her taloned hand as she pulls it out of your tired body. 'Doesn[apostrophe]t that sound like so much fun?' She asks as she lies back on the cushions next to you, clearly happy and tired from the playtime, 'you should really come stay and be a nice big breeding slut of a gryphon like me, I just know you would love it..' She says with a sigh as you slowly slide down off the cushions, and you have to admit, her offer does sound so very tempting...";  
					infect "Hermaphrodite Gryphon";
					now lastTimothyfucked is turns;
				otherwise:
					say "'Aw thats too bad, I was looking forward to putting it to use again, It[apostrophe]s been a little neglected lately in favor of filling me full of wonderful little gryphon eggs.' She says giving you a sad look out of her avian eyes. 'But I guess there isn[apostrophe]t much more to say than is there, maybe you
 should try my milk or find another gryphon out there to help fill you full of eggs'";
		otherwise:
			if bodyname of player is "Hermaphrodite Gryphon":
				say "'Oh wow! A handsome stud gryphon all to myself!' Timothy says with a happy smile as you approach her, smiling as she takes in your male gryphons form, 'A very handsome looking male too! Just looking at you is making me feel so very horny,' the gryphoness moans, as she shifts her large body, rubbing her talons over her large belly, as she spreads her lion like legs even further apart to give you a good view of just how wet she is. 'Why don[apostrophe]t you come up here and put that wonderful rod of yours to good use?' She pants out, her enticing aroma filling your nose as you climb onto the cushions with her. 'I just can[apostrophe]t wait to feel you inside me,' She moans, her ample chest heaving with excitement as you guide yourself to her waiting passage. You can[apostrophe]t help but feel yourself growing more excited than ever as the tip of your [cock of player] cock probes at her damp lips, her taloned hands running along your sides as she begs for you to fill her up.[line break]";
				say "Giving in to your own needs as well as her begging encouragement you groan as you sink yourself into her warm confines. Timothy cries out in pleasure as your cock enters her fully, her lion like legs stroking along your sides as she tries to press you into her even further. The feel of your thick rod inside her warm damp folds is nothing short of amazing, and you find yourself groaning in pleasure as you lean forward, your chest resting on her swollen belly as your hands grip her soft furred thighs. Timothy begins to moan desperately underneath you as you start to thrust into her extremely willing body, her head thrown back on the cushions and her eyes closed in pleasure as you take the little slut gryphoness for your own.[line break]";
				say "'Oh god it feels so good, so big and so masculine, I just love the feeling of it buried so deep in me.' Timothy moans underneath you, 'Please take me harder, rut me and fill me with your hot seed! Please use me like a good little pet and fill me up with your eggs!' The gryphoness begs in gasping moans of pleasure, making you grin as she is reduced  to little more than a needy beast under you, the pleasure of her well trained body mixing with the pleasure of seeing her become your willing slut, begging for the seed you are sure to give her soon. 'It feels so good to be nice and swollen with eggs, please cum in me, I want to feel your eggs growing in me with all the others, give you handsome little gryphon babies, and you can keep me as happily full as my mistress does...' She coos at you, her lust filled words filling your mind with pleasure, as her well trained pussy strokes your cock for all its worth.  Her ministrations soon have you shuddering in pleasure as your orgasm rocks your body with pleasure, your cock shooting its seed deep inside her body while her soft furred legs clutch you tightly to her.  You lie there for several minutes as she pants and strokes your body, your cock emptying itself fully into her body, before slowly softening, the amazing experience leaving you shaking with pleasure even as you pull yourself out of the wanton gryphoness and try to gather your wits about you.  'That was wonderful,' Timothy moans, rubbing her leonine thighs together as her taloned hands stroke her belly. 'I hope I will have some new eggs growing in here soon, Though maybe you should come back and visit me again once we both have recovered just to make sure... Don[apostrophe]t worry though, I won[apostrophe]t tell my mistress about this visit so you can keep coming back and having fun with me...' She says with a satisfied smile on her beak, as she relaxes back on the cushions.'";
				infect "Hermaphrodite Gryphon";
				increase Timothymated by 1;
				now lastTimothyfucked is turns;
			otherwise:
				say "'Sorry, but I really don[apostrophe]t think my mistress would like it if I let a non gryphon like you have its way with me. It just wouldn[apostrophe]t be right for a happy little breeding gryphon like me to get pregnant with anything but gryphon seed you understand.' Timothy says with a sad look at your body. 'Maybe you should try drinking some of my milk or going out to find a nice handsome gryphon to give you a big wet cunt of your own that he could fill with little baby gryphons....'" ;
	otherwise:
		if bodyname of player is "Hermaphrodite Gryphon":
			say "'Oh my, you look splendid!' Timothy says as she runs her eyes over your female gryphons form. 'With none of those annoying male bits to get in the way either, I bet you will make a wonderful little breeding gryphon don[apostrophe]t you agree?' She says, as she gestures for you to come closer so she can see you better. You find yourself flushing slightly as you obey, your body tightening with need as the heady scent of gryphon sex fills your nostrils, your pussy dampening with need as you crawl up to the pregnant gryphons form.  As soon as you draw close enough, Timothy begins to run her talons along your body, guiding you gently with her hands until you are sitting upright between her legs, and you find yourself staring at her thick black spined cock resting up against her belly, right in front of your gaping pussy. 'So hot and needy already,' Timothy says with a slight chuckle as she reaches down to stroke along your clit, making you moan, 'You really need a nice thick gryphon cock in you don[apostrophe]t you? Why not just give in to what your body wants and let me fill you up with mine.' The gryphon says, as she guides you forward, your body responding to her words and touches as she positions you over her thick cock, before lowering you down onto it.[line break]";
			say "The feel of the thick gryphon cock slowly splitting you open as you lower down onto it is amazing, your needy gryphon sex spreading wide eagerly to grip the thick cock like a glove, making you shudder in delight as you find yourself taking Timothys stiff rod in as far as you can, its soft spines rubbing against you pleasantly as they push into your body until you are resting up against his thick knot. You gasp as the pregnant gryphon pulls you forward so your stomach rubs up against her pregnant belly, making you both moan at the wonderful sensations as she begins to lift her hips up and thrust her cock into you.  The movement causes you to groan in pleasure as she bounces you up and down on her cock, your body rubbing up against her large belly with every thrust, while her knot rubs up against the outside of your body, its thick bulge spreading you wider with each thrust as you feel your pussy stretching out to allow that wonderful bulge inside.  You find yourself crying out lustily as your body finally relents and you can feel your pussy gripping his knot tight as it finally presses into your body fully, your pussy closing tightly around it as it expands and locks you together.[line break]";
			say "'You need this so badly don[apostrophe]t you?' Timothy pants out as she continues to thrust into your all too willing body, 'If even the cock of a little breeding slut like myself feels this good to you, just imagine what the cock of a real stud gryphon is like,' Timothy moans into your ears, as she continues to move within you, her knot tugging at your passage with every small motion, sending waves of pleasure throughout your body. 'Just imagine their strong male hands holding you down as they fill you up, mounting you again and again until your belly swells large with their seed.' her talons stroke your the back of your head as you lean down closer, your body clenching in need as her soft words fill your mind. 'You would make such a perfect little breeding slut wouldn[apostrophe]t you, with no distracting little cock to get in the way, all you would have to think about is their wonderful cocks locking into your wet pussy, day after day, fucking you until your belly is as large as mine and you bear their big strong gryphon offspring. Don[apostrophe]t you want that? Want to be just another happy breeding slut for them to use?' Timothy whispers as she runs her talons along your body, her cock moving slowly within you as she keeps you panting at the edge of orgasm, her words washing over your lust fogged mind as she teases your body.  Before you can realize what you are doing, you find yourself nodding and begging as you agree with her, you find yourself begging for some strong gryphon to come claim you and make you its pet, desperately wanting them to fill your body up with fertile gryphon seed, and turn you into a breeding whore just like the pregnant gryphon underneath you.  The sheer dirtyness of what you are saying seems to make you even more excited as you beg, the truth of your words filling you with pleasure as you realize that at this moment in time that is exactly what your needy body wants, and an amazingly pleasurable orgasm explodes through you at that realization.[line break]"; 
			say "'I knew you wanted to be happy and full of eggs just like me,' Timothy moans in victory, as her body stiffens underneath you, her cock twitching inside your hot folds as it finally shoots its thick gryphon seed into your waiting womb, the thick knot tying you together ensuring that not a drop of that oh so fertile cum is wasted, while the spines tickle your passage to ensure your body is receptive. You find yourself panting as you lie on Timothys stomach lightly, the knot keeping you together as she whispers more dirty words into your ears about the pleasures of becoming a breeding gryphon like her. You find yourself nodding almost automatically at her lewd suggestions of male gryphons and constant sex, almost wanting to give in and see what life as a breeder is like, eventually though, her knot softens,
 and the exhausted gryphoness relaxes back on the cushions to rest as you pull your tired body off of her, the spines tingling pleasantly as they pull out of you.  You stagger back to your feet and begin to gather your equipment to wander out in the city again, although you find one of your hands keeps wandering back to rub your belly, and you know that with the thick knot locking you together and the lovely spines stimulating your body, the chances of a pregnancy if such a thing is at all possible, is extremely high, somehow this thought just seems to make you feel even better, and you find yourself smiling as you get ready to leave.[impregchance][impregchance]";
			infect "Hermaphrodite Gryphon";
			increase Timothymated by 1;
			now lastTimothyfucked is turns;
		otherwise:
			say "'Mmm you want to be filled with wonderful little gryphon eggs too?' Timothy says as she eyes your female form, 'You aren[apostrophe]t quite ready to be a proper breeder though yet, while the female parts are in the right place, the rest of your body just doesn[apostrophe]t quite match.' the pregnant gryphoness says with a sigh, 'Fortunately I think I have a bit of a drink here that can fix that,' She says as she gestures you closer to her. With her excited scent filling your nostrils you find yourself complying eagerly, your pussy clenching hopefully as you draw closer, slowly crawling up onto the cushions near her leonine feet as you move up to her. She looks down at you over her pregnant belly as you move closer, a strange grin on her beak as she reaches down with one taloned hand and begins stroking her thick black gryphon cock in a teasing manner.  As your head draws closer to her nether regions, her musky gryphon scent grows even stronger, and you find your gaze fixing on her cock, her talons moving teasingly along its black length as you draw closer.  Drawing up level to her belly, your eyes still fixed on her cock, you are slightly startled to feel her other taloned hand stroke along the side of your head, before softly pushing it downwards towards that enticing black cock.[line break][line break]";
			say "You find your lips parting almost automatically as she guides you down towards her cock, your tongue tracing over its pointed tip as you draw close to it, the taste only intensifying your desire as your mouth waters and your pussy leaks its juices out onto your thighs. 'Oh yes,' Timothy moans, as she guides her shaft into your mouth, her talons gripping your head lightly as she feels your lips enveloping her member. 'Take all of my cock into that wonderful mouth of yours and suck  on it please!' She cries out, as she pushes your head downwards.  Needing no further encouragement with that delightful taste in your mouth, you find yourself eagerly sucking and teasing on her stiff black rod, your head bumping and rubbing softly against her large belly as it bobs up and down on her lovely shaft. Your mouth grips Timothys shaft in its loving embrace as she grips the back of your head with her talons, her moans and groans music to your ears as you take more and more of her maleness into your mouth, licking and teasing at the soft black knot at the base of her cock as you suck happily on the rest of her shaft.[line break]";
			say "Unable to help herself, the gryphoness begins thrusting slightly into your mouth, moaning in need as she draws closer and closer to orgasm, the sounds encouraging you lavish even more attention upon her gryphon cock.  'God yes!' She cries out as her body shudders above you, and her cock stiffens as it fills your mouth with its fertile seed, the taste seeming incredible as you do your best to gulp it down. 'Suck it all down,' She moans as she continues to fill your mouth up to the brim, some dribbling down your chin slightly even as you continue working her rod. 'Drink down every little drop of gryphon sperm like a good little breeding slut, and let it make you into just another happy little gryphon whore just like me, ready and willing for all the horny gryphon males to come fill your gaping pussy with their seed.  And than you can stay here with me and have your belly nice and full with their eggs too, and we can do this all the time...' She moans out in pleasure, the words seeming to sink into your mind, bringing forth images of your body changing to be more like the gryphons, and how wonderful it would be to be nice and full of new life all the time as you do your part to expand the gryphon population.  You pull yourself off her spent cock, licking your lips as your body shudders in its own orgasm, her fertile seed filling your stomach and making your body tingle, and you find yourself wondering if being a happily fucked gryphon pet might not be a good idea after all.";
			infect "Hermaphrodite Gryphon";


when play ends:
	if bodyname of player is "Hermaphrodite Gryphon":
		if Timothymated is greater than 2:
			if humanity of player is less than 10:
				if cocks of player is greater than 0:
					if cunts of player is greater than 0:
						say "Giving in to the instinctive urges deep within your needy mind, stiff cock, and hot pussy, you find yourself taking off on your new wings as you head back to the place where you found and enjoyed the wonderful breeding gryphon. Much to your delight, you find that Timothy[apostrophe]s mistress has returned, the handsome herm gryphon welcoming you with open arms as she sees how needy and ready your body is for her. Before long she has your body pressed up against Timothys needy form, your cock pressing at the needy wetness between Timothys legs even as she fills your pussy up with her own wonderfully strong gryphon cock.  You find yourself overwhelmed with pleasure as she guides your cock into Timothys silken passage, the pregnant gryphon moaning underneath you as you are sandwiched between her and the strong and powerful gryphon behind you. Your lust fogged mind quickly succumbs to the intense pleasure of both fucking and being fucked at the same time, your body pressing into the gryphon underneath you in time to the stronger gryphon mistresses thrusts. Soon she cries out as she fills your needy body with her fertile seed, the feel of all the lovely baby batter coating your insides triggering your own orgasm as your body shoots its own seed into your fellow breeding slut.  You stay there panting, your bodies locked together in pleasure by your thick gryphon knots as her seed sinks into your body, working to fill your womb with her eggs. You find yourself smiling as you can feel your mistress slipping her collar around your neck, marking you as her property just as much as the smiling gryphon underneath you. ";
						say " You look down and tilt the tag up to read your new name, and you can feel your beak pulling back in a smile as you can see the tag that proudly proclaims you to be 'Toy' hanging from your collar. You can[apostrophe]t help but feel joy at the rightness of the name, and moan in pleasure as your mistress[apostrophe]s cock begins to stiffen and move within you again. Your mind is overwhelmed with lust as she begins to use you like a good toy, filling your needy belly up again and again with her seed, even as her pet writhes underneath you. Soon you know you will look just like her pet, your belly round and large with her eggs, and your form so well bred it will be hard to even move, lying here together waiting for your mistress to return and fill you with even more eggs so you can birth the next generation of her wonderful offspring. Just the thought of your eventual fate seems so wonderful to your instinct driven mind now, as you rub your leonine legs against hers, that you find yourself begging and pleading for her to fill you up with her seed again and again until your body is as round and full with life as her pets. Your mistress is happy to comply, and soon you find yourself living a wonderful new life, as your mistresses happily pregnant new toy, and though you and her pet often keep each other company while she is out, putting your flexible beaks and talons to work, you are both happy to know that only her seed fills your wombs with her wonderful eggs, which you birth for her time and time again.  You are so happy you discovered the pleasures of being just a lovely gryphons breeding toy...";
					otherwise:
						say "Giving in to the instinctive urges deep within your needy mind and stiff, you find yourself taking off on your new wings as you head back to the place where you found and enjoyed the wonderful breeding gryphon. Unfortunately you find that Timothy[apostrophe]s gryphon mistress has returned, and upon seeing you she does not appear amused. Spreading her wings out she drives you back with several harsh blows, keeping her pet to herself as she drives your male form off to find another breeder to fill with your seed. Your bodys new needs only enhanced by the touches of a breeding slut, you prowl the streets looking for a unclaimed pet of your own. Having surrendered to the infection rather late, you find the city practically empty of good stock, until the military arrives. ";
						say "You carefully stalk several of the soldiers until you can manage to lure one of the females away from the rest long enough for you to swoop in and carry her off. She is stunned as you carry her to your prepared nest, where you than proceed to quickly strip her bare and master her body with your strong gryphon cock. You love the feel of her body changing underneath you as you rut her again and again for hours on end, driving all her old and unnecessary human thoughts from her new gryphon brain as you make her into a fitting receptacle for your eggs.  You are happy to see that when she is finished she is perfectly matched to you, a proper breeder with just a lovely well fucked cunt instead of the dual equipment so many of the other gryphons sport.  Soon she is your happy mate, her belly swelling with your eggs, and her body eager for your
 seed every time you return from your hunting, she bears you many healthy gryphon eggs as time passes, and eventually you manage to find more pets to share your nest and keep her company while you hunt, though she always remains your favorite.  Your many, many offspring will eventually spread across the land, converting more and more people into happy little breeding gryphons.... but not for some time to come.";
				otherwise:
					say "Giving in to the instinctive urges deep within your needy mind and hot pussy, you find yourself taking off on your new wings as you head back to the place where you found and enjoyed the wonderful breeding gryphon. Much to your delight, you find that Timothy[apostrophe]s mistress has returned, the handsome herm gryphon welcoming you with open arms as she sees how needy and ready your body is for her. Before long she has you sprawled out face down on the cushions, your head between Timothys legs as she fills your pussy up with her wonderfully strong gryphon cock.  The pleasure of her cock pressing into you making you moan as you lick and suck eagerly at Timothys cock even as the gryphon stud fucks you roughly. Soon you find yourself orgasming uncontrollably underneath him as he fills your belly up with his fertile seed, your body shuddering as it prepares itself for the eggs that are sure to come. ";
					say " As you lie there trying to recover your mouth still licking and nuzzling at Timothys sex, you feel something settling around your throat, and look down to find that your mistress has just fitted you with your own collar, marking you as just another one of her happily fucked pets. You raise one of your talons up to tilt the tag up so you can read what it says, and find your beak pulling back in a smile as you see it reads 'Egg-Slut'  and you realize just how true the tag is, and find yourself enjoying how it declares your purpose to any handsome stud gryphon who draws near.  You find yourself cooing happilly as your mistress strokes your feathered head with her strong talons, happy to finally be free to be nothing more than your mistresses little egg slut.  You find yourself smiling as she guides you back down onto the cushions next to your fellow breeding slut, her cock already thick again and ready to fill your needy body will all the eggs your slutty heart could desire... and you find yourself glad as you feel her thick gryphon seed shooting within you again, that you have finally found where you belong, serving your mistress and bearing her many many young....";
			otherwise:
				say "Leaving the city, you find yourself constantly wondering about the strange breeding gryphon you left behind in that strange floating city. And you find yourself wondering if they are still there even after the military has long since evacuated those on the ground, the happy breeder and her mistress and gryphon studs who keep her filled with eggs again and again. Eventually curiosity gets the better of you, and you pack up and head back to the city to look, you tell yourself that it is just to let them know they should return to normal society, as you follow the trail they left to their city where it hides among the mountains, you feel your body responding to the scent, and realize that it is you that has finally come home, as they greet you with open arms. While you are never heard from again, there are persistent rumors of an ever growing number of gryphons in those isolated mountains...";


Section 4- Gryphon Nest

Gryphon nest is a room.

The description of Gryphon nest is "This small room is tucked between several of the other tents filling the area, its soft canvas surrounding a small private enclosure filled with a large variety of different cushions and cloths, the soft light from the glowing floor and tent cloth illuminating the area. You can see several small items and trinkets, scattered amongst the cushions, but your eyes are drawn most to the heavily pregnant herm gryphon lying sprawled out on the cushions, a small collar with a tag hanging from around her neck.";
Timothy is in Gryphon nest.
Gryphon nest is west of City Plaza.














Zoo People ends here.

