Version 1 of Greek Mythos by Prometheus begins here.

[ TwelveLaborsStage                                                  ]
[ 0: Not started                                                      ]
[ 1: Started First Task - The Nemean Lion                             ]
[ 2: Started Second Task - Lernean Hydra                              ]
[ 3: Started Third Task - The Hind of Ceryneia                        ]
[ 4: Started the Fourth Task - The Erymanthean Boar                   ]
[ 5: Started the Fifth Task - The Augean Stables                      ]
[ 6: Started the Sixth Task - The Stymphalian Birds                   ]
[ 7: Started the Seventh Task - The Cretan Bull                       ]
[ 8: Started the Eighth Task - The Horses of Diomedes                 ]
[ 9: Started the Ninth Task - The Belt of Hippolyte                   ]
[ 10: Started the Tenth Task - Geryon's Cattle                        ]
[ 11: Started the Eleventh Task - The Apples of the Hesperides        ]
[ 12: Started the Twelfth Task - Fetch Cerberus from the Underworld   ]


TwelveLaborsStage is a number that varies. TwelveLaborsStage is usually 0.

[QUEST LOG]
to TwelveLaborsQuestLog:
	if TwelveLaborsStage is:
		-- 1:
			say "[bold type]Twelve Labors Quest: [roman type]I was told to go to the Dry Plains to face the Nemean Lion. I should be sure of my readiness before doing so.";
		-- 2:
			say "[bold type]Twelve Labors Quest: [roman type]Having successfully defeated the Nemean Lion, I was told that the next Labor, the Lernean Hydra, would be waiting for me in the Junkyard.";

Section 1 - Events

[Labors of Herakles]
Labors Introduction is a situation.
The sarea of Labors Introduction is "Museum".

after going to Museum Foyer while (Labors Introduction is not resolved and level of player > 30 and a random chance of 1 in 2 succeeds):
	move player to Museum Foyer;
	LaborsIntroductionEvent;

Instead of resolving Labors Introduction:
	LaborsIntroductionEvent;

to LaborsIntroductionEvent: [Invited to perform the Labors]
	say "     As you enter the museum entrance hall, the air feels different to usual as though it is charged. You consider asking Valerie about it but a loud thunderclap and the sudden appearance of an impressively bearded man interrupts this thought. 'You there. Mortal. Are you [name of player]?' he intones grandly. You quickly nod dumbfounded. The man relaxes a bit and takes you by the shoulder as you walk down the corridors. 'I am Zeus. God of the sky, and king of the Olympians. Your actions within this plane have not gone unnoticed and as such I would like to extend to you an invitation to carry out the Labors of Herakles. I do hope you are familiar with them, but even if you aren't, I'm sure you'll manage them anyway. Though I doubt you'll be quite as impressive as my son, but I'm biased so don't be discouraged.' He seems a lot less wrathful than some of the myths make him out to be, luckily for you.";
	say "     By this time you are opposite a shrine to Hera. Beside it, an elegant woman is brushing dust off the marble and muttering rude remarks about the cleaners. Zeus coughs politely, causing her to look up. While you wouldn't describe her face as sexy, there is a regal beauty that commands respect. You stand there awkwardly, unsure what to say. The woman finally breaks the silence with a sigh. 'As my husband is too rude to introduce me, I am Hera, goddess of Marriage, and Queen of Olympus. Come sit with my by the shrine.' You allow her to guide you to a step and seat yourself at a polite distance next to Hera, allowing a bashful Zeus to sit on her other side. 'How much has he explained to you?' the goddess asks, offering you a dish of pomegranate seeds. You reply that he had only had time to say that you were invited to perform the Labors.";
	WaitLineBreak;
	say "     'When Herakles had to do the labors it was to seek redemption for killing his family, and as you can understand I did some morally questionable things to try and stop him,' Hera begins to explain. Zeus rolls his eyes when she says [']morally questionable['] but doesn't interrupt. 'Now, we use the labors more as a ritual to maintain our power. Most of the Greek gods that you know used to be human but transcended with the immense power we were given. There are some exceptions such as Hekate, Nyx, the Titans or older beings, but in general most of us were human once. Poseidon still views us as such, but we've changed. Other planes are different, so be careful you don't upset some deity by calling them a human,' she says with a smile. 'But I'm getting sidetracked. I was meant to be telling you about the labors.'";
	say "     'I will be acting more as an adversarial force rather than your enemy. Your efforts to succeed and overcome the trials ahead of you will generate a sort of energy that maintains our powers, but we have regular worshippers so there isn't any danger of us weakening should you fail.' Hera's comments. Seeing the concern on your face, Zeus quickly adds, 'We wouldn't have chosen you if we didn't think you had a chance. We want you to succeed too.' His wife wraps her arm around your shoulder, 'I didn't intend to sound as uncaring as I did. I apologize. Each time you complete a labor you shall be rewarded, our power is limited here, but I hope you'll at least like some of them. As I'm sure you understand, this city has a, shall we say, hedonistic atmosphere that might even shock Aphrodite or Dionysus, so some of the labors may take on a similar theme. I hope you don't mind.' From Zeus's grin, you can tell that he is looking forward to watching.";
	WaitLineBreak;
	say "     'None of us will interfere in the labors directly. So only attempt each trial when you are sure you are ready. We can not be sure of your welfare, so you may die,' Hera informs you concernedly. 'Or become a monsters sex toy,' Zeus mutters, shrinking back under the glare directed at him by his wife. He quickly continues the speech, 'The first labor is the [bold type]Nemean Lion [roman type], a absolutely vast feline with a near impenetrable hide. I'm not allowed to tell you how to defeat it, but I would advise finding out if you don't already know. It can be found in the [bold type]Dry Plains [roman type]so depending on whether or not you feel ready for it, I would suggest searching there.' He looks to Hera to see whether there is anything further she feels you need to know. 'Be careful hero, as amusing as Ares might find you meeting a valiant death, it wouldn't serve any purpose and we would rather you didn't take part than get yourself killed.'";
	say "     They seem to be finished explaining what they want you to do so, wanting a bit of space from them, you return to the museum entrance. Valerie is back behind the front desk reading through a book of riddles which she quickly hides upon noticing you. 'I'm sorry I wasn't here earlier. I was [italic type]advised [roman type]not to be here.' She rolls her eyes as she says this. 'What Zeus needed to tell you without me being present I probably shouldn't pry into, but be careful. Gods and mortals don't often mix well.' It would seem she would prefer not to get mixed up in the gods' request so you keep quiet about it. A shame. She might have been able to help with suggestions for how to defeat the Nemean Lion. Should you decide to attempt the labors, you're going to have to find someone else with classical knowledge or hope you know enough yourself to succeed.";
	now TwelveLaborsStage is 1;
	add "Twelve Labors Quest" to OpenQuests of player;
	now Labors Introduction is resolved;
	now Meet the Nemean Lion is not resolved;

Meet the Nemean Lion is a situation.
Meet the Nemean Lion is resolved.
The level of Meet the Nemean Lion is 0.
The sarea of Meet the Nemean Lion is "Plains".

instead of going to Dry Plains while (TwelveLaborsStage is 1 and a random chance of 1 in 5 succeeds):
	move player to Dry Plains;
	MeettheNemeanLionEvent;

Instead of resolving Meet the Nemean Lion:
	MeettheNemeanLionEvent;

to MeettheNemeanLionEvent: [Fight the Nemean Lion]
	say "     Wading through the long grass, you hear a roar in the distance and fearful shouts. You consider avoiding the situation, but curiosity and concern overpower your caution. You begin to rush towards the commotion, the sounds getting louder. Ahead of you, you see a hill with three unconscious centaurs strewn across the dirt, their breaths ragged. The grass is soaked in blood, turning your stomach, the source of which is the ragged tears in the centaurs['] flesh caused by what appears to be claws. The sound of beating hooves causes you to snap your head up as an equine body charges over the crest of the hill pursued by the largest lion you have ever seen. This centaur seems to be faring better than his brethren judging from his lack of wounds, but while he has sweat trickling over his skin, his adversary appears unfazed by the physical exertion. You doubt that this will last much longer, but you doubt you would be able to escape even if you tried.";
	say "     Still evading the lion's claws, the centaur knocks an arrow to his bow and looses back at his pursuer. To your surprise, the arrow [italic type]shatters [roman type]on impact with the feline's hide. It would seem that this is the mythical Nemean Lion. Now that you look more closely, you see the remnants of other arrows suggesting that this has been going on for some time. Why then does he still try the same tactic? Your thoughts are answered by the groans of the centaurs down the side of the hill as they regain consciousness and attempt to stand. The combatants both hear this, with the centaur shouting, 'Run, this is an adversary that we can't overcome! The interloper will buy us time.' What? The centaurs flee, their leader rushing right past you leaving you facing a bloodthirsty beast from Greek myth. If you survive this then your going to be having some words with him and his herd.";
	challenge "Nemean Lion";
	if fightoutcome < 20: [player won]
		say "     'Nicely done mortal. Nicely done indeed.' You turn to find a man clapping his hands, impressed at your success. He continues, 'I hope you won't take offence at my surprise. I'm Hermes and I have been tasked with rewarding you. So what's it going to be; the five piece lounge set, the holiday to sunny Barcelona, or perhaps the hide of the Nemean Lion without having to get all bloody skinning a highly resistant beast?' Before you can reply, he interjects, 'Sorry, but there isn't actually a choice. Like Herakles, you're getting the skin. You don't have a use for a lounge set, and sending you to Barcelona may spread the contagion.' The unconscious lion begins to glow as Hermes raises his arms, speaking in an unrecognizable language. You shield your eyes from the rapidly brightening light and by the time you look back, a lion skin that looks fashioned in a cloak lies before you. Crouching to pick it up, you are surprised at how light it feels for it's size and question the waiting god about it.";
		say "     'You can't just accept a miracle for what it is can you? You have to ask how. It's magic, and not even mine. I just acted as a sort of conduit for Hekate. It should protect you from physical harm you may come across in the city. Insults and lewd gestures will hit you just fine though, so don't put yourself in situations that you aren't comfortable with. I've got to run though, messages to deliver and travelers to watch. Enjoy!' With that, Hermes just seems to disappear as he steps through thin air, leaving you awkwardly crouched, trying to jam a lion skin into your backpack. It is at this point that you realize that you have no idea where you are going next. A voice behind you startles you out of this thought and you prepare to defend yourself as you spin around.";
		WaitLineBreak;
		say "     You are greeted by the knees and white tunic of Zeus. He chortles as he looks down at you, offering you a hand up. 'Sorry to surprise you, but I noticed that my son forgot to tell you where to go next, and I felt the reward was a little... hollow for the amount of effort you put in. So how would you like to mount or be mounted by the Nemean Lion? He's male, so if you prefer women feel free to refuse. You won't be rewarded or punished further either way. I promise I'll let you [italic type]fraternise [roman type]in relative privacy.";
		say "     [bold type]Do you take Zeus up on this offer?[roman type][line break]";
		LineBreak;
		say "     ([link]Y[as]y[end link]) - Yes. Why not gain something extra out of your struggle?";
		say "     ([link]N[as]n[end link]) - No. There are things you would rather be doing and the lion doesn't sufficiently gain your interest.";
		if player consents: [Sex with Lion]
			if player is male: [ Male Choices]
				say "     [bold type]Who is mounting whom?[roman type][line break]";
				LineBreak;
				say "     ([link]Y[as]y[end link]) - You shall mount the lion. Take out your excess adrenaline on his ass.";
				say "     ([link]N[as]n[end link]) - Let the lion mount you. You dominated it in combat, now let it dominate you.";
				if player consents: [Pitch Anal]
					say "     Grinning at you with a gleam in his eye, Zeus raises his arms, the sky turning black above him. With a loud boom, a lightning bolt strikes the hill above you, the flash blinding you for a moment. When the stars clear from your vision, the lion has returned, its coat resplendent. Another noticeable feature is the erect pink cock bobbing beneath his golden stomach, a fine gleam of pre shining. His behavior, for it is definitely a he, is closer to that of a house cat, friendly without wishing to appear too much so, brushing against Zeus's leg as it walks past. 'I'm looking forward to this,' you hear the god mutter to himself, patting the lion between his ears. 'I suppose I'll leave you to it. Don't worry, he's a lot tamer now so any wounds you get shouldn't be too serious. Oh, and he'll be banished once you orgasm so try to give him a little pleasure too.' With that, the king of Olympus vanishes in a thunderclap.";
					say "     Now that Zeus is gone, the feline shifts his focus to you, rubbing against your leg and purring. If you consider it sufficiently intelligent, then this might be attempts at bribing you into pleasuring it, and oh how you plan on doing so. [if player is submissive]Crouching beside the lion's engorged penis, you gently begin to stroke his flank, gradually closing in on the twitching organ. Your partner's legs shiver in anticipation, copious fluids dripping onto the soil, exuding an arousing scent that stirs your loins. [else]Gripping its mane, you stare it in the eyes to reinforce your dominance, being rewarded with him shrinking away and baring his throat. Content with his reaction, you crouch beside him and begin to stroke his penis, the aroma of his arousal stirring your loins. [end if]As the friction decreases over his erection, you become curious as to what his impressive cock tastes like and lie on your back below his groin, your control still maintained.";
					WaitLineBreak;
					say "     The lion's musk is much more potent beneath him, filling your nostrils to the point of even flowing into your throat. This aids you to salivate as the earthy flavor tickles your mouth and your patience runs thin. Giving your lips a cursory lick, you slip the feline cock into your mouth, looping your tongue around the shaft to taste his essence. Feeling it rotate in your mouth, you are surprised to see the Nemean Lion turning so that his face is beside your loins. As his tongue makes contact with the sensitive flesh of your member you flinch, the rough texture grazing up your length. In tandem, you orally stimulate each other, both out of desire, but also keeping in mind the final goal of you mounting your former adversary. With this thought, you allow his member to spring from within your mouth and shuffle back a bit, granting yourself a view of his dark tail hole. You consider for a moment before deciding the more lubrication the better and bring your mouth towards his backside.";
					say "     The lion takes your cock deeper within his maw as you begin to trace the tip of your tongue around the waiting orifice, his hide slightly salty with an aftertaste of his arousal. You can feel the head of your penis sliding into the lion's throat as your tongue slides over his sphincter, the hard tissue at the back of his mouth forming a pleasant ring around your length. The feline's purrs intensify as you explore his rear cavity, the vibrations being felt by both your invading organs, heightening the stimulation and causing you to shiver. The copious saliva shining from around the big cat's anus indicate his readiness if the rampant cock swaying between his slightly crouched legs wasn't enough, and you withdraw your face from his rear. You are almost reluctant to end his oral ministrations, but the anticipation of what is to come steels your resolve as you slip your shaft from his mouth with a noticeable squelch. With all necessary areas suitably slick, you are ready for the main event.";
					WaitLineBreak;
					say "     Scrabbling out from beneath him, you take a minute to admire his muscular derriere as you clamber to your feet. Testing his pulsing opening with a finger, you find it wet and eager for you as you slip your digit inside for a second. The lion lets out a growl as though to protest the sluggish speed at which you progress towards penetrating his anus properly. Lining your cock up carefully, you take a breath before driving yourself inside of him with a single thrust. The walls of his rectum squeeze around your flesh as you pound into him with vigor similar to your combat, the feline letting out grunts and purrs as his prostate is battered. [if player is dominant]You grasp the scruff of his neck with one hand to help anchor yourself while your other strokes over his tail and around your joining. He responds by letting out an ecstatic yowl and releasing a sizable spurt of pre onto the ground[else]Your hands roam over his flanks, squeezing the muscles in his thighs and probing your joining. You lean over the feline's back, allowing one hand to reach his penis to give it a few strokes, being rewarded with a few spurts of pre that splatters the dirt[end if].";
					say "     As your coupling continues, your partner gradually presses his chest more firmly against the ground while keeping his hindquarters elevated for your firm love-making. He seems to be recognizing your dominance over him. You can feel yourself getting closer and closer to climax and intensify your thrusts. The resultant force of this causes the Nemean Lion's cock to slap against his tummy, the noise mingling with the squelches from his anus. This is apparently too much for the cat, as he emits a magnificent roar and begins to cum. A veritable flood of semen erupts from his barbed penis, flying through the air to soak the ground beneath him as well as painting his underbelly with the musky liquid. His orgasm is accompanied by the rapid contractions of his rear passage, the moist passage's caresses clasping with increased force around your rigid shaft.";
					WaitLineBreak;
					say "     A cross between a groan and a sigh oozes from your lips as your release arrives with a vengeance for all the teasing up until now. The first spasm doesn't release any semen, but the second onwards squirts what feels like more than your balls would be capable of holding into the dazed lion's inviting colon, your twitching scrotum pressed tightly between your groins. When your muscles release the tension preventing you from moving, you both collapse on your sides, keeping your still trickling shaft in his quivering anus. Taking deep breaths, you stroke his fur as your climax comes to an end feeling apprehensive about your companion's approaching banishment. 'Don't worry. Banishment isn't death,' a male voice says from behind you. You rapidly turn your head, but see no-one. 'I'm not supposed to be here, so please forgive my not showing myself. But as I was saying, the lion will be fine. Echidna loves her monsters no matter how mundane or unworldly they appear. Good luck in the Labors.'";
					say "     You gather the being is gone from the silence that follows, only broken by the feline's deep purrs and your panting. With a flash of light, the lion vanishes leaving you alone beside a small puddle of cum. 'Now that that's done, would you like to know your next task?' You jump slightly at the sound of Zeus's voice and resist the urge to cover yourself considering he was probably watching the whole thing. 'Well, from your lack of refusal I'll take that as a yes. You must defeat a hydra of extraordinary size. Once again, I'm not allowed to give you hints, but just in case you didn't get help for the previous labor, there are people in the city with a knowledge of myth so you could possibly ask them for advice.' As he turns to leave, he says over his shoulder, 'you'll find your quarry in the junkyard, but he's larger than the [']normal['] hydras you find there.' With that, you are left alone again, the soil drinking the result of your breeding.";
				else: [Catch Anal]
					say "     Grinning at you with a gleam in his eye, Zeus raises his arms, the sky turning black above him. With a loud boom, a lightning bolt strikes the hill above you, the flash blinding you for a moment. When the stars clear from your vision, the lion has returned, its coat resplendent. Another noticeable feature is the erect pink cock bobbing beneath his golden stomach, a fine gleam of pre shining. His behavior, for it is definitely a he, is closer to that of a house cat, friendly without wishing to appear too much so, brushing against Zeus's leg as it walks past. 'I'm looking forward to this,' you hear the god mutter to himself, patting the lion between his ears. 'I suppose I'll leave you to it. Don't worry, he's a lot tamer now so any wounds you get shouldn't be too serious. Oh, and he'll be banished once you orgasm so try and forgive him if he's a little rough.' With that, the king of Olympus vanishes in a thunderclap.";
					say "     Now that Zeus is gone, the feline shifts his focus to you, rubbing against your leg and purring. If you consider it sufficiently intelligent, then this might be attempts at bribing you into pleasuring it, and oh how you plan on doing so. [if player is submissive]Crouching beside the lion's engorged penis, you gently begin to stroke his flank, gradually closing in on the twitching organ. Your partner's legs shiver in anticipation, copious fluids dripping onto the soil, exuding an arousing scent that stirs your loins. [else]Gripping its mane, you stare it in the eyes to reinforce your dominance, being rewarded with him shrinking away and baring his throat. Content with his reaction, you crouch beside him and begin to stroke his penis, the aroma of his arousal stirring your loins. [end if]As the friction decreases over his erection, you become curious as to what his impressive cock tastes like and lie on your back below his groin, your control still maintained.";
					WaitLineBreak;
					say "     The lion's musk is much more potent beneath him, filling your nostrils to the point of even flowing into your throat. This aids you to salivate as the earthy flavor tickles your mouth and your patience runs thin. Giving your lips a cursory lick, you slip the feline cock into your mouth, looping your tongue around the shaft to taste his essence. Feeling it rotate in your mouth, you are surprised to see the Nemean Lion turning so that his face is beside your loins. As his tongue makes contact with the sensitive flesh of your member you flinch, the rough texture grazing up your length. In tandem, you orally stimulate each other, both out of desire, but also keeping in mind the final goal of him mounting you. Perhaps with this thought in mind, the lion lets your member slip from his jaws and begins to lick at your ass. His tongue grazes over the sensitive skin of your scrotum as he attempts to lubricate your anus. Another side effect is that he has to crouch more to reach, thus forcing his cock further into your soft throat.";
					say "     This doesn't cause you much discomfort however as you swap your focus to circling your tongue around his shaft while allowing him to thrust. The rough texture of his tongue makes you occasionally twitch as it catches on the crinkled skin sphincter, the tingles making your penis tap against your partner's neck. Heightening the stimulation, the lion begins to purr as he continues to taste your darkest area, the vibrations carrying through your body and you are sure that he'll be able to feel them in his own cock. The smell of musk grows stronger as you both continue, his balls presses into your nose each time he thrusts. From the feeling of wetness around your anus, you doubt it will be long before you are ready and apprehension conflicts with the eagerness to feel the large feline pounding into you. He seems to share your anticipation for what comes next, dismounting your face and circling around to allow you to get on all fours. With all necessary areas suitably slick, you are ready for the main event.";
					WaitLineBreak;
					say "     Looking over your shoulder, you admire his toned form while you wait for him to approach and mount you. He sniffs your backside for a moment, the wafts of air feeling cool against the sheen of fluid around your anus. With a noise of eagerness, the Nemean Lion heaves himself onto your back and for a moment you wonder whether you will be able to support his weight. As he comes down on top of you, you find your concern to be unfounded. Either he isn't as heavy as he looks or there is some force ensuring your pairing goes smoothly. For a few seconds you relax at the feeling of his warm fur against your naked back before another stimuli takes precedence. With a growl of determination, the lion thrusts forward, impaling your receptive body on his barbed penis. As the head rapidly squeezes through your opening, each of these nubs slips through with pleasurable feedback rushing through your nerves. The big cat only stops his forward momentum when he feels his balls contact with yours.";
					say "     [if player is submissive]To your surprise, the lion softly grasps your neck in his jaws as he continues to thrust firmly. Beneath a magnificent beast as he pounds you and protectively holds you, you subconsciously feel that this is your natural position. [else]To your surprise, you feel the lion's rough tongue rasping over the back of your neck as he continues to push into you. You may be beneath him, but such affection shows he doesn't think you inferior. [end if]You gradually lower your upper body to the ground as the coupling progresses, your rear being kept raised in order to receive your partner's rigid cock. From the increase in force that accompanies his thrusts, you wonder whether he is getting close to climax. By this time he is nearly pounding you into the ground, his thrusts making your penis slap against your tummy, the sound mingling with the squelches from your anus. With a magnificent roar, the Nemean Lion cums deep within your bowels, the flood of spooge spurting out of the joining as his balls contract against your own.";
					WaitLineBreak;
					say "     A cross between a groan and a sigh bursts from your mouth as the pressure from the hot sperm in your ass sends you over the edge too. The first spasm doesn't release any semen, but the second onwards squirts what feels like more than your balls would be capable of holding onto the dirt in front of your head, stray bursts splattering your face. With the lion pressed firmly against your backside, you are held in position while you both recover from your orgasmic paralysis. As soon as the feline takes a step back, you collapse on your side, his shaft sliding from your gaping hole, spilling a new river of semen onto the ground. Through the haze of climax, you become concerned about your companion's approaching banishment. 'Don't worry. Banishment isn't death,' a male voice says from behind you. You rapidly turn your head, but see no-one. 'I'm not supposed to be here, so please forgive my not showing myself. But as I was saying, the lion will be fine. Echidna loves her monsters no matter how mundane or unworldly they appear. Good luck in the Labors.'";
					say "     You gather the being is gone from the silence that follows, only broken by the feline's deep purrs and your panting. With a flash of light, the lion vanishes leaving you alone beside a sizable pool of cum. 'Now that that's done, would you like to know your next task?' You jump slightly at the sound of Zeus's voice and resist the urge to cover yourself considering he was probably watching the whole thing. 'Well, from your lack of refusal I'll take that as a yes. You must defeat a hydra of extraordinary size. Once again, I'm not allowed to give you hints, but just in case you didn't get help for the previous labor, there are people in the city with a knowledge of myth so you could possibly ask them for advice.' As he turns to leave, he says over his shoulder, 'you'll find your quarry in the junkyard, but he's larger than the [']normal['] hydras you find there.' With that, you are left alone again, the soil drinking the result of your breeding.";
			else: [Vaginal Sex]
				say "     Grinning at you with a gleam in his eye, Zeus raises his arms, the sky turning black above him. With a loud boom, a lightning bolt strikes the hill above you, the flash blinding you for a moment. When the stars clear from your vision, the lion has returned, its coat resplendent. Another noticeable feature is the erect pink cock bobbing beneath his golden stomach, a fine gleam of pre shining. His behavior, for it is definitely a he, is closer to that of a house cat, friendly without wishing to appear too much so, brushing against Zeus's leg as it walks past. 'I'm looking forward to this,' you hear the god mutter to himself, patting the lion between his ears. 'I suppose I'll leave you to it. Don't worry, he's a lot tamer now so any wounds you get shouldn't be too serious. Oh, and he'll be banished once you orgasm so try and forgive him if he's a little rough.' With that, the king of Olympus vanishes in a thunderclap.";
				say "     Now that Zeus is gone, the feline shifts his focus to you, rubbing against your leg and purring. If you consider it sufficiently intelligent, then this might be attempts at bribing you into pleasuring it, and oh how you plan on doing so. [if player is submissive]Crouching beside the lion's engorged penis, you gently begin to stroke his flank, gradually closing in on the twitching organ. Your partner's legs shiver in anticipation, copious fluids dripping onto the soil, exuding an arousing scent that stirs your loins. [else]Gripping its mane, you stare it in the eyes to reinforce your dominance, being rewarded with him shrinking away and baring his throat. Content with his reaction, you crouch beside him and begin to stroke his penis, the aroma of his arousal stirring your loins. [end if]As the friction decreases over his erection, you become curious as to what his impressive cock tastes like and lie on your back below his groin, your control still maintained.";
				WaitLineBreak;
				say "     The lion's musk is much more potent beneath him, filling your nostrils to the point of even flowing into your throat. This aids you to salivate as the earthy flavor tickles your mouth and your patience runs thin. Giving your lips a cursory lick, you slip the feline cock into your mouth, looping your tongue around the shaft to taste his essence. Feeling it rotate in your mouth, you are surprised to see the Nemean Lion turning so that his face is beside your loins. As his tongue makes contact with the sensitive flesh of your vulva you flinch, the rough texture grazing over your clit. In tandem, you orally stimulate each other, both out of desire, but also keeping in mind the final goal of him mounting you. Perhaps with this thought in mind, the lion redoubles his affections, thrusting his tongue deep within your canal and further dampening the moistening walls. Every so often, his tongue unintentionally slips from your depths and laps over the divide between your anus and pussy.";
				say "     Concerned that your reciprocation is lagging behind, you determinedly press your face further and further up his length, his barbed tip slipping through the firm ring at the back of your mouth and down your throat. He lets out a rumble of approval and gives your button a light nip before starting to lightly thrust into your eager mouth. Content to allow this, you focus on circling your tongue around his shaft, slathering his flesh enthusiastically. The smell of musk grows stronger as you both continue, his balls presses into your nose each time he thrusts. From the constant trickle of wetness from your pussy, you doubt it will be long before you are ready and apprehension conflicts with the eagerness to feel the large feline pounding into you. He seems to share your anticipation for what comes next, dismounting your face and circling around to allow you to get on all fours. With all necessary areas suitably slick, you are ready for the main event.";
				WaitLineBreak;
				say "     Looking over your shoulder, you admire his toned form while you wait for him to approach and mount you. He sniffs your cunt for a moment, the wafts of air feeling cool against the sheen of fluid clinging to the lips. With a noise of eagerness, the Nemean Lion heaves himself onto your back and for a moment you wonder whether you will be able to support his weight. As he comes down on top of you, you find your concern to be unfounded. Either he isn't as heavy as he looks or there is some force ensuring your pairing goes smoothly. For a few seconds you relax at the feeling of his warm fur against your naked back before another stimuli takes precedence. With a growl of determination, the lion thrusts forward, impaling your receptive body on his barbed penis. His shaft slips into your vagina with ease, aided by the copious lubricant of saliva and secretions. The barbs around his tip rub against your clip as he thrusts and withdraws, eliciting gasps and moans from you.";
				say "     [if player is submissive]To your surprise, the lion softly grasps your neck in his jaws as he continues to thrust firmly. Beneath a magnificent beast as he pounds you and protectively holds you, you subconsciously feel that this is your natural position. [else]To your surprise, you feel the lion's rough tongue rasping over the back of your neck as he continues to push into you. You may be beneath him, but such affection shows he doesn't think you inferior. [end if]You gradually lower your upper body to the ground as the coupling progresses, your rear being kept raised in order to receive your partner's rigid cock. From the increase in force that accompanies his thrusts, you wonder whether he is getting close to climax. By this time he is nearly pounding you into the ground, his thrusts making his scrotum to slap against your tummy, the sound mingling with the squelches from your stretched pussy. With a magnificent roar, the Nemean Lion cums deep within you, the flood of semen filling your womb and flowing out of the joining as his balls contract against your clitoris.";
				WaitLineBreak;
				say "     A cross between a groan and a sigh bursts from your mouth as the pressure from the hot sperm deep within you sends you over the edge too. Around his still twitching shaft your cunt begins to repeatedly contract, further cum being squeezed from within your body to trickle over your tummy and onto the bottoms of your breasts. With the lion pressed firmly against your backside, you are held in position while you both recover from your orgasmic paralysis. As soon as the feline takes a step back, you collapse on your side, his shaft sliding from your gaping hole, spilling a new river of semen onto the ground. Through the haze of climax, you become concerned about your companion's approaching banishment. 'Don't worry. Banishment isn't death,' a male voice says from behind you. You rapidly turn your head, but see no-one. 'I'm not supposed to be here, so please forgive my not showing myself. But as I was saying, the lion will be fine. Echidna loves her monsters no matter how mundane or unworldly they appear. Good luck in the Labors.'";
				say "     You gather the being is gone from the silence that follows, only broken by the feline's deep purrs and your panting. With a flash of light, the lion vanishes leaving you alone beside a sizable pool of cum. 'Now that that's done, would you like to know your next task?' You jump slightly at the sound of Zeus's voice and resist the urge to cover yourself considering he was probably watching the whole thing. 'Well, from your lack of refusal I'll take that as a yes. You must defeat a hydra of extraordinary size. Once again, I'm not allowed to give you hints, but just in case you didn't get help for the previous labor, there are people in the city with a knowledge of myth so you could possibly ask them for advice.' As he turns to leave, he says over his shoulder, 'you'll find your quarry in the junkyard, but he's larger than the [']normal['] hydras you find there.' With that, you are left alone again, the soil drinking the result of your breeding.";
		else: [Not interested]
			say "     You shake your head, saying that you have no wish to fornicate in any way with your recent adversary. Zeus looks momentarily surprised, but quickly recovers. 'Each to their own I suppose. Would you like to know your next task?' You silently contemplate the effort the previous labor took but before you can reply Zeus continues. 'From your lack of refusal I'll take that as a yes. You must defeat a hydra of extraordinary size. Once again, I'm not allowed to give you hints, but just in case you didn't get help for the previous labor, there are people in the city with a knowledge of myth so you could possibly ask them for advice.' As he turns to leave, he says over his shoulder, 'you'll find your quarry in the junkyard, but he's larger than the [']normal['] hydras you find there.' With that, you are left alone again, slightly annoyed that the god didn't wait for a proper response.";
		now TwelveLaborsStage is 2;
		increase carried of lionskin by 1;
	else if fightoutcome > 19 and fightoutcome < 30: [lost]
		say "     You come round to a landscape devoid of life. The wounds that previously covered your body have mended and, more importantly, you are alive. With a thunderclap, you are no longer alone. A grim faced Zeus looks down at your prone body before speaking, 'You have failed the first Labor. We seemed to have judged you poorly, you are weak and lucky to be alive. In future think properly and make sure you are ready before attempting to overcome challenges you face. We are unlikely to meet with you again. Farewell.' He disappears in another clap of thunder, leaving you alone as rain begins to pelt from the skies. As you sit up, the realization sinks in that while you may have failed, someone made sure you survived your defeat. Who could be mighty enough to defeat the lion when you couldn't?";
	else if fightoutcome is 30: [fled]
		say "     Realizing that the trial ahead of you may be too difficult, you turn and flee. As you retreat, you can hear the large feline pursuing you, snarls and growls encouraging haste. You barely notice the muscular man you pass as you run down the hill going the opposite direction, too focused on your own problems. You continue fleeing for several minutes before you realize that you weren't being chased any more. You turn around to look back at the hill only to find it gone. The expanse of the plains is unadulterated by hills with large lions. 'Don't be too surprised that it's not there anymore,' a voice says behind you. You spin around to find Zeus glaring at you as he strokes his beard. 'Not only did you fail to defeat the Nemean Lion, but your cowardly actions disgrace yourself and us.' This comment is accompanied by the god spitting at your feet.";
		say "     'In future think properly and make sure you are ready before attempting to overcome challenges you face. We are unlikely to meet with you again. Farewell.' He disappears in another clap of thunder, leaving you alone as rain begins to pelt from the skies. While you are glad you aren't dead, Zeus's reaction dampens your spirits in sync with the rain soaking your skin. You finally have time to think back on the man you passed as you ran and wonder who he was and whether he was alright. You feel that you have seen him somewhere but can't quite remember. His muscles were huge so perhaps he was a bodybuilder you think to yourself as you trudge on in search of shelter from the rain. It doesn't look like you'll be taking part in the Labors any more.";
	now Meet the Nemean Lion is resolved;

Section 2 - Table of Game Objects

Table of Game Objects (continued)
name	desc	weight	object
"lionskin"	"The skin of the Nemean Lion. Ethically acquired after completing the first labor of Herakles."	5	lionskin

lionskin is equipment.
It is not temporary.
The AC of lionskin is 100.
The effectiveness of lionskin is 40.
The placement of lionskin is "body".
The descmod of lionskin is "You have the hide of a big cat wrapped around your shoulders.".
The slot of lionskin is "body".

Greek Mythos ends here.
