Kitsune Expansion by Shadowwolf94 begins here.
[Original by Dys]
[Version 1.0 WIP by Dys]
[Version 1.1 complete by Shadowwolf94]

Section 0 - Variables

[None for the moment]

Section 1 - Talk

[To be added]

Section 2 - Sex

to say Kitsune_NewMaleDomScenes:
	say "     [if Player is submissive]Blushing and then whispering into Kitsune's ear after shuffling over to him somewhat nervously[else]Asking the silver fox to have some fun on top today[end if], you realize you should let the vulpine know what you want. Your heart nearly jumps into your throat when you hear the other growl at you in want. An air of faux-dominance comes over the vulpine like a thick fog and instantly you can feel your [if Player is submissive]stomach tighten up into knots[else]excitement begin to grow[end if]. What are you going to request to do with him?";
	blank out the whole of table of fucking options;
	now sextablerun is 0;
	[New Scene!]
	choose a blank row from table of fucking options;
	now title entry is "Service him orally";
	now sortorder entry is 1;
	now description entry is "Have Kitsune shift to his feral form and mount you from the front side";
	[Old Legacy Scene]
	choose a blank row from table of fucking options;
	now title entry is "Let the fox mount you (anal)";
	now sortorder entry is 2;
	now description entry is "Have Kitsune shift to his feral form and mount you, aiming for your backdoor";
	[]
	if Player is female:
		choose a blank row from table of fucking options;
		now title entry is "Let the fox mount you (vaginal)";
		now sortorder entry is 3;
		now description entry is "Have Kitsune shift to his feral form and mount you";
	[New Scene!]
	choose a blank row from table of fucking options;
	now title entry is "Ride his cock (anal)";
	now sortorder entry is 4;
	now description entry is "Ride the fox's cock, letting him use his tails to his advantage";
	[New System!!]
	choose a blank row from table of fucking options;
	now title entry is "Work him up, then control him (anal)";
	now sortorder entry is 5;
	now description entry is "Work him up and order him about from beneath";
	[]
	if Player is male:
		choose a blank row from table of fucking options;
		now title entry is "Have the fox tend to your shaft";
		now sortorder entry is 6;
		now description entry is "Have the fox tend to your shaft";
	sort the table of fucking options in sortorder order;
	repeat with y running from 1 to number of filled rows from table of fucking options:
		choose row y from the table of fucking options;
		say "[link][y] - [title entry][as][y][end link][line break]";
	say "[line break][link]0 - Nevermind[as]0[end link][line break]";
	while sextablerun is 0:
		say "Pick the corresponding number> [run paragraph on]";
		get a number;
		if calcnumber > 0 and calcnumber <= the number of filled rows from table of fucking options:
			now current menu selection is calcnumber;
			choose row calcnumber from table of fucking options;
			say "[title entry]: [description entry]?";
			if Player consents:
				let nam be title entry;
				now sextablerun is 1;
				if nam is:
					-- "Service him orally":
						say "[Kitsune_ServiceOrally]";
					-- "Let the fox mount you (anal)":
						say "[Kitsune_OldAnalDom]";
					-- "Let the fox mount you (vaginal)":
						say "[Kitsune_OldVaginalDom]";
					-- "Ride his cock (anal)":
						say "[Kitsune_RideCockAnal]";
					-- "Work him up, then control him (anal)":
						say "[Kitsune_PowerBottom]";
					-- "Have the fox tend to your shaft":
						say "[Kitsune_OralDom]";
					wait for any key;
		else if calcnumber is 0:
			say "     Kitsune is wagging his tails with a sly smile.";
			now sextablerun is 1;
			wait for any key;
		else:
			say "Invalid selection made. Please pick an option from 0 to [the number of filled rows in the table of fucking options].";
	clear the screen and hyperlink list;

Section 2.1 - Individual Scenes

to say Kitsune_ServiceOrally:
	setmonster "Kitsune";
	say "     [if Player is submissive]Timidly[else]Eagerly[end if], you make your suggestion to the fox, watching his expression to see if he likes the idea. You're met with a small smirk and another lustful growl as the vulpine closes the gap between the two of you, locking his muzzle with your [if Player is MuzzleFaced]own in a heated kiss, his tongue flicking across your teeth and into your maw eagerly. The deep French kiss is erotic and exciting, all the things you could've wanted from the wonderful vulpine, and you can't help but melt into his embrace[else]face, his tongue brushing against your lips, seeking entrance. You quickly grant him what he wants, embracing the lustful yet awkward kiss, feeling his tongue swirling around inside your mouth[end if]. Of course, it doesn't last forever. Soon enough, Kitsune breaks the kiss, your mouth connected to his by a strand of saliva. He grins salaciously at you before stepping back and shifting into his quadrupedal form, [if Player is FeralBodied]making sure that his chest is level with the top of your head[else]adjusting his size so the top of his head comes up to your chest[end if].";
	say "     It would seem your silvery companion wants you to enjoy him in his more natural form, which only serves to excite you further. You [if Player is FeralBodied]duck your head down, going into a slight crouch to fit yourself beneath him, wiggling closer to his groin[else]get down on your hands and knees, crawling beneath him to his waiting sheath[end if]. The masculine musk rolling off of him is intoxicating, a wonderful, heady aroma that makes you shiver in arousal. Eager to get started, you extend your tongue to lick along his heavy sack, letting the salty taste fill your senses. Involuntarily, you moan as you continue to work those hefty nuts with your tongue, occasionally taking one into your mouth to suckle. If the small, lustful growl from the fox above you is any indication of how much he's enjoying this, you can't wait to see how much he'll like your next step. You eagerly move on to his sheath, lapping along the plump, fuzzy flesh, feeling it throb and pulse under your teasing tongue. Slowly but surely his length begins to emerge, the entire tool slipping free in just under a minute of your expert treatment.";
	WaitLineBreak;
	say "     Deciding it's time to move on to the main event, you wrap your lips around the tip of his pulsing member. Immediately, a spurt of pre lands on your tongue, setting your taste buds alight with Kitsune's exotic musky flavor, making you desire more. He's not one to deny you this as you feel a gentle tail pressing against the back of your head, urging you on. A low growl reinforces the fox's desire, so you quickly and eagerly oblige him, taking a bit of his length past your lips, swirling your tongue around its girth. You continue this treatment for just a bit longer, electing to tease the vulpine.";
	if scalevalue of Player <= 3: [Small player]
		if Player is twistcapped or "Vore Predator" is listed in feats of Player: [Player is able to take it all.]
			say "     You're only able to play with him for a few moments before he steps forward, suddenly forcing a few inches into your mouth. You moan loudly around the fox's meat, your tongue continuing to caress the parts you can reach as his hips gently buck, using your maw as one may use a more traditional orifice. You hear him huff and growl as he takes another step forward, forcing another few inches into you, this time breaching your throat and bulging it lewdly. Further and further the fox presses in before his knot finally kisses your lips, a promise of what you know is coming soon. He withdraws about halfway, his tails moving sporadically behind him betraying just how much he's enjoying this, their movements jolting and twitching as he thrust in once more. His knot pats against your lips with every thrust he makes, getting louder and louder as he grows more determined to tie you. You can feel his cock twitching and throbbing as his climax approaches, but it seems he [italic type]needs[roman type] that extra pleasure from tying to push him over the edge.";
			WaitLineBreak;
			say "     With a low growl of determination, Kitsune pushes into you with all his might, a tail holding your head still as his knot finally pushes past your resisting jaw. Alarmingly, though, he doesn't stop there, instead using a tail to spread your jaw even wider, pushing even further, taking advantage of your body's twisted properties as even his knot nears your throat. He pushes hard, giving a low growl as he feels your pliable form yielding around him, his knot finally slipping into your throat where it begins to swell, well and truly locking you together. Thankfully your corrupted form allows you to take it without pain, even as his knot reaches its full size and his climax begins. His entire cock undulates and twitches as he begins to spurt rope after rope of his hot vulpine seed into your depths, nearly going straight into your stomach. All that cum flowing into you with nowhere to go causes your stomach to swell steadily, to the point you almost start to look pregnant. Finally, after what feels like an eternity, his climax begins to taper off, ending with just a few smaller spurts of thick cum.";
			say "     Now the two of you simply lie in wait, Kitsune panting in exhaustion. He's truly given you everything he has, yet even still his tails gently caress your form, doing his best to help you relax as the two of you wait for his knot to go down.";
		else: [Player is unable to take it all, though depending on chance, Kitsune might force the knot in anyway.]
			if a random chance of 3 in 4 succeeds:
				say "     Eventually, you move your head down, taking more and more of Kitsune's length into your mouth, soon feeling his tapered tip pressing against the back of your throat. You give a soft whine of disappointment at being unable to take more, but a gentle growl from the fox gives you a boost of determination. You rise off of his length until only his tip remains in your mouth, flicking your tongue around it a bit before slowly taking it to the back of your throat once more. This time, you actively try to feed yourself more of the shaft, feeling the tip beginning to spread your throat wide. You grimace in slight pain, but press on, trying your best to please him. Throat bulging outwards, you eventually have to stop. This doesn't seem to bother Kitsune as he looks at you lustfully, tails gently caressing your form as you work his cock.";
				WaitLineBreak;
				say "     Seeming pleased with your effort thus far, his tails wrap around your form, stopping you as he decides to take over the fun. He growls lustfully as he thrusts into your [if Player is MuzzleFaced]maw[else]mouth[end if]. He's not too harsh, but fast enough that you can tell he's beginning to approach his climax. He grunts as his cock twitches and throbs inside you, and you [if Player is FeralBodied]moan eagerly as you feel his thrusts growing more frantic, driving him closer and closer to his impending climax[else]decide to give him that last bit of help to push him over the edge, hands reaching up to grip at his knot, feeling it pulse and throb under your fingers[end if]. With a loud howl, he cums, thick strands of fox cum spilling straight down your throat. You do your best to swallow down the seed, but the sheer volume of it is a bit too much to handle, and some of it spills from the corners of your mouth. Eventually, his flow tapers down, your belly bloated with what you were able to swallow and your body stained with what you weren't. He gives you a pleased, happy look as he pulls his cock from your mouth, turning around to give your face a gentle lick as he comes down from his high.";
			else:
				say "     It seems that your teasing manages to get to the vulpine as he lets out a low growl before gently thrusting into your mouth. You moan eagerly as his tip prods against your throat, his length retreating only to press in once more. Each thrust grows just a bit faster and a bit deeper, his tip eventually pushing its way into your throat and bulging your neck with his girth. He lets out a pleasured growl as he feels your tight confines rippling around his length, making him near his climax even faster. He places a tail around your head, keeping it in place as his knot pats against your lips, his thrusts shortening, growing harder. He's determined to tie himself to your [if Player is MuzzleFaced]muzzle[else]face[end if], clearly desiring to seal every drop of his seed inside you. At first, you don't think he'll succeed, but eventually, his determination beats out your jaw's resistance, his knot slipping past your teeth with a lewd pop.";
				WaitLineBreak;
				say "     You let out a shuddering breath as you feel his cock throbbing and pulsing, his knot swelling to its full size behind your teeth, locking you to him for the full duration of his orgasm. He gives a soft howl of pleasure as he begins to cum, pumping his foxy seed straight down your throat. Rope after rope of rich ejaculate spills into you, slowly and steadily filling your stomach to bulging. It feels like an eternity before his climax comes to an end, your belly packed with his seed. Now you simply wait, attached to his knot until it finally goes down.";
	else:
		say "     Another soft growl from the fox urges you on, [if Player is FeralBodied]taking a step forward to take another few inches of his shaft into your mouth[else]wrapping your hands around his shaft just a bit further down, giving it gentle pumps as you take another few inches into your mouth eagerly[end if]. Kitsune lets you continue on your own for a bit, but he seems to be growing a tad bit impatient as his hips suddenly lurch forward, cramming another several inches into you. You can feel his tip press against the back of your throat and you can't help but let out a low moan as he starts thrusting into your mouth at a gentle yet steady pace. As he grows more and more eager, his thrusts get faster and faster until he manages to breach your throat, pressing the final few inches up to the knot inside your mouth. He growls and barks as he redoubles his efforts, his large knot making soft pats as he works to get it past your lips. Harder and harder he presses, until finally, it slips in with a lewd pop. It quickly begins to throb and swell even larger, locking it behind your teeth until he's well and truly finished with you.";
		WaitLineBreak;
		say "     You groan lowly around the cock embedded in your mouth and throat, body jolting gently as Kitsune makes his final thrusts to push himself over the edge. You can feel his entire shaft undulate and throb as he reaches his climax, the rush of rich fox seed spilling straight down your throat. You do your best to gulp it down eager, rope of rope of the thick cream quickly filling your stomach. It does stop at that, though, the flow continuing until your belly starts to swell with its volume. Only then does the stream seem to taper off, slowly but surely ending with a final few spurts. You feel a tail gently caressing your belly as Kitsune lets out a content rumble. It seems the two of you will be stuck like this for a fair bit while the fox's afterglow wears off.";
		PlayerEat 15;
		PlayerDrink 15;
	Kitsune_FuckFinish;


to say Kitsune_RideCockAnal:
	setmonster "Kitsune";
	say "     The silver vulpine smirks and wiggles his tails seductively, eyes running over your [if Player is FeralBodied]feral form[else]attractive body[end if], drinking in every detail. He gives a playful growl, walking around you slowly, his tails caressing against your form, making you shiver with desire under their teasing touch. All too soo, the treatment ends, and your left watching as he lies on his back, his body slowly shifting into his quadrupedal form. Once his change is complete, he looks at you with that same look as before, gesturing with his tails, inviting you to climb atop him. [if Player is FeralBodied]You do your best to avoid putting too much weight on his, careful footfalls going around the silver fox as you position yourself above his larger body, your chest rubbing against his own fluffy form[else]Not wanting to keep your lovely companion waiting, you clamber atop his larger form, positioning your rear just above his sheath, feeling his soft fur against you[end if].";
	say "     The vulpine doesn't let you sit idle for long as you feel a few of his prehensile silver tails wrap themselves around your body. For what they are, the appendages are rather strong, gently lifting you and positioning your rear directly above his sheath, the feeling of that hot fuzzy tube against your hole exciting and enticing, making you wiggle in excitement. [if Player is male]Another tail comes around to your already-erecting cock, the soft fur running slowly against sensitive flesh, making you moan quietly as he teases you. [end if][if Player is female]At the same time, the fox brings another silver tail-tip to your clit, the bristly-yet-soft fur flicking across that sensitive nub, making you shudder. [end if]With a lustful growl, he gives a gentle buck against you, his sheath bunching up against you, his length eager to come out.";
	WaitLineBreak;
	say "     The fox gives a huff as his length begins to grow free of its home. You can feel its slick warmth sliding across your hole, making you shudder in anticipation. You can feel its girth each time he presses that tapered tip against your ring, every time he pushes against you in an effort to bury his bone inside you. You don't have to wait long for him to accomplish this goal, Kitsune letting out a low, pleasured rumble as he feels his tip slowly sink into your tract. You moan, feeling yourself stretch around him, the fox somehow the perfect size to make you ache ever-so-slightly, the perfect amount to be pleasurable. His tails['] grip on you grows stronger[if Player is herm], the teasing touch against your maleness grows just a bit firmer, and his tailtip against your slit thankfully ceases its effects for now[else if Player is male], the teasing touch against your maleness growing just a bit firmer[else if Player is female], his tailtip against your clit thankfully ceasing its efforts for now[end if] as the vulpine moves your form into a better position, his length continuing to erect and grow inside of you. It's a deeply intimate feeling, and you can't help but shudder slightly as your feel his length finally slowing in its growth, a new pressure on your ring. The beginnings of his knot press gently against your rear entrance, and the fox looks at you with a teasing expression, making you fully aware of what is to come.";
	say "     With a gentle squeeze, the tails wrapped around your body begin to slowly lift you off of his length. Eventually, only his tip is left inside you, and the fox gives what almost sounds like a growling moan as he brings you back down on his cock. Those prehensile tails move you up and down again and again, the fox growing more and more pleasured as it goes on. You can feel him dribbling pre inside you, each thrust growing just a bit stronger, the tapered tip grinding against your prostate every time he presses into you. [if Player is male]You feel his tail against your cock wrapping firmly around it, almost like a stroking hand. In time with his thrusts, his tail firmly strokes along your dripping length, making you moan and buck into his motions eagerly. [end if]Soon enough, the vulpine lets out a pleasured yip, his cock twitching wildly inside you as his tails press you firmly against his crotch. You can feel his knot pulsing, growing larger even as he works to force it into you, stretching you wider and wider until, finally, it slips in with a wet pop[if Player is male]. You cry out, feeling your cock twitch and throb in his tail's grip, the stroking and the pressure against your prostate enough to finally send you careening over the edge, spilling rope after rope of your load onto the vulpine's belly[end if].";
	WaitLineBreak;
	say "     With a low growl, the fox continues to buck and grind against you, not able to get much movement, tied as you are. Still it soon proves to be enough, Kitsune letting out a lustful howl as he climaxes, spilling his rich vulpine spunk into your depths. None of his copious load is able to escape past the firm seal of his knot, so each and every shot of seed into your body makes your belly bloat just a bit, until his climax finally ends, leaving the both of you panting, waiting for his knot to come down. A wave of exhaustion crashes over you, feeling the sudden desire to rest. You lie down, pressing your [if Player is MuzzleFaced]muzzle into his chest, nuzzling your foxy companion with a happy sigh[else]face into his fluffy chest, nestling in against him with a contented sigh[end if].[mimpregchance]";
	Kitsune_FuckFinish;

[to say Kitsune_VaginalMissionary:
	say "     Shivering as the silver vulpine steps towards you, his paw gently reaches forward to caress your [if Player is FeralBodied]feral form[else]needy body[end if], his tail flicking about behind him. With a sudden tug, he pulls you up against his chest, the heavy scent of this powerful male making your head spin. It fills your thoughts as you feel his paws slide down your back and over your ass, suddenly taking hold and hefting you up into his arms. You let out a small whine of need as he carries you over to the bed, your own needy scent mixing with his as your body prepares itself for what it knows comes next. As he lays you down, you spread out for him, baring everything to the stud about to claim you. His paws slide over your hips as your eyes are drawn down towards his crotch, that plump sheath swelling as the tip of his shaft starts to slip out.";
	say "     Squirming beneath his gaze, you feel his paws exploring your body, caressing your [if Breast Size of Player > 0]supple breasts[else]chest[end if] as he moves on top of you. A thick drop of pre leaking out of his swelling shaft as he slides his paw down your stomach, slowly making his way down to your crotch. He pauses for a moment to admire your [if Player is male]shaft and [end if]pussy, licking his lips and growling possessively. Taking hold of your hips, he presses the tip of his shaft against your folds, letting his pre spread across them as you squirm in his grasp, your needy folds [if Player is male]and pulsing shaft [end if]crying out for attention.";
	WaitLineBreak;
	say "     ";
	Kitsune_FuckFinish;]


to say Kitsune_PowerBottom:
	setmonster "Kitsune";
	say "     Grinning and pressing up against the silver vulpine, you slide your hand down his stomach and across his crotch, taking hold of his balls as you gently roll them about in your palm. The Kitsune lets out a gasp as you tease and play with him, his shaft quickly swelling and leaking pre. Nibbling along his neck, you continue to work him up, taking hold of his shaft as it swells and gently stoking it, his strong scent filling the air. You whisper into his ear about how badly you want his cock, about how good it's going to feel when he's fucking you good and hard. You hear him let out a needy growl as he reaches around you to take hold of your ass, pulling you close.";
	say "     You stand there, stroking his shaft and winding him up, knowing full well how strong and controlling he can be. You know what will come next, and it'll only take a little more prodding to get him ready. Sliding down to your knees, you run your tongue along his shaft, flicking it against the tip and tasting the droplets of pre that have formed there. His paw comes to rest at the back of your head as he urges you to start sucking. Giving him a sly wink, you instead wrap one hand around the base of his shaft and cup his balls with the other. Stroking and licking at his shaft, you hear his huffs and growls as you tease him, keeping him on edge. Soon, you gently wrap you lips around the tip of his shaft and suckle on it, lapping up every drop of pre that comes spurting out. His hips buck with need as he tries to force more of his shaft into your maw, but you keep him at back, bringing him closer and closer to climax before suddenly pulling back and letting go, leaving him panting and huffing. You see the primal need in his eyes as you stand back up and spin around and quickly make your way over to the bed. His heavy footsteps and heavy breath tell you all you needy to know as you strip down and ready yourself for what's next.";
	WaitLineBreak;
	say "     As the last of your clothes hit the floor his paws come down on your shoulders, gripping them tight and pushing you forward and down onto the bed. Letting out a moan, you sway your hips at him and reach back to spread your cheeks apart. His paws soon take hold of your hips as he climbs up on top of you, his thick shaft grinding against your pucker and coating it in his pre. 'Aww, what's the matter? Did someone leave you unfulfilled?' you say with a teasing tone. His response is a throaty growl and his hips bucking against yours, the tip of his vulpine cock pressing against your asshole. Glancing back at him, you smile and buck back, forcing it in and clenching down around it. His grip tightens as he pushes forward, slamming the rest of his length in, his body leaning over you as he starts to pull back. Not wanting to miss out, you roll your hips and squeeze down hard around him, doing your best to drive him wild. His hips slam back against yours as he starts fucking you in earnest, a paw coming up from your hip to wrap around your chest. With each thrust you can feel the beginnings of his knot forming, the base of his shaft swelling and stretching you open a little more each time.";
	say "     Bracing yourself on one arm, you reach back to run your fingers through his fur. You feel your way around till you find his shoulder and suddenly take hold, pulling him down on top of you as you groan beneath him. 'Is this all you've got? I was expecting something more. Come on already, I came here to get fucked, not lightly massaged. Or are you not the stud you claim to be.' you say as your hips slam back into his. He growls and bites down on the nape of your neck, claiming you as he would a feral bitch. Your hips move in time with his, sliding forward as he pull back, clenching down on the growing knot before it slips out, and then meeting his return thrust with your own. You rolls and twist your hips as you work his shaft inside you, milking out thick spurts of pre that only aid in your endeavors. But all good things must come to an end, and as you feel his knot getting harder to fit past your ring, you dig your hand into his fur and grip it tight, pulling hard as you let out a howl and jam your hip against his, clenching down hard and holding him there as his knot swells inside you.";
	WaitLineBreak;
	say "     He grinds and presses his body against yours as he ties you, desperately trying to push deeper in as your walls squeeze and hold him still. 'Just a little longer. I want to feel you squirming on top of me,' you say as he huffs and growls, trying to get that last bit of stimulation he needs to cum. Deciding he's earned his reward, you relax your muscles for a moment before clenching down as hard as you can on his knot. He howls out above you as his knot and shaft suddenly swell with cum, his length pulsing and throbbing inside you as you feel the warm tingle of his seed inside you, your [if Player is male]own seed staining the sheets beneath you as you reach climax[else if Player is female]feminine juices staining the sheets beneath you as you reach your own climax[else]body shaking in pleasure as you reach your own climax[end if]. Collapsing onto the sheets you smile to yourself as you feel his knot still twitching inside, the occasional spurt of cum making you shiver as you both wait for his knot to come down. Closing your eyes you lay there in bliss.[mimpregchance]";
	Kitsune_FuckFinish;


to say Kitsune_OralDom:
	say "     You watch as the silver vulpine's gaze wanders down to your crotch, his tongue licking across his lips as he lets out a soft growl. Running his paws over your hips, he leans forward and nibbles at your neck playfully, slowly guiding you back towards the bed. You shiver in anticipation as one of his paws brushes across your [if Player is female]moistening folds and [end if]swelling shaft. You let out a whimper as you feel the edge of the bed pressing into the back of your legs, his body pushing up against yours as his paw begins to caress your shaft[if Player is female] and tease your pussy[end if]. With a soft push, you fall back onto the bed and watch helplessly as he takes hold of your legs, slowly spreading them apart with a mischievous grin.";
	say "     With your legs spread wide, he has full access to your [if Player is female]dripping folds and [end if]twitching shaft. You wiggle as his paws slide up your thighs and he drops down to his knees, his muzzle hovering above your crotch as he stares it hungrily. His head dips down as he runs a tongue across your length, making it switch and spurt out a dribble of pre, his body and scent driving your wild while his gaze reminds you to stay still and let him take what he wants. A paw comes up to wrap around your shaft as he laps at the tip, those soft paw pads squeezing and stoking your length as you lay there[if Player is female], pausing occasionally to slip under your balls and give your button a lick[end if]. Bunching the sheets in your hands, you let out a long low moan as your body responds to his every touch, your shaft now dribbling a steady stream of pre that he eagerly laps up. Looking down at him, all you can manage is a pleading expression.";
	WaitLineBreak;
	say "     His eyes light up as sees your face, and he gives your length one long lick from base to tip, before wrapping his lips around it and beginning to gently suck on your suck, his head bobbing ever so slightly as his tongue continue to slick across the tip. Your hips twitch and buck under his ministrations, your body writhing on the bed as his paws caress your form, playing with your body but also keeping you pressed down into the bed. You can feel him beginning to take more and more of your shaft into his muzzle with each bob of his head, his tongue switching from lapping at the tip to slipping around the sides and rolling across the bottom of your cock. You whine and moan with need as he works you up slowly, as soon as he finds a weak spot, he plays with it to get you close, and then backs off to continue exploring. It's driving you crazy, forced to lay there as he holds your release hostage, always so close but never quite enough.";
	say "     Your pre is coming out in heavy spurts now, you can feel him greedily swallowing it down as your tip starts to press into the back of his throat, those tight walls rippling across your head as his tongue presses and grinds along the underside of your cock. You hear and feel him letting out a gently growl as he suddenly presses his muzzle down over your shaft, sliding your shaft into his throat and presses his nose into your crotch. He holds it there as his paws grip your hips, holding you still while the rest of you writhes on the bed. His throat milking your length for all the pre it can give before suddenly pulling his muzzle back and sliding your length out to the tip. You're given the briefest of moments to catch your breath before his mouth slams back down on your cock, his head rapidly bobbing up and down your length, his throat clenching and rippling around your shaft each time it's force in. You throw you head back and yell, back arching as he assaults your cock with his mouth.";
	WaitLineBreak;
	say "     Unable to hold back, you try to thrust your hips up and into his muzzle, but his strong grip keeps you pinned to the bed. Your shaft swelling and pulsing with your climax as you unload into his maw, thick streams of cum painting the back of his throat white as he once more presses his muzzle down into your crotch and gulps around your cock. His gullet works to squeeze every last drop of cum it can from you. Whimpering and twitching on the bed, you ride out your climax like this, your hips held firmly in place as he drinks his fill of your seed. Not long after you taper out, he pulls back and slips your cock out of his lips, licking them with a smile on his face as he gets to his feet. Giving you a wink as you lay there exhausted on the bed, he turns around and saunters off, stretching his arms out and then giving his throat a gentle rubbing.";
	Kitsune_FuckFinish;

Section 2.2 - Functions

to Kitsune_FuckFinish:
	now Kitsunearoused is 2;
	kitsuneinfect;
	now lastfuck of Kitsune is turns;

Section 3 - Legacy Scenes

to say Kitsune_OldAnalDom:
	setmonster "Kitsune";
	say "     Walking past Kitsune to go over to the fox-man's bed, you strip yourself free from your clothing without a word spoken. Letting the fox-man know exactly what you want and how you want it without having to speak a word, you make yourself ready for your lover to take you as you lay yourself down onto the flat of the plush mattress and then wiggle your ass up at the vulpine. Kitsune seems to accept this behavior with good humor as he throws his own loincloth off and then gets down onto his hands and knees to shift his shape into that of his more animal-like form. Watching with wide eyes as the feral fox comes over to you, you don't hesitate in moaning aloud when you feel Kitsune dipping his head down to spread your puckered taint open with his flat, but broad tongue. A whimper pierces free from your lips as the dexterous organ whips its way inside of you all the way up to your [if Player is male]pleasure button and then over the small hidden mound[else]most sensitive depths[end if] until you are visibly jerking up and down on the bed from the spikes of pleasure going through you.";
	say "     You could almost swear that you heard a laugh come from behind you, but this can't be right since Kitsune's muzzle is currently buried up into your ass. Not bothering to wonder on this for long, you gasp and then shiver when the other pulls himself free from your ass and then gives an audible lick of his lips before growling at you hotly. Looking into the other's azure blue eyes, you don't stop yourself from dropping your eyes down to have a look at the vulpine's midsection when a slight tint of red catches the corner of your vision. Twisting your head down some to have a look see at what the fox is packing, you smile approvingly as Kitsune lifts his right rear leg up to show you what you're dealing with. Longer than a foot with a thick girth and a tapered head, the fox's cock is a thing of both beauty and wonder as you look at it with lustful eyes. Dripping from the head of the shaft are thick beads of precum and idly you find yourself wondering what it would be like to have that animal-like cock thrusting into the back of your throat as you bury your face into Kitsune's groin.";
	WaitLineBreak;
	say "     Again you can swear that you can hear a laugh come from Kitsune, but upon snapping your gaze up to the fox's silvery face you find that the vulpine is merely smiling at you instead of all out laughing. You fleetingly wonder if the other can laugh in this form but before you can ponder over this for too long Kitsune has lowered his hind leg back to the floor and is now walking up to you. A lick across your cheek has you smiling at the other and then turning your head around so that you can lower your front more fully onto the mattress of the other's bed. A huff of pleasure comes from Kitsune at seeing you in this position and quickly the fox mounts you like a normal canine would. Four long limbs wrap themselves tightly around your body as Kitsune hugs you firmly up into his furry chest and you have to chuckle at the disbelief of actually wanting to let another creature fuck you in this position, right before you moan as the fox slides his eager cock into your awaiting body. A gasping shudder makes you tense up as the turgid length back behind you moves steadily through your rectum, but before you can become too tight for him to move Kitsune places his head down next to yours to lick you across the face. The calming feel of the fox's tongue sweeping across your lips and nose has you relaxing enough to let the vulpine hilt himself inside of you completely.";
	say "     The touch of fur against your body feels almost electric to you and you don't stop from shuddering as your mate pumps his hips steadily into your ass until he fully inserts himself into your rectum. This fact mixed with the feel of Kitsune's heavy weight on your back and the knowledge that the vulpine is pressed hip to ass with you takes you above and beyond the realm of sensuality as you pant openly into the fox's concerned face. Still looking at you with careful azure eyes Kitsune rumbles quietly to ask you if you are alright. Your answer to him comes when you shove back onto the other's cock with a hard enough push to almost topple the mounted canid. Growling at you for your presumptuousness Kitsune barks once and then curls his legs around you even tighter before starting to drill your ass a new hole. Restless motions make up the play between the both of you as you almost fight the other for the right to breed. Growling and bucking, your hips move in time with Kitsune's own frantic motions as the vulpine taps his furry nuts into your underside. The weight of the furry orbs are so heavy against your taint that you blush somewhat at the knowledge that soon their contents will be swimming around inside of your guts when Kitsune finishes with you.";
	WaitLineBreak;
	say "     Moaning and gripping the sheets of the bed you try not to look into the burning azure eyes of the fox having his way with you, but you can't help but turn your head into Kitsune's as the vulpine laves his tongue across your cheek. Opening your muzzle to swallow the fidgety organ you give your mate a sloppy kiss, the likes of which surprise the hell out of Kitsune, as you continue to push yourself back into the other. The beating your ass is taking is one that you know you're going to regret later on when you try to sit on something, but then again it'll be well worth it you think perversely. That is until you feel a bloated bulge at the end of the fox's cock getting fuller as it gains extra added girth with the every passing second the kitsune uses to hammer himself deeply into your backside. Remembering that canines have knots at the end of their dicks you prepare yourself for the worst when Kitsune's forward thrusts start to become wilder as his bulb grows thicker. When the right leg of the fox goes up into the air you stifle a yelp of pain by biting into the covers when Kitsune finally knots you. Shuddering and crying out as the other buries his bloated orb deeper and deeper into your rectum while still keeping up his restless thrusts, you are not prepared for what happen next.";
	say "     Like the animal he has become Kitsune growls and then snaps his teeth around the juncture between your neck and your throat to symbolize your submission underneath him. Yowling the from pain of wickedly sharp fangs burying themselves into your shoulder you find yourself arching up into the other, exactly what Kitsune wanted you to do, and then howling in ecstasy as orgasm rips through you[if Player is male]. Your up until now ignored cock soon gushes with cum as your climax takes you over the edge and into oblivion[else if Player is female]. Your fluttering nethers twitch and then spread as they ooze honey out from between your legs onto the grassy ground beneath your feet[end if].";
	WaitLineBreak;
	say "     Kitsune is not long in chasing after you in the frantic race towards rapture as the fox lifts his fangs free from your neck and then tips his head up to howl at the ceiling powerfully. A shudder goes through the mythical creature's body just in time for you to feel a blazing heat spill forward into your guts. You have to actually suck air through your teeth as you feel the pressure of the flood going through you so powerfully that it act bursts through into your stomach which subsequently makes you feel dizzy from both the heat and intensity. Because of your position you can't see it, but had you been able to you would have notice a small mound starting to swell up inside of your tummy from the rising tide of fox cum filling you to the brim. Flush with orgasm you can only turn your head to the side to nuzzle Kitsune's snout when the other brings his own head down to pant quietly into your face. This definitely has been an experience that you are looking forward to repeating, you think just before passing out onto the top of Kitsune's bed. You never notice when the other pops himself free from your loosened tunnel an hour later, or to how the vulpine stuffs his tongue underneath your rump to clean his seed from out of you with his playful organ.[mimpregchance]";
	Kitsune_FuckFinish;

to say Kitsune_OldVaginalDom:
	setmonster "Kitsune";
	say "     Bashfully asking Kitsune to fill your wet cunt, you get a surprise when not only does the Kitsune nod to show his acceptance of your request but then backs himself away from you to get down onto all fours. Your eyes are slightly mesmerized as you watch the form of the silver fox-man melt and then shift until - once again - the Kitsune takes on the animal-like form you remember seeing that one time before. Standing as rigid and proud as he had on that day, you blush warmly as you slowly strip off your clothes and then reveal to the Great Dane-sized fox your juicy box. Gaping slightly in readiness for your lover, Kitsune doesn't waste any time as he bumps his canid head into your legs, telling you without words to get down onto your knees. Complying with what your mate wishes, you find yourself getting into the classic doggy position just in time to feel something warm and wet caressing itself onto the sides of your female folds.";
	say "     Turning back to look at the other you can just barely make out the sight of Kitsune's head dipped down into the spread opening of your legs. Blushing somewhat at both the feeling of the fox's thick tongue slipping inside of you and the knowledge of what is going to be stuffing itself into your hot puss soon, you shuffle your thighs open just a little bit more as you silently ask the vulpine to continue preparing you for what's to come. The silver fox seems grateful for your aid because he quickly pushes his cool and moist nose inside of your cunt, well past your clitoris, on close up into the lower area of your cervix. Not knowing how the other is breathing around your honeyed depths, you find yourself not caring much as the fox's tongue is soon cleaning you out and spreading you open into new and unusual dimensions. A few licks later your legs feel like they are about to turn into melted butter and you actually whine like a vixen in heat as you shake your rump for Kitsune to move things forward to the main event. Thankfully Kitsune does just that as he pulls himself out of you to lick his snout just before you can collapse onto the floor. It's a good thing you have some strength remaining to hold yourself up because just as soon as he is done sampling the flavor of your cunt the fox is placing himself up and across your backside.";
	WaitLineBreak;
	say "     You grunt as the weight of the male vulpine bears down on you, but soon that grumble turns into a moan as Kitsune lines himself up with your netherlips and then spears himself home into your depths with a hard, but accurate thrust. A keening cry leaves the two of you, though for very different reasons as you both connect to each other in a primordial way. As for the fox, he is enjoying burying himself deeply into your snatch as the exquisite pleasure of your tightness nearly makes the mythical creature's nine tails stand on end as he slides his hips while slowly pressing deeper into you. For you on the other hand, you find yourself crying out as the girth of the large and tapered animal-like shaft is drilling a new hole inside of you as Kitsune steadily buries his bone inside of your cunt. While there is pleasure in the fox's actions, there is also pain, and you find yourself digging your hands into the grass underneath your body as you will yourself to relax for your mate.";
	say "     By the time Kitsune is pressed flush up against your behind, both you and he are panting for air as the union between you both has become almost fiery in definition. Hot and sweaty from the exertion, you breathe deeply down against the grass before whimpering as Kitsune's narrow vulpine head eases down next to your face to lick a slimy tongue across your cheek. Smiling lovingly to the other, you nod your head to the fox to let him know that you are ready and then brace yourself as Kitsune slowly pulls himself back to withdraw from your snatch. Hard and uncompromising, the long length of the vulpine shaft that Kitsune carries in between his legs slips out of you like a sword leaving a samurai's sheath, and the vulpine pulls out of you until only his tip remains inside of your folds. Still gazing at you with azure eyes filled with concern, you nod at the vulpine and receive a tentative whimper from the dominant male before the other thrusts his haunches fully back into you. Pain and pleasure lance throughout your spine as Kitsune soon starts to breed you like a vixen of his kind.";
	WaitLineBreak;
	say "     Saying that the fox is rough would be a lie, but saying that his motions are gentle would be an even bigger one. Somewhere in between concern and lust, Kitsune fucks you with the passion of the animal that he truly is. Grinding his balls into your backside, hammering his furry hips into your thighs with almost bruising force, the fox moves as though slightly possessed as his rampant cock fills you to the brim while at the same time his tongue caringly licks out across your neck and face, almost soothingly so as he shows his concern for you. Somewhere in the midst of things you might have been flattered by the show of such devotion, but currently all you can do is fight to stay in control of yourself as your eyes threaten to roll back and your tongue hangs out from the overload of physical pleasure. The feel of Kitsune's cock hitting you in all the right spots along the inner folds of your body seems to be igniting a greater fire inside of you as you buck and moan back against the other in an almost unconscious manner.";
	say "     Like a female needing to be bred with pups, you find your body grows hotter and hotter the longer Kitsune pumps his way steadily into your vagina all the way into your cervix. The big animal seems to know what he's doing as the fox wriggles his hips around with somewhat twitchy motions in an effort to get all of your pleasure spots. You gasp, keen, whimper and shout as Kitsune fucks you almost brutally at the same time he is caressing your chin with his tongue. The feeling of something large swelling back behind you snaps you out of your erotic daze as you wonder about the thing in question, but soon your answer comes as Kitsune humps into you once and then twice harder than before and then locks you both together on the end of his knot. Going stock-still both you and the fox freeze as the instinctual information of what has just occurred passes between both of your minds. Once the knowledge has implanted itself into both of your psyches Kitsune raises his head to the ceiling above to howl his release into your fertile cunt. It's only a second after the howl begins that you feel molten heat spread out into your body, causing your already elevated temperature to flare to new heights.";
	WaitLineBreak;
	say "     A visceral scream rents from out of your mouth as you absorb the mythic creature's cum into the inner sanctum of your hot juice box all the way up into your stomach. A second later a trigger goes off somewhere inside of you because without you being conscious of it your body just erupts with heavenly pleasure as your honey floods out and around Kitsune's cock on down onto the other's bulbous girth locking the two of you tightly into each other. The fox seems to enjoy the feeling though because once he lowers his head to the back of your sweat-soaked neck, he quickly moves to take your nape into his jowls and then hold tightly onto you in an animalistic mating hold. A shiver runs up your spine as you realize what this gesture means, but at the same time you can't help but give yourself over to it as your mate continues to fill you to the brim with his seed. Taking a peek to look down at yourself you find that you're stomach is slightly filling out with the fox's cum. A blush forms on your face before you can stop it.";
	say "     By the time Kitsune is ready to relieve himself from inside of your still-tight nethers the other is almost groggy with exhaustion. That doesn't stop him from pulling out of you however when you give a whimper up at him. Pulling his hips back with a slow shuffle, you gasp and then hiss as the half-bloated bulb at the end of the vulpine's cock slides free from you with an audible popping noise. Your legs tense up instinctively as you feel your juice and Kitsune's cum drizzling down from between your legs. Yet you don't have to worry about wasting the precious gift you had been given as before you can blink a firm muzzle and wet tongue are slipping inside of you to clean up the leakage. A slightly perverted smile crosses your face as you think about how thorough your quadruped lover is in his ministrations as you feel his tongue wiggle up on through your tender cervix.[impregchance]";
	Kitsune_FuckFinish;

Kitsune Expansion ends here.
