More Misc Events by Kaleem mcintyre begins here.

"Adds a series of random events to Flexible Survival."


Section 1- Unorthodox Sight

Unorthodox Sight is a situation.
The sarea of Unorthodox Sight is "Red";
when play begins:
	add Unorthodox Sight to badspots of furry;
	add Unorthodox Sight to badspots of guy;

Instead of resolving a Unorthodox Sight:
	say "Feeling a strong sense that something [italic type]weird[roman type] is about to happen around you, you find that your head begins to whip this way and that against your will as you try and figure out what's wrong. Having already braved enough dangers to know to listen to your instinctual senses when they start to scream at you, you find yourself going over to a nearby building corner and then huddling down so that you can scan the area completely for any signs of danger. Yet this feeling doesn't feel hostile, so much as it just feels [italic type]off[roman type] for some reason. Ironically enough you've been through so much that you've actually perfected your sixth sense as you watch two forms walk down the street together, one being led by a leash on all fours while the other is standing tall and proud next to the former. Happily two long and furry tails wag together as the strange pair walk directly to where you are positioned at. Not knowing what the other two might do if they spot you, you crouch back away from them just as they get within ten yards of your position. Remaining quiet as the duo walk past you, you let your eyes go wide as you watch the sight of the two male figures going pass without a care in the world, if the smiles plastered on their faces are anything to speak of.";
	say "Now normally, or what can be considered normal around here anyway, certain bigger and tougher mutants take complete advantage of other smaller and weaker ones, either physically or sexually. However, the scene that played out in front of you two seconds ago defies this form of logic as a latex fox, with all the markings of the vulpine breed, save being entirely made of rubber, had just walked a latex wolf anthro right on by you as though the latter were some kind of loyal pet. The fact that the latex wolf was so much bigger, not to mention more muscular, than the latex fox has you somewhat confused as you wonder why in the world the other was letting the diminutive vulpine parade him around like that. Nothing about the latex fox seemed all that outstanding, especially given the average sized sheath the naked creature was supporting between its legs, however you can't deny what you've just seen as being real. Especially not having turned just in time to see fresh cum oozing out of the backside of the obviously submissive latex wolf. The last you see of the two is the wolf turning to look at his [italic type]master[roman type] and then getting a playful pat on the head from the vulpine. Rising up and then scratching at your head in partial confusion, you take a full on second to wonder about the somewhat unorthodox scene before shrugging your shoulders to dismiss it. It's not really that important anyway... but still... how weird was that?";
	increase score by 1;
	Now Unorthodox Sight is resolved;


Section 2 - Desperation

Desperation is a situation.
The sarea of Desperation is "Outside";

when play begins:
	add Desperation to badspots of girl;

Instead of resolving a Desperation:
	say "Coming across a bunch of soldiers you notice the large grouping of uniformed men and women seemed to have somehow brought a wyvern down onto the ground and were currently staring at the mutant irritably. The large beast, which has to be almost thirty feet long, cries and chirps loudly just as the soldiers begin to shout and kick at it. The desperation in some of the human's voices has your body tensing as you watch from your position on side of the assembled collective. Not saying so much as a word to alert them of your presence you continue to watch what is happening in front of you with a mix of emotions. Your eyes widen as the troops began to viciously beat at the creature with both their boots and the ends of their long assault rifles. Your stomach turns as you note how blood and other fluids are slowly starting to leak around the defenseless creature's body in a quickly growing pool. Why, if they have already downed the mutant, don't they just kill it already?, you think as you watch the viciousness of humanity continue for several seconds. This can't go on, you think as you hear the monster's cries of pain growing steadily louder. It's just not right... but should you really interfere? Aren't the soldiers just doing their job, after all?";
	if the player consents:
		say "White hot fire soon shoots through your mind as you can't watch the soldiers continue torturing the monster any longer until finally something inside of your erupts in anger. Fury born of the raw hatred at seeing life, even a twisted one such as a monsters, being so readily desecrated has you moving from around your place behind the three and then howling a battle cry as you charge at soldiers. Quickly the men and women flip their heads around to look at you, but sadly all they can see is a speeding ball of fury as you crash into the ones closets to the downed wyvern. Throwing the miscreants away from the beast you find yourself looking at all of slightly scared soldiers in anger before suddenly flying into them. Punching and kicking and hissing at the men and women like a mother protecting her young you send the confused soldiers scattering as you savage anyone too slow, or stupid, not to get away from the mutant. By the time you're done with them your knuckles are wet with blood, though whether it belongs to the other humans, the wyverns, or your own you don't know, but it doesn't matter in the face of having sent the others away from your charge. Turning around to look at the poor creature you realize that the wyvern is looking at you intensely with its strange, feline slit eyes. An understanding seems to go through you both as you flush down at the monster. Maybe now would be a good time for you to do some first aid on the creature. Do you even have a medkit?";
		if medkit is owned:
			say "While you're no doctor you manage to use your medical kit to stitch and patch up whatever wounds you can find on the big beast. A few chirps of pain come from the creature, but you just tell it/her/him to grin and bear it as this is the cost of being taken care of. Once you are done however, you take a few steps back to look at your [italic type]patient[roman type] and then nod accordingly when you see the other look over its battered and worn body. Blood quickly stains the bandages that you have wrapped around the wyvern as the mutant tries to get up and quickly you have to hush the thing so that you can stop it from ruining all of your hard work. Quickly comforting the beast into settling down you try and tell it not to move and that it needs to rest before it can recover fully. The monster seems somewhat hesitant about doing so, and looking around you can understand why as the area you both are in is quite open to possible attack, either from the soldiers or other mutants. Giving a sigh of exasperation you slowly pad up to the reptilian creature's muzzle and then pat the wyvern on the snout gently before telling it that you will watch over it. The beast seems to understand, or well you think that it understands you, as it slowly relaxes and then settles down to rest. Once the wyvern is snoring in sleep, you prepare yourself to stand guard over the creature in order to keep your promise.";
			say "Thankfully you encounter little trouble as neither the soldiers or any other mutants come around the vulnerable critter. The size and smell of it probably scaring anything with good common sense off. That soon changes however, when a flock of wyverns soon come around to see about their missing companion. Noticing the large assortment of flying creatures you decide that now it's time to beat feet out of here. You've done your good deed for the day after all.";
			delete medkit;
			increase humanity of player by 10;
			increase score by 10;
		otherwise:
			say "Shaking your head you go over and around the sides of the beast, tending to its wounds the best you can with your limited supplies as you strip your shirt from off of your body to use for makeshift bandages. Tearing off strips of your upper garment, and even your pants in order to have enough material, you work carefully, but determinedly to save the wyvern's life. Ok, well that might be a bit of a stretch as the beast's wounds are not THAT bad, but they are somewhat grisly to look at. The pooling blood had seem to come from many of the small, but numerous wounds that the creature had received and from the looks of it the only way the wyvern would have died is if it had taken too many hits to the head. Never minding this, it takes you a few moments to go over the entirety of the monster from top to tail, but once you do you have to smile in satisfaction as you have done a pretty decent job in patching up the reptilian mutant. Looking to the other to see how it feels you see that your time with mending the other's wounds has been too long for your patient's attention as the wyvern is now asleep. Snorting somewhat in annoyance at the other you find your lips raising up into a genuine smile as you look down at the flying mutate in wonder. While normally you wouldn't ever want to face one of these creatures in battle, you can't help but marvel slightly at the beauty of the critter. Reaching out to stroke the sleeping beast's muzzle you suddenly go rigid as you hear the cries of other wyverns shouting throughout the sky above you.";
			say "You find yourself moving on quick feet as you hightail it away from the other before its friends can come around to see you standing there with their beaten up comrade. Kindness aside, you're not fool enough to try and explain this to a bunch of, what you're sure will be, angry mutants about how you hadn't hurt their friend, but that you have saved its life instead. Mama didn't raise a fool, after all.";
			increase humanity of player by 10;
			increase score by 1;
	otherwise:
		say "The soldiers are just doing their job, you think with some confliction. You have no right to get involved and besides that the wyvern is a freaking monster for cripes sake! Shaking your head you turn to let the uniformed wearing men and women go about their [italic type]duty[roman type] without looking back. The loud chirps of the wyvern seem to grow louder, almost as if calling out for help, but then soon quiet all of a sudden.";
	Now Desperation is resolved;


Section 3 - Family

Family is a situation.
The sarea of Family is "Beach";
when play begins:
	add Family to badspots of furry;
	add Family to badspots of guy;

Instead of resolving a Family:
	say "While making your way towards the beach you find your gaze taking in a very attention-grabbing sight, one that almost makes you misstep as you blink twice just to be sure you're not seeing things. Because there, walking in between two male wolves, is a young fox that looks as though the latter could only have been a teenager by comparison of the larger, not to mention broader, lupine anthros taking point on either side of the smaller creature. If that in itself wasn't so fascinating, the fact that all three were naked, and clearly male by their impressive sheaths, was nothing compared to the sight of the trio holding hands together like family members would on a day out and about. You watch as the young vulpine looks between his two, you can only guess, guardians with a happy smile upon his muzzle and suddenly you find yourself staring at them somberly as they continue to walk down onto the beach. Not really sure why you do it, you follow several yards behind as you wonder where the three are going.";
	say "Your answer comes when notice the three males find their way onto an empty side of the beach and then suddenly stop and let go of their connected hands. Wonder about what's going to happen next your mouth nearly drops as you watch the three start to chase each other around, both of the older wolves taking point in being the [italic type]prey[roman type] for the other two at differentiating points as the three begin a serious play of tag with one another. Following this scene for several minutes, just as the game changes from tag to wrestling, you don't notice it when a tear comes rolling down the side of your cheeks, followed by another and then another, as you suddenly feel the longing need to call you friends and family. If only so you can just hear their voices and let them know that you're okay. This is a good reminder for you that, despite the sexual depravity of this strange and whacked out world, there are still something beautiful left to be found here in the city.";
	increase score by 1;
	now Family is resolved;

Section 4 - Magic

Magic is a situation.
The sarea of Magic is "Mall";

Instead of resolving a Magic:
	say "Heading to the underground sanctum of the mall, aka the sewers, and vehemently wishing it was because you getting paid to see about a lost dog, you find yourself stopping dead in your tracks as you notice someone standing a fifteen feet away from where you are while holding a crystal ball into their hands. Blinking just to be sure that you are seeing right you find yourself going over to the other just in time to watch as the foot wide orb rises up into the air between the cloaked creature hands all the way until it is levitating in front of their unknown person's face. Seeing the other a lot clearer, once you've narrowed the distance between you both to a mere five feet, you find that you can't exactly make out what the other persona exactly is as the cloak and crystal ball hides the other's body and face, respectively, almost perfectly. Opening your mouth to speak you find yourself snapping your jaw shut when a single hand comes up and then waves a single gloved finger at you in admonishment. Not knowing what you did wrong you feel slightly chastised, that is, before the floating orbs comes directly over to hover unswervingly in front of your face.";
	say "Curiosity holds you still as you are not sure of what to do because of the oddity of the situation. You do manage to smile nervously into the beautifully polished ball however, as your reflection shows off your nervousness before gasping in trepidation as images of the city begin to pass over the rim of the ball. Like a TV screen flickering between channels you watch everything from mutants horses fucking each other in the park, to wanton and transformed police officers screwing feline prostitutes in the red light district, to doctors and nurses treating howling and transmogrifying patients in the nearby hospital, to wyverns flapping throughout the sky and getting shot down at by large cannons that the military have set up as a blockade to keep the creatures within the city limits until finally you see yourself again when the images come to a halt. 'This is your world as it is coming to be known by both those here and afar.' Someone says and instantly you find yourself trying to look at the cloaked figure in front of you. The crystal ball blocks off your sights of the other as you lift up and then down and then around to try and have a glance at the unknown person. The speaker, who you guess is the other person continues to talk, despite your humorous antics. 'How do you plan to go about surviving once the present danger has passed, I wonder? You have to know that those in power won't be able to keep this situation under control for too much longer...' A youthful voice asks and immediately you take a step back to have a look at the cloaked figure as the bubbling need to ask them what they mean surges throughout you.";
	say "Fear runs throughout your spine when you don't see the person right where they had been just minutes before. Whipping your head from side to side you try and see if you can find any trace of the unnamed individual your blood begins to run cold as you can find none. The only remnant that the other had even been is the crystal ball still floating listlessly in front of your face, but soon that too takes its leave of you. Shining brightly with an aurora of colors the orb blinks and then pops out of existence. Tiny trails of starry lights float down in the wake of the crystal's departure before they too fade out of existence. The sudden feeling of apprehension makes you take several steps back before you turn and then run away from where you had been, your mind frantically trying to reason with you over what just happened. A playfully jubilant voice chuckles in your ears, the sound being strangely reminiscent of that of the person who had just spoken to you, and quickly you make even faster tracks away from where you had just been. You've totally forgotten why you had even come here in the sewers in the first place.";
	increase score by 1;
	now Magic is resolved;

Section 5 - Auto Shop

Auto Shop is a situation.
The sarea of Auto Shop is "Red";
when play begins:
	add Auto Shop to badspots of furry;
	add Auto Shop to badspots of guy;

Instead of resolving a Auto Shop:
	say " Making your way throughout the city's most notorious district you find yourself pausing as you hear the sounds of a car engine being revved into life. Thinking that maybe the military has found some way to get you, and the other sane civilians out of this hellhole, you quickly race over to a nearby auto shop, whose lights are surprisingly still on. Figuring that the small place must be running on some kind of generator you don't let your mental quandaries stop you from heading into the open garage and then... stopping so fast you nearly leave skid marks on the concrete. What you find inside is indeed a old 2004 four door sedan being accelerated into life, however that's the [italic type]minor[roman type] focus of your visual inspection as you find several canines, and a few feline mutants, all working together to get each other off in the most perverse and raunchy ways possible. Fucking... has long since come to be an outdated terminology for what's happening in here as large dobermans with both six packs and pot bellies rut hard fucksticks inside of the bubbled asses of collies, wolves, and slim felines alike. The stench of male musk is almost stifling in here and you have to take a step back as you try not to suffocate from underneath the heavy fumes of sweat soaked scents billowing into the air.";
	say "With all of this debauchery going on you, after shaking your head to free up your mind, wonder who in the world is gunning the motor of the sedan. Your answer comes when you see a large jaguar rising up and down inside of the front seat of the car as [italic type]something[roman type] manhandles the feline into being thrust up and down into its lap. With the window of the vehicle broken you can see clearly that the muzzle of the jag is parted and drool is leaking from out the sides of the yowling feline's maw as the other gets pounded harder and harder by the unknown creature behind it. You don't even want to say [italic type]man[roman type] because in this fucked up city there are no longer just men who can deep dick your ass as something quite new has been added to the fairer sex of the once human species. You can't see that clearly beyond the black cat shivering and moaning as to what is spreading the other open down below, but what you can see if the Sedan revving up every time the jaguar gets thrust down into the lap of its dominant partner. Obviously, someone has a big foot. Realizing that you won't be receiving any help here you decide to slowly back away out of the shop before any of the guys notice you and decide that you're a prime candidate to be initiated into the workforce. You never notice how many eyes are already on you, some of them looking rather hungrily in your direction as your asshole and elbows are moving like greased lightning away from the opened garage of the auto shop. Sarcastically you snort as the only thing getting [italic type]tuned[roman type] up in there is a bunch of guy's tailholes."; 
	increase score by 1;
	now Auto Shop is resolved;


More Misc Events ends here.