Reptaur by Kaleem mcintyre begins here.

Section 1 - Monster Responses

when play begins:
	add { "Reptaur" } to infections of hermaphrodite;
	add { "Reptaur" } to infections of furry;
	add { "Reptaur" } to infections of tailweapon;

to say Reptaurdesc:
	setmongender 5; [creature is herm]
	say "     The slow and quiet thumps of feet hitting the ground draws your attention just in time to see the scaly figure of a four-legged reptile-morph coming at you, its dark eyes burning with quiet rage. You swallow thickly as you note the pervasive scent of male musk and sweat that emanates from the creature's muscular form. While normally you wouldn't be too mindful of facing down an overgrown reptile mutant, this one gives you some pause for thought. With an upper body that looks like a cross between a serpent and a man, the thing is covered in [one of]green[or]red[or]brown[or]dark orange[at random] scales and has a thick eight-pack making up its torso. From the waist down, there are four horse-like legs that come to an end at clawed feet instead of hooves and a six foot tail that looks thick and heavy. You ready yourself to face this strange and dauntingly mutated beast.";

to say losetoReptaur:
	say "Getting pounced on and then knocked to the ground the Reptaur hisses in front of your [facename of player] face before roughly tearing you out of your clothes. By the glower in the reptile's dark eyes it looks as though it's about to take whatever sexual frustration its feeling out on you.";
	if player is male:
		if a random chance of 1 in 3 succeeds:
			say "Watching the Reptaur as it looks down at your cock with a somewhat unreadable expression on its scaly face you find yourself getting a tad bit nervous as think over what the creature may do next. When the Reptaur lowers its head down to begin breathing over your dick you actually meep slightly when its cool, moist muzzle opens itself to swallow around your manhood. Moaning and grunting from the feeling of being sucked off you find yourself purring almost when a large and slightly rough feeling palm reaches down to caress itself across you're the underside of your taint.";
			say "When a long, but thin tongue wraps itself around your cock you take in a sharp breath of air as a trail of fire races down throughout your spine. The sensation of the serpentine creature's thin, but dexterous tongue wrapping around your manhood has you desperate to spill your cum into the Reptaur's throat. When the reptile begins to bobs its head up and down onto your lap you know that it won't be long before you climax as you feel your balls churn their contents within your sac. Quickly you find yourself getting into things as you raise one of your hands up to guide the creature's scaled head into giving you a perfect blowjob. You try not to notice how this makes the Reptaur hiss at you in warning.";
			WaitLineBreak;
			Say "Before the Reptaur can get too incensed you gasp and then whimper before flooding the reptile's throat with your cum. The scaly creature makes no bones about drinking down your seed as it quietly rumbles in the back of its throat, seemingly a bit pleased with your taste. Minutes later, when you have no more to give, the Reptaur shrugs your hand off of its head, takes a few steps back away from you, licks its whip thin tongue over the front of its muzzle, and then goes off about its way as if nothing strange has happened.";
			Say "Nothing about this would be so bad if a sudden jolt of pain didn't force your gaze down to have a look over two sharp pinprick oozing yellow venom down the side of your thigh.";
		else if a random chance of 1 in 3 succeeds:
			Say "As you watch the Reptaur walk its massive body over your own bruised and battered form you find yourself slightly confused as to the creature intentions, that is, right up until the scaly mutant plants its rear down directly onto your manhood. The fight must have turned you on more than you thought because for some reason you are as hard as a rock down below. Grunting from the tight feel of [italic type]something[roman type] warm and moist gripping at your cock you don't have time to think about the oddity of what's happening as the Reptaur takes you into its arms, bends its head down to nuzzle its snout into your hair and then quietly hisses a pleasurable croon into your ear. When the other begins to buck its hind quarters up and down onto your lap your mind actually goes white for a second as the tight grip of the Reptaur's nethers hug your cock into an almost unrelenting grip.";
			WaitLineBreak;
			Say "Thankfully, as the serpentine creature slides itself up and down onto you, the tight and slightly wet feel of something sticky helps to ease the pressure up off from around your cock making it so you no longer see stars popping in front of your eyes. Thrusting your hips up into the creature's warm depths without thought you clench your eyes and look up at the Reptaur as the reptile flicks its serpentine tongue over and across your [facename of player] face almost lovingly, a far cry from the creature's earlier hostility while in battle. As the Reptaur's smooth and deliciously wonderful rump pumps itself against your [bodyname of player] body you almost feel like you're heaven as you jack hammer yourself up into the creature with equally forceful strokes of your own hips.";
			WaitLineBreak;
			Say "As the seconds turn into minutes the pace set between you and the Reptaur steadily increases as you and then mutant fuck each other with progressively stronger bucks, both of you equaling the strength the other exerts, as your cum begins to boil inside of your balls. Groaning as you reach the point of no return you arch into the reptile holding you down just as your cock strokes over that all too familiar pleasurable spot inside of the Reptaur's vice tight backside to urge the mutant into its climax. You find yourself cumming seconds later however, as your balls shoot their load into the Reptaur, but instead of moaning in rapture you find your throat tightening in pain as agony rips throughout your shoulder.";
			WaitLineBreak;
			Say "Jaws locked firmly into your shoulder blade the Reptaur hisses its orgasm into your flesh as something milky and thick covers your groin. With your shoulder screaming in pain you gaze at the Reptaur, with its muscles taunt and its body shivering from the physical exertion the serpentine creature just spent, as the reptile's impossibly long tail hikes itself up into the air before everything goes black. When next you come to you find the Reptuar pulling its fangs back from your shoulder as it hisses the end of its climax into your face. Turning your head slightly to see yellow venom dripping out of the pinpricks you find yourself ruefully chuckling at the oddity of what just happened, that is, right before you watch your scaly master pull itself up from your body to turn to go off on its way.";
			Say "This might not have been so odd, had you not found yourself looking at your cum dripping out of the creature's well worn cunt.";
		else:
			if bodyname of player is not "Reptaur":
				say "When the Reptaur grabs you by the leg and then bodily lifts you up into its scaly face by your neck you find yourself grasping and then grunting in pain as the reptile squeezes the air out from your lungs. Momentary panic makes you wonder what's about to happen next, but when your answer comes it comes laced with pain instead of just understanding. As fangs snap down onto your [bodyname of player] neck you stifle a yell as you feel the venom of the other surge throughout your body as your mind goes wild with panic.";
				say "Seconds later the Reptaur pulls its jaw away from your neck and then drops you to the ground like a sack of rice. Quickly watching as the serpentine creature charges away from you, you somewhat robotically reach up to rub a hand across your sore neck as tingles of warmth radiate throughout your body.";
			else:
				say "Seeing your [bodyname of player] form lying defeat the other Reptaur hisses quietly down into your face before turning around to present itself to you. The tantalizing sight of the other's feminine nether lips, gaping slightly and oozing a slick trail of juice down its backside, has your body hastily getting up off of the ground like a shot. However, going over to the other and then trying to mount the Reptaur nets you a hard bite onto the side of the neck by the reptilian mutant. Backing away in confusion you find the other serpentine creature hissing at you playfully and then charging off away from some feet away.";
				WaitLineBreak;
				say "Confused by this strange display you're not sure what this is all about, that is, until the Reptaur stops and then wags it rump at you. Seeing that the other reptile wants to play at the expense of your rising lust you end up chasing the scaly mutant around for several long minutes before finally cornering the other Reptaur and then forcing it to submit to you. You never notice how you snap and hiss at your would be playmate as you mount the feral mutant, your arms hugging tight around the front of the other reptile's chest to hold it steady, as your hips try to forcefully thrust into the unseen depths of the other. All your mind is focused on is getting to the sweet cunt of your brethren Reptaur and then seeding the serpent beneath you with your brood.";
				WaitLineBreak;
				say "Your cock quickly finds purchase inside of the hot and moist cunt of the other Reptaur and don't stop the croon of glee that purses free from your lips as you quickly hump yourself into your lover with almost furious thrusts of your hips. Arching its hips and then hissing a groan of pleasure the other reptile bows its head as it submits itself to your forceful acquisition of its body. Grunting and moaning in pleasure you take the side of the other Reptaur's shoulder into your [facename of player] jaw and then hold it down as you proceed to quicken your pace.";
				WaitLineBreak;
				say "Hammering your pelvis into the other reptile's backside you can feel your already overly excited body getting hotter as your cum churns around inside of your balls, threatening to give up their contents at any second now. Releasing the other's shoulder you hiss quietly into the Reptaur's neck as you hump with several more powerful thrusts before stilling and then unleashing your cum in a massive wave inside of the other serpent's body. Your warm seed flooding your playmate's cunt sends your submissive lover into a frenzy as the Reptuar beneath you gasps and then shudders before lifting its tail up high in a sign of acquiescence. You smirk as you can feel the juices of the other's pussy drenching down the side of your groin, but you keep the other held steady until you have finished with it.";
		infect "Reptaur";
 	else:
		if a random chance of 1 in 2 succeeds:
			say "Sniffing at your prone body the Reptaur makes it move to have its way with you as it lowers its scaly lower end onto the ground and then grabs you with its forward front legs. Acting as pseudo-hands the appendages haul you up and then turn your [bodyname of player] body over to that you are facing away from the creature. Not that this helps your situation any as the Reptaur hikes your body up and then centers your cunt down onto its slick reptilian cock pushing out from the mutant's genital slit. The thick length of reptile flesh quickly slips up into your cervix and soon begins to drill inside of your womb as the Reptaur thrusts you up and down onto his lap.";
			WaitLineBreak;
			say "[if breasts of player > 0]Grunting and hissing while pumping your body up and down the Reptaur slips one of the arms connected to his torso down to grip at your breasts. Squeezing and fondling your ample tits the Reptaur has you moaning and panting in time with his powerful thrusts as he humps his muscles hips quicker and more passionately into your body[end if].";
			say "Reptilian cock gushing with pre down onto your thighs the Reptaur grunts and then lowers his scaled snout down next to your face, flicking his tongue out to tease the shell of your ear, to quietly croons into your face. You're not sure what this is on about but when the other trails his fangs down alongside of your shoulder you find your breaths coming out in quick pants as you wonder... When said fangs find their home inside of your skin you yell out to the sky as white fire burns a trail down the back of your spine on into your belly. The fact that the Reptaur's jack hammering thrusts are getting stronger now as he all but pounds you onto his cock like his personal sexual toy makes things all the more intense as your body responds to the creature by tightening your cunt around his cock.";
			WaitLineBreak;
			say "Fangs holding you tight and cock leaking pre down the side of your legs you find yourself slipping in and out of a world of delirium as both pleasure and pain battle for supremacy inside of your head. However, it's the wet warmth of the scaly mutant filling your depths to the brim with his cum that has you climaxing in seconds as gush after gush of hot cum surges out to puddle down on the ground between the two of you. It take several minutes before the last of the Reptaur's sticky cum has trailed out of his internal balls before the serpentine creature pulls you up off of his now matted lap. Bizarrely enough the creature is actually gentle as he set you onto your unsteady feet before getting back onto his four feet to go off about his way.[impregchance]";
		else:
			if bodyname of player is not "Reptaur":
				say "When the Reptaur grabs you up and then brings you into his hold you find yourself slightly confused as to what's about to happen as you focus in on the claws holding onto your throat. However, when the scaly creature runs its long serpentine tongue across your [facename of player] neck you find yourself calmed by the smooth and moist organ playfully teasing its way across your throat. This proves to be a fatal mistake on your part because quickly the serpent bites down onto your shoulder sending a sharp wave of pain racing throughout your spine. Gasping and then yelping as you instinctually flail around in an effort to try and get away you find the Reptaur holding onto you tightly as its venom seeps into your bloodstream.";
				WaitLineBreak;
				say "Seconds later, when its venom has completely seeped into you, the Reptaur pulls its jaw back from off of your tender, and now aching skin, and then gently sets you onto the ground. Without a word it turns and then leaves you. Idly you reach up to rub the side of your healing neck as confusion sweeps throughout your mind.";
			else:
				say "Maybe it's because you possess the body of a Reptaur, or maybe it's has something to do with something else, you're not sure, but when the reptilian creature in front of you hisses his dominance into your face your entire form actually freezes as something instinctual surges throughout every cell of your being. The Reptaur wastes little time in letting you figure things out as he hefts you up and then bodily forces you to turn around to present your rump to him. A shiver racks down the side of your back as you lift your tail for the Reptaur growling quietly behind you.";
				WaitLineBreak;
				say "When you feel the other climb up onto you, you brace your weight against the ground as you prepare yourself to be filled by the firth of dominant reptile. The smooth feeling of the serpent's chest and lower end caressing its way across your backside follows a slow jab of something hard and moist trying to find its way inside of your cunt. Hissing and groaning as that [']something['] finds its way into you and then plows up into your cervix you moan a pleasurable croon to the sky, right before two thick and muscles arms come up to grab you around your chest to pull you back tightly into the Reptaur. A playful flick of a tongue at your ear makes you shudder just in time for the scaly mutant to begin fucking you.";
				WaitLineBreak;
				say "The steady sway of the other's hips into your own has your heart pounding loudly inside of your ears, but that proves to be nothing compared to the feeling hilted by the large and slightly pointed shaft of the reptile over and over again. Grinding himself into your rump the Reptaur nips at the side of your neck, his fangs just shy of threatening to bite down onto your scaly neck, making you arch and then hiss loudly as you feel your playmate quickening his pace. Clenching the talons of your four feet into the ground your buck yourself back into the other reptile just as the lips of your cunt begin to flutter around the shaft digging further into you.";
				WaitLineBreak;
				say "The warmth of the Reptaur's breath onto your shoulder coupled with the feel of his oozing cock juicing your pussy makes a heavy flush stain across your face as your body goes into overload. Grunting and then gasping in rapture you nuzzle your [facename of player] head back into the reptile's throat just as you feel your climax about to overtake you. As your tight nethers slap close around the Reptaur the scaly beast roars out his orgasm as he thrust into you powerfully once and then twice before going still.";
				WaitLineBreak;
				say "The feeling of his cum seeding your womb makes a thrill shoot through you as your honeyed reptile juice seeps out to flow down your backside as well as the groin of Reptaur above you. It takes a few minutes for the other to finish, but once he does the scaly mutant pulls himself out of your thoroughly used cunt with a wet slurp and then licks you across the neck before going off about his way. It takes you several seconds to find your composure after that, especially as you shiver from the feeling of the other dripping down your legs.[impregchance]";
		infect "Reptaur";


to say beattheReptaur:
	say "Sweeping the Reptaur's front legs out from under it you end up making the reptilian creature stumble into a half bow before you. Humbled by its defeat the Reptaur growls while looking at you with seething anger glowing hot in its dark eyes.";
	if libido of player > 40:
		say "Despite the rage glowing in the Reptaur's eyes you can smell the musky scent of its arousal rising high throughout the air.";
		say "     [bold type]Feel like trying to get it on with the incensed reptile?[roman type][line break]";
		LineBreak;
		say "     ([link]Y[as]y[end link]) - Yes.";
		say "     ([link]N[as]n[end link]) - No.";
		if the player consents:
			LineBreak;
			say "Wanting to feel those luxurious looking scales hugged up against your own [bodyname of player] form you step closer to the Reptaur to smirk at it playfully.";
			if player is female:
				say "     [bold type]Do you want to have the Reptaur please you orally or would you rather do something else to the creature?[roman type][line break]";
				LineBreak;
				say "     ([link]Y[as]y[end link]) - Oral.";
				say "     ([link]N[as]n[end link]) - Other.";
				if player consents:
					LineBreak;
					say "Removing yourself from your clothes you bring the Reptaur's head down towards your leaking cunt and then spread your legs wide for the other. When the reptile's serpentine tongue snakes itself into your cunt you gasp and then arch before spreading your legs wide. When two strong and scaly hands come up to take your waist into a firm and unrelenting hold you soon you find yourself being given the kind of oral pleasure no mammal could compare with.";
					WaitLineBreak;
					say "As the Reptaur's hot tongue slips up inside of your cervix your fingers clench and then unclench as you reach up to grip the side of the Reptaur's shoulders. Grunting a moan you bring the Reptaur closer into your body as you feel the first spark of your climax about to approach. Legs trembling and knees threatening to give out you rub your groin into the scaly mutant's face with slow and teasing sways of your hips as you grunt while trying to hold back your climax. It's only through holding onto the reptile's shoulders that you find any strength to keep from falling onto your ass. The Reptaur seems not to mind this as his tongue flicks up inside of your body, sending more and more shocks of pleasure on up throughout.";
					WaitLineBreak;
					say "When your nethers begin to tighten along his tongue as the Reptaur continues to slurp his way throughout the inside of your cunt you bite the edge of your lip as your mind begins to slowly explode from the buildup of sexual energy quaking inside of your guts. The doggedness of the reptile's tireless organ to move itself up and around inside of you has your mouth panting with quiet gasps as your vision begins to grow dim.";
					WaitLineBreak;
					say "It takes maybe a minute more of this before you climax hits you, but when it does your orgasm is so much that you actually flood the Reptaur's face with enough juice that you force it to pull back from you just to be able to breathe. Of course this doesn't stop your juices from trailing out from between your legs as you cry up at the [if daytimer is day]blue sky[else]darkened sky[end if] while you steadily thrust your hips into the Reptaur's muzzle. Your rush of ecstasy tapers off minutes later, but once it does your slowly release the Reptaur from your hold and then kiss it over the snout before shakily going off about your way. This action leaves the reptile looking very confused behind you as the serpentine creature licks its thoroughly soaked face with its tongue.";
				else:
					LineBreak;
					say "Having beaten the beast you bay the Reptaur to stand after waving your hands up in front of the creature's scaly face. Not sure, the reptile hesitantly does as you command, though not without glaring at you in warning. You pay the serpentine beast no attention as you walk around beside it, and then finally behind it, to have a look for the other's cock. When you look over the Reptaur's genital slit, slightly pushed open with the barest hint of its manhood pushing out, you bend yourself down and then give the scaly creature some much-needed... incentive to become erect as you lick your tongue around the edges of the other's protective opening.";
					WaitLineBreak;
					say "The first touch of your tongue along the creature's slightly moistened cock has the Reptaur shivering and then moaning with pleasure. Probably never getting something like this before, the serpent seems all too eager to let you have its way as it shuffles its back legs wide enough for you to slip underneath the beast. It's long and dexterous tail rising up like a flag into the sky you smirk around your delicious treat you kiss and suck while bobbing your head along the reptile's mouthwatering shaft.";
					WaitLineBreak;
					say "Tonguing at the other for several minutes finds you swallowing the Reptaur's precum into the pit of your throat as the reptile's tapered tip pushes further down bypassing whatever gag reflex you might have once possessed. Bobbing your head while reaching up to caress what you can't deep throat you listen as the Reptaur above you croons and hisses while hobbling its massive hips further into your face.";
					say "     [bold type]As the taste of the serpent becomes thicker on your palate you wonder if you should try and get the Reptaur to mount you or just let it cum inside of your throat?[roman type][line break]";
					LineBreak;
					say "     ([link]Y[as]y[end link]) - Cunt.";
					say "     ([link]N[as]n[end link]) - Throat.";
					if player consents:
						LineBreak;
						say "Wanting to feel the heat of the serpent's seed buried deep inside of your womb you pull your face back from the Reptaur's cock, slurping your lips over the long piece of maleness just because you can, and then roll yourself around so that you can maneuver yourself around to connect your cunt with the mutant's cock. Once you are ready you push yourself back against the scaly mutant to signal your readiness to be fucked.";
						WaitLineBreak;
						say "The Reptaur wastes no time in giving you what you want as it pushes its hips down until its cock meets the tender folds of your pussy. Once that happens the scaly creature slowly begins to drive its long shaft in and out of you as it works to find a proper rhythm with which to ignite the flames of passion between the both of you. Getting to the hilt without any extra added trouble from you proves to make things much simpler for the Reptaur as it humps itself back and forth into your nonresistant form while it digs its feet firmly into the ground. A groan has you shivering in bliss from the feel of your reptile lover mounting you, but soon that vocal call deepens into a throaty moan as the Reptaur really begins to give you all that it's got.";
						WaitLineBreak;
						say "Like a true reptile the Reptaur doesn't have much finesse as it simply grinds its claws into the earth and then hammers its hips into your own in an effort to drive you further into the ground. Digging your own feet down to give yourself some extra added leverage helps you to withstand the onslaught of the reptile's thrust as you buck yourself back into the scaly mutant pounding your pussy hard enough to make you choke on air. The length of mass spearing through you has you almost seeing stars as the serpent's shaft pounds deep into your body to where you can actually feel your guts moving around as you continue to submit yourself to the Reptaur.";
						WaitLineBreak;
						say "The steady slap of your [skinname of player] skin meeting the reptile's own slick and scaled form makes for an interesting beat as the two of you climb closer and closer to the pinnacle of orgasm. The rush of the final moment comes like a wave over you both as you hike yourself up and then grunt your end as your cunt clamps close around the Reptaur's cock. The other, having not expected this, hisses and then yells out to the sky as your climax forces the creature's own to come about in a massive torrent. Streams of cum literally flood out the side of your cunt on down onto the backside of your legs as your lover continues to thrust himself into you, however, because of the warmth and feel of being bred by the Reptaur you hardly even notice as you allow yourself to take in the fullness of the reptile's ample load.[impregchance]";
						WaitLineBreak;
						say "When you both calm down from your respective finishes the Reptaur slowly eases its cock out from your body, dragging its shrinking organ over onto your back as it does so, and then slowly steps its way off back to... wherever it has come from. You don't mind though because just as soon as the other is gone from sight you flop down in exhaustion onto the muddy, not to mention musky smelling ground.";
					else:
						LineBreak;
						say "Deciding that the taste of the other is just too good to pass up you continue to suck the Reptaur off while pumping the creature with your [bodyname of player] fast stroking hand. The reptile mutant seems not to know what to do with itself as it humps forward into you while hissing and crooning in utter ecstasy. When the taste of the other begins to thicken so much that you actually find yourself getting full off of the other you know that you'll have hurry the process along if you want to taste the Reptaur's cum.";
						WaitLineBreak;
						say "Pulling back until just the tip of the Reptaur's cock is placed neatly onto your tongue with the edge of your lips wrapped around the first few centimeters of the creature, you reach two of your fingers up into the reptile mutant's genital slit and then begin fingering around inside of the other's gamey pouch. When your fingers probe over something lumpy inside of that hidden slit your Reptaur lovers roars loud enough to deafen you just as a flood of his cum washes over your taste buds. The texture of the other's cum has a thick and heady taste, much like a fine wine, as the continuing flowing of seed fills you up in a strangely fulfilling way. However, you don't thing over this much as you suck the serpent's cum down until there's nothing left in the Reptaur's balls left to give.";
						say "Its only then, after your stomach is almost ready to burst, that you give the Reptaur a much-needed reprieve by pulling off of the Reptaur's now-shrinking cock. The scaly mutant is very quick to pull itself away from you now that you've drained its cum and without looking back the Reptaur takes off into the hills.";
			else:
				say "     [bold type]Do you want the Reptaur to suck you off or would you rather mount your new steed?[roman type][line break]";
				LineBreak;
				say "     ([link]Y[as]y[end link]) - Oral.";
				say "     ([link]N[as]n[end link]) - Mount.";
				if player consents:
					LineBreak;
					say "Having defeated the Reptaur you unzip your pants and then pull out your cock as you stroke yourself to full hardness. The fight gave you just the right thrill making your blood almost sing and as you look down at your opponent lying prone at your feet you find yourself ready to partake in your conquest over the reptile. The glare the other sends your way is nothing compared to the smirk covering your lips as you lower your head down to growl in front of the serpent's face. Warning the other that if it bites you'll have a new set of snakeskin shoes to go along with this victory you watch as the other bows in a second defeat before you.";
					WaitLineBreak;
					Say "Chuckling at the other and telling how things won't be so bad you get a quiet hiss from the Reptaur in disbelief. Raising the reptile's head up you reach down to run your fingers over and along the scaly mutant's jaw before gently prying the other's muzzle open. Looking serpent's twin fangs, poised and glimmering, as though in readiness to be used, you don't feel any fear as you slowly edge your cock into the other's maw. Sinking your maleness into warm of the Reptaur's mouth you groan and then shudder as the serpent wraps its tongue around your length without having to be told to.";
					WaitLineBreak;
					Say "Reaching up to rub the Reptaur along the side of the head you brace your feet into the ground and then begin pumping your hips back and forth to get a good motion started. The Reptaur, slightly unhappy with being used like this, doesn't give you any indication that it's about to try and rebel as the reptilian creature sucks at your musky shaft while grunting around your humping hips. The feel of your body connecting with its own in such a primal way has the Reptaur getting into things a minute later as you begin to speed things up.";
					Say "The smooth texture of the Reptaur's mouth is almost divine, but it's nothing compared to that long and whip thin tongue coiling tightly around the head of your shaft. Groaning slightly when a hand reaches down to play with the underside of your taint you hiss and arch forward into the scaly mutant, forcibly making it deep throat you. The Reptaur hisses, but you don't mind as you feel yourself approaching that pinnacle called orgasm. Grabbing the side of the reptile's head tightly in between your fingers you thrust your body back and forth into with growing force as you try to milk your cock along the stroking reptile's tongue. ";
					WaitLineBreak;
					Say "When the serpentine's tip of the reptiles tongue enters into the slit of your cock you throw your head back and then hiss like a snake as you flood your conquered foe's maw with your seed. Gout after thick gout of cum fills the Reptaur's mouth, forcing the other to swallow, as you let loose everything your balls have to offer, which just so happens to be a lot. The minute your orgasm begins to taper off you pull back from the Reptaur and then look down to see the serpent licking the few trails of cum dripping down the side of its cheek. When the other looks up at you with an unreadable expression on its face you can only gloat in victory as you tell the other, 'I told you so.'";
				else:
					LineBreak;
					Say "Feeling excited about having defeated such a mighty beast you shrug yourself out of your clothes and then stand in your full glory before the Reptaur. The reptile hisses a slight croon of pleasure up at you as it looks to you with awe and respect for having defeated it. Eyes filled with pride at you conquering it instead of another mutant you find the Reptaur's tail flagging slightly as the reptile tips its head up at you. Feeling your excitement about to rise to almost mind-numbing levels from this display of submission by the other you move around to the backside of the Reptaur, smiling lustfully at the creature all the while. What you see when you get there though, after hiking the scaly beast's tail up out of the way, has you blinking in some surprise.";
					WaitLineBreak;
					Say "Two holes lay hidden underneath the shadow of the reptile's tail. A tight anus, which looks as though it's never been used before, and a gaping cunt, that seems as though it's just waiting on you to pierce it.";
					say "     [bold type]Hungering for both, and yet knowing that your [italic type]lover[roman type] might not appreciate being used twice over, which do you feel like using?[roman type][line break]";
					LineBreak;
					say "     ([link]Y[as]y[end link]) - Cunt.";
					say "     ([link]N[as]n[end link]) - Ass.";
					If player consents:
						LineBreak;
						Say "Wanting to feel yourself buried deep inside of the Reptaur's moistened cunt you reach your fingers down to spread the twin folds of the serpent apart before placing the scaly mutant's tail onto the side of your right shoulder. Dipping inside of the slightly loosened cunt of the other you make a show of spreading the Reptaur open for several minutes while at the same time priming yourself to spear the reptile the thick lance of flesh growing rigid between your legs. When the serpent begins to croon over its shoulder at your and that long and flexible tail taps lightly at your shoulder you take a guess that your lover of the hour is ready for a rough ride.";
						WaitLineBreak;
						Say "You don't waste time as you position yourself up above the other to mount the reptile as though it were a stallion as you place yourself at the proper angle to unite your cock with the reptile's cunt. The first thrust of your hips into the backside of the serpent's cunt has the Reptaur grunting from your rough treatment. However, the other makes no effort to try and buck you off. Instead, the serpent spreads its legs wider, digs its feet into the ground to get a better sense of balance about itself, and then lowers its chest down for you to climb atop it easier. You find yourself chuckling heartily at this as you drive your cock through the depths of the other, stroking over that single spot of pleasure that could drive one to madness inside of the beast.";
						WaitLineBreak;
						Say "Groaning and crooning the same as the Reptaur you pull yourself up further over the other so as to get as much as your cock into the scaly mutant. Gripping your fingers around the other's flanks and then hugging your [']mount['] close into you, you shuffle your hips the best way you think possible to bring yourself and your lover off. Noting the quiet hisses and sudden arches the Reptaur makes as it pushes back into you, you use those little gestures as signs of how you shoulder thrust inside of the other next.";
						WaitLineBreak;
						Say "When your face begins to heat with a heavy flush and your breaths begin to come out in a more rapid manner you know that it won't be long before you're ready to cum.";
						Say "And like clockwork the final moment of ecstasy comes to its peak at the same time your Reptaur companion clenches down vice tight onto your cock, which consequently sends you right off the edge of the map. Baying to the sky like a hound you sound off your orgasm while gripping your fingers as tightly as you can into the scaled hide of your [']mount[']. The warm flood of your seed drenches the inside of the Reptaur's depths, heating the serpent's fertile nethers up so much that it triggers the reptile's own flood of juices. The feeling of being buried into the tight warmth of the Reptaur as the creatures cums all over you makes you sing your pleasure to the sky above as your hump yourself into the other several more times before going still.";
						WaitLineBreak;
						Say "Panting and then gasping your end you pull your thoroughly soaked cock out of the reptile and then back away from the other to collapse onto your rump. The Reptaur, seeing that the moment is over, looks at you and then looks at its soiled backside and then hisses at you before going off about its way. In the back of your mind you wonder who will be the victor the next time you encounter one of those mutant reptiles.";
					else:
						LineBreak;
						Say "Wanting the beast's ass more than its cunt you slap the Reptaur onto the rump, forcing a hiss and then yelp out of the other, before reaching two of your digits up to your [facename of player] face to spit onto your fingertips. The quick turn of the reptile's head back towards you does nothing to phase your confidence as you work to slip your lubed fingers into the scaly mutant's tailstar. This action makes the Reptaur moan like the wanton beast it is as its large tail moves up around the side of your neck to hold itself steady just as the creature shuffles its hips from side to side while pushing its rump back into you.";
						WaitLineBreak;
						Say "Chuckling at the other you spread the Reptaur's tailhole open as wide as you can, thumbing your fingers around until you can find the reptile's prostate, which, after you locate, you then tease. The shudders that rack up the side of the creature's backside look almost painful as the Reptaur croons to the sky while pumping its ass back at you almost wantonly. Pulling your digits out and then slapping at the scaly rear of your lover once again you don't take more than a second to admire the now loosened pucker of the four legged mutant before placing yourself up onto the Reptaur's backside like a seasoned rider.";
						WaitLineBreak;
						Say "Angling your cock so that you'll be able to hilt yourself into your reptilian [']steed['] you find yourself hissing the same as the Reptaur when your manhood slides into the opened depths of the other. Hot and warm, yet tight and unyielding, the reptile's anus feels much like a warm glove as it contours around the length of your shaft. Grinding your body into the serpent while reaching out to wrap your arms around the muscular waist of the other you begin humping without having to think about your next move as you drive your cock firmly into the Reptaur's ass, as though it belongs there.";
						WaitLineBreak;
						Say "At first, the Reptaur is not too comfortable with this, the scaly creature stamping at the ground like an incensed stallion as it wags its tail dangerously alongside your neck. Yet as your hammering hips help to drill your length along the creature's prostate the Reptaur is quick to silence the grumbles of protests building inside of its throat as the rapture sizzling throughout its body begin to grow more prominent. Nuzzling your face into the upper portion of the scaled creature's man-like backside you find your teeth biting down into the surprisingly sweaty scales as you thrust yourself with mounting force into your Reptaur lover.";
						WaitLineBreak;
						Say "The minutes are quick to tick by as you drive yourself further and deeper into the reptile. With your body's warmth seeping into the serpent's own panting form, coupled with your cock hitting at its prostate, unknowing helps to send signals down to the Reptaur's cock, causing the thick girth to push free from the creature's genital slit. The pulsing organ, thick as the creature's wrist and slightly tapered at the tip, dribbles precum onto the ground beneath the two of you like a streaming river. The growing waterfall's thickening texture is the only sign that the Reptaur is growing closer to reaching its zenith, but you are heedless to this fact as the [']itch['] you've come to associate with orgasm threatens you with your own climax.";
						WaitLineBreak;
						Say "Just as you can feel the burden of your release about to come upon you, you pull yourself back from the Reptaur, almost until only the tip of your cock is snugly placed inside of the other, and then thrust yourself up over the reptile as far as you can to drive your shaft completely into the Reptaur. The roar the serpent lets out from your cock stroking over its prostate for the last time is nothing compared to the blinding sensation mixed with partial deafness that overtakes you as blow your load inside of the beast.";
						WaitLineBreak;
						Say "Down below the Reptaur's cock jumps once, twice and then surges with cum as the scaly beast climaxes with battering ram-like force onto the ground. Up above you place your teeth back onto the Reptaur's scales as you bite down hard while letting your balls continue to pump their contents into the ass of your submissive lover. The minutes that you both share in your mutual orgasms feel almost like seconds as all too soon you find yourself pulling out from the Reptaur to fall flat onto the ground.";
		 				Say "After your cock has dribbled its last you find yourself getting a slight surprise when the Reptaur turns to glare at you somewhat hotly. Not knowing what this on about, you find yourself gaping slightly as the scaly mutant smirks at you before turning to trudge off on its way. The last you see of the other is the Reptaur's tail flagging into the air showcasing your cum running down its taint.";
		else:
			LineBreak;
			say "Not feeling like doing anything sexy with the Reptaur you look over the angry creature and then [one of]tap it across it's scaled snout[or]give it a cheeky grin[or]wink at it saucily[or]blow it a kiss[at random] before turning to go off your way.";


Section 2 - Monster Insertion

Table of random critters (continued)
name	attack	defeated	victory	desc	face	body	skin	tail	cock	face change	body change	skin change	ass change	cock change	str	dex	sta	per	int	cha	sex	HP	lev	wdam	area	cocks	cock length	cock width	breasts	breast size	male breast size	cunts	cunt length	cunt width	libido	loot	lootchance
--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	-- 	--	--	--	--	--	--	--	--;

When Play begins:
	Choose a blank row from Table of random critters;
	now name entry is "Reptaur"; [ Infection/Creature name. Capitalized. ]
	now attack entry is "[one of]The Reptaur hefts you up into the air with one arm and then powerfully drives you into the ground![or]The Reptaur charges into at top speed![or]The Reptaur unsheathes its claws and then swipes at your face and chest![or]The Reptaur run around to your backside and then bowls you over with a fierce kick of its rear legs![or]The Reptaur launches you into the air with a sharp uppercut![or]The Reptaur coils its long tail around your throat and then slams you back and forth onto the ground![at random]"; [ Successful attack message ]
	now defeated entry is "[beattheReptaur]"; [ Text when monster loses. Change 'Reptaur' as above. ]
	now victory entry is "[losetoReptaur]"; [ Text when monster wins. Change 'Reptaur' as above. ]
	now desc entry is "[Reptaurdesc]"; [ Description of the creature when you encounter it. ]
	now face entry is "smooth and blunted with a somewhat rounded muzzle making up the end of your face. The shape of said muzzle just so happens to hinder you from smelling much of anything. However, your new serpentine tongue takes care of that small detail by [italic type]tasting[roman type] all the scents in the air around you"; [ Face. Format as Your face is [face of player]. ]
	now body entry is "strangely mixed between that of an ungulate, a serpent, and a man. Like the centaurs of old you have the lower body of a horse, but instead of your lower end being lightly furred its smooth all over while your feet end with four digitigrade paws fitted with sharp claws instead of hooves. Your upper body is mixed between that or a serpent's and a man's as you possess two strong, but smooth arms, with muscles for days covering both your chest and back"; [ Body. Format as "Your body is [body of player]." ]
	now skin entry is "bright greenish-blue scales that seem to glow almost teal in the right light"; [ Skin. Format as "Looking at yourself, your body is covered in [skin of player] skin." ]
	now tail entry is "You have a six foot long, two and a half foot wide tail that ends at a rounded tip, much like a rattlesnake's."; [ Ass/Tail. Write as a full sentence (with period) or leave blank for none. ]
	now cock entry is "reptilian"; [ Cock. Format as "You have a 'size' [cock of player] cock." ]
	now face change entry is "your hair begins to fall out while your muzzle rounds out to become somewhat blunted at the point where your nose should meet your face. As your eyes narrow into almond-like slits your two eyeteeth elongated into wickedly sharp fangs while your tongue narrows down to become almost whip thin"; [ Face TF text. Format as "Your face tingles as [face change entry]." ]
	now body change entry is "your bones shift and flex underneath your skin as your backside stretches out behind you to give you an extra pair of legs. If things were already odd the hairs on your body begin to fall off while your skin slowly becomes smooth all over. Of course, to top things off, you're not prepared for vertigo to overtake you as your new feet help to lift you up while at the same moment you [']original['] legs begin to thicken with extra muscle. Your torso, chest, and arms are not spared from this new changes as extra added growth surges throughout your upper body helping it to offset your newly made taurian backside as the organs inside of your body work to rearrange themselves"; [ Body TF text, format as "Your body tingles as [body change entry]. ]
	now skin change entry is "your flesh starts to harden, the beginnings of your scales coming in, while at the same time your skin changes its pigmentation to become almost teal-like color"; [ Skin TF text, format as "Your skin tingles as [skin change entry]. ]
	now ass change entry is "your lower backside begins to stretch out as your spine lengthens to cover the split of your ass. Crazy as this is, this is almost nothing compared to your glutes swelling out from your body, giving you a perfect bubble-like rump, as your new tail thickens and stretches out to almost match the length of your entire form"; [ Ass/Tail TF text, format as "Your ass tingles as [tail change entry]." ]
	now cock change entry is "the mass of flesh thickens and then rounds at the head while growing several ridges along the upper length"; [ Cock TF text, format as "Your groin tingles as [cock change entry]." ]
	now str entry is 20; [ These are now the creature's stats... ]
	now dex entry is 21; [ ...and are only altered onto the player via Shifting or the Mighty Mutation feat ]
	now sta entry is 22; [ These values may be used as part of alternate combat.]
	now per entry is 16;
	now int entry is 18;
	now cha entry is 23;
	now sex entry is "Both"; [ Infection will move the player towards this gender. Current: 'Male' 'Female' 'Both' ]
	now HP entry is 89; [ The monster's starting HP. ]
	now lev entry is 15; [ Monster level. (Level x 2) XP for victory. (Level / 2) XP for losing. ]
	now wdam entry is 15; [ Monster's average damage when attacking. ]
	now area entry is "Park"; [ "Outside" "Mall" "Park" "Beach" etc... Check an existing creature in the area. ]
	now cocks entry is 2; [ Number of cocks the infection will try to cause if sex entry is 'Male' or 'Both'. ]
	now cock length entry is 12; [ Length infection will make cock grow to if cocks. ]
	now cock width entry is 6; [ Cock width, more commonly used for ball size. ]
	now breasts entry is 0; [ Number of nipples the infection will give a player. ]
	now breast size entry is 0; [ Size of breasts the infection will try to attain. ]
	now male breast size entry is 0; [ Breast size for if Sex="Male", usually zero. ]
	now cunts entry is 1; [ The number of cunts the infection will try to cause if sex entry is 'Female' or 'Both'. ]
	now cunt length entry is 12; [ Depth of female sex the infection will attempt to give a player. ]
	now cunt width entry is 6; [ Width of female sex the infection will try to give a player. ]
	now libido entry is 55; [ Target libido the infection will rise towards. ]
	now loot entry is ""; [ Dropped item, blank for none. Case sensitive. ]
	now lootchance entry is 0; [ Percentage chance of dropping loot, from 0-100. ]
	now scale entry is 4; [ Number 1-5, approx size/height of infected PC body: 1=tiny, 3=avg, 5=huge ]
	now body descriptor entry is "[one of]muscled[or]strong[or]sexy[or]deadly[at random]"; [ Ex: "plump" "fat" "muscled" "strong" "slimy" "gelatinous" "slender". Use [one of] to vary ]
	now type entry is "reptile"; [ one-word creature type. Ex: feline, canine, lupine, robotic, human... Use [one of] to vary ]
	now magic entry is false;
	now resbypass entry is false;
	now non-infectious entry is false;
	blank out the nocturnal entry; [ True=Nocturnal (night encounters only), False=Diurnal (day encounters only), blank for both. ]
	now altcombat entry is "rtaurpounce"; [ Row used to designate any special combat features, "default" for standard combat. ]

[A sample structure for succumbing/surviving messages at the end of the game.]
[Numerous other examples can be found in existing creature files.]


Section 3 - Reptaur Pounce Alt Attack

Table of Critter Combat (continued)
name	combat (rule)	preattack (rule)	postattack (rule)	altattack1 (rule)	alt1chance (number)	altattack2 (rule)	alt2chance (number)	monmiss (rule)	continuous (rule)	altstrike (rule)
"rtaurpounce"	retaliation rule	--	--	rtaurpounce rule	17	--	--	--	--	--

this is the rtaurpounce rule:		[double-damage pouncing]
	choose row monster from the table of random critters;
	let rangenum be ( 80 - ( peppereyes * 4 ) );
	let dam be ( ( wdam entry times a random number from rangenum to 120 ) / 67 ); [+50% damage]
	if hardmode is true and a random chance of 1 in ( 10 + peppereyes ) succeeds:
		now dam is (dam * 150) divided by 100;
		say "The enemy finds a particular vulnerability in your defense - Critical Hit![line break]";
	say "The [one of][name entry][or]reptile[or]reptilian taur[or]reptilian creature[purely at random] knocks you to the ground and pounces atop you quickly, stomping you repeatedly with its clawed feet in an attempt to knock the resistance out of you. This [one of]powerful[or]strong[or]devastating[purely at random] assault does [special-style-2][dam][roman type] damage!";
	now damagein is dam;
	say "[noshieldabsorbancy]"; [unable to use shield while pinned]
	if absorb > dam:
		now absorb is dam;
	if absorb > 0:
		say "You prevent [special-style-1][absorb][roman type] damage!";
	decrease HP of the player by dam;
	increase HP of player by absorb;
	follow the player injury rule;
	say "You are [descr].";




when play ends:
	if bodyname of player is "Reptaur":
		if humanity of player < 10:
			say "Falling prey to the Reptaur strain of infect you find yourself losing control over your senses. Instinctively heading deep into the city to become lost amongst your feral kin who roam the park area you find the rest of your days becoming much a blur as you feed, and fuck and fight any who decide to harm the little patch you've made for yourself. The small herd of other Reptaur's that become something like your family make up the difference for whatever emotional needs you may require and as for the sex... well that's never in small demand. Especially when you and your kin begin capturing lonesome soldiers who end up straying too far from their post to [italic type]blow off a little steam[roman type].";
		else:
			say "Surviving the crisis plaguing the city you wind up being captu-rescued by the military and then taken to one of their quarantine facilities to be experime-checked over by the helpful men in camouflage fatigues. Days of winding up being poked and prodded and else made into a part-time lab rat has your temper reaching almost dangerous levels as you threaten to blow up at the doctors and scientist on duty. However, right before you go ballistic you end up being released back out into the world at the behest of a certain doctor that just so happens to be mutant friendly. Thrown back out into the world you slowly come to realize that there's not much keeping you here in the city anymore and at that point you are quick to pack up what little things you have in order to head for new horizons awaiting you out there in the big world.";
			if player is male:							[MALE/HERM]
				say "Having the body of a reptile mixed with a quasi-centaur means that you find yourself netting an odd number of physical jobs, given your build and constitution, the latter which gives you a heads up over others in the blue collar field. Least to say you make many new friends while working your part-time jobs and end up with a host of lovers, some mutants like yourself and some not. However, none of them can hold a candle to the one special guy you wind up meeting a polite – see boring – social gathering set up one Halloween evening.[line break]";
				say "The person in question, whose name just so happens to be Lance, is a charming brown haired human who you just so happens to not mind doing the fact that you have a tail that constantly finds its way wrapped around his lithe, but deceptively strong body. It took about a month for you to charm Lance into your bed, though it proved to be a fun four weeks with you hissing quietly into the man's ear ever chance you got while coiling your long tail around his body just to show the other mutants just who he belonged to now. However, once you did have the other writhing in your lap as you worked your long and slightly tapered cock into the depths of his tight rump, it took all of an hour for your infectious nature, something the scientist seemed to have overlooked, to fully change the other into another Reptaur. To say the least Lance takes the fact that he no longer has to wear pants anymore pretty well after he woke up to look down over his newly muscled reptilian form. Yet as of this day in time, almost a year later, you still have not talked the other into wearing that zebra printed equine thong some red headed maniac in the fashion industry decided to dream up while coming out with a new line of centaur fetish gear.[line break]";
				say "Despite this little setback though, both you and your lover make a pretty good pair both at home and on the job after Lance reprints his IDs and accepts a change in business ventures now that he is a mutant. For your part you still work construction and other blue collar gigs that you can snatch up whenever there's a slow season, while Lance busies himself working with a new mutant based accounting firm that's gone global. It's not a perfect life, but then again, that's part of what makes it unique... or rather worthwhile.";
			else if "Sterile" is not listed in feats of player:	[F-BREEDABLE]
				say "Being dominantly female in gender you find yourself being drawn by your maternal instincts to a small outreach center responsible for the upkeep and education of both mutant and human teens. The organization that supports the center is shadier than the mafia but, with the female centaur and her cohorts working to maintain order for the facility certain... unsavory elements... end up being removed from having any interactions with the young ones. Its only after seeing the centaur, whose name is Debra, kicking out several men in suits that claimed that they wanted to have a look in on the children to check on their progress, with the aid of yourself and some of her other companions, that you find yourself being intimately drawn to the other woman.[line break]";
				say "Of course, being the professional woman that she is, Debra makes it clear that her focus is on the children and that any sexual practices get handled when she's well off duty. This turns out to be something you come to respect, though grudgingly so since you have to come in to work every day knowing what you can never have, however over the months that pass your feelings slowly turn themselves towards a new prospect in the form of Libby, a herm Equitaur, whose morals are a little bit shakier, but her resolve to do right by the teenagers at the center no less resolute. Finding a lover and companion in Libby turns out to be much better for you than being with Debra, right up until you find your belly swelling with the Equitaur herms clutch after about ten days into your sexual relationship. Least to say, you and Libby manage to make the center just a little more [italic type]prosperous[roman type] as you add several of your equine-reptaur foals into the mix with the other children.[line break]";
				say "Debra takes a deaf ear to how all of your children call her Aunt Deb, but whenever you catch the centauress's tail swaying leisurely behind her back whenever she thinks no one is looking, you get a good feeling that she likes the new title.";
			else:									[F-STERILE]
				say "After leaving the city you find yourself drifting around for a while, going back and forth between place to place until you finally find yourself settling in a little provincial town in the middle of bumfuck nowhere. With a population of a hundred and it doesn't take you long to settle in, especially being one of the few mutants in the place, but it does take you a little while longer to get over the lonesomeness of not having much in common with the rest of the townsfolk. The children seem to like you though as they often want to ride on your back during your days off from work at the mayor's office. Its only when more [italic type]new blood[roman type] comes into the place, some weeks after your arrival, in the form of mutants looking to get away from the world that things begin to change.[line break]";
				say "The local mayor, who likes he was there during Noah's Flood, elects you as the deputy mayor to take care of these newcomers and soon you find yourself wrapped up in situating everybody into a new place and then bridging the social gap between the humans and mutants. Not having much experience with this sort of thing the wolftaur brothers that come into town a few days later are quick to aid you in your endeavors as they work to expand the town for more incoming outsiders. Their plans to build up new housing complexes spurn the mayor to making some calls and asking for a few favors to get the money necessary to have said buildings put into place.[line break]";
				say "Days into things, you find yourself become enraptured by the two wolftaurs. Maybe it's because of their charisma, or maybe it's the fact that both just happen to be of an upbeat and positive mindset while dealing with a bunch of nonsense in the form of bureaucratic red tape, but before long all three of you find yourselves sharing your bed together as the brothers show you just how much fun being a part of a pack can be. To say the least, the strange howls that go around town every other night become somewhat commonplace as the weeks roll by. However, the excuses you keep giving to the neighborhood children about the funny noises and reason you walk so strange every other morning are kinda running thin.";

[ Edit this to have the correct creature name as well]

Reptaur ends here.
