Version 1 of Gus by Hyliad begins here.
[Version 1 - Put into its own file]

[ GusTalkProgress                                     ]
[   0: starting value                                 ]
[   1:                                                ]
[   2:                                                ]
[   3:                                                ]
[   4:                                                ]
[   5:                                                ]

GusTalkProgress is a number that varies.
HadGusBackgroundTalk is a truth state that varies. HadGusBackgroundTalk is usually false.

to say ShagShackSex23: [Gus]
	if GusTalkProgress is 0: [first encounter]
		say "     You walk among the mattresses, most of them already used by rutting couples, until you notice one that, strangely, seems unoccupied. Stopping in front of it, you notice that there is actually somebody sitting on the floor right next to it, their back resting against the bed. As you take another step forward to check them out, his slender and lanky body comes into sight, naked and apparently male. Judging from the long neck along with beak and the white and black feathers, you think that he is a stork. The young man is sitting cross-legged, his whole focus currently resting on the comic book that he's holding. His wings, covered in white feathers like the rest of his body, sport taloned hands which he uses to hold the object of his attention and turn the pages. As you stand there staring at him, he gives you a quick glance before returning to his reading, then two seconds or so later, as if his brain has only now processed the information, turns to you again with wide eyes. He jumps to his feet, throwing the comic book under the bed as if you were never supposed to see it and standing up to face you.";
		say "     'H-hey there, [sir]! I apologize for not noticing you. I'm Gus! Nice to meet you. I'm here to help with whatever you need.' A bit surprised by his casual attitude and how out of place he looks, you ask what kind of services he offers, almost expecting whoring to not be one of them. 'Well sex, of course! That's pretty much it actually, but I mean, if you want a chat or a massage or anything, I'm game too.' When you ask if he would prefer that to having sex, he giggles as if you just made a joke. 'Oh no, I love sex as much as the next guy. I'm just saying, I want you to have fun most of all, so it's about what you want. Demand and I shall provide!' he adds with a happy smile, playfully doing some poor imitation of a military salute.";
		now GusTalkProgress is 1; [intro scene done, prepped for talking to him]
		WaitLineBreak;
		say "     It seems that the stork is more than happy to provide anything you desire. But just what is it that you desire?";
	else if GusTalkProgress < 5: [talked with Gus less than four times]
		say "     Finding your way back to the stork's mattress, you find him once again buried in a comic book, although it appears to be a different one than last time. He soon notices you and closes it, making it disappear under the bed before standing up next to it. 'Hello [sir]! It's a real pleasure to have you again. What can I do for you today?'";
		say "     The stork smiles warmly, waiting for your order. Obviously, he's eager to spend some time with you, but how should you spend it?";
	else: [talked at least four times]
		say "     Knowing exactly where to find the stork by now, you quickly make your way to his mattress where you see him lying with, big surprise, a comic book in his hands. He notices you quickly and brightens up, waving at you enthusiastically as you reach him. 'Hello, [sir]. It's always a pleasure to see you,' he says with a sincere smile. After the comic book disappears under the bed, no doubt to join a pile of similar comics stashed in there, the stork gets up and gives you a hug and a kiss. Soon enough, more kisses follow, and before you even realize it, the two of you are making out lustfully as the bird caresses your [if player is neuter]ass[else]crotch[end if] with his wing. 'So,' he says with a lustful look, 'what can I do for one of my favorite clients today?'";
	now HadGusBackgroundTalk is false;
	say "[GusSexMenu]";

to say GusTalk:
	if GusTalkProgress is 1: [guaranteed talk 1 coming first]
		say "     'In the mood for some talking first? I like that!' The good-natured stork giggles, leaning on the bed and patting the spot next to him. As you take your place next to him, you ask him to tell you a little about himself. 'My story isn't that interesting really. It's pretty much the same story as most people in this city: life was normal and then all of a sudden it wasn't normal at all anymore, but by the time I realized, I already had feathers everywhere, and then I wasn't normal anymore either. It's kind of depressing to think about all that, but tell you what, let's get comfy and have some fun for now,' he says caressing your chest. 'And if you wanna know more next time, I'll tell you my story. Deal?'";
		now GusTalkProgress is 2; [ready for talk 2]
	else if GusTalkProgress is 2:
		say "     Gus says, 'Well I did say that I would tell you my story, didn't I?' Gus relaxes on the mattress, stretching his legs a bit and resting his wings on the back of his head. 'Well, here's the story behind the legend! I used to work at a delivery service, before the infection and all I mean. It doesn't sound like the kind of job you do for passion, but I really liked it, giving people stuff. It's not like those packages were gifts from me or anything. It was stuff they had bought online, but it still felt like I was making their day a little better. I'm not an ambitious guy or a hard worker. The only way for me to appreciate a job is to know it's something that helps people in some sort of way. I knew I was just a replaceable guy in a big company all about profit, but my part of the job wasn't about that. For me at least.' Gus stops for a second, seemingly reflecting on his past as he gazes to the ceiling.";
		say "     'I was partnered with Peck, big guy, really nice. He drove the truck, and I was delivering the packages to the clients. Most shipping companies have one guy do both, not sure why ours didn't, but it worked smoothly. Anyway, it was during a delivery that everything went bananas for me. It happened in some house in the middle of the city that managed to be isolated somehow, like basically it had its own tiny street and it was the only house in it, and I had to deliver a package there. So Peck parks in the tiny street, and I go deliver the package, and I ring the bell, but for a moment no answer or anything. I knew better than just walk away after a short while, because I can tell you from experience as a delivery man, you often wake up people sleeping, or they're half-naked and need to put on some pants, or they have headphones on and don't hear you the first time, or whatever. So anyway, I wait, and then...' the stork pauses with a teasing smile.";
		WaitLineBreak;
		say "     '...And that's it!' Gus suddenly proclaims. You blink in surprise. That's it? What kind of a story is that? As you get old flashbacks of that show you used to love until the ending totally sucked, Gus chuckles. 'Well I mean, obviously that's NOT it, but you'll have to come back another time to hear the rest.' As you voice your frustration at being denied the full experience, the bird gives you an apologetic smile. 'Sorry [sir] but I'm a whore, and we only get so much time together. I'd feel terrible if we completely run out of time and you had to leave this place without getting anything more than a talk', he adds teasingly. 'So I guess you'll have to come back again for more!' he says before getting up. 'So, what can I do for you today beside talking?'";
		now GusTalkProgress is 3; [ready for talk 3]
	else if GusTalkProgress is 3:
		say "     'Still interested in my story? I'm cool with that. Alright, so as I said', Gus starts while the two of you go lie on the bed, 'I'm at this house to deliver a package, and so far no answer. But right after I ring the bell a second time, the door opens slightly and I hear somebody walking away from it, and then some guy's voice telling me to come in. I just open the door and I stay there, because you just don't enter somebody's house like that, but then that guy keeps talking from inside, telling me he needs help with something. So of course being me, I comply, but when I follow the voice to the living room and see the guy, turns out he's a bird man, all black and feathery and all, and naked with that! You think I'd panic, or try to run away, but no, I just stood there like an idiot and went [']Hello sir, I have your package?['] as if I had just met a normal dude in a business suit. I think I wasn't exactly scared, frankly I was just super confused, so I think I just tried to look like I knew what was happening while my brain was processing.'";
		say "     'Turns out bird man was interested in more packages than the one I was there to deliver; not even a minute later, I had a half-man half-bird creature giving me a blowjob and I was enjoying way far too much to question whether I should let it happen or not. I was a virgin at the time, so between that and the nanites, it's no surprise that I fainted right after I came in his mouth. When I come back to my senses, I'm on the sofa of the living room, the bird guy is still there, and he offers me a glass of water and even to stay the night. I decline because I'm working and my friend is waiting for me in the truck, but when I explain that to him, bird guy answers that my friend must have been waiting a long time because I had been out for six hours or so.";
		WaitLineBreak;
		say "     So I ask the guy to sign the paper confirming that he received his package, which makes him laugh but he still does it, and then I rush outside. And the delivery truck is there alright, but no Peck, like he had simply vanished. Bird guy tells me he hadn't even noticed the delivery truck and that nobody came to the house looking for me, so as for where Peck went, your guess is as good as mine. Never saw him again. The infection had already started, and obviously this was an infected area, so he probably crossed paths with a mutant too. He was a cool guy. I hope he's safe, and that he's happy being whatever he probably turned into.'";
		say "     'Oh man, I'm talking way more than any whore should again. To conclude the story, I was so shaken up and confused, I just drove the delivery truck back to my home without returning it like I normally would, and from my apartment that night, I hear screams outside, some of them not human. Through the windows, I see people running, and some other things running after them. And none of my roommates had come back, and of course at some point I lost all water and power. Needless to say, I didn't know what to do, and I was seriously freaking out.' The stork pauses, clearly a little perturbed by remembering those scary times, until his faces brightens up again. 'But that's enough talk for today!' he says, clapping his taloned hands. 'We're gonna run out of time for other stuff if we keep going. Besides, reminiscing about bird guy made me pretty excited, coz let me tell you, he was one heck of a sexy bird. I'll finish the story next time, I promise.'";
		now GusTalkProgress is 4; [ready for talk 4]
	else if GusTalkProgress is 4:
		say "     Gus says, 'I did promise I'd tell you the rest of the story didn't I? Alright, here comes the epic conclusion! So I'm in my apartment seriously freaking out, and I decide to make my food last for as long as I can so I don't have to go outside, but I eventually run out two days later.' You raise an eyebrow, blown away by such impressive survival skills. 'What? I hadn't bought food planning for the apocalypse, okay?' he says. 'And those sandwiches were gonna go stale anyway. That was, uh, pretty much all my roommates and I ate, so there wasn't any cans or anything. So I leave my apartment, and I try knocking at the door of some of my neighbors, but I get no answer so I freak out. I make my way downstairs and I stop at every door, but I soon stop knocking at those because I start hearing animal sounds behind them, and some of the doors have those really scary animal scratches on them. One door was just destroyed, completely burst open from the inside and obviously not by a human. At this point I'm shaking in my boots but I somehow manage to go on and leave the building to search for supplies.";
		say "     'So I find myself in the city trying to stay hidden and nothing makes sense, I see hyenas on freaking bikes, gryphons and other stuff flying in the sky right above me, and creatures that don't even look like anything I'd ever seen. Honestly, my memories gets chaotic from there, because I got spotted by a freaking DRAGON and had to make a run for it, and I ended up completely lost. At that point I'm thirsty and everything hurts, and it feels like I have been wandering for days, so ultimately I'm so desperate that when I see a group of wolverine dudes that don't look too hungry or rapey I just go to them, but before I can even beg for water, I just faint. When I wake up, I'm on a small mattress in a tiny room, and when I get out of it, surprise, I see a gigantic room full of lots of mattresses, and on those mattresses, people of all forms, sizes and genders just getting in on. It was the Shag Shack!'";
		WaitLineBreak;
		say "     'At that point I'm confused of course, but after one of the wolverine guards explains to me what this place is about, I understand that it's probably safe. The wolverines also tell me that even though they helped, they're not running a charity so if I'm not helping around, I'd have to go back to surviving on my own. You can guess what kind of 'help' they were talking about. I refuse right away, because like, isn't it dangerous to bang monsters? But the wolverines just laugh at that, and when I ask what's so funny, they walk me to a mirror and that's when I find out, I'm a bird now! How I had not noticed before, I have no clue. Like, had I been that way since my encounter with the other bird guy? Or did his infection only affect me much later, like when I was wandering in the city? The nanites might have been messing up with my brain all along, so no idea. Either way, I'm a stork now, which is weird because the other bird guy wasn't, and I'm certain nobody else could have infected me. I guess he had some stork in him that just didn't show.";
		say "     'So to come back to the story, now that it turns out I'm already changed, I actually consider the idea of becoming a prostitute. It might sound crazy, [']cause I mean, I was still a virgin at that point remember, but as I look around and I see all those people fucking I think [']Heck, everybody seem to be enjoying themselves[']. Like, the clients AND the prostitutes. And I'm not really enthusiastic at the prospect of getting back outside, so I decide to give it a try. My first client is a german shepherd, super nice guy. He knows I'm a virgin, actually I think Jerome pretty much put my virginity up for auction and sold it to the highest bidder, so he takes things slowly. And he takes ME slowly, too, ha ha. Turns out, I love sex! Getting my first client off felt so amazing, I just asked for another right away. Being a stork also grew on me surprisingly fast. I don't exactly fly that much, because even though it's pretty cool I also get tired super fast, I mean, I'm not exactly the most buff guy around,' he says while waving his fragile wings.' But I enjoy the new me, I truly do.'";
		WaitLineBreak;
		say "     'And that's pretty much it really. I never left the Shag Shack. Why would I? I make so many people feel good, and happy, and I help them forget all their problems for a bit, while also feeling awesome in the process. It's ten times as good as my previous job! Sure it's a weird as hell place, even for a whorehouse, I mean there's... weird people, and I'm not even talking about the [']employees['] that aren't people as much as they're beasts, but everyone here enjoys what they do, even those beasts, so if a client finds whatever suits them here, good for them! I'm not exactly the most requested guy around here, I guess because I don't strike people as hot at first glance, but I have regulars that always come back, thanks to my charming and addictive personality,' he says playfully giving you a wink, 'so that makes up for it. Besides, several guards have a liking of me, and I don't mean sexually, they just like having me around. So, I really don't have to worry about losing my job. You're one of my regulars too now [sir], by the way. And it's always a pleasure to talk to you.'";
		say "     'Now, I really overdid it with the talking today, didn't I, but tell you what, I'm gonna take some extra time so we can enjoy ourselves. I mean it's my fault for talking for too long anyway, and the guys here like me enough to indulge a client going overtime with me once in a while. But still... Thank you for listening. Nobody ever took the time to hear my story before, not in that much detail. From now on, I only want to hear about you, alright? So I can know what it's like to survive out there when you don't totally suck at it. But that's for the next times; what can I do for you now, [sir]?' he asks with a big smile, visibly eager to thank you for listening to his whole story.";
		now GusTalkProgress is 5; [entering the repeat talk zone]
	else:
		let randomnumber be a random number from 1 to 2;
		if randomnumber is:
			-- 1:
				say "     As you say you're in the mood for some talking, Gus giggles. 'Why am I not surprised?' The stork then starts asking you questions about your past and who you were before it all started. He is very curious about you, and you end up so involved in your reminiscence that at first you don't even notice how he starts caressing your crotch, clearly excited about getting physical with you.";
			-- 2:
				say "     Gus says, 'So tell me [sir], what happened to you recently?' As you tell Gus of your latest adventures (and misadventures), the stork shows great interest; he is sometimes impressed, sometimes excited, sometimes freaked out a bit, but always happy to learn more about your daily life. 'Listening to you really reminds me why I enjoy it here. Everything is so complicated outside. I'd rather just fuck!' he says with a giggle. Speaking of, the avian start caressing your crotch with his wing, clearly eager for something more physical.";
	now HadGusBackgroundTalk is true;
	say "[GusSexMenu]";

to say GusSexMenu:
	LineBreak;
	now sextablerun is 0;
	blank out the whole of table of fucking options;
	[]
	if HadGusBackgroundTalk is false:
		choose a blank row in table of fucking options;
		now title entry is "Talk a bit before sex";
		now sortorder entry is 1;
		now description entry is "Start with a discussion first";
	[]
	choose a blank row in table of fucking options;
	now title entry is "Give Gus a blowjob";
	now sortorder entry is 2;
	now description entry is "Offer to suck Gus off";
	[]
	if player is female: [only females and herms can get cunnilingus]
		choose a blank row in table of fucking options;
		now title entry is "Get cunnilingus";
		now sortorder entry is 3;
		now description entry is "Have Gus use his mouth";
	[]
	if player is male: [only males and herms can get a blowjob]
		choose a blank row in table of fucking options;
		now title entry is "Get a blowjob";
		now sortorder entry is 4;
		now description entry is "Ask Gus to suck you off";
	[]
	if (player is male and anallevel > 1):[only males and herms can give anal]
		choose a blank row in table of fucking options;
		now title entry is "Give anal";
		now sortorder entry is 5;
		now description entry is "Take the stork from behind";
	[]
	if player is female: [only females and herms can take him in the pussy]
		choose a blank row in table of fucking options;
		now title entry is "Receive vaginal";
		now sortorder entry is 6;
		now description entry is "Have Gus fuck you in the pussy";
	[]
	if anallevel > 1:
		choose a blank row in table of fucking options;
		now title entry is "Receive anal";
		now sortorder entry is 7;
		now description entry is "Have Gus take you anally";
	[]
	sort the table of fucking options in sortorder order;
	repeat with y running from 1 to number of filled rows in table of fucking options:
		choose row y from the table of fucking options;
		say "[link][y] - [title entry][as][y][end link][line break]";
	say "[link]100 - Nevermind[as]100[end link][line break]";
	while sextablerun is 0:
		say "Pick the corresponding number> [run paragraph on]";
		get a number;
		if calcnumber > 0 and calcnumber <= the number of filled rows in table of fucking options:
			now current menu selection is calcnumber;
			choose row calcnumber in table of fucking options;
			say "[title entry]: [description entry]?";
			if player consents:
				let nam be title entry;
				now sextablerun is 1;
				if (nam is "Talk a bit before sex"):
					say "[GusTalk]";
				if (nam is "Give Gus a blowjob"):
					say "[GusSex1]";
				if (nam is "Get cunnilingus"):
					say "[GusSex2]";
				if (nam is "Get a blowjob"):
					say "[GusSex3]";
				if (nam is "Give anal"):
					say "[GusSex4]";
				if (nam is "Receive vaginal"):
					say "[GusSex5]";
				if (nam is "Receive anal"):
					say "[GusSex6]";
				wait for any key;
		else if calcnumber is 100:
			say "Break off the conversation?";
			if player consents:
				now sextablerun is 1;
				say "     The stork blinks. 'Is it something wrong with me?' he asks with a worried look, but you assure him that you just had a change of heart and don't feel like having sex at the moment. Gus doesn't seem completely convinced, but nods. 'Well, I wouldn't want you to do anything you don't wish for. Maybe next time, then.' He smiles as he wishes you farewell, but you look back at the stork resuming his reading, you can see a slightly frustrated look on his face.";
			else:
				say "Pick between 1 and [the number of filled rows in the table of fucking options] or 100 to exit.";
		else:
			say "Invalid Option. Pick between 1 and [the number of filled rows in the table of fucking options] or 100 to exit.";
	clear the screen and hyperlink list;

to say GusSex1: [give blowjob]
	say "     'Oh, haha. Well, I certainly wouldn't mind that. Sounds like a deal.' With that, Gus sits on the edge of the mattress with his legs open, his penis poking out of his slit already. You kneel between his legs, resting your hands on them, taking a moment to watch his cock slowly leaving its slit. Deciding to speed things up, you give the stork's length a lick from slit to tip, which leads him to rest his wings on your shoulders in response, gently pulling you closer and enticing you to continue. Soon, all of his cock is out, and you happily start sucking on it as the avian lets out an audible sigh of happiness, relaxing as you work. 'Ah, that's nice... It's pretty cool of you to do that. Most of my clients are alright guys, but they just want to get off. I have no problem with that, I mean I love it even, but it's nice to... Be the focus, too...' His words fade away, pleasure overwhelming the bird as you smile at him, knowing that your efforts are appreciated.";
	say "     After a while, the stork starts gently rocking his hips towards you at an irregular pace; between that and his wings pressing harder against you, you know that he is already close to orgasm. In a nice change of pace from what you came to expect in this city, he does not force your head on his crotch or hump you in a dominating manner, instead letting out a very light moan as his body seem to tense and relax simultaneously, almost leaking out his seed rather than spurting it as he cums inside of your mouth. He quietly whispers, 'O-oh yeah...' as he finishes, enticing you to swallow the cum you had dutifully kept in your mouth so far, making an audible gulping sound to make sure he'd know. Gus looks down at you with a satisfied grin, obviously happy to keep his cock in your mouth for a moment. You certainly don't mind either, but after a little while, he gently pushes you away with his wings.";
	WaitLineBreak;
	say "     'Thank you for that. It was really cool, but I have to get a new client eventually. That's how life here goes, but that's how I like it, too!' He smiles and gives you a smooch. 'Well then, I hope you'll come back for more. And maybe you can get off too next time, okay?' He sticks his tongue out at you, and then wishes you goodbye as you leave.";

to say GusSex2: [get cunnilingus]
	say "     'Ooooh, me gusta! With much pleasure, [sir].' Gus gently encourages you to lean on the bed before kneeling in front of you right between your legs. Slowly, he starts removing your clothes, taking his time to reveal your pussy to him. The stork leans in and takes a breath of your musk, and then another, but, not wanting to frustrate you, eventually wastes little time before giving your pussy a lick, and is very soon eagerly lapping at it. You start relaxing, closing your eyes to focus on the sensations and resting your hands on the back of the stork's head, enticing him to keep going. The stork seems rather into it, clearly savoring your taste each time he plunges his tongue inside, and his enthusiasm and dedication soon earns him your moans, which only seems to motivate him further. You can feel him try new areas to lick inside of your pussy, experimenting to see how you react every time so that he can find the spots that please you the most.";
	say "     Of course, it is only a matter of time before he starts giving attention to your clitoris, and giving attention to it he certainly does, first with an occasional kiss that causes you to shudder and then a lick from time to time. He clearly enjoys teasing you, knowing that this spot is likely to be what you are yearning for him to focus on, and you close your legs around his head to entice him further. Eventually, he gives in and starts giving long, powerful licks to your clit, causing your pleasure to suddenly get much more intense and sending you into a frenzy of lustful cries.";
	WaitLineBreak;
	if (player is male and anallevel > 2):
		say "     The bird seems to enjoy this as much as you do, but still appears to have some more ideas on what to do with you; right when you start really getting into it, the bird, after sucking on one of his fingers, inserts it into your ass, adding this fingering to the oral stimulation, while starting to jerk you off with his other hand. This is truly what sends you to heaven, and you soon find yourself reaching climax surprisingly fast, happily orgasming and cumming on while Gus's head while he gets to drink your feminine juices. After a while, your orgasm dies down, and you are left panting and looking at the ceiling, feeling satisfied. While you enjoy the afterglow, Gus dutifully licks you clean, taking his time so that you can relax, gently brushing your clit every now and then to tease you some more, and occasionally switching to your cock and asshole.";
		say "     Ultimately you take a sitting position as Gus hands you your clothes; as you put your gear back on, he smiles and asks, 'Was that any good?' You smile and nod, insisting that he did a very good job. 'That's great to hear! It was very enjoyable for me, too. If you ever need more of that, or of something else, you come back, alright? I'm not going anywhere.' You two say your goodbyes, as Gus reaches under the bed for his comic book, eager to progress as much as he can until his next client and still licking off your taste on his beak.";
	else if anallevel > 2:
		say "     The bird seems to enjoy this as much as you do, but still appears to have some more ideas on what to do with you; right when you start really getting into it, the bird, after sucking on one of his fingers, inserts it into your ass, adding this fingering to the oral stimulation. This is truly what sends you to heaven, and you soon find yourself reaching climax surprisingly fast, happily orgasming while Gus gets to drink your juices. After a while, your orgasm dies down, and you are left panting and looking at the ceiling, feeling satisfied. While you enjoy the afterglow, Gus dutifully licks you clean, taking his time so that you can relax, gently brushing your clit every now and then to tease you some more, and occasionally switching to your asshole.";
		say "     Ultimately you take a sitting position as Gus hands you your clothes; as you put your gear back on, he smiles and asks, 'Was that any good?' You smile and nod, insisting that he did a very good job. 'That's great to hear! It was very enjoyable for me, too. If you ever need more of that, or of something else, you come back, alright? I'm not going anywhere.' You two say your goodbyes, as Gus reaches under the bed for his comic book, eager to progress as much as he can until his next client and still licking off your taste on his beak.";
	else:
		say "     The bird seems to enjoy this as much as you do, and soon, you find yourself reaching climax surprisingly fast, happily orgasming while Gus gets to drink your juices. After a little while, your orgasm dies down, and you are left panting and looking at the ceiling, feeling satisfied. While you enjoy the afterglow, Gus dutifully licks you clean, taking his time so that you can relax, and gently brushing your clit every now and then to tease you some more. Ultimately you take a sitting position as Gus hands you your clothes; as you put your gear back on, he smiles and asks, 'Was that any good?' You smile and nod, insisting that he did a very good job. 'That's great to hear! It was very enjoyable for me, too. If you ever need more of that, or of something else, you come back, alright? I'm not going anywhere.' You two say your goodbyes, as Gus reaches under the bed for his comic book, eager to progress as much as he can until his next client and still licking off your taste on his beak.";

to say GusSex3: [get blowjob]
	say "     'Right away, general captain [sir]!' The good-natured stork doesn't waste time getting down on his knees in front of the mattress, before you even have time to sit on it. As you prepare to remove your clothes to give him the needed access to your parts, you hear him complain: 'Hey, where's the fun in that? Let me do that part!' Giving a chuckle, you sit in front of him with your legs open. Giving you a playful smile, the avian slowly uses his taloned hands to remove your pants, taking his time and visibly enjoying it. Ultimately, he frees your cock, fully hard by now, and gives you an appreciative look. You almost feel like he's about to make a playful comment, but instead, he just leans in to take a whiff before giving your tip a few kisses. Apparently satisfied with your musk and taste, he start giving more and more kisses, making sure your balls also get some love.";
	say "     'As much as you appreciate the stork's enthusiasm, you soon find yourself wanting more, and start caressing his head, as to indicate it's time to take things further. Gus gets it, and with a big smile, he open his beak wide before softly closing it around your cock. After taking a few more seconds to enjoy your taste, the avian starts bobbing his head up and down. Surprisingly, he's going at a relatively fast pace, probably to make up for all that slow warm-up, which is a welcome change. Soon, you find yourself thrusting your hips lightly every time your partner's head goes down, finding a rhythm that suits you both and fucking his mouth nicely. The act seems to be equally pleasing for Gus, who lets out little moans of pleasure from time to time; you're not sure if it's from the excitement, because he is incredibly turned on by your dick, or simply because he is trying to show you that he's happy, but you certainly appreciate it.";
	WaitLineBreak;
	if (player is female and WSlevel > 2):
		say "     This goes on until Gus realizes from your panting and rapid thrusts that you are about to cum. To help you achieve climax, he stops his beak job to jerk you off, softly fingering your pussy with his other hand and opening his beak wide once again. When you orgasm, he is definitely very happy to receive all of the seed you have to give in his mouth. After you finish to cum, he gulps it all down, and then gives little kisses to your cock once again as you catch your breath. He then keeps on nursing your cock, sucking on it softly while you enjoy your afterglow and keeping it in his mouth. Seeing him so eager to please gives you an indecent idea, and with a grin, you put your hands on the back of the bird's head, giving him small pats as if this was your only goal, but truly to make sure he will not pull away in surprise. Then, you relax and sigh happily, letting go of another liquid that you need to release.";
		say "     When the yellow stream makes contact with his tongue, Gus doesn't understand what is going on and instinctively tries to pull back from your crotch. However, your hands prevent it by keeping him in place, and he has no choice but to receive your special gift. As he stays motionless, you wonder how he is going to react to this turn of event, but when you hear a gulp, you know that you just scored a win: the avian looks up at you, the edges of his beak extending into a smile, as he dutifully receives your piss and drinks it down. You take your time giving him his second drink of the hour, until your bladder is empty and you take a hold of your cock, shaking it while it is still in his beak so that your partner also gets to taste the last drops, before finally releasing the panting bird.";
		WaitLineBreak;
		say "     Wiping a drop that had overflowed from his beak with his wing, the whore licks his lips with a wide smile and a naughty look. 'That was rather risqué, [sir]. Luckily, I am more than happy to help you with this other need of yours. Thank you, [sir].' Standing back up, he hands you your clothes, and you dress up. When you look back at him, the stork has already grabbed his comic book from under the bed - or is it a new one? 'It was nice! If you feel like coming back for more, even soon, you know where to find me, alright?' He smiles, and you smile back, making your leave as the bird resumes his reading, his tongue softly licking the edge of his beak.";
	else if (anallevel > 2 and WSlevel > 2):
		say "     This goes on until Gus realizes from your panting and rapid thrusts that you are about to cum. To help you achieve climax, he stops his beak job to jerk you off, and sucks on a finger of his other hand before softly introducing it into your asshole, opening his beak wide once again. When you orgasm, he is definitely very happy to receive all of the seed you have to give in his mouth. After you finish to cum, he gulps it all down, and then gives little kisses to your cock once again as you catch your breath. He then keeps on nursing your cock, sucking on it softly while you enjoy your afterglow and keeping it in his mouth. Seeing him so eager to please gives you an indecent idea, and with a grin, you put your hands on the back of the bird's head, giving him small pats as if this was your only goal, but truly to make sure he will not pull away in surprise. Then, you relax and sigh happily, letting go of another liquid that you need to release.";
		say "     When the yellow stream makes contact with his tongue, Gus doesn't understand what is going on and instinctively tries to pull back from your crotch. However, your hands prevent it by keeping him in place, and he has no choice but to receive your special gift. As he stays motionless, you wonder how he is going to react to this turn of event, but when you hear a gulp, you know that you just scored a win: the avian looks up at you, the edges of his beak extending into a smile, as he dutifully receives your piss and drinks it down. You take your time giving him his second drink of the hour, until your bladder is empty and you take a hold of your cock, shaking it while it is still in his beak so that your partner also gets to taste the last drops, before finally releasing the panting bird.";
		WaitLineBreak;
		say "     Wiping a drop that had overflowed from his beak with his wing, the whore licks his lips with a wide smile and a naughty look. 'That was rather risqué, [sir]. Luckily, I am more than happy to help you with this other need of yours. Thank you, [sir].' Standing back up, he hands you your clothes, and you dress up. When you look back at him, the stork has already grabbed his comic book from under the bed - or is it a new one? 'It was nice! If you feel like coming back for more, even soon, you know where to find me, alright?' He smiles, and you smile back, making your leave as the bird resumes his reading, his tongue softly licking the edge of his beak.";
	else if player is female:
		say "     This goes on until Gus realizes from your panting and rapid thrusts that you are about to cum. To help you achieve climax, he stops his beak job to jerk you off, softly fingering your pussy with his other hand and opening his beak wide once again. When you orgasm, he is definitely very happy to receive all of the seed you have to give in his mouth. After you finish to cum, he gulps it all down, and then gives little kisses to your cock once again as you catch your breath. He then keeps on nursing your cock, sucking on it softly while you enjoy your afterglow and keeping it in his mouth for a while. Eventually, he leaves your crotch to rest and walks to your clothes, handing them to you so you can dress up.";
		say "     When you look back at him, the stork has already grabbed his comic book from under the bed - or is it a new one? 'Thank you [sir]', he says standing up. 'It was nice! If you feel like coming back for more, even soon, you know where to find me, alright?' He smiles, and you smile back, making your leave as the bird resumes his reading, his tongue softly licking the edge of his beak.";
	else if anallevel > 2:
		say "     This goes on until Gus realizes from your panting and rapid thrusts that you are about to cum. To help you achieve climax, he stops his beak job to jerk you off, and sucks on a finger of his other hand before softly introducing it into your asshole, opening his beak wide once again. When you orgasm, he is definitely very happy to receive all of the seed you have to give in his mouth. After you finish to cum, he gulps it all down, and then gives little kisses to your cock once again as you catch your breath. He then keeps on nursing your cock, sucking on it softly while you enjoy your afterglow and keeping it in his mouth for a while. Eventually, he leaves your crotch to rest and walks to your clothes, handing them to you so you can dress up.";
		say "     When you look back at him, the stork has already grabbed his comic book from under the bed - or is it a new one? 'Thank you [sir]', he says standing up. 'It was nice! If you feel like coming back for more, even soon, you know where to find me, alright?' He smiles, and you smile back, making your leave as the bird resumes his reading, his tongue softly licking the edge of his beak.";
	else if WSlevel > 2:
		say "     This goes on until Gus realizes from your panting and rapid thrusts that you are about to cum. To help you achieve climax, he stops his beak job to jerk you off, and sucks on a finger of his other hand before softly introducing it into your asshole, opening his beak wide once again. When you orgasm, he is definitely very happy to receive all of the seed you have to give in his mouth. After you finish to cum, he gulps it all down, and then gives little kisses to your cock once again as you catch your breath. He then keeps on nursing your cock, sucking on it softly while you enjoy your afterglow and keeping it in his mouth. Seeing him so eager to please gives you an indecent idea, and with a grin, you put your hands on the back of the bird's head, giving him small pats as if this was your only goal, but truly to make sure he will not pull away in surprise. Then, you relax and sigh happily, letting go of another liquid that you need to release.";
		say "     When the yellow stream makes contact with his tongue, Gus doesn't understand what is going on and instinctively tries to pull back from your crotch. However, your hands prevent it by keeping him in place, and he has no choice but to receive your special gift. As he stays motionless, you wonder how he is going to react to this turn of event, but when you hear a gulp, you know that you just scored a win: the avian looks up at you, the edges of his beak extending into a smile, as he dutifully receives your piss and drinks it down. You take your time giving him his second drink of the hour, until your bladder is empty and you take a hold of your cock, shaking it while it is still in his beak so that your partner also gets to taste the last drops, before finally releasing the panting bird.";
		WaitLineBreak;
		say "     Wiping a drop that had overflowed from his beak with his wing, the whore licks his lips with a wide smile and a naughty look. 'That was rather risqué, [sir]. Luckily, I am more than happy to help you with this other need of yours. Thank you, [sir].' Standing back up, he hands you your clothes, and you dress up. When you look back at him, the stork has already grabbed his comic book from under the bed - or is it a new one? 'It was nice! If you feel like coming back for more, even soon, you know where to find me, alright?' He smiles, and you smile back, making your leave as the bird resumes his reading, his tongue softly licking the edge of his beak.";
	else:
		say "     This goes on until Gus realizes from your panting and rapid thrusts that you are about to cum. To help you achieve climax, he stops his beak job to jerk you off, and opens his beak wide once again. When you orgasm, he is definitely very happy to receive all of the seed you have to give in his mouth. After you finish to cum, he gulps it all down, and then gives little kisses to your cock once again as you catch your breath. He then keeps on nursing your cock, sucking on it softly while you enjoy your afterglow and keeping it in his mouth for a while. Eventually, he leaves your crotch to rest and walks to your clothes, handing them to you so you can dress up.";
		say "     When you look back at him, the stork has already grabbed his comic book from under the bed - or is it a new one? 'Thank you [sir]', he says standing up. 'It was nice! If you feel like coming back for more, even soon, you know where to find me, alright?' He smiles, and you smile back, making your leave as the bird resumes his reading, his tongue softly licking the edge of his beak.";

to say GusSex4: [give anal]
	say "     As you suggest that you want to plunge your cock in the avian's tight hole, Gus smiles and gets on all fours on the edge of the bed, raising his feathered tail to show you what you're looking for. Appreciative and eager to feel him around your cock, you take position behind him, resting your hands on his cheeks and spreading them to take a good look at the stork's tailhole. Using his long neck to turn his head and look at you, your partner of the hour smiles and wriggles his ass for you before you lean over him and line up yourself with his hole, pushing in slowly. The whore lets out satisfied moans as you sink yourself inside of him, and soon more of them as you keep pushing forward. Ultimately you pull back before pushing again, giving small, slow thrusts to sink further each time, until you finally are all the way in. 'Oooh, now that's really nice', says the bird. You certainly agree, especially as he keeps pushing back against you even now that you're balls deep inside of him.";
	say "     You soon resume your thrusting, putting your hands on his hips so you that can help him push against you and enjoying each time the feeling of your balls slapping against his rear. Before long Gus is crying out loudly, making you guess that he truly has a thing for receiving anal; from the position and movements of his right arm, you guess that he is doubling the pleasure by jerking off his modest cock. Knowing that the bird is taking care of his modest shaft, you focus on fucking him nicely; the avian's ass feels amazing around your cock, and before long your thrusts are short and fast as you put all of your weight on your partner, pressing him hard against the bed, which is visibly to his liking as he encourages you further. 'Oh god, yes! Oh, that's the fucking stuff!'";
	WaitLineBreak;
	say "     Eventually your mind goes blank, his tight, welcoming ass becoming your whole world for a few seconds until, with a big thrust, you start releasing your seed. The long-awaited feeling is made even more delightful by the submissive moans of your partner, who you tell is orgasming at the same time you are, and you keep on giving a few strong thrusts, each time releasing more of your essence, until you are completely empty and your partner's ass is well-seeded. Catching your breath, you relax, keeping your cock inside of the stork's comfortable fuckhole. Meanwhile, said stork is still panting and moaning softly, visibly having not recovered from your fucking quite yet; given that he is pressed flat on his belly against the bed, you assume that he must be soaked in his own bird sperm, but as he doesn't seem to mind one bit, you don't see any reason that you should.";
	if WSlevel > 2:
		say "     After a while, the sight of the bird panting hard, and still visibly enjoying the feeling of your cock inside him, gives you a rather naughty idea. Understanding just how much the birdie loves being used, you decide to push things further, and subtly start putting all off your weight on his body again, pinning him against the bed in a position where he can barely move. As he doesn't seem to notice, probably too busy enjoying the afterglow, you relax and indulge in another physical need you have, starting to urinate inside of his ass. You're already buried in there after all, so why bother doing it somewhere else?";
		WaitLineBreak;
		say "     It only takes a few seconds for the bird's eyes to go wide in surprise and for his ass to suddenly tighten around your cock once again, as he gives you an astonished look. 'Hey, but you, oh, oooooh, oh my. Oh, wow.' You watch with a grin as the bird visibly relaxes, resting his head against the bed and closing his eyes with a little smile on his face. You can also feel his anus slowly relaxing, as it now accepts the flow of piss leaving your penis, and the two of you stay completely still; to the outside eye, you look like two lovers enjoying their afterglow in peace, but of course the two of you know that a little something extra is actually taking place. When you finish, Gus wriggles his ass a bit, as to milk you of any drops left, and then lets out a chuckle 'Well then. That was pretty bold of you, [sir]. I like that.' He winks at you, and you hold the submissive birdie boy close to you, your needs met in more ways than one.";
		say "     You two keep this position for a while, with the bird visibly very happy to keep you inside of him and you very happy to oblige him. Eventually however, after a few glances towards the entrance of the Shag Shack, Gus gets on his knees under you, indicating that it is time for the two of you to part ways for now. Rather than pulling out, you stay in place, letting him slowly remove himself by moving forward. He does so with heavy breaths, his anus obviously still getting stimulated by the action. Still under you as you keep your crouching position, he turns on his back to look up at you, visibly not minding that his back is getting soaked by the cum on the bed. The stork smiles at you widely, giving you a little peck on the mouth.";
		WaitLineBreak;
		say "     'A nice cock in my ass with a twist. What more can a bird ask for?' As you smirk with pride, Gus sighs, his face taking a look of regret. 'I'm afraid we're out of time. But I believe it was as nice for you...' he says while caressing the softening prick between your legs, 'that it was for me.' As you tell the bird that you definitely enjoyed his tight hole, his smile gets even wider. 'This kind of stuff remind me why I love my job so much.' He gives you another peck on the lips, and then sends you on your way. Giving a glance back, you see him lie on the bed with a hand rubbing his stomach, visibly enjoying the sensation of having his insides full of cum and urine.'";
	else:
		say "     You two keep this position for a while, with the bird visibly very happy to keep you inside of him and you very happy to oblige him. Eventually however, after a few glances towards the entrance of the Shag Shack, Gus gets on his knees under you, indicating that it is time for the two of you to part ways for now. Rather than pulling out, you stay in place, letting him slowly remove himself by moving forward. He does so with heavy breaths, his anus obviously still getting stimulated by the action. Still under you as you keep your crouching position, he turns on his back to look up at you, visibly not minding that his back is getting soaked by the cum on the bed. The stork smiles at you widely, giving you a little peck on the mouth.";
		WaitLineBreak;
		say "     'Thank you, [sir]. That was awesome! God I love a good cock in my ass.' As you smirk with pride, Gus sighs, his face taking a look of regret. 'I'm afraid we're out of time. But I believe it was as nice for you...' he says while caressing the softening prick between your legs, 'that it was for me.' As you tell the bird that you definitely enjoyed his tight hole, his smile gets even wider. 'This kind of stuff reminds me why I love my job so much.' He gives you another peck on the lips, and then sends you on your way. Giving a glance back, you see him lie on the bed with a hand rubbing his stomach, visibly enjoying the sensation of having his insides full of cum.'";

to say GusSex5: [receive vaginal]
	if player is male:
		say "     'Well of course, [sir].' The bird smiles and gives you a sultry look, before starting to undress you after asking permission to, taking his sweet time and clearly enjoying it. First, he removes your top, taking a step back to give an appreciative look, and then gets on his knees to remove everything left. You shudder a bit as he exposes your crotch, but Gus just smiles and leans in to take a whiff of your musk, giving your now erect penis a little kiss before giving it a lick. Standing up, he leads you to the bed on which you position yourself, on your knees with your legs spread so that the bird can mount you properly. And mount you he does, crawling over you and taking the top position, but unlike most monsters in this city who would have just rammed themselves in, he instead surrounds your waist with his arms to hold you close, his taloned hands caressing your chest as he rubs his beak against your cheek and whispers sweet words to you.";
		say "     As nice as those pre-mating cuddles are, you find yourself more and more aroused by his cock rubbing between your nether lips, which was no doubt the bird's plan, and you answer his whispers by asking him to enter you, to which he answers, 'Yes, [sir]' before slowly sinking in. You let out a heavy breath as his dick spreads your walls softly, and he quickly bottoms out, hugging you even stronger before starting to move his hips back and forth, covering your neck in kisses as he starts panting. His cock is rather small, especially compared to so many of the monsters out there, but his previous skillful teasing and continuous attentions, coupled with the fact that he softly grabs your cock and starts jerking it, are more than enough to make this, if not a mind-blowing fuck, at least a very enjoyable lovemaking. Soon, the two of you find a nice rhythm where his pushes forward and your pushes back are perfectly synchronized, which goes on for a long while.";
		WaitLineBreak;
		say "     Suddenly, you feel the male withdrawing completely. As you are about to complain, he gently makes you turn so that you're on your back. There, after you open your legs for him once more, he happily sinks back inside of you while also doubling on the kissing and cuddling, this new position making it much easier, and you soon wonder if there is any part of your face and chest still left unkissed or unlicked. He resumes jerking you off at the same time, and all those renewed attentions start driving you crazy in lust, and you hug the stork close to you just as he does the same, his hips still moving on their own as the male follows his natural need to fuck.";
		say "     Before long, both you and the stork are moaning loudly, aroused further by hearing each other voice their pleasure. As your bliss intensifies, the bird's thrusts become faster and stronger; clearly, he is not far from his release. Nevertheless, he is clearly doing an effort not to cum yet, likely so he can bring you to your own climax first. His grunts and mindless thrusts have replaced the soft lovemaking from before, which mirrors your own state as you finally cry in delight, reaching your peak and cumming all over your chest. Realizing that he can finally let go, Gus doesn't hesitate, thrusting harder than ever for a few seconds until his body goes still, the bird's dick spurting seed inside of your womb. His orgasm soon comes to a close, and all of the tension in his body suddenly evaporates; he even shortly puts all of his weight on you, which admittedly isn't that much weight, before recovering his strength and mumbling an apology.";
		WaitLineBreak;
		say "     Gus pulls out, for good this time, and you are about to stand up when he urges you not to do so yet, gently having you lie back down with his wing. Instead, he gently pushes your legs open once more and reaches for your leaking vagina, cleaning up his mess with his tongue until your pussy is clean... Well, on the outside at least. The bird stands up and finally encourages you to do so as well, offering you a wing for support. He picks up your clothes on the floor and offers them to you, passing you each piece of it after the previous one is back on you where it belongs.";
		say "     As you are back to the state that you were when you walked in, except for some more cum inside of you, Gus says 'You felt pretty great, [sir]. I hope you're satisfied with my [']performance['].' He says the last word in an overly serious tone, showing you that he is still as laid back as when you found him. 'Seriously though, I hope you liked it.' You assure the bird that his performance was very satisfying, which makes him smile even more. With a kiss on the cheek, he urges you to come back anytime you feel like it, and watches you leave the Shag Shack before resuming reading his comic book.";
	else:
		say "     'Well of course, [sir].' The bird smiles and gives you a sultry look, before starting to undress you after asking permission to, taking his sweet time and clearly enjoying it. First, he removes your top, taking a step back to give an appreciative look, and then gets on his knees to remove everything left. You shudder a bit as he exposes your crotch, but Gus just smiles and leans in to take a whiff of your musk before giving it a lick. Standing up, he leads you to the bed on which you position yourself, on your knees with your legs spread so that the bird can mount you properly. And mount you he does, crawling over you and taking the top position, but unlike most monsters in this city who would have just rammed themselves in, he instead surrounds your waist with his arms to hold you close, his taloned hands caressing your chest as he rubs his beak against your cheek and whispers sweet words to you.";
		say "     As nice as those pre-mating cuddles are, you find yourself more and more aroused by his cock rubbing between your nether lips, which was no doubt the bird's plan, and you answer his whispers by asking him to enter you, to which he answers, 'Yes, [sir]' before slowly sinking in. You let out a heavy breath as his dick spreads your walls softly, and he quickly bottoms out, hugging you even stronger before starting to move his hips back and forth, covering your neck in kisses as he starts panting. His cock is rather small, especially compared to so many of the monsters out there, but his previous skillful teasing and continuous attentions are more than enough to make this, if not a mind-blowing fuck, at least a very enjoyable lovemaking. Soon, the two of you find a nice rhythm where his pushes forward and your pushes back are perfectly synchronized, which goes on for a long while.";
		WaitLineBreak;
		say "     Suddenly, you feel the male withdrawing completely. As you are about to complain, he gently makes you turn so that you're on your back. There, after you open your legs for him once more, he happily sinks back inside of you while also doubling on the kissing and cuddling, this new position making it much easier, and you soon wonder if there is any part of your face and chest still left unkissed or unlicked. This new position and all those renewed attentions start driving you crazy in lust, and you hug the stork close to you just as he does the same, his hips still moving on their own as the male follows his natural need to fuck.";
		say "     Before long, both you and the stork are moaning loudly, aroused further by hearing each other voice their pleasure. As your bliss intensifies, the bird's thrusts become faster and stronger; clearly, he is not far from his release. Nevertheless, he is clearly doing an effort not to cum yet, likely so he can bring you to your own climax first. His grunts and mindless thrusts have replaced the soft lovemaking from before, which mirrors your own state as you finally cry in delight, reaching your peak. Realizing that he can finally let go, Gus doesn't hesitate, thrusting harder than ever for a few seconds until his body goes still, the bird's dick spurting seed inside of your womb. His orgasm soon comes to a close, and all of the tension in his body suddenly evaporates; he even shortly puts all of his weight on you, which admittedly isn't that much weight, before recovering his strength and mumbling an apology.";
		WaitLineBreak;
		say "     Gus pulls out, for good this time, and you are about to stand up when he urges you not to do so yet, gently having you lie back down with his wing. Instead, he gently pushes your legs open once more and reaches for your leaking vagina, cleaning up his mess with his tongue until your pussy is clean... Well, on the outside at least. After giving your cock a similar cleaning, the bird stands up and finally encourages you to do so as well, offering you a wing for support. He picks up your clothes on the floor and offers them to you, passing you each piece of it after the previous one is back on you where it belongs.";
		say "     As you are back to the state that you were when you walked in, except for some more cum inside of you, Gus says 'You felt pretty great, [sir]. I hope you're satisfied with my [']performance['].' He says the last word in an overly serious tone, showing you that he is still as laid back as when you found him. 'Seriously though, I hope you liked it.' You assure the bird that his performance was very satisfying, which makes him smile even more. With a kiss on the cheek, he urges you to come back anytime you feel like it, and watches you leave the Shag Shack before resuming reading his comic book.";

to say GusSex6: [receive anal]
	say "     Gus nods. 'But of course! If it pleases you, [sir].' You start stripping, but as you remove your top, you are surprised to feel someone behind you uncovering your bottom parts. It's the stork of course, and you let him help out, stepping out of your clothes after he pulls them down. You don't even have time to finish removing your top before you suddenly feel his taloned hands spread your buttcheeks, and his tongue getting a taste of you. You're still uncomfortably trying to remove your top when his tongue penetrates your anus, giving you a rimming to prepare what's to come. By the time you complete your stripping, his tongue is probing deep inside of you, and you are breathing heavily, putting a hand on the back of his head to hold him there and keep yourself steady. He is clearly used to the act, and his skillful tongue rubs you just right. However, this is just the warm-up, and soon enough he stops, standing next to you while licking his lips, and encouraging you to position yourself on the mattress with a peck on the cheek as you see that his cock is fully ready for you.";
	if player is herm:
		say "     You crawl on the bed and position yourself ready, soon joined by the bird who leans over you, surrounding you with an arm to hug you close as he lines up his cock with your ass. Thanks to his tongue work, he easily penetrates you., and as he gives little kisses on your cheek, he sinks further until he's all the way inside. Once that is done, he hugs you with both of his arms, both to help keeping steady in your fuck and to hold you close, and he starts moving his hips back and forth. The stork is clearly very enthusiastic, and his rhythm soon quickens as he keeps humping, however he certainly does not forget about your own pleasure, which is made obvious when he lowers his hands further down your body and starts both fingering your pussy and jerk you off in rhythm with his thrusts.";
		WaitLineBreak;
		say "     The triple stimulation, coupled with his other arm hugging you and his continued kissing and snuggling, provides a lot of simultaneous stimulation, and before long, his lovemaking brings you to ecstasy. Gus happens to reach his orgasm right before you do, letting out little moans as he unleashes his seed inside of your ass, only a second before the double masturbation and feeling of being filled send you over the edge, as you release both your cum and feminine juices on the bed beside you. The stork's animal instincts have clearly taken over his polite attitude, and he just humps you wildly for a little while, eager to release all of his semen inside of you. Ultimately he does so, and the two of you fall flat on the bed, panting hard and recovering. After a while, Gus slowly pulls out, continuing to smooch your neck and cheeks in the process. Standing up, he takes a second to catch his breath and walks to your clothes, picking them up and handing them to you.";
		say "     As you put your top on, the bird uses this as yet another opportunity to sneak up on your lower body parts, giving your ass, your cock, and your pussy a nice cleaning before you eventually finish dressing up as he watches appreciatively. 'I hope you liked it, [sir]. I'm more of a taker than a giver when it comes to ass, but I did my best to make it as fun for you as it was for me. And it's a very nice ass, by the way,' he concludes with a wink. Since the bird was so appreciative of it, you decide to walk away with a swagger so that he gets a good last look at it. As you look back, you can see his comic book back in his hands; however, his eyes are definitely peeking at your ass from behind it.";
	else if player is male:
		say "     You crawl on the bed and position yourself ready, soon joined by the bird who leans over you, surrounding you with an arm to hug you close as he lines up his cock with your ass. Thanks to his tongue work, he easily penetrates you, and as he gives little kisses on your cheek, he sinks further until he's all the way inside. Once that is done, he hugs you with both of his arms, both to help keeping steady in your fuck and to hold you close, and he starts moving his hips back and forth. The stork is clearly very enthusiastic, and his rhythm soon quickens as he keeps humping, however he certainly does not forget about your own pleasure, which is made obvious when he lowers one of his hands further down your body and takes a hold of your prick, starting to jerk it in rhythm with the thrusts.";
		WaitLineBreak;
		say "     The double stimulation, coupled with his other arm hugging you and his continued kissing and snuggling, provides a lot of simultaneous stimulation, and before long, his lovemaking brings you to ecstasy. Gus happens to reach his orgasm right before you do, letting out little moans as he unleashes his seed inside of your ass, only a second before your own cock erupts, spurting cum over the bed beside you. The stork's animal instincts have clearly taken over his polite attitude, and he just humps you wildly for a little while, eager to release all of his semen inside of you. Ultimately he does so, and the two of you fall flat on the bed, panting hard and recovering. After a while, Gus slowly pulls out, continuing to smooch your neck and cheeks in the process. Standing up, he takes a second to catch his breath and walks for your clothes, picking them up and handing them to you.";
		say "     As you put your top on, the bird uses this as yet another opportunity to sneak up on your lower body parts, giving both your ass and cock a nice cleaning before you eventually finish dressing up as he watches appreciatively. 'I hope you liked it, [sir]. I'm more of a taker than a giver when it comes to ass, but I did my best to make it as fun for you as it was for me. And it's a very nice ass, by the way,' he concludes with a wink. Since the bird was so appreciative of it, you decide to walk away with a swagger so that he gets a good last look at it. As you look back, you can see his comic book back in his hands; however, his eyes are definitely peeking at your ass from behind it.";
	else if player is female:
		say "     You crawl on the bed and position yourself ready, soon joined by the bird who leans over you, surrounding you with an arm to hug you close as he lines up his cock with your ass. Thanks to his tongue work, he easily penetrates you., and as he gives little kisses on your cheek, he sinks further until he's all the way inside. Once that is done, he hugs you with both of his arms, both to help keeping steady in your fuck and to hold you close, and he starts moving his hips back and forth. The stork is clearly very enthusiastic, and his rhythm soon quickens as he keeps humping, however he certainly does not forget about your own pleasure, which is made obvious when he lowers one of his hands further down your body and starts fingering your pussy in rhythm with his thrusts.";
		WaitLineBreak;
		say "     The double stimulation, coupled with his other arm hugging you and his continued kissing and snuggling, provides a lot of simultaneous stimulation, and before long, his lovemaking brings you to ecstasy. Gus happens to reach his orgasm right before you do, letting out little moans as he unleashes his seed inside of your ass, only a second before the vaginal stimulation and feeling of being filled send you over the edge, as you release your juices on the bed beside you. The stork's animal instincts have clearly taken over his polite attitude, and he just humps you wildly for a little while, eager to release all of his semen inside of you. Ultimately he does so, and the two of you fall flat on the bed, panting hard and recovering. After a while, Gus slowly pulls out, continuing to smooch your neck and cheeks in the process. Standing up, he takes a second to catch his breath and walks to your clothes, picking them up and handing them to you.";
		say "     As you put your top on, the bird uses this as yet another opportunity to sneak up on your lower body parts, giving both your ass and pussy a nice cleaning before you eventually finish dressing up as he watches appreciatively. 'I hope you liked it, [sir]. I'm more of a taker than a giver when it comes to ass, but I did my best to make it as fun for you as it was for me. And it's a very nice ass, by the way,' he concludes with a wink. Since the bird was so appreciative of it, you decide to walk away with a swagger so that he gets a good last look at it. As you look back, you can see his comic book back in his hands; however, his eyes are definitely peeking at your ass from behind it.";
	else:
		say "     You crawl on the bed and position yourself ready, soon joined by the bird who leans over you, surrounding you with an arm to hug you close as he lines up his cock with your ass. Thanks to his tongue work, he easily penetrates you, and as he gives little kisses on your cheek, he sinks further until he's all the way inside. Once that is done, he hugs you with both of his arms, both to help keeping steady in your fuck and to hold you close, and he starts moving his hips back and forth. The stork is clearly very enthusiastic, and his rhythm soon quickens as he keeps humping, however he is obviously intents on making you share this pleasure, as you can tell based on how he keeps nuzzling, kissing and caressing you passionately all while breeding your ass.";
		WaitLineBreak;
		say "     All those attentions provide a lot of simultaneous stimulation, and before long his lovemaking brings you to ecstasy. Gus happens to reach his orgasm right before you do, letting out little moans as he unleashes his seed inside of your ass, only a second before you reach your own. The stork's animal instincts have clearly taken over his polite attitude, and he just humps you wildly for a little while, eager to release all of his semen inside of you. Ultimately he does so, and the two of you fall flat on the bed, panting hard and recovering. After a while, Gus slowly pulls out, continuing to smooch your neck and cheeks in the process. Standing up, he takes a second to catch his breath and walks for your clothes, picking them up and handing them to you.";
		say "     As you put your top on, the bird uses this as yet another opportunity to sneak up on your ass, giving it a nice cleaning before you eventually finish dressing up as he watches appreciatively. 'I hope you liked it, [sir]. I'm more of a taker than a giver when it comes to ass, but I did my best to make it as fun for you as it was for me. And it's a very nice ass, by the way,' he concludes with a wink. Since the bird was so appreciative of it, you decide to walk away with a swagger so that he gets a good last look at it. As you look back, you can see his comic book back in his hands; however, his eyes are definitely peeking at your ass from behind it.";

Gus ends here.
