Version 1 of Icarus by Stripes begins here.
[Version 1 - Content added]

"Adds Icarus the Blue Chaffinch as an NPC to the Flexible Survival game"

[ hp of Icarus ]
[ 0 = untamed  ]
[ 1 = at bunker, no talk ]
[ 2 = talked  ]
[ 3 = taught to suck cock ]


Section 1 - Icarus the Blue Chaffinch

Icarus is a person.
The description of Icarus is "[Icarusdesc]";
The conversation of Icarus is { "Wilder!" }.
icarusscene is a truth state that varies.  icarusscene is usually false.

[See Blue Chaffinch file for collecting Icarus.]

the scent of Icarus is "[if facename of player is listed in infections of Avianpredlist]The blue songbird smells like prey.[otherwise]The blue songbird has a soft, pleasant scent.[end if]";


to say Icarusdesc:
	say "     This avian fellow is covered in bright blue plumage that is very even in colour across most of his body.  Only the ends of his wings and tail are a much darker midnight blue on the flight feathers, and his lower belly and the underside of his narrow tail are downy and white.  He has a puffy looking body compared to his slender arms and legs thanks to his soft feathers.  His head is rounded and shaped like that of a finch, though his beak is thicker.  Double-checking with one of the nature books in the library, you've confirmed that your assumption was right and that he's almost certainly been infected to resemble an exotic blue chaffinch.  His eyes are like black beads with a touch of white feathers just above and below.";
	say "     Lacking a name of his own, you've decided to call him Icarus.  Once strong and arrogant, your repeated rough treatment of him as a predatory avian has affected the passerine to the point that he's accepted to become your songbird slut.  He usually spends his daytime hours up in the rafters, singing softly[if the number of booked people > 2] for the others[end if].  He seems fairly happy here, as if accepting the spacious library as his birdcage.";

Instead of conversing the Icarus:
	if hp of Icarus is 0:
		say "ERROR-Icarus-0L: You should not be able to find me!";
	otherwise if hp of Icarus is 1:
		say "     He looks around the library in a very bird-like manner, his head twisting and turning as he looks.  This is a pretty nice place you've got in here.  Pretty spacious and the rafters make for a good perching spot.  It seems safe enough, too.  Good little cage for your caught birdie.'  Now that he's not trying to sound tough, you notice that he's got a soft, musical voice.";
		say "     He fidgets around for a moment, his wings rustling a little.  'Look... I... can you play with me like that again soon?' he asks with a touch of nervous excitement in his voice.  'I'd never have gone for that before, with a guy, especially not on the bottom.  But... just... something about it - the terror, the pain, the viceral lust.  I've never been so turned on in my life and I want you to do it again.  You were so... powerful - your talons grabbing me, your beak flashing - my blood was pumping with fear and anticipation before you tore into me with that cock of yours.  Any time you feel like being the scary predator bird, I'll be your weak, delicious prey.'";
		now hp of Icarus is 2;
	otherwise if icarusscene is false and a random chance of 1 in 3 succeeds:
		say "     Icarus flies down when you wave him over.  While you chat for a bit, he talks about the few bits he remembers about his old life.  'I remember being a big, tough guy before.  Strong and confident.  So when I woke up like this, part of me just couldn't accept it and tried to keep being that guy.  But you helped me realize that I'm a cute songbird slut now and how nice that can be.  I get to be your special birdie prey too, which makes it all the better.'";
		now icarusscene is true;
	otherwise:
		say "     [one of]Icarus sings a melodious tune from the rafters while you listen for a spell.[or]Holding up a nature book, Icarus shows you some photos of blue chaffinches.  'It seems they're only found on the Canary Islands.  I wonder how I ended up becoming one.  I don't really remember how I got transformed.  All I know is that I didn't see any others around.'[or]'You were such a wild hunter out there when you caught me.  It was so exhilerating.  I'm looking forward to you taking me like that again.'[or]'You don't need to worry about feeding me.  I managed to raid the zoo stores early on for a bunch of birdfeed, so I've got plenty of seeds.'[or]'I can hardly wait until the next time you feel like making me your prey and sinking your talons and cock into me.'[at random]";


Section 2 - Sexxxings

Part 0 - Basic Sex Menu

the fuckscene of Icarus is "[sexwithIcarus]".

to say sexwithIcarus:
	if hp of Icarus is 0:
		say "ERROR-Icarus-0F: You should not be able to find me!";
	otherwise if hp of Icarus is 1:
		say "     How about you talk to him first before fucking the little songbird again?";
	otherwise if cocks of player is 0 and cunts of player is 0:
		say "     Lacking any gender of your own, you feel there's little point in going to Icarus for sex.";
	otherwise if lastfuck of Icarus - turns < 6:
		say "     'Oh, I'm still worn out from the last time, but I [if bodyname of player is listed in infections of Avianpredlist and facename of player is listed in infections of Avianpredlist]do so want to go again soon[otherwise]hope you'll consider being the scary predator next time[end if].'";
	otherwise if hp of Icarus > 1:
		if cocks of player is 0:
			say "     The blue bird blushes a little and looks away, his wings fluttering.  'Look, before I might've, but... you see... to me you'll always be my fearsome, male hunter and it just wouldn't feel right.  If I wanted some pussy, I could just go out on the town and get it,' his old, macho voice coming back a bit for a bit before returning to normal.  'But for you, I just want to be your songbird slut and your prey, like you said.'  He shifts around eagerly on his taloned feat, clearly remembering the previous times you had your way with him.";
		otherwise if bodyname of player is listed in infections of Avianpredlist and facename of player is listed in infections of Avianpredlist:
			if a random chance of 3 in 5 succeeds:
				say "     Feeling the need to have some fun with your little songbird prey, you call him down.  As he's landing, you grab him and push him down over one of the tables quite roughly.  He moans as you push up his tailfeathers and spread his spindly legs, exposing the bird's white-feathered bottom.  The small passarine squirms and chirps a little, struggling not to get away, but enough so you as the strong predator have to pin him down as you get your cock lined up with his pucker.  As you push into him, he gives a groan of discomfort and pleasure, his tight hole being forced to spread open for your [cock size desc of player] [cock of player] phallus.";
				say "     He continues to squirm as you start humping away, driving you to grip him painfully hard with your talons.  Your lust and your instincts, already worked up by having the cute passarine beneath you, cause you to dig your talons into him to keep your prey from escaping.  Icarus cries out as you grip his ass painfully hard, though his cry is definitely one of pleasure.  When you reach around to stroke him off, his cock is rock hard and dribbling precum steadily.  Grinning, you nips hard at his shoulder with your beak, calling him your puny, slutty treat and grinning happily and he moans and nods in agreement, loving being the slutty prey for such a fearsome predator.";
				say "     You keep it up, something in the weak bird's behaviour egging you on to be rough with him.  Your bite his shoulder firmly with your beak several times while stuffing his ass with your dribbling rod.  And certainly, he loves it as well.  The throbbing of his cock in your hand and the way his asshole tightens around you suddenly is all the warning you get before the stuffed bird cums hard, splattering his load on the floor as you cum a few moments later, claiming his ass once again[if cock width of player > 35].  Your [cum load size of player] load leaves the poor songbird so bloated and full of your cum that some leaks out of his beak.  His body is left rounded like a feathery balloon from it all.  He can only give a weak chirp as you pull out and your hot cum pours of his stretched and stuffed ass, slowly deflating[otherwise if cock width of player > 25].  Your [cum load size of player] load leaves the poor songbird rounded like a feathery balloon.  When you pull out, he gives a weak chirp as your hot cum pours of his stretched and stuffed ass, slowly deflating[otherwise if cock width of player > 15].  Your [cum load size of player] load leaves the poor songbird somewhat chubbier looking than before, his belly stuffed quite full with your seed.  When you pull out, he gives a weak chirp as hot cum leaks from his stretched and stuffed ass[otherwise].  He gives a weak chirp when you pull out, hot cum leaking from his stretched and creamy ass[end if].  While giving him a bruisingly hard nip, you wipe your cock clean on his blue tailfeathers before heading off, leaving him there to eventually recover.";
			otherwise if hp of Icarus is 2:
				say "     In the mood for some fun with your little songbird, you call him down with the intent on training him to suck cock.  Once he's landed, you grab him roughly and push his face to your crotch.  You grind your throbbing rod against his feathered face, telling him to get to work.  He gulps nervously, but you also see an eagerness in his eyes as he stares at your [cock size desc of player] [cock of player] penis[esmn].";
				say "     He starts with a few tentative licks before you instruct him to open wide.  Holding his head as he opens his beak, you guide your cocktip to it and pull his head forward sharply.  He gives a wet groan as you push your shaft into his mouth, forcing the little birdie to take your [cock size desc of player] [cock of player] meat[if cock length of player > 20].  It takes a firm pull on Icarus's head to press your glans into his mouth and then down his throat, but the passarine only takes it with another moan of pleasure despite its [cock size desc of player] size[otherwise if cock length of player > 10].  It takes a bit of an extra push to get your glans into his small beak and down his throat, but the passarine only takes it with another moan of pleasure despite its [cock size desc of player] size[otherwise].  The passarine takes it in with a moan of pleasure[end if] as you stuff his virgin mouth with cock for the first time.";
				say "     Now that you're in his mouth[if cock length of player > 10] and throat[end if], you grip your birdie slut's head and start thrusting into his mouth while ordering him to start sucking.  He tries his best, but the little guy's quite inexperienced at it.  His new body's sexual instincts do seem to be helping him along, letting him use his beak without nipping you while learning quickly.  It takes a few instructions and a little practice for him to get warmed up, but soon enough he's sucking you off like he's done it plenty of times.  Chuckling that he's turning into quite the cock slut, you grin as a blush of red shows through his blue cheekfeathers and pound into his maw all the harder.";
				say "     With him working eagerly to suck the big, strong predator off, it's only a matter of time before you groan that you're about to cum.  He tries to pull back, but you yank his head forward again, telling him that you're not letting him get out of this and adding that you've got plenty of tasty seed to feed your caged birdie.  He moans and blushes all the more, sucking hungrily for it just as your reach your climax and start pumping your thick load into him[if cock width of player > 35].  Your [cum load size of player] load stuffs the poor songbird so bloated and full of your cum that eventually leaks out of the edges of his beak as he overflows.  His body is left rounded like a feathery balloon from it all.  He can only give a wet, gurgling chirp as you pull out and a gush of your hot cum pours of his mouth before he manages to swallow and hold back the flow[otherwise if cock width of player > 25].  Your [cum load size of player] load stuffs the poor songbird until he's rounded like a feathery balloon.  When you pull out, he gives a wet, gurgling chirp as a little of your hot cum trickles from his beak before he manages to swallow and hold the rest inside[otherwise if cock width of player > 15].  Your [cum load size of player] load leaves the poor songbird somewhat chubbier looking than before, his belly stuffed quite full with your seed.  When you pull out, he gives a weak chirp and licks his beak[otherwise].  He gives a weak chirp when you pull out, then licks his beak[end if].  Before leaving him there on the floor now that you're through, you tell him that you look forward to giving him plenty more training at it.  He can't help but blush and smile at the prospect.";
				now hp of Icarus is 3;
			otherwise:
				say "     Motioning for Icarus to come down, you grope and fondle the bird as he lands.  After stroking him to get him excited, you pull out your own erection and tell him to get sucking.  There is an eagerness in his eyes as he looks at your shaft and is soon on his knees, nuzzling and licking at your cock[smn] and balls.  Showing more flair and eagerness than his first attempt at it, his licking is accompanied by the soft stroking of his soft feathers against you sensitive flesh, sending shivers of delight through you.";
				say "     Pleased with his improvement, you place a hand at the back of his head while guiding your cock into his beak with an order to move on to sucking.  He nods and opens his beak wider as you press his head down overtop of your [cock size desc of player] [cock of player] shaft.  In the mood to get on with it after his sensual touches have gotten you worked up, you pull him forward, forcing more and more of your cock into his open maw[if cock length of player > 10] and down his throat[end if].  He moans in pleasure at this rough treatment of himself and sucking down on your shaft[if cock length of player > 20] as you work to get the whole of your impressive manhood into his mouth[end if].";
				say "     Now that you're in his mouth[if cock length of player > 10] and throat[end if], you grip your birdie slut's head in both hands and start thrusting firmly into it while he works hard to suck you off.  You tease him, saying that your tasty treat is learning quickly to be a cock slut.  He blushes red under his blue feathers, but also goes down on you all the more eagerly.";
				say "     With him working eagerly to suck you off, it's only a matter of time before you groan that you're about to cum.  He makes no attempt to pull back from the impressive hunter's cock, knowing you'll want to finish in him, accepting as you thrust all the harder into his mouth.  After a few more slams into him, you orgasm and start pumping your creamy cum into him.  This pushes Icarus over the edge and his cock, untouched from earlier, pulses and spurts his avian cum onto the floor in large splatters as he gulps down your seed[if cock width of player > 35].  Your [cum load size of player] load stuffs the poor songbird so bloated and full of your cum that eventually leaks out of the edges of his beak as he overflows.  His body is left rounded like a feathery balloon from it all.  He can only give a wet, gurgling chirp as you pull out and a gush of your hot cum pours of his mouth before he manages to swallow and hold back the flow[otherwise if cock width of player > 25].  Your [cum load size of player] load stuffs the poor songbird until he's rounded like a feathery balloon.  When you pull out, he gives a wet, gurgling chirp as a little of your hot cum trickles from his beak before he manages to swallow and hold the rest inside[otherwise if cock width of player > 15].  Your [cum load size of player] load leaves the poor songbird somewhat chubbier looking than before, his belly stuffed quite full with your seed.  When you pull out, he gives a weak chirp and licks his beak[otherwise].  He gives a weak chirp when you pull out, then licks his beak[end if].  Before leaving him there on the floor now that you're done with him, you tell him that he did well and that you look forward to giving him plenty more training at it, which has him blush, grin and lick his beak.";
			now lastfuck of Icarus is turns;
		otherwise:
			if a random chance of 3 in 5 succeeds:
				say "     Feeling the need to have some fun with your little songbird, you call him down.  As he's landing, you grab him and push him down over one of the tables.  He moans as you push up his tailfeathers and spread his spindly legs, exposing the bird's white-feathered bottom.  The small passarine squirms and chirps a little, struggling not to get away, but enough so you have to pin him down as you get your cock lined up with his pucker.  As you push into him, he gives a groan of discomfort and pleasure, his tight hole being forced to spread open for your [cock size desc of player] [cock of player] phallus.";
				say "     He settles down a little as you start humping away, chirping as he soon starts to beg for more.  Knowing how he's grown to like it, you grip one of his thin, feathered legs tightly and pound his ass hard and deep.  Even as he whimpers at the pain, he's also moaning in delight.  When you reach around to stroke him off, his cock is throbbing hard and dripping with precum.  Teasing him for being such a puny, little slut, you grin as he moans and nods in agreement, loving being a horny cock slut now.";
				say "     You keep it up, something in the weak bird's behaviour egging you on to be rough with him.  And certainly, he loves it as well.  The throbbing of his cock in your hand and the way his asshole tightens around you suddenly is all the warning you get before the stuffed bird cums hard, splattering his load on the floor as you cum a few moments later, claiming his ass once again[if cock width of player > 35].  Your [cum load size of player] load leaves the poor songbird so bloated and full of your cum that some leaks out of his beak.  His body is left rounded like a feathery balloon from it all.  He can only give a weak chirp as you pull out and your hot cum pours of his stretched and stuffed ass, slowly deflating[otherwise if cock width of player > 25].  Your [cum load size of player] load leaves the poor songbird rounded like a feathery balloon.  When you pull out, he gives a weak chirp as your hot cum pours of his stretched and stuffed ass, slowly deflating[otherwise if cock width of player > 15].  Your [cum load size of player] load leaves the poor songbird somewhat chubbier looking than before, his belly stuffed quite full with your seed.  When you pull out, he gives a weak chirp as hot cum leaks from his stretched and stuffed ass[otherwise].  He gives a weak chirp when you pull out, hot cum leaking from his stretched and creamy ass[end if].  While taking a moment to check that your birdie pet's still fine, you wipe your cock clean on his blue tailfeathers before heading off, leaving him there to eventually recover.";
			otherwise if hp of Icarus is 2:
				say "     In the mood for some fun with your little songbird, you call him down with the intent on training him to suck cock.  Once he's landed, you grab him and push his face to your crotch.  You grind your throbbing rod against his feathered face, telling him to get to work.  He gulps nervously, but you also see an eagerness in his eyes as he stares at your [cock size desc of player] [cock of player] penis[esmn].";
				say "     He starts with a few tentative licks before you instruct him to open wide.  Holding his head as he opens his beak, you guide your cocktip to it and pull his head forward.  He gives a wet groan as you push your shaft into his mouth, forcing the little birdie to take your [cock size desc of player] [cock of player] meat[if cock length of player > 20].  It takes a firm pull on Icarus's head to press your glans into his mouth and then down his throat, but the passarine only takes it with another moan of pleasure despite its [cock size desc of player] size[otherwise if cock length of player > 10].  It takes a bit of an extra push to get your glans into his small beak and down his throat, but the passarine only takes it with another moan of pleasure despite its [cock size desc of player] size[otherwise].  The passarine takes it in with a moan of pleasure[end if] as you stuff his virgin mouth with cock for the first time.";
				say "     Now that you're in his mouth[if cock length of player > 10] and throat[end if], you pat your birdie slut's head and order him to start sucking.  He tries his best, but the little guy's quite inexperienced at it.  His new body's sexual instincts do seem to be helping him along, letting him use his beak without nipping you while learning quickly.  It takes a few pointers and a little while for him to get warmed up, but soon enough he's sucking you off like he's done it plenty of times.  Chuckling that he's turning into quite the cock slut, you grin as a blush of red shows through his blue cheekfeathers.";
				say "     With him working eagerly to suck you off, it's only a matter of time before you groan that you're about to cum.  He tries to pull back, but you grip his head tightly, telling him that you've got some tasty seed to feed the little birdie.  He blushes all the more and sucks hungrily for it just as your reach your climax and start pumping your thick load into him[if cock width of player > 35].  Your [cum load size of player] load stuffs the poor songbird so bloated and full of your cum that eventually leaks out of the edges of his beak as he overflows.  His body is left rounded like a feathery balloon from it all.  He can only give a wet, gurgling chirp as you pull out and a gush of your hot cum pours of his mouth before he manages to swallow and hold back the flow[otherwise if cock width of player > 25].  Your [cum load size of player] load stuffs the poor songbird until he's rounded like a feathery balloon.  When you pull out, he gives a wet, gurgling chirp as a little of your hot cum trickles from his beak before he manages to swallow and hold the rest inside[otherwise if cock width of player > 15].  Your [cum load size of player] load leaves the poor songbird somewhat chubbier looking than before, his belly stuffed quite full with your seed.  When you pull out, he gives a weak chirp and licks his beak[otherwise].  He gives a weak chirp when you pull out, then licks his beak[end if].  Before leaving him there on the floor to recover, you tell him that he did well for a first time and that you look forward to giving him plenty more training at it.  He can't help but blush and grin at the prospect.";
				now hp of Icarus is 3;
			otherwise:
				say "     Motioning for Icarus to come down, you grope and fondle the bird as he lands.  After stroking him to get him excited, you pull out your own erection and tell him to get sucking.  There is an eagerness in his eyes as he looks at your shaft and is soon on his knees, nuzzling and licking at your cock[smn] and balls.  Showing more flair than his first attempt at it, his licking is accompanied by the soft stroking of his soft feathers against you sensitive flesh, sending shivers of delight through you.";
				say "     Pleased wiht his improvement, you rub a hand over his head before pushing it forward with an order to move on to sucking.  He nods and opens his beak wide, leaning forward to take your [cock size desc of player] [cock of player] shaft in his mouth.  Feeling he's going a little slow after his sensual touches have gotten you worked up, you pull him forward, forcing more of your cock into his open maw[if cock length of player > 10] and down his throat[end if].  He moans in pleasure at this rough treatment of himself and starts sucking down on your shaft[if cock length of player > 20] as he works to get the rest of your impressive manhood into his mouth[end if].";
				say "     Now that you're in his mouth[if cock length of player > 10] and throat[end if], you pat your birdie slut's head and start thrusting while he works hard to suck you off.  You tease him, saying he's learning quickly to be a cock slut.  He blushes red under his blue feathers, but also goes down on you all the more eagerly.";
				say "     With him working eagerly to suck you off, it's only a matter of time before you groan that you're about to cum.  He makes no attempt to pull back, knowing you'll want to finish in him, accepting as you thrust harder into his mouth.  After a few more hard pushes into him, you orgasm and start pumping your creamy cum into him.  This pushes Icarus over the edge and his cock, untouched from earlier, pulses and spurts his avian cum onto the floor as he gulps down your seed[if cock width of player > 35].  Your [cum load size of player] load stuffs the poor songbird so bloated and full of your cum that eventually leaks out of the edges of his beak as he overflows.  His body is left rounded like a feathery balloon from it all.  He can only give a wet, gurgling chirp as you pull out and a gush of your hot cum pours of his mouth before he manages to swallow and hold back the flow[otherwise if cock width of player > 25].  Your [cum load size of player] load stuffs the poor songbird until he's rounded like a feathery balloon.  When you pull out, he gives a wet, gurgling chirp as a little of your hot cum trickles from his beak before he manages to swallow and hold the rest inside[otherwise if cock width of player > 15].  Your [cum load size of player] load leaves the poor songbird somewhat chubbier looking than before, his belly stuffed quite full with your seed.  When you pull out, he gives a weak chirp and licks his beak[otherwise].  He gives a weak chirp when you pull out, then licks his beak[end if].  Before leaving him there on the floor to recover, you tell him that he did well and that you look forward to giving him plenty more training at it, which has him blush, grin and lick his beak.";
			now lastfuck of Icarus is turns;



Icarus ends here.