Version 2 of Incubus For FS by Stripes begins here.
[ Version 2.4 - Added libido pill as drop item ]

"Adds an Incubus creature to Flexible Survival's Wandering Monsters table"
[Created in thanks for Wahn for all his hard work helping with typos]

Section 1 - Monster Responses

incubusnosex is a number that varies.

when play begins:
	add { "Incubus" } to infections of guy;
	add { "Incubus" } to infections of hellspawn;

to say losetoincubus:
	now incubusnosex is 0;
	if bodyname of player is "Incubus" or bodyname of player is "Succubus":
		if cunts of player > 0:
			say "     Unwilling or unable to continue resisting the infernal temptation that the incubus provides, you give your body up to him.  Stepping up to you, he runs his hands over your face and shoulders, lightly caressing you.  'Mmm... I see that you've already begun to accept our infernal gifts and give into your lustful nature.  Good.'  He guides you onto all fours and lets his tail slide across your body, sending shivers of delight through your tainted flesh.";
			say "     The incubus moves atop you, rubbing his throbbing cock between your cheeks, leaking precum steadily.  You can't help but moan as his tail continues to sensually tease you as he lets his glans brush across your anus before continuing on down to your wet slit.  It slides against your folds teasingly, making you beg for him to fuck you.  He grins at this and slides his tongue across your cheek, then nibbles your ear.  'Certainly, my dear.  Let's make some hellspawn.'  With that, he thrusts into you.";
			say "     The pleasure you feel as his large, perfect cock pushes into you is one of utter, sinful delight.  He fucks you hard and fast, rocking his hips and pumping his shaft into you.  His hands roam over your body, joining his tail in teasing against your flesh.  It is only the soft sound of the beating of his wings that tells you how he's supporting himself so easily atop you.  His body, penis, fingers, tongue, mouth and tail all move with the practiced ease of one who's spent countless ages exploring sexual pleasure and loving every moment of it.  You cannot help but cum repeatedly from it all, your pussy practically overflowing with lustful juices from almost continual orgasms.";
			say "     Finally, after what feels like hours of sinful fucking, he drives his shaft fully into you and unleashes his hot seed, pouring his tainted load into your womb[if cocks of player is 1].  Your balls tighten and your cock throbs as he pumps it, spraying your semen onto his waiting hand before bringing it forward for you both to lustfully lap up[otherwise if cocks of player > 0].  He pumps at your cocks, playfully stroking each to orgasm in turn while his other hand waits to catch the load.  Each sticky handful of cum is brought forward for you both to lustfully lap up[end if].  His large balls slap against your thighs as he drains them his infernal seed into you.  Spent, he pushes you to the ground, gives you a lustful kiss and heads off in nimble leaps across the rubble as his little wings flap frantically.[impregchance]";
		otherwise:
			say "     Unwilling or unable to continue resisting the infernal temptation that the incubus provides, you give your body up to him.  Stepping up to you, he runs his hands over your face and shoulders, lightly caressing you.  'Mmm... I see that you've already begun to accept our infernal gifts and give into your lustful nature.  Good.'  He guides you onto all fours and lets his tail slide across your body, sending shivers of delight through your tainted flesh.";
			say "     The incubus moves atop you, rubbing his throbbing cock between your cheeks, leaking precum steadily.  You can't help but moan as his tail continues to sensually tease you as he lets his glans brush across your anus, letting his pre get it slick.  It presses lightly against your tight back entrance teasingly, soon making you beg for him to fuck you.  He grins at this and slides his tongue across your cheek, then nibbles your ear.  'Certainly, my dear.  Let us enjoy the forbidden male lust.'  With that, he thrusts into you.";
			say "     The pleasure you feel as his large, perfect cock pushes into you is one of utter, sinful delight.  He fucks you hard and fast, rocking his hips and pumping his shaft into you.  His hands roam over your body, joining his tail in teasing against your flesh.  It is only the soft sound of the beating of his wings that tells you how he's supporting himself so easily atop you.  His body, penis, fingers, tongue, mouth and tail all move with the practiced ease of one who's spent countless ages exploring sexual pleasure and loving every moment of it.  You cannot help but moan and push back into his thrusts as he buggers you, your asshole practically milking at his cock with lustful need.";
			say "     Finally, after what feels like hours of sinful fucking, he drives his shaft fully into you and unleashes his hot seed, pouring his tainted load into your bowels[if cocks of player is 1].  Your balls tighten and your cock throbs as he pumps it, spraying your semen onto his waiting hand before bringing it forward for you both to lustfully lap up[otherwise if cocks of player > 0].  He pumps at your cocks, playfully stroking each to orgasm in turn while his other hand waits to catch the load.  Each sticky handful of cum is brought forward for you both to lustfully lap up[end if].  His large balls slap against your thighs as he drains them his infernal seed into you.  Spent, he pushes you to the ground, gives you a lustful kiss and heads off in nimble leaps across the rubble as his little wings flap frantically.[impregchance]";
	otherwise if player is submissive and ( ( cunts of player > 0 and a random chance of 3 in 5 succeeds ) or ( cocks of player is 0 and a random chance of anallevel in 5 succeeds ) ):
		say "     [if hp of player > 0]Having submitted to[otherwise]Beaten by[end if] the infernal temptation of the incubus, you are pushed down by the alluring male.  Looking up at the creature who's bested you - an his stiff erection - your submissive tendencies kick in.  Licking your lips, you reach for his cock without even realizing it.  You only take notice of your actions and the fact that you're welcoming his perfect penis into your mouth when he chuckles darkly.";
		say "     'It seems you're already quite well suited to becoming my slutty plaything.  Go on, toy, suck that cock you so clearly desire.'";
		say "     You blush at his order and submit yourself to the demonic tempter's will.  You work your tongue along its smooth flesh and across its leaking glans.  And sucking on the incubus's cock only makes you more aroused[if cocks of player > 0 and cunts of player > 0], rock hard and dripping yourself[otherwise if cocks of player > 0], rock hard yourself[otherwise if cunts of player > 0], dripping yourself[end if].  By the point he tells you to [if cunts of player > 0]lay down and spread your legs[otherwise]get on all fours and raise your ass[end if], you do so without hesitation.";
		if cunts of player > 0:
			say "     To tease you, he first lets his tail brush tantalizingly across your juicy pussy a few times while he [if breast size of player > 1 and a random chance of 2 in 3 succeeds]squeezes your breasts[otherwise if cocks of player > 0]strokes your throbbing manhood[otherwise]holds its folds open with his graceful fingers[end if].  This causes you to moan and beg for him to fuck you, to which he grins.  Moving into position above you, he gets his saliva-slick cock to your cunny.  'Mmm... your desire for my infernal penis is simply [italic type]delicious[roman type],' he says, savouring the final word as he starts sinking his shaft into your needy vagina.  Feeling that perfect cock penetrating you causes you to moan with sinful delight.";
			say "     While your submissive body desires a good, hard pounding, he starts slowly and sensually, building your arousal higher.  [if cocks of player > 0].  Leaving one hand to tend to your erection[smn], the other roams[otherwise].  His hands roam[end if] across your body, joining his tail in teasing against your flesh.  With what feels like the experience of millenia, this demonic lover soon has you squirming in delight beneath him, your body begging for him to ravage you.  Grinding your hips up into each thrust, you plead for him to fuck you hard, but he keeps himself in check.  While his skillful lovemaking allows your pussy several small orgasms, you're denied the powerful release your [bodytype of player] body starts to ache for as he continues to tantalizingly deny you for quite some time.";
			say "     It is only once you start moaning for your master to take you, to fill you like the slutty whore[if player is impreg_able], to breed you like the fucktoy pet you are[end if] that he finally relents and pounds you with infernal zeal.  You cry out in sinful ecstasy, your hips being raised as he kneels up and drills hard and deep into you over and over again.  Your pussy quivers around his meat as you feel your rapidly approaching climax.  In the end, you orgasm long and hard, your body trembling as waves of delight run through you and your cunt milks at his cock with need[if cocks of player > 0].  Your penis[esmn] throb[smv] with an aching need of their own, splattering you with your own cum in long arcs of sticky semen[end if].  Grinning at how he's manipulated your body and lust so easily, he drives his throbbing rod deep inside you and releases his own load, pumping shot after gooey shot of demonic seed into you, claiming your womb.  While the excess flows out around his pulsing shaft, his tainted load fills your uterus with a wet heat that oozes deeper still, as if almost to your very soul.  Once he's drained his balls inside you, he pulls out and leaves you on the ground in a dazed afterglow.  He gives you a tongue-filled kiss and a final grope before heading off in nimble leaps across the rubble as his little wings flap frantically.[impregchance]";
		otherwise:
			say "     To tease you, he first lets his tail brush tantalizingly across your tight hole a few times[if cocks of player > 0] while he strokes your throbbing manhood[end if].  This causes you to moan and beg him to fuck you, to which he grins.  Moving into position, he gets his saliva-slick cock to your anus.  'Mmmm... your desire for the forbidden male lust is simply [italic type]delicious[roman type],' he says, savouring the final word as he starts sinking his shaft into your tight hole.  Feeling that perfect cock penetrating you causes you to moan with sinful delight.";
			say "     While your submissive body desires a good, hard pounding, he starts slowly and sensually, building your arousal even higher[if cocks of player > 0].  Leaving one hand to tend to your erection[smn], the other roams[otherwise].  His hands roam[end if] across your body, joining his tail in teasing against your flesh.  With what feels like the experience of millenia, this demonic lover soon has you squirming in delight beneath him, your body begging for him to ravage you.  And even when you start to beg him to do so, he continues to teasingly deny you for some time, always drawing you close and then backing away from your orgasm.";
			say "     It is only once you start moaning for your master to take you, to fill you like the slutty pet you are that he finally relents and pounds you with infernal zeal.  You cry out in sinful ecstasy, your ass pressing back into those hard thrusts while your anus squeezes and milks at his cock[if cocks of player > 0].  Feeling his pounding thrusts against your prostate while he pumps your manhood soon drives you over the edge.  You cum long and hard, your pent up cum blasting from your balls and pooling beneath you[otherwise].  While lacking a direct means of release, the rough fucking sends shudders of pleasure through your [bodytype of player] body as you feel a rush of heat[end if].  Grinning at how he's manipulated your body and lust so easily, he drives his throbbing rod deep inside you and releases his own load, pumping shot after gooey shot of demonic seed into you, claiming your ass.  His tainted load fills your bowels with a wet heat that oozes deep inside you, as if almost to your very soul.  Once he's drained his balls inside you, he pulls out and leaves you on the ground in a dazed afterglow.  He gives you a tongue-filled kiss and a final grope before heading off in nimble leaps across the rubble as his little wings flap frantically.[mimpregchance]";
		decrease humanity of player by a random number between 4 and 8;
		if "Strong Psyche" is listed in feats of player, increase humanity of player by 2;
		if "Weak Psyche" is listed in feats of player, decrease humanity of player by 2;
	otherwise if cunts of player > 0:
		say "     Unwilling or unable to continue resisting the infernal temptation that the incubus provides, you give your body up to him.  Stepping up to you, he runs his hands over your face and shoulders, lightly caressing you.  'Mmm... I'm glad [if hp of player > 0]you've accepted[otherwise]you're no longer resisting[end if] your body's lustful needs.  Now let's give you a body to match those sinful desires,' he says with a dark smile.  He guides you onto all fours and lets his tail slide across your body, sending shivers of delight through you.";
		say "     The incubus moves atop you, rubbing his throbbing cock between your cheeks, leaking precum steadily.  You can't help but moan as his tail continues to sensually tease you as he lets his glans brush across your anus before continuing on down to your wet slit.  It slides against your folds teasingly, making you beg for him to fuck you.  He grins at this and slides his tongue across your cheek, then nibbles your ear.  'Certainly, my dear.  Let's corrupt this mortal body of yours.'  With that, he moves his cock back up to your asshole and thrusts into you.";
		say "     The disappointment you feel for being denied his cock is countered by the pleasure you feel as his large, perfect cock pushes into you.  It is an utter, sinful delight to feel that perfect cock sink into your rear, sodomizing you.  He fucks you hard and fast, rocking his hips and pumping his shaft into you.  His hands roam over your body, joining his tail in teasing against your flesh.  It is only the soft sound of the beating of his wings that tells you how he's supporting himself so easily atop you.";
		say "     His tail moves down to you denied pussy and pushes into you, its large spade made of soft flesh that spreads you open as it pushes into you.  Your cunt quivers in delight at this, delighting in the sensation of having something in it after being denied your lover's cock.  His body, penis, fingers, tongue, mouth and tail all move with the practiced ease of one who's spent countless ages exploring sexual pleasure and loving every moment of it.  You cannot help but moan and push back into his thrusts as he buggers you, your asshole practically milking at his cock with lustful need while your cunt overflows with the juices of continual orgasms.";
		say "     Finally, after what feels like hours of sinful fucking, he drives his shaft fully into you and unleashes his hot seed, pouring his tainted load into your bowels and you cum hard around his thrusting tail[if cocks of player is 1].  Your balls tighten and your cock throbs as he pumps it, spraying your semen onto his waiting hand before bringing it forward for you both to lustfully lap up[otherwise if cocks of player > 0].  He pumps at your cocks, playfully stroking each to orgasm in turn while his other hand waits to catch the load.  Each sticky handful of cum is brought forward for you both to lustfully lap up[end if].  His large balls slap against your thighs as he drains them his infernal seed into you.  Spent, he pushes you to the ground, gives you a lustful kiss and heads off in nimble leaps across the rubble as his little wings flap frantically.";
	otherwise:
		say "     Unwilling or unable to continue resisting the infernal temptation that the incubus provides, you give your body up to him.  Stepping up to you, he runs his hands over your face and shoulders, lightly caressing you.  'Mmm... I'm glad [if hp of player > 0]you've accepted[otherwise]you're no longer resisting[end if] your body's lustful needs.  Now let's give you a body to match those sinful desires,' he says with a dark smile.  He guides you onto all fours and lets his tail slide across your body, sending shivers of delight through you.";
		say "     The incubus moves atop you, rubbing his throbbing cock between your cheeks, leaking precum steadily.  You can't help but moan as his tail continues to sensually tease you as he lets his glans brush across your anus, letting his pre get it slick.  It presses lightly against your tight back entrance teasingly, soon making you beg for him to fuck you.  He grins at this and slides his tongue across your cheek, then nibbles your ear.  'Certainly, my dear.  Let us enjoy the forbidden male lust.'  With that, he thrusts into you.";
		say "     The pleasure you feel as his large, perfect cock pushes into you is one of utter, sinful delight.  He fucks you hard and fast, rocking his hips and pumping his shaft into you.  His hands roam over your body, joining his tail in teasing against your flesh.  It is only the soft sound of the beating of his wings that tells you how he's supporting himself so easily atop you.  His body, penis, fingers, tongue, mouth and tail all move with the practiced ease of one who's spent countless ages exploring sexual pleasure and loving every moment of it.  You cannot help but moan and push back into his thrusts as he buggers you, your asshole practically milking at his cock with lustful need.";
		say "     Finally, after what feels like hours of sinful fucking, he drives his shaft fully into you and unleashes his hot seed, pouring his tainted load into your bowels[if cocks of player is 1].  Your balls tighten and your cock throbs as he pumps it, spraying your semen onto his waiting hand before bringing it forward for you both to lustfully lap up[otherwise if cocks of player > 0].  He pumps at your cocks, playfully stroking each to orgasm in turn while his other hand waits to catch the load.  Each sticky handful of cum is brought forward for you both to lustfully lap up[end if].  His large balls slap against your thighs as he drains them his infernal seed into you.  Spent, he pushes you to the ground, gives you a lustful kiss and heads off in nimble leaps across the rubble as his little wings flap frantically.[impregchance]";
	if libido of player > 80, now libido of player is 80;
	if "Female Preferred" is listed in feats of player and girl is not banned:
		infect "Succubus";
	otherwise:
		infect "Incubus";


to say beattheincubus:
	if bodyname of player is "Incubus" or bodyname of player is "Succubus":
		if cocks of player > 0:
			say "     'Well done, my infernal sibling,' the incubus says with a smile as he bows in submission to you.  'You are definitely the more powerful seducer,' he acknowledges with another, lower bow and you can't help but smile, feeling strangely at ease now that the combat is over.  'Shall you claim your prize?' he says with a grin, turning around and getting onto all fours.  His tail arches up and his shapely, bubble butt is offered to you.  You are quite tempted by the sight, eager to give him the good, hard fucking he would have given you.  Shall you?";
			if the player consents:
				say "     You move atop him eagerly, bringing your throbbing cock to his dark pucker.  He moans lustfully and pushes back, spearing himself onto your [cock size desc of player] shaft with the ease of one who's been taken by the cocks of numerous demonic creatures before.  The feel of his gripping, squeezing walls around your cock is exquisite, filling you with such sinful pleasure at buggering that hot hole.  His anus is like a hot vice around your shaft and almost seems to suck on it with its lustful need for your seed.  You let your hand roam over his muscled body, then move it down to stroke over that perfect cock of his.";
				say "     When you finally cum, painting his inner walls with your semen, he cums as well with a loud cry of sexual pleasure.  He holds a cupped hand into the spurting blasts, gathering a palmful of his tainted load.  He laps up some of it and, when he offers you some as well, you are too lost in your lustful pleasure to even consider refusing.  You lap up the rest and even suck his fingers clean.  After withdrawing, you both rise and he gives you a passionate French kiss while running his hands over your body.  'I look forward to you joining our ranks more fully so we may continue to share in the pleasures of the flesh,' he whispers while nibbling your ear before bounding off across the rubble in nimble leaps, flapping his little wings frantically.  You watch him go while his tainted seed sends warm tingles through your body.";
				if libido of player > 80, now libido of player is 80;
				if "Female Preferred" is listed in feats of player and girl is not banned:
					infect "Succubus";
				otherwise:
					infect "Incubus";
			otherwise:
				say "     When you refuse, the incubus['] face briefly becomes one of demonic anger before returning to its beautiful appearance.  'Very well, then.  Perhaps you will be more accommodating once you join our ranks more fully.  I promise to show you such wonderful pleasures of the flesh, my dear,' he says with a dark smile.  'I expect you will become a most impressive temptation,' he says, still grinning.  'I hope you'll accept my offers for sinful delights when that time comes, or perhaps the next time we meet,' he adds with a slow lick across the spaded tip of his tail.  With that, he turns and bounds off across the rubble in nimble leaps, his little wings flapping frantically.";
		otherwise:
			say "     'Well done, my infernal sibling,' the incubus says with a smile as he bows in submission to you.  'You are definitely the more powerful seducer,' he acknowledges with another, lower bow and you can't help but smile, feeling strangely at ease now that the combat is over.  'I look forward to you joining our ranks more fully so we may share in the pleasures of the flesh.  I expect you will become a most impressive temptation,' he says with a grin.  'I hope you'll accept my offers for sinful delights when that time comes, or perhaps the next time we meet,' he adds with a slow lick across the spaded tip of his tail.  With that, he turns and bounds off across the rubble in nimble leaps, his little wings flapping frantically.";
	otherwise if cocks of player > 0 and incubusnosex < 3:
		say "     'Alas, I am defeated,' the incubus moans as it staggers back as it tries to remain standing.  'I cannot resist your might any further,' the incubus says as he falls to his knees.  'You may now make use of my body as you would,' he says with an exaggerated sigh, reaching for your groin and licking his lips.  Shall you take your prize and make the sex demon blow you, or will you refuse this final temptation?";
		if the player consents:
			say "     Wanting a go at the sex demon's hot mouth, you grab his head and pull him forward onto your cock.  He moans softly as you thrust between his soft, wet lips and starts sucking expertly.  His hands roam across your ballsac, your thighs and your ass as he works eagerly to blow you.  Your infernal lover is very good at it, working his whole mouth to build you up to the biggest climax he can.  With a talent brought from centuries of such depravities, the demon's mouth offers such a sinful delight.";
			if "Less Anal" is not listed in feats of player and a random chance of 2 in 3 succeeds:
				say "     As the great blow job continues, you enjoy the moans of the incubus sucking you off.  As he performs a particularly pleasurable bit of tonguework that has you panting and groaning, you feel a slick digit slip between your cheeks and probing at your anus.  Too aroused and into getting sucked off, you don't resist as that wet finger makes its way into your rectum to rub at your prostate.  You moan and clench down on it as you blow your load, shooting your hot seed into the demonic boytoy's mouth to feed his dark lusts.  The finger's withdrawn slowly with a wet pop and your cock released.";
				say "     'Mmm... that was most enjoyable.  Do you see how much better it could be now if you just give in and accept the pleasures of the flesh?' he says with a grin as he rises with ease.  He makes a show of licking his lips before turning and bounding off across the rubble in nimble leaps, his little wings flapping frantically.  It is not until he's gone that you notice the warm, wet feeling of your anus and look down to see the puddle of incubus cum with a finger streak through it.";
			otherwise:
				say "     As the great blow job continues, you enjoy the moans of the incubus sucking you off.  As he performs a particularly pleasurable bit of tonguework that has you panting and moaning, he grabs your balls with a warm, sticky hand and rubs them firmly.  This soon has you over the edge and shooting your hot seed into the demonic boytoy's mouth to feed his dark lusts.  He licks and sucks your cock clean, then nibbles on your balls lightly.";
				say "     'Mmm... that was most enjoyable.  Do you see how much better it could be now if you just give in and accept the pleasures of the flesh?' he says with a grin as he rises with ease.  He makes a show of licking his lips before turning and bounding off across the rubble in nimble leaps, his little wings flapping frantically.  It is not until he's gone that you notice the warm, wet feeling on your ballsac and look down to see the puddle of incubus cum with a hand streak through it.";
			if "Female Preferred" is listed in feats of player and girl is not banned:
				infect "Succubus";
			otherwise:
				infect "Incubus";
		otherwise:
			say "     The incubus['] eyes burn and his face briefly becomes one of demonic anger before returning to its beautiful appearance.  'Very well, then.  Should you change your mind, I promise to show you such wonderful pleasures of the flesh, my dear,' he says with a dark smile.  'I expect you will become a most impressive temptation,' he says, still grinning.  'I hope you'll accept my offers for sinful delights when that time comes, or perhaps the next time we meet,' he adds with a slow lick across the spaded tip of his tail.  With that, he rises with ease and bounds off across the rubble in nimble leaps, his little wings flapping frantically.";
			increase incubusnosex by 1;
	otherwise:
		say "     'It is unfortunate that you aren't interested in the pleasures I could offer you,' the incubus says as he staggers back from your assault.  'I could have shared such sensual pleasures of the flesh with you,' he says with a disappointed sigh before turning and bounding off in nimble leaps across the rubble, his little wings flapping frantically.";


to say incubus fight:
	say "[one of]The incubus zips up beside you incredibly quickly, pressing his throbbing shaft against you as his hands teasingly play across your body, making you strongly consider just giving in to him![or]The incubus lands a one-two combo of punches that strike with unnatural might![or]The incubus does an acrobatic flip back and stretches his body in a sensual display, making you long for its sinful pleasures![or]The demonic creature grabs your wrists and stares deep into your eyes.  His eyes seem to glow and your will to keep resisting wavers![or]The incubus weaves in close to you and presses his body to yours.  As he gropes you, his tongue slides along your neck and up to your ear, which he gives a playful nibble![or]The demonic seducer spins, slapping his tail across your ass, then rubs it teasingly against your sore bottom before pulling it away again![at random]";
	increase libido of player by a random number from 3 to 8;
	if bodyname of player is "Succubus" or bodyname of player is "Incubus", increase libido of player by a random number between 1 and 2;
	if "Horny Bastard" is listed in feats of player, increase libido of player by 1;
	if "Cold Fish" is listed in feats of player, decrease libido of player by 1;
	if libido of player >= 110:
		say "You find yourself too aroused to keep fighting the handsome seducer and drop to your knees.  Having fallen under the sway of this dark tempter, you long to submit yourself to his lustful desires.";


to say incubusdesc:
	say "     You are confronted by a person who moves to block your path.  At first, you could almost mistake him for a handsome man, were it not for some extra features which confirm a more sinister nature.  Atop his lovely face are a pair of small, red horns and his eyes are dark and slitted.  At his back, he has a pair of bat-like wings.  These are small, each roughly the size of his well-manicured hands.  From the end of his spine extends a long, slender tail ending in a spaded tip.  His physique is well-toned and his [one of]cream[or]pink[or]tan[or]chocolate[at random] skin is smooth and without blemish despite the mess of the surrounding city.  His body is beautifully muscled, but not massively so, looking like a statue of Adonis come to life.  His tail gives a swish as he looks you over with a lustful grin.  '[one of]Now, you may be able to provide some amusement,[or]Give in to your urges and enjoy physical pleasure,[or]I'm looking forward to filling you properly,[or][if cunts of player > 0]Spread your legs[otherwise]Bend over[end if] for me, my lovely.  You know you want me in you,[or]I know what you desire.  Let me give it to you,[or]Join me in delicious, sinful pleasure,[at random]' he says with a silky, seductive voice and a sinister smile on his full, red lips.  His hands run across his shapely body, showing it off for you before moving down to slide over his erect cock, nine inches of hard, throbbing, human and utterly perfect-looking man meat.";


Section 2 - Monster Insertion

Table of random critters (continued)
name	attack	defeated	victory	desc	face	body	skin	tail	cock	face change	body change	skin change	ass change	cock change	str	dex	sta	per	int	cha	sex	hp	lev	wdam	area	cocks	cock length	cock width	breasts	breast size	male breast size	cunts	cunt length	cunt width	libido	loot	lootchance	scale (number)	body descriptor (text)	type (text)	magic (truth state)	resbypass (truth state)	non-infectious (truth state)	nocturnal (truth state)	altcombat (text)
--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	-- 	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--;

[ Adds a blank row to the table, this is immediately filled ;) ]
When Play begins:
	Choose a blank row from Table of random critters;
	now name entry is "Incubus";		[The creature's name as displayed and used in naming descriptions]
	now attack entry is "[incubus fight]";	[Text used when the monster succeeds on an attack]
	now defeated entry is "[beattheincubus]";				[ Text when monster loses.  Change 'template' as above. ]
	now victory entry is "[losetoincubus]";					[ Text when monster wins.  Change 'template' as above. ]
	now desc entry is "[incubusdesc]";						[ Description of the creature when you encounter it. ]
	now face entry is "that a beautiful human, with lovely features, full lips and a seductive smile.  Your eyes are dark and slitted.  Growing from your brow are a pair of small, red horns";
	now body entry is "that of a handsome and attractive human being, toned and strong.  Attached to your back are a pair of bat-like wings.  These are red and quite small, barely hand-sized";
	now skin entry is "[one of]soft, human[or]pristine[or]perfect[at random]";
	now tail entry is "You have a round, bubble butt with a long, slender tail attached.  It is a classic devil tail: thin, red and ending in a spaded tip.";	[ Tail desc., written as a full sentence or left blank for none. ] 
	now cock entry is "[one of]amazing[or]incubus[or]perfect[or]human-like[at random]";
	now face change entry is "your facial muscles seem to ripple under the skin, rearranging themselves into a softer, more sexually attractive appearance.  Small horns push out of your brow"; [ face change text. format as "Your face feels funny as (your text)" ]
	now body change entry is "it is reshaped into a more attractive form, though you are soon distracted from this change by the strange feeling of your skin stretching and pressing out from your back.  Looking over your shoulder, you stare in wonder as two small bulges of flesh push out of your back, before popping open in an almost orgasmic release.  You now have a small pair of blood red bat wings on your back";
	now skin change entry is "your skin seems to soften and smooth out, any blemishes and unwanted hair wiped away with a wonderfully pleasant sensation that leaves you with perfect skin";
	now ass change entry is "it tightens up into a perfect, sexy ass, forming a wonderfully fuckable bubble butt";
	now cock change entry is "it seems to grow partially erect and twitch eagerly, almost like it has a mind of it's own, eagerly hunting for the next chance to be put to use";
	now str entry is 16;			[ The player's stats will move towards these values through infection. ]
	now dex entry is 20;			[ Only the monster's dexterity has any effect in combat. ]
	now sta entry is 12;			[ These numbers should reflect a fully infected player's stats, not the attacking monster's. ]
	now per entry is 16;
	now int entry is 10;
	now cha entry is 25;
	now sex entry is "Male";		[ Infection will move the player towards this gender.  Current: 'Male' 'Female' 'Both' ]
	now hp entry is 50;			[ The monster's starting hit points. ]
	now lev entry is 8;			[ Monster level.  (Level x 2) XP for victory.  (Level / 2) XP for losing. ]
	now wdam entry is 14;			[ Monster's average damage when attacking. ]
	now area entry is "Campus";		[ "Outside" "Mall" "Park" "Beach" etc... Check an existing creature in the area. ]
	now cocks entry is 1;			[ Number of cocks the infection will try to cause if sex entry is 'Male' or 'Both'. ]
	now cock length entry is 9;		[ Length infection will make cock grow to if cocks. ]
	now cock width entry is 7;		[ Cock width, more commonly used for ball size. ]
	now breasts entry is 0;			[ Number of breasts the infection will give a player. ]
	now breast size entry is 0;		[ Size of breasts the infection will try to attain. ]
	now male breast size entry is 0;	[ Breast size for if Sex="Male", usually zero. ]
	now cunts entry is 0;			[ The number of cunts the infection will try to cause if sex entry is 'Female' or 'Both'. ]
	now cunt length entry is 0;		[ Depth of female sex the infection will attempt to give a player. ]
	now cunt width entry is 0;		[ Width of female sex the infection will try to give a player. ]
	now libido entry is 80;			[ Target libido the infection will rise towards. ]
	now loot entry is "libido pill";			[ Dropped item, blank for none.  Case sensitive. ]
	now lootchance entry is 20;		[ Percentage chance of dropping loot, from 0-100. ]
	[ These represent the new additions to the table of random critters ]
	now scale entry is 3;				[ Number 1-5, approx size/height of infected PC body: 1=tiny, 3=avg, 5=huge ]
	now body descriptor entry is "[one of]alluring[or]sexy[or][if cocks of player > 0]handsome[otherwise]sultry[end if][at random]";
	now type entry is "demonic";		[ one-word creature type. Ex: feline, canine, lupine, robotic, human... Use [one of] to vary ]
	now magic entry is true;			[ Is this a magic creature? true/false (normally false) ]
	now resbypass entry is false;			[ Bypasses Researcher bonus? true/false (almost invariably false) ]
	now non-infectious entry is false;		[ Is this a non-infectious, non-shiftable creature? True/False (usually false) ]
	blank out the nocturnal entry;		[ True=Nocturnal (night encounters only), False=Diurnal (day encounters only), blank for both. ]
	now altcombat entry is "default";		[ Row used to designate any special combat features, "default" for standard combat. ]

[A sample structure for succumbing/surviving messages at the end of the game.]
[Numerous other examples can be found in existing creature files.]

when play ends:
	if bodyname of player is "Incubus":
		if player is pure, project the figure of incubus1_icon;
		if humanity of player is less than 10:
			if cocks of player > 0 and cunts of player > 0:
				say "     Finally giving in to your new body's sexual urges, you waste no time in following the call of the others of your kind back to the campus where they've been tempting the college students and professors alike into sinful decadence.  There, you quickly hunt down one of your incubi brethren and pounce onto him.  While he smiles at first at the feel of your cock against him, he is surprised to feel your breasts and cunt there are well.  Grinning evilly, you roll him onto all fours and start fucking the surprised incubus senseless.  Gripping the base of his cock, you keep him from cumming as you fuck him again and again, your feminine side allowing you repeated orgasms that soon have him moaning and begging beneath you.  Once he's finally acknowledged you as his superior, you roll him over and drive your cunt down over his aching cock, finally letting him cum inside you in one massive, release.";
				say "     Your new minion leads you back to the other incubi's lair, finding them in a lustful orgy with each other and their captive pets.  You waste no time in filling each and every one of them with your demonic seed while denying them release until they submit to you and give their tainted load to your hungering pussy.  Soon enough, they are all bowing before you in subjugation, their lustful master and mistress in one.  Unable to keep up with your insatiable new body, your new subjects hail you as their king.  Your horns grow larger, curving over your flowing hair and becoming pitch black at the base as your former tormentors worship your powerfully attractive body.";
				say "     Still, their worship isn't quite enough and while you are quite certain more incubi will come from your bountiful womb, you will need more playthings to satisfy yourself now.  After fucking all of their captive pets, breeding them full of your incubi spawn, you command your subjects to go forth and seek out more pets to fuck and people to convert.  While you enjoy the ones already here and those new playthings they bring in, still you aren't satisfied and you send them further afield.";
				say "     The military camp proves to be the perfect place for your incubi to hunt, all the horny, young soldiers being easily led astray by the forbidden temptations provided by the sexual demons.  They are converted into either more incubi themselves or into pets for your pleasure, depending on how lustful and depraved their weak minds are.  Quickly, the camp falls into chaos as more and more soldiers give into the temptations of your minions.  The quarantine attempts failing as they are unable to reinforce the barricades with soldiers joining your ranks faster than they can be deployed.  While those incubi you create in the horny pets are normal incubi, those birthed from your womb are hermaphroditic like yourself and further help to accelerate the conquest.";
				say "     While the other creatures in the city begin to escape through the fallen lines, you and your incubi are further amused by this, letting them go so they make someday become lovely little pets as well for your people.  Your forces continuously spread out and secure the rest of the territory around here as more and more people give into the pleasures of the flesh.  A new kingdom rises up from the ruins of their pathetic, little civilization.  It is a kingdom of incubi, based on sex and pleasure, with you at its head, dark king and mistress to all the incubi.  Your herm offspring become the ruling class among them, the lords running their territories in your name and submitting themselves until you for breeding every year.";
			otherwise if cocks of player > 0:
				say "     Succumbing to the sexual desires of your lustful body, you find yourself following the call of the others of your kind back to the campus where they've been tempting the college students and professors alike into sinful decadence.  There you are greeted with open arms by your incubus brothers, welcomed with kisses and fondling.  Joining your new brethren in celebration of your new form, you return their kissing and groping in kind.  You run your hands over their sexy bodies just as eagerly as theirs run over yours, adoring their perfect, sculpted beauty.  But simple touches aren't enough to satisfy your infernal desires and soon enough you all are sharing in a lustful orgy, enjoying every sinful pleasure two males may share.";
				say "     After your lustful welcome, you all break up to go roam the city some more, looking eagerly for more survivors to convert.  While you find a number of already converted beasts and creatures as you prowl the streets, they are hardly able to satisfy your infernal lusts for long.  A few you find make fine pets to divert yourself or to breed full of tainted spawn, but little more.  Fortunately for you, it isn't long before the rescue comes, bringing much more enjoyable diversion in the form of the horny, young soldiers.  You are able to sidle up to several squads of those handsome soldiers as they come to [']rescue['] you.  Your sensual body provides unnatural temptation to them as you tease and kiss them, whispering how much you want to [']thank['] them for coming to save you into all their gullible ears.  Soon enough, each batch of soldiers and any others they've found in need of help gives in to you and is well on its way to joining you as a lovely incubus brother or becoming a nicely oversexed female pet for you and your brethren to enjoy.  And the best part is there always seems to be more horny, gullible soldiers to tempt into decadent, male lust.";
			otherwise if cunts of player > 0:
				say "     Succumbing to the sexual desires of your lustful body, you find yourself following the call of the others of your kind to the campus where they've been tempting the college students and professors alike into sinful decadence.  Arriving there, you are soon met by a handsome incubus approaching you with a sultry sway and a collar and leash in his head.  'Now, here I see we have another lustful pet for my brothers and I to enjoy,' he says as he examines your form with an amused grin on his red lips.  'It looks like you've come to accept your place as another lovely breeder for us, now haven't you?' he purrs into your ear as he brushes the loop of the leash across your wet folds, making you shiver with arousal.  'All you need do now is accept your place and put on the collar, my sweet plaything,' he says, licking around the edge of your ear as he holds it up to you, 'and we'll share such pleasures with you.'  Part of you deep down knows that you will never be the same if you put on the collar, but the need of your body is too great and you long to accept the promised pleasures at any price.";
				say "     Taking the collar, you slip it around your neck and the latch seems to vanish and you can feel something deep inside you being collared and chained as well.  Fastening the leash to your collar, the incubus grins and licks your juices from its leather handle before leading you down the streets like a good pet, your cunt dripping juices with every step.  Soon, you can't help but fantasize about all the ways you can be a good, little pet and breedtoy for your master, serving him and his brothers like a good fucktoy when they're not out hunting for more innocent people to make into sexy pets like you.  Arriving at the lobby of a large condominium building, you look up to see a group of gathered incubi smiling and grinning at you eagerly.  As your new master parades you around the room, you see several other pets already serving their own masters in the corners, their bellies swollen with growing hellspawn.  You realize all those dirty little fantasies are about to come true.";
			otherwise:		[neuter]
				say "     Succumbing to the sexual desires of your lustful body, but having no means of release, you find yourself following the call of the others of your kind to the campus where they've been tempting the college students and professors alike into sinful decadence.  Arriving there, you are soon met by a handsome incubus approaching you with a sultry sway and a collar and leash in his head.  'Now, here I see we have another lustful pet for my brothers and I to enjoy,' he says as he examines your form with an amused grin on his red lips.  'What an amusing creature you are,' he purrs into your ear as he brushes the loop of the leash across your bare groin, making you shiver a little.  You find the infernal creature very arousing despite your condition and you moan in need.  'All you need do now is accept your place and put on the collar, my sweet plaything,' he says, licking around the edge of your ear as he holds it up to you. 'I'm very curious to see how you'll respond to the pleasures we can provide.'  Part of you deep down knows that you will never be the same if you put on the collar, but the need of your body is too great and you long to accept the promised pleasures at any price.";
				say "     Taking the collar, you slip it around your neck and the latch seems to vanish and you can feel something deep inside you being collared and chained as well.  Fastening the leash to your collar, the incubus grins and rubs your bare groin before leading you down the streets like a good pet, your body hot with a growing arousal you cannot sate.  Soon, you can't help but fantasize about giving yourself to him, serving him and his brothers like a good fucktoy when they're not out hunting for more innocent people to make into sexy pets.  Arriving at the lobby of a large condominium building, you look up to see a group of gathered incubi smiling and grinning at you eagerly.  As your new master parades you around the room, you see several other pets already serving their own masters in the corners, their bellies swollen with growing hellspawn.";
				say "     Your nature as a neutered incubus draws considerable curious interest from the gathered incubi.  As your master cuddles you in his lap, rubbing his cock against your rear, there is much discussion among them about how you'll react.  Your excitement grows until all you can do is moan incoherently before he slides his cock into your tight ass and another fills your mouth with his cock.  The feel of those perfect cocks inside you provide such pleasure, if little actual relief, for your lusts";
				if a random chance of 1 in 2 succeeds:
					say ".  They have their way with you until they cum hard, pumping their loads into you.  Your incubus body, made for sexual pleasure, provides them with considerable pleasure and you enjoy their ample loads, lustfully delighting in the feel of it being pumped into you.  You're shared around with all the others, each taking turns with you non-stop, pumping you full of more and more cum as already failing mind is obliterated in a sea of arousal.  You become a moaning, squirming being of unsatisfied lust, feeling only momentary pleasure when someone's cumming inside you.  You become a cum-bucket for the group, enjoying to fuck you full of cum and almost feeding off your eternal lust.  They even share you with any pets they have with cocks, letting even them bugger your needy body.  You spent the rest of your existence soaked and stuffed with cum in a state of unreleased arousal, loving every moment of it.";
				otherwise:
					say ".  They have their way with you until they cum hard, pumping their hot loads into you.  Their cocks throb and their balls pulse as they spurt again and again, pumping everything they have to give in a lustful display while moaning about how wonderful it is and that it's the best sex they've ever had.  You moan and squirm in your master's lap as a powerful orgasm wracks your body, filling you with such sensual pleasure as you've never known before.  When they finally collapse back, their cocks and balls are gone, completely drained away into cum to fill you.";
					say "     The other incubi are surprised by this, but something about the display has aroused them as well and they don't flee or attack.  When you and the other nullified incubi rise and move to take hold of other cocks, the wild sex is repeated again with the same results and effect.  Soon enough, all of them are converted into new nullcubi and they turn to their pets.  Licking cunts, sucking cocks and nursing from nipples, the pets are pleasured until they cum repeatedly and are remade into genderless sluts.  Those pregnant pets enjoy a rapidly progressing pregnancy and birth of nullcubi children before their pussies close up forever.  Once all are converted, the lustful nullcubi head out into the city.  They lust for the delight of the only sexual release they have, bringing others to a final, overpowering orgasm that leaves them nullcubi like themselves.";
		otherwise:
			say "     When the rescue comes, you are quite happy to leave this place behind and go with the military.  Your new form gets numerous speculative looks from the soldiers, your attractive body tempting quite a few of them and you find yourself tempted to sneak around with a few of them.  Once you are clear of the military and free to do as you please, you consider what you'd like to do for a living now that you've changed so drastically.  While you ponder the matter, you move around, finding lovers of various sorts from those infected and not, finding [if charisma of player > 16]it easy to seduce almost anyone you desire[otherwise]several you are able to persuade[end if] into having sex with you.  After a few months of living a life of hedonistic abandon, you grow bored with it and seek to find something more fulfilling to do with your time outside of sex.";
			say "     Deciding to seek out a television career, you are easily able to seduce your way into an interview and soon enough a position at a major news network.  Your attractive, sexually exciting body draws in the viewers, making your segments on the changing world and the nanite infection very popular.  Rather than waste your time gathering the news, you report the events, adding a particularly lustful flair to everything.  You become the voice of the news for the network and eventually the top name in news, skyrocketing with popularity that keeps you surrounded by lustful fans, guest stars and coworkers to satisfy your lustful desires.";
			say "     And as your audience grows, they also start to grow more accepting of the changing world and their sexual desires and your reporting reflects this.  More guests appear naked or even showing off their altered bodies and the populace responds, seeking to change themselves into the forms you clearly enjoy the most as you showcase them.  While never directly credited, the effect of your career greatly accelerates the world's cascade into a new, lustful era of sexual, infected diversity.";

[ Edit this to have the correct creature name as well]
Incubus For FS ends here.
