Version 5 of Forest Events by Aureas Gigas begins here.
[ Version 5 - Fifth Event ]

One flew into the Cuckoos Nest is a situation.
The sarea of One flew into the Cuckoos Nest is "Forest".
CuckooWatched is a number that varies. CuckooWatched is usually 0.

when play begins:
	add One flew into the Cuckoos Nest to badspots of humorous;
	add One flew into the Cuckoos Nest to badspots of guy;
	add One flew into the Cuckoos Nest to badspots of girl;

Instead of resolving a One flew into the Cuckoos Nest:
	now battleground is "void"; [prevents a random fight, as these are replacement random fights]
	say "     Moving through the woods, you reach a small clearing that seems rather peaceful. All around, some remains of the buildings from before the forest took over are visible between the trunks, and it seems like people are actually living here. There are a few tents and improvised shelters here and there. One spot in the middle of it might have been a bus stop - with two benches side by side, that looks like the perfect spot to rest a little after your tiring work of exploring.";
	say "     While walking towards the bench, you pass by a small tent with a male and female cuckoo inside... and can't help but throw a look inside at them. Based on the affectionate ways the two are talking and holding each other, you think that they are probably a couple. With a smile on your lips, you move on and sit down on the nearby bench. Sitting down relieves your aching muscles and re-energizes your body. A short while later, the male cuckoo steps out of the tent and calls back to his mate that he is going to hunt for supplies, then leaves into the woods.";
	WaitLineBreak;
	say "     He is barely out of sight before a burly white-coated bull strolls over to the tent and glances inside, then asks, 'Is he gone?' Stepping out to meet him, the female anthro bird nods and starts kissing the tall bovine. They vanish inside the tent together, and from the muted grunts and moans coming out of it, you can guess what's going on in there now. Chuckling at the antics of these people, you get up from the bench eventually and move back out into the woods to continue your exploration. A couple of minutes down a narrow footpath between the trees, you cross paths with the male cuckoo from before - on his way back towards the settlement.";
	say "     [bold type]Remembering what is happening in his tent, part of you wants to give the man a little warning before he walks in on his partner having an affair.[roman type][line break]";
	LineBreak;
	say "     ([link]Y[as]y[end link]) - Warn the guy.";
	say "     ([link]N[as]n[end link]) - Don't say anything.";
	if player consents:
		say "     You stop the Cuckoo and stumble with your words describing this awkward situation. The bird's eyes light up and he says, 'Oh! Thank you for telling me!' He then starts to sprint down the path, moving quickly towards his home. Curious to see what will happen next, you follow him. As he approaches the tent, the anthro bird stops and peeps at it from behind a bush. You hide there as well so you don't attract any attention.";
		say "     Through the opening of the tent you can see the cuckoo girl riding the bull's long tapered cock in a reverse cowgirl position, her body exposed for anyone outside the tent to see. Aroused by this the male cuckoo begins to softly stroke his dick. It doesn't take too much longer before the bull bellows a loud moo and comes inside the girl. He takes a second to catch his breath before quickly leaving.";
		WaitLineBreak;
		say "     Stepping out of the entrance of the tent, still naked and with a trickle of cum running down the inside of her thighs, the cuckoo girl smiles and calls to you, 'You can come out now Gray, and tell your [if player is female]friend[else]buddy[end if] that they can come out as well.' The male cuckoo stands up and replies, 'Be right there Izzy.' Turning to you, he smiles and bashfully begins to explain that this kind of thing is normal for them. Seems like their infection left Izzy with a desire for big dicks and Gray with the desire to see her take them. Gray then hugs Izzy and playfully asks if 'she's grabbed life by the horns'. She gives him a friendly little swat against the chest and the two of them start to cuddle. You leave them be so they can enjoy an intimate moment.";
		now CuckooWatched is 1; [warned the guy and saw the resolution with them happy together]
	else:
		say "     Deciding it's not worth it to get involved in this type of drama, you keep your mouth shut and keep walking.";
		now CuckooWatched is 100; [ignored the cuckoos]
	now One flew into the Cuckoos Nest is resolved;
	now Two Crash into the Cuckoos Nest is not resolved;

Two Crash into the Cuckoos Nest is a situation.	Two Crash into the Cuckoos Nest is resolved.
The sarea of Two crash into the Cuckoos Nest is "Forest".

when play begins:
	add Two crash into the Cuckoos Nest to badspots of humorous;
	add Two crash into the Cuckoos Nest to badspots of guy;
	add Two crash into the Cuckoos Nest to badspots of girl;

Instead of resolving a Two crash into the Cuckoos Nest:
	now battleground is "void"; [prevents a random fight, as these are replacement random fights]
	say "     While traveling through the woods you decide to see what the cuckoo couple you encountered before is up to. Walking back to the small community of transformed people in one of the less dangerous sections of the forest, what you find seems a little larger than what you remember. There is a new little shack or two and additional hammocks in places that used to be vacant. In the midst of it all is a large crackling campfire, around which two infected individuals sit and chat while toasting some marshmallows for s'mores. One of them is an anthro squirrel, who laughs amusedly as his fox-morph companion bites into his sweet treat and soon has a glob of gooey marshmallow dangling from his lips. A little embarrassed, the fox wipes the goop off his mouth, then smiles as he is handed another fresh marshmallow.";
	say "     You continue on your way to the tent of the cuckoo couple location. Approaching from a different angle than you had previously you see a couple of things that you hadn't seen last time. Behind the tent there appears to be a sizable pile of clothing. ";
	if CuckooWatched is 100: [ignored them]
		say "Based on the variety of sizes and shapes of the garments and the fact that they're piled up just behind the tent, the male cuckoo has to know what his lover is up to. Seems like more than a few of the visitors leave at least part of their clothes behind, very possibly as they're being shooed out by the female cuckoo 'before her mate returns'. Seeing many footprints of an anthro bird's feet that lead behind a nearby bush, you think that there is a high probability for them to be into some interesting sexual play. From the looks of it, cuckolding and voyeurism, as the female bird has fun with other males while her mate watches from a concealed position.";
	else if CuckooWatched is 2: [watched before]
		say "Based on the variety of sizes and shapes the clothes don't appear to belong to the couple but rather to their 'guests'. All of the boxers and briefs are stretched in the front - and knowing the cuckoo lady's preferences this isn't very surprising. Seems like more than a few of the visitors leave at least part of their clothes behind, very possibly as they're being shooed out by the female cuckoo 'before her mate returns'.";
	WaitLineBreak;
	say "     There are also a couple of bras and panties in the pile showing that probably some herms or dick-girls have had their fun with the girl as well. Nearby you see a tree that has been carved into numerous times. Examining the tree closer you see some symbols with tally marks underneath them. Your eyes are drawn to a symbol of a circle with curved horns and one tally mark underneath. Remembering what happened last time, you surmise that the symbol represents the white bull that fucked the cuckooess [if CuckooWatched is 100]while her mate was away[else]while you and the male watched[end if]. Following this logic it is easy to deduce a couple more of the symbols. The dog bone symbol with seven tallies shows that the woman has been 'knotty' with more than a couple of canines, a feather symbol with five marks shows she has had some birdy fun with more than just her husband, a horseshoe marking with three rows of five tally marks indicates that she really likes to go for some 'pony rides'.";
	say "     As you got quite close to the tent during your investigation of the clothes pile and tree, you can hear the lovebirds inside the tent, saying sweet nothings into each others ears. The two campfire cooks notice which tree you're nearby and snicker. 'I'll bet two marshmallows the next one's a dog,' murmurs the squirrel. 'No way, it's gonna be a horse, she's ridden more equines than the Pony Express,' snarks the messy vulpine. It seems that cuckoo's dalliances aren't a well kept secret for this community. You then hear the flap of the tent move as Izzy the female cuckoo steps out of the tent. She tells her partner Gray that she is going off to 'hunt.' Gray grins and jokingly states she should bring back an 8 point buck. The slutty huntress winks one of her eyes and says happily, 'You've always got the best ideas.' Then the amorous woman struts down the trail.";
	WaitLineBreak;
	say "     Gray starts cleaning the inside of the tent, sweeping out any dirt or trash. He fluffs up a couple of pillows that lay inside. Content with the condition of the interior, the male sits inside the tent and takes a couple of deep breaths. He closes his eyes and start to murmur something. After listening a little harder you discover he is imagining Izzy getting fucked by someone with a massive cock. Still with his eyes closed, the imaginative male starts to play with his cock. His quickly erect penis is a little on the small size at five inches and avian in shape, which means large at the base and tapering off towards the tip. Rubbing the top of the pointed tip the bird says a little louder, 'Take that bull's dick... get a cream-pie as white as his coat...'";
	say "     It seems like the scene playing in his memory is based on the event that occurred the last time you were here. A wild idea crosses your mind as you watch the small cocked cuckoo. Wouldn't it be fun to step into the tent yourself and start fooling around with the boy, making Izzy the voyeur for once.";
	say "     [bold type]Do you want to head into the tent and switch things up for the couple?[roman type][line break]";
	LineBreak;
	say "     ([link]Y[as]y[end link]) - Head inside.";
	say "     ([link]N[as]n[end link]) - Don't go inside.";
	if player consents:
		say "     Quietly you head into the tent, making sure to leave the entry way open so people can see what goes on inside. Gray is still lost in the fantasy pumping his below average-sized cock. Watching the bird up close you can see a certain charm to his appearance. He has a sleek and slender frame with a build that is in pretty decent shape. The cuckoo has a slightly masculine smell like sandalwood. Fortune favors the bold, so you lick your lips move your lean down to his crotch. Softly you start to lick the tapered tip of his avian cock.";
		say "     Still lost in fantasy, the slim male groans and groggily states, 'Now you want to get spit-roasted... babe that's so fucking hot!' It seems like your involvement has made Gray's role in his fantasy more active. Feeling more daring you decide to start to sucking on his dick at an unhurried pace, gradually going further down the shaft with each bob of your head. After a few long moments of this drawn-out oral you reach the much thicker base, by now the entranced avian has stroking using his claw-like hands and is now caressing his body.";
		WaitLineBreak;
		say "     Deciding the daydreamer needs to awaken from his state you decide to quicken the pace of the fellatio. The anthro male's face scrunches up and he opens his eyes. The sight of [if CuckooWatched > 99]a stranger[else]someone he barely knows[end if] sucking him off gets him out of his stupor and he opens his beak to say something. You decide to go on the offensive, smiling around his hard pole and swirling your tongue over its sensitive length. And it works - what comes out of his beak is simply a long contented moan. Then he chuckles and says, 'It's not every day that a person snaps out of an erotic fantasy to see a sexy [if player is female]babe[else]stud[end if] going down on them!'";
		say "     You can feel the claws on his hands tenderly touching the top and back of your head, encouraging you to keep going. Given the green light by Gray, you start going full steam back and forth. Deep-throating his shaft is pretty easy [if scalevalue of player < 3]despite your smaller frame [end if]- good thing he's not all that hung. Soon, you hear some noise from outside the tent - a quick glance after pulling off the bird's cock reveals that other inhabitants of the little settlement are greeting someone who came down the trail through the forest. Among the voices to be heard is a high-pitched feminine voice, as well as a deep baritone. Sounds like Izzy and whatever type of 'prey' she was able to attract.";
		WaitLineBreak;
		say "     With a grin on your face, you basically 'inhale' Gray's cock, taking it all down to the base in one go that draws a loud moan from the horny bird. The steps and sounds of conversation that had been coming steadily closer towards the tent you're in until that moment stop suddenly. You can't make out what's being said next, not above the moans and slurps your oral service is creating, but a couple of seconds later there is a rustling noise just outside. The source of that no doubt are the bushes next to the tent. Then murmuring starts up, and you hear the female bird's companion say, 'I thought you said your tent would be empty.' She replies, 'I thought it would be... now hush. I wanna see what's going on.'";
		say "     Gray's eyes which had been focused on you dart to the side, looking at the fabric of the tent, then towards the entrance. A grin spreads across his face as he starts to push you down on his prick, even a little forcefully as he grinds the plump base of his shaft against your lips and holds you there. The anthro avian's cock throbs against your tongue, indicating that something is making his arousal spike hard. You'd bet your whole gear that Gray's mate is now watching the two of you go at it!";
		WaitLineBreak;
		say "     The cuckoo is a bit overenthusiastic about in face-fucking right now, so you actually start to gag for a second or two before he pushes you back off the shaft. Though that wasn't about concern for you either - while you're gasping for breath, he shouts, 'I'm coming!' and starts to shoot long strings of sticky cum on your face. After standing over you and riding out his orgasm, aiming his shaft to really cream you good, the bird takes a moment to catch his breath. Then the exhibitionistic male takes a step back and walks through the tent with his half-hard dick openly dangling between his legs. And not only that, he even steps outside in his nakedness - just a few steps to snatch up a towel from a laundry line, but still.";
		say "     Returning a few seconds later, Gray tosses you the towel to wipe away the cum. While you are cleaning your face, Izzy comes into the tent too and says in a mock-offended voice, 'I can't believe I've caught you in bed with some home-wrecker! And you're strutting around as if to show off! What kind of crazy person hooks up with other people while in a committed relationship?' Gray gives a flippant shrug with his shoulders - which earns him a smile and hug from his girlfriend, followed by a steamy kiss.";
		WaitLineBreak;
		say "     'I can't believe how hot it was watching you get blown. I totally get why you enjoy watching from that spot. It's a great feeling,' Izzy gushes at Gray and the two share a happy smile. Then the male bird asks in an impish tone, 'Better than getting stuffed by that draft horse?' Emphatically shaking her head left and right, Izzy replies, 'Against THAT stud, even graduating college with a 4.0 would be inferior. You saw how big he was!' Their banter is interrupted by someone clearing his throat right outside the tent entrance. Looking over there, you see a large stag with an impressive tent-pole in his pants.";
		say "     'Soooo... are we gonna do anything, or is this lovey dovey time?' the stag asks with a grin, adjusting his bulge suggestively. Gray whispers in Izzy's ear and after giving him a kiss, she says to the buck, 'It seems that the fellatio provided my boy with a new idea of fun - you get to ram my pussy, while Gray gets round two on some oral action.' All three smile and start to get into the right positions. Meanwhile, you drop the towel and quietly leave, happy to have inspired new ways for the couple to have fun together.";
		WaitLineBreak;
		say "     After stepping out of the entrance of the tent, you start to walk back the way you came. The campfire tenders are eyeing you with great interest.[if bodyname of player is listed in infections of Caninelist] The squirrel says boldly, 'Ha! I knew it was gonna be some doggy this time.' The fox rolls his eyes and says, 'We didn't say if it would be for the man or woman, but what the hell I'll throw you a bone.'[else if bodyname of player is listed in infections of Equinelist] The fox says matter of factly, 'Told you it be a horse.' Grumbling, the squirrel hands two marshmallows over and says, 'Yeah yeah... whatever.'[else] Both infected shrug and state that it is a draw and wonder which symbol the couple is going to carve as your tally mark.[end if]";
		Now CuckooWatched is 3;
	else:
		say "     Deciding against the idea you start to turn around walk back down the path. You come across Izzy walking with a studly male deer. It seems neither of the campfire cooks are going to win today's bet.";
		Now CuckooWatched is 99;
	Now Two Crash into the Cuckoos Nest is resolved;
	now Avian Tent is not resolved;

Avian Tent is a situation. Avian Tent is resolved.
The sarea of Avian Tent is "Forest";

when play begins:
	add Avian Tent to badspots of guy;
	add Avian Tent to badspots of girl;

Instead of resolving a Avian Tent:
	say "     As you are making your way through the forest you come across Izzy, the female member of the cuckoo couple you've met before. She is strolling down a path not too far from your own, heading deeper into the woods away from you. Based on the clothing she is wearing and only carrying a metal bar for self-defense it seems like she's on the 'hunt' for something besides supplies. The sexy avian wears a low cut white blouse which has been tied off to show her slender waist, combined with a skimpy tartan miniskirt that hardly conceals anything. As she bends down to get past a low-hanging branch you see that she doesn't have any panties on either.";
	say "     Curious about whom the adventurous avian will bring back to her tent this time, you do stealthily tail her for a while, soon seeing her approach the wreckage of an air force jet. There are deep scratches all along the fuselage - seems like this thing had a run-in with a wyvern or something similar. Nearby to the wreck is a makeshift shelter made using a parachute as a canopy. Under that sits a large anthro osprey, busy sharpening his combat knife by using a whetstone. This must have been the pilot. The fabric on his air-force jumpsuit is visibly strained by his enlarged form. Eyeing this fine example of masculinity, the cuckooess straightens her feathers for a moment and chuckles softly.";
	WaitLineBreak;
	say "     Swaying her hips as she walks up to the transformed pilot, Izzy says in a flirtatious tone 'Hey there fly-boy, welcome to the neighborhood.' He grasps his knife tightly for a second, ready to defend himself, but soon relents as it becomes obvious that his visitor doesn't seem intent on forcing herself on him. Happy to have some non-hostile contact in the city, the man begins to chat with the slutty woman. After a while of sharing tales about who they are and what is going on, Izzy offers, 'I can show you the community I live in. We're always ready to welcome new people that are still alright in the head, you know. And a person with your skills and physique would be greatly appreciated...' She emphasizes this point by stroking his bicep. The bird of prey shrugs and says, 'Better than sitting around here and watching the wreck rust, I guess. So sure, lead on.' A happy grin on her face, the cuckooess takes his hand and leads him back towards the camp.";
	say "     Coming back down the same trail you followed her on, the two of them spot you before you can react - resulting in a friendly nod by Izzy as she leads her newfound piece of man-candy past you a moment later. She doesn't seem surprised to see you... could it be that the avian spotted you before and enjoyed being observed on her 'hunt?'. No matter which, as you go on to walk after them in a little distance, the would-be seductress intentionally bends over at certain narrow parts of the trail so that the osprey's gaze quickly gets focused on her shapely booty and the absence of underwear on her person. It doesn't take long before a noticeable bulge in the crotch area can be seen on the pilot's jumpsuit.";
	WaitLineBreak;
	say "     Upon reaching the campground a couple of the infected walk up and begin to greet the new person. With more and more of the camp's inhabitants checking out the newcomer, it becomes obvious to you that Gray, the cuckooess's partner, isn't among the crowd. The osprey pilot talks to a couple of people, but eventually Izzy gets a bit impatient, leaning in against him and guiding one of his hands to caresses her ass. Getting the hint about what is going to happen next, the other inhabitants of the community soon do go back to what they had been doing previously - not without exchanging some grins and chuckles of course. Once done showing her guest the amenities of the small community, the pair arrive at the final destination of Izzy's tent.";
	say "     The promiscuous cuckoo asks, 'So what do you think of our humble little community Ace? Any interest in moving in?' The hunky osprey smiles and responds, 'It looks pretty good... but I might need a little more convincing.' The sultry avian femme leans in close to him and whispers 'Let me show you just how convincing I can be.' Then she begins to eagerly make out with the handsome raptor. By this point the bulge in the male's jumpsuit is at full mast. Breaking off from the oral fun a moment later, Izzy grabs the man's hand and pulls open the entrance of the tent. Inside, you can see Gray kneeling on the floor in one corner. He has been blindfolded and has his arms are tied behind his back.";
	WaitLineBreak;
	say "     Stripping off the pilot's jumpsuit, the adulterous lady guides the anthro osprey to lie on a bedroll, and then starts to kiss down his toned abs and the tip of his 10 inch long avian cock. She then sits on the raptor's lap and starts tease Gray by softly stroking her foot-talons across his face. The blindfolded male quietly moans. Grinning Izzy asks, 'You don't mind if we have some company? I made a bet with my partner here that if he doesn't climax before I cum I'll find a sexy woman to have a threesome.' With a mild chuckle the bird of prey says, 'This ain't my first time at this type of rodeo, you would be surprised just how many couples have thing for a man in uniform. I'm gonna fuck you so hard it's going to be impossible for him to win the bet.";
	say "     [bold type]Do you want to watch while the osprey hooks up with the cuckooess?[roman type][line break]";
	LineBreak;
	say "     ([link]Y[as]y[end link]) - Watch.";
	say "     ([link]N[as]n[end link]) - Don't watch.";
	if player consents:
		say "     You're very interested in seeing how this will play out, so you hide behind a bush that has been quite a popular hiding spot based on the variety of foot or paw-prints surrounding it. Meanwhile, the burly osprey's hands start to cup the sultry femme's perky c cup breasts, and he proclaims in a confident air, 'Girls like you always turn to putty in a real man's grasp.' Then he wraps one hand around her neck while the other rubs the clit, saying in her ear-hole, 'Admit it, a needy slut like you wants to be dominated.' Shuddering, the female nods and breathlessly utters, 'Yes. I want it... no, I need it!' The dominant raptor grips Izzy's neck tighter and growls, 'You forgot to say sir.' Gasping from the pain and pleasure, the woman says between short breaths, 'Sorry sir! Please forgive me sir!' Smirking, the dom yields his grip and orders the sultry cuckoo to worship his cock.";
		say "     The now-submissive cuckooess hops off his lap and turns around giving you a very good view of her pussy, slick with her juices. Next she starts to lick the tapered tip of the pilot's impressive rod. In between licks the subby birdy teasingly says, 'How are you able to fit inside a cockpit when you're packing something like this sir? Having to giant joystick to deal with is probably why you crashed.' Grabbing the back of her head the sea hawk responds, 'You talk too much,' and pushes her head forward so that the mouthy femme can take his dick all the way to the enlarged base. I know a better use for that mouth of yours,' the forceful osprey says next. With the tapered tip of the pilot's phallus reaching the back of her throat, the woman can only manage to utter a very garbled, 'Yes sir.'";
		WaitLineBreak;
		say "     Izzy's eyes start to widen as she is kept deep-throating the shaft for a couple seconds longer than is comfortable. Releasing his grip, the osprey allows the cuckooess's beak to get off his cock and lies down on his back and states 'Now how about you ride me in reverse cowgirl position.' Taking a couple of seconds to catch her breath the exhausted woman nods and gets ready to move into place. Guiding the thick raptors rod between her nether lips the cuckoess grunts as it slides into her Meanwhile, having had to listen to his girlfriend being taken by someone he hasn't even seen yet, Gray's slightly undersized dick starts to leak precum. Noticing this the sea hawk give gives a sudden and forceful thrust of his hips causing the adulterous femme to sharply cry out.";
		say "     Oozing with bravado, the raptor says, 'Bet you've never made her cry out like that before have you boy?' Meekly, the diminutive cuckoo male shakes his head and says, 'No sir...' With a wry smile, the fighter jet pilot caresses the curves of the stuffed woman's curvaceous booty then says, 'Now I want you to use your hips to ride my dick, I'm not gonna do any thrusting, if you want to cum you have to earn it.' Turning her head to look at the face of the commanding male the woman winks one eye and energetically replies, 'Sir yes sir!' She then places her arms on the burly ospreys broad shoulders and starts to thrust her hips up and down to ride the large shaft. Picking up the pace she goes faster and fast coming ever closer to a climax.";
		WaitLineBreak;
		say "     By this point Izzy's tied-up lover in the corner is writhing on the ground, unable to touch himself and aching for release. Looking at this sight the big dicked male utters in a commanding tone, 'Get over here boy, I want the girl to give you a footjob.' Following the sound of his girlfriend's moaning the tied-up male moves close to the couple. Wrapping her talons along the small shaft the busy woman teasingly says, 'How does it feel love, to get the side dish while this stud is getting the main course. He's filling me up sooo well.' Getting a footjob, the male cuckoo squirms and trembles, trying to suppress his urge to cum - but he is just too turned on by the whole situation, as is she. Both of the cuckoos are on the very edge of climaxing, and a heartbeat later, the two cum with the female being the first one.";
		say "     The bird of prey's shaft gets covered in a deluge of squirted femcum while a couple of drops of the Gray's cuckoo's spunk lands on Izzy's right butt cheek and the osprey's heavy orbs. 'Clean up that mess boy!' barks the raptor, he then grabs the spent male's neck using one his foot talons. With his face pulled close to the other two's genitals, Gray starts to use his tongue to lick up the ejaculate, being especially thorough with the large balls. This new sensation causes the pilot to tense up and unload a massive amount of jizz inside Izzy.";
		WaitLineBreak;
		say "     It takes a few minutes for the three to catch their breath and recover. Sliding off the spent giant shaft; the sated cuckooess gets off her osprey partner's lap and start to untie the ropes and blindfold on her lover. Next she gives him a long passionate kiss using plenty of tongue. Beaming with joy she states, 'Oh my god Baby, that was so fucking hot! I loved every second of that! Are you sure you're okay with it sweetie?' Her partner eagerly nods. Shifting her head, she then asks the spent dom, 'Is that convincing enough for you to stay Ace?' Grinning, the osprey says, 'I'll admit you do make a very convincing case.' Sitting up, he pats the other male on the shoulder and says, 'Sorry if things got a little too intense...'";
		say "     Interrupting him, Gray utters 'No! No! It was totally fine man.' Izzy then asks, 'My eyes were closed did you see who came first?' The osprey shakes his head and replies, 'I didn't have a good view of the situation. But I think your partner came before you did.' Accidentally rustling the bushes when you shift your position, you see the wheels inside the woman's mind work as she looks over in your direction. Suddenly her eyes light up and she starts to smile. Walking over to your locations she drags you out of the bush and asks 'So [if player is female]ma'am[else]buddy[end if] did you happen to see which one of us came first while you were being a peeping tom?' Bashfully you reply it was her. Gray smiles while the osprey gives him a thumbs up. You start to walk away while they are wrapped up in discussion and offering to help the osprey move. Based on the tone you are hearing the start of a new unusual friendship.";
		Now CuckooWatched is 6; [watched the couple with the osprey partner. Gray won bet]
	else:
		say "     Deciding you don't want to watch this couple's unusual proclivities you walk away from the settlement, hearing the sound of the female's moans grow ever distant.";
		Now CuckooWatched is 7; [did not watch the couple. Izzy won ]
	now Avian Tent is resolved;

Sandwich Shop is a situation.
The sarea of Sandwich Shop is "Forest".

Instead of resolving a Sandwich Shop:
	now battleground is "void"; [prevents a random fight, as these are replacement random fights]
	say	"     While walking through the woods you cross the ruins of a small mini-mall. Trees seem to have sprouted throughout many of the stores and one of the light-posts in front of the building has fallen on a sedan, with the wreck now covered in heavily grown foliage on the outside and inside of the car. Another light-post is leaning sharply and on the verge of falling over. There are three stores within the building complex - the closest by is a liquor store, shards of glass from broken bottles cover its floor. It appears that anything drinkable is gone, all the shelves long looted.";
	say "     The next closest store is a mattress store. Its door has a slogan stating 'Sleep... with us!' (the word 'better' is scratched off). All of the beds inside have been completely ruined, their mattresses covered in claw-marks and cum-stains. You see a couple of broken bottles on the floor too - seems like the looters must have decided to start a party in there. Last is a sandwich shop that's part of a small corporate chain. Its inside is a mess with all the tables tipped over, onion peels and shredded lettuce littering the floor and blots of crusted marinara sauce splattered over the walls and menu board.";
	WaitLineBreak;
	say "     Then suddenly, you hear a wolf howl loudly - not far off at all. He is answered by another, and another, and another. You can't be exactly sure, as the howls overlap into a joined call, but there seem to be about 20 members in that pack! No chance to beat that many of them if they surround you out in the open, so you decide to hide inside the sandwich shop. Hastily rushing inside and doing your best not to make noise by stepping on broken glass or slipping on wasted food scraps, you hide behind an overturned table.";
	say "     You're keeping your head down, but outside the store you can hear the barks and yelps of two wolves. While keeping as absolutely still and quiet as you can be, you hear one wolf sniffing near the doorway. Uh-oh, has he got your scent!? You ready yourself to jump up and fight, but then... fate intervenes. The precariously leaning light-post outside suddenly falls, crashing to the ground and sending the two canines running with a whimper. Once their barks are far enough away that they can be barely heard, you exit your hiding spot.";
	WaitLineBreak;
	say "     You look around the area and sense no current danger. Even though the restaurant is ruined, some small instinctual part of you feels like there has to be some food around here that hasn't been ruined or purloined. The metal support beams inside the store creak and groan enough to give you some pause to worry about being trapped if the building collapses.";
	say "     [bold type]What do you want to do now?[roman type][line break]";
	LineBreak;
	say "     ([link]Y[as]y[end link]) - Scavenge inside the store.";
	say "     ([link]N[as]n[end link]) - Leave the store.";
	if player consents:
		say "     You walk into the back area of the store. The stainless steel sink basin used for washing dishes has been bent and pushed aside by a four foot tall sapling that is piercing the floorboards. Interestingly, only the words '12 inches that'll make your mouth water' and 'try our savory... balls' remain readable on the menu board right beside the little tree, with everything else scratched beyond recognition - what an odd coincidence. Or maybe not - you make out some scraps of paint on the gently swaying branches. Wait, there's not even any wind in here! It is definitively moving on its own.";
		say "     Who knows who or what that plant might once have been and if it retains some memories of its former self... so you decide to keep your distance as you explore further. All of the refrigerators in the back have already ransacked, their doors standing wide open. Still, you then look inside them one by one just to be sure, and your persistence is rewarded - there is a small brown paper bag behind a couple of shredded boxes in one of them! You look inside and find a brownie that has been wrapped in plastic with a small note saying, 'Here's a treat for your break, love M'. A small shiver runs down your spine as you imagine what might have happened to the owner of that brownie, or their partner. But hey, waste not want not, so you nevertheless take the food and slide it into your backpack.";
		increase carried of food by 1;
	else:
		say "     Seems a little too risky, with likely no reward, so you exit the store and walk in the opposite direction of where the wolves went.";
	now Sandwich Shop is resolved;

[ BridgetPowellEventVar                                ]
[  0: never met                                        ]
[  1: watched Bridget fuck Powell                      ]
[ 98: didn't help in the fight against the lizards     ]
[ 99: didn't stay to see what Bridget does with Powell ]


Thief's Punishment is a situation.
The sarea of Thief's Punishment is "Forest".
BridgetPowellEventVar is a number that varies. BridgetPowellEventVar is usually 0.

when play begins:
	add Thief's Punishment to badspots of guy;
	add Thief's Punishment to badspots of girl;

instead of resolving Thief's Punishment:
	now battleground is "void"; [prevents a random fight, as these are replacement random fights]
	say "     While walking through the woods you come across a small campsite that is next to a collapsed gym. A blue tent has been set up next to it, in front of which a small campfire merrily burns, shining firelight on a workout bench and couple of barbells that must have been salvaged from the ruin. Sitting on the ground right next to the fire is a can of beans and a six-pack of water bottles. While you're still trying to decide what to do now, you hear the sound of a zipper from the tent, then its entrance is pulled open from the inside and a burly anthro tigress comes out.";
	say "     To say she does a bit of weightlifting would be the understatement of the century - her seven foot tall body is covered in large bulging muscles, washboard abs, and what must be twenty inch biceps when she flexes. She's wearing a black sports bra to cover her D cup breasts, and tight black Lycra shorts whose fabric seems to be strained to their limit by her massive thighs and toned buttocks. The tigress is quick to notice your presence so close to her camp and she smiles, then waves at you, calling out to come over and share her fire. She seems sane enough and fairly friendly so you walk closer and begin to chat with her.";
	WaitLineBreak;
	say "     In the short conversation that follows, you learn some things about the bulked-up tigress. The cheerful amazonian is called Bridget and tells you of how she used to work as a trainer for the gym. Then she brags about how the transformation made her even more ripped and how she was able to beat up a gang of aggressive infected with just her bare hands. Well, paws really - anthro ones, but still equipped with impressive claws. She flexes one of her biceps and says, 'Training certainly paid off for me!' Yet while she is busy showing of her muscles for you, a slender anthro mouse wearing a black hoodie starts to sneak towards the camp.";
	say "     His eyes are fixated upon the package of water bottles. As soon as he notices that you spotted him, the rodent lunges for the box and snatches it to his chest. Bridget turns her head and sees the terrified thief running away with the case of water. Letting out a ferocious roar, the enraged tigress charges after the would-be plunderer. Closing the gap quickly, the hard-bodied feline tackles the crook and puts him in a choke-hold. It is clear she is pissed off from the way she snarls, 'Tap out if you give up!' In a flash the mouse is quickly tapping her thighs proclaiming in short breaths 'I give! I give!' The wrathful amazonian relents after a moment and relaxes her arm from around his throat.";
	WaitLineBreak;
	say	"     After giving the would-be bandit a chance to catch his breath, the tigress grabs him by the scruff of his hood and growls through gritted fangs, 'You better give me one good reason why a wimp like you thought stealing from someone like me was a good idea!' Nervously the failed water-snatcher replies, 'I'm sorry! Please forgive me! A group of mutants discovered my hiding spot and robbed me of all my supplies. I... I haven't had anything to drink in two days. When I saw that crate of water bottles I just couldn't help myself. Please don't eat me!'";
	say "     The cat-like weightlifter laughs and says teasingly, 'I could eat a shrimp like you for a post workout snack. But you look a little too lean to taste any good. You'll have to be punished another way. What's your name, anyways? Shrimp seems accurate for how you look but I doubt your momma named you that.' Squirming in her grasp, the mouse stutters, 'My name i... is... ppp... Powell.' The tigress bodybuilder listens to him with a toothy grin, but does little to acknowledge him, instead looking over towards you. 'Feel free to watch if you want, I'm going to make mousy here work for his atonement.'";
	WaitLineBreak;
	say "     [bold type]It's only fair that thieves get punished, and it doesn't look she plans on doing any real harm to him...[roman type][line break]";
	LineBreak;
	say "     ([link]Y[as]y[end link]) - Watch the thief get punished.";
	say "     ([link]N[as]n[end link]) - Walk away.";
	if player consents:
		say "     You say you will watch, if only to make sure he doesn't get hurt too badly. After a cheerful nod to you, Bridget whispers in her captive's ear, 'Don't worry. I won't bite... hard.' The mouse's legs start shaking and a whimper escapes his throat, to which the tigress says, 'Just kidding... Sheesh can't even take a joke. All right sticky fingers - go kneel down by the bench!' Being let go, the diminutive captive glances towards the edge of the forest as if contemplating another (most likely futile) escape attempt, then gulps visibly and walks over to the bench. There he submissively kneels, his gaze lowered to ground level.";
		say "     The massive feline walks after him and begins to peel off her shorts - smiling gleefully as she shows off her booty and her aroused pussy. The captured rodent's eyes dart back and forth between the ground and his captor's genitals. In a coy tone Bridget comments, 'You truly are a thief, even now you're stealing glances at me.' The shocked mouse stutters and repeatedly says sorry - drawing a chuckle from her. The tigress pats his cheek gently and smirks, then says cockily, 'You don't need to feel sorry, I've worked hard to get my ass to look like this. If anything I'd be more offended if you weren't peeking. Speaking of...how about you start making up for your mistake by worshiping my glutes.'";
		WaitLineBreak;
		say "     Meekly the rodent nods and places a shaking hand against Bridget's toned and muscled butt. He the begins to softly rub its soft curves and knead the muscles through her short, soft fur. This massage continues for a short while until the beefed up lady looks noticeably relaxed. Grinning, she sighs, 'Ok, I'll admit you're pretty good with your hands... Now let's see just how good your tongue is.' With that said, she then sits down on the weightlifting bench and spreads her legs. It is obvious just how aroused the over-muscled tiger woman is by the damp juices of her arousal dripping onto the bench.";
		say "     The dominant anthro tiger pulls her rodent captive's snout close to her pussy. Powell almost hyperventilates for a moment from the situation - and position - he finds himself in, then is broken out of that by a somewhat impatient mrowl from Bridget. He then starts to lick around the folds of her nether lips and gently sucks on her clit. The huge tigress lets out a few pleasured pants and pushes his head against her crotch. Growing increasingly more daring the diminutive captive begins eagerly licking inside her, really sticking his tongue deep and wiggling it around.";
		WaitLineBreak;
		say "     Pleased by her little mouse's efforts, the muscular feline lets out a few aroused growls and locks Powell into place between her muscled thighs. Knowing the only way to escape his captor's clutch is to finish what he has started, the slender mouse quickens the pace to bring the buff trainer to climax. After not too much longer, a loud roar echoes through the forest as Bridget orgasms - her thighs firmly pressing the rodent's head stuck in between. After riding out the wave of pleasure, Bridget eventually lowers her legs to the ground, with the repentant thief flopping down to lie lengthwise on the bed - panting to catch his breath and let the sides of his head recover from the squishing.";
		say "     It takes a couple of minutes for both of them to recover. Embarrassed, Powell stands up and says in a hurried fashion, 'I'll be going now. I won't try something like that ever again, I swear. Bye!' But just as he is about to leave the tigress grabs his tail. 'Where do you think you're going, pint size? I didn't say you could just walk off scot free! If you think one little bit of tongue-wagging is enough, think again!' Bridget tells him in a domineering tone. Futilely tugging at his tail, the rodent starts to stammers out some words, but is immediately interrupted by the personal trainer shushing him.";
		say "     With a broad grin on her face, Bridget tells her caught thief, 'As your ongoing punishment, you're going to have to massage me, train with me, and see to my every need. In return I'll make sure you're well fed, protected from that gang of assholes, and a lot more in shape. Sound good?' Perplexed, the small mouse gapes at her for a second, then starts to smile and nods eagerly. Bridget slaps him on the back and says jovially, 'Great! I'll make a gym rat out of ya before you know it.' You can't help but smile about how this situation turned out as you leave, walking along one of the dirt tracks into the forest. Behind you, the two of them start doing some warm-up stretches.";
		now BridgetPowellEventVar is 1; [player knows Powell's fate]
	else:
		say "     With a shrug, you shake your head and walk away.";
		now BridgetPowellEventVar is 99; [player ignored Bridget and Powell]
	now Thief's Punishment is resolved;
	now Thief's Reformation is not resolved;

Thief's Reformation is a situation. Thief's Reformation is resolved.
The sarea of Thief's Reformation is "Forest".

when play begins:
	add Thief's Reformation to badspots of guy;
	add Thief's Reformation to badspots of girl;

instead of resolving Thief's Reformation:
	now battleground is "void"; [prevents a random fight, as these are replacement random fights]
	say "     While walking through the woods, you once again find yourself near the fitness studio ruin and are reminded of the muscled tigress you encountered there earlier. Curious about how she is doing now you decide to head over. Soon stepping out into the little clearing, you see that the campsite is a little different than the first time. A fair bit of rubble from the front of the collapsed gym has been removed, forming a large mound a little off to the side. This now allows a glimpse into the inside of the building - or at least what's left of it, squished between the floor and low-sagging ceiling.";
	say "     Looks like all that is holding the roof up at least a little are the countless smashed exercise machines, bent and broken from the collapse. Parts of broken mirrors still hang up on some of the small portions of the walls that are still upright, with the rest covering the floor in shards and splinters. But not everywhere, at a second glance - there is actually a path into the mess of a ruin which has been swept free of glass and stone shards, weaving around and sometimes through the tangles of broken machines. Must be a tight squeeze to get through in some places. Doesn't look like Bridget would fit.";
	WaitLineBreak;
	say "     Clearly, someone has salvaged several pieces of exercise equipment that were still intact and reachable, moving them out front. Besides the workout bench you saw previously, there is an old red metal exercise bike that seems to be in good condition. A pull-up bar hangs from a sturdy branch on a nearby oak tree and a machine designed to exercise your calves has been pulled to be near by the weigh-lifting bench. Towers of disc-like weights are neatly organized on the ground. More boxes of water lie to the side of the tent, with numerous large containers of protein powder close by too.";
	say "     While you're still inspecting the camp, you start to hear the sound of two individuals jogging down one of the paths leading to the clearing, chatting away happily. ";
	if BridgetPowellEventVar is 99: [player doesn't know their arrangement]
		say "As the two round a bend and come into view, you see it is Bridget the tigress - and also for some reason the mouse who tried to steal her water previously. Whatever the punishment was, it didn't seem too harsh based on the fact that he appears to enjoy his captors company now.";
	else if BridgetPowellEventVar is 1: [player watched Bridget sex up Powell and adopt him]
		say "As the two round the bend and are visible, you see it is Bridget and Powell. Remembering the 'punishment' it seems like the mouse didn't weasel out of the agreement and has been helping her in the salvage operation too. Based on the way the rodent looks at his trainer/captive it seems like he really loves the arrangement.'";
	WaitLineBreak;
	say "     The two joggers see you and walk over give you a warm hello[if BridgetPowellEventVar is 99], including an introduction of the mouse as Powell[end if]. The four and a half foot tall rodent has certainly changed since you saw him last. Instead of the gangly nerdish physique he had previously, there are toned muscles on his frame now. While still being pretty slender, where once his biceps had the consistency of a wet noodle, there are now muscles that make him someone to be reckoned with. Furthermore, it seems like more than just his body has changed. The athlete in training appears to have lost a lost most of his nervous anxiety and apprehension, instead seeming quite calm and confident.";
	say	"     Bridget steps forward and does her best to be a good host, saying, 'Let me go get some drinks for you and Powell, I've got a recipe for a dynamite protein shake.' She grabs two water bottles and a protein powder container then heads inside the tent. You ask the mouse what the two of them have been up to since you last met. Powell explains in an eager tone that Bridget has become his trainer and is very dedicated in making the best out of him. Clearing the rubble, weightlifting, and cardio exercises are all part of an intense training regimen that she set for him. Joyfully the male rodent explains how his feline fitness guru knows how to strike a perfect balance of punishment and reward to keep him well motivated. Judging from the way the bulge of his tight shorts throbbed when he said 'reward', it is fairly obvious that the tigress likes to use sex as a motivational goal.";
	WaitLineBreak;
	say "     You hear liquid being stirred by a metal spoon as Bridget comes back out of her tent after a little while. She hands the two of you shakes and says to you, 'Hope you like my special shake. I know rookie here does.' You look down at the bottle - the liquid seems creamier than your typical protein shake. The newly athletic male gulps his drink down quickly, chugging it with eager swallows. You take a small sip yourself, tasting a rich chocolate flavor similar to a malt. Quite a nice drink in a rich, stomach-filling way that reduces hunger as well as thirst. Curious about the recipe, you ask Bridget what exactly she put in there.";
	say "     The trainer tigress replies matter of factly, 'Oh, it's a mixture of some of the various types of protein powders, clean water of course and several squirts of breast milk.' You look at her incredulously, and Bridget she points at the rodent who is just licking a bit of a brown milk mustache off his upper lip. 'What can I say - sweet little mousy here got it into his head to suck my nipples during a 'training' session we were doing, and before I knew it, he was drinking from me. Surprised the hell out of me to suddenly start leaking, but hey - it feels pretty nice and really works for him. A fair bit of his gains are from the tiger milk!'";
	WaitLineBreak;
	say "     Your awkward conversation is interrupted by the sounds of a rowdy gang of six infected beings strutting out of the forest and into the clearing. They're all lizard-based infected, showing scaly skin and tails on their bodies. A large monitor lizard seems to be the one in charge, stepping forward and calling out, 'Hey look - it's a bitch and a pussy, but I don't know which one is which!' His goons burst into laughter. Continuing his statement he says, 'If you don't want to get hurt hand over all your water and supplies. You know how this goes, don't you mousy boy.' Powell glares at the intruders and replies, 'Go away I don't want to hurt you.' Stepping up besides her companion, Bridget flexes her muscles and growls, 'But I do.' Looking over her shoulder, she says to you in a more civil tone, 'You don't have to stick around if you don't like to. This is our fight, we can handle ourselves.'";
	WaitLineBreak;
	say "     [bold type]No matter what she says, the two of them are outnumbered pretty fiercely. Do you maybe want to stick around and help them fight off the gang of lizards?[roman type][line break]";
	LineBreak;
	say "     ([link]Y[as]y[end link]) - Fight.";
	say "     ([link]N[as]n[end link]) - Walk away.";
	if player consents:
		say "     As you say that you will stand and fight with them, Bridget gives a smile and nod in recognition, then turns her attention to the intruders. Seconds later, the building tension is broken as she lunges at a nearby gila monster with a growl. The fight that explodes in the clearing after that is a rapid affair that you pretty much only remember glimpses from, being in the midst of the chaos and all that. At one point, a gecko charges towards Powell's back - only to have the mouse use his own momentum against him, throwing the surprised reptile over his shoulder to slam into the ground. At the same time, an iguana closes in to take Powell from the flank - but you're there in time to give the opportunist a solid strike that sends him flying.";
		say "     After some more hitting, punching, tries to bite and even a tail-sweep from one of the reptiles, Bridget decides the battle for your team by grabbing two lizards by their necks and knocking their heads together. As the two scaled fighters drop to the ground unconscious, the monitor lizard gang-leader hisses and runs off with little regard to his underlings. His bruised gang-members quickly snatch up their fallen comrades and hurry after their cowardly boss.";
		WaitLineBreak;
		say "     Still breathing hard from the exertion of the fight, the tigress and mouse turn towards you and give their thanks for your help. Then Bridget grabs Powell and gives him a great bear hug saying, 'I'm so proud of you! You used that throw I taught you!' Powell doesn't reply with words - he actually can't as she is squeezing him just a little too tightly to draw breath. Tapping out against her side, the much smaller mouse reminds the muscled tigress to let him go in a somewhat shame-faced manner. After catching his breath, Powell replies, 'Thanks for everything. I couldn't have done this without you.' With a lustful look in her eyes the hard-bodied woman adds a moment later, 'I think you've earned a little bit of a reward.'";
		say "     Bridget peels off her shorts and heads over to the workout bench to lay down on it. Then she spreads her legs and slides a paw-hand down to her crotch, rubbing over her moist pussy lips and pushing them apart a little with her fingers in an open invitation for her mousy companion. The big cat clearly is wet and eager for her trainee's cock. Already a little turned on by feeling the large breasts while getting bear hugged, the mouse removes his own clothes to reveal a human-like cock that is a solid ten inches long. Quite a package for a little guy!";
		WaitLineBreak;
		say "     Without any hesitation Powell plunges his manhood inside the feline and starts fucking her wildly, bracing himself against Bridget's rock hard abs. Bridget growls in lust and fills the clearing with pleased roars as she rocks her hips in tempo with his movements. Their intense mating quickly escalates to the point where both are at the edge of climax - then beyond. With satisfied shouts from both athletes, they come at the same time, with Powell's balls pumping a heavy load into Bridget's womb. Breeding his amazonian mistress, he puts enough cum into her to have it squirt our around his still thrusting shaft before too much longer, drenching the bench's leather padding in their mixed fluids.";
		say "     As the studly mouse sinks forward to lay on Bridget's stretched-out form, his prick still balls-deep in her well-filled pussy, Powell rests his head on her large breasts for a little moment. Deep, contented purring starts to emanate from the depths of the sexy tigress's broad chest and she strokes his back affectionately - then gives a pleased mrowl as her little mouse proceeds to catch her nipple between his lips, suckling more tiger milk directly from the teat. You leave the two to enjoy their intimate moment, idly wondering how long it might take until the rodent has to share the bounty of Bridget's breasts with someone else - or several someones even. Not long would be your guess, if he always cums that much and keeps fucking her...";
		now BridgetPowellEventVar is 2; [helped them in the fight]
	else:
		say "     You decide to play it safe and let the two jocks fight their own battle. Wishing them the best of luck, you quickly dash into the forest on the opposite side of the clearing to lizard gang-members. Behind you, there are sounds of a tough scuffle.";
		now BridgetPowellEventVar is 98; [left them to fight alone]
	now Thief's Reformation is resolved;

Forest Events ends here.
