Anthro Shaft Beast For FS by DragonFlayer begins here.
[ Edit the above line, replace monster name with your monster's name, and your name with the name you'd like credited for the mod. ]

"Adds an Anthro Shaft Beast to Flexible Survivals Sewer Monsters table"
[Description text for this Extension.]

Section 1 - Monster Responses

[ Use To say for overlong behaviours that would make the table difficult to read and understand. Typically needed if there are alot of cock/species/cunt checks. ] 

to say shaft beast attack:
	if cunts of player is greater than 0:
		say "The beast grins at you lustfully as you fall on your rear after the last strike lands on you 'No more games...' said a voice coming from no where, but by the way the creature smiled, it had to be hir.. and unseen force suddently pushes you down to lay on your back and spread your legs wide apart.. your clothes pulled away carefully by the same invisible hands and then shi kneels down, taking your legs and spreading them wider apart with hir large and powerful hands, rubbing the gigantic equipment between your legs and then pressing it against your [cunt size desc of player] sized cunt slit... hir spire throbs hard and adjusts in size to better please you, make it fit tightly and slightly stretch you wider than your current limits.. shi gave no second thoughts and thrusted in to the hilt after the adjustment, making you cry out in bliss as hir spire seems to rub against all the right places, after the initial thrust shi lowered hir face to yours, pressing hir snout against your face.. shi began to lick all around, kissing and suckling over your neck and chest as shi begins to pump hir spire back and forth with such a gentle pace that you couldn't help but relax and enjoy yourself at the hands of the now loving beast.. you swear you heard a song in the distance... but among the bliss this creature gave, it didn't matter... Hir pace increased randomly, but at the perfect moments, as if this monster has been your life long companion and knew all the tricks of your body, shi was making you moan and shake in lust, you were soon suckling on hir tongue all on your own, your arms and legs wrapped and tightly squeezing the beast against you willingly as you moved along with the beast's thrusts in perfect union.. after several blissful moments, your release and the creature's own mixed and joined in a wonderful tide of bliss that made you lose all grasp on reality... You woke up later, with a wide smile and a deep blush, your clothes neatly folded at your side and your body covered from head to toe in the creature's juices... Shi was nowhere, but you felt like you would see hir again... Your belly is quite rounder than before and you feel things moving and tickling inside it.. You hope it's just your imagination or the savage good time you had not so long ago... [line break] [impregchance]";
		sharethebliss;
	otherwise:
		if libido of player is greater than 50:
			say "The beast grins at you lustfully as you fall on your rear after the last strike lands on you 'No more games...' said a voice coming from no where, but by the way the creature smiled, it had to be hir.. and unseen force suddently pushes you down to lay on your back and spread your legs wide apart.. your clothes pulled away carefully by the same invisible hands and then shi kneels down, taking your legs and spreading them wider apart with hir large and powerful hands, rubbing the gigantic equipment between your legs and then pressing it against your pucker.. hir spire throbs hard and then shoots a thick glob of hir pre against your rear, probing in to fill you with it a bit.. you felt weird, tickles spreading in your lower body as shi gave no second thoughts and thrusted in to the hilt with hir gigantic spire, making you cry out in bliss as hir spire seems to rub against all the right places, you were surprised that you could take it all, you were worried that shi would split you in half.. but instead, you were in a world of bliss, there wasn't even a single bit of pain, your stomach being quite large, the shape of the monster's spire showing even the smallest veins, after the initial thrust shi lowered hir face to yours, pressing hir snout against your face.. shi began to lick all around, kissing and suckling over your neck and chest as shi begins to pump hir spire back and forth with such a gentle pace that you couldn't help but relax and enjoy yourself at the hands of the now loving beast.. you swear you heard a song in the distance... but among the bliss this creature gave, it didn't matter... Hir pace increased randomly, but at the perfect moments, as if this monster has been your life long companion and knew all the tricks of your body, shi was making you moan and shake in lust, you were soon suckling on hir tongue all on your own, your arms and legs wrapped and tightly squeezing the beast against you willingly as you moved along with the beast's thrusts in perfect union.. after several blissful moments, your release and the creature's own mixed and joined in a wonderful tide of bliss that made you lose all grasp on reality... You woke up later, with a wide smile and a deep blush, your clothes neatly folded at your side and your body covered from head to toe in the creature's juices... Shi was nowhere, but you felt like you would see hir again... [line break]";
			sharethebliss;
		otherwise:
			say "The beast giggles at your brave attempt to resist, she approaches and smiles widely as you lay on your back, exhausted and pinned down by some unseen force, shi kneels between your legs, spreading them apart and using hir throbbing fingers, shi rubbed and caressed over your belly and chest, your clothes evaporated before your eyes as the bizarre monster explored your body with those thick dripping fingers.. with hir massive prehensile cock tongue and those six tentacles... feeling every part of you, but avoiding your groin as shi explores.. then shi pulls away and smiles.. turning around to reveal hir massive, swollen, drooling cunt slit.. and shi sat down on your face, pushing your whole head inside it, bathing you in hir juices and overwhelming you with the powerful female musk that burned your lungs and drilled into your mind, it was too much for you and eventually you lost your consciousness.... By the time you woke up, the creature was gone, you find yourself covered from head to toe in the creature's female musk, your clothes neatly folded to a side as if they had never desintegrated and ... feeling a bit.. different... [line break]";
			sharethebliss;

to say shaft beast defeat:
	if libido of player is greater than 60:
		if cocks of player is greater than 0:
			say "The creature hisses and lands on hir rear after your last strike, panting and exhausted, shi just lays there, exposing hir features to you submissively.. the powerful scents and the sight proves too much for your own need, the creature smiles as you approach, the skin of hir head grows darker, shi was blushing and shi just spreads hir legs wider for you, undressing and immediatly taking hold of hir legs, shi presents hir massive slit to you.. and then the swollen opening changes.. adjusting.. to become a tight fit for you, you grinned widely at the sight, this creature wanted you to ravage and fuck it mindless alright, In a blink, you were thrusting your spire deep into the willing monster without any inhibitions, pumping roughly and spanking hir rear with your groin every powerful thrust, the beast moaned out for you, every throbbing spire on hir body drooling heavily, as did every nipple, your pace increasing, hir scent driving you mad with lust and at the climax of it all, you released your seed deep within the beast, who roared in pure bliss as hir own body was shaken by blissful orgasm, making a huge mess like no other, your body being covered from head to toe with hir many juices.. once you were done, you pulled out and kissed the creature's horns and face lustfully, shi kissed your neck and let you go.. for some reason, the beast must have allowed you to walk away unchanged, you were certain that they could infect with just a touch.. but it seems they have control over who and when infection happens... You just went on your way, satisfied...[line break]";
			decrease humanity of player by 5;
		otherwise:
			if cunts of player is greater than 0:
				say "The creature hisses and lands on hir rear after your last strike, panting and exhausted, shi just lays there, exposing hir features to you submissively.. the powerful scents and the sight proves too much for your own need, the creature smiles as you approach, the skin of hir head grows darker, shi was blushing and shi just spreads hir legs wider for you, undressing and moving over the large pillar of flesh between hir legs, you prepared to slip and slide along the gigantic spire, it throbbed hard and fired juices against your slit and thighs, the mess spreading over your crotch.. you don't mind a bit as you just lower yourself and gasp out loudly once your female lips kiss the tip of that large spire.. and you stretch around it as if made of rubber, while still feeling very tight against it.. you moan out louder as you lower more of yourself along that huge rod.. sliding smoothly without effort, it even seems to grow bigger inside you, before you noticed how much you had taken, your cunt was kissing the beast's crotch and the shape of it's massive rod could be seen on your belly with every detail, you panted and moaned lustfully as the creature took hold of your hips and together you began to hump and bounce against each other in the best ride you have had in a while, the beast was not an amateur, it knew where and when to touch, as if shi had a map of your body, shi made you moan like no one else had before, by the time you both were too engulfed in your own pleasure, your body then shakes in the bliss of one of the most powerful orgasms in your life, the creature doesn't hold any longer, blasting your insides with buckets of it's seed.. making your belly swell large and round quickly.. the pressure enough to help you pull away from the shooting spire, the creature roared and painted your body with hir seeds.. your legs shake as you fall against the creature, you smiled widely.. approaching hir face and then you kissed the creature's horns and face lustfully, shi kissed your neck and let you go.. for some reason, the beast must have allowed you to walk away unchanged, you were certain that they could infect with just a touch.. but it seems they have control over who and when infection happens... You just went on your way, satisfied and with a large, full, sloshing belly that sometimes wiggled oddly...[line break][impregchance]";
				decrease humanity of player by 5;
	otherwise:
		say "The creature hissses and steps away from you after your last strike, you felt a strong headache, closing your eyes, you covered your ears as if a hundred harpies were yelling at you.. when the horrible screech was gone, you opened your eyes and the beast was gone, escaping while you were stunned.[line break]";
	
Section 2 - Monster Insertion

Table of random critters (continued)
name	attack	defeated	victory	desc	face	body	skin	tail	cock	face change	body change	skin change	ass change	cock change	str	dex	sta	per	int	cha	sex	hp	lev	wdam	area	cocks	cock length	cock width	breasts	breast size	male breast size	cunts	cunt length	cunt width	libido	loot	lootchance
--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--	--

[ Adds a blank row to the table, this is immediately filled ;) ]
When Play begins:
	Choose a blank row from Table of random critters;
	now name entry is "Anthro Shaft Beast"; [Name of your new Monster]
	now attack entry is "[one of]You feel a powerful kick hit your stomach, but shi didn't move, the monster is just standing there, smiling ominously[or]A strong uppercut was delivered to your chin, or so you think, the unmoving creature just grins at you[or]Hir heavy tail lashes at you, forcing you to land on your rear, shi giggles as you recover from the impact[or]Shi opens hir maw widely, hir obscene cock tongue aiming at you and shooting straight at your face with pressure and force of a fire hose[or]A Pair of the monster's rear tendrils swing at you and strike your chest like twin whips[at random][line break]"; [Text used when the monster makes an Attack]
	now defeated entry is "[shaft beast defeat]"; [ Text or say command used when Monster is defeated.]
	now victory entry is  "[shaft beast attack]"; [ Text used when monster wins, can be directly entered like combat text or description. or if more complex it can be linked to a 'To Say' block as the demonstration text shows.] 
	now desc entry is "You see someone approach, a fellow survivor? in a place like this? you were already filling with joy as you saw it was a normal human [one of]male[or]female[at random] completely nude. However, your joy doesn't last long as the fellow survivor grins at you and an odd feeling invades you, one of lust and fear, along with other alien sensations you had never felt before, when you snapped out of it, there is a powerful musk in the air that filled your lungs and immediatly made your body tingle with arousal, you no longer saw a survivor, but a monster that took a few minutes to understand, the strange, bizarre creature chuckled and posed for you, showing hir obscene and exaggerated features. Before you is an abomination of Purple Flesh, standing on large feet with 5 throbbing cocks instead of toes, the same could be said of hir hands, the Creature had an impressive breeding tool standing proud at 3 feet, with several ridges and a barbed tip, along the underside of said cock, hang 8 golf ball sized [apostrophe]tits[apostrophe] that drip eagerly with a thick almost cum-like white goo that made you wonder if that was actually milk, hanging heavily under the massive medieval torture device is a ball sack that you swear must be packing 4 watermelon sized testicles, her chest and belly were swollen with six G cup sized breasts, each with an orange sized nipple, the monster's neck and the base of every breast had rings of large round nubs that you could only recognize as clitorises the size of a grape, the breasts only had one ring, but hir neck had 4 evenly spread along it. Hir head was also alarming, a combination of a pointy cock and the snout of a dragon. There were no eyes, nose or ears... Just the wide maw of the creature over the smooth surface of a cock-like head with a pair of long cock shaped [apostrophe]horns[apostrophe] that dripped and spurted constantly with hir musk. Behind her you see 6 tentacles with pointy cock heads at the tips, thicker than a baseball and 5 feet long each, hir tail also is an obscene show, thick as one as hir legs and heavy, the underside covered from base to the large, fat cocktip at the end with rows of heavy dripping tits, you couldn't bear to see more, but you knew that behind that gigantic testicles there must be a massive cunt, swollen and dripping, the female musk shi spread around, along witht he male one were drilling into your mind. This creature must certainly be draconian in nature, or was, all male genitalia on hir body is generally shaped after dragon genitals. The highly sexual creature pulsed and throbbed from everywhere, dripping and shining with a thick layer of hir own juices.... Shi approaches quickly, ready to give you a rather blissful fate.[line break] ";[ Description of the creature when you encounter it.]
	now face entry is "mix of cock and dragon head, your head was smooth and faceless, half of it shaped like a dragon cock, but the front had more snout-like proportions, you still had lips and the insides of your maw and throat feel a lot like female genitalia, your [apostrophe]fangs[apostrophe] are a bunch of clitoris actually, just brushing your massive 2 feet long prehensile tentacle-like cocktongue around the insides make you moan sluttily and make a blissful";[ Face description, format as the text "Your have a (your text) face."] 
	now body entry is "a blissful symphony, it pulses and throbs constantly at any stimulation, there were six cunts along the sides of your spine arranged in parallel like the breasts in front of you, each wide cunt drooling heavily as your six thick cock tentacles push and wiggle out from each cunt at 5 feet from base to tip and thicker than a baseball, highly prehensile and moving on their own as if they had minds of their own, your hands and feet were quite large, each finger and toe were replaced with prehensile foot-long cocks, your belly tingles constantly, you feel things moving inside, living things.";[ Body Description, format as the text "Your Body is (your text)"] 
	now skin entry is "purple, veiny and slick cock-like";[ skin Description, format as the text "You have (your text) skin"] 
	now tail entry is "Your tail is heavy and thick as one of your legs, slightly longer than one as well, the tip is a large swollen pointy cock head which is almost the size of your own penile head, the underside of the tail is covered with rows of breasts from it's base to the glans of the cock tip, the breasts being larger at the base and smaller around the tip.";[ Tail description, write a whole Sentence or leave blank. ] 
	now cock entry is "draconian shaped cock tip, as well as 8 small breasts along it's underside, proportional to the size of your tool, your manhood is also ridged along the sides and barbed all over the glans and edges, quite an interesting";[ Cock Description, format as you have a 'size' (your text) cock] 
	now face change entry is "it pops and swells, pushing forward, your eyes close and cease to exist, along with your nose and ears, all facial features gone except for your lips which spread wider, your face pushing into a draconian snout, while the back of your head takes a penile approach with small barbs around the edges, a pair of foot-long cock shaped horns grow at the back of your head, each dripping heavily with male musk, just as your lips drooled with female juices, your tongue swells and pushes out like a powerful tendril, 2 feet long and thick as a golfball, drooling from the now swollen cock head at the tip, your neck swells and pulses as 4 rings of round bumps swell evenly along it, each bump taking the shape of grape sized clitorises.[line break]"; [ face change text. format as "Your face feels funny as (your text)" ]
	now body change entry is "it swells and pulse all over, moans escaping your lips as you rub your body in corrupted lust, your hands and feet swelling large, each finger and toe extending, pulsing and then growing into foot-long sized cocks, six cunts swell and split open along your spine, your back dripping as they drooled heavily and then spread wide open to allow six 5 feet long tentacles to slide out and wiggle around out of control, each thick as a baseball.[line break]"; [ body change text. format as "Your body feels funny as (your text)" ]
	now skin change entry is "it tingles and pulses as purple shades spread all over it, veins showing here and there and then you feel unbearable heat spread all over, your body releasing a thick layer of musky sweat that coats you from head to toe, making your skin glisten and drip.[line break]"; [ skin change text. format as "Your skin feels funny as (your text)" ]
	now ass change entry is "it trembles and tickles, as you grow a massive cock tail and it curls up proudly, flopping down shortly after with the weight of the many rows of breasts spreading over it's underside, the cocktip swelling till it almost matches the size of your head and it's slit drools heavily immediatly.[line break]"; [ ass/tail change text. format as "Your ass feels funny as (your text)" ]
	now cock change entry is "it swells and throbs, the pulse made change spread from base to tip, first the ridges along the sides, followed by 8 small dripping tits swelling along it's underside, then the tip becomes point and drools heavily, barbs spreading over the glans and edges.[line break]"; [ cock change text. format as "Your cock feels funny as (your text)" ]
	now str entry is 20;
	now dex entry is 12;
	now sta entry is 19;					
	now per entry is 22;
	now int entry is 32;
	now cha entry is 10;
	now sex entry is "Both"; 	[ Defines which sex the infection will try and make you. current options are 'Male' 'Female' 'Both']
	now hp entry is 60;			[ How many HP has the monster got? ]
	now lev entry is 8;			[ Level of the Monster, you get this much hp if you win, or this much hp halved if you loose ] 
	now wdam entry is 12;			[Amount of Damage monster Does when attacking.]
	now area entry is "Mall";	[ Current options are 'Outside' and 'Mall'  Case sensitive]
	now cocks entry is 1;			[ How many cocks will the infection try and cause if sex is 'Male' or 'Both']
	now cock length entry is 36;		[ Length infection will make cock grow to if cocks]
	now cock width entry is 24;		[ Size of balls apparently ;) sneaky Nuku]
	now breasts entry is 6;			[ Number of Breasts infection will give you. ]
	now breast size entry is 10;		[Size of breasts infection will try to attain ]
	now male breast size entry is 0;	[ Breast size for if Sex="Male", usually zero. ]
	now cunts entry is 1;			[ if sex = "Female or both", indicates the number of female sexes infection will grant you.]
	now cunt length entry is 36;		[ Length of female sex  infection will attempt to give you. ]
	now cunt width entry is 24;		[ Width of female sex  infection will try and give you ] 
	now libido entry is 80;			[ Amount player Libido will go up if defeated ]
	now loot entry is "Psionic Egg";			[ Loot monster drops, ]
	now lootchance entry is 50;		[ Chance of loot dropping 0-100 ]
	
to sharethebliss:
	infect "Anthro Shaft Beast";
	increase libido of player by 80;

an everyturn rule:
	if bodyname of player is "Anthro Shaft Beast":
		say "[broodmother call]";
	
to say broodmother call:
	if humanity of player is greater than 90:
		say "You hear a beautful song in the distance";
		increase libido of player by 5;
		decrease humanity of player by 1;
	otherwise:
		if humanity of player is greater than 70:
			say "Your legs feel weak, a soft tender voice speaks to you, the beautiful sound caresses your body, the back of your mind pulsing with joy, you smile.. enraptured by the strong entity speaking to you in unknown tongues.. then you snap out of it with a loud gasp, looking around with worry.. you had never felt such thing, you felt as if you were being watched from every corner.. and moved quickly to another spot, the feeling of being stared at never going away...[line break]";
			increase libido of player by 10;
			decrease humanity of player by 2;
		otherwise:
			if humanity of player is greater than 50:
				say "The voice continues drilling slowly into your mind, you feel helpless, unable to ignore it, but why would you?... it was so beautiful.. so powerful and it felt as if it was speaking to you and only you.. as if this entity from nowhere had eyes only for you, you couldn't help but lay down and smile, caressing your wonderful, sexy, strong body.. stroking your tendrils, making them coil and rub all over yourself.. it took hours for you to regain your control and leave.. you were dripping with arousal, part of you just wanted to give in and follow the voice's instructions.. you could understand the voice sometimes...[line break]";
				increase libido of player by 20;
				decrease humanity of player by 3;
			otherwise:
				if humanity of player is greater than 20:
					say "You cannot help but hissss in delight as you feel a tender caress run across your spine, the voice is at it again, but now.. you feel hands.. and kisses spreading all over your body.. invisble lips pressing against your most sensitive parts. invisible.. tender fingers caressing every inch of your body, your arousal burning like the sun, your body so warm, you feel those fingers dig into you.. caressing your insides.. touching.. your mind, then bliss, endless bliss lighting every fiber of your body, by the time you wake up, you let a silent cry escape your lips, you had hoped it would never end... your head hurts badly, you want more.. The Broodmother's call.. you cannot wait for the next one...[line break]";
					increase libido of player by 40;
					decrease humanity of player by 5;
				otherwise:
					say "[one of]'Come to me, my beautiful child.. we await for your offering...'[or]'Join usssssss...'[or]'Resssssist no further...'[or]'We are waiting for you...'[at random] said the Broodmother from hir hive, reaching out at you with waves of lust, places.. experiences from the past.. and the present flash before your eyes, the Broodmother giving you a mental map, preparing you for the long trip and your joining to hir blissful Hive...[line break]";
					sharethebliss;

when play ends:
	if bodyname of player is "Anthro Shaft Beast":
		if humanity of player is less than 10:
			say "Day by day the Broodmother's voice grows stronger, hir tempting, enthralling voice soothes your troubled mind, shi makes you forget of your worries and your old self, you give in at last, the Broodmother's joy at your own willing bliss made the most beautiful song you had ever heard, the neural network lighting up, every node calling and pulling on you, the song driving you into the underground, towards the Shaft Beast Hive, to meet a new blissful fate, serving under the beautiful and terrible Broodmother.. eventually shi makes of you hir favorite child, hir second in command as you take care of your Mother's constantly growing family, at hir side...";
		otherwise:
			say "Somehow you manage to resist the powerful voice of the Broodmother till rescue arrived, you feel your body pulse madly, demanding that you join the other abominations like yourself, your obscene body makes it hard for you to move on and the Broodmother's constant demands drive you mad day by day, but you hold yourself together, you were not going to submit to it or anyone else, the Military find you to be extremely infectious after you made dozens of them change with only your musk! They found no way to contain you or your infectious nature, instead, they decided to [apostrophe]put you out of your misery[apostrophe], but you would have none of that, with a soft swing of your fingers you fried minds, took down Choppers and sent Tanks flying away, escaping the military you find a nice, warm cave to hide and lie down, deciding to live in there you just accept your new self... After a few months of your lonely existence, you find out that you were not like other Shaft Beast.. you were different, stronger and after a few weeks, you couldn't hear the Broodmother's voice anymore. Something had changed, you did... your lips twisting into a wicked grin as you could feel it, YOU were the Broodmother now, the children of the old one now listening to your call, feeling your lust and bliss, This world just waits for the endless sea of bliss you shall bring to it now...";
			
Table of Game Objects(continued)
name	desc	weight	object
"Psionic Egg"	"An strange purple fleshy egg constantly [apostrophe]sweating[apostrophe] with a clear musky goo, you feel odd while holding it and you swear you heard someone whisper nearby"	1	Psionic Egg

Psionic Egg is a grab object.
Psionic Egg is infectious. The strain of Psionic Egg is "Anthro Shaft Beast".
the usedesc of Psionic Egg is "You hold the egg tightly in your hands, and as you look at it you hear a beautiful enthralling voice calling out at you, when you come to your senses, the egg has melted and it's now being absorbed by your skin...[line break]";


[ Edit this to have the correct Name as wall]
Anthro Shaft Beast For FS ends here.
