Version 3 of Daisy by Sarokcat n Verath begins here.
[ Version 3.1 - Two new M/F scene ]

"Adds an NPC to Flexible Survival with a variety of responses and goals..."

Section 1

Daisytalk is a number that varies.
daisyimpreg is a number that varies. daisyimpreg is usually 255.

Daisy is a woman.[or woman]
The description of Daisy is "[Daisydescribing]".
The conversation of Daisy is { "Ooo!" }.
The fuckscene of Daisy is "[sexwithdaisy]".

to say Daisydescribing:
	if Daisy is in Mares Quarters:
		say "     Standing off in one corner of the room and trying to catch your attention without the other mares noticing is a rather youngish looking maregirl. A closer look at the mare shows that she is still only partially transformed, though her body is definitely showing the signs of her equine transformation. The tight, electric blue g-string she is wearing shows off her newly enlarged cunt and  distinct camelto. Her face is almost completely equine and pushed out into a proper muzzle, while her ears have elongated into points and settled into their new position on top of her head. Her legs have also changed, although it is clear they are not quite complete yet, as they are longer and thinner and her heels have shifted upwards, forcing her to walk on her stiffening toes; they are well on their way to being proper digitigrade legs and hooves like the rest of the mares[']. Her half fearful, half lust-crazed look as she stares at you desperately makes you shudder as you realize how easily you could end up in her position.";
	else:	[in Master's Office]
		daisypregupdate;
		if HP of Daisy is 2 or HP of Daisy is 5:	[visibly preggers, pre-milfy]
			say "     A sexy brown and white dappled mare looks up at you eagerly from the corner of your office. Her adoring look makes you grin with amusement, which in turn makes the mare blush. She is aglow with happiness, caressing her rounded belly with a dreamy smile. Her lithe, sexy form is now that of a perfectly-shaped mareslut. Her coat is finely brushed and her blue eyes are nice and bright. Unlike most of the other maresluts, she seems to have found a French maid costume somewhere, or at least a few scraps of cloth and lace suggestive of one. It is a little tight over her pregnant body, but she wears it proudly. In her condition, she's not able to do as much tidying, but she is just as sexy all the same, stretching out sensually on cushions or mattresses when not cleaning.";
		else if HP of Daisy < 6:				[pre-milfy]
			say "     A sexy brown and white dappled mare looks up at you eagerly from the corner of your office. Her adoring look makes you grin with amusement, which in turn makes the mare blush[if HP of Daisy is 1 or HP of Daisy is 4]. She is aglow with happiness and seems extra-perky[end if]. Her lithe, sexy form is now that of a perfectly shaped mareslut. Her coat is finely brushed and her blue eyes are nice and bright. Unlike most of the other maresluts, she seems to have found a French maid costume somewhere, or at least a few scraps of cloth and lace suggestive of one. She wears this proudly as she goes around tidying up the Master's Office while you watch.";
		else if the remainder after dividing HP of Daisy by 3 is 2:	[visibly preggers, milfy]
			say "     A sexy brown and white dappled mare looks up at you eagerly from the corner of your office. Her adoring look makes you grin with amusement, and the mare rubs her pregnant belly, clearly pleased to have another of your foals on the way. Her sexy form has gained slightly wider hips and a bigger bust, now quite the MILFy mareslut - especially in her current condition. Her coat is finely brushed and her blue eyes are nice and bright. Unlike most of the other maresluts, she's assembled a French maid costume for herself, or at least a few scraps of cloth and lace suggestive of one. It is a little tight over her pregnant body, but she wears it proudly. In her condition, she's not able to do as much tidying, but she is just as sexy all the same, stretching out sensually on cushions or mattresses when not cleaning.";
		else:		[milfy]
			say "     A sexy brown and white dappled mare looks up at you eagerly from the corner of your office. Her adoring look makes you grin with amusement, and the mare runs a hand alluringly down her curvy body[if the remainder after dividing HP of Daisy by 3 is 1]. She is aglow with happiness and seems extra-perky[end if]. Her sexy form has gained slightly wider hips and a bigger bust while keeping a fairly slender waist, now quite the MILFy mareslut. Her coat is finely brushed and her blue eyes are nice and bright. Unlike most of the other maresluts, she's assembled a French maid costume somewhere, or at least a few scraps of cloth and lace suggestive of one. She wears this proudly as she goes around tidying up the Master's Office while you watch. The sight of her makes eager to [if the remainder after dividing HP of Daisy by 3 is 0]knock her up again[else]see her grow heavy with another of your foals[end if].";

instead of sniffing Daisy:
	daisypregupdate;
	if Daisy is in Master's Office:
		if HP of Daisy is 0:
			say "This mare smells of female arousal, now in heat and ready to be bred.";
		else if the remainder after dividing HP of Daisy by 3 is 0:
			say "The dappled mare smells of female arousal, now in heat and ready to be bred once again.";
		else if the remainder after dividing HP of Daisy by 3 is 1:
			say "The dappled mare smells of a lovely mix of warm hay and arousal.";
		else:
			say "The pregnant mare smells of a lovely mix of warm hay and arousal.";
	else:
		say "The dappled mare smells of horny mare and growing arousal. She is soon to go into heat.";

instead of conversing the Daisy:
	daisypregupdate;
	if Daisy is in Mares Quarters:
		if Daisytalk is 0:	[first time you encounter the npc text]
			say "     'Hey, you just arrived here didn't you? Do you mind if I ask you a favor?' the partially transformed girl asks, before blushing and looking down for a minute. 'Oh sorry, I forgot to introduce myself. My name is Daisy and I am kinda new here myself, so they are still teaching me how to interact with clients and studs,' Daisy says with an embarrassed shrug. 'It's great being here and all, and everyone is so nice and helpful, and I know I am so lucky to be here with all these handsome stallions around waiting to fuck me and fill me their foals.' She smiles dreamily for a minute as she rubs her bare breasts absently with her hands, before shaking her head slightly and looking at you again.";
			say "     'But it still feels like something is missing, and I was kind of hoping you could help me figure out what it was. If you don't mind, that is?' Daisy says with a small smile. 'I know I can't take up too much of your time or the other mares will start to get jealous, but if you could stop by occasionally and talk to me, I would really appreciate it. And maybe that would help me remember what it was that I seem to be missing,' the maregirl says with a slight grin as she looks at you hopefully, her smile broadening when you reluctantly nod in agreement. 'Great! I know I was somewhere else before they brought me here, because I remember all those nice handsome stallions with their big, thick cocks bringing me here. But I can't really remember much else about that time, though I think I might have been a student of some kind. And while they tell me that it must not be important if I can't remember it, I just feel like something is missing. So maybe if you talk to me about the city out there occasionally, it will help me remember. Either that or it will remind me of how much better off I am as a good little mare in here, and I can stop worrying about it,' Daisy says with happy smile, before looking around and seeing that several of the other mares have noticed your little talk, and shooing you along for now.";
			increase Daisytalk by 1;
		else if XP of Onyx is 3:	[Discussing Onyx for the 1st time]
			say "     'Hey there again, I'm glad you could come visit me again,' the transforming girl says with a grateful smile. 'It's really nice of you to help out a new filly like myself, you know. I really appreciate it,' Daisy says happily, before glancing around nervously to see if anyone is watching as she leans close to whisper softly to you. 'You know I have been trying to focus a bit more since I met you, and I think I am getting a little closer to remembering... something. I don't suppose you might have encountered anything that around here that might help?' she asks quietly as she rubs her mostly transformed head absently. As you look at her you find yourself thinking about Onyx for a minute. Wasn't he looking for someone who was brought here at the same time? Deciding it couldn't hurt to ask, you bring up the transforming boy to Daisy, mentioning that he also was a student who was brought here recently... and that perhaps she might know him somehow.";
			say "     'Onyx? Onyx.... no, not Onyx, though that sounds... close...' she says as she scrunches up her equine forehead in thought, the cute sight making you grin slightly as she mutters to herself about fellow students and Onyx... before blinking in surprise. 'Not Onyx, but... Oscar, I think. And I think that might be what I was trying to remember! He was important to me somehow. I think, anyways,' Daisy says with quiet excitement. She listens intently as you fill her in on the changing boy's current plight, and how he thinks he is looking for someone. 'Oh... well that's not good. Do you think he is staying because of me? That sounds... pretty nice actually. It would be good to have a nice filly friend to share the stallions with, or maybe he can become a stallion and fuck me nice and hard and long, and then we could be together...' she says with a dreamy smile on her face as one of her hands drops down to rub absently at her g-string, while the other massages her ample breasts absently. Looking at how happy she seems as a slutty little transforming filly, you find yourself wondering if you really want to take Onyx away from the place, or if you might not be able to help the changing boy fit in here with his obviously happy friend instead. Do you ask her about helping Onyx to [link]leave (y)[as]y[end link] or do you bring up the fact that Onyx might be persuaded to [link]stay (n)[as]n[end link] and be a good horse with just a little bit of incentive?";
			if player consents:
				say "     You find yourself shaking your head to clear it of the increasingly sexual sight of Daisy enjoying herself, before bringing up the fact that you might be able to get Onyx, and perhaps eventually her away from the Stables. 'Leave the Stables? But why would we want to leave the Stables? That's where the stallions are,' she says with obvious confusion as she cocks her head at you questioningly. 'Though... I suppose I must have wanted to be somewhere else before...' Daisy pauses to try to think for several minutes, while glancing around the room idly, before sighing heavily. 'I just can't remember... though I do seem to recall that he was important to me somehow, but it's all so fuzzy and dreamlike,' she says sadly, hanging her head down for a second. She looks up at you with her deep black eyes pleadingly. 'I can't trust myself to know what's best anymore, and you seem to know what you are doing, so I guess I'll just have to trust you instead.'";
				say "     The transforming mare looks around herself quickly before leaning closer to you. 'I do remember them taking our stuff from us, and I had a leaf patterned necklace that I think Oscar, or rather Onyx, might have given me... If I'm right and you find that necklace in the storeroom, he should listen to you when you tell him I said he should go with you and be happy,' she whispers with a soft smile on her muzzle as she rubs her empty neck. 'Just let him know I am nice and comfortable here with all the other mares, though I still think it might have been nice if he had decided to stay here instead...' she trails off for a minute, before glancing around and noting that several other mares are starting to take note of your conversation, and shoos you away to go look for her necklace.";
				now XP of onyx is 4;
				Now Stablestoreroom is unresolved;
			else:
				say "     'You think you could get him to stay? Oh, that would be wonderful!' Daisy says as she claps her changing hands together happily, before blushing a bit and glancing around to see if any of the other mares noticed her small outburst. 'Sorry about that. I just got a bit excited there,' she says sheepishly before continuing. 'If you think you can convince him to stay and be a good little stallion, or even a good little filly, with me, I would be ever so happy. And I am sure he would fit in wonderfully here... especially if he ends up with a nice big horsecock... mmm...' Daisy moans dreamily for a second, the expression on her partially changed face filled with lust as she stares off into the distance before catching herself and looking back at you. 'Convincing Oscar, or rather Onyx, to stay, shouldn't be too hard. Just tell him that I said he should be a good little horsey like me,' she says with a rather equine grin as she rubs her hands over her shapely new body. 'If he is who I almost remember, that should help I think, and then we can have so much fun together! And maybe you can stay here with us as well!' she says happily, her exuberance beginning to attract some attention from a few of the other mares in the area. Noticing the attention she is attracting, Daisy blushes slightly before shooing you off with a slight teasing wink.";
				now XP of onyx is 50;
		else if XP of Onyx > 3 and XP of Onyx < 50:		[Onyx - freedom path]
			say "     [one of]'Hey again, got any good stories for me?'[or]'I wonder what it is that could be missing from my life. There is plenty of food and mares to keep me company, and soon I will even get to play with the stallions! What more could a mare want?'[or]'I feel so much better now that I remembered a little of what was so important.'[or]'You take good care of Onyx for me, ok?'[or]'I know I was human before, but that just seems like such a waste. Being a mare feels so much better!'[or]'Shhh, you don't want them to think I am monopolizing all your time!'[or]'How is it going with Onyx?'[or]'I wonder what kind of studs I will end up servicing when I finally finish my training.'[or]'You should try being a mare sometime. It's wonderfully relaxing just to let someone else make all the decisions for you while you lie around in the rooms until a nice customer or stud comes along...'[or]'I wonder if I will ever have any foals. That would be so nice,' she says wistfully.[or]'I understand they have breeding mares somewhere else in the building. I wonder what they are like?'[or]'I think I came here with... someone?'[or]'Fancy is a nice mare. She helps take care of the rest of us, though she seems a bit lonely herself sometimes.'[at random]";
		else if XP of Onyx >= 50 and XP of Onyx < 100:		[Onyx - Stables path]
			say "     [one of]'Hey again. Got any good stories for me?'[or]'I wonder what it is that could be missing from my life. There is plenty of food and mares to keep me company, and soon I will even get to play with the stallions! What more could a mare want?'[or]'I feel so much better now that I remembered a little of what was so important.'[or]'I am so looking forward to how Onyx turns out!'[or]'I know I was human before, but that just seems like such a waste. Being a mare feels so much better!'[or]'Shhh, you don't want them to think I am monopolizing all your time!'[or]'How is it going with Onyx?'[or]'I wonder what kind of studs I will end up servicing when I finally finish my training.'[or]'You should try being a mare sometime. It's wonderfully relaxing just to let someone else make all the decisions for you while you lie around in the rooms until a nice customer or stud comes along...'[or]'I wonder if I will ever have any foals. That would be so nice,' she says wistfully.[or]'I understand they have breeding mares somewhere else in the building. I wonder what they are like?'[or]'I hope Onyx becomes a slutty little mare just like me! It feels so veeery good!'[or]'Fancy is a nice mare. She helps take care of the rest of us, though she seems a bit lonely herself sometimes.'[at random]";
		else:	[Normal short messages the npc will say each time you talk to them]
			say "     [one of]'Hey again. Got any good stories for me?'[or]'I wonder what it is that could be missing from my life. There is plenty of food and mares to keep me company, and soon I will even get to play with the stallions! What more could a mare want?'[or]'I know I was human before, but that just seems like such a waste. Being a mare feels so much better!'[or]'Shhh, you don't want them to think I am monopolizing all your time!'[or]'I wonder what kind of studs I will end up servicing when I finally finish my training.'[or]'You should try being a mare sometime. It's wonderfully relaxing just to let someone else make all the decisions for you while you lie around in the rooms until a nice customer or stud comes along...'[or]'I wonder if I will ever have any foals. That would be so nice,' she says wistfully.[or]'I understand they have breeding mares somewhere else in the building. I wonder what they are like?'[or]'I think I came here with... someone?'[or]'Fancy is a nice mare. She helps take care of the rest of us, though she seems a bit lonely herself sometimes.'[at random]";
	else:
		if Daisytalk is 0:		[First talk taking place in the office]
			say "     'I know we haven't really had a chance to talk much, you being so busy as the Stablemaster and all. I do appreciate you making a place for me here,' she says happily, motioning to your palatial office as if it were truly a castle of wonders instead of a heart of debauchery. 'Well, like Fancy said, my name is Daisy and I'm one of the newest mares here. She says I'm finally ready for breeding - which is wonderful, it feels like I've been waiting forever. And now I get to serve the Stablemaster,' she gushes, shifting excitedly from hoof to hoof.";
			say "     When she manages to calm down a little after playing with herself under her frilly skirt, a cloud of worry crosses her face. 'But it still feels like something is missing sometimes. I was kind of hoping you could help me figure out what it was. If you don't mind, that is,' she says, running her hoof-like hands over your chest. 'I'm sure such a big, strong [if player is male]stud[else]mare[end if] like you could help me figure it out. I want to be the best slutty mare breeder I can be and I know if I can remember what I've forgotten, then I can focus on doing just that for you,' she says. When you nod and agree to look into it, she grinds herself up against you even as she gives you a peck on the cheek in thanks.";
			say "     'You're such a great Stablemaster. I'm so looking forward to serving and servicing you,' she says. 'Now, I remember I was somewhere else before they brought me here, because I remember all those nice handsome stallions with their big, thick cocks bringing me here. But I can't really remember much else about that time, though I think I might have been a student of some kind. And while they tell me that it must not be important if I can't remember it, I just feel like something is missing. So maybe if you talk to me about the city out there occasionally, it will help me remember. Either that or it will remind me of how much better off I am as a good little mare in here, and I can stop worrying about it,' Daisy says with happy smile, before realizing that she's been talking to her [if player is male]master[else]mistress[end if] rather than being the sexy mare breeder she was trained to be.";
		else if XP of Onyx is 3:	[Discussing Onyx for the first time]
			say "     'It's so nice of you to stop and talk to me again,' the [if HP of Daisy >= 6]MILFy mare[else]mare girl[end if] says with an adoring smile, wiggling her ass sexily as she does a little cleaning. 'It's really nice of you to care about a silly little filly like myself, you know. You must be so busy as the Stablemaster and all.'";
			say "     Setting down the vase and duster she's holding, she turns to face you. 'You know, I have been trying to focus a bit more since I met you, and I think I am getting a little closer to remembering... something. I don't suppose you might have encountered anything that around here that might help?' she asks quietly as she rubs her transformed head absently. As you look at her you find yourself thinking about Onyx for a minute. Wasn't he looking for someone who was brought here at the same time? Deciding it couldn't hurt to ask, you bring up the transforming boy to Daisy, mentioning that he also was a student who was brought here recently... and that perhaps she might know him somehow.";
			say "     'Onyx? Onyx.... no, not Onyx, though that sounds... close...' she says as she scrunches up her equine forehead in thought, the cute sight making you grin slightly as she mutters to herself about fellow students and Onyx... before blinking in surprise. 'Not Onyx, but... Oscar, I think. And I think that might be what I was trying to remember! He was important to me somehow. I think, anyways,' Daisy says with quiet excitement. She listens intently as you fill her in on the changing boy's current plight, and how he thinks he is looking for someone. 'Oh... well that's not good. Do you think he is staying because of me? That sounds... pretty nice actually. It would be good to have a nice filly friend to share the stallions with, or maybe he can become a stallion and fuck me nice and hard and long, and then we could be together...' she says with a dreamy smile on her face as one of her hands drops down to rub absently under her skirt while the other massages her ample breasts. 'You're the Stablemaster; I'm sure you'll know what's best.'";
			say "     Looking at how happy she seems as a slutty mare, you find yourself wondering if you really want to take Onyx away from the place. Might he not be better able to serve you and the Stables if you were instead to help the young man change to fit in so he (or perhaps as a she) can stay with his obviously happy friend instead. Do you ask her about helping Onyx to [link]leave (y)[as]y[end link] or do you suggest that Onyx might be persuaded to [link]stay (n)[as]n[end link] and be a good horse with just a little bit of incentive?";
			if player consents:
				say "     You find yourself shaking your head to clear it of the increasingly sexual sight of Daisy enjoying herself, before bringing up the fact that you might be able to get Onyx away from the Stables. 'Leave the Stables? But why would he want to leave the Stables? That's where the stallions are,' she says with obvious confusion as she cocks her head at you questioningly. 'Though... I suppose I must have wanted to be somewhere else before...' Daisy pauses to try to think for several minutes, while glancing around the room idly, before sighing heavily. 'I just can't remember... though I do seem to recall that he was important to me somehow, but it's all so fuzzy and dreamlike,' she says sadly, hanging her head down for a second. She looks up at you with her deep black eyes pleadingly. 'I can't trust myself to know what's best anymore, and you seem to know what you are doing, so I guess I'll just have to trust you instead. If you don't think he'll work out here at the Stables, then can you find a better home for him? Some place where he'll get plenty of sex?'";
				say "     The [if HP of Daisy >= 6]MILFy mare[else]mare girl[end if] leans in closer, running her hands over your chest before leaning in closer to you. 'I do remember them taking our stuff from us, and I had a leaf patterned necklace that I think Oscar, or rather Onyx, might have given me... If I'm right and you find that necklace in the storeroom, he should listen to you when you tell him I said he should go with you and be happy,' she whispers with a soft smile on her muzzle as she rubs her empty neck. 'Just let him know I am nice and comfortable here with all the other mares, though I still think it might have been nice if he had decided stay here instead... Be sure to find him a place where he can have as much fun as I'm having,' she says with a happy giggle, making a show of bending over to show off her lace-covered ass as she gets back to tidying up your bordello office.";
				now XP of onyx is 4;
				Now Stablestoreroom is unresolved;
			else:
				say "     'You think you could get him to stay? Oh, that would be wonderful!' Daisy says, hugging you happily and giving you a kiss that quickly turns very bawdy as your tongues wrestle. 'Sorry about that. I just got a bit excited there,' she says with a giggle, stepping back and moving her hands to play with her breasts. 'If you think you can convince him to stay and be a good little stallion, or even a good little filly with me, I would be ever so happy. And I'm sure he'll fit in wonderfully here... especially if he ends up with a nice big horsecock... mmm...' Daisy moans dreamily for a second, the expression on her partially changed face filled with lust as she stares off into the distance before catching herself and looking back at you. 'Convincing Oscar, or rather Onyx, to stay, shouldn't be too hard. Just tell him that I said he should be a good little horsey like me,' she says with a rather equine grin as she rubs her hands over her shapely new body. 'If he is who I almost remember, that should help I think, and then we can have so much fun together!' she says happily. 'Mmm... just the thought of it is turning me on. Oh, if it's not too forward of a servant like me... All this talk has gotten me really turned on and I'd really like to show you my gratitude,' she says, licking sensually across her lips while caressing your sexy body.";
				now lastfuck of Daisy is turns + 12;
				now XP of onyx is 50;
		else if XP of Onyx > 3 and XP of Onyx < 50:		[Onyx - freedom path]
			say "     [one of]'What've you been up to lately, [if player is male]master[else]mistress[end if]? Got any good stories for me?'[or]'I wonder what it is that could be missing from my life. Everything's so great here with you, the mares and the stallions! What more could a mare want?'[or]'I feel so much better now that I remembered a little of what was so important.'[or]'You take good care of Onyx for me, ok?'[or]'I know I was human before, but that just seems like such a waste. Being a mare feels so much better!'[or]'Do you like my outfit?' she asks, posing suggestively to show off her French maid outfit.[or]'How is it going with Onyx?'[or]'It's such an honor to be assigned to servicing you.'[or]'I don't think I could handle being the Stablemaster like you. I much prefer just standing around and being sexy while letting others make the decisions for me. I mean, I get to play sexy maid when I'm not being your slutty mare - it's great!'[or]'[if HP of Daisy >= 3]Having foals is wonderful! I want to breed so many more strong stallions and fine mares,' she says, running her hands over her belly[else if HP of Daisy is 2]My first foal is on its way. I'm so happy!' she says gleefully[else if HP of Daisy is 1]I think I might have a foal on the way,' she says with a happy whisper, nearly bouncing for joy at the prospect[else]I'm so looking forward to having my first foal. Please take me as soon as you can, Stablemaster,' she says with lustful eagerness[end if].[or]'I understand they have breeding mares somewhere else in the building. Could you maybe assign me there when you're done with me? Not that I want to leave here, but if you ever tire of me...' she whimpers, the thought of disappointing you and being replaced bringing tears to the corners of her eyes.[or]'I feel so much better knowing I don't have to worry my silly little head about anything now and can be the slutty mare everyone wants me to be.'[or]'Fancy is a nice mare. She works so hard helping to take care of the rest of us, though she seems a bit lonely herself sometimes. You should go visit her!' she says with a big smile.[at random]";
		else if XP of Onyx >= 50 and XP of Onyx < 100:		[Onyx - Stables path]
			say "     [one of]'What've you been up to lately, [if player is male]master[else]mistress[end if]? Got any good stories for me?'[or]'I wonder what it is that could be missing from my life. Everything's so great here with you, the mares and the stallions! What more could a mare want?'[or]'I feel so much better now that I remembered a little of what was so important.'[or]'I am so looking forward to how Onyx turns out!'[or]'I know I was human before, but that just seems like such a waste. Being a mare feels so much better!'[or]'Do you like my outfit?' she asks, posing suggestively to show off her French maid outfit.[or]'How is it going with Onyx?'[or]'It's such an honor to be assigned to servicing you.'[or]'I don't think I could handle being the Stablemaster like you. I much prefer just standing around and being sexy while letting others make the decisions for me. I mean, I get to play sexy maid when I'm not being your slutty mare - it's great!'[or]'[if HP of Daisy >= 3]Having foals is wonderful! I want to breed so many more strong stallions and fine mares,' she says, running her hands over her belly[else if HP of Daisy is 2]My first foal is on its way. I'm so happy!' she says gleefully[else if HP of Daisy is 1]I think I might have a foal on the way,' she says with a happy whisper, nearly bouncing for joy at the prospect[else]I'm so looking forward to having my first foal. Please take me as soon as you can, Stablemaster,' she says with lustful eagerness[end if].[or]'I understand they have breeding mares somewhere else in the building. Could you maybe assign me there when you're done with me? Not that I want to leave here, but if you ever tire of me...' she whimpers, the thought of disappointing you and being replaced bringing tears to the corners of her eyes.[or]'I hope Onyx becomes a slutty little mare just like me! It feels so veeery good!'[or]'I feel so much better knowing I don't have to worry my silly little head about anything now and can be the slutty mare everyone wants me to be.'[or]'Fancy is a nice mare. She works so hard helping to take care of the rest of us, though she seems a bit lonely herself sometimes. You should go visit her!' she says with a big smile.[at random]";
		else:	[Did not start Onyx's content]
			say "     [one of]'What've you been up to lately, [if player is male]master[else]mistress[end if]? Got any good stories for me?'[or]'I wonder what it is that could be missing from my life. Everything's so great here with you, the mares and the stallions! What more could a mare want?'[or]'I know I was human before, but that just seems like such a waste. Being a mare feels so much better!'[or]'Do you like my outfit?' she asks, posing suggestively to show off her French maid outfit.[or]'It's such an honor to be assigned to servicing you.'[or]'I don't think I could handle being the Stablemaster like you. I much prefer just standing around and being sexy while letting others make the decisions for me. I mean, I get to play sexy maid when I'm not being your slutty mare - it's great!'[or]'[if HP of Daisy >= 3]Having foals is wonderful! I want to breed so many more strong stallions and fine mares,' she says, running her hands over her belly[else if HP of Daisy is 2]My first foal is on its way. I'm so happy!' she says gleefully[else if HP of Daisy is 1]I think I might have a foal on the way,' she says with a happy whisper, nearly bouncing for joy at the prospect[else]I'm so looking forward to having my first foal. Please take me as soon as you can, Stablemaster,' she says with lustful eagerness[end if].[or]'I understand they have breeding mares somewhere else in the building. Could you maybe assign me there when you're done with me? Not that I want to leave here, but if you ever tire of me...' she whimpers, the thought of disappointing you and being replaced bringing tears to the corners of her eyes.[or]'I think I came here with... someone?'[or]'Fancy is a nice mare. She works so hard helping to take care of the rest of us, though she seems a bit lonely herself sometimes. You should go visit her!' she says with a big smile.[at random]";



to say sexwithdaisy:
	daisypregupdate;
	if daisytalk is 0 and Daisy is in Mares Quarters:
		say "     You should at least feign interest in the mare you're planning on fucking. Try talking to her first.";
	else if lastfuck of Daisy - turns < 6:
		say "     You've made use of this mare fairly recently. You decide to wait rather than risk getting bored of her too soon.";
	else if player is neuter:
		say "     It might not be prudent for the Stablemaster to display that they have no genitals at this time.";
	else if Daisy is in Master's Office:
		quietrestorenightmareform;
		say "     Eyeing Daisy, you grow aroused and approach her with lustful intent[if nmformswitch is true]. Your lust for this prize mare awakens your Nightmare form, transforming your body to that of the powerful equine[end if]. Putting your arms around the dappled beauty, you have her strip off her maid outfit so you might take your privilege with her. As the new Stablemaster, your claim on using Daisy is uncontested and she is eager to fulfil your needs";
		if player is male:
			if HP of Daisy >= 5 and the remainder after dividing HP of Daisy by 3 is 2 and a random chance of 2 in 3 succeeds:
				say ". To demonstrate this, the pregnant mare drops to her knees and lavishes attention upon your equine manhood. Her tongue licks up and down it, drooling over your virile balls. After the tongue bath, she goes for full immersion, taking it into her long, equine muzzle. The blow job is very enjoyable, the mare clearly having taken to her training well.";
				say "     Given how the mare is already with foal, you decide to fully enjoy her oral skills. Letting her work over your cock for a while, you have her pause so you can take a seat in your impressive chair before telling her to resume her work. She smiles and crawls over to you on all fours in a sultry manner, full breasts swaying deliciously. Taking your cock in hand again, she nuzzles at your ballsack, moaning at your potent scent. She licks your orbs while letting your equine shaft rub along her dappled face. She worships the virile manhood of her master like this for a while, showing her adoration for the stallion and the cock that have given her [if HP of Daisy >= 8]several [end if]foals.";
				say "     As enjoyable as this is, you do tire of it after a while and order the mare to suck you off. She does so eagerly, taking your cock back into her equine muzzle with a long moan. Her tongue and palate slide across your manhood as she takes you in and then gets to work sucking you off. Her cock-sucking skills are excellent, the mare doing the very best she can to please her master. The tight, wet embrace of her mouth and throat causes your mighty shaft to pulse and throb with excitement.";
				say "     Keeping it up, the copious amounts of precum she sucks out of you is eventually replaced with the much thicker and potent blasts of your stallion seed. She moans in delight at the taste of it and sucks all the harder, working to get every gooey drop she can into her belly to feed her coming foal. Still fondling your balls with one hand, the other gets buried between her legs as she masturbates to a climax of her own[if cock width of player <= 6]. While your load may be small by the standard of stallions, she still finds it deliciously satisfying in its potency[else if cock width of player <= 16]. She finds your [cum load size of player] load deliciously satisfying in its potency[else]. Your [cum load size of player] is deliciously satisfying for her, both in its volume and its potency[end if]. Only once you're fully spent does she take her muzzle off of you, moving to rest it upon your lap with a happy sigh of adoration for her mighty Stablemaster.";
			else if HP of Daisy >= 6 and a random chance of 1 in 2 succeeds:
				say ". The MILFy mare reclines herself on one of the mattresses and spreads her legs lewdly, moaning softly that she'd love [if the remainder after dividing HP of Daisy by 3 is 0]you to breed her again[else]to feel you inside her again[end if]. As way of added (and unnecessary) enticement, she brushes her fingertips across her moist petals before spreading them open for you in invitation.";
				say "     With such an enticing target, your equine rod bucks eagerly. This sends a splatter of precum across the mare's [if the remainder after dividing HP of Daisy by 3 is 2]pregnant [end if]belly. 'Oh, someone's eager. Come, my sexy master, let me be your warm stable,' she says, holding out her other hand. Advancing, you bring your manhood into her reach and she starts by stroking it, then licking and kissing it before finally taking it into her long, equine muzzle. Her training and growing experience shows as she practically worships the mighty rod that's given her [if HP of Daisy >= 9]several [end if]foals.";
				say "     While this blow job is very enjoyable, you both know what you really want so you push her head back after only a dozen or so sucks. She gives your crown a final lick before laying back fully on the mattress. You move atop her, lining up your equine shaft and pushing it into the mare's welcoming folds. She gives a nickering moan as you push deep into her with ease, Daisy's cunt trained to be the Stablemaster's to use and breed. Her hoof hands rub your strong chest and sides, her hips wiggle and her inner walls squeeze and pull at you. She puts her growing experience at pleasing you to good use, working her hips and squeezing her cunt around you in the ways that please you the best. As reward for her efforts, you give her the thorough fucking she so clearly needs.";
				say "     As your excitement builds towards your peak, the MILFy mare moves a hand to cup your virile balls. You release a loud neigh and drive deep into her as you climax. Your [short ball size] orbs twitch in her grip and she gives a happy nicker, knowing that your hot seed is on the way, and a moment later, your cock throbs hard inside her as the first of several gooey blasts is shot into the lovely[if the remainder after dividing HP of Daisy by 3 is 0] and fecund[end if] mare. Feeling this is enough to set her off, cumming with lustful cries of her own. Once you've finished and pulled out, she's on your cock immediately, licking and sucking it clean of her virile master's spunk. You caress the dutiful girl's forehead and ears as she does, waiting until you're fully clean before leaving her to enjoy the warmth you've left in her belly.";
				if the remainder after dividing HP of Daisy by 3 is 0:
					increase HP of Daisy by 1;
					now daisyimpreg is turns;
			else:
				say "[if HP of Daisy is 0]. Ready and willing to at long last be bred[else if the remainder after dividing HP of Daisy by 3 is 0]. Ready and willing to be bred again[else]. Eager for her master to mount her again[end if], she starts by getting on her knees and lavishing attention upon your equine manhood. Her tongue licks up and down it, drooling over your virile balls. After the tongue bath, she goes for full immersion, taking it into her long, equine muzzle. The warm-up blow job is very enjoyable, the mare clearly having taken to her training well.";
				say "     After this sample of her cock-sucking skills, you move her over to one of the mattresses. You smile as she spreads her legs wantonly[if HP of Daisy is 0] for her first breeding[else if the remainder after dividing HP of Daisy by 3 is 0] for another breeding[else if the remainder after dividing HP of Daisy by 3 is 2], eager despite her advancing pregnancy[end if]. With a proud neigh, you line your midnight shaft to her pink folds and thrust deep inside. She gives a nickering moan and arches up into your thrust, sending you even deeper. The young mare is delightfully responsive, [if HP of Daisy is 0]loving having the Stablemaster for her first breeding[else]loving all the personal attention you as the Stablemaster have been giving her[end if]. Her hoof hands rub your chest and sides, her hips wiggle and her inner walls squeeze and pull at you. As reward for her efforts, you give her the thorough fucking she so clearly needs.";
				say "     When you reach your climax, you cum hard, pumping a thick load of equine seed into [if HP of Daisy is 0]her previously unclaimed womb[else if the remainder after dividing HP of Daisy by 3 is 0]her fecund womb[else if the remainder after dividing HP of Daisy by 3 is 1]the sexy mare[else]the pregnant mare[end if]. She gives a loud nicker of her own at your orgasmic release, cumming herself in response. Once you've finished and pulled out, she's on your cock immediately, licking and sucking it clean of her virile master's spunk. You caress the dutiful girl's forehead and ears as she does, waiting until you're fully clean before leaving her to enjoy the warmth you've left in her belly.";
				if the remainder after dividing HP of Daisy by 3 is 0:
					increase HP of Daisy by 1;
					now daisyimpreg is turns;
		else:
			say ". Eager to be of service to the Stablemaster, she starts by getting on her knees and [']servicing['] you with her broad tongue. Her tongue licks all across your [cunt size desc of player] puss[yfn] and clit[sfn] before finally pressing into [if cunts of player > 1]one of those hot tunnels[else]your hot tunnel[end if].";
			say "     While this wasn't the primary focus of her training, you can tell that she and the other mares must indulge in this, given both the eagerness and familiarity she shows with the task. You grip her head firmly with one hand, keeping her muzzle buried in your crotch while the other rubs her forehead and ears. Calling her a good mare and an eager little whore only encourages her, clearly eager to please her Stablemaster as best she can. With her going to town on your cunt[sfn], you enjoy several mini-orgasms before finally building to a powerful one that has you cry out with a nickering neigh. The girl buried in your crotch emits a wet moan in response and drinks down your feminine juices while fingering herself to climax. As your orgasm wanes, she switches to lighter licking, obediently cleaning your midnight coat around the crotch with her tongue. You caress the dutiful girl's forehead and ears as she does, waiting until you're fully clean before leaving her to keep playing with herself while remembering her mistress's visit.";
		now lastfuck of Daisy is turns;
	else:
		say "     'Sorry, but I have to pass on that. While it would be kind of nice to be used like a proper mare, I haven't managed to finish my training yet. They say I can't work with any customers until I know how to properly service them,' Daisy says with a shy smile. 'Though maybe you could come back once they say I am ready and you could ride me then?' she continues as she looks at you hopefully.";


to daisypregupdate:
	if HP of Daisy > 0:
		if the remainder after dividing HP of Daisy by 3 is 1 and daisyimpreg - turns >= 12:
			increase HP of Daisy by 1;
		if the remainder after dividing HP of Daisy by 3 is 2 and daisyimpreg - turns >= 24:
			increase HP of Daisy by 1;
		if HP of Daisy is 30:
			now HP of Daisy is 12; [prevent huge values]


Daisy ends here.
