Onyx by Sarokcat n Verath begins here.

"Adds a npc to Flexible Survival with a variety of responses and goals..."

section 1- Onyx

Onyxtalk is a number that varies.
Onyxaroused is a number that varies.[not a needed number, but used to set different arousal states if they aren't automatically willing to just hop into bed.]
Onyxquest is a number that varies.[often used for quests or renamed to Onyxquest, see boris for some good examples of this, totally unneeded if the npc doesn't have an associated quest.]
Onyxkeys is a number that varies.[Will be used by the part of the quest that frees him from his cell.]
LastOnyxfucked is a number that varies. LastOnyxfucked is usually 250.
Onyxfucked is a number that varies. Onyxfucked is usually 0.

Onyx is a man.[or woman]
The description of Onyx is "[onyxappearance]";
The conversation of Onyx is { "Help me!" }.

instead of sniffing Onyx:		[results for currently uncoded outcomes included]
	if onyxquest is 0:
		say "The young man smells both human and equine.";
	otherwise if onyxquest is 1 or onyxquest is 2:
		say "The young man smells even more of horses than before, with his human scent fading further.";
	otherwise if onyxquest is 3:
		say "The young mare smells of arousal and sex, clearly enjoying her new life at the club.";
	otherwise if onyxquest is 4 or onyxquest is 6:
		say "The young stallion smells of growing male arousal.";
	otherwise if onyxquest is 5:
		say "The slutty mare smells strongly of arousal and equine sex.";

To say onyxappearance:[his description at each stage, comments on what each stage is linked to will be in these brackets]
	if onyxquest is 0:[onyx is still trapped, or first times you encounter him.]
		say "Standing behind the barred door to his room is a teenage boy of about the right age for a college student. His body already beginning to show the signs of his equine transformation. The boy is wearing nothing but a tight black thong that easily contains his obviously shrinking manhood. The young mans face is slightly pushed out into a growing equine muzzle and his ears have elongated into points and have started moving to the top of his head. You can see that his legs are becoming longer and thinner, and his ankles have shifted upwards on them, forcing him to stand on the balls of his changing feet, his toes already starting to merge to form a rather horselike hoof.  The half fear half lust crazed look in his eyes makes you shudder slightly as you realize how easily that could have been you behind those bars, and possibly could still be.";
	if onyxquest is 1:[onyx has been freed from his cell, but has continued transforming and needs to be persuaded if they are to leave, or if they are going to stay(leave will be harder to achieve then letting him stay).]
		say "Leaning up against the wall is a teenage horseboy, his transforming features are much more obvious now as his face is obviously pushing out into an equine muzzle, and his legs are shifting to the point where he can hardly stand on them without the help of the wall. His feet are nearly fully formed hooves however, and his hands are becoming slightly hooflike as well, so you can tell it isn[apostrophe]t going to be much longer before he finishes changing, though from the small bulge in his tight black thong, you can see that he is still holding on to his manhood, for however much longer that will last at least...";
	if onyxquest is 2:[Onyx has come with you to freedom, and is waiting at the library, not fully transformed yet, but actually starting to look forward to it and could end up either way.]
		say "The tall horseboy is seated at one of the empty library desks, and is idly poking at several of the books stacked in front of him curiously. His features have continued to change from when you rescued him from the library, and his face is nearly a full equine muzzle now, and underneath the desk, you are all to well aware of how very equine his legs and body has become. Onyx doesn[apostrophe]t seem to mind the changes at all anymore however, and he looks up at you with a rather sexy smile as you approach.";
	if onyxquest is 3:[Onyx has become convinced to visit the palomino, where she is learning to be a female stripper.]
		say "Onyx seems quite happy as she bobs her head to the beat of the bouncy music, the former teenage boy has obviously adapted well to her new role as a sexy mare. Her lush black equine pelt is draped in a leather harness with shiny silver buckles, and she has is wearing a tight red thong and bra that barely contain her obviously damp and needy mare pussy, and her pert and sexy breasts. You can tell just by the looks that several of the club goers are giving her that she is going to be quite a popular little stripper here at the club, and from the teasing glances she sends you from time to time, she certainly appears grateful for all your help in getting her here..";
	if onyxquest is 4:[Onyx has decided to take advantage of the situation, and has become a slightly more dominant male horse in the library, and is looking to convince you to be a proper mare for him. Fully tfed now]
		say "Onyx looks like a proper Stallion now, his handsome black equine features, and lovely pelt of jet black horse fur making him look extremely exotic and sexy as he wanders around the library. Noticing you looking at him, he shoots you a rather dominant equine grin, as he flexes slightly for your enjoyment. His obviously large and powerful stallionhood obviously far to large now to be contained in a thong, it hangs half erect between your stallions legs as if teasing you to come over and worship it properly.";
	if onyxquest is 5:[Onyx has decided to stay at the Stables, and is looking forward to becoming a proper mare like all the rest. Fully Tfed Looking forward to some nice training, which maybe you can help her with(maybe harnesses and light bondage?)]
		say "The transforming boy has finally become a proper mare, and certainly lives up to her new name now. Onyx has become a pure black mare, her lithe equine body seems perfectly proportioned for pleasure as she shifts her weight from hoof to hoof teasingly.  She seems to have stopped worrying about anything other than being a properly slutty mare now, and from the looks she is shooting you from time to time, she is more than interested in letting you take her for a ride...";	
	if onyxquest is 6:[Onyx has decided to stay at the stables, and has cut a deal with them, he gets to stay a stallion, as long as he makes a mare to take his place! And that mare would be you if he can get you in that position. Fully Tfed- likely will take the initiative and see about getting the character into a bridle, saddle, harness, other leather accessories, or maybe just tied up for a while....]
		say "The formerly weak teenage boy has been replaced by a large and powerful black stallion, his proud muzzle and the wicked glint in his equine eyes promise a lot of fun as he eyes you with anticipation. He still hangs out in the hallway here, though at some point his name has been removed from the room he is standing in front of, and someone has hung the name 'Obsidian' in it[apostrophe]s place. Looking at where the powerful stallion shifts his weight teasingly as he gestures you closer, you can[apostrophe]t tell whether or not you feel sorry for the next captive they put in the room with him, or envious...";


	




instead of conversing the Onyx:
	if Onyxtalk is 0:[first time you encounter the npc text]
		say "'Oh hey,' The partially transformed boy says with a sigh as you approach his cell to talk with him. 'Come to tease me again and try to get me to give in and become a slutty little mare?' He says with a sigh, before shifting to turn and give you a closer look, and blinking in surprise. 'Hey wait, you seem different from the rest of them, you aren[apostrophe]t with the horses here are you?' He says with increasing excitement as he sits up and staggers to the door, obviously slightly unsteady on his legs as he tries to walk. 'It[apostrophe]s good to see someone that isn[apostrophe]t one of those horsemen, here to tell me what a fine filly I will make them. My name is Os... Os.. something, dammit.' The transforming equine curses, his hands gripping the bars as he steadies himself on his obviously changing feet. 'Sorry, they told me to forget that name, and it kind of looks like I am, it has been getting harder and harder to remember things anyways since I arrived here.' He shudders for a second, before sighing and looking at you with his slightly larger then normal eyes pleadingly. 'I guess you can call me Onyx, I mean I know I have another name, and I don[apostrophe]t really like answering to what they call me, but it looks like I don[apostrophe]t have much choice until I can remember my old name.' Onyx says with resignation, staring at his changing feet for a minute, before focusing his attention fully on you again.[line break]";
		say "'Anyways, maybe you can help me, I was brought here with my boyfriend... no wait dammit, my girlfriend, I was, no I still am the guy...' Onyx says, and then groans in confusion, 'Sorry, this whole situation is just messing with my head, if I end up stuck here much longer, I[apostrophe]ll probably end up giving in and being just another sexy little equine fucktoy for all those handsome stallions out there... gah no that's not right.' He sighs with exasperation, before shrugging slightly at you, 'See what I mean? I don[apostrophe]t suppose you could help me get out of this damn cage somehow could you? They say they will only let me out when I am ready to be a proper horse like the rest of them, though from the looks of things that won[apostrophe]t take too much longer.' Onyx says as he rubs one of his hands along the side of his still forming muzzle with worry, before addressing you again. 'Please won[apostrophe]t you give me a hand here? I know that several of the guards have keys to the cells in this area, you just need to find one of the ones on patrol and find a way to get the key from them.' He asks hopefully, as he looks at you plaintively 'Hopefully before I finish changing, and can still remember that I am a … um, student of... something? I think I remember classes somewhere, that's where we were hiding when they caught us anyways...' Onyx[apostrophe]s voice trails off as he seems to try to recall something, after several minutes of him staring into the distance, you decide to continue on your way, wondering if you should find the key to free the changing boy, or if he is already too far gone to save.";
		increase Onyxtalk by 1;
		now Onyxkeys is 1;
		stop the action;
	if onyxquest is 2:
		say "'Hey thanks again for your help,' The mostly changed equine teenager says with a soft smile as you approach him, 'I know I am going to keep changing, but at least I[apostrophe]m here with you instead of trapped with those crazies back at the stables.' He says with a soft smile, before sighing slightly. 'I still wish I knew how to fit in properly though now, everything is just so confusing, and I still am not sure if I am going to end up a stallion or a mare when all this is over with...' Onyx says with a sigh, before giving you a shy grin and a shrug, 'Heck I don[apostrophe]t even feel sure about which one I want to end up as.  Both ideas seem so sexy and appealing to me sometimes...' He looks off into the distance with a smile on his face for a second, before shrugging and poking at the books in front of him again. Looking at the books yourself, you find yourself grinning as you note he has all sorts of books about horses spread out in front of him, with pictures of both mares and stallions spread out on the table. Glancing up at your new equine acquaintance you find yourself wondering if maybe you can[apostrophe]t find something, or someone out there, to help you finish transforming him into either a sexy stud, or a slutty mare for you to play with..";
		stop the action;
	if onyxquest is 5:
		say "[one of]'Hello again master!'[or]'I feel like such a sexy slut now![or]'I wonder if Daisy will like my new look?[or]'Mmmmm stallions....'[or]'I love being a mare! Please let me thank you properly for making me so nice and slutty!'[or]'Can you believe I actually thought I wanted to be a stallion at one point? What would I ever do without this wonderfully sensitive pussy of mine?'[or]'Oh master, the stables are such a wonderful place for a mare, just think of all that lovely thick stallion meat just waiting to fill a mare up!'[at random]";
	if onyxquest is 6:
		say "[one of]'Hey there again sexy, feel like another go?'[or]'Want to feel a real stallion again?'[or]'You should stay here more often...'[or]'Stable life suits me don[apostrophe]t you think?'[or]'I feel so much better now, I can[apostrophe]t even imagine why I was worried about this.'[or]'Know anyone interested in playing the mare for me?' he says teasingly.[or]'Those stallions were right, this feels amazing.'[or]'You will look so sexy walking around on hooves I think.'[or]'Ready to be my mare yet? You know it will be amazingly good.'[or]'I wonder if Daisy will like my new body?' Onyx says with a lascivious grin.[at random]";
	if onyxtalk is 4:
		say "'[one of]Hey again handsome, welcome back.'[or]'You look like you would make a fine horsey too!'[or]'It[apostrophe]s so good not to have to worry about having forgotten something anymore.'[or]I stopped worrying about remembering anything other than how to be a good horsie now, it wasn[apostrophe]t important anyways after all.'[or]He neighs at you happily,a smile on his muzzle as he looks around the hallway.[or]I think I could get the hang of this being a horse thing if I could only figure out whether I was supposed to be a stallion or a mare...'[or]You haven[apostrophe]t seen a stallion around here have you? They usually come by here pretty often, and I think they might like to meet you.'[or]So did you want to have some fun yet?'[at random]";
	if Onyxkeys is 5:
		say "'Oh hey it[apostrophe]s you again!' Onyx says happily as you approach the changing equine again where he leans up against the wall. 'A couple stallions came by while you were gone, and they seemed surprised about me being out for some reason.' He says with a shrug, as he rubs his forehead with one of his changing hands absently, and you note that his changes seem to be continuing to progress though somewhat more slowly than before. 'Anyways, they stopped to talk, but they just left a bit ago... and now you show up!' He says with a rather equine smile as he grins at you happily, 'Did you figure out what I was supposed to be doing? I[apostrophe]m still pretty confused by everything going on here...' Onyx asks you hopefully, and you find yourself smiling as well as you nod at the changing equine.[line break]";
		say "Onyx listens raptly while you explain that his companion says he should stay and be a good little horsey just like she is, and stay in the stables so he can eventually keep her company. Onyx seems to smile even broader than before as you slowly relate all the information you learned, and when you finish he nods happily. 'So the important thing I need to do is stay here and be the best horse I can be! That sounds a lot like what the stallions said to, and if so many different important people agree that Onyx should be a good horse, then I[apostrophe]ll do my best to be the best horse around!' He says happily as he shifts his weight slightly onto his almost fully formed hooves, 'And maybe you can help me and become a good little horsey too!' Onyx says with a smile as he looks right at you teasingly, and you get the feeling that maybe now you could have some 'fun' with the still changing horsey if you wanted to...";
		now onyxtalk is 4;
		stop the action;
	if onyxkeys is 4 and onyxquest < 2:
		say "'Welcome back again,' The still changing horseboy says with a smile on his changing muzzle as he lifts a hand in greeting. 'You know some stallions just came by to talk to me while you were gone, and they seemed surprised I got out, they said I had some potential or something.' He says with a slight smile at the thought of the stallions, before shaking his head and rubbing his forehead with his changing hands, 'Something still doesn[apostrophe]t seem quite right though...' He says with a sad and confused sigh.  His expression brightens however as you pull out the intricate silver necklace you went to all the trouble of finding. 'This... looks so familiar,' he mutters as you hand it to him and he runs the necklace over through his hands absently, before stopping to read the inscription on the back several times, his equine lips moving slightly as he mutters softly to himself, before blinking and looking at you.[line break]";
		say "'Now I remember, we were captured.. and they brought us here to make us like them..' Onyx says with a slightly panicked look on his partially formed muzzle, 'And I can[apostrophe]t believe I almost forgot that and gave up, but what about Diana, did you find out what happened to her?' He asks nervously, as if afraid to hear the answer.  His shoulders slump slightly when you explain that his girlfriend is now well on her way to being a happy slutty mare like all the rest, though he does perk up slightly when you tell him she said he should escape with you if he could. He seems ready to go rushing to her rescue for a minute, before sighing and giving up when you explain just how many mares there are in the area with her.  Sighing Onyx admits that he is pretty sure that he can[apostrophe]t actually bring himself to fight any of the more dominant equines right now, and with some persuasion agrees to follow you out of the stables.  It takes a bit of work for you to distract the two guards outside, but you manage to keep their attention long enough for Onyx to slip out unnoticed.  Once free of the stables, you lead your new and slightly unhappy new equine companion back to the safest place you know if in this crazy city, breathing a soft sigh of relief as the library comes into sight and you can both rest and relax for a bit.";
		now onyxquest is 2;
		now Onyx is in Grey Abbey Library;
		move player to Grey Abbey Library;
		stop the action;
	if Onyxtalk is 2:[freed onyx short messages]
		say "'[one of]Hey again, welcome back.'[or]'You look familiar, are you going to be a horse too?'[or]'I know I was supposed to be doing something... something important... but what could be more important then being a proper horse?'[or]I think I was in something called college, though for some reason all I get when I try thinking more about it, is a vague sense of boredom... maybe it was so boring I don[apostrophe]t want to remember it?'[or]He neighs at you happily,a smile on his muzzle as he looks around the hallway.[or]I think I could get the hang of this being a horse thing if I could only figure out whether I was supposed to be a stallion or a mare...'[or]You haven[apostrophe]t seen a stallion around here have you? They usually come by here pretty often, and I need to ask them what I was supposed to be doing...'[or]Dammit, I just can[apostrophe]t remember what I was supposed to be doing, do you know?'[at random]";
		stop the action;
	if Onyxkeys is 2:
		say "'Hey welcome back,' Onyx says with a smile on his increasingly equine face as he moves over to the bars again, standing much more easily on his changing feet as he does so. You take a minute to look at the boy and notice his transformation seems to have progressed farther, and he is almost more horselike than he is human now. 'Did you find the keys?' The equine like boy asks eagerly, and you wonder whether you should actually set him free or not, still unsure, you hold up the keys where he can see them, and he claps his hands together happily as he looks at you. 'I knew you could do it!' He says happily, watching with his large equine eyes as you unlatch the cell door and swing it open carefully.  Onyx grins as he staggers out of the room, seeming disoriented for a minute as he looks around himself.[line break]";
		say "'I[apostrophe]m free!' He says happily as he looks around himself, before blinking, 'I am finally out of that little cell... this means... I am finally a good little horsy?' He says with some confusion, as he looks at you for help. 'I know I had to be out of there for some reason, but they said I could come out when I was a proper horse, so does this mean I am a proper horse now?' Onyx says as he rubs his head with his hands, obviously having trouble thinking straight right now, 'I think maybe I should just stay here for for a minute and try to think, there was a boy I was supposed to rescue, or was it a girl? Someone else here... Maybe you could help me find out what it is I was supposed to do?' Onyx says hopefully as he looks back up at you again, 'It[apostrophe]s just so hard to think about what happened before I ended up here...  but I know it was important somehow... though I am not sure if it is as important as being a good little filly is...' He says with a confused sigh as he moves over to rest against one of the walls. Looking at him like this, you are pretty sure that he could be pretty easy to manipulate if you could just figure out how to do so, which is probably what the horses here were counting on. Sighing you resolve to look around to see what else you can find in this place to help get him moving again, you do recall he keeps mentioning someone else brought in at the same time he was... maybe you should try finding them. Although you get the feeling that you probably shouldn[apostrophe]t leave him alone for too long in this strange place as he is now.";
		now Onyxtalk is 2;
		now onyxquest is 1;
		stop the action;
	if Onyxtalk is 1:[Normal short messages the npc will say each time you talk to them]
		say "[one of]'Hey again, made any progress so far on those keys?'[or]'I know I had a name.. and I think it began with an... O? Maybe it was Onyx? No wait, that's my current name...'[or]He whikers at you slightly, then seems embarrassed when he realizes what he did.[or]'Come to visit the prisoner again? You aren[apostrophe]t the only one who likes to come look, plenty of the mares come by to tell me how much fun I can look forward too, and the men... well lets just not talk about what they talk about doing to me' Onyx says, and you notice him starting to blush.[or]'You should be careful hanging around talking to me like this, some of the horses come by here pretty often to keep an eye on me. You wouldn[apostrophe]t want to end up in a cell next to mine now would you?'[or]'Why are you hanging around here talking to me so much? If you want to know what it is like in here, just lock yourself in one of the other cells why don[apostrophe]t you, then you can find out what it is like to be a captive while they teach you about being a proper little horse. [or]'This is getting to me, I keep thinking about how much fun it would be to be a big dumb horse... or better yet, be fucked by one...'[or]'I wonder if there is any way to reverse the changes at this point, or if I am going to end up a horse even if I get out of here...'[at random]";



Onyxmareslut is a number that varies.


Instead of fucking the Onyx:
	if lastOnyxfucked - turns is less than 6:
		say "'Sorry there friend,' Onyx says with a sad shake of their equine head, 'I need a bit more time to recover after our last romp, maybe you could come back then?' The transformed equine says with a teasing look as they go back to what they were doing..";
		stop the action;
	if Onyxmareslut is 2:
		if cunts of player is greater than 0:
			say "'Ah I knew my slut would return to her stallion soon enough, you just can[apostrophe]t help but lust after my rod now can you?' Onyx says with a smirk on his horselike muzzle as he reaches out and strokes your body with his hand teasingly, making you moan almost automatically as your well trained body responds submissively to his touch. 'Now it[apostrophe]s time for the real fun though isn[apostrophe]t it slut?' he says teasingly as he rubs your already damp pussy with his powerful hands, making you moan with desire at your stallions touch, the scent of his heady musk filling your head, and reminding you of just how good it feels to submit and let him have his way with you. Your head swimming with lust, you pant eagerly as he slowly pulls you into the room he was standing in front of, and pushes you down onto the bed. Your thoughts already filling with images of the handsome black stallion fucking your increasingly eager body, you spread yourself for him eagerly as he climbs up onto the bed on top of you,  his hands gathering yours up and pinning them above your head as his thick black and pink rod rubs up against your thighs. 'What a good little slutty mare you make, you want my cock so bad don[apostrophe]t you little mare?' He says teasingly as he shifts his weight above you, and you find yourself moaning and nodding eagerly, your damp pussy feeling horribly empty and needy as you stare down at his amazingly sexy stallionhood.[line break]";
			say "'Good mare, time for you to get it in you then,' He says with a chuckle as he lowers his hands down to your hips and positions his cocktip at the entrance to your female passage. You moan and try to lower your hands to grip him to you tighter, only to find that while you were distracted he managed to fasten the beds restraints to your hands, keeping them locked above you. Somehow being unable to move your hands seems strangely erotic with a powerful stallion positioned right above you, your body completely at the mercy of his hands and cock as he chuckles and thrusts his wonderful rod right into you.  You find yourself letting out a loud whinny of lust and need as his thick meat presses into your body, spreading you wide around him as he begins to thrust into you with increasing force, your needy passage gripping and massaging Onyx[apostrophe]s meat with every thrust, as increasingly powerful bursts of pleasure shoot through your body. Before long you are moaning like a proper mare under the powerful stallions attentions, begging him to fill your needy body with his seed and show you what it feels like to be a mare. Onyx needs little encouragement to do just that, and the black stallion easily fulfills his duties as a stud as he pounds into your body, before giving one last powerful thrust into you as his cock stiffens and fills your waiting womb with his seed, causing you to orgasm harder then ever before as you feel his fertile sperm floating around inside your body.[line break]";
			say "As you lie there with your mind floating blissfully free, you can dimly sense your amazing stallion pulling out of your body, and doing something with your still spread legs, though you find it hard to care about anything like that when you feel so very amazing right now.  You do look up however when you hear Onyx[apostrophe]s hooves clopping slightly on the floor as he leaves the small room, your needy body already missing a stallions touch. Onyx grins as he looks back and sees you watching him, and you feel your heart jump slightly as he brandishes a familiar ring of keys, right before he slides the door to the cell you are in shut. Panic chasing away some of the pleasure of your recent mating, you try to struggle and sit up, only to realize that now not only are your hands bound, but he locked some sort of cuffs on your legs as well, completely trapping you spread-eagled on the bed.  'No getting away for you this time,' Onyx chuckles with amusement as you stare at the sexy stallion in shock. 'See the stallions deal was, I could stay a stallion as long as I found a mare to take my place here at the stables... and well then you came along. Don[apostrophe]t worry though, from what i[apostrophe]ve seen so far, you will love being a proper mare, once your training is done anyways.' He says with a chuckle as he walks away from the door taking all your equipment and the keys with him, and the worst part of it is, you aren[apostrophe]t even sure if you want to call him back and make him let you go, or call him back and have him fuck your needy body again! Either way though, it looks like you will be staying here a while...";
			now Onyxmareslut is 3;
			now humanity of player is 0;
			now body of player is "";
			now bodyname of player is "equine";
			now scalevalue of player is 3;
			now bodydesc of player is "sultry";
			now bodytype of player is "[one of]equine[or]horse-like[at random]";
			now the daycycle of player is 0;
			follow the turnpass rule;	
		otherwise:
			say "'Back again? And still not even the slightest bit mare-like? Maybe you should go try hanging out in the mares quarters a bit more, have some food and relax.' The powerful black stallion says teasingly, 'And come back and talk to me again when you are a bit more like a sexy mare.' Onyx says with a teasing stroke of his thick cock, before waving you on your way.";
			infect "Mareslut";
			stop the action;
	if Onyxmareslut is 1:
		if cunts of player is greater than 0:
			say "'I knew you would be back soon,' Onyx says with a teasing grin as the new and powerful stallion stretches his black furred form teasingly, the sight of his body and the scent of an aroused stallion making your own body respond automatically.  You moan as Onyx draws closer to you, your pussy clenching with desire as your body heats up at his soft touch, You swear you can see the increasingly dominant seeming stallion grin as he pushes you into one of the open rooms, his powerful body pressed against yours as he guides you over to the bed, before pushing you down on your back.  You barely have time to think before the large equine male is on top of you, his form pressing you down underneath him, even as his thick equine cock rubs up between your legs. Helpless to resist the large equine on top of you, either physically or emotionally, you surrender to the moment and the sensations of being pinned underneath the large male, while the blunt tip of his cock strokes the outside of your feminine lips teasingly. You moan in need as he continues to tease you for several minutes with his soft equine lips and hands, and teasing strokes of his equine stallionhood, even as your body burns with increasingly equine heat, your empty slit begging to be filled by the strong powerful male above you. Eventually Onyx grins and you realize you have started begging him out loud for him to fill you, you have little time to think about it however, as the large black stud grunts and buries his thick rod inside of you. The feeling of his warm equine rod filling you up is amazing, and you melt in the stallions arms as he continues to thrust himself into you, feeling increasingly submissive and helpless as the powerful male thrusts into your body. As you clutch Onyx close you find his presence makes you feel increasingly safe and sexy, like you were meant to be a slutty little mare for this powerful stallion, to have him hold you, fuck you, and make you his forever. You groan with pleasure as images of playing the mare for your stallion fill your head, though soon you groan for another reason, as your body explodes with pleasure as the powerful black stud above you lets out a loud whinny, and you feel his thick seed fill your body.  You lie there limply as the pleasure washes through you, his cock twitching inside you and filling you up as he kisses and nibbles at your neck teasingly with his equine lips, before pulling himself off of you. Hauling yourself up, you barely manage to stagger out into the hallway after Onyx as he saunters out, the black equine giving you an amused grin as you realize your thighs are still coated in his seed, the realization making you blush, but feeling surprisingly good as well, and as Onyx gives you a knowing wink, you realize you will be back to visit your new found stud again soon enough...[impregchance]";
			infect "Mareslut";
			now lastonyxfucked is turns;
			if a random chance of 1 in 3 succeeds:
				now Onyxmareslut is 2;
			stop the action;
		otherwise:
			say "'Back again? And still not even the slightest bit mare-like? Maybe you should go try hanging out in the mares quarters a bit more, have some food and relax.' The powerful black stallion says teasingly, 'And come back and talk to me again when you are a bit more like a sexy mare.' Onyx says with a teasing stroke of his thick cock, before waving you on your way.";
			infect "Mareslut";
			stop the action;
	if onyxquest is 5:
		if cocks of player is greater than 0:
			say "Onyx smiles happily and whinnies in greeting as you approach, seemingly unable to speak as she stares with desire at your erect [cock of player] rod.  Her obvious need making you grin as she runs her hands over her sleek black mare's body, already anticipating the fun to come as she leans back against the wall with her legs widely spread for you.  Her submissive actions make you feel increasingly powerful and dominant as you pin her to the wall, your stiff cock already probing at her damp passage even as she moans happily underneath you.  You waste no time in burying yourself inside her new pussy, enjoying every submissive squeak and whinny of pleasure as you pound into her amazingly soft and sensual pussy.  Soon you are gripping the little mareslut's hips tightly as she wraps her legs around you, her soft thighs pressing up against your body as you continue to fuck her needy body properly.  It isn[apostrophe]t long though before her amazing passage has you crying out with pleasure as your body stiffens and you shoot your load into her waiting womb.  Your new mare squeals with happiness as she shudders with orgasm as well as she receives your seed.  Her needy pussy milks your cock of every last drop of cum as you hold her tight.  Eventually though, you are both spent and unable to cum any more, and you reluctantly let your fun new plaything slump to the ground against the wall again, while you gather your stuff up and try to recover from your exertions.  Glancing back at the happy and slutty little mare though, you make a note to come back here again once you have recovered, to give your newest mare another lovely taste of the meat she seems to like so much...";
			now lastonyxfucked is turns;
			infect "Horseman";
			stop the action;
		otherwise:
			say "Onyx squeals happily, seemingly unable to speak with excitement as you stroke your hands over her new sensitive black body, and you can smell her intense arousal as she rubs her new form up against you teasingly.  Her submissive actions making you feel increasingly dominant as well as horny, and you can feel yourself smirking with amusement as you decide to put the slutty mares new equine muzzle to good use.  She seems mildly surprised at first as you push her down to her knees in front of you, only to grin happily as she scents your female arousal, eagerly burying her equine muzzle in your crotch like a good little sexpet.  You moan with pleasure at the feel of her velvety equine muzzle nuzzling at your damp feminine sex, her soft lips rubbing over your lips teasingly, as you bury your hands in her soft short mane.  Onyx doesn[apostrophe]t tease you with her soft touches for long though, being just as eager to please her new mistress as you are to play with this new sexy pet you made. You gasp happily as her flexible equine tongue probes your damp folds, her teasing licks are tentative at first, but soon she is lapping at your sex eagerly, the pleasure growing and building with every amazing pass of that soft equine tongue. Before you know it you are rewarding the slutty mare with a gush of your juices as you cry out in orgasm, coating her muzzle and making her moan happily underneath you as she does her best to lick every drop of your wonderful flavor up. Eventually you gather your wits about you and step back slightly, though Onyx stays there on her hands and knees looking up at you with a happy expression on her muzzle as she smiles at you. You find yourself grinning slightly at the erotic sight as you gather your equipment up, before preparing to continue your journey, leaving the slutty new mare there on her knees behind you like a good little pet...";
			infect "Horseman";
			stop the action;
	if onyxquest is 2:
		say "'Sorry friend,' Onyx says with a shy smile as he moves the pictures of horses around in front of him. 'But I haven[apostrophe]t yet figured out what I should be yet, and I figure actually giving in and having sex would kind of make the decision for me... so I think I should pass for now..' He says with a sigh as he goes back to looking at the pictures, and you wonder if maybe there isn[apostrophe]t something out there in the city you could find which would help him make the choice you want him to... perhaps in the red light district or one of the clubs in town...";
	if onyxquest is 0:
		say "'Great, another person teasing me with sex while I am stuck behind bars.' Onyx says with a sigh, 'Sorry but until I get out of here, the only sex I am getting is with my hoof, I mean hand.' He says before blushing slightly. 'I suppose that is another good reason to get me out of here, cause damn I am getting horny in here....'";
	if onyxtalk is 4:
		say "'Oh hey, you want to have some fun with me?' Onyx says with a smile as you approach the changing equine with obvious sexual intent. 'Of course if I am going to be sexy little horse I need to have lots and lots of sex, and you should too so you can be just as sexy a horse as me...' The black equine says with a teasing smile as he draws closer to you, rubbing his softly furred equine body up against your own teasingly, his scent seeming increasingly arousing as the transforming male pulls you close and whispers in your ear. 'Why don[apostrophe]t I show you some of the tricks the stallions told me about, and teach you how much fun it is to be saddled up and ridden?' He says teasingly, while his arousing scent makes your head swim with desire, and your body warms up in response to his touch. Do you give in to your building desires and the increasingly arousing touch of the horseboy?'";
		if player consents:
			say "You find yourself nodding almost automatically in response to Onyx[apostrophe]s surprisingly forceful words, though you don[apostrophe]t have much time to think about that as Onyx grins happily at your surrender, and quickly presses your unresisting body up against the wall of the hallway.";
			if cocks of player is greater than 0:
				if cunts of player is greater than 0:
					say "'Good slut,' you hear Onyx mutter into your ear as he runs his hands over your body teasingly, his large equine fingers brushing your cock lightly, before finding your already damp cunt underneath.  'Looks like you don[apostrophe]t really need that pathetic little man meat of yours now do you... what you need is a real stallions meat in you isn[apostrophe]t it?' Onyx says teasingly, as he rubs your damp passage, his touch making you whimper with desire even as you arch your body forward at his touch. 'A nice thick stallionhood like this.' He says, as he pushes your head down until his thick blunt equine cock is right in front of your face, one hand still holding your hands pinned, while his other strokes his surprisingly large changed cock teasingly. Your attention is quickly focused on his large equine member, even as the aroused musk of the dominant stallion fills your mind, your body responding almost automatically like a good little mares as your cock shrinks and your female sex burns with desire. Your eyes fixed on his hooftipped hand as it strokes over his sexy and powerful rod, which now shows no sign of the shrinking you noticed earlier, indeed it seems to have grown drastically, and is still growing to be on par with that of any of the stallions wandering the halls!  You find yourself panting with arousal at every sexy pump of his hand up that thick meat, and if you weren[']t so helpless and restrained you think you wouldn[apostrophe]t be able to keep your hands from stroking the sexy equine meat in front of you as well. Soon enough though, Onyx grunts loudly above you, and the tip of his equine member erupts, spilling his thick stallionseed all over your helpless form.  You moan with increased arousal and find yourself feeling increasingly needy and surprisingly happy to be covered in the cum of a powerful equine, the feel of it sinking into your skin and changing you is absolutely amazing, and somehow being held in place by the powerful stallion while it happens just makes everything better as well. Eventually he lets you go, and when you look up at the stallion that dominated you so easily, you are somewhat surprised to see that his changes have finished completely, and a powerful black stallion stands where the weak slutboi once stood, the sight of his large proud equine form making you feel even more submissive and horny just by looking at him.";
					infect "Mareslut";
					infect "Mareslut";
					now Onyxmareslut is 1;
					now onyxquest is 6;
					now lastonyxfucked is turns;
					if fancyquest is greater than 0:
						stop the action;
					otherwise:
						now fancyaroused is 1;
						stop the action;
				otherwise:
					say "'That's a good slut,' Onyx says teasingly as he presses you up against the wall, his body rubbing up against your own form teasingly, and you can practically feel his cock growing with arousal even as yours seems to shrink under the assault of the surprisingly dominant male. Seeming to notice your reaction, the large black equine gives you a rather amused grin, even as he pins you down even more securely and begins to stroke his increasingly equine cock with his hand. 'You won[apostrophe]t be needing that little thing for much longer, not when you can have a big thick equine cock like mine in you now will you?' He says teasingly, his words making you moan even as your attention is drawn down to his large blunt tipped equine member, which now shows no sign of the shrinking you thought you saw earlier, indeed it seems to have grown to be almost on par with the members of many of the horsemen wandering the stables! Noting your fascination with his thick cock, he shoves you down the wall slightly, so that the tip is almost poking you in the face as he continues to stroke his member with increasing vigor.  You find yourself panting with arousal at every sexy pump of his hand up that thick meat, and if you weren[']t so helpless and restrained you think you wouldn[apostrophe]t be able to keep your hands from stroking the sexy equine meat in front of you as well. Soon enough though, Onyx grunts loudly above you, and the tip of his equine member erupts, spilling his thick stallionseed all over your helpless form.  You moan with increased arousal and find yourself feeling increasingly needy and surprisingly happy covered in the cum of a powerful equine, the feel of it sinking into your skin and changing you is absolutely amazing, and somehow being held in place by the powerful stallion while it happens just makes everything better as well. Eventually he lets you go, and when you look up at the stallion that dominated you so easily, you are somewhat surprised to see that his changes have finished completely, and a powerful black stallion stands where the weak slutboi once stood, the sight of his large proud equine form making you feel even more submissive and horny just by looking at him.";
					infect "Mareslut";
					infect "Mareslut";
					now Onyxmareslut is 1;
					now onyxquest is 6;
					now lastonyxfucked is turns;
					if fancyquest is greater than 0:
						stop the action;
					otherwise:
						now fancyaroused is 1;
						stop the action;
			otherwise:
				say "'Good slut,' you hear Onyx mutter into your ear as he runs his hands over your body teasingly, his large equine fingers stroking your body, before venturing down to your already damp and needy pussy.  'Looks your already wet and ready for me, just like a good little mareslut should be... what your body needs is a real stallions meat in you isn[apostrophe]t it?' Onyx says teasingly, as he rubs your damp passage, his touch making you whimper with desire even as you arch your body forward at his touch, unable to deny his statement as your body responds to your increasingly stallionlike captor. 'A nice thick stallionhood like this.' He says, as he pushes your head down until his thick blunt equine cock is right in front of your face, one hand still holding your hands pinned, while his other strokes his surprisingly large changed cock teasingly. Your attention is quickly focused on his large equine member, even as the aroused musk of the dominant stallion fills your mind, your body responding almost automatically like a good little mares as your sex burns with desire, your body aching to be split open by his thick equine rod. Your eyes fixed on his hooftipped hand as it strokes over his sexy and powerful rod, which now shows no sign of the shrinking you noticed earlier, indeed it seems to have grown drastically, and is still growing to be on par with that of any of the stallions wandering the halls!  You find yourself panting with arousal at every sexy pump of his hand up that thick meat, and if you weren[']t so helpless and restrained you think you wouldn[apostrophe]t be able to keep your hands from stroking the sexy equine meat in front of you as well. Soon enough though, Onyx grunts loudly above you, and the tip of his equine member erupts, spilling his thick stallionseed all over your helpless form.  You moan with increased arousal and find yourself feeling increasingly needy and surprisingly happy to be covered in the cum of a powerful equine, the feel of it sinking into your skin and changing you is absolutely amazing, and somehow being held in place by the powerful stallion while it happens just makes everything better as well. Eventually he lets you go, and when you look up at the stallion that dominated you so easily, you are somewhat surprised to see that his changes have finished completely, and a powerful black stallion stands where the weak slutboi once stood, the sight of his large proud equine form making you feel even more submissive and horny just by looking at him.";
				infect "Mareslut";
				infect "Mareslut";
				now Onyxmareslut is 1;
				now onyxquest is 6;
				now lastonyxfucked is turns;
				if fancyquest is greater than 0:
					stop the action;
				otherwise:
					now fancyaroused is 1;
					stop the action;
		otherwise:
			if cocks of player is greater than 0:
				say "You shake your head slightly to clear it as you push the surprised Onyx back up against the wall, the changing equine surprised and helpless to react as you take charge of the situation. Onyx moans helplessly as your hands roam his already aroused and needy body teasingly, your cock growing increasingly excited as you stroke his soft black fur, even as his cock seems to shrink and vanish as you watch. As your hands rub over his almost completely flat crotch, you can feel his skin part under your touch and a small gush of wetness soaks his panties as a new feminine slit forms, even as her chest begins to swell slightly with newly budding breasts. You can feel yourself grinning eagerly as the new mares heat filled scent fills your head, the new mare moaning with arousal as she responds to your dominant touch with increasing submissiveness, the instincts of a mare in heat obviously already taking over as his body continues to change under your sexual assault.  The sight of Onyx becoming a proper mare only serves to excite you and increase your arousal amazingly, your stiff [cock of player] cock rubbing up against her soft body even as one of your hands slowly tugs her soaked thong out of the way, exposing her lovely winking maresex for the first time.[line break]";
				say "You find yourself groaning with pleasure as you position yourself, before thrusting into the stables newest black mare, filling her tight pussy up with your rod for the first time. She moans and throws her head back submissively, and you can see her muzzle shifting and becoming fully equine even as you pull back and thrust into her again, slowly building up a rhythm as she clutches you tightly to her body and whinnys with need. The feel of her velvety folds massaging your cock, and her now ample breasts rubbing up against your body is just too amazing, and before long you are crying out with pleasure yourself as you fill her eager body with your seed, sealing her fate as just another lusty little mareslut. Groaning as you try to recover from your orgasm, you pull yourself out of her sex, and let her slump down the wall with a happy and rather dazed look on her new fully equine muzzle, her hands roaming her new sexual body even as you gather up your equipment and prepare to head on about your business. Though the sight of her well fucked body leaning up against the wall does make you grin with amusement as you recover from your own powerful orgasm, quite glad you could show the former teenager the joys of being a proper mare like all the rest...";
				Now onyxquest is 5;
				now lastonyxfucked is turns;
				if fancyquest is greater than 0:
					stop the action;
				otherwise:
					now fancyaroused is 1;
					stop the action;
				stop the action;			
			otherwise:
				say "You shake your head slightly to clear it as you push the surprised Onyx back up against the wall, the changing equine seemingly surprised as you take charge of the situation.  He moans slightly as your hands roam his body teasingly, your touch lingering on his almost flat crotch and his slightly swelling chest even as you rub your already aroused body against the new equines increasingly sexy form.  You can feel yourself grinning as the unsure equine begins to moan with arousal and respond to your dominant touch with increasing submissiveness, his instincts obviously taking over as his body begins to change under your sexual assault.  He moans helplessly as he clutches you tight, the slight swellings on his chest blossoming forth into fully formed breasts under your hands, even as you can feel his already diminutive manhood shrink and vanish into his body. For some reason the feeling of Onyx becoming a mare under your touch only increases your arousal, your own pussy dampening with need as you rub your crotch against that of the stables newest black mare. She moans and throws her head back submissively, and you can see her muzzle shifting and becoming fully equine even as you slip one of your fingers inside her newly formed pussy and begin to massage her velvety soft new mound teasingly. 'Now that[apostrophe]s a good looking mare,' you find yourself whispering to the changing mare as her eyes drift closed and she gives herself over to the pleasure of your touch, your arousal growing even harder to contain as you rub your heat filled body up against the newly formed mares sexy black form. [line break]";
				say "Before long you are moaning almost as hard as Onyx is, as her hands begin to wander your form as well, as she gives herself over to the submissive desires of her new body completely, and you shudder with pleasure as she cries whinnys in pleasure as her first female orgasm wracks her body.  The pleasure of taming the sexy mare, and the feel of her body shuddering helplessly against yours, is too much to contain, and you gasp in orgasm as well, pleasure shooting through your body even as the new female Onyx[apostrophe]s form slips down the wall limply, with a dazed look in her fully equine new eyes. You find yourself feeling increasingly powerful and dominant as you look down on where Onyx is panting breathlessly against the wall, even as her new hooftipped hands roam her changed body happily. Feeling strangely satisfied with your work here, you gather your wits about you as you prepare to head out to continue roaming the stables, although you do find yourself thinking that maybe you should come back to visit your own personal pet mare again as soon as she has recovered....";
				Now onyxquest is 5;
				now lastonyxfucked is turns;
				if fancyquest is greater than 0:
					stop the action;
				otherwise:
					now fancyaroused is 1;
					stop the action;
				stop the action;
	if onyxquest is 1:
		say "'Sex?' Onyx says with some confusion, before giving you an equine smile. 'I think I would love some, cause damn I am soooo fucking horny,' He says as he reaches down to rub his small crotch absentmindedly. 'But I think if we do that, I won[apostrophe]t be able to remember anything else, and I know there was something I had to do... or was it someone that had to do me?' The equine says, before shaking his head at the puzzling situation. 'Maybe we should wait till we figure out what we are going to do first, then we can have some hot heavy sex.... lots and lots of hot and heavy sex...";










when play ends:
	if Onyxmareslut is 3:
		say "Your time at the stables has been surprisingly pleasant, once you stopped fighting your purpose and your captivity, you came to really enjoy being bound and helpless for all the stallions to use. And use you they did! You had many visitors at first from among the stallions, though your favorite was the big black stallion who captured you in the first place. It wasn[apostrophe]t long before you begin responding to your new name, 'Obsidian', and loving your equally sexy new black furred mares body, and once the training was over and you are finally released from the training stall, you make sure to thank Onyx very personally for his help in making you such a sexy little mare. So much so that he had trouble walking for several days afterwards, much to the amusement of his fellow stallions.  Eventually though you settle down to your new life as a rather powerful and sexy mareslut, and with your enhanced submissiveness you find you have a real strong client base among those who like to dominate their partners and tie them up.  Of course eventually you are shifted over to work with some of the breeding mares more often, and you look back on that time fondly as you sit with your many black foals gathered around you and grin at just how many of them look like that handsome young stallion that still visits you often... and recall how glad you are that you convinced him to stay in the stables like a good horsey, and how glad you are that he did the same to you as well!";
		stop the action;














Onyx ends here.
